/* ****************************************************************************
 * $Revision:  $:
 * $Author: nasrullah dusenmahamad $:
 * $Date: 2018-07-11 $:
 * $HeadURL: $:
 * $Id: Manage Bank Branch Addresses - Spain - DFF.sql $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10503##RES##WLF_RESOURCE_DFF
-- DFF_ATTRIBUTES=RS_ATTRIBUTE,RS_ATTRIBUTE_NUMBER,RS_ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

--RSC_PREREQUISITE_OBJECTS=WLF_RESOURCES_TL
--RSC_PREREQUISITE_OBJECTS=WLF_RESOURCES_B

SELECT wlfRESOURCTLE0.NAME RES_TITLE
,wlfRESOURCE0.RS_ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,wlfRESOURCE0.RS_ATTRIBUTE1
,wlfRESOURCE0.RS_ATTRIBUTE2
,wlfRESOURCE0.RS_ATTRIBUTE3
,wlfRESOURCE0.RS_ATTRIBUTE4
,wlfRESOURCE0.RS_ATTRIBUTE5
,wlfRESOURCE0.RS_ATTRIBUTE6
,wlfRESOURCE0.RS_ATTRIBUTE7
,wlfRESOURCE0.RS_ATTRIBUTE8
,wlfRESOURCE0.RS_ATTRIBUTE9
,wlfRESOURCE0.RS_ATTRIBUTE10
,wlfRESOURCE0.RS_ATTRIBUTE11
,wlfRESOURCE0.RS_ATTRIBUTE12
,wlfRESOURCE0.RS_ATTRIBUTE13
,wlfRESOURCE0.RS_ATTRIBUTE14
,wlfRESOURCE0.RS_ATTRIBUTE15
,wlfRESOURCE0.RS_ATTRIBUTE16
,wlfRESOURCE0.RS_ATTRIBUTE17
,wlfRESOURCE0.RS_ATTRIBUTE18
,wlfRESOURCE0.RS_ATTRIBUTE19
,wlfRESOURCE0.RS_ATTRIBUTE20
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER1
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER2
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER3
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER4
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER5
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER6
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER7
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER8
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER9
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER10
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER11
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER12
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER13
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER14
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER15
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER16
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER17
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER18
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER19
,wlfRESOURCE0.RS_ATTRIBUTE_NUMBER20
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE1,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE1
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE2,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE2
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE3,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE3
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE4,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE4
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE5,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE5
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE6,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE6
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE7,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE7
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE8,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE8
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE9,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE9
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE10,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE10
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE11,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE11
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE12,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE12
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE13,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE13
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE14,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE14
,TO_CHAR(wlfRESOURCE0.RS_ATTRIBUTE_DATE15,'DD-Mon-YYYY') RS_ATTRIBUTE_DATE15

,wlfRESOURCE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,wlfRESOURCE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,wlfRESOURCE0.CREATED_BY  RSC_CREATED_BY
,wlfRESOURCE0.CREATION_DATE  RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM WLF_RESOURCES_B wlfRESOURCE0
,WLF_RESOURCES_TL wlfRESOURCTLE0

WHERE wlfRESOURCE0.RESOURCE_ID = wlfRESOURCTLE0.RESOURCE_ID
AND wlfRESOURCE0.RESOURCE_TYPE = 'ORA_TRNG_VENDOR'
AND wlfRESOURCTLE0.LANGUAGE = USERENV('LANG')
AND (wlfRESOURCE0.RS_ATTRIBUTE_CATEGORY IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE1 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE2 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE3 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE4 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE5 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE6 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE7 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE8 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE9 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE10 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE11 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE12 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE13 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE14 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE15 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE16 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE17 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE18 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE19 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE20 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER1 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER2 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER3 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER4 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER5 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER6 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER7 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER8 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER9 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER10 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER11 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER12 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER13 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER14 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER15 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER16 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER17 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER18 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER19 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_NUMBER20 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_DATE1 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_DATE2 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_DATE3 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE4 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE5 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE6 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE7 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE8 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE9 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_DATE10 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_DATE11 IS NOT NULL OR 
wlfRESOURCE0.RS_ATTRIBUTE_DATE12 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE13 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE14 IS NOT NULL OR
wlfRESOURCE0.RS_ATTRIBUTE_DATE15 IS NOT NULL 
)

