/* ****************************************************************************
* $Revision: 79143 $:
* $Author: tanawat.wongjan $:
* $Date: 2022-08-04 14:52:52 +0700 (Thu, 04 Aug 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Configure%20Seniority%20Dates%20-%20Seniority%20Date%20Rule%20List.sql $:
* $Id: Configure Seniority Dates - Seniority Date Rule List.sql 79143 2022-08-04 07:52:52Z tanawat.wongjan $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PER_SENIORITY_DATES_SETUP

SELECT DECODE(seniorityDatesE0.ACTIVE_FLAG,'Y','Yes','No') RES_ACTIVE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_SENIORITY_ITEMS'
    AND LOOKUP_CODE = seniorityDatesE0.SENIORITY_DATE_CODE
    ) RES_SENIORITY_RULE_NAME
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_TRIG_FIELDS'
    AND LOOKUP_CODE = seniorityDatesE0.TRIGGERING_FIELD
    ) RES_ATTRIBUTE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_SENIORITY_LEVELS'
    AND LOOKUP_CODE = seniorityDatesE0.LEVEL_CODE
    ) RES_LEVEL
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = seniorityDatesE0.FORMULA_ID
    ) RES_ADJUSTMENT_FORMULA
,DECODE(seniorityDatesE0.CUMULATIVE_FLAG,'Y','Yes','No') RES_CUMULATIVE
,DECODE(seniorityDatesE0.ALLOW_EDIT_FLAG,'Y','Yes','No') RES_ALLOW_EDIT
,DECODE(seniorityDatesE0.DISPLAY_IN_UI,'Y','Yes','No') RES_DISPLAY_IN_GUIDED_FLOWS
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_SENIORITY_SETUP_BASIS'
    AND LOOKUP_CODE = seniorityDatesE0.SETUP_SENIORITY_BASIS
    ) RES_OVERRIDE_SENIORITY_BASIS
,(CASE
    WHEN seniorityDatesE0.FORMULA_ID IS NOT NULL THEN
        'Yes'
    ELSE
        'No'
    END) RES_USE_FORMULA_FOR_HOURS_CONV
,seniorityDatesE0.HOURS_IN_DAY RES_HOURS_IN_A_DAY
,seniorityDatesE0.HOURS_IN_MONTH RES_HOURS_IN_A_MONTH
,seniorityDatesE0.HOURS_IN_YEAR RES_HOURS_IN_A_YEAR
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = seniorityDatesE0.CONVERSION_FF_ID
    ) RES_HOURS_CONVERSION_FORMULA
,DECODE(seniorityDatesE0.LABOUR_UNION_MEMBER_FLAG,'Y','Yes','No') RES_UNION_MEMBER
,seniorityDatesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,seniorityDatesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,seniorityDatesE0.CREATED_BY RSC_CREATED_BY
,seniorityDatesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,seniorityDatesE0.LEGISLATION_CODE RSC_COUNTRY_ID
FROM PER_SENIORITY_DATES_SETUP seniorityDatesE0
ORDER BY seniorityDatesE0.SENIORITY_DATE_CODE