/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Configure%20Default%20Benefits%20Relationships%20-%20Configure%20Default%20Benefits%20Relationships.sql $:
 * $Id: Configure Default Benefits Relationships - Configure Default Benefits Relationships.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT 'Reliance enterprises' RES_NAME
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = benBENEFITRELEO.PRODUCT_CD
	AND LOOKUP_TYPE = 'BEN_SYS_CODE' 
	AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_USAGE 
,(SELECT TERRITORY_SHORT_NAME
	FROM FND_TERRITORIES_VL
	WHERE TERRITORY_CODE = benBENEFITRELEO.LEGISLATION_CODE 
	) RES_COUNTRY
,(SELECT NAME
   FROM HR_ORGANIZATION_V
   WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
   AND CLASSIFICATION_CODE = 'HCM_LEMP'
   AND ORGANIZATION_ID =benBENEFITRELEO.LEGAL_ENTITY_ID) RES_LEGAL_ENTITY
,DECODE(benBENEFITRELEO.MULTI_ASSIGNMENT_FLAG,'Y','Yes','No') RES_ENABLE_MULTIPLE_ASSIGNMENT
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = benBENEFITRELEO.BENEFIT_RELATION_NAME
	AND LOOKUP_TYPE = 'BEN_BENEFIT_RELATION_NAME' 
	AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_DEFAULT_BENEFITS_RELATIONS
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = benBENEFITRELEO.ADD_ASGN_TREAT_CD
	AND LOOKUP_TYPE = 'BEN_REL_PATTERN' 
	AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_NEW_ASSIGNMENT_BEHAVIOR
,DECODE(benBENEFITRELEO.ADD_PRI_ASGN_TREAT_CD,'Y','Yes','No') RES_ADD_NEW_ASSIGNMENT_TO_PRIM
,TO_CHAR(benBENEFITRELEO.DATE_FROM,'DD-Mon-YYYY')  RES_FROM_DATE
,TO_CHAR(benBENEFITRELEO.DATE_TO,'DD-Mon-YYYY')  RES_TO_DATE
,benBENEFITRELEO.LAST_UPDATED_BY 			RSC_LAST_UPDATED_BY
,benBENEFITRELEO.LAST_UPDATE_DATE 			RSC_LAST_UPDATE_DATE
,benBENEFITRELEO.CREATED_BY 				RSC_CREATED_BY
,benBENEFITRELEO.CREATION_DATE 			RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benBENEFITRELEO.LEGISLATION_CODE RSC_COUNTRY_ID
FROM BEN_LEG_ENTITY_DEFAULTS benBENEFITRELEO
WHERE SYSDATE BETWEEN benBENEFITRELEO.DATE_FROM AND NVL(benBENEFITRELEO.DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))