/* ****************************************************************************
 * $Revision: 56649 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-07-12 11:20:44 +0700 (Tue, 12 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.12/branches/core/v2.2.0.0/reverse_sql/FINANCIALS/Currency%20Rates%20Manager%20-%20Rate%20Types.sql $:
 * $Id: Currency Rates Manager - Rate Types.sql 56649 2016-07-12 04:20:44Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- STRICTLY_BATCH_SEQ = RES_ACCOUNT_CONTACT_ROLE_RES_1

SELECT '' RES_BATCH_IDENTIFIER
,'' RES_INSERT_UPDATE_CODE
,'I' RES_INSERT_UPDATE_INDICATOR
,'CUSTOMER' RES_ACCOUNT_CONTACT_SOURCE_SYS
,HzCustAccountsE0.ACCOUNT_NUMBER RES_ACCOUNT_CONTACT_SOURCE_S_0
,'CUSTOMER' RES_ACCOUNT_CONTACT_ROLE_RESPO
,HzRoleResponsibilityE0.RESPONSIBILITY_ID RES_ACCOUNT_CONTACT_ROLE_RES_1
,HzRoleResponsibilityE0.RESPONSIBILITY_TYPE RES_RESPONSIBILITY_TYPE
,HzRoleResponsibilityE0.PRIMARY_FLAG RES_PRIMARY_INDICATOR
,HzRoleResponsibilityE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_CONTEXT_PROMP
,HzRoleResponsibilityE0.ATTRIBUTE1 RES_DESCRIPTIVE_FLEXFIELD_SEGM
,HzRoleResponsibilityE0.ATTRIBUTE2 RES_DESCRIPTIVE_FLEXFIELD_SE_2
,HzRoleResponsibilityE0.ATTRIBUTE3 RES_DESCRIPTIVE_FLEXFIELD_SE_3
,HzRoleResponsibilityE0.ATTRIBUTE4 RES_DESCRIPTIVE_FLEXFIELD_SE_4
,HzRoleResponsibilityE0.ATTRIBUTE5 RES_DESCRIPTIVE_FLEXFIELD_SE_5
,HzRoleResponsibilityE0.ATTRIBUTE6 RES_DESCRIPTIVE_FLEXFIELD_SE_6
,HzRoleResponsibilityE0.ATTRIBUTE7 RES_DESCRIPTIVE_FLEXFIELD_SE_7
,HzRoleResponsibilityE0.ATTRIBUTE8 RES_DESCRIPTIVE_FLEXFIELD_SE_8
,HzRoleResponsibilityE0.ATTRIBUTE9 RES_DESCRIPTIVE_FLEXFIELD_SE_9
,HzRoleResponsibilityE0.ATTRIBUTE10 RES_DESCRIPTIVE_FLEXFIELD_S_10
,HzRoleResponsibilityE0.ATTRIBUTE11 RES_DESCRIPTIVE_FLEXFIELD_S_11
,HzRoleResponsibilityE0.ATTRIBUTE12 RES_DESCRIPTIVE_FLEXFIELD_S_12
,HzRoleResponsibilityE0.ATTRIBUTE13 RES_DESCRIPTIVE_FLEXFIELD_S_13
,HzRoleResponsibilityE0.ATTRIBUTE14 RES_DESCRIPTIVE_FLEXFIELD_S_14
,HzRoleResponsibilityE0.ATTRIBUTE15 RES_DESCRIPTIVE_FLEXFIELD_S_15
,HzRoleResponsibilityE0.ATTRIBUTE16 RES_DESCRIPTIVE_FLEXFIELD_S_16
,HzRoleResponsibilityE0.ATTRIBUTE17 RES_DESCRIPTIVE_FLEXFIELD_S_17
,HzRoleResponsibilityE0.ATTRIBUTE18 RES_DESCRIPTIVE_FLEXFIELD_S_18
,HzRoleResponsibilityE0.ATTRIBUTE19 RES_DESCRIPTIVE_FLEXFIELD_S_19
,HzRoleResponsibilityE0.ATTRIBUTE20 RES_DESCRIPTIVE_FLEXFIELD_S_20
,HzRoleResponsibilityE0.ATTRIBUTE21 RES_DESCRIPTIVE_FLEXFIELD_S_21
,HzRoleResponsibilityE0.ATTRIBUTE22 RES_DESCRIPTIVE_FLEXFIELD_S_22
,HzRoleResponsibilityE0.ATTRIBUTE23 RES_DESCRIPTIVE_FLEXFIELD_S_23
,HzRoleResponsibilityE0.ATTRIBUTE24 RES_DESCRIPTIVE_FLEXFIELD_S_24
,HzRoleResponsibilityE0.ATTRIBUTE25 RES_DESCRIPTIVE_FLEXFIELD_S_25
,HzRoleResponsibilityE0.ATTRIBUTE26 RES_DESCRIPTIVE_FLEXFIELD_S_26
,HzRoleResponsibilityE0.ATTRIBUTE27 RES_DESCRIPTIVE_FLEXFIELD_S_27
,HzRoleResponsibilityE0.ATTRIBUTE28 RES_DESCRIPTIVE_FLEXFIELD_S_28
,HzRoleResponsibilityE0.ATTRIBUTE29 RES_DESCRIPTIVE_FLEXFIELD_S_29
,HzRoleResponsibilityE0.ATTRIBUTE30 RES_DESCRIPTIVE_FLEXFIELD_S_30
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER1 RES_DESCRIPTIVE_FLEXFIELD_NUMB
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER2 RES_DESCRIPTIVE_FLEXFIELD_N_31
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER3 RES_DESCRIPTIVE_FLEXFIELD_N_32
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER4 RES_DESCRIPTIVE_FLEXFIELD_N_33
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER5 RES_DESCRIPTIVE_FLEXFIELD_N_34
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER6 RES_DESCRIPTIVE_FLEXFIELD_N_35
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER7 RES_DESCRIPTIVE_FLEXFIELD_N_36
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER8 RES_DESCRIPTIVE_FLEXFIELD_N_37
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER9 RES_DESCRIPTIVE_FLEXFIELD_N_38
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER10 RES_DESCRIPTIVE_FLEXFIELD_N_39
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER11 RES_DESCRIPTIVE_FLEXFIELD_N_40
,HzRoleResponsibilityE0.ATTRIBUTE_NUMBER12 RES_DESCRIPTIVE_FLEXFIELD_N_41
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE1,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_DATE
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE2,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_42
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE3,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_43
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE4,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_44
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE5,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_45
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE6,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_46
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE7,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_47
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE8,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_48
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE9,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_49
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE10,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_50
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE11,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_51
,TO_CHAR(HzRoleResponsibilityE0.ATTRIBUTE_DATE12,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_52
,HzRoleResponsibilityE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,HzRoleResponsibilityE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,HzRoleResponsibilityE0.CREATED_BY RSC_CREATED_BY
,HzRoleResponsibilityE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HZ_PARTIES HzPartiesE0
,HZ_PARTY_USG_ASSIGNMENTS HzPartyUsgAssignmentsE0
,HZ_CUST_ACCOUNTS HzCustAccountsE0
,HZ_CUST_ACCOUNT_ROLES HzCustAccountRolesE0
,HZ_ROLE_RESPONSIBILITY HzRoleResponsibilityE0
WHERE HzPartiesE0.PARTY_ID = HzPartyUsgAssignmentsE0.PARTY_ID
AND HzPartyUsgAssignmentsE0.PARTY_USAGE_CODE = 'CUSTOMER'
AND HzPartiesE0.PARTY_ID = HzCustAccountsE0.PARTY_ID
AND HzCustAccountsE0.CUST_ACCOUNT_ID = HzCustAccountRolesE0.CUST_ACCOUNT_ID
AND HzCustAccountRolesE0.CUST_ACCOUNT_ROLE_ID = HzRoleResponsibilityE0.CUST_ACCOUNT_ROLE_ID