/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/CustomerAccountAndOrSiteBankAccounts.sql $:
 * $Id: CustomerAccountAndOrSiteBankAccounts.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- STRICTLY_BATCH_SEQ = RES_CUSTOMER_ACCOUNT_SOURCE__0,RES_ACCOUNT_SITE_SOURCE_SYST_1,RES_BANK_ACCOUNT_NUMBER

-- Account Level
SELECT 'CUSTOMER' RES_CUSTOMER_ACCOUNT_SOURCE_SY
,HzCustAccountsE0.ACCOUNT_NUMBER RES_CUSTOMER_ACCOUNT_SOURCE__0
,'' RES_ACCOUNT_SITE_SOURCE_SYSTEM
,'' RES_ACCOUNT_SITE_SOURCE_SYST_1
,'' RES_BATCH_IDENTIFIER
,IbyExtBankAccountsE0.BANK_ACCOUNT_NAME RES_BANK_ACCOUNT_NAME
,IbyPmtInstrUsesAllE0.PRIMARY_FLAG RES_PRIMARY_INDICATOR
,TO_CHAR(IbyPmtInstrUsesAllE0.START_DATE,'YYYY/MM/DD') RES_FROM_DATE
,DECODE(TO_CHAR(IbyPmtInstrUsesAllE0.END_DATE,'YYYY/MM/DD'),'4712/12/31',NULL,TO_CHAR(IbyPmtInstrUsesAllE0.END_DATE,'YYYY/MM/DD')) RES_TO_DATE
,IbyPmtInstrUsesAllE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_CONTEXT_PROMP
,IbyPmtInstrUsesAllE0.ATTRIBUTE1 RES_DESCRIPTIVE_FLEXFIELD_SEGM
,IbyPmtInstrUsesAllE0.ATTRIBUTE2 RES_DESCRIPTIVE_FLEXFIELD_SE_2
,IbyPmtInstrUsesAllE0.ATTRIBUTE3 RES_DESCRIPTIVE_FLEXFIELD_SE_3
,IbyPmtInstrUsesAllE0.ATTRIBUTE4 RES_DESCRIPTIVE_FLEXFIELD_SE_4
,IbyPmtInstrUsesAllE0.ATTRIBUTE5 RES_DESCRIPTIVE_FLEXFIELD_SE_5
,IbyPmtInstrUsesAllE0.ATTRIBUTE6 RES_DESCRIPTIVE_FLEXFIELD_SE_6
,IbyPmtInstrUsesAllE0.ATTRIBUTE7 RES_DESCRIPTIVE_FLEXFIELD_SE_7
,IbyPmtInstrUsesAllE0.ATTRIBUTE8 RES_DESCRIPTIVE_FLEXFIELD_SE_8
,IbyPmtInstrUsesAllE0.ATTRIBUTE9 RES_DESCRIPTIVE_FLEXFIELD_SE_9
,IbyPmtInstrUsesAllE0.ATTRIBUTE10 RES_DESCRIPTIVE_FLEXFIELD_S_10
,IbyPmtInstrUsesAllE0.ATTRIBUTE11 RES_DESCRIPTIVE_FLEXFIELD_S_11
,IbyPmtInstrUsesAllE0.ATTRIBUTE12 RES_DESCRIPTIVE_FLEXFIELD_S_12
,IbyPmtInstrUsesAllE0.ATTRIBUTE13 RES_DESCRIPTIVE_FLEXFIELD_S_13
,IbyPmtInstrUsesAllE0.ATTRIBUTE14 RES_DESCRIPTIVE_FLEXFIELD_S_14
,IbyPmtInstrUsesAllE0.ATTRIBUTE15 RES_DESCRIPTIVE_FLEXFIELD_S_15
,IbyExtBankAccountsE0.BANK_ACCOUNT_NUM RES_BANK_ACCOUNT_NUMBER
,IbyExtBankAccountsE0.CURRENCY_CODE RES_BANK_ACCOUNT_CURRENCY
,TO_CHAR(IbyExtBankAccountsE0.END_DATE,'YYYY/MM/DD') RES_BANK_ACCOUNT_INACTIVE_ON
,IbyExtBankAccountsE0.DESCRIPTION RES_BANK_ACCOUNT_DESCRIPTION
,CeBankBranchesVE0.BANK_NAME RES_BANK_NAME
,CeBankBranchesVE0.BANK_BRANCH_NAME RES_BANK_BRANCH_NAME
,CeBankBranchesVE0.BANK_NUMBER RES_BANK_BRANCH_NUMBER
,CeBankBranchesVE0.DESCRIPTION RES_BANK_BRANCH_DESCRIPTION
,CeBankBranchesVE0.ADDRESS_LINE1 RES_BANK_BRANCH_ADDRESS_LINE_1
,CeBankBranchesVE0.ADDRESS_LINE2 RES_BANK_BRANCH_ADDRESS_LINE_2
,CeBankBranchesVE0.ADDRESS_LINE3 RES_BANK_BRANCH_ADDRESS_LINE_3
,CeBankBranchesVE0.CITY RES_BANK_BRANCH_CITY
,CeBankBranchesVE0.STATE RES_BANK_BRANCH_STATE
,CeBankBranchesVE0.ZIP RES_BANK_BRANCH_ZIP_CODE
,CeBankBranchesVE0.PROVINCE RES_BANK_BRANCH_PROVINCE
,CeBankBranchesVE0.COUNTRY_NAME RES_BANK_BRANCH_COUNTRY
,BankBranchDetailE0.PRIMARY_PHONE_AREA_CODE RES_BANK_BRANCH_AREA_CODE
,BankBranchDetailE0.PRIMARY_PHONE_NUMBER RES_BANK_BRANCH_PHONE_NUMBER
,IbyExtBankAccountsE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_BANK_ACCOUNT_
,IbyExtBankAccountsE0.ATTRIBUTE1 RES_BANK_ACCOUNT_DESCRIPTIVE_F
,IbyExtBankAccountsE0.ATTRIBUTE2 RES_BANK_ACCOUNT_DESCRIPTIV_16
,IbyExtBankAccountsE0.ATTRIBUTE3 RES_BANK_ACCOUNT_DESCRIPTIV_17
,IbyExtBankAccountsE0.ATTRIBUTE4 RES_BANK_ACCOUNT_DESCRIPTIV_18
,IbyExtBankAccountsE0.ATTRIBUTE5 RES_BANK_ACCOUNT_DESCRIPTIV_19
,IbyExtBankAccountsE0.ATTRIBUTE6 RES_BANK_ACCOUNT_DESCRIPTIV_20
,IbyExtBankAccountsE0.ATTRIBUTE7 RES_BANK_ACCOUNT_DESCRIPTIV_21
,IbyExtBankAccountsE0.ATTRIBUTE8 RES_BANK_ACCOUNT_DESCRIPTIV_22
,IbyExtBankAccountsE0.ATTRIBUTE9 RES_BANK_ACCOUNT_DESCRIPTIV_23
,IbyExtBankAccountsE0.ATTRIBUTE10 RES_BANK_ACCOUNT_DESCRIPTIV_24
,IbyExtBankAccountsE0.ATTRIBUTE11 RES_BANK_ACCOUNT_DESCRIPTIV_25
,IbyExtBankAccountsE0.ATTRIBUTE12 RES_BANK_ACCOUNT_DESCRIPTIV_26
,IbyExtBankAccountsE0.ATTRIBUTE13 RES_BANK_ACCOUNT_DESCRIPTIV_27
,IbyExtBankAccountsE0.ATTRIBUTE14 RES_BANK_ACCOUNT_DESCRIPTIV_28
,IbyExtBankAccountsE0.ATTRIBUTE15 RES_BANK_ACCOUNT_DESCRIPTIV_29
,BankBranchDetailE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_BANK_BRANCH_C
,BankBranchDetailE0.ATTRIBUTE1 RES_BANK_BRANCH_DESCRIPTIVE_FL
,BankBranchDetailE0.ATTRIBUTE2 RES_BANK_BRANCH_DESCRIPTIVE_30
,BankBranchDetailE0.ATTRIBUTE3 RES_BANK_BRANCH_DESCRIPTIVE_31
,BankBranchDetailE0.ATTRIBUTE4 RES_BANK_BRANCH_DESCRIPTIVE_32
,BankBranchDetailE0.ATTRIBUTE5 RES_BANK_BRANCH_DESCRIPTIVE_33
,BankBranchDetailE0.ATTRIBUTE6 RES_BANK_BRANCH_DESCRIPTIVE_34
,BankBranchDetailE0.ATTRIBUTE7 RES_BANK_BRANCH_DESCRIPTIVE_35
,BankBranchDetailE0.ATTRIBUTE8 RES_BANK_BRANCH_DESCRIPTIVE_36
,BankBranchDetailE0.ATTRIBUTE9 RES_BANK_BRANCH_DESCRIPTIVE_37
,BankBranchDetailE0.ATTRIBUTE10 RES_BANK_BRANCH_DESCRIPTIVE_38
,BankBranchDetailE0.ATTRIBUTE11 RES_BANK_BRANCH_DESCRIPTIVE_39
,BankBranchDetailE0.ATTRIBUTE12 RES_BANK_BRANCH_DESCRIPTIVE_40
,BankBranchDetailE0.ATTRIBUTE13 RES_BANK_BRANCH_DESCRIPTIVE_41
,BankBranchDetailE0.ATTRIBUTE14 RES_BANK_BRANCH_DESCRIPTIVE_42
,BankBranchDetailE0.ATTRIBUTE15 RES_BANK_BRANCH_DESCRIPTIVE_43
,CeBankBranchesVE0.BRANCH_NUMBER RES_BANK_NUMBER
,CeBankBranchesVE0.ADDRESS_LINE4 RES_BANK_BRANCH_ADDRESS_LINE_4
,CeBankBranchesVE0.COUNTRY RES_BANK_BRANCH_COUNTY
,CeBankBranchesVE0.EFT_USER_NUMBER RES_BANK_BRANCH_EFT_USER_NUMBE
,IbyExtBankAccountsE0.CHECK_DIGITS RES_BANK_ACCOUNT_CHECK_DIGITS
,'' RES_USER_DEFINED_GLOBAL_CONTEX
,'' RES_GLOBAL_DESCRIPTIVE_FLEXFIE
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_44
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_45
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_46
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_47
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_48
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_49
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_50
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_51
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_52
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_53
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_54
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_55
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_56
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_57
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_58
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_59
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_60
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_61
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_62
,'' RES_ORGANIZATION_ID
,CeBankBranchesVE0.BANK_HOME_COUNTRY RES_BANK_HOME_COUNTRY
,IbyExternalPayersAllE0.DIRDEB_INSTRUCTION_CODE RES_LOCAL_INSTRUMENT
,IbyExternalPayersAllE0.SERVICE_LEVEL RES_SERVICE_LEVEL_CODE
,IbyExternalPayersAllE0.PURPOSE_CODE RES_PURPOSE_CODE
,IbyExternalPayersAllE0.BANK_CHARGE_BEARER_CODE RES_BANK_CHARGE_BEARER_CODE
,IbyExternalPayersAllE0.DEBIT_ADVICE_DELIVERY_METHOD RES_DELIVERY_METHOD
,IbyExternalPayersAllE0.DEBIT_ADVICE_EMAIL RES_EMAIL
,IbyExternalPayersAllE0.DEBIT_ADVICE_FAX RES_FAX
,CeBankBranchesVE0.EFT_SWIFT_CODE RES_BIC
,IbyExtBankAccountsE0.COUNTRY_CODE RES_BANK_ACCOUNT_COUNTRY_CODE
,IbyExtBankAccountsE0.FOREIGN_PAYMENT_USE_FLAG RES_ALLOW_INTERNATIONAL_PAYMEN
,IbyPmtInstrUsesAllE0.PRIMARY_FLAG RES_PRIMARY_OWNER
,IbyExtBankAccountsE0.BANK_ACCOUNT_NAME_ALT RES_ALTERNATE_BANK_ACCOUNT_NAM
,IbyExtBankAccountsE0.BANK_ACCOUNT_TYPE RES_BANK_ACCOUNT_TYPE
,IbyExtBankAccountsE0.ACCOUNT_SUFFIX RES_BANK_ACCOUNT_SUFFIX
,IbyExtBankAccountsE0.AGENCY_LOCATION_CODE RES_AGENCY_LOCATION_CODE
,IbyExtBankAccountsE0.IBAN RES_IBAN
,IbyPmtInstrUsesAllE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,IbyPmtInstrUsesAllE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,IbyPmtInstrUsesAllE0.CREATED_BY RSC_CREATED_BY
,IbyPmtInstrUsesAllE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HZ_PARTIES HzPartiesE0
,HZ_PARTY_USG_ASSIGNMENTS HzPartyUsgAssignmentsE0
,HZ_CUST_ACCOUNTS HzCustAccountsE0
,IBY_EXTERNAL_PAYERS_ALL IbyExternalPayersAllE0
,IBY_PMT_INSTR_USES_ALL IbyPmtInstrUsesAllE0
,IBY_EXT_BANK_ACCOUNTS IbyExtBankAccountsE0
--,IBY_ACCOUNT_OWNERS IbyAccountOwnersE0
,CE_BANK_BRANCHES_V CeBankBranchesVE0
,HZ_PARTIES BankBranchDetailE0

WHERE HzPartiesE0.PARTY_ID = HzPartyUsgAssignmentsE0.PARTY_ID
AND HzPartyUsgAssignmentsE0.PARTY_USAGE_CODE = 'CUSTOMER'
AND HzPartiesE0.PARTY_ID = HzCustAccountsE0.PARTY_ID
AND HzPartiesE0.PARTY_ID = IbyExternalPayersAllE0.PARTY_ID
AND HzCustAccountsE0.CUST_ACCOUNT_ID = IbyExternalPayersAllE0.CUST_ACCOUNT_ID
AND IbyExternalPayersAllE0.ACCT_SITE_USE_ID IS NULL
AND IbyExternalPayersAllE0.EXT_PAYER_ID = IbyPmtInstrUsesAllE0.EXT_PMT_PARTY_ID
/*AND IbyPmtInstrUsesAllE0.INSTRUMENT_ID = IbyAccountOwnersE0.EXT_BANK_ACCOUNT_ID
AND HzPartiesE0.PARTY_ID = IbyAccountOwnersE0.ACCOUNT_OWNER_PARTY_ID*/
AND IbyPmtInstrUsesAllE0.INSTRUMENT_ID = IbyExtBankAccountsE0.EXT_BANK_ACCOUNT_ID
AND IbyExtBankAccountsE0.BANK_ID = CeBankBranchesVE0.BANK_PARTY_ID
AND IbyExtBankAccountsE0.BRANCH_ID = CeBankBranchesVE0.BRANCH_PARTY_ID
AND IbyExtBankAccountsE0.BRANCH_ID = BankBranchDetailE0.PARTY_ID

UNION

SELECT 'CUSTOMER' RES_CUSTOMER_ACCOUNT_SOURCE_SY
,HzCustAccountsE0.ACCOUNT_NUMBER RES_CUSTOMER_ACCOUNT_SOURCE__0
,'CUSTOMER' RES_ACCOUNT_SITE_SOURCE_SYSTEM
,HzPartySitesE0.PARTY_SITE_NUMBER RES_ACCOUNT_SITE_SOURCE_SYST_1
,'' RES_BATCH_IDENTIFIER
,IbyExtBankAccountsE0.BANK_ACCOUNT_NAME RES_BANK_ACCOUNT_NAME
,IbyPmtInstrUsesAllE0.PRIMARY_FLAG RES_PRIMARY_INDICATOR
,TO_CHAR(IbyPmtInstrUsesAllE0.START_DATE,'YYYY/MM/DD') RES_FROM_DATE
,DECODE(TO_CHAR(IbyPmtInstrUsesAllE0.END_DATE,'YYYY/MM/DD'),'4712/12/31',NULL,TO_CHAR(IbyPmtInstrUsesAllE0.END_DATE,'YYYY/MM/DD')) RES_TO_DATE
,IbyPmtInstrUsesAllE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_CONTEXT_PROMP
,IbyPmtInstrUsesAllE0.ATTRIBUTE1 RES_DESCRIPTIVE_FLEXFIELD_SEGM
,IbyPmtInstrUsesAllE0.ATTRIBUTE2 RES_DESCRIPTIVE_FLEXFIELD_SE_2
,IbyPmtInstrUsesAllE0.ATTRIBUTE3 RES_DESCRIPTIVE_FLEXFIELD_SE_3
,IbyPmtInstrUsesAllE0.ATTRIBUTE4 RES_DESCRIPTIVE_FLEXFIELD_SE_4
,IbyPmtInstrUsesAllE0.ATTRIBUTE5 RES_DESCRIPTIVE_FLEXFIELD_SE_5
,IbyPmtInstrUsesAllE0.ATTRIBUTE6 RES_DESCRIPTIVE_FLEXFIELD_SE_6
,IbyPmtInstrUsesAllE0.ATTRIBUTE7 RES_DESCRIPTIVE_FLEXFIELD_SE_7
,IbyPmtInstrUsesAllE0.ATTRIBUTE8 RES_DESCRIPTIVE_FLEXFIELD_SE_8
,IbyPmtInstrUsesAllE0.ATTRIBUTE9 RES_DESCRIPTIVE_FLEXFIELD_SE_9
,IbyPmtInstrUsesAllE0.ATTRIBUTE10 RES_DESCRIPTIVE_FLEXFIELD_S_10
,IbyPmtInstrUsesAllE0.ATTRIBUTE11 RES_DESCRIPTIVE_FLEXFIELD_S_11
,IbyPmtInstrUsesAllE0.ATTRIBUTE12 RES_DESCRIPTIVE_FLEXFIELD_S_12
,IbyPmtInstrUsesAllE0.ATTRIBUTE13 RES_DESCRIPTIVE_FLEXFIELD_S_13
,IbyPmtInstrUsesAllE0.ATTRIBUTE14 RES_DESCRIPTIVE_FLEXFIELD_S_14
,IbyPmtInstrUsesAllE0.ATTRIBUTE15 RES_DESCRIPTIVE_FLEXFIELD_S_15
,IbyExtBankAccountsE0.BANK_ACCOUNT_NUM RES_BANK_ACCOUNT_NUMBER
,IbyExtBankAccountsE0.CURRENCY_CODE RES_BANK_ACCOUNT_CURRENCY
,TO_CHAR(IbyExtBankAccountsE0.END_DATE,'YYYY/MM/DD') RES_BANK_ACCOUNT_INACTIVE_ON
,IbyExtBankAccountsE0.DESCRIPTION RES_BANK_ACCOUNT_DESCRIPTION
,CeBankBranchesVE0.BANK_NAME RES_BANK_NAME
,CeBankBranchesVE0.BANK_BRANCH_NAME RES_BANK_BRANCH_NAME
,CeBankBranchesVE0.BANK_NUMBER RES_BANK_NUMBER
,CeBankBranchesVE0.DESCRIPTION RES_BANK_BRANCH_DESCRIPTION
,CeBankBranchesVE0.ADDRESS_LINE1 RES_BANK_BRANCH_ADDRESS_LINE_1
,CeBankBranchesVE0.ADDRESS_LINE2 RES_BANK_BRANCH_ADDRESS_LINE_2
,CeBankBranchesVE0.ADDRESS_LINE3 RES_BANK_BRANCH_ADDRESS_LINE_3
,CeBankBranchesVE0.CITY RES_BANK_BRANCH_CITY
,CeBankBranchesVE0.STATE RES_BANK_BRANCH_STATE
,CeBankBranchesVE0.ZIP RES_BANK_BRANCH_ZIP_CODE
,CeBankBranchesVE0.PROVINCE RES_BANK_BRANCH_PROVINCE
,CeBankBranchesVE0.COUNTRY_NAME RES_BANK_BRANCH_COUNTRY
,BankBranchDetailE0.PRIMARY_PHONE_AREA_CODE RES_BANK_BRANCH_AREA_CODE
,BankBranchDetailE0.PRIMARY_PHONE_NUMBER RES_BANK_BRANCH_PHONE_NUMBER
,IbyExtBankAccountsE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_BANK_ACCOUNT_
,IbyExtBankAccountsE0.ATTRIBUTE1 RES_BANK_ACCOUNT_DESCRIPTIVE_F
,IbyExtBankAccountsE0.ATTRIBUTE2 RES_BANK_ACCOUNT_DESCRIPTIV_16
,IbyExtBankAccountsE0.ATTRIBUTE3 RES_BANK_ACCOUNT_DESCRIPTIV_17
,IbyExtBankAccountsE0.ATTRIBUTE4 RES_BANK_ACCOUNT_DESCRIPTIV_18
,IbyExtBankAccountsE0.ATTRIBUTE5 RES_BANK_ACCOUNT_DESCRIPTIV_19
,IbyExtBankAccountsE0.ATTRIBUTE6 RES_BANK_ACCOUNT_DESCRIPTIV_20
,IbyExtBankAccountsE0.ATTRIBUTE7 RES_BANK_ACCOUNT_DESCRIPTIV_21
,IbyExtBankAccountsE0.ATTRIBUTE8 RES_BANK_ACCOUNT_DESCRIPTIV_22
,IbyExtBankAccountsE0.ATTRIBUTE9 RES_BANK_ACCOUNT_DESCRIPTIV_23
,IbyExtBankAccountsE0.ATTRIBUTE10 RES_BANK_ACCOUNT_DESCRIPTIV_24
,IbyExtBankAccountsE0.ATTRIBUTE11 RES_BANK_ACCOUNT_DESCRIPTIV_25
,IbyExtBankAccountsE0.ATTRIBUTE12 RES_BANK_ACCOUNT_DESCRIPTIV_26
,IbyExtBankAccountsE0.ATTRIBUTE13 RES_BANK_ACCOUNT_DESCRIPTIV_27
,IbyExtBankAccountsE0.ATTRIBUTE14 RES_BANK_ACCOUNT_DESCRIPTIV_28
,IbyExtBankAccountsE0.ATTRIBUTE15 RES_BANK_ACCOUNT_DESCRIPTIV_29
,BankBranchDetailE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_BANK_BRANCH_C
,BankBranchDetailE0.ATTRIBUTE1 RES_BANK_BRANCH_DESCRIPTIVE_FL
,BankBranchDetailE0.ATTRIBUTE2 RES_BANK_BRANCH_DESCRIPTIVE_29
,BankBranchDetailE0.ATTRIBUTE3 RES_BANK_BRANCH_DESCRIPTIVE_30
,BankBranchDetailE0.ATTRIBUTE4 RES_BANK_BRANCH_DESCRIPTIVE_31
,BankBranchDetailE0.ATTRIBUTE5 RES_BANK_BRANCH_DESCRIPTIVE_32
,BankBranchDetailE0.ATTRIBUTE6 RES_BANK_BRANCH_DESCRIPTIVE_33
,BankBranchDetailE0.ATTRIBUTE7 RES_BANK_BRANCH_DESCRIPTIVE_34
,BankBranchDetailE0.ATTRIBUTE8 RES_BANK_BRANCH_DESCRIPTIVE_35
,BankBranchDetailE0.ATTRIBUTE9 RES_BANK_BRANCH_DESCRIPTIVE_36
,BankBranchDetailE0.ATTRIBUTE10 RES_BANK_BRANCH_DESCRIPTIVE_37
,BankBranchDetailE0.ATTRIBUTE11 RES_BANK_BRANCH_DESCRIPTIVE_38
,BankBranchDetailE0.ATTRIBUTE12 RES_BANK_BRANCH_DESCRIPTIVE_39
,BankBranchDetailE0.ATTRIBUTE13 RES_BANK_BRANCH_DESCRIPTIVE_40
,BankBranchDetailE0.ATTRIBUTE14 RES_BANK_BRANCH_DESCRIPTIVE_41
,BankBranchDetailE0.ATTRIBUTE15 RES_BANK_BRANCH_DESCRIPTIVE_42
,CeBankBranchesVE0.BRANCH_NUMBER RES_BANK_BRANCH_NUMBER
,CeBankBranchesVE0.ADDRESS_LINE4 RES_BANK_BRANCH_ADDRESS_LINE_4
,CeBankBranchesVE0.COUNTRY RES_BANK_BRANCH_COUNTY
,CeBankBranchesVE0.EFT_USER_NUMBER RES_BANK_BRANCH_EFT_USER_NUMBE
,IbyExtBankAccountsE0.CHECK_DIGITS RES_BANK_ACCOUNT_CHECK_DIGITS
,'' RES_USER_DEFINED_GLOBAL_CONTEX
,'' RES_GLOBAL_DESCRIPTIVE_FLEXFIE
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_43
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_44
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_45
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_46
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_47
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_48
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_49
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_50
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_51
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_52
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_53
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_54
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_55
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_56
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_57
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_58
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_59
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_60
,'' RES_GLOBAL_DESCRIPTIVE_FLEX_61
,'' RES_ORGANIZATION_ID
,CeBankBranchesVE0.BANK_HOME_COUNTRY RES_BANK_HOME_COUNTRY
,IbyExternalPayersAllE0.DIRDEB_INSTRUCTION_CODE RES_LOCAL_INSTRUMENT
,IbyExternalPayersAllE0.SERVICE_LEVEL RES_SERVICE_LEVEL_CODE
,IbyExternalPayersAllE0.PURPOSE_CODE RES_PURPOSE_CODE
,IbyExternalPayersAllE0.BANK_CHARGE_BEARER_CODE RES_BANK_CHARGE_BEARER_CODE
,IbyExternalPayersAllE0.DEBIT_ADVICE_DELIVERY_METHOD RES_DELIVERY_METHOD
,IbyExternalPayersAllE0.DEBIT_ADVICE_EMAIL RES_EMAIL
,IbyExternalPayersAllE0.DEBIT_ADVICE_FAX RES_FAX
,CeBankBranchesVE0.EFT_SWIFT_CODE RES_BIC
,IbyExtBankAccountsE0.COUNTRY_CODE RES_BANK_ACCOUNT_COUNTRY_CODE
,IbyExtBankAccountsE0.FOREIGN_PAYMENT_USE_FLAG RES_ALLOW_INTERNATIONAL_PAYMEN
,IbyPmtInstrUsesAllE0.PRIMARY_FLAG RES_PRIMARY_OWNER
,IbyExtBankAccountsE0.BANK_ACCOUNT_NAME_ALT RES_ALTERNATE_BANK_ACCOUNT_NAM
,IbyExtBankAccountsE0.BANK_ACCOUNT_TYPE RES_BANK_ACCOUNT_TYPE
,IbyExtBankAccountsE0.ACCOUNT_SUFFIX RES_BANK_ACCOUNT_SUFFIX
,IbyExtBankAccountsE0.AGENCY_LOCATION_CODE RES_AGENCY_LOCATION_CODE
,IbyExtBankAccountsE0.IBAN RES_IBAN
,IbyPmtInstrUsesAllE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,IbyPmtInstrUsesAllE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,IbyPmtInstrUsesAllE0.CREATED_BY RSC_CREATED_BY
,IbyPmtInstrUsesAllE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,buE0.BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HZ_PARTIES HzPartiesE0
,HZ_PARTY_USG_ASSIGNMENTS HzPartyUsgAssignmentsE0
,HZ_CUST_ACCOUNTS HzCustAccountsE0
,IBY_EXTERNAL_PAYERS_ALL IbyExternalPayersAllE0
,IBY_PMT_INSTR_USES_ALL IbyPmtInstrUsesAllE0
,IBY_EXT_BANK_ACCOUNTS IbyExtBankAccountsE0
--,IBY_ACCOUNT_OWNERS IbyAccountOwnersE0
,CE_BANK_BRANCHES_V CeBankBranchesVE0
,HZ_PARTIES BankBranchDetailE0
,HZ_PARTY_SITES HzPartySitesE0
,HZ_CUST_ACCT_SITES_ALL HzCustAcctSitesAllE0
,HZ_CUST_SITE_USES_ALL HzCustSiteUsesAllE0
,FUN_ALL_BUSINESS_UNITS_V buE0
WHERE HzPartiesE0.PARTY_ID = HzPartyUsgAssignmentsE0.PARTY_ID
AND HzPartyUsgAssignmentsE0.PARTY_USAGE_CODE = 'CUSTOMER'
AND HzPartiesE0.PARTY_ID = HzCustAccountsE0.PARTY_ID
AND HzPartiesE0.PARTY_ID = IbyExternalPayersAllE0.PARTY_ID
AND HzCustAccountsE0.CUST_ACCOUNT_ID = IbyExternalPayersAllE0.CUST_ACCOUNT_ID
AND IbyExternalPayersAllE0.EXT_PAYER_ID = IbyPmtInstrUsesAllE0.EXT_PMT_PARTY_ID
AND IbyPmtInstrUsesAllE0.INSTRUMENT_ID = IbyExtBankAccountsE0.EXT_BANK_ACCOUNT_ID
AND IbyExtBankAccountsE0.BANK_ID = CeBankBranchesVE0.BANK_PARTY_ID
AND IbyExtBankAccountsE0.BRANCH_ID = CeBankBranchesVE0.BRANCH_PARTY_ID
AND IbyExtBankAccountsE0.BRANCH_ID = BankBranchDetailE0.PARTY_ID
AND HzPartiesE0.PARTY_ID = HzPartySitesE0.PARTY_ID
AND HzPartySitesE0.PARTY_SITE_ID = HzCustAcctSitesAllE0.PARTY_SITE_ID
AND IbyExternalPayersAllE0.ACCT_SITE_USE_ID = HzCustSiteUsesAllE0.SITE_USE_ID
AND HzPartySitesE0.PARTY_SITE_ID = HzCustAcctSitesAllE0.PARTY_SITE_ID
AND HzCustAccountsE0.CUST_ACCOUNT_ID = HzCustAcctSitesAllE0.CUST_ACCOUNT_ID
AND HzCustAcctSitesAllE0.SET_ID = buE0.DEFAULT_SET_ID(+)