/* ****************************************************************************
 * $Revision: 56649 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-07-12 11:20:44 +0700 (Tue, 12 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.12/branches/core/v2.2.0.0/reverse_sql/FINANCIALS/Currency%20Rates%20Manager%20-%20Rate%20Types.sql $:
 * $Id: Currency Rates Manager - Rate Types.sql 56649 2016-07-12 04:20:44Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- STRICTLY_BATCH_SEQ = RES_LOCATION_ORIGINAL_SYSTEM_R

SELECT '' RES_BATCH_IDENTIFIER
,'CUSTOMER' RES_LOCATION_ORIGINAL_SYSTEM
,HzPartySitesE0.PARTY_SITE_NUMBER RES_LOCATION_ORIGINAL_SYSTEM_R
,'I' RES_INSERT_UPDATE_INDICATOR
,HzLocationsE0.COUNTRY RES_COUNTRY
,HzLocationsE0.ADDRESS1 RES_ADDRESS_LINE_1
,HzLocationsE0.ADDRESS2 RES_ADDRESS_LINE_2
,HzLocationsE0.ADDRESS3 RES_ADDRESS_LINE_3
,HzLocationsE0.ADDRESS4 RES_ADDRESS_LINE_4
,HzLocationsE0.CITY RES_CITY
,HzLocationsE0.STATE RES_STATE
,HzLocationsE0.PROVINCE RES_PROVINCE
,HzLocationsE0.COUNTY RES_COUNTY
,HzLocationsE0.POSTAL_CODE RES_POSTAL_CODE
,HzLocationsE0.POSTAL_PLUS4_CODE RES_POSTAL_CODE_EXTENSION
,HzLocationsE0.LOCATION_LANGUAGE RES_LOCATION_LANGUAGE
,HzLocationsE0.DESCRIPTION RES_DESCRIPTION
,HzLocationsE0.SHORT_DESCRIPTION RES_SHORT_DESCRIPTION
,HzLocationsE0.SALES_TAX_GEOCODE RES_SALES_TAX_GEOCODE
,HzLocationsE0.SALES_TAX_INSIDE_CITY_LIMITS RES_SALES_TAX_INSIDE_CITY_LIMI
,HzLocationsE0.TIMEZONE_CODE RES_TIMEZONE_CODE_IDENTIFIER
,'' RES_ADDRESS_LINES_1
,HzLocationProfilesE0.ACTUAL_CONTENT_SOURCE RES_ADDRESS_VALIDATION_SOURCE
,HzLocationProfilesE0.VALIDATION_STATUS_CODE RES_RETURNED_ADDRESS_VALIDATIO
,TO_CHAR(HzLocationsE0.DATE_VALIDATED,'YYYY/MM/DD') RES_ADDRESS_VALIDATION_DATE
,TO_CHAR(HzLocationsE0.ADDRESS_EFFECTIVE_DATE,'YYYY/MM/DD') RES_ADDRESS_EFFECTIVE_DATE
,DECODE(TO_CHAR(HzLocationsE0.ADDRESS_EXPIRATION_DATE,'YYYY/MM/DD'),'4712/12/31',NULL,TO_CHAR(HzLocationsE0.ADDRESS_EXPIRATION_DATE,'YYYY/MM/DD')) RES_ADDRESS_EXPIRATION_DATE
,HzLocationsE0.VALIDATED_FLAG RES_VALIDATION_INDICATOR
,HzLocationsE0.DO_NOT_VALIDATE_FLAG RES_VALIDATION_INELIGIBLE_INDI
,'' RES_INTERFACE_STATUS
,'' RES_ERROR_IDENTIFIER
,HzLocationsE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_CONTEXT_PROMP
,HzLocationsE0.ATTRIBUTE1 RES_DESCRIPTIVE_FLEXFIELD_SEGM
,HzLocationsE0.ATTRIBUTE2 RES_DESCRIPTIVE_FLEXFIELD_SE_0
,HzLocationsE0.ATTRIBUTE3 RES_DESCRIPTIVE_FLEXFIELD_SE_1
,HzLocationsE0.ATTRIBUTE4 RES_DESCRIPTIVE_FLEXFIELD_SE_2
,HzLocationsE0.ATTRIBUTE5 RES_DESCRIPTIVE_FLEXFIELD_SE_3
,HzLocationsE0.ATTRIBUTE6 RES_DESCRIPTIVE_FLEXFIELD_SE_4
,HzLocationsE0.ATTRIBUTE7 RES_DESCRIPTIVE_FLEXFIELD_SE_5
,HzLocationsE0.ATTRIBUTE8 RES_DESCRIPTIVE_FLEXFIELD_SE_6
,HzLocationsE0.ATTRIBUTE9 RES_DESCRIPTIVE_FLEXFIELD_SE_7
,HzLocationsE0.ATTRIBUTE10 RES_DESCRIPTIVE_FLEXFIELD_SE_8
,HzLocationsE0.ATTRIBUTE11 RES_DESCRIPTIVE_FLEXFIELD_SE_9
,HzLocationsE0.ATTRIBUTE12 RES_DESCRIPTIVE_FLEXFIELD_S_10
,HzLocationsE0.ATTRIBUTE13 RES_DESCRIPTIVE_FLEXFIELD_S_11
,HzLocationsE0.ATTRIBUTE14 RES_DESCRIPTIVE_FLEXFIELD_S_12
,HzLocationsE0.ATTRIBUTE15 RES_DESCRIPTIVE_FLEXFIELD_S_13
,HzLocationsE0.ATTRIBUTE16 RES_DESCRIPTIVE_FLEXFIELD_S_14
,HzLocationsE0.ATTRIBUTE17 RES_DESCRIPTIVE_FLEXFIELD_S_15
,HzLocationsE0.ATTRIBUTE18 RES_DESCRIPTIVE_FLEXFIELD_S_16
,HzLocationsE0.ATTRIBUTE19 RES_DESCRIPTIVE_FLEXFIELD_S_17
,HzLocationsE0.ATTRIBUTE20 RES_DESCRIPTIVE_FLEXFIELD_S_18
,HzLocationsE0.ATTRIBUTE21 RES_DESCRIPTIVE_FLEXFIELD_S_19
,HzLocationsE0.ATTRIBUTE22 RES_DESCRIPTIVE_FLEXFIELD_S_20
,HzLocationsE0.ATTRIBUTE23 RES_DESCRIPTIVE_FLEXFIELD_S_21
,HzLocationsE0.ATTRIBUTE24 RES_DESCRIPTIVE_FLEXFIELD_S_22
,HzLocationsE0.ATTRIBUTE25 RES_DESCRIPTIVE_FLEXFIELD_S_23
,HzLocationsE0.ATTRIBUTE26 RES_DESCRIPTIVE_FLEXFIELD_S_24
,HzLocationsE0.ATTRIBUTE27 RES_DESCRIPTIVE_FLEXFIELD_S_25
,HzLocationsE0.ATTRIBUTE28 RES_DESCRIPTIVE_FLEXFIELD_S_26
,HzLocationsE0.ATTRIBUTE29 RES_DESCRIPTIVE_FLEXFIELD_S_27
,HzLocationsE0.ATTRIBUTE30 RES_DESCRIPTIVE_FLEXFIELD_S_28
,HzLocationsE0.ATTRIBUTE_NUMBER1 RES_DESCRIPTIVE_FLEXFIELD_NUMB
,HzLocationsE0.ATTRIBUTE_NUMBER2 RES_DESCRIPTIVE_FLEXFIELD_N_29
,HzLocationsE0.ATTRIBUTE_NUMBER3 RES_DESCRIPTIVE_FLEXFIELD_N_30
,HzLocationsE0.ATTRIBUTE_NUMBER4 RES_DESCRIPTIVE_FLEXFIELD_N_31
,HzLocationsE0.ATTRIBUTE_NUMBER5 RES_DESCRIPTIVE_FLEXFIELD_N_32
,HzLocationsE0.ATTRIBUTE_NUMBER6 RES_DESCRIPTIVE_FLEXFIELD_N_33
,HzLocationsE0.ATTRIBUTE_NUMBER7 RES_DESCRIPTIVE_FLEXFIELD_N_34
,HzLocationsE0.ATTRIBUTE_NUMBER8 RES_DESCRIPTIVE_FLEXFIELD_N_35
,HzLocationsE0.ATTRIBUTE_NUMBER9 RES_DESCRIPTIVE_FLEXFIELD_N_36
,HzLocationsE0.ATTRIBUTE_NUMBER10 RES_DESCRIPTIVE_FLEXFIELD_N_37
,HzLocationsE0.ATTRIBUTE_NUMBER11 RES_DESCRIPTIVE_FLEXFIELD_N_38
,HzLocationsE0.ATTRIBUTE_NUMBER12 RES_DESCRIPTIVE_FLEXFIELD_N_39
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE1,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_DATE
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE2,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_40
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE3,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_41
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE4,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_42
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE5,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_43
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE6,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_44
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE7,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_45
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE8,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_46
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE9,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_47
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE10,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_48
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE11,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_49
,TO_CHAR(HzLocationsE0.ATTRIBUTE_DATE12,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_50
,'' RES_GNR_STATUS
,HzLocationsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,HzLocationsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,HzLocationsE0.CREATED_BY RSC_CREATED_BY
,HzLocationsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HZ_PARTIES HzPartiesE0
,HZ_PARTY_USG_ASSIGNMENTS HzPartyUsgAssignmentsE0
,HZ_PARTY_SITES HzPartySitesE0
,HZ_LOCATIONS HzLocationsE0
,(SELECT LOCATION_ID
	,ACTUAL_CONTENT_SOURCE
	,VALIDATION_STATUS_CODE
	FROM HZ_LOCATION_PROFILES
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	)HzLocationProfilesE0
WHERE HzPartiesE0.PARTY_ID = HzPartyUsgAssignmentsE0.PARTY_ID
AND HzPartyUsgAssignmentsE0.PARTY_USAGE_CODE = 'CUSTOMER'
AND HzPartiesE0.PARTY_ID = HzPartySitesE0.PARTY_ID
AND HzPartySitesE0.LOCATION_ID = HzLocationsE0.LOCATION_ID
--AND HzPartiesE0.IDEN_ADDR_LOCATION_ID = HzLocationsE0.LOCATION_ID
AND HzLocationsE0.LOCATION_ID = HzLocationProfilesE0.LOCATION_ID(+)