/* ****************************************************************************
 * $Revision: 56649 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-07-12 11:20:44 +0700 (Tue, 12 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.12/branches/core/v2.2.0.0/reverse_sql/FINANCIALS/Currency%20Rates%20Manager%20-%20Rate%20Types.sql $:
 * $Id: Currency Rates Manager - Rate Types.sql 56649 2016-07-12 04:20:44Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- STRICTLY_BATCH_SEQ = RES_SUBJECT_RELATIONSHIP_PAR_0,RES_OBJECT_RELATIONSHIP_PART_1

SELECT '' RES_BATCH_IDENTIFIER
,'CUSTOMER' RES_SUBJECT_RELATIONSHIP_PARTY -- Subject Relationship Party Original System
,HzPartiesE0.PARTY_NUMBER RES_SUBJECT_RELATIONSHIP_PAR_0 -- Subject Relationship Party Original System Reference
,'CUSTOMER' RES_OBJECT_RELATIONSHIP_PARTY_ -- Object Relationship Party Original System
,HzPartiesE1.PARTY_NUMBER RES_OBJECT_RELATIONSHIP_PART_1 -- Object Relationship Party Original System Reference
,HzRelationshipsE0.RELATIONSHIP_TYPE RES_RELATIONSHIP_TYPE
,HzRelationshipsE0.RELATIONSHIP_CODE RES_RELATIONSHIP_CODE
,TO_CHAR(HzRelationshipsE0.START_DATE,'YYYY/MM/DD') RES_FROM_DATE
,'I' RES_INSERT_UPDATE_INDICATOR
,DECODE(TO_CHAR(HzRelationshipsE0.END_DATE,'YYYY/MM/DD'),'4712/12/31',NULL,TO_CHAR(HzRelationshipsE0.END_DATE,'YYYY/MM/DD')) RES_TO_DATE
,HzRelationshipsE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_CONTEXT_PROMP
,HzRelationshipsE0.ATTRIBUTE1 RES_DESCRIPTIVE_FLEXFIELD_SEGM
,HzRelationshipsE0.ATTRIBUTE2 RES_DESCRIPTIVE_FLEXFIELD_SE_2
,HzRelationshipsE0.ATTRIBUTE3 RES_DESCRIPTIVE_FLEXFIELD_SE_3
,HzRelationshipsE0.ATTRIBUTE4 RES_DESCRIPTIVE_FLEXFIELD_SE_4
,HzRelationshipsE0.ATTRIBUTE5 RES_DESCRIPTIVE_FLEXFIELD_SE_5
,HzRelationshipsE0.ATTRIBUTE6 RES_DESCRIPTIVE_FLEXFIELD_SE_6
,HzRelationshipsE0.ATTRIBUTE7 RES_DESCRIPTIVE_FLEXFIELD_SE_7
,HzRelationshipsE0.ATTRIBUTE8 RES_DESCRIPTIVE_FLEXFIELD_SE_8
,HzRelationshipsE0.ATTRIBUTE9 RES_DESCRIPTIVE_FLEXFIELD_SE_9
,HzRelationshipsE0.ATTRIBUTE10 RES_DESCRIPTIVE_FLEXFIELD_S_10
,HzRelationshipsE0.ATTRIBUTE11 RES_DESCRIPTIVE_FLEXFIELD_S_11
,HzRelationshipsE0.ATTRIBUTE12 RES_DESCRIPTIVE_FLEXFIELD_S_12
,HzRelationshipsE0.ATTRIBUTE13 RES_DESCRIPTIVE_FLEXFIELD_S_13
,HzRelationshipsE0.ATTRIBUTE14 RES_DESCRIPTIVE_FLEXFIELD_S_14
,HzRelationshipsE0.ATTRIBUTE15 RES_DESCRIPTIVE_FLEXFIELD_S_15
,HzRelationshipsE0.ATTRIBUTE16 RES_DESCRIPTIVE_FLEXFIELD_S_16
,HzRelationshipsE0.ATTRIBUTE17 RES_DESCRIPTIVE_FLEXFIELD_S_17
,HzRelationshipsE0.ATTRIBUTE18 RES_DESCRIPTIVE_FLEXFIELD_S_18
,HzRelationshipsE0.ATTRIBUTE19 RES_DESCRIPTIVE_FLEXFIELD_S_19
,HzRelationshipsE0.ATTRIBUTE20 RES_DESCRIPTIVE_FLEXFIELD_S_20
,HzRelationshipsE0.ATTRIBUTE21 RES_DESCRIPTIVE_FLEXFIELD_S_21
,HzRelationshipsE0.ATTRIBUTE22 RES_DESCRIPTIVE_FLEXFIELD_S_22
,HzRelationshipsE0.ATTRIBUTE23 RES_DESCRIPTIVE_FLEXFIELD_S_23
,HzRelationshipsE0.ATTRIBUTE24 RES_DESCRIPTIVE_FLEXFIELD_S_24
,HzRelationshipsE0.ATTRIBUTE25 RES_DESCRIPTIVE_FLEXFIELD_S_25
,HzRelationshipsE0.ATTRIBUTE26 RES_DESCRIPTIVE_FLEXFIELD_S_26
,HzRelationshipsE0.ATTRIBUTE27 RES_DESCRIPTIVE_FLEXFIELD_S_27
,HzRelationshipsE0.ATTRIBUTE28 RES_DESCRIPTIVE_FLEXFIELD_S_28
,HzRelationshipsE0.ATTRIBUTE29 RES_DESCRIPTIVE_FLEXFIELD_S_29
,HzRelationshipsE0.ATTRIBUTE30 RES_DESCRIPTIVE_FLEXFIELD_S_30
,HzRelationshipsE0.ATTRIBUTE_NUMBER1 RES_DESCRIPTIVE_FLEXFIELD_NUMB
,HzRelationshipsE0.ATTRIBUTE_NUMBER2 RES_DESCRIPTIVE_FLEXFIELD_N_31
,HzRelationshipsE0.ATTRIBUTE_NUMBER3 RES_DESCRIPTIVE_FLEXFIELD_N_32
,HzRelationshipsE0.ATTRIBUTE_NUMBER4 RES_DESCRIPTIVE_FLEXFIELD_N_33
,HzRelationshipsE0.ATTRIBUTE_NUMBER5 RES_DESCRIPTIVE_FLEXFIELD_N_34
,HzRelationshipsE0.ATTRIBUTE_NUMBER6 RES_DESCRIPTIVE_FLEXFIELD_N_35
,HzRelationshipsE0.ATTRIBUTE_NUMBER7 RES_DESCRIPTIVE_FLEXFIELD_N_36
,HzRelationshipsE0.ATTRIBUTE_NUMBER8 RES_DESCRIPTIVE_FLEXFIELD_N_37
,HzRelationshipsE0.ATTRIBUTE_NUMBER9 RES_DESCRIPTIVE_FLEXFIELD_N_38
,HzRelationshipsE0.ATTRIBUTE_NUMBER10 RES_DESCRIPTIVE_FLEXFIELD_N_39
,HzRelationshipsE0.ATTRIBUTE_NUMBER11 RES_DESCRIPTIVE_FLEXFIELD_N_40
,HzRelationshipsE0.ATTRIBUTE_NUMBER12 RES_DESCRIPTIVE_FLEXFIELD_N_41
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE1,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_DATE
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE2,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_42
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE3,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_43
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE4,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_44
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE5,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_45
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE6,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_46
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE7,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_47
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE8,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_48
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE9,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_49
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE10,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_50
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE11,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_51
,TO_CHAR(HzRelationshipsE0.ATTRIBUTE_DATE12,'YYYY/MM/DD') RES_DESCRIPTIVE_FLEXFIELD_D_52
,HzRelationshipsE0.SUBJECT_TYPE RES_SUBJECT_PARTY_TYPE
,HzRelationshipsE0.OBJECT_TYPE RES_OBJECT_PARTY_TYPE
,'CUSTOMER' RES_RELATIONSHIP_SOURCE_SYSTEM
,HzRelationshipsE0.RELATIONSHIP_REC_ID RES_RELATIONSHIP_SOURCE_SYS_53
,HzRelationshipsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,HzRelationshipsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,HzRelationshipsE0.CREATED_BY RSC_CREATED_BY
,HzRelationshipsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HZ_PARTIES HzPartiesE0
,HZ_PARTY_USG_ASSIGNMENTS HzPartyUsgAssignmentsE0
,HZ_RELATIONSHIPS HzRelationshipsE0
,HZ_PARTIES HzPartiesE1
WHERE HzPartiesE0.PARTY_ID = HzPartyUsgAssignmentsE0.PARTY_ID
AND HzPartyUsgAssignmentsE0.PARTY_USAGE_CODE  = 'CUSTOMER'
AND HzPartiesE0.PARTY_ID = HzRelationshipsE0.SUBJECT_ID
AND HzRelationshipsE0.OBJECT_ID = HzPartiesE1.PARTY_ID
AND HzRelationshipsE0.SUBJECT_TABLE_NAME = 'HZ_PARTIES'
AND HzRelationshipsE0.OBJECT_TABLE_NAME = 'HZ_PARTIES'