/* ****************************************************************************
 * $Revision: 56649 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-07-12 11:20:44 +0700 (Tue, 12 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.12/branches/core/v2.2.0.0/reverse_sql/FINANCIALS/Currency%20Rates%20Manager%20-%20Rate%20Types.sql $:
 * $Id: Currency Rates Manager - Rate Types.sql 56649 2016-07-12 04:20:44Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- STRICTLY_BATCH_SEQ = RES_PARTY_ORIGINAL_SYSTEM_REFE,RES_PARTY_SITE_ORIGINAL_SYST_0,RES_PART_SITE_USE_TYPE

SELECT '' RES_BATCH_IDENTIFIER
,'CUSTOMER' RES_PARTY_ORIGINAL_SYSTEM
,HzPartiesE0.PARTY_NUMBER RES_PARTY_ORIGINAL_SYSTEM_REFE
,'CUSTOMER' RES_PARTY_SITE_ORIGINAL_SYSTEM
,HzPartySitesE0.PARTY_SITE_NUMBER RES_PARTY_SITE_ORIGINAL_SYST_0
,HzPartySiteUsesE0.SITE_USE_TYPE RES_PART_SITE_USE_TYPE
,HzPartySiteUsesE0.PRIMARY_PER_TYPE RES_PRIMARY_INDICATOR
,'I' RES_INSERT_UPDATE_INDICATOR
,TO_CHAR(HzPartySiteUsesE0.BEGIN_DATE,'YYYY/MM/DD') RES_FROM_DATE
,DECODE(TO_CHAR(HzPartySiteUsesE0.END_DATE,'YYYY/MM/DD'),'4712/12/31',NULL,TO_CHAR(HzPartySiteUsesE0.END_DATE,'YYYY/MM/DD')) RES_TO_DATE
,HzPartySiteUsesE0.ATTRIBUTE_CATEGORY RES_USER_DEFINED_CONTEXT_PROMP
,HzPartySiteUsesE0.ATTRIBUTE1 RES_DESCRIPTIVE_FLEXFIELD_SEGM
,HzPartySiteUsesE0.ATTRIBUTE2 RES_DESCRIPTIVE_FLEXFIELD_SE_1
,HzPartySiteUsesE0.ATTRIBUTE3 RES_DESCRIPTIVE_FLEXFIELD_SE_2
,HzPartySiteUsesE0.ATTRIBUTE4 RES_DESCRIPTIVE_FLEXFIELD_SE_3
,HzPartySiteUsesE0.ATTRIBUTE5 RES_DESCRIPTIVE_FLEXFIELD_SE_4
,HzPartySiteUsesE0.ATTRIBUTE6 RES_DESCRIPTIVE_FLEXFIELD_SE_5
,HzPartySiteUsesE0.ATTRIBUTE7 RES_DESCRIPTIVE_FLEXFIELD_SE_6
,HzPartySiteUsesE0.ATTRIBUTE8 RES_DESCRIPTIVE_FLEXFIELD_SE_7
,HzPartySiteUsesE0.ATTRIBUTE9 RES_DESCRIPTIVE_FLEXFIELD_SE_8
,HzPartySiteUsesE0.ATTRIBUTE10 RES_DESCRIPTIVE_FLEXFIELD_SE_9
,HzPartySiteUsesE0.ATTRIBUTE11 RES_DESCRIPTIVE_FLEXFIELD_S_10
,HzPartySiteUsesE0.ATTRIBUTE12 RES_DESCRIPTIVE_FLEXFIELD_S_11
,HzPartySiteUsesE0.ATTRIBUTE13 RES_DESCRIPTIVE_FLEXFIELD_S_12
,HzPartySiteUsesE0.ATTRIBUTE14 RES_DESCRIPTIVE_FLEXFIELD_S_13
,HzPartySiteUsesE0.ATTRIBUTE15 RES_DESCRIPTIVE_FLEXFIELD_S_14
,HzPartySiteUsesE0.ATTRIBUTE16 RES_DESCRIPTIVE_FLEXFIELD_S_15
,HzPartySiteUsesE0.ATTRIBUTE17 RES_DESCRIPTIVE_FLEXFIELD_S_16
,HzPartySiteUsesE0.ATTRIBUTE18 RES_DESCRIPTIVE_FLEXFIELD_S_17
,HzPartySiteUsesE0.ATTRIBUTE19 RES_DESCRIPTIVE_FLEXFIELD_S_18
,HzPartySiteUsesE0.ATTRIBUTE20 RES_DESCRIPTIVE_FLEXFIELD_S_19
,HzPartySiteUsesE0.ATTRIBUTE21 RES_DESCRIPTIVE_FLEXFIELD_S_20
,HzPartySiteUsesE0.ATTRIBUTE22 RES_DESCRIPTIVE_FLEXFIELD_S_21
,HzPartySiteUsesE0.ATTRIBUTE23 RES_DESCRIPTIVE_FLEXFIELD_S_22
,HzPartySiteUsesE0.ATTRIBUTE24 RES_DESCRIPTIVE_FLEXFIELD_S_23
,HzPartySiteUsesE0.ATTRIBUTE25 RES_DESCRIPTIVE_FLEXFIELD_S_24
,HzPartySiteUsesE0.ATTRIBUTE26 RES_DESCRIPTIVE_FLEXFIELD_S_25
,HzPartySiteUsesE0.ATTRIBUTE27 RES_DESCRIPTIVE_FLEXFIELD_S_26
,HzPartySiteUsesE0.ATTRIBUTE28 RES_DESCRIPTIVE_FLEXFIELD_S_27
,HzPartySiteUsesE0.ATTRIBUTE29 RES_DESCRIPTIVE_FLEXFIELD_S_28
,HzPartySiteUsesE0.ATTRIBUTE30 RES_DESCRIPTIVE_FLEXFIELD_S_29
,'CUSTOMER' RES_PARTY_SITE_USE_ORIGINAL_SY
,HzPartySiteUsesE0.PARTY_SITE_USE_ID RES_ORIGINAL_SYSTEM_PARTY_SITE
,HzPartySiteUsesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,HzPartySiteUsesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,HzPartySiteUsesE0.CREATED_BY RSC_CREATED_BY
,HzPartySiteUsesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,buE0.BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HZ_PARTIES HzPartiesE0
,HZ_PARTY_USG_ASSIGNMENTS HzPartyUsgAssignmentsE0
,HZ_PARTY_SITES HzPartySitesE0
,HZ_PARTY_SITE_USES HzPartySiteUsesE0
,HZ_CUST_ACCT_SITES_ALL HzCustAcctSitesAllE0
,FUN_ALL_BUSINESS_UNITS_V buE0
WHERE HzPartiesE0.PARTY_ID = HzPartyUsgAssignmentsE0.PARTY_ID
AND HzPartiesE0.PARTY_ID = HzPartySitesE0.PARTY_ID
AND HzPartyUsgAssignmentsE0.PARTY_USAGE_CODE  = 'CUSTOMER'
AND HzPartySitesE0.PARTY_SITE_ID = HzPartySiteUsesE0.PARTY_SITE_ID
AND HzPartySitesE0.PARTY_SITE_ID = HzCustAcctSitesAllE0.PARTY_SITE_ID
AND HzCustAcctSitesAllE0.SET_ID = buE0.DEFAULT_SET_ID(+)