/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Define%20Budget%20Scenarios%20-%20Value%20Sets.sql $:
 * $Id: Define Budget Scenarios - Value Sets.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 
SELECT fndVSVauleSetEO.VALUE_SET_CODE 	RES_VALUE_SET_CODE
,fndVSVauleSetEO.DESCRIPTION 			RES_DESCRIPTION
,(SELECT USER_MODULE_NAME FROM FND_APPL_TAXONOMY_VL
	WHERE MODULE_ID = fndVSVauleSetEO.MODULE_ID 				
			)RES_MODULE
,(SELECT MEANING FROM FND_LOOKUPS 
	WHERE LOOKUP_TYPE = 'FND_VS_VALIDATION_TYPES'
		AND LOOKUP_CODE = fndVSVauleSetEO.VALIDATION_TYPE
			)	RES_VALIDATION_TYPE
,(SELECT MEANING FROM FND_LOOKUPS 
	WHERE LOOKUP_TYPE = 'FND_VS_VALUE_DATA_TYPES'
		AND LOOKUP_CODE = fndVSVauleSetEO.VALUE_DATA_TYPE
			)	RES_VALUE_DATA_TYPE
,DECODE(fndVSVauleSetEO.SECURITY_ENABLED_FLAG,'Y','Yes','No') RES_SECURITY_ENABLED
,DECODE(fndVSVauleSetEO.VALIDATION_TYPE,'FORMAT',NULL,fndVSVauleSetEO.DATA_SECURITY_OBJECT_NAME) AS RES_DATA_SECURITY_RESOURCE_NAM
,(SELECT MEANING FROM FND_LOOKUPS 
	WHERE LOOKUP_TYPE = 'FND_VS_VARCHAR2_SUBTYPES'
		AND LOOKUP_CODE = fndVSVauleSetEO.VALUE_SUBTYPE
			)	RES_VALUE_SUBTYPE
,fndVSVauleSetEO.MAXIMUM_LENGTH 		RES_MAXIMUM_LENGTH
,fndVSVauleSetEO.PRECISION 				RES_PRECISION
,fndVSVauleSetEO.SCALE					RES_SCALE
,fndVSVauleSetEO.MINIMUM_VALUE			RES_MINIMUM_VALUE
,fndVSVauleSetEO.MAXIMUM_VALUE			RES_MAXIMUM_VALUE
,DECODE(fndVSVauleSetEO.ZERO_FILL_FLAG,'Y','Yes','No')		RES_UPPERCASE_ONLY
,DECODE(fndVSVauleSetEO.UPPERCASE_ONLY_FLAG,'Y','Yes','No')	RES_ZERO_FILL
,fndVSVauleSetEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,fndVSVauleSetEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,fndVSVauleSetEO.CREATED_BY RSC_CREATED_BY
,fndVSVauleSetEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FND_VS_VALUE_SETS fndVSVauleSetEO
WHERE fndVSVauleSetEO.VALUE_SET_CODE = 'Accounting Scenario'
ORDER BY fndVSVauleSetEO.VALUE_SET_CODE