/* ****************************************************************************
 * $Revision: 58428 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-09-23 18:27:01 +0700 (Fri, 23 Sep 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/customized/In%20Develop/reverse_sql/Manage%20Units%20of%20Measure%20Profiles%20-%20Profile%20Values.sql $:
 * $Id: Manage Units of Measure Profiles - Profile Values.sql 58428 2016-09-23 11:27:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EGP_SYSTEM_ITEMS_B
-- STRICTLY_BATCH_SEQ = RES_ITEM_NUMBER,RES_ORGANIZATION_CODE

SELECT /*+ PARALLEL(8) */ 'CREATE' RES_TRANSACTION_TYPE
,'' RES_BATCH_ID
,'' RES_BATCH_NUMBER
,ItemsE0.ITEM_NUMBER RES_ITEM_NUMBER
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemsE0.ORGANIZATION_ID
	) RES_ORGANIZATION_CODE
,RevisionsE0.REVISION RES_REVISION
,'' RES_SOURCE_SYSTEM_CODE
,'' RES_SOURCE_SYSTEM_REFERENCE
,revisionEFFE0.CONTEXT_CODE RES_ATTRIBUTE_GROUP_CODE
,revisionEFFE0.ATTRIBUTE_CHAR1 RES_ATTRIBUTE_CHAR1
,revisionEFFE0.ATTRIBUTE_CHAR2 RES_ATTRIBUTE_CHAR2
,revisionEFFE0.ATTRIBUTE_CHAR3 RES_ATTRIBUTE_CHAR3
,revisionEFFE0.ATTRIBUTE_CHAR4 RES_ATTRIBUTE_CHAR4
,revisionEFFE0.ATTRIBUTE_CHAR5 RES_ATTRIBUTE_CHAR5
,revisionEFFE0.ATTRIBUTE_CHAR6 RES_ATTRIBUTE_CHAR6
,revisionEFFE0.ATTRIBUTE_CHAR7 RES_ATTRIBUTE_CHAR7
,revisionEFFE0.ATTRIBUTE_CHAR8 RES_ATTRIBUTE_CHAR8
,revisionEFFE0.ATTRIBUTE_CHAR9 RES_ATTRIBUTE_CHAR9
,revisionEFFE0.ATTRIBUTE_CHAR10 RES_ATTRIBUTE_CHAR10
,revisionEFFE0.ATTRIBUTE_CHAR11 RES_ATTRIBUTE_CHAR11
,revisionEFFE0.ATTRIBUTE_CHAR12 RES_ATTRIBUTE_CHAR12
,revisionEFFE0.ATTRIBUTE_CHAR13 RES_ATTRIBUTE_CHAR13
,revisionEFFE0.ATTRIBUTE_CHAR14 RES_ATTRIBUTE_CHAR14
,revisionEFFE0.ATTRIBUTE_CHAR15 RES_ATTRIBUTE_CHAR15
,revisionEFFE0.ATTRIBUTE_CHAR16 RES_ATTRIBUTE_CHAR16
,revisionEFFE0.ATTRIBUTE_CHAR17 RES_ATTRIBUTE_CHAR17
,revisionEFFE0.ATTRIBUTE_CHAR18 RES_ATTRIBUTE_CHAR18
,revisionEFFE0.ATTRIBUTE_CHAR19 RES_ATTRIBUTE_CHAR19
,revisionEFFE0.ATTRIBUTE_CHAR20 RES_ATTRIBUTE_CHAR20
,revisionEFFE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,revisionEFFE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,revisionEFFE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,revisionEFFE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,revisionEFFE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,revisionEFFE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,revisionEFFE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,revisionEFFE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,revisionEFFE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,revisionEFFE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE1,'YYYY/MM/DD') RES_ATTRIBUTE_DATE1
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE2,'YYYY/MM/DD') RES_ATTRIBUTE_DATE2
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE3,'YYYY/MM/DD') RES_ATTRIBUTE_DATE3
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE4,'YYYY/MM/DD') RES_ATTRIBUTE_DATE4
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE5,'YYYY/MM/DD') RES_ATTRIBUTE_DATE5
,revisionEFFE0.ATTRIBUTE_CHAR21 RES_ATTRIBUTE_CHAR21
,revisionEFFE0.ATTRIBUTE_CHAR22 RES_ATTRIBUTE_CHAR22
,revisionEFFE0.ATTRIBUTE_CHAR23 RES_ATTRIBUTE_CHAR23
,revisionEFFE0.ATTRIBUTE_CHAR24 RES_ATTRIBUTE_CHAR24
,revisionEFFE0.ATTRIBUTE_CHAR25 RES_ATTRIBUTE_CHAR25
,revisionEFFE0.ATTRIBUTE_CHAR26 RES_ATTRIBUTE_CHAR26
,revisionEFFE0.ATTRIBUTE_CHAR27 RES_ATTRIBUTE_CHAR27
,revisionEFFE0.ATTRIBUTE_CHAR28 RES_ATTRIBUTE_CHAR28
,revisionEFFE0.ATTRIBUTE_CHAR29 RES_ATTRIBUTE_CHAR29
,revisionEFFE0.ATTRIBUTE_CHAR30 RES_ATTRIBUTE_CHAR30
,revisionEFFE0.ATTRIBUTE_CHAR31 RES_ATTRIBUTE_CHAR31
,revisionEFFE0.ATTRIBUTE_CHAR32 RES_ATTRIBUTE_CHAR32
,revisionEFFE0.ATTRIBUTE_CHAR33 RES_ATTRIBUTE_CHAR33
,revisionEFFE0.ATTRIBUTE_CHAR34 RES_ATTRIBUTE_CHAR34
,revisionEFFE0.ATTRIBUTE_CHAR35 RES_ATTRIBUTE_CHAR35
,revisionEFFE0.ATTRIBUTE_CHAR36 RES_ATTRIBUTE_CHAR36
,revisionEFFE0.ATTRIBUTE_CHAR37 RES_ATTRIBUTE_CHAR37
,revisionEFFE0.ATTRIBUTE_CHAR38 RES_ATTRIBUTE_CHAR38
,revisionEFFE0.ATTRIBUTE_CHAR39 RES_ATTRIBUTE_CHAR39
,revisionEFFE0.ATTRIBUTE_CHAR40 RES_ATTRIBUTE_CHAR40
,revisionEFFE0.ATTRIBUTE_NUMBER11 RES_ATTRIBUTE_NUMBER11
,revisionEFFE0.ATTRIBUTE_NUMBER12 RES_ATTRIBUTE_NUMBER12
,revisionEFFE0.ATTRIBUTE_NUMBER13 RES_ATTRIBUTE_NUMBER13
,revisionEFFE0.ATTRIBUTE_NUMBER14 RES_ATTRIBUTE_NUMBER14
,revisionEFFE0.ATTRIBUTE_NUMBER15 RES_ATTRIBUTE_NUMBER15
,revisionEFFE0.ATTRIBUTE_NUMBER16 RES_ATTRIBUTE_NUMBER16
,revisionEFFE0.ATTRIBUTE_NUMBER17 RES_ATTRIBUTE_NUMBER17
,revisionEFFE0.ATTRIBUTE_NUMBER18 RES_ATTRIBUTE_NUMBER18
,revisionEFFE0.ATTRIBUTE_NUMBER19 RES_ATTRIBUTE_NUMBER19
,revisionEFFE0.ATTRIBUTE_NUMBER20 RES_ATTRIBUTE_NUMBER20
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE6,'YYYY/MM/DD') RES_ATTRIBUTE_DATE6
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE7,'YYYY/MM/DD') RES_ATTRIBUTE_DATE7
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE8,'YYYY/MM/DD') RES_ATTRIBUTE_DATE8
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE9,'YYYY/MM/DD') RES_ATTRIBUTE_DATE9
,TO_CHAR(revisionEFFE0.ATTRIBUTE_DATE10,'YYYY/MM/DD') RES_ATTRIBUTE_DATE10
,revisionEFFE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,revisionEFFE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,revisionEFFE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,revisionEFFE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,revisionEFFE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,revisionEFFE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,revisionEFFE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,revisionEFFE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,revisionEFFE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,revisionEFFE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,TO_CHAR(revisionEFFE0.VERSION_START_DATE,'YYYY/MM/DD') RES_VERSION_START_DATE
,(SELECT VERSION_CODE
	FROM EGO_VERSIONS_B
	WHERE VERSION_ID = revisionEFFE0.VERSION_ID
	) RES_VERSION_REVISION_CODE
,revisionEFFE0.ATTRIBUTE_NUMBER1_UOM RES_ATTRIBUTE_NUMBER1_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER2_UOM RES_ATTRIBUTE_NUMBER2_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER3_UOM RES_ATTRIBUTE_NUMBER3_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER4_UOM RES_ATTRIBUTE_NUMBER4_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER5_UOM RES_ATTRIBUTE_NUMBER5_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER6_UOM RES_ATTRIBUTE_NUMBER6_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER7_UOM RES_ATTRIBUTE_NUMBER7_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER8_UOM RES_ATTRIBUTE_NUMBER8_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER9_UOM RES_ATTRIBUTE_NUMBER9_UOM_NAME
,revisionEFFE0.ATTRIBUTE_NUMBER10_UOM RES_ATTRIBUTE_NUMBER10_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER11_UOM RES_ATTRIBUTE_NUMBER11_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER12_UOM RES_ATTRIBUTE_NUMBER12_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER13_UOM RES_ATTRIBUTE_NUMBER13_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER14_UOM RES_ATTRIBUTE_NUMBER14_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER15_UOM RES_ATTRIBUTE_NUMBER15_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER16_UOM RES_ATTRIBUTE_NUMBER16_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER17_UOM RES_ATTRIBUTE_NUMBER17_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER18_UOM RES_ATTRIBUTE_NUMBER18_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER19_UOM RES_ATTRIBUTE_NUMBER19_UOM_NAM
,revisionEFFE0.ATTRIBUTE_NUMBER20_UOM RES_ATTRIBUTE_NUMBER20_UOM_NAM
,'' RES_ATTRIBUTE_NUMBER1_UE
,'' RES_ATTRIBUTE_NUMBER2_UE
,'' RES_ATTRIBUTE_NUMBER3_UE
,'' RES_ATTRIBUTE_NUMBER4_UE
,'' RES_ATTRIBUTE_NUMBER5_UE
,'' RES_ATTRIBUTE_NUMBER6_UE
,'' RES_ATTRIBUTE_NUMBER7_UE
,'' RES_ATTRIBUTE_NUMBER8_UE
,'' RES_ATTRIBUTE_NUMBER9_UE
,'' RES_ATTRIBUTE_NUMBER10_UE
,'' RES_ATTRIBUTE_NUMBER11_UE
,'' RES_ATTRIBUTE_NUMBER12_UE
,'' RES_ATTRIBUTE_NUMBER13_UE
,'' RES_ATTRIBUTE_NUMBER14_UE
,'' RES_ATTRIBUTE_NUMBER15_UE
,'' RES_ATTRIBUTE_NUMBER16_UE
,'' RES_ATTRIBUTE_NUMBER17_UE
,'' RES_ATTRIBUTE_NUMBER18_UE
,'' RES_ATTRIBUTE_NUMBER19_UE
,'' RES_ATTRIBUTE_NUMBER20_UE
,revisionEFFE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,revisionEFFE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,revisionEFFE0.CREATED_BY  RSC_CREATED_BY
,revisionEFFE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,ItemsE0.ORGANIZATION_ID RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_SYSTEM_ITEMS_B ItemsE0
,EGP_ITEM_REVISIONS_B RevisionsE0
,EGO_ITEM_REVISION_EFF_B revisionEFFE0
WHERE ItemsE0.INVENTORY_ITEM_ID = RevisionsE0.INVENTORY_ITEM_ID
AND ItemsE0.ORGANIZATION_ID = RevisionsE0.ORGANIZATION_ID
AND RevisionsE0.REVISION_ID = revisionEFFE0.REVISION_ID
AND ItemsE0.TEMPLATE_ITEM_FLAG = 'N'
AND ItemsE0.ACD_TYPE = 'PROD'