/* ****************************************************************************
 * $Revision: 58428 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-09-23 18:27:01 +0700 (Fri, 23 Sep 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/customized/In%20Develop/reverse_sql/Manage%20Units%20of%20Measure%20Profiles%20-%20Profile%20Values.sql $:
 * $Id: Manage Units of Measure Profiles - Profile Values.sql 58428 2016-09-23 11:27:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- STRICTLY_BATCH_SEQ = RES_ITEM_NUMBER,RES_ORGANIZATION_CODE,RES_REVISION

SELECT /*+ PARALLEL(8) */ 'CREATE' RES_TRANSACTION_TYPE
,'' RES_BATCH_ID
,'' RES_BATCH_NUMBER
,ItemsE0.ITEM_NUMBER RES_ITEM_NUMBER
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemsE0.ORGANIZATION_ID
	) RES_ORGANIZATION_CODE
,RevisionsE0.REVISION RES_REVISION
,RevisionsE0.REVISION_REASON RES_REVISION_REASON
,'' RES_SOURCE_SYSTEM_CODE
,'' RES_SOURCE_SYSTEM_REFERENCE
,(SELECT DESCRIPTION
	FROM EGP_ITEM_REVISIONS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND REVISION_ID = RevisionsE0.REVISION_ID
	) RES_DESCRIPTION
,TO_CHAR(RevisionsE0.EFFECTIVITY_DATE,'YYYY/MM/DD') RES_EFFECTIVITY_DATE
,TO_CHAR(RevisionsE0.ECN_INITIATION_DATE,'YYYY/MM/DD') RES_ECN_INITIATION_DATE
,TO_CHAR(RevisionsE0.IMPLEMENTATION_DATE,'YYYY/MM/DD') RES_IMPLEMENTATION_DATE
,RevisionsE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,RevisionsE0.ATTRIBUTE1 RES_ATTRIBUTE1
,RevisionsE0.ATTRIBUTE2 RES_ATTRIBUTE2
,RevisionsE0.ATTRIBUTE3 RES_ATTRIBUTE3
,RevisionsE0.ATTRIBUTE4 RES_ATTRIBUTE4
,RevisionsE0.ATTRIBUTE5 RES_ATTRIBUTE5
,RevisionsE0.ATTRIBUTE6 RES_ATTRIBUTE6
,RevisionsE0.ATTRIBUTE7 RES_ATTRIBUTE7
,RevisionsE0.ATTRIBUTE8 RES_ATTRIBUTE8
,RevisionsE0.ATTRIBUTE9 RES_ATTRIBUTE9
,RevisionsE0.ATTRIBUTE10 RES_ATTRIBUTE10
,RevisionsE0.ATTRIBUTE11 RES_ATTRIBUTE11
,RevisionsE0.ATTRIBUTE12 RES_ATTRIBUTE12
,RevisionsE0.ATTRIBUTE13 RES_ATTRIBUTE13
,RevisionsE0.ATTRIBUTE14 RES_ATTRIBUTE14
,RevisionsE0.ATTRIBUTE15 RES_ATTRIBUTE15
,RevisionsE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,RevisionsE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,RevisionsE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,RevisionsE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,RevisionsE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,RevisionsE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,RevisionsE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,RevisionsE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,RevisionsE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,RevisionsE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,TO_CHAR(RevisionsE0.ATTRIBUTE_DATE1,'YYYY/MM/DD') RES_ATTRIBUTE_DATE1
,TO_CHAR(RevisionsE0.ATTRIBUTE_DATE2,'YYYY/MM/DD') RES_ATTRIBUTE_DATE2
,TO_CHAR(RevisionsE0.ATTRIBUTE_DATE3,'YYYY/MM/DD') RES_ATTRIBUTE_DATE3
,TO_CHAR(RevisionsE0.ATTRIBUTE_DATE4,'YYYY/MM/DD') RES_ATTRIBUTE_DATE4
,TO_CHAR(RevisionsE0.ATTRIBUTE_DATE5,'YYYY/MM/DD') RES_ATTRIBUTE_DATE5
,RevisionsE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,RevisionsE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,RevisionsE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,RevisionsE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,RevisionsE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,RevisionsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,RevisionsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,RevisionsE0.CREATED_BY  RSC_CREATED_BY
,RevisionsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,ItemsE0.ORGANIZATION_ID RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_SYSTEM_ITEMS_B ItemsE0
,EGP_ITEM_REVISIONS_B RevisionsE0
WHERE ItemsE0.INVENTORY_ITEM_ID = RevisionsE0.INVENTORY_ITEM_ID
AND ItemsE0.ORGANIZATION_ID = RevisionsE0.ORGANIZATION_ID
AND ItemsE0.TEMPLATE_ITEM_FLAG = 'N'
ORDER BY RevisionsE0.CREATION_DATE