/* ****************************************************************************
 * $Revision: 58428 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-09-23 18:27:01 +0700 (Fri, 23 Sep 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/customized/In%20Develop/reverse_sql/Manage%20Units%20of%20Measure%20Profiles%20-%20Profile%20Values.sql $:
 * $Id: Manage Units of Measure Profiles - Profile Values.sql 58428 2016-09-23 11:27:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EGP_SYSTEM_ITEMS_B
-- STRICTLY_BATCH_SEQ = RES_ITEM_NUMBER,RES_ORGANIZATION_CODE

SELECT /*+ PARALLEL(8) */ 'CREATE' RES_TRANSACTION_TYPE
,'' RES_BATCH_ID
,'' RES_BATCH_NUMBER
,ItemsE0.ITEM_NUMBER RES_ITEM_NUMBER
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemsE0.ORGANIZATION_ID
	) RES_ORGANIZATION_CODE
,RevisionsE0.REVISION RES_REVISION
,'' RES_SOURCE_SYSTEM_CODE
,'' RES_SOURCE_SYSTEM_REFERENCE
,'' RES_TRADING_PARTNER_ITEM_NUMBE
,'' RES_TRADING_PARTNER_NUMBER
,'' RES_ENTITY_TYPE
,'' RES_BATCH_DOC_NAME
,(SELECT USER_NAME
	FROM FND_DOCUMENT_CATEGORIES_VL
	WHERE CATEGORY_NAME = attachedDocsE0.CATEGORY_NAME
	) RES_ATTACHMENT_CATEGORY
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'FND_DOCUMENT_DATATYPES'
	AND LOOKUP_CODE = docsE0.DATATYPE_CODE
	) RES_FILE_TYPE_NAME
,docsE0.URL RES_FILE_URL_TEXT
,docsE0.TITLE RES_TITLE
,(CASE
	WHEN docsE0.DM_FOLDER_PATH IS NOT NULL THEN	'Y'
	ELSE 'N'
	END) RES_SHARED
,docsE0.DESCRIPTION RES_DESCRIPTION
,attachedDocsE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,attachedDocsE0.ATTRIBUTE1 RES_ATTRIBUTE_1
,attachedDocsE0.ATTRIBUTE2 RES_ATTRIBUTE_2
,attachedDocsE0.ATTRIBUTE3 RES_ATTRIBUTE_3
,attachedDocsE0.ATTRIBUTE4 RES_ATTRIBUTE_4
,attachedDocsE0.ATTRIBUTE5 RES_ATTRIBUTE_5
,attachedDocsE0.ATTRIBUTE6 RES_ATTRIBUTE_6
,attachedDocsE0.ATTRIBUTE7 RES_ATTRIBUTE_7
,attachedDocsE0.ATTRIBUTE8 RES_ATTRIBUTE_8
,attachedDocsE0.ATTRIBUTE9 RES_ATTRIBUTE_9
,attachedDocsE0.ATTRIBUTE10 RES_ATTRIBUTE_10
,attachedDocsE0.ATTRIBUTE11 RES_ATTRIBUTE_11
,attachedDocsE0.ATTRIBUTE12 RES_ATTRIBUTE_12
,attachedDocsE0.ATTRIBUTE13 RES_ATTRIBUTE_13
,attachedDocsE0.ATTRIBUTE14 RES_ATTRIBUTE_14
,attachedDocsE0.ATTRIBUTE15 RES_ATTRIBUTE_15
,attachedDocsE0.ATTRIBUTE16 RES_ATTRIBUTE_16
,attachedDocsE0.ATTRIBUTE17 RES_ATTRIBUTE_17
,attachedDocsE0.ATTRIBUTE18 RES_ATTRIBUTE_18
,attachedDocsE0.ATTRIBUTE19 RES_ATTRIBUTE_19
,attachedDocsE0.ATTRIBUTE20 RES_ATTRIBUTE_20
,attachedDocsE0.ATTRIBUTE21 RES_ATTRIBUTE_21
,attachedDocsE0.ATTRIBUTE22 RES_ATTRIBUTE_22
,attachedDocsE0.ATTRIBUTE23 RES_ATTRIBUTE_23
,attachedDocsE0.ATTRIBUTE24 RES_ATTRIBUTE_24
,attachedDocsE0.ATTRIBUTE25 RES_ATTRIBUTE_25
,attachedDocsE0.ATTRIBUTE26 RES_ATTRIBUTE_26
,attachedDocsE0.ATTRIBUTE27 RES_ATTRIBUTE_27
,attachedDocsE0.ATTRIBUTE28 RES_ATTRIBUTE_28
,attachedDocsE0.ATTRIBUTE29 RES_ATTRIBUTE_29
,attachedDocsE0.ATTRIBUTE30 RES_ATTRIBUTE_30
,attachedDocsE0.ATTRIBUTE31 RES_ATTRIBUTE_31
,attachedDocsE0.ATTRIBUTE32 RES_ATTRIBUTE_32
,attachedDocsE0.ATTRIBUTE33 RES_ATTRIBUTE_33
,attachedDocsE0.ATTRIBUTE34 RES_ATTRIBUTE_34
,attachedDocsE0.ATTRIBUTE35 RES_ATTRIBUTE_35
,attachedDocsE0.ATTRIBUTE36 RES_ATTRIBUTE_36
,attachedDocsE0.ATTRIBUTE37 RES_ATTRIBUTE_37
,attachedDocsE0.ATTRIBUTE38 RES_ATTRIBUTE_38
,attachedDocsE0.ATTRIBUTE39 RES_ATTRIBUTE_39
,attachedDocsE0.ATTRIBUTE40 RES_ATTRIBUTE_40
,attachedDocsE0.ATTRIBUTE41 RES_ATTRIBUTE_41
,attachedDocsE0.ATTRIBUTE42 RES_ATTRIBUTE_42
,attachedDocsE0.ATTRIBUTE43 RES_ATTRIBUTE_43
,attachedDocsE0.ATTRIBUTE44 RES_ATTRIBUTE_44
,attachedDocsE0.ATTRIBUTE45 RES_ATTRIBUTE_45
,attachedDocsE0.ATTRIBUTE46 RES_ATTRIBUTE_46
,attachedDocsE0.ATTRIBUTE47 RES_ATTRIBUTE_47
,attachedDocsE0.ATTRIBUTE48 RES_ATTRIBUTE_48
,attachedDocsE0.ATTRIBUTE49 RES_ATTRIBUTE_49
,attachedDocsE0.ATTRIBUTE50 RES_ATTRIBUTE_50
,attachedDocsE0.ATTRIBUTE51 RES_ATTRIBUTE_51
,attachedDocsE0.ATTRIBUTE52 RES_ATTRIBUTE_52
,attachedDocsE0.ATTRIBUTE53 RES_ATTRIBUTE_53
,attachedDocsE0.ATTRIBUTE54 RES_ATTRIBUTE_54
,attachedDocsE0.ATTRIBUTE55 RES_ATTRIBUTE_55
,attachedDocsE0.ATTRIBUTE56 RES_ATTRIBUTE_56
,attachedDocsE0.ATTRIBUTE57 RES_ATTRIBUTE_57
,attachedDocsE0.ATTRIBUTE58 RES_ATTRIBUTE_58
,attachedDocsE0.ATTRIBUTE59 RES_ATTRIBUTE_59
,attachedDocsE0.ATTRIBUTE60 RES_ATTRIBUTE_60
,attachedDocsE0.ATTRIBUTE61 RES_ATTRIBUTE_61
,attachedDocsE0.ATTRIBUTE62 RES_ATTRIBUTE_62
,attachedDocsE0.ATTRIBUTE63 RES_ATTRIBUTE_63
,attachedDocsE0.ATTRIBUTE64 RES_ATTRIBUTE_64
,attachedDocsE0.ATTRIBUTE65 RES_ATTRIBUTE_65
,attachedDocsE0.ATTRIBUTE66 RES_ATTRIBUTE_66
,attachedDocsE0.ATTRIBUTE67 RES_ATTRIBUTE_67
,attachedDocsE0.ATTRIBUTE68 RES_ATTRIBUTE_68
,attachedDocsE0.ATTRIBUTE69 RES_ATTRIBUTE_69
,attachedDocsE0.ATTRIBUTE70 RES_ATTRIBUTE_70
,attachedDocsE0.ATTRIBUTE71 RES_ATTRIBUTE_71
,attachedDocsE0.ATTRIBUTE72 RES_ATTRIBUTE_72
,attachedDocsE0.ATTRIBUTE73 RES_ATTRIBUTE_73
,attachedDocsE0.ATTRIBUTE74 RES_ATTRIBUTE_74
,attachedDocsE0.ATTRIBUTE75 RES_ATTRIBUTE_75
,attachedDocsE0.ATTRIBUTE76 RES_ATTRIBUTE_76
,attachedDocsE0.ATTRIBUTE77 RES_ATTRIBUTE_77
,attachedDocsE0.ATTRIBUTE78 RES_ATTRIBUTE_78
,attachedDocsE0.ATTRIBUTE79 RES_ATTRIBUTE_79
,attachedDocsE0.ATTRIBUTE80 RES_ATTRIBUTE_80
,attachedDocsE0.ATTRIBUTE81 RES_ATTRIBUTE_81
,attachedDocsE0.ATTRIBUTE82 RES_ATTRIBUTE_82
,attachedDocsE0.ATTRIBUTE83 RES_ATTRIBUTE_83
,attachedDocsE0.ATTRIBUTE84 RES_ATTRIBUTE_84
,attachedDocsE0.ATTRIBUTE85 RES_ATTRIBUTE_85
,attachedDocsE0.ATTRIBUTE86 RES_ATTRIBUTE_86
,attachedDocsE0.ATTRIBUTE87 RES_ATTRIBUTE_87
,attachedDocsE0.ATTRIBUTE88 RES_ATTRIBUTE_88
,attachedDocsE0.ATTRIBUTE89 RES_ATTRIBUTE_89
,attachedDocsE0.ATTRIBUTE90 RES_ATTRIBUTE_90
,attachedDocsE0.ATTRIBUTE91 RES_ATTRIBUTE_91
,attachedDocsE0.ATTRIBUTE92 RES_ATTRIBUTE_92
,attachedDocsE0.ATTRIBUTE93 RES_ATTRIBUTE_93
,attachedDocsE0.ATTRIBUTE94 RES_ATTRIBUTE_94
,attachedDocsE0.ATTRIBUTE95 RES_ATTRIBUTE_95
,attachedDocsE0.ATTRIBUTE96 RES_ATTRIBUTE_96
,attachedDocsE0.ATTRIBUTE97 RES_ATTRIBUTE_97
,attachedDocsE0.ATTRIBUTE98 RES_ATTRIBUTE_98
,attachedDocsE0.ATTRIBUTE99 RES_ATTRIBUTE_99
,attachedDocsE0.ATTRIBUTE100 RES_ATTRIBUTE_100
,attachedDocsE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,attachedDocsE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,attachedDocsE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,attachedDocsE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,attachedDocsE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,attachedDocsE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,attachedDocsE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,attachedDocsE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,attachedDocsE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,attachedDocsE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,attachedDocsE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_DATE1
,attachedDocsE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_DATE2
,attachedDocsE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_DATE3
,attachedDocsE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_DATE4
,attachedDocsE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_DATE5
,attachedDocsE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_DATE6
,attachedDocsE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_DATE7
,attachedDocsE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_DATE8
,attachedDocsE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_DATE9
,attachedDocsE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_DATE10
,attachedDocsE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,attachedDocsE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,attachedDocsE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,attachedDocsE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,attachedDocsE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,attachedDocsE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,docsE0.DM_DOCUMENT_ID RES_DOCUMENT_ID --> NEW
,docsE0.DM_VERSION_NUMBER RES_DOCUMENT_VERSION_NUMBER --> NEW
,attachedDocsE0.PRIMARY_CATEGORY_FLAG RES_PRIMARY_CATEGORY_FLAG --> NEW
,'' RES_NEW_ATTACHMENT_CATEGORY --> NEW
,'' RES_NEW_FILE_URL_TEXT --> NEW
,'' RES_NEW_TITLE --> NEW
,attachedDocsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,attachedDocsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,attachedDocsE0.CREATED_BY  RSC_CREATED_BY
,attachedDocsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,ItemsE0.ORGANIZATION_ID RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_SYSTEM_ITEMS_B ItemsE0
,EGP_ITEM_REVISIONS_B RevisionsE0
,(SELECT *
	FROM FND_ATTACHED_DOCUMENTS
	WHERE ENTITY_NAME = 'ITEM_ENTITY'
	) attachedDocsE0
,FND_DOCUMENTS_VL docsE0
WHERE ItemsE0.INVENTORY_ITEM_ID = RevisionsE0.INVENTORY_ITEM_ID
AND ItemsE0.ORGANIZATION_ID = RevisionsE0.ORGANIZATION_ID
AND attachedDocsE0.PK1_VALUE = ItemsE0.ORGANIZATION_ID
AND attachedDocsE0.PK2_VALUE = ItemsE0.INVENTORY_ITEM_ID
AND attachedDocsE0.DOCUMENT_ID = docsE0.DOCUMENT_ID

UNION

SELECT /*+ PARALLEL(8) */ 'CREATE' RES_TRANSACTION_TYPE
,'' RES_BATCH_ID
,'' RES_BATCH_NUMBER
,'' RES_ITEM_NUMBER
,'' RES_ORGANIZATION_CODE
,'' RES_REVISION
,'' RES_SOURCE_SYSTEM_CODE
,'' RES_SOURCE_SYSTEM_REFERENCE
,tradingPartnersE0.TP_ITEM_NUMBER RES_TRADING_PARTNER_ITEM_NUMBE
,partiesE0.PARTY_NUMBER RES_TRADING_PARTNER_NUMBER
,'' RES_ENTITY_TYPE
,'' RES_BATCH_DOC_NAME
,(SELECT USER_NAME
	FROM FND_DOCUMENT_CATEGORIES_VL
	WHERE CATEGORY_NAME = attachedDocsE0.CATEGORY_NAME
	) RES_ATTACHMENT_CATEGORY
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'FND_DOCUMENT_DATATYPES'
	AND LOOKUP_CODE = docsE0.DATATYPE_CODE
	) RES_FILE_TYPE_NAME
,docsE0.URL RES_FILE_URL_TEXT
,docsE0.TITLE RES_TITLE
,(CASE
	WHEN docsE0.DM_FOLDER_PATH IS NOT NULL THEN	'Y'
	ELSE 'N'
	END) RES_SHARED
,docsE0.DESCRIPTION RES_DESCRIPTION
,attachedDocsE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,attachedDocsE0.ATTRIBUTE1 RES_ATTRIBUTE_1
,attachedDocsE0.ATTRIBUTE2 RES_ATTRIBUTE_2
,attachedDocsE0.ATTRIBUTE3 RES_ATTRIBUTE_3
,attachedDocsE0.ATTRIBUTE4 RES_ATTRIBUTE_4
,attachedDocsE0.ATTRIBUTE5 RES_ATTRIBUTE_5
,attachedDocsE0.ATTRIBUTE6 RES_ATTRIBUTE_6
,attachedDocsE0.ATTRIBUTE7 RES_ATTRIBUTE_7
,attachedDocsE0.ATTRIBUTE8 RES_ATTRIBUTE_8
,attachedDocsE0.ATTRIBUTE9 RES_ATTRIBUTE_9
,attachedDocsE0.ATTRIBUTE10 RES_ATTRIBUTE_10
,attachedDocsE0.ATTRIBUTE11 RES_ATTRIBUTE_11
,attachedDocsE0.ATTRIBUTE12 RES_ATTRIBUTE_12
,attachedDocsE0.ATTRIBUTE13 RES_ATTRIBUTE_13
,attachedDocsE0.ATTRIBUTE14 RES_ATTRIBUTE_14
,attachedDocsE0.ATTRIBUTE15 RES_ATTRIBUTE_15
,attachedDocsE0.ATTRIBUTE16 RES_ATTRIBUTE_16
,attachedDocsE0.ATTRIBUTE17 RES_ATTRIBUTE_17
,attachedDocsE0.ATTRIBUTE18 RES_ATTRIBUTE_18
,attachedDocsE0.ATTRIBUTE19 RES_ATTRIBUTE_19
,attachedDocsE0.ATTRIBUTE20 RES_ATTRIBUTE_20
,attachedDocsE0.ATTRIBUTE21 RES_ATTRIBUTE_21
,attachedDocsE0.ATTRIBUTE22 RES_ATTRIBUTE_22
,attachedDocsE0.ATTRIBUTE23 RES_ATTRIBUTE_23
,attachedDocsE0.ATTRIBUTE24 RES_ATTRIBUTE_24
,attachedDocsE0.ATTRIBUTE25 RES_ATTRIBUTE_25
,attachedDocsE0.ATTRIBUTE26 RES_ATTRIBUTE_26
,attachedDocsE0.ATTRIBUTE27 RES_ATTRIBUTE_27
,attachedDocsE0.ATTRIBUTE28 RES_ATTRIBUTE_28
,attachedDocsE0.ATTRIBUTE29 RES_ATTRIBUTE_29
,attachedDocsE0.ATTRIBUTE30 RES_ATTRIBUTE_30
,attachedDocsE0.ATTRIBUTE31 RES_ATTRIBUTE_31
,attachedDocsE0.ATTRIBUTE32 RES_ATTRIBUTE_32
,attachedDocsE0.ATTRIBUTE33 RES_ATTRIBUTE_33
,attachedDocsE0.ATTRIBUTE34 RES_ATTRIBUTE_34
,attachedDocsE0.ATTRIBUTE35 RES_ATTRIBUTE_35
,attachedDocsE0.ATTRIBUTE36 RES_ATTRIBUTE_36
,attachedDocsE0.ATTRIBUTE37 RES_ATTRIBUTE_37
,attachedDocsE0.ATTRIBUTE38 RES_ATTRIBUTE_38
,attachedDocsE0.ATTRIBUTE39 RES_ATTRIBUTE_39
,attachedDocsE0.ATTRIBUTE40 RES_ATTRIBUTE_40
,attachedDocsE0.ATTRIBUTE41 RES_ATTRIBUTE_41
,attachedDocsE0.ATTRIBUTE42 RES_ATTRIBUTE_42
,attachedDocsE0.ATTRIBUTE43 RES_ATTRIBUTE_43
,attachedDocsE0.ATTRIBUTE44 RES_ATTRIBUTE_44
,attachedDocsE0.ATTRIBUTE45 RES_ATTRIBUTE_45
,attachedDocsE0.ATTRIBUTE46 RES_ATTRIBUTE_46
,attachedDocsE0.ATTRIBUTE47 RES_ATTRIBUTE_47
,attachedDocsE0.ATTRIBUTE48 RES_ATTRIBUTE_48
,attachedDocsE0.ATTRIBUTE49 RES_ATTRIBUTE_49
,attachedDocsE0.ATTRIBUTE50 RES_ATTRIBUTE_50
,attachedDocsE0.ATTRIBUTE51 RES_ATTRIBUTE_51
,attachedDocsE0.ATTRIBUTE52 RES_ATTRIBUTE_52
,attachedDocsE0.ATTRIBUTE53 RES_ATTRIBUTE_53
,attachedDocsE0.ATTRIBUTE54 RES_ATTRIBUTE_54
,attachedDocsE0.ATTRIBUTE55 RES_ATTRIBUTE_55
,attachedDocsE0.ATTRIBUTE56 RES_ATTRIBUTE_56
,attachedDocsE0.ATTRIBUTE57 RES_ATTRIBUTE_57
,attachedDocsE0.ATTRIBUTE58 RES_ATTRIBUTE_58
,attachedDocsE0.ATTRIBUTE59 RES_ATTRIBUTE_59
,attachedDocsE0.ATTRIBUTE60 RES_ATTRIBUTE_60
,attachedDocsE0.ATTRIBUTE61 RES_ATTRIBUTE_61
,attachedDocsE0.ATTRIBUTE62 RES_ATTRIBUTE_62
,attachedDocsE0.ATTRIBUTE63 RES_ATTRIBUTE_63
,attachedDocsE0.ATTRIBUTE64 RES_ATTRIBUTE_64
,attachedDocsE0.ATTRIBUTE65 RES_ATTRIBUTE_65
,attachedDocsE0.ATTRIBUTE66 RES_ATTRIBUTE_66
,attachedDocsE0.ATTRIBUTE67 RES_ATTRIBUTE_67
,attachedDocsE0.ATTRIBUTE68 RES_ATTRIBUTE_68
,attachedDocsE0.ATTRIBUTE69 RES_ATTRIBUTE_69
,attachedDocsE0.ATTRIBUTE70 RES_ATTRIBUTE_70
,attachedDocsE0.ATTRIBUTE71 RES_ATTRIBUTE_71
,attachedDocsE0.ATTRIBUTE72 RES_ATTRIBUTE_72
,attachedDocsE0.ATTRIBUTE73 RES_ATTRIBUTE_73
,attachedDocsE0.ATTRIBUTE74 RES_ATTRIBUTE_74
,attachedDocsE0.ATTRIBUTE75 RES_ATTRIBUTE_75
,attachedDocsE0.ATTRIBUTE76 RES_ATTRIBUTE_76
,attachedDocsE0.ATTRIBUTE77 RES_ATTRIBUTE_77
,attachedDocsE0.ATTRIBUTE78 RES_ATTRIBUTE_78
,attachedDocsE0.ATTRIBUTE79 RES_ATTRIBUTE_79
,attachedDocsE0.ATTRIBUTE80 RES_ATTRIBUTE_80
,attachedDocsE0.ATTRIBUTE81 RES_ATTRIBUTE_81
,attachedDocsE0.ATTRIBUTE82 RES_ATTRIBUTE_82
,attachedDocsE0.ATTRIBUTE83 RES_ATTRIBUTE_83
,attachedDocsE0.ATTRIBUTE84 RES_ATTRIBUTE_84
,attachedDocsE0.ATTRIBUTE85 RES_ATTRIBUTE_85
,attachedDocsE0.ATTRIBUTE86 RES_ATTRIBUTE_86
,attachedDocsE0.ATTRIBUTE87 RES_ATTRIBUTE_87
,attachedDocsE0.ATTRIBUTE88 RES_ATTRIBUTE_88
,attachedDocsE0.ATTRIBUTE89 RES_ATTRIBUTE_89
,attachedDocsE0.ATTRIBUTE90 RES_ATTRIBUTE_90
,attachedDocsE0.ATTRIBUTE91 RES_ATTRIBUTE_91
,attachedDocsE0.ATTRIBUTE92 RES_ATTRIBUTE_92
,attachedDocsE0.ATTRIBUTE93 RES_ATTRIBUTE_93
,attachedDocsE0.ATTRIBUTE94 RES_ATTRIBUTE_94
,attachedDocsE0.ATTRIBUTE95 RES_ATTRIBUTE_95
,attachedDocsE0.ATTRIBUTE96 RES_ATTRIBUTE_96
,attachedDocsE0.ATTRIBUTE97 RES_ATTRIBUTE_97
,attachedDocsE0.ATTRIBUTE98 RES_ATTRIBUTE_98
,attachedDocsE0.ATTRIBUTE99 RES_ATTRIBUTE_99
,attachedDocsE0.ATTRIBUTE100 RES_ATTRIBUTE_100
,attachedDocsE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,attachedDocsE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,attachedDocsE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,attachedDocsE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,attachedDocsE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,attachedDocsE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,attachedDocsE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,attachedDocsE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,attachedDocsE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,attachedDocsE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,attachedDocsE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_DATE1
,attachedDocsE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_DATE2
,attachedDocsE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_DATE3
,attachedDocsE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_DATE4
,attachedDocsE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_DATE5
,attachedDocsE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_DATE6
,attachedDocsE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_DATE7
,attachedDocsE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_DATE8
,attachedDocsE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_DATE9
,attachedDocsE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_DATE10
,attachedDocsE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,attachedDocsE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,attachedDocsE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,attachedDocsE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,attachedDocsE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,attachedDocsE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,docsE0.DM_DOCUMENT_ID RES_DOCUMENT_ID --> NEW
,docsE0.DM_VERSION_NUMBER RES_DOCUMENT_VERSION_NUMBER --> NEW
,attachedDocsE0.PRIMARY_CATEGORY_FLAG RES_PRIMARY_CATEGORY_FLAG --> NEW
,'' RES_NEW_ATTACHMENT_CATEGORY --> NEW
,'' RES_NEW_FILE_URL_TEXT --> NEW
,'' RES_NEW_TITLE --> NEW
,attachedDocsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,attachedDocsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,attachedDocsE0.CREATED_BY  RSC_CREATED_BY
,attachedDocsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_TRADING_PARTNER_ITEMS tradingPartnersE0
,HZ_PARTIES partiesE0
,(SELECT *
	FROM FND_ATTACHED_DOCUMENTS
	WHERE ENTITY_NAME = 'EGP_TRADING_PARTNER_ITEMS'
	) attachedDocsE0
,FND_DOCUMENTS_VL docsE0
WHERE attachedDocsE0.PK1_VALUE = tradingPartnersE0.TRADING_PARTNER_ID
AND tradingPartnersE0.TRADING_PARTNER_ID = partiesE0.PARTY_ID
AND attachedDocsE0.DOCUMENT_ID = docsE0.DOCUMENT_ID