/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=WLF_LEARNING_ITEMS_F
-- REPLACE_HTML_KEYWORD = RES_SHORT_DESCRIPTION,RES_SYLLABUS

SELECT learningTlE0.NAME RES_COURSE_TITLE
,learningE0.LEARNING_ITEM_NUMBER RES_COURSE_NUMBER
,TO_CHAR(learningE0.START_DATE,'DD-Mon-YYYY') RES_PUBLISH_START_DATE

,DECODE(TO_CHAR(learningE0.END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(learningE0.END_DATE ,'DD-Mon-YYYY')) RES_PUBLISH_END_DATE
,REPLACE(REPLACE(REPLACE(learningTlE0.DESCRIPTION_LONG,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#') RES_SYLLABUS
,REPLACE(REPLACE(REPLACE(learningTlE0.DESCRIPTION_SHORT,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#') RES_SHORT_DESCRIPTION
,learningDtlsE0.MINIMUM_TRAINING_HOURS RES_MINIMUM_EXPECTED_EFFORT
,learningDtlsE0.MAXIMUM_TRAINING_HOURS RES_MAXIMUM_EXPECTED_EFFORT
,learningE0.CURRENCY_CODE RES_CURRENCY
,learningE0.MIN_PRICE RES_MINIMUM_PRICE
,learningE0.PRICE RES_MAXIMUM_PRICE


-- Training Supplier or Instructor

,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_FACILITATOR_TYPE'
    AND LOOKUP_CODE = learningDtlsE0.DFLT_FACILITATOR_TYPE
	) RES_FACILITATOR_TYPE
,(CASE
	WHEN learningDtlsE0.DFLT_FACILITATOR_TYPE = 'ORA_TRNG_VENDOR' THEN
		(SELECT NAME
			FROM WLF_RESOURCES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND RESOURCE_ID = learningDtlsE0.DFLT_FACILITATOR_ID)
	WHEN learningDtlsE0.DFLT_FACILITATOR_TYPE = 'ORA_INSTRUCTOR' THEN
		(SELECT DISPLAY_NAME
			FROM PER_PERSON_NAMES_F
			WHERE NAME_TYPE = 'GLOBAL'
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
			AND PERSON_ID = (SELECT PERSON_ID
				FROM WLF_INSTRUCTOR_RESOURCES
				WHERE INSTRUCTOR_ID = learningDtlsE0.DFLT_FACILITATOR_ID))
	END) RES_PRIMARY_INSTRUCTOR_NAME


-- Pricing

,pricingE0.CURRENCY RES_SET_OFFERING_DEFAULT_PRICE


-- Payment

,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_PAYMENT_PROCESSING'
    AND LOOKUP_CODE = NVL(paymentsE0.PAYMENT_TYPE ,'ORA_NOPAYMENT')
	) RES_PAYMENT_TYPE


-- Capacity Rules

,DECODE(learningDtlsE0.ENABLE_CAPACITY,'Y','Yes','No') RES_CAPACITY_RULES
,learningDtlsE0.MINIMUM_ATTENDEES RES_MINIMUM_CAPACITY
,learningDtlsE0.MAXIMUM_ATTENDEES RES_MAXIMUM_CAPACITY
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_WAITLIST_TYPE'
    AND LOOKUP_CODE = learningDtlsE0.WAITLIST_MGMT_MODE 
	) RES_WAITLIST_MODE
,DECODE(learningDtlsE0.ENABLE_WAITLIST,'Y','Yes','No') RES_ALLOW_JOINING_THE_WAITLIST -- Allow joining the waitlist from self-service


-- Default Assignment Rules

,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_ASSIGN_RECORD_STATUS'
    AND LOOKUP_CODE = assgsE0.DEFAULT_INITIAL_RECORD_STATUS 
	) RES_INITIAL_ASSIGNMENT_STATUS
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_CO_VALIDITY_OPTIONS'
    AND LOOKUP_CODE = assgsE0.VALIDITY_OPTION 
	) RES_VALIDITY_PERIOD_OPTIONS
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_CO_CREDIT_EXP_RULES'
    AND LOOKUP_CODE = assgsE0.EXPIRY_OPTION 
	) RES_EXPIRATION
,learningE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,learningE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,learningE0.CREATED_BY  RSC_CREATED_BY
,learningE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM WLF_LEARNING_ITEMS_F_TL learningTlE0
,WLF_LEARNING_ITEMS_F learningE0
,WLF_LI_COURSES_F learningDtlsE0

,(SELECT * 
	FROM WLF_PRICING_RULES_F 
	WHERE USAGE = 'ORA_COURSE'
	) pricingE0
,WLF_PAYMENT_RULES_F paymentsE0
,WLF_ASSIGNMENT_RULES assgsE0

WHERE learningE0.LEARNING_ITEM_TYPE = 'ORA_COURSE'
AND SYSDATE BETWEEN learningE0.EFFECTIVE_START_DATE AND learningE0.EFFECTIVE_END_DATE

AND learningE0.LEARNING_ITEM_ID = learningTlE0.LEARNING_ITEM_ID
AND learningE0.EFFECTIVE_START_DATE = learningTlE0.EFFECTIVE_START_DATE
AND learningTlE0.LANGUAGE = USERENV('LANG')

AND learningE0.LEARNING_ITEM_ID = learningDtlsE0.LEARNING_ITEM_ID
AND learningE0.EFFECTIVE_END_DATE BETWEEN learningDtlsE0.EFFECTIVE_START_DATE AND learningDtlsE0.EFFECTIVE_END_DATE

AND learningE0.PRICING_RULE_ID = pricingE0.PRICING_RULE_ID(+)
AND learningDtlsE0.PAYMENT_RULE_ID = paymentsE0.PAYMENT_RULE_ID(+)
AND learningDtlsE0.EFFECTIVE_END_DATE BETWEEN paymentsE0.EFFECTIVE_START_DATE(+) AND paymentsE0.EFFECTIVE_END_DATE(+)
AND learningE0.ASSIGNMENT_RULE_ID = assgsE0.ASSIGNMENT_RULE_ID(+)

ORDER BY learningE0.LEARNING_ITEM_NUMBER