/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=WLF_LEARNING_ITEMS_F
-- REPLACE_HTML_KEYWORD = RES_DESCRIPTION,RES_SHORT_DESCRIPTION

SELECT learningTlE0.NAME RES_SPECIALIZATION_TITLE
,TO_CHAR(learningE0.START_DATE,'DD-Mon-YYYY') RES_PUBLISH_START_DATE
,DECODE(TO_CHAR(learningE0.END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(learningE0.END_DATE ,'DD-Mon-YYYY')) RES_PUBLISH_END_DATE
,learningE0.LEARNING_ITEM_NUMBER RES_SPECIALIZATION_NUMBER
,learningDtlsE0.MINIMUM_TRAINING_HOURS RES_MINIMUM_EXPECTED_EFFORT
,learningDtlsE0.MAXIMUM_TRAINING_HOURS RES_MAXIMUM_EXPECTED_EFFORT
,REPLACE(REPLACE(REPLACE(learningTlE0.DESCRIPTION_LONG,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#') RES_DESCRIPTION
,REPLACE(REPLACE(REPLACE(learningTlE0.DESCRIPTION_SHORT,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#') RES_SHORT_DESCRIPTION
,learningE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,learningE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,learningE0.CREATED_BY  RSC_CREATED_BY
,learningE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM WLF_LEARNING_ITEMS_F_TL learningTlE0
,WLF_LEARNING_ITEMS_F learningE0
,WLF_LI_SPECIALIZATIONS_F learningDtlsE0
WHERE learningE0.LEARNING_ITEM_TYPE = 'ORA_SPECIALIZATION'
AND SYSDATE BETWEEN learningE0.EFFECTIVE_START_DATE AND learningE0.EFFECTIVE_END_DATE

AND learningE0.LEARNING_ITEM_ID = learningTlE0.LEARNING_ITEM_ID
AND learningE0.EFFECTIVE_START_DATE = learningTlE0.EFFECTIVE_START_DATE
AND learningTlE0.LANGUAGE = USERENV('LANG')

AND learningE0.LEARNING_ITEM_ID = learningDtlsE0.LEARNING_ITEM_ID
AND learningE0.EFFECTIVE_END_DATE BETWEEN learningDtlsE0.EFFECTIVE_START_DATE AND learningDtlsE0.EFFECTIVE_END_DATE

ORDER BY learningE0.LEARNING_ITEM_NUMBER