/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- REPLACE_HTML_KEYWORD = RES_AUDITOR 

SELECT gmsINSTITUE0.INSTITUTION_NAME RES_NAME
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = gmsINSTITUAUDITE0.AUDIT_TYPE
	AND LOOKUP_TYPE = 'ORA_GMS_AWARD_AUDIT_TYPE' AND LANGUAGE = USERENV('LANG')
	) RES_TYPES_NAME
,gmsINSTITUAUDETAILE0.PROGRAM_COVERAGE RES_PROGRAM_COVERAGE
,(SELECT partiesE0.PARTY_NAME
	FROM GMS_SPONSORS_VL sponsorsE0,HZ_PARTIES partiesE0
	WHERE sponsorsE0.PARTY_ID = partiesE0.PARTY_ID
    AND sponsorsE0.SPONSOR_ID = gmsINSTITUAUDETAILE0.SPONSOR_ID
	) RES_SPONSOR
,REPLACE(REPLACE(REPLACE(gmsINSTITUAUDETAILE0.AUDITOR,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#') RES_AUDITOR
,gmsINSTITUAUDETAILE0.REPORT_NUMBER RES_REPORT_NUMBER
,TO_CHAR(gmsINSTITUAUDETAILE0.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(gmsINSTITUAUDETAILE0.END_DATE,'DD-Mon-YYYY') RES_END_DATE
,TO_CHAR(gmsINSTITUAUDETAILE0.REPORT_DATE,'DD-Mon-YYYY') RES_REPORT_DATE

,gmsINSTITUAUDETAILE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,gmsINSTITUAUDETAILE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,gmsINSTITUAUDETAILE0.CREATED_BY  RSC_CREATED_BY
,gmsINSTITUAUDETAILE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM GMS_INSTITUTIONS_VL gmsINSTITUE0
,GMS_INSTN_AUDIT_TYPES gmsINSTITUAUDITE0
,GMS_INSTN_AUDIT_DETAILS_VL gmsINSTITUAUDETAILE0
WHERE gmsINSTITUE0.INSTITUTION_ID = gmsINSTITUAUDITE0.INSTITUTION_ID
AND gmsINSTITUAUDITE0.INSTN_AUDIT_TYPE_ID = gmsINSTITUAUDETAILE0.INSTN_AUDIT_TYPE_ID
ORDER BY gmsINSTITUE0.INSTITUTION_NAME,RES_TYPES_NAME,gmsINSTITUAUDETAILE0.PROGRAM_COVERAGE
