/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=WLF_PROPERTIES

SELECT RES_CONCURRENCY_DETAILS_NUMBER
,DECODE(RES_VIDEO_TRANSCODING_RUN_VIDE,'Y','Yes','No') RES_VIDEO_TRANSCODING_RUN_VIDE
,RES_VIDEO_TRANSCODING_MAXIMUM_
,DECODE(RES_COVER_ART_PROCESS_RUN_COVE,'Y','Yes','No') RES_COVER_ART_PROCESS_RUN_COVE
,RES_COVER_ART_PROCESS_MAXIMUM_
,DECODE(RES_PROCESS_ELEARNING_PACKAGE_,'Y','Yes','No') RES_PROCESS_ELEARNING_PACKAGE_
,RES_PROCESS_ELEARNING_PACKAG_0
,DECODE(RES_EXECUTION_DETAILS_OVERRIDE,'Y','Yes','No') RES_EXECUTION_DETAILS_OVERRIDE
,(SELECT DISPLAY_NAME 
	FROM PER_PERSON_NAMES_F 
	WHERE PERSON_ID = RES_EXECUTION_DETAILS_DEFAULT_ 
	AND NAME_TYPE = 'GLOBAL'
	) RES_EXECUTION_DETAILS_DEFAULT_
,DECODE(RES_EXECUTION_DETAILS_ALLOW_DE,'Y','Yes','No') RES_EXECUTION_DETAILS_ALLOW_DE
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_CODE = RES_VIDEO_TRANSCODING_SELECT_V
	AND LOOKUP_TYPE = 'ORA_WLF_VIDEO_TRANSCODING_QUAL'
	) RES_VIDEO_TRANSCODING_SELECT_V

,RSC_LAST_UPDATED_BY
,RSC_LAST_UPDATE_DATE
,RSC_CREATED_BY
,RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID


FROM 
(

SELECT (SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'REBUILD_LEARNING_INDEXES_JOB_BATCH_SIZE') RES_CONCURRENCY_DETAILS_NUMBER
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'AUTO_SCHEDULE_VIDEO_JOB') RES_VIDEO_TRANSCODING_RUN_VIDE
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'VIDEO_JOB_BATCH_SIZE') RES_VIDEO_TRANSCODING_MAXIMUM_
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'AUTO_SCHEDULE_COVER_ART_JOB') RES_COVER_ART_PROCESS_RUN_COVE
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'COVER_ART_JOB_BATCH_SIZE') RES_COVER_ART_PROCESS_MAXIMUM_
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'AUTO_SCHEDULE_SCORM_AICC_JOB') RES_PROCESS_ELEARNING_PACKAGE_
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'MANAGE_LRNR_DUE_DATE_OFFSET') RES_PROCESS_ELEARNING_PACKAG_0
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'MANAGE_LRNR_SHOW_RUN_AS_USER_SETUP') RES_EXECUTION_DETAILS_OVERRIDE
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'MANAGE_LRNR_DEFAULT_RUN_AS_USER') RES_EXECUTION_DETAILS_DEFAULT_
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'MANAGE_LRNR_OVERRIDE_RUN_AS_USER') RES_EXECUTION_DETAILS_ALLOW_DE
,(SELECT VALUE FROM WLF_PROPERTIES WHERE NAME = 'ORA_WLF_VIDEO_TRANSCODING_QUAL') RES_VIDEO_TRANSCODING_SELECT_V

,setupsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,setupsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,setupsE0.CREATED_BY  RSC_CREATED_BY
,setupsE0.CREATION_DATE  RSC_CREATION_DATE

FROM (SELECT LAST_UPDATED_BY
	,LAST_UPDATE_DATE
	,CREATED_BY
	,CREATION_DATE 
	,ROW_NUMBER() OVER (ORDER BY LAST_UPDATE_DATE DESC) R1
	FROM WLF_PROPERTIES 
	) setupsE0
WHERE R1 = 1)