/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PAY_ELEMENT_LINKS_F 

SELECT DISTINCT elementsE0.ELEMENT_NAME RES_ELEMENT_NAME
,legislativeDataGrpsE0.NAME RES_LEGISLATIVE_DATA_GROUP
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
	WHERE BASE_CLASSIFICATION_ID = elementsE0.CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PRIMARY_CLASSIFICATION
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
    WHERE BASE_CLASSIFICATION_ID = elementsE0.SECONDARY_CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
    ) RES_SECONDARY_CLASSIFICATION
,TO_CHAR(inputE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY')  RES_EFFECTIVE_START_DATE
,payElementlinkE0.ELEMENT_LINK_NAME RES_ELEMENT_ELIGIBILITY_NAME
,inputE0.NAME RES_INPUT_VALUE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'PAY_UNITS'
    AND LOOKUP_CODE =  inputE0.UOM
    ) RES_UOM
,DECODE(payCostinfoE0.COSTED_FLAG,'Y','Yes','No') RES_COSTED


,inputE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,inputE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,inputE0.CREATED_BY RSC_CREATED_BY
,inputE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legislativeDataGrpsE0.LEGISLATION_CODE RSC_COUNTRY_ID


FROM PAY_ELEMENT_TYPES_VL elementsE0
,PAY_ELEMENT_LINKS_F payElementlinkE0
,PAY_LINK_INPUT_VALUES_F payLinkinputE0
,PAY_INPUT_VALUES_VL inputE0
,PAY_COST_INFO_F payCostinfoE0
,(SELECT NAME
    ,LEGISLATIVE_DATA_GROUP_ID
	,LEGISLATION_CODE
    FROM PER_LEGISLATIVE_DATA_GROUPS_VL
    )legislativeDataGrpsE0

	
WHERE elementsE0.LEGISLATIVE_DATA_GROUP_ID = legislativeDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID
AND elementsE0.ELEMENT_TYPE_ID = payElementlinkE0.ELEMENT_TYPE_ID 
AND payElementlinkE0.ELEMENT_LINK_ID = payLinkinputE0.ELEMENT_LINK_ID
AND payLinkinputE0.LINK_INPUT_VALUE_ID = payCostinfoE0.SOURCE_ID
AND payLinkinputE0.INPUT_VALUE_ID = inputE0.INPUT_VALUE_ID 

AND elementsE0.EFFECTIVE_START_DATE = payElementlinkE0.EFFECTIVE_START_DATE
AND payElementlinkE0.EFFECTIVE_START_DATE = payLinkinputE0.EFFECTIVE_START_DATE
AND NVL(payElementlinkE0.COSTING_LINK_FLAG,'N') = 'N'


--AND SYSDATE BETWEEN elementsE0.EFFECTIVE_START_DATE AND NVL(elementsE0.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))

AND payCostinfoE0.SOURCE_TYPE = 'LIV'
ORDER BY elementsE0.ELEMENT_NAME


