/* ****************************************************************************
 * $Revision: 53782 $:
 * $Author: nasrullah.dusenmahamad $:
 * $Date: 2016-03-31 18:00:16 +0700 (Tue, 22 Mar 2016) $:
 * $HeadURL: $:
 * $Id: Manage Enterprise HCM Information - Attachments.sql 53782 2016-03-22 11:00:16Z nasrullah.dusenmahamad $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT QLRTS.RES_EXPENSE_REPORT_TEMPLATES_N
,QLRTS.RES_BUSINESS_UNIT
,QLRTS.RES_EXPENSE_TYPE_NAME
,QLRTS.RES_EXPENSE_TYPE
,QLRTS.RES_EFFECTIVE_END_DATE
,DECODE(ExpenseTypeItemizeEO.EXPENSE_TYPE_PARENT_ID,NULL,'No','Yes') RES_INCLUDE
,ExpenseTypeItemizeEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ExpenseTypeItemizeEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ExpenseTypeItemizeEO.CREATED_BY RSC_CREATED_BY
,ExpenseTypeItemizeEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,QLRTS.ORG_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM
	(SELECT ExpenseTemplateEO.NAME RES_EXPENSE_REPORT_TEMPLATES_N
	,(SELECT BU_NAME
		FROM FUN_ALL_BUSINESS_UNITS_V
		WHERE BU_ID = ExpenseTemplateEO.ORG_ID
		) RES_BUSINESS_UNIT
	,ExpenseTypeEO.NAME RES_EXPENSE_TYPE_NAME
	,(SELECT DISPLAYED_FIELD
		FROM EXM_LOOKUP_VALUES
		WHERE LOOKUP_TYPE = 'EXM_ITEMIZATION_BEHAVIOUR'
		AND LOOKUP_CODE   = ExpenseTypeEO.ITEMIZATION_BEHAVIOUR_CODE
		) RES_ITEMIZATION
	,ExpenseTypeE1.NAME RES_EXPENSE_TYPE
	,TO_CHAR(ExpenseTypeE1.END_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_END_DATE
	,ExpenseTypeEO.EXPENSE_TYPE_ID EXPENSE_TYPE_PARENT_ID
	,ExpenseTypeE1.EXPENSE_TYPE_ID
	,ExpenseTemplateEO.ORG_ID
	FROM EXM_EXPENSE_TEMPLATES ExpenseTemplateEO
	,EXM_EXPENSE_TYPES ExpenseTypeEO
	,EXM_EXPENSE_TYPES ExpenseTypeE1
	WHERE ExpenseTemplateEO.EXPENSE_TEMPLATE_ID = ExpenseTypeEO.EXPENSE_TEMPLATE_ID
	AND ExpenseTemplateEO.EXPENSE_TEMPLATE_ID   = ExpenseTypeE1.EXPENSE_TEMPLATE_ID
	AND ExpenseTypeEO.EXPENSE_TYPE_ID          <> ExpenseTypeE1.EXPENSE_TYPE_ID
	) QLRTS
,EXM_EXPENSE_TYPE_ITEMIZE ExpenseTypeItemizeEO
WHERE QLRTS.EXPENSE_TYPE_PARENT_ID = ExpenseTypeItemizeEO.EXPENSE_TYPE_PARENT_ID(+)
AND QLRTS.EXPENSE_TYPE_ID          = ExpenseTypeItemizeEO.EXPENSE_TYPE_ID(+)
ORDER BY 1,2,3,5