/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT 
(SELECT ITEM_CLASS_NAME
	FROM EGP_ITEM_CLASSES_VL
	WHERE ITEM_CLASS_ID = ItemClassPEO.PARENT_ITEM_CLASS_ID
	) RES_PARENT_ITEM_CLASS 
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,TransAttrEO.DISPLAY_NAME RES_NAME
,TransAttrEO.INTERNAL_NAME RES_INTERNAL_NAME
,TransAttrEO.DESCRIPTION RES_DESCRIPTION
,NVL((SELECT DISTINCT 'Yes'
	FROM EGP_TRANS_ATTRS_METADATA
	WHERE PK1_VALUE = ItemClassPEO.ITEM_CLASS_ID
	AND TRANS_ATTR_ID = TransAttrEO.TRANS_ATTR_ID
	AND DOMAIN_CODE = 30
	),'No') RES_APPLICATION_SCOPE_ASSET_LI
,NVL((SELECT DISTINCT 'Yes'
	FROM EGP_TRANS_ATTRS_METADATA
	WHERE PK1_VALUE = ItemClassPEO.ITEM_CLASS_ID
	AND TRANS_ATTR_ID = TransAttrEO.TRANS_ATTR_ID
	AND DOMAIN_CODE = 31
	),'No') RES_APPLICATION_SCOPE_CONFIGUR
,NVL((SELECT DISTINCT 'Yes'
	FROM EGP_TRANS_ATTRS_METADATA
	WHERE PK1_VALUE = ItemClassPEO.ITEM_CLASS_ID
	AND TRANS_ATTR_ID = TransAttrEO.TRANS_ATTR_ID
	AND DOMAIN_CODE = 28
	),'No') RES_APPLICATION_SCOPE_CONFIG_0
,NVL((SELECT DISTINCT 'Yes'
	FROM EGP_TRANS_ATTRS_METADATA
	WHERE PK1_VALUE = ItemClassPEO.ITEM_CLASS_ID
	AND TRANS_ATTR_ID = TransAttrEO.TRANS_ATTR_ID
	AND DOMAIN_CODE = 24
	),'No') RES_APPLICATION_SCOPE_DISTRIBU
,NVL((SELECT DISTINCT 'Yes'
	FROM EGP_TRANS_ATTRS_METADATA
	WHERE PK1_VALUE = ItemClassPEO.ITEM_CLASS_ID
	AND TRANS_ATTR_ID = TransAttrEO.TRANS_ATTR_ID
	AND DOMAIN_CODE = 32
	),'No') RES_APPLICATION_SCOPE_MANUFACT
,NVL((SELECT DISTINCT 'Yes'
	FROM EGP_TRANS_ATTRS_METADATA
	WHERE PK1_VALUE = ItemClassPEO.ITEM_CLASS_ID
	AND TRANS_ATTR_ID = TransAttrEO.TRANS_ATTR_ID
	AND DOMAIN_CODE = 25
	),'No') RES_APPLICATION_SCOPE_ORDER_CA
,NVL((SELECT DISTINCT 'Yes'
	FROM EGP_TRANS_ATTRS_METADATA
	WHERE PK1_VALUE = ItemClassPEO.ITEM_CLASS_ID
	AND TRANS_ATTR_ID = TransAttrEO.TRANS_ATTR_ID
	AND DOMAIN_CODE = 29
	),'No') RES_APPLICATION_SCOPE_PRICING
,(SELECT TO_CHAR(MAX(START_DATE),'DD-Mon-YYYY HH24:MI:SS')
	FROM EGP_TRANS_ATTRS_METADATA
	WHERE PK1_VALUE = ItemClassPEO.ITEM_CLASS_ID
	) RES_START_DATE
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = TransAttrEO.UOM_CODE
	) RES_UOM
,(SELECt MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_TRANS_ATTR_DATA_TYPES'
	AND LOOKUP_CODE = TransAttrEO.DATA_TYPE_CODE
	) RES_DATA_TYPE
,(SELECT value_set_code
		FROM fnd_vs_value_sets
		WHERE value_set_id = TransAttrMetaDataEO.value_set_id
		) RES_VALUE_SET
,TransAttrMetaDataEO.DEFAULT_VALUE_ID RES_DEFAULT_VALUE
,NULL RES_INACTIVE
,NULL RES_REQUIRED
,NULL RES_READ_ONLY
,NULL RES_HIDDEN
,TransAttrEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,TransAttrEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,TransAttrEO.CREATED_BY  RSC_CREATED_BY
,TransAttrEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,(SELECT DISTINCT value_set_id
	,PK1_VALUE
	,TRANS_ATTR_ID
	,DEFAULT_VALUE_ID
	FROM EGP_TRANS_ATTRS_METADATA) TransAttrMetaDataEO
,EGP_TRANS_ATTRS_VL TransAttrEO
WHERE ItemClassPEO.ITEM_CLASS_ID = TransAttrMetaDataEO.PK1_VALUE
AND TransAttrMetaDataEO.TRANS_ATTR_ID = TransAttrEO.TRANS_ATTR_ID
CONNECT BY ItemClassPEO.PARENT_ITEM_CLASS_ID = ItemClassPEO.ITEM_CLASS_ID
ORDER SIBLINGS BY RES_PARENT_ITEM_CLASS,RES_ITEM_CLASS,RES_NAME