/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10011##RES##EGP_SYSTEM_ITEMS_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.

SELECT 
(SELECT ITEM_CLASS_NAME
	FROM EGP_ITEM_CLASSES_VL
	WHERE ITEM_CLASS_ID = ItemClassPEO.PARENT_ITEM_CLASS_ID
	) RES_PARENT_ITEM_CLASS 
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,ItemVersionEO.TEMPLATE_NAME RES_NAME
,OrgOrganizationDefinitionsPE1.ORGANIZATION_CODE RES_ORGANIZATION
,ItemVersionEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ItemVersionEO.ATTRIBUTE1
,ItemVersionEO.ATTRIBUTE2
,ItemVersionEO.ATTRIBUTE3
,ItemVersionEO.ATTRIBUTE4
,ItemVersionEO.ATTRIBUTE5
,ItemVersionEO.ATTRIBUTE6
,ItemVersionEO.ATTRIBUTE7
,ItemVersionEO.ATTRIBUTE8
,ItemVersionEO.ATTRIBUTE9
,ItemVersionEO.ATTRIBUTE10
,ItemVersionEO.ATTRIBUTE11
,ItemVersionEO.ATTRIBUTE12
,ItemVersionEO.ATTRIBUTE13
,ItemVersionEO.ATTRIBUTE14
,ItemVersionEO.ATTRIBUTE15
,ItemVersionEO.ATTRIBUTE16
,ItemVersionEO.ATTRIBUTE17
,ItemVersionEO.ATTRIBUTE18
,ItemVersionEO.ATTRIBUTE19
,ItemVersionEO.ATTRIBUTE20
,ItemVersionEO.ATTRIBUTE21
,ItemVersionEO.ATTRIBUTE22
,ItemVersionEO.ATTRIBUTE23
,ItemVersionEO.ATTRIBUTE24
,ItemVersionEO.ATTRIBUTE25
,ItemVersionEO.ATTRIBUTE26
,ItemVersionEO.ATTRIBUTE27
,ItemVersionEO.ATTRIBUTE28
,ItemVersionEO.ATTRIBUTE29
,ItemVersionEO.ATTRIBUTE30
,ItemVersionEO.ATTRIBUTE_NUMBER1
,ItemVersionEO.ATTRIBUTE_NUMBER2
,ItemVersionEO.ATTRIBUTE_NUMBER3
,ItemVersionEO.ATTRIBUTE_NUMBER4
,ItemVersionEO.ATTRIBUTE_NUMBER5
,ItemVersionEO.ATTRIBUTE_NUMBER6
,ItemVersionEO.ATTRIBUTE_NUMBER7
,ItemVersionEO.ATTRIBUTE_NUMBER8
,ItemVersionEO.ATTRIBUTE_NUMBER9
,ItemVersionEO.ATTRIBUTE_NUMBER10
,TO_CHAR(ItemVersionEO.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(ItemVersionEO.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(ItemVersionEO.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(ItemVersionEO.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(ItemVersionEO.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,ItemVersionEO.ATTRIBUTE_TIMESTAMP1
,ItemVersionEO.ATTRIBUTE_TIMESTAMP2
,ItemVersionEO.ATTRIBUTE_TIMESTAMP3
,ItemVersionEO.ATTRIBUTE_TIMESTAMP4
,ItemVersionEO.ATTRIBUTE_TIMESTAMP5
,ItemVersionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemVersionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemVersionEO.CREATED_BY RSC_CREATED_BY
,ItemVersionEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(SELECT BUSINESS_UNIT_ID
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemVersionEO.ORGANIZATION_ID
	) RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,(CASE
	WHEN EXISTS
		(SELECT DISTINCT MASTER_ORGANIZATION_ID
			FROM INV_ORG_PARAMETERS
			WHERE MASTER_ORGANIZATION_ID = ItemVersionEO.ORGANIZATION_ID)
	THEN NULL
	ELSE ItemVersionEO.ORGANIZATION_ID
	END) RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,(SELECT ITEM_CATALOG_GROUP_ID
	,TEMPLATE_NAME
	,ATTRIBUTE_CATEGORY
	,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5
	,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10
	,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15
	,ATTRIBUTE16,ATTRIBUTE17,ATTRIBUTE18,ATTRIBUTE19,ATTRIBUTE20
	,ATTRIBUTE21,ATTRIBUTE22,ATTRIBUTE23,ATTRIBUTE24,ATTRIBUTE25
	,ATTRIBUTE26,ATTRIBUTE27,ATTRIBUTE28,ATTRIBUTE29,ATTRIBUTE30
	,ATTRIBUTE_NUMBER1,ATTRIBUTE_NUMBER2,ATTRIBUTE_NUMBER3,ATTRIBUTE_NUMBER4,ATTRIBUTE_NUMBER5
	,ATTRIBUTE_NUMBER6,ATTRIBUTE_NUMBER7,ATTRIBUTE_NUMBER8,ATTRIBUTE_NUMBER9,ATTRIBUTE_NUMBER10
	,ATTRIBUTE_DATE1,ATTRIBUTE_DATE2,ATTRIBUTE_DATE3,ATTRIBUTE_DATE4,ATTRIBUTE_DATE5
	,ATTRIBUTE_TIMESTAMP1,ATTRIBUTE_TIMESTAMP2,ATTRIBUTE_TIMESTAMP3,ATTRIBUTE_TIMESTAMP4,ATTRIBUTE_TIMESTAMP5
	,LAST_UPDATED_BY,LAST_UPDATE_DATE,CREATED_BY,CREATION_DATE,ORGANIZATION_ID
	FROM EGP_SYSTEM_ITEMS_V ItemVersionEO
	WHERE (ItemVersionEO.ATTRIBUTE_CATEGORY  IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE1           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE2           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE3           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE4           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE5           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE6           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE7           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE8           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE9           IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE10          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE11          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE12          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE13          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE14          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE15          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE16          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE17          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE18          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE19          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE20          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE21          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE22          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE23          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE24          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE25          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE26          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE27          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE28          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE29          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE30          IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER1    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER2    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER3    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER4    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER5    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER6    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER7    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER8    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER9    IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_NUMBER10   IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_DATE1      IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_DATE2      IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_DATE3      IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_DATE4      IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_DATE5      IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_TIMESTAMP1 IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_TIMESTAMP2 IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_TIMESTAMP3 IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_TIMESTAMP4 IS NOT NULL
		OR ItemVersionEO.ATTRIBUTE_TIMESTAMP5 IS NOT NULL)
	AND TEMPLATE_NAME IS NOT NULL
	) ItemVersionEO
,INV_ORGANIZATION_DEFINITIONS_V OrgOrganizationDefinitionsPE1
WHERE /*ItemVersionEO.TEMPLATE_NAME IS NOT NULL
AND*/ ItemClassPEO.ITEM_CLASS_ID             = ItemVersionEO.ITEM_CATALOG_GROUP_ID
AND ItemVersionEO.ORGANIZATION_ID = OrgOrganizationDefinitionsPE1.ORGANIZATION_ID
--AND
CONNECT BY ItemClassPEO.PARENT_ITEM_CLASS_ID = ItemClassPEO.ITEM_CLASS_ID
ORDER SIBLINGS BY RES_PARENT_ITEM_CLASS,RES_ITEM_CLASS,RES_NAME