/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Receivables%20Activities%20-%20Receivables%20Activities.sql $:
 * $Id: Manage Receivables Activities - Receivables Activities.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- FIELD_TO_APPLY_FUNCTION=RES_ACTIVITY_GL_ACCOUNT/GET_CODE_COMBINATION

SELECT QRSLT.NAME1 RES_BUSINESS_UNIT
,QRSLT.NAME RES_NAME
,QRSLT.DESCRIPTION RES_DESCRIPTION
,QRSLT.RECEIVABLES_TRX RES_ACTIVITY_TYPE
,DECODE(QRSLT.STATUS,'A','Yes','No') RES_ACTIVE
,QRSLT.GL_ACCOUNT_SOURCE_L RES_GL_ACCOUNT_SOURCE
,QRSLT.TAX_CODE_SOURCE_L RES_TAX_RATE_CODE_SOURCE
,DECODE(QRSLT.TAX_RECOVERABLE_FLAG,'Y','Yes','No') RES_RECOVERABLE
,(CASE
	WHEN QRSLT.GL_ACCOUNT_SOURCE_L = 'Activity GL account' OR QRSLT.GL_ACCOUNT_SOURCE_L = 'Revenue on invoice' THEN
		QRSLT.CODE_COMBINATION_ID 
	ELSE 
		NULL
	END) RES_ACTIVITY_GL_ACCOUNT
,(SELECT DISTRIBUTION_SET_NAME 
	FROM AR_DISTRIBUTION_SETS_ALL
	WHERE DISTRIBUTION_SET_ID = QRSLT.DEFAULT_ACCTG_DISTRIBUTION_SET
	) RES_DISTRIBUTION_SET
,(CASE 
	WHEN QRSLT.RECEIVABLES_TRX = 'Adjustments' AND QRSLT.GL_ACCOUNT_SOURCE_L = 'Tax rate code on invoice' AND QRSLT.TAX_CODE_SOURCE_L = 'Activity' THEN
		QRSLT.ASSET_TAX_CODE
	ELSE
		NULL
	END) RES_TAX_RATE_CODE
,(CASE 
	WHEN QRSLT.RECEIVABLES_TRX = 'Adjustments' AND QRSLT.GL_ACCOUNT_SOURCE_L = 'Tax rate code on invoice' AND QRSLT.TAX_CODE_SOURCE_L = 'Activity' THEN
		NULL
	ELSE
		QRSLT.ASSET_TAX_CODE 
	END) RES_ASSET_TAX_RATE_CODE
,QRSLT.LIABILITY_TAX_CODE RES_LIABILITY_TAX_RATE_CODE
,QRSLT.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY  RSC_CREATED_BY
,QRSLT.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,QRSLT.ORG_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM (SELECT BusinessUnitPEO.BU_NAME AS NAME1
	,ArReceivablesTrxAll.LAST_UPDATED_BY
	,ArReceivablesTrxAll.LAST_UPDATE_DATE
	,ArReceivablesTrxAll.CREATED_BY
	,ArReceivablesTrxAll.CREATION_DATE
	,ArReceivablesTrxAll.ORG_ID
	,ArReceivablesTrxAll.NAME
	,ArReceivablesTrxAll.CODE_COMBINATION_ID
	,ArReceivablesTrxAll.DESCRIPTION
	,ARRECEIVABLESTRXALL.TYPE
	,DECODE(ARRECEIVABLESTRXALL.TYPE,NULL,NULL,(FUSION.ARPT_SQL_FUNC_UTIL.GET_LOOKUP_MEANING('RECEIVABLES_TRX',ARRECEIVABLESTRXALL.TYPE))) RECEIVABLES_TRX
	,ArReceivablesTrxAll.STATUS
	,ArReceivablesTrxAll.ASSET_TAX_CODE
	,ArReceivablesTrxAll.LIABILITY_TAX_CODE
	,ARRECEIVABLESTRXALL.GL_ACCOUNT_SOURCE
	,DECODE(ARRECEIVABLESTRXALL.GL_ACCOUNT_SOURCE,NULL,NULL,(FUSION.ARPT_SQL_FUNC_UTIL.GET_LOOKUP_MEANING('GL_ACCOUNT_SOURCE',ARRECEIVABLESTRXALL.GL_account_source))) GL_ACCOUNT_SOURCE_L
	,ARRECEIVABLESTRXALL.TAX_CODE_SOURCE
	,DECODE(ARRECEIVABLESTRXALL.TAX_CODE_SOURCE,NULL,NULL,(FUSION.ARPT_SQL_FUNC_UTIL.GET_LOOKUP_MEANING('TAX_CODE_SOURCE',ARRECEIVABLESTRXALL.TAX_CODE_SOURCE))) TAX_CODE_SOURCE_L
	,ArReceivablesTrxAll.TAX_RECOVERABLE_FLAG
	,ArReceivablesTrxAll.ACCOUNTING_AFFECT_FLAG
	,ArReceivablesTrxAll.RISK_ELIMINATION_DAYS
	,ArReceivablesTrxAll.DEFAULT_ACCTG_DISTRIBUTION_SET
	FROM AR_RECEIVABLES_TRX_ALL ArReceivablesTrxAll
	,FUN_ALL_BUSINESS_UNITS_V BUSINESSUNITPEO
	WHERE ArReceivablesTrxAll.ORG_ID = BusinessUnitPEO.BU_ID
	AND ARRECEIVABLESTRXALL.GL_ACCOUNT_SOURCE = 'ACTIVITY_GL_ACCOUNT'
	AND ArReceivablesTrxAll.CODE_COMBINATION_ID IS NOT NULL
	
	UNION
	
	SELECT BusinessUnitPEO.BU_NAME AS NAME1
	,ArReceivablesTrxAll.LAST_UPDATED_BY
	,ArReceivablesTrxAll.LAST_UPDATE_DATE
	,ArReceivablesTrxAll.CREATED_BY
	,ArReceivablesTrxAll.CREATION_DATE
	,ArReceivablesTrxAll.ORG_ID
	,ArReceivablesTrxAll.NAME
	,ArReceivablesTrxAll.CODE_COMBINATION_ID
	,ArReceivablesTrxAll.DESCRIPTION
	,ARRECEIVABLESTRXALL.TYPE
	,DECODE(ARRECEIVABLESTRXALL.TYPE,NULL,NULL,(FUSION.ARPT_SQL_FUNC_UTIL.GET_LOOKUP_MEANING('RECEIVABLES_TRX',ARRECEIVABLESTRXALL.TYPE))) RECEIVABLES_TRX
	,ArReceivablesTrxAll.STATUS
	,ArReceivablesTrxAll.ASSET_TAX_CODE
	,ArReceivablesTrxAll.LIABILITY_TAX_CODE
	,ARRECEIVABLESTRXALL.GL_ACCOUNT_SOURCE
	,DECODE(ARRECEIVABLESTRXALL.GL_ACCOUNT_SOURCE,NULL,NULL,(FUSION.ARPT_SQL_FUNC_UTIL.GET_LOOKUP_MEANING('GL_ACCOUNT_SOURCE',ARRECEIVABLESTRXALL.GL_account_source))) GL_ACCOUNT_SOURCE_L
	,ARRECEIVABLESTRXALL.TAX_CODE_SOURCE
	,DECODE(ARRECEIVABLESTRXALL.TAX_CODE_SOURCE,NULL,NULL,(FUSION.ARPT_SQL_FUNC_UTIL.GET_LOOKUP_MEANING('TAX_CODE_SOURCE',ARRECEIVABLESTRXALL.TAX_CODE_SOURCE))) TAX_CODE_SOURCE_L
	,ArReceivablesTrxAll.TAX_RECOVERABLE_FLAG
	,ArReceivablesTrxAll.ACCOUNTING_AFFECT_FLAG
	,ArReceivablesTrxAll.RISK_ELIMINATION_DAYS
	,ArReceivablesTrxAll.DEFAULT_ACCTG_DISTRIBUTION_SET
	FROM AR_RECEIVABLES_TRX_ALL ArReceivablesTrxAll
	,FUN_ALL_BUSINESS_UNITS_V BUSINESSUNITPEO
	WHERE ArReceivablesTrxAll.ORG_ID = BusinessUnitPEO.BU_ID
	AND ARRECEIVABLESTRXALL.GL_ACCOUNT_SOURCE <> 'ACTIVITY_GL_ACCOUNT'
	
	/*
		Discussion with consultant for the condition of this query: Retrieve the data by using 2 condition 
		1. The column 'GL Account Source' contain value as 'Activity GL account' the column 'Activity GL Account' must contain value.
		2. The column 'GL Account Source' haven't contain value as 'Activity GL account'.
	*/
	
	) QRSLT
ORDER BY QRSLT.NAME1
,QRSLT.name