/* ****************************************************************************
* $Revision: 78735 $:
* $Author: pisan.jariyasettachok $:
* $Date: 2022-06-13 20:34:08 +0700 (Mon, 13 Jun 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Tax%20Rates%20and%20Tax%20Recovery%20Rates%20-%20Transaction%20Tax%20Accounts.sql $:
* $Id: Manage Tax Rates and Tax Recovery Rates - Transaction Tax Accounts.sql 78735 2022-06-13 13:34:08Z pisan.jariyasettachok $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- FIELD_TO_APPLY_FUNCTION=RES_TAX_EXPENSE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_INTERIM_TAX/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_TAX_RECOVERABLE_ACCOUNT/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_TAX_LIABILITY_ACCOUNT/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_FINANCE_CHARGE_TAX_LIABILI/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_NONRECOVERABLE_TAX_ACCOUNT/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_NONRECOVERABLE_TAX_ACCOU_0/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_NONRECOVERABLE_TAX_ACCOU_1/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_EXPENSE_AND_REVENUE_ACCOUN/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_EXPENSE_AND_REVENUE_ACCO_2/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_EXPENSE_AND_REVENUE_ACCO_3/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_EXPENSE_AND_REVENUE_ACCO_4/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_PREPAID_TAX_ACCOUNT/GET_CODE_COMBINATION

--RSC_PREREQUISITE_OBJECTS=ZX_ACCOUNTS


SELECT HEAD.TAX_REGIME_CODE RES_TAX_REGIME_CODE,
HEAD.PARTY_NAME RES_CONFIGURATION_OWNER,
HEAD.TAX RES_TAX,
HEAD.tax_status_code RES_TAX_STATUS_CODE,
HEAD.tax_jurisdiction_code RES_TAX_JURISDICTION_CODE,
HEAD.tax_rate_code RES_TAX_RATE_CODE,
HEAD.PERCENTAGE_RATE RES_RATE_PERCENTAGE,
HEAD.UOM_CODE RES_UOM_CODE,
HEAD.UNIT_OF_MEASURE RES_UOM_NAME,
HEAD.QUANTITY_RATE RES_RATE_QUANTITY,
to_char(HEAD.EFFECTIVE_FROM,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE,
(SELECT name
	FROM gl_ledgers
	WHERE ledger_id = QRSLT.ledger_id
	) RES_LEDGER
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = QRSLT.INTERNAL_ORGANIZATION_ID
	) RES_BUSINESS_UNIT
,QRSLT.NON_REC_ACCOUNT_CCID RES_TAX_EXPENSE
,QRSLT.INTERIM_TAX_CCID RES_INTERIM_TAX
,QRSLT.TAX_ACCOUNT_CCID RES_TAX_RECOVERABLE_ACCOUNT
,QRSLT.TAX_LIAB_ACCT_CCID RES_TAX_LIABILITY_ACCOUNT
,QRSLT.FINCHRG_NON_REC_TAX_CCID RES_FINANCE_CHARGE_TAX_LIABILI
,QRSLT.TAX_PREPAID_ACCOUNT_CCID RES_PREPAID_TAX_ACCOUNT
,QRSLT.EDISC_NON_REC_TAX_CCID RES_NONRECOVERABLE_TAX_ACCOUNT
,QRSLT.ADJ_NON_REC_TAX_CCID RES_NONRECOVERABLE_TAX_ACCOU_0
,QRSLT.UNEDISC_NON_REC_TAX_CCID RES_NONRECOVERABLE_TAX_ACCOU_1
,QRSLT.EDISC_CCID RES_EXPENSE_AND_REVENUE_ACCOUN
,QRSLT.ADJ_CCID RES_EXPENSE_AND_REVENUE_ACCO_2
,QRSLT.FINCHRG_CCID RES_EXPENSE_AND_REVENUE_ACCO_3
,QRSLT.UNEDISC_CCID RES_EXPENSE_AND_REVENUE_ACCO_4
,QRSLT.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY RSC_CREATED_BY
,QRSLT.CREATION_DATE RSC_CREATION_DATE
,QRSLT.ledger_id RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(CASE
	WHEN HEAD.PARTY_TYPE_CODE = 'OU' THEN
		HEAD.BU_ID
	END) RSC_BUSINESS_UNIT_ID
,(CASE
	WHEN HEAD.PARTY_TYPE_CODE = 'FIRST_PARTY' THEN
		HEAD.LEGAL_ENTITY_ID
	END) RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
	
FROM (SELECT DISTINCT ZxRatesVl.TAX_REGIME_CODE,
	party.PARTY_NAME,
	ZxRatesVl.TAX,
	ZxRatesVl.tax_status_code,
	ZxRatesVl.tax_jurisdiction_code,
	ZxRatesVl.tax_rate_code,
	ZxRatesVl.PERCENTAGE_RATE,
	ZxRatesVl.UOM_CODE,
	ZxRatesVl.QUANTITY_RATE,
	ZxRatesVl.EFFECTIVE_FROM,
	ZxRatesVl.TAX_rate_ID,
	UnitOfMeasurePEO.UNIT_OF_MEASURE
	,ZxRatesVl.CONTENT_OWNER_ID
	,party.PARTY_TYPE_CODE
	,party.BU_ID
	,party.LEGAL_ENTITY_ID
	FROM ZX_RATES_VL ZxRatesVl,
	ZX_FIRST_PARTY_ORGS_MOAC_V party,
	ZX_REGIMES_VL RegimeTLEO, 
	ZX_MCO_CHECK_ACCESS_V ZMCAV,
	ZX_MCO_LV_TAXES_V Tax,
	INV_UNITS_OF_MEASURE_VL UnitOfMeasurePEO
	WHERE RegimeTLEO.TAX_REGIME_CODE         = ZxRatesVl.TAX_REGIME_CODE
	AND party.party_tax_profile_id           = ZxRatesVl.CONTENT_OWNER_ID
	AND ZxRatesVl.ACTIVE_FLAG                = 'Y'
	AND ZMCAV.TAX_REGIME_CODE = ZxRatesVl.TAX_REGIME_CODE
	AND ZMCAV.PARENT_FIRST_PTY_ORG_ID = ZxRatesVl.CONTENT_OWNER_ID
	AND Tax.TAX_REGIME_CODE = ZxRatesVl.TAX_REGIME_CODE
	AND Tax.TAX = ZxRatesVl.TAX
	AND Tax.CONTENT_OWNER_ID = ZxRatesVl.CONTENT_OWNER_ID
	AND ZxRatesVl.rate_type_code <> 'RECOVERY'  
	AND UPPER(NVL(RegimeTLEO.REGIME_TYPE_FLAG,'I')) = UPPER('I') 
	AND ZxRatesVl.UOM_CODE = UnitOfMeasurePEO.UOM_CODE(+)
	)  HEAD
,(SELECT ZA.TAX_ACCOUNT_ENTITY_CODE, ZA.TAX_ACCOUNT_CCID,
	ZA.INTERIM_TAX_CCID, ZA.NON_REC_ACCOUNT_CCID, ZA.ADJ_CCID,
	ZA.EDISC_CCID, ZA.UNEDISC_CCID, ZA.FINCHRG_CCID,
	ZA.ADJ_NON_REC_TAX_CCID, ZA.EDISC_NON_REC_TAX_CCID,
	ZA.UNEDISC_NON_REC_TAX_CCID, ZA.FINCHRG_NON_REC_TAX_CCID,
	ZA.RECORD_TYPE_CODE, ZA.CREATED_BY, ZA.CREATION_DATE,
	ZA.LAST_UPDATED_BY, ZA.LAST_UPDATE_DATE, ZA.LAST_UPDATE_LOGIN,
	ZA.REQUEST_ID, ZA.ATTRIBUTE1, ZA.ATTRIBUTE2, ZA.ATTRIBUTE3,
	ZA.ATTRIBUTE4, ZA.ATTRIBUTE5, ZA.ATTRIBUTE6, ZA.ATTRIBUTE7,
	ZA.ATTRIBUTE8, ZA.ATTRIBUTE9, ZA.ATTRIBUTE10, ZA.ATTRIBUTE11,
	ZA.ATTRIBUTE12, ZA.ATTRIBUTE13, ZA.ATTRIBUTE14, ZA.ATTRIBUTE15,
	ZA.ATTRIBUTE_CATEGORY, ZA.PROGRAM_LOGIN_ID, ZA.TAX_ACCOUNT_ID,
	ZA.TAX_ACCOUNT_ENTITY_ID, ZA.LEDGER_ID, ZA.OBJECT_VERSION_NUMBER,
	ZA.INTERNAL_ORGANIZATION_ID,
	ZA.PROGRAM_APP_NAME,
	ZA.PROGRAM_NAME,
	BusinessUnitPEO.BU_NAME AS NAME,
	ZA.INTERNAL_ORGANIZATION_ID AS INT_ORG_ID_DUP,
	GL.CHART_OF_ACCOUNTS_ID,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID1,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID2,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID3,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID4,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID5,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID6,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID7,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID8,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID9,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID10,
	FIFS.ID_FLEX_STRUCTURE_CODE, 'N' CREATED_FROM_ICON,
	'N' AS NEW_RECORD, GL.NAME AS LEDGER_NAME, ZA.LEDGER_ID AS LEDGER_ID_DUP,
	ZA.tax_accrual_account_ccid,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID11,
	GL.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID12, ZA.TAX_LIAB_ACCT_CCID
	, ZA.TAX_PREPAID_ACCOUNT_CCID
	FROM
	ZX_ACCOUNTS ZA,
	GL_LEDGERS GL,
	FND_ID_FLEX_STRUCTURES FIFS,
	FUN_ALL_BUSINESS_UNITS_V BusinessUnitPEO 
	WHERE  GL.LEDGER_ID (+) = ZA.LEDGER_ID 
	AND  FIFS.APPLICATION_ID (+) = 101 
	AND  FIFS.ID_FLEX_CODE (+)= 'GL#' 
	AND  FIFS.ID_FLEX_NUM = GL.CHART_OF_ACCOUNTS_ID 
	AND  BusinessUnitPEO.BU_ID (+) = ZA.INTERNAL_ORGANIZATION_ID
	) QRSLT  
WHERE HEAD.TAX_rate_ID = QRSLT.TAX_ACCOUNT_ENTITY_ID
ORDER BY (SELECT DECODE(TAX_TYPE_CODE,'OFFSET',1,2) 
	FROM ZX_TAXES_VL 
	WHERE TAX = HEAD.TAX 
	AND CONTENT_OWNER_ID = HEAD.CONTENT_OWNER_ID
	AND TAX_REGIME_CODE = HEAD.TAX_REGIME_CODE
	)
,RES_TAX_REGIME_CODE
,RES_TAX_RATE_CODE 