/* ****************************************************************************
 * $Revision: 77370 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2021-11-25 13:24:52 +0700 (Thu, 25 Nov 2021) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Plans%20-%20Enrollment%20Life%20Event.sql $:
 * $Id: Manage Benefit Plans - Enrollment Life Event.sql 77370 2021-11-25 06:24:52Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=BEN_PL_F

SELECT RES_PLAN_NAME
,RES_EFFECTIVE_START_DATE
,RES_PLAN_OR_OPTION_NAME
,RES_PLAN_OR_OPTION_DESCRIPTION
,RES_LIFE_EVENT_RESTRICTIONS
,RES_RESTRICTIONS_EFFECTIVE_STA
,RES_RESTRICTIONS_EFFECTIVE_END
,RES_ENROLLMENT_METHOD
,RES_AUTOMATIC_FORMULA
,RES_DEFAULT_ENROLLMENT_RULE
,RES_DEFAULT_ENROLLMENT_FORMULA
,RES_ALLOWABLE_ENROLLMENT_CHANG
,RES_ENROLLMENT_RULE
,RES_ENROLLMENT_FORMULA
,RES_INTERIM_RULE
,RES_INTERIM_FORMULA
,RES_UNSUSPEND_ENROLLMENT_RULE
,RES_UNSUSPEND_ENROLLMENT_FORMU
,RES_UNSUSPEND_RATE_RULE
,RES_UNSUSPEND_RATE_FORMULA
,RES_CURRENT_ELIGIBILITY_PREVEN
,RES_CURRENT_ENROLLMENT_PREVENT
,RES_ASSIGN_ON_DEFAULT
,RES_AUTOMATIC_ENROLLMENT
,RSC_LAST_UPDATED_BY
,RSC_LAST_UPDATE_DATE
,RSC_CREATED_BY
,RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,RSC_COUNTRY_ID


FROM
(
 
SELECT benPlansE0.NAME RES_PLAN_NAME
,TO_CHAR(benPlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,benPlansE0.NAME RES_PLAN_OR_OPTION_NAME
,'Plan' RES_PLAN_OR_OPTION_DESCRIPTION
,(SELECT NAME
    FROM BEN_LER_F_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND LER_ID = restrictsE0.LER_ID
    ) RES_LIFE_EVENT_RESTRICTIONS
,TO_CHAR(restrictsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_RESTRICTIONS_EFFECTIVE_STA
,DECODE(TO_CHAR(restrictsE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY'),'31-12-4712',NULL,TO_CHAR(restrictsE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_RESTRICTIONS_EFFECTIVE_END
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_MTHD'
    AND LOOKUP_CODE = restrictsE0.ENRT_MTHD_CD
    ) RES_ENROLLMENT_METHOD
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = restrictsE0.AUTO_ENRT_MTHD_RL
    ) RES_AUTOMATIC_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DFLT_ENRT'
    AND LOOKUP_CODE = restrictsE0.DFLT_ENRT_CD
    ) RES_DEFAULT_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = restrictsE0.DFLT_ENRT_RL
    ) RES_DEFAULT_ENROLLMENT_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_TCO_CHG_ENRT'
    AND LOOKUP_CODE = restrictsE0.TCO_CHG_ENRT_CD
    ) RES_ALLOWABLE_ENROLLMENT_CHANG
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT'
    AND LOOKUP_CODE = restrictsE0.ENRT_CD
    ) RES_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = restrictsE0.ENRT_RL
    ) RES_ENROLLMENT_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DFLT_TO_ASN_PNDG_CTFN'
    AND LOOKUP_CODE = restrictsE0.DFLT_TO_ASN_PNDG_CTFN_CD
    ) RES_INTERIM_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = restrictsE0.DFLT_TO_ASN_PNDG_CTFN_RL
    ) RES_INTERIM_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_UNSSPND_ENRT'
    AND LOOKUP_CODE = restrictsE0.UNSSPND_ENRT_CD
    ) RES_UNSUSPEND_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = restrictsE0.UNSSPND_ENRT_RL
    ) RES_UNSUSPEND_ENROLLMENT_FORMU
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_UNSSPND_ENRT'
    AND LOOKUP_CODE = restrictsE0.UNSSPND_RT_CD
    ) RES_UNSUSPEND_RATE_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = restrictsE0.UNSSPND_RT_RL
    ) RES_UNSUSPEND_RATE_FORMULA
,DECODE(restrictsE0.STL_ELIG_CANT_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ELIGIBILITY_PREVEN
,DECODE(restrictsE0.CRNT_ENRT_PRCLDS_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ENROLLMENT_PREVENT
,DECODE(restrictsE0.DFLT_FLAG,'Y','Yes','No') RES_ASSIGN_ON_DEFAULT
,NULL RES_AUTOMATIC_ENROLLMENT

,restrictsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,restrictsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,restrictsE0.CREATED_BY  RSC_CREATED_BY
,restrictsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPlansE0.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PL_F benPlansE0
,(SELECT NAME
	,PL_TYP_ID
    FROM BEN_PL_TYP_F
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND OPT_TYP_CD != 'FLXCR'
	) planTypesE0
,(SELECT *
    FROM BEN_LER_CHG_PL_NIP_ENRT_F
    WHERE LER_ID IN (SELECT LER_ID FROM BEN_LER_F WHERE TYP_CD NOT IN ('SCHEDDUO','SCHEDDA'))
    ) restrictsE0
WHERE SYSDATE BETWEEN benPlansE0.EFFECTIVE_START_DATE AND benPlansE0.EFFECTIVE_END_DATE
AND benPlansE0.PL_TYP_ID = planTypesE0.PL_TYP_ID
AND benPlansE0.PL_ID = restrictsE0.PL_ID

UNION

SELECT benPlansE0.NAME RES_PLAN_NAME
,TO_CHAR(benPlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,(SELECT NAME
    FROM BEN_OPT_F
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    AND OPT_ID = optionsE0.OPT_ID
    ) RES_PLAN_OR_OPTION_NAME
,'Options' RES_PLAN_OR_OPTION_DESCRIPTION
,(SELECT NAME
    FROM BEN_LER_F_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND LER_ID = benLEROPTIONE0.LER_ID
    ) RES_LIFE_EVENT_RESTRICTIONS
,TO_CHAR(benLEROPTIONE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_RESTRICTIONS_EFFECTIVE_STA
,DECODE(TO_CHAR(benLEROPTIONE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY'),'31-12-4712',NULL,TO_CHAR(benLEROPTIONE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_RESTRICTIONS_EFFECTIVE_END
,NULL RES_ENROLLMENT_METHOD
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLEROPTIONE0.AUTO_ENRT_MTHD_RL
    ) RES_AUTOMATIC_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DFLT_ENRT'
    AND LOOKUP_CODE = benLEROPTIONE0.DFLT_ENRT_CD
    ) RES_DEFAULT_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLEROPTIONE0.DFLT_ENRT_RL
    ) RES_DEFAULT_ENROLLMENT_FORMULA
,NULL RES_ALLOWABLE_ENROLLMENT_CHANG
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT'
    AND LOOKUP_CODE = benLEROPTIONE0.ENRT_CD
    ) RES_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLEROPTIONE0.ENRT_RL
    ) RES_ENROLLMENT_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DFLT_TO_ASN_PNDG_CTFN'
    AND LOOKUP_CODE = benLEROPTIONE0.DFLT_TO_ASN_PNDG_CTFN_CD
    ) RES_INTERIM_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLEROPTIONE0.DFLT_TO_ASN_PNDG_CTFN_RL
    ) RES_INTERIM_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_UNSSPND_ENRT'
    AND LOOKUP_CODE = benLEROPTIONE0.UNSSPND_ENRT_CD
    ) RES_UNSUSPEND_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLEROPTIONE0.UNSSPND_ENRT_RL
    ) RES_UNSUSPEND_ENROLLMENT_FORMU
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_UNSSPND_ENRT'
    AND LOOKUP_CODE = benLEROPTIONE0.UNSSPND_RT_CD
    ) RES_UNSUSPEND_RATE_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLEROPTIONE0.UNSSPND_RT_RL
    ) RES_UNSUSPEND_RATE_FORMULA
,DECODE(benLEROPTIONE0.STL_ELIG_CANT_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ELIGIBILITY_PREVEN
,DECODE(benLEROPTIONE0.CRNT_ENRT_PRCLDS_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ENROLLMENT_PREVENT
,DECODE(benLEROPTIONE0.DFLT_FLAG,'Y','Yes','No') RES_ASSIGN_ON_DEFAULT
,DECODE(benLEROPTIONE0.AUTO_ENRT_FLAG,'Y','Yes','No') RES_AUTOMATIC_ENROLLMENT

,benLEROPTIONE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,benLEROPTIONE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,benLEROPTIONE0.CREATED_BY  RSC_CREATED_BY
,benLEROPTIONE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPlansE0.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PL_F benPlansE0
,(SELECT NAME
	,PL_TYP_ID
    FROM BEN_PL_TYP_F
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND OPT_TYP_CD != 'FLXCR'
	) planTypesE0
,BEN_OIPL_F optionsE0
,(SELECT *
    FROM BEN_LER_CHG_OIPL_ENRT_F
    WHERE LER_ID IN (SELECT LER_ID FROM BEN_LER_F WHERE TYP_CD NOT IN ('SCHEDDUO','SCHEDDA'))
    ) benLEROPTIONE0
WHERE SYSDATE BETWEEN benPlansE0.EFFECTIVE_START_DATE AND benPlansE0.EFFECTIVE_END_DATE
AND benPlansE0.PL_TYP_ID = planTypesE0.PL_TYP_ID
AND benPlansE0.PL_ID = optionsE0.PL_ID
AND optionsE0.OIPL_ID = benLEROPTIONE0.OIPL_ID
AND benPlansE0.EFFECTIVE_END_DATE BETWEEN optionsE0.EFFECTIVE_START_DATE AND optionsE0.EFFECTIVE_END_DATE

ORDER BY RES_PLAN_NAME
,RES_EFFECTIVE_START_DATE
,RES_PLAN_OR_OPTION_NAME)