/* ****************************************************************************
 * $Revision: 79010 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-07-14 13:11:43 +0700 (Thu, 14 Jul 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Invoice%20Methods%20-%20Billing%20Extension%20Assignments.sql $:
 * $Id: Manage Invoice Methods - Billing Extension Assignments.sql 79010 2022-07-14 06:11:43Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

--RSC_PREREQUISITE_OBJECTS=PJB_BILLING_METHODS_VL
--RSC_PREREQUISITE_OBJECTS=PJB_BILLING_ASSIGNMENTS

SELECT pjbBillMethodEO.BILL_METHOD_NAME	RES_INVOICE_METHOD_NAME
,(SELECT MEANING FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'PJB_EXTENSION_EXECUTION_LEVEL'
	AND LOOKUP_CODE = pjbBillMethodEO.CALCULATION_LEVEL_CODE) RES_CALCULATION_LEVEL
,pjbBillAssignEO.PROCESSING_ORDER RES_PROCESSING_ORDER
,(SELECT BILLING_EXTENSION_NAME FROM PJB_BILLING_EXTENSIONS
		WHERE BILLING_EXTENSION_ID = pjbBillAssignEO.BILLING_EXTENSION_ID) RES_NAME
,DECODE(pjbBillAssignEO.ACTIVE_FLAG,'Y','Active','Inactive') RES_STATUS
,(SELECT MEANING FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_PJB_CFG_TRANSACTION_CODE'
	AND LOOKUP_CODE = pjbBillAssignEO.TRANSACTION_CODE) RES_TRANSACTION
,(SELECT EVENT_TYPE_NAME
			FROM PJF_EVENT_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND EVENT_TYPE_ID = pjbBillAssignEO.TRANSACTION_TYPE) RES_TRANSACTION_TYPE
,pjbBillAssignEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,pjbBillAssignEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,pjbBillAssignEO.CREATED_BY RSC_CREATED_BY
,pjbBillAssignEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJB_BILLING_METHODS_VL pjbBillMethodEO
,PJB_BILLING_ASSIGNMENTS pjbBillAssignEO
WHERE pjbBillMethodEO.BILL_METHOD_FLAG =  'I'
AND pjbBillMethodEO.BILL_METHOD_ID = pjbBillAssignEO.BILL_METHOD_ID
ORDER BY pjbBillMethodEO.BILL_METHOD_NAME

