/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT (SELECT BU_NAME
    FROM FUN_ALL_BUSINESS_UNITS_V
    WHERE BU_ID = exmCUMULMEO.ORG_ID
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
    ) RES_BUSINESS_UNIT
,(SELECT NAME
	FROM XLE_ENTITY_PROFILES
	WHERE LEGAL_ENTITY_ID = exmCUMULMEO.LEGAL_ENTITY_ID) RES_LEGAL_ENTITY
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = exmCUMULMEO.CUMUL_MILEAGE_PERIOD_CODE
	AND LOOKUP_TYPE = 'EXM_CUMUL_MILEAGE_PERIOD' AND LANGUAGE = USERENV('LANG')) RES_CUMULATIVE_MILEAGE_TRACKIN
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = exmCUMULMEO.PERIOD_START_MONTH
	AND LOOKUP_TYPE = 'MONTH' AND LANGUAGE = USERENV('LANG')) RES_CUMULATIVE_PERIOD_START_MO
,exmCUMULMEO.PERIOD_START_DAY RES_CUMULATIVE_PERIOD_START_DA
,TO_CHAR(exmCUMULMEO.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(exmCUMULMEO.END_DATE,'DD-Mon-YYYY') RES_END_DATE
,DECODE(exmCUMULMEO.ENABLED_VEH_CATEGORY_FLAG,'Y','Yes','No') RES_CUMULATIVE_MILEAGE_DETERMI
,DECODE(exmCUMULMEO.ENABLED_VEH_TYPE_FLAG,'Y','Yes','No') RES_CUMULATIVE_MILEAGE_DETER_0
,DECODE(exmCUMULMEO.ENABLED_FUEL_TYPE_FLAG,'Y','Yes','No') RES_CUMULATIVE_MILEAGE_DETER_1

,exmCUMULMEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,exmCUMULMEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,exmCUMULMEO.CREATED_BY RSC_CREATED_BY
,exmCUMULMEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,exmCUMULMEO.ORG_ID RSC_BUSINESS_UNIT_ID
,exmCUMULMEO.LEGAL_ENTITY_ID RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EXM_CUMUL_MILEAGE_DETERMINANTS exmCUMULMEO