/* ****************************************************************************
 * $Revision$:
 * $Author$:
 * $Date$:
 * $HeadURL$:
 * $Id$:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=XCC_CONTROL_BUDGETS

SELECT xccCONTROLBUDE0.NAME  RES_NAME
,(CASE
	WHEN xccKEYSEGE0.SOURCE_SEGMENT_TYPE = 'GL_COA_SEGMENT' THEN
		(SELECT PROMPT 
			FROM FND_KF_SEGMENTS_VL seg
			,FND_KF_STR_INSTANCES_VL strInst
			WHERE seg.STRUCTURE_ID                 = strInst.STRUCTURE_ID
			AND seg.ENABLED_FLAG                   = 'Y'
			AND strInst.ENABLED_FLAG               = 'Y'
			AND strInst.STRUCTURE_INSTANCE_NUMBER  = xccCONTROLBUDE0.CHART_OF_ACCOUNTS_ID
			AND seg.COLUMN_NAME = xccKEYSEGE0.SOURCE_SEGMENT_COLUMN_NAME)	
	WHEN xccKEYSEGE0.SOURCE_SEGMENT_TYPE = 'PROJECT_SEGMENT' THEN
		(SELECT PROMPT 
			FROM FND_KF_SEGMENTS_VL seg
			,FND_KF_STR_INSTANCES_VL strInst
			WHERE seg.STRUCTURE_ID                 = strInst.STRUCTURE_ID
			AND seg.ENABLED_FLAG                   = 'Y'
			AND strInst.ENABLED_FLAG               = 'Y'
			AND strInst.STRUCTURE_INSTANCE_NUMBER  = xccCONTROLBUDE0.BUDGET_CHART_OF_ACCOUNTS_ID
			AND seg.SEGMENT_CODE = xccKEYSEGE0.SOURCE_SEGMENT_COLUMN_NAME)
	END) RES_BUDGET_SEGMENT
,treesE0.TREE_NAME RES_TREE
,xccKEYSEGTRE0.START_PERIOD_NAME RES_FROM_PERIOD
,xccKEYSEGTRE0.END_PERIOD_NAME RES_TO_PERIOD
,(SELECT TREE_VERSION_NAME 
    FROM FND_TREE_VERSION_VL
    WHERE TREE_STRUCTURE_CODE = xccKEYSEGE0.TREE_STRUCTURE_CODE
    AND TREE_CODE = xccKEYSEGE0.TREE_CODE
    AND TREE_VERSION_ID = xccKEYSEGTRE0.TREE_VERSION_ID
    )  RES_TREE_VERSION

,(CASE
	WHEN xccKEYSEGE0.TREE_STRUCTURE_CODE = 'GL_ACCT_FLEX' THEN
		(SELECT FndLableVlE0.LABEL_NAME
			FROM FND_TREE_LABEL FndTreeLabelE0
			,FND_LABEL_VL FndLableVlE0
			WHERE FndTreeLabelE0.TREE_LABEL_ID = xccKEYSEGTRE0.TREE_LABEL_ID
			AND FndTreeLabelE0.DATA_SOURCE_ID = xccKEYSEGTRE0.TREE_LABEL_DATA_SOURCE_ID
			AND FndTreeLabelE0.TREE_STRUCTURE_CODE = xccKEYSEGE0.TREE_STRUCTURE_CODE
			AND FndTreeLabelE0.TREE_CODE = xccKEYSEGE0.TREE_CODE
			AND FndLableVlE0.LABEL_ID = FndTreeLabelE0.LABEL_PK3_VALUE 
			AND FndTreeLabelE0.DATA_SOURCE_ID = FndLableVlE0.DATA_SOURCE_ID
			AND FndLableVlE0.TREE_STRUCTURE_CODE = xccKEYSEGE0.TREE_STRUCTURE_CODE)
	WHEN xccKEYSEGE0.TREE_STRUCTURE_CODE = 'PJO_XCC_RESOURCE_STRUCTURE' THEN
		(SELECT lk.MEANING
			FROM FND_TREE_LABEL FndTreeLabelE0
			,FND_LOOKUP_VALUES lk
			WHERE FndTreeLabelE0.TREE_LABEL_ID = xccKEYSEGTRE0.TREE_LABEL_ID
			AND FndTreeLabelE0.DATA_SOURCE_ID = xccKEYSEGTRE0.TREE_LABEL_DATA_SOURCE_ID
			AND FndTreeLabelE0.TREE_STRUCTURE_CODE = xccKEYSEGE0.TREE_STRUCTURE_CODE
			AND FndTreeLabelE0.TREE_CODE = xccKEYSEGE0.TREE_CODE
			AND lk.LANGUAGE = USERENV('LANG')
			AND lk.LOOKUP_TYPE = 'PJO_XCC_RES_TR_LBL'
			AND lk.LOOKUP_CODE = FndTreeLabelE0.LABEL_PK1_VALUE )
	END) RES_TREE_LABEL
,xccKEYSEGTRE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,xccKEYSEGTRE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,xccKEYSEGTRE0.CREATED_BY RSC_CREATED_BY
,xccKEYSEGTRE0.CREATION_DATE RSC_CREATION_DATE
,xccCONTROLBUDE0.LEDGER_ID RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
FROM XCC_CONTROL_BUDGETS xccCONTROLBUDE0
,XCC_CB_KEY_SEGMENTS xccKEYSEGE0
,FND_TREE_VL treesE0
,XCC_CB_KEY_SEG_TREE_VERSIONS xccKEYSEGTRE0
WHERE xccCONTROLBUDE0.CONTROL_BUDGET_ID  = xccKEYSEGE0.CONTROL_BUDGET_ID 
AND xccKEYSEGE0.TREE_STRUCTURE_CODE = treesE0.TREE_STRUCTURE_CODE
AND xccKEYSEGE0.TREE_CODE = treesE0.TREE_CODE
AND xccKEYSEGE0.KEY_SEGMENT_ID = xccKEYSEGTRE0.KEY_SEGMENT_ID
ORDER BY xccCONTROLBUDE0.NAME 