/* ****************************************************************************
* $Revision: 71641 $:
* $Author: tanawat.wongjan $:
* $Date: 2019-03-18 14:02:24 +0700 (Mon, 18 Mar 2019) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Worker%20Time%20Entry%20Profiles%20-%20Worker%20View.sql $:
* $Id: Manage Worker Time Entry Profiles - Worker View.sql 71641 2019-03-18 07:02:24Z tanawat.wongjan $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=HRQ_QUESTIONNAIRES_VL

SELECT qTemplatesE0.QUESTIONNAIRE_ID RES_QUESTIONNAIRE_TEMPLATE_ID
,qTemplatesE0.NAME RES_QUESTIONNAIRE_TEMPLATE_NAM
,questionairsE0.QUESTIONNAIRE_CODE RES_QUESTIONNAIRE_CODE
,DECODE(questionairsE0.SCORED_FLAG,'Y','Yes','No') RES_SCORE_QUESTIONNAIRE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HRQ_QSTNR_CALC_RULE_TYPE'
    AND LOOKUP_CODE = questionairsE0.CALC_RULE_CODE
    ) RES_OVERALL_SCORE_CALCULATION_
,questionairsE0.NAME RES_NAME
,foldersE0.NAME RES_FOLDER
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRQ_QUESTIONNAIRE_STATUS'
    AND LOOKUP_CODE = questionairsE0.STATUS
    ) RES_STATUS
,questionairsE0.QSTNR_VERSION_NUM RES_QUESTIONNAIRE_VERSION_NUMB
,DECODE(questionairsE0.IN_USE,'Y','Yes','No') RES_IN_USE
,questionairsE0.INTRO_TEXT RES_INSTRUCTIONS_AND_HELP_MATE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRQ_SECTION_ORDER'
    AND LOOKUP_CODE = questionairsE0.SECTION_ORDER
    ) RES_SECTION_ORDER
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRQ_SECTION_PRESENTATION'
    AND LOOKUP_CODE = questionairsE0.SECTION_PRESENTATION
    ) RES_SECTION_PRESENTATION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRQ_PAGE_LAYOUT'
    AND LOOKUP_CODE = questionairsE0.PAGE_LAYOUT
    ) RES_PAGE_LAYOUT
,questionairsE0.QSTNS_PER_PAGE RES_MAXIMUM_NUMBER_OF_QUESTION
,questionairsE0.KEYWORDS RES_KEYWORDS
,questionairsE0.CREATED_BY  AS RSC_CREATED_BY
,questionairsE0.CREATION_DATE AS RSC_CREATION_DATE
,questionairsE0.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,questionairsE0.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,questionairsE0.BUSINESS_GROUP_ID  RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM HRQ_CATEGORIES_VL foldersE0
,(SELECT *
    FROM HRQ_QUESTIONNAIRES_VL
    WHERE TEMPLATE_FLAG = 'N'
    ) questionairsE0
,HRQ_QSTNR_TEMPLATES_VL qTemplatesE0
WHERE foldersE0.CATEGORY_ID = questionairsE0.CATEGORY_ID
AND questionairsE0.QSTNR_TEMPLATE_ID = qTemplatesE0.QSTNR_TEMPLATE_ID
AND questionairsE0.CATEGORY_ID IN (SELECT CATEGORY_ID FROM HRQ_CATEGORIES_VL foldersE0
START WITH foldersE0.CATEGORY_ID = 3
CONNECT BY PRIOR foldersE0.CATEGORY_ID = foldersE0.PARENT_CATEGORY_ID)