/* ****************************************************************************
 * $Revision: 56623 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-07-11 14:33:44 +0700 (Mon, 11 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Journal%20Sources%20-%20Manage%20Journal%20Sources.sql $:
 * $Id: Manage Journal Sources - Manage Journal Sources.sql 56623 2016-07-11 07:33:44Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT ExmAudListRuleSetsEO.NAME RES_NAME
,ExmAudListRuleSetsEO.DESCRIPTION RES_DESCRIPTION
,DECODE(ExmAudListRuleSetsEO.RECEIPT_DELAY_FLAG,'Y','Yes','No') RES_MAXIMUM_NUMBER_OF_DAYS_TO_
,ExmAudListRuleSetsEO.RECEIPT_DELAY_DAYS RES_MAXIMUM_NUMBER_OF_DAYS_T_0
,ExmAudListRuleSetsEO.RECEIPT_DELAY_LIST_DAYS RES_MAXIMUM_NUMBER_OF_DAYS_T_1
,DECODE(ExmAudListRuleSetsEO.MONTHLY_TOTAL_FLAG,'Y','Yes','No') RES_ALLOWABLE_TOTAL_MONTHLY_AM
,DECODE(ExmAudListRuleSetsEO.MONTHLY_TOTAL_CURRENCY_CODE,NULL,NULL,ExmAudListRuleSetsEO.MONTHLY_TOTAL_CURRENCY_CODE || ' - ' || (SELECT NAME FROM FND_CURRENCIES_VL WHERE CURRENCY_CODE = ExmAudListRuleSetsEO.MONTHLY_TOTAL_CURRENCY_CODE)) RES_ALLOWABLE_TOTAL_MONTHLY__2
,ExmAudListRuleSetsEO.MONTHLY_TOTAL_LIMIT RES_ALLOWABLE_TOTAL_MONTHLY__3
,ExmAudListRuleSetsEO.MONTHLY_TOTAL_LIST_DAYS RES_ALLOWABLE_TOTAL_MONTHLY__4
,DECODE(ExmAudListRuleSetsEO.MONTHLY_VIOLATIONS_FLAG,'Y','Yes','No') RES_ALLOWABLE_NUMBER_OF_POLICY
,ExmAudListRuleSetsEO.MONTHLY_VIOLATIONS_LIMIT RES_ALLOWABLE_NUMBER_OF_POLI_5
,ExmAudListRuleSetsEO.MONTHLY_VIOLATIONS_LIST_DAYS RES_ALLOWABLE_NUMBER_OF_POLI_6
,DECODE(ExmAudListRuleSetsEO.MONTHLY_REPORTS_FLAG,'Y','Yes','No') RES_ALLOWABLE_NUMBER_OF_EXPENS
,ExmAudListRuleSetsEO.MONTHLY_REPORTS_LIMIT RES_ALLOWABLE_NUMBER_OF_EXPE_7
,ExmAudListRuleSetsEO.MONTHLY_REPORTS_LIST_DAYS RES_ALLOWABLE_NUMBER_OF_EXPE_8
,ExmAudListRuleSetsEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ExmAudListRuleSetsEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ExmAudListRuleSetsEO.CREATED_BY RSC_CREATED_BY
,ExmAudListRuleSetsEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EXM_AUD_LIST_RULE_SETS ExmAudListRuleSetsEO
ORDER BY NAME