/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=HXT_SETUP_PROFILES_VL

SELECT tDevicesE0.NAME RES_PROFILE_NAME
,tDevicesE0.DESCRIPTION RES_DESCRIPTION
,TO_CHAR(optionsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,(SELECT NAME
    FROM HWM_TCD_MAPPING_SETS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND TCD_MAPPING_SET_ID = optionsE0.VALUE30
    ) RES_TIME_DEVICE_EVENT_MAPPING_
,(SELECT RULE_SET_NAME
    FROM HWM_RULE_SETS_F
    WHERE RULE_SET_ID = optionsE0.VALUE32
    ) RES_TIME_DEVICE_RULE_SET
,(SELECT RULE_SET_NAME
    FROM HWM_RULE_SETS_F
    WHERE RULE_SET_ID = optionsE0.VALUE33
    ) RES_TIME_SUBMISSION_RULE_SET
,(SELECT NAME
    FROM HWM_TCD_EXP_DATA_DEF_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND TCD_EXP_DATA_DEF_ID = optionsE0.VALUE31
    ) RES_TIME_DEVICE_EXPORT_DATA
,optionsE0.VALUE10 RES_SOURCE_ID
,tDevicesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,tDevicesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,tDevicesE0.CREATED_BY RSC_CREATED_BY
,tDevicesE0.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,tDevicesE0.ENTERPRISE_ID RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM HXT_SETUP_PROFILES_VL tDevicesE0
,HXT_SETUP_OPTION_VALS optionsE0
WHERE tDevicesE0.PRODUCT_AREA = 'TIME_DEVICE'
AND tDevicesE0.SETUP_PROFILE_ID = optionsE0.SETUP_PROFILE_ID
ORDER BY tDevicesE0.PRECEDENCE