/* ****************************************************************************
 * $Revision: 73657 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2020-02-28 12:03:32 +0700 (Fri, 28 Feb 2020) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.20/trunk/core/reverse_sql/FINANCIALS/Manage%20Leave%20Agreements%20-%20Leave%20Agreement.sql $:
 * $Id: Manage Leave Agreements - Leave Agreement.sql 73657 2020-02-28 05:03:32Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=ANC_ABSENCE_AGREEMENTS_VL

WITH PREP_DATA AS (SELECT ABSENCE_AGREEMENT_ID
	,REPLACE(WITHDRAW_REASON_CD||',',' ','') A1
	FROM ANC_ABSENCE_AGREEMENTS_F
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE)
,REASON_TO_ROW AS (SELECT * 
	FROM (SELECT ABSENCE_AGREEMENT_ID
		,1 SEQ
		,SUBSTR(A1,1,INSTR(A1,',',1,1)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,2 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,1)+1,INSTR(A1,',',1,2) - INSTR(A1,',',1,1)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,3 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,2)+1,INSTR(A1,',',1,3) - INSTR(A1,',',1,2)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,4 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,3)+1,INSTR(A1,',',1,4) - INSTR(A1,',',1,3)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,5 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,4)+1,INSTR(A1,',',1,5) - INSTR(A1,',',1,4)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,6 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,5)+1,INSTR(A1,',',1,6) - INSTR(A1,',',1,5)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,7 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,6)+1,INSTR(A1,',',1,7) - INSTR(A1,',',1,6)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,8 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,7)+1,INSTR(A1,',',1,8) - INSTR(A1,',',1,7)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,9 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,8)+1,INSTR(A1,',',1,9) - INSTR(A1,',',1,8)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,10 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,9)+1,INSTR(A1,',',1,10) - INSTR(A1,',',1,9)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,11 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,10)+1,INSTR(A1,',',1,11) - INSTR(A1,',',1,10)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,12 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,11)+1,INSTR(A1,',',1,12) - INSTR(A1,',',1,11)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,13 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,12)+1,INSTR(A1,',',1,13) - INSTR(A1,',',1,12)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,14 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,13)+1,INSTR(A1,',',1,14) - INSTR(A1,',',1,13)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,15 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,14)+1,INSTR(A1,',',1,15) - INSTR(A1,',',1,14)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,16 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,15)+1,INSTR(A1,',',1,16) - INSTR(A1,',',1,15)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,17 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,16)+1,INSTR(A1,',',1,17) - INSTR(A1,',',1,16)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,18 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,17)+1,INSTR(A1,',',1,18) - INSTR(A1,',',1,17)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,19 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,18)+1,INSTR(A1,',',1,19) - INSTR(A1,',',1,18)-1) REASON
		FROM PREP_DATA
		
		UNION
		
		SELECT ABSENCE_AGREEMENT_ID
		,20 SEQ
		,SUBSTR(A1,INSTR(A1,',',1,19)+1,INSTR(A1,',',1,20) - INSTR(A1,',',1,19)-1) REASON
		FROM PREP_DATA)
	WHERE REASON IS NOT NULL
	)
	
SELECT ancABSENAGREEMEO.NAME RES_NAME
,allReasonsE0.MEANING RES_WITHDRAWAL_REASON_NAME
,(CASE
	WHEN EXISTS (SELECT 1 FROM REASON_TO_ROW WHERE ABSENCE_AGREEMENT_ID = ancABSENAGREEMEO.ABSENCE_AGREEMENT_ID AND REASON = allReasonsE0.LOOKUP_CODE) THEN
		'Yes'
	ELSE
		'No'
	END) RES_WITHDRAWAL_REASON_VALUE
,ancABSENAGREEMEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ancABSENAGREEMEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ancABSENAGREEMEO.CREATED_BY RSC_CREATED_BY
,ancABSENAGREEMEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,ancABSENAGREEMEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM ANC_ABSENCE_AGREEMENTS_VL ancABSENAGREEMEO
,(SELECT MEANING
	,LOOKUP_CODE
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ORA_ANC_AGR_WITHDRAWN'
	) allReasonsE0
WHERE SYSDATE BETWEEN ancABSENAGREEMEO.EFFECTIVE_START_DATE AND NVL(ancABSENAGREEMEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND ancABSENAGREEMEO.LANGUAGE = USERENV('LANG')
ORDER BY ancABSENAGREEMEO.NAME