/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT (SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = smartFormsE0.PRC_BU_ID
	) RES_PROCUREMENT_BU
,smartFormsE0.SMART_FORM_NAME RES_SMART_FORM
,smartFormsE0.DESCRIPTION RES_INSTRUCTION_TEXT
,REPLACE(REPLACE(REPLACE(TO_CHAR(smartFormsE0.KEYWORDS),CHR(38),CHR(38)||'amp;'),chr(13),' '),chr(10),' ') RES_KEYWORDS
,smartFormsE0.IMAGE RES_IMAGE_URL
,(SELECT LINE_TYPE
	FROM PO_LINE_TYPES_VL
	WHERE LINE_TYPE_ID = smartFormsE0.LINE_TYPE_ID
	) RES_LINE_TYPE
,smartFormsE0.ITEM_DESCRIPTION RES_ITEM_DESCRIPTION
,DECODE(smartFormsE0.ITEM_DESC_EDITABLE_FLAG,'Y','Yes','No') RES_ITEM_DESCRIPTION_USER_EDIT
,(SELECT CATEGORY_NAME
	FROM POR_BROWSE_CATEGORIES_VL
	WHERE CATEGORY_ID = smartFormsE0.BROWSING_CATEGORY_ID
	) RES_RESTRICT_TO_BROWSING_CATEG
,(SELECT CATEGORY_NAME
	FROM EGP_CATEGORIES_VL
	WHERE CATEGORY_ID = smartFormsE0.CATEGORY_ID
	) RES_CATEGORY_NAME
,DECODE(smartFormsE0.CATEGORY_EDITABLE_FLAG,'Y','Yes','No') RES_CATEGORY_NAME_USER_EDITABL
,smartFormsE0.QUANTITY RES_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = smartFormsE0.UOM_CODE
	) RES_UOM
,DECODE(smartFormsE0.UOM_EDITABLE_FLAG,'Y','Yes','No') RES_UOM_USER_EDITABLE
,smartFormsE0.UNIT_PRICE RES_PRICE
,DECODE(smartFormsE0.UNIT_PRICE_EDITABLE_FLAG,'Y','Yes','No') RES_PRICE_USER_EDITABLE
,smartFormsE0.CURRENCY_CODE RES_CURRENCY
,DECODE(smartFormsE0.CURRENCY_EDITABLE_FLAG,'Y','Yes','No') RES_CURRENCY_USER_EDITABLE
,smartFormsE0.AMOUNT RES_AMOUNT
,DECODE(smartFormsE0.AMOUNT_EDITABLE_FLAG,'Y','Yes','No') RES_AMOUNT_USER_EDITABLE
,DECODE(smartFormsE0.NEGOTIATION_REQUIRED_FLAG,'Y','Yes','No') RES_NEGOTIATION_REQUIRED
,DECODE(smartFormsE0.NEGOTIATION_REQ_EDITABLE_FLAG,'Y','Yes','No') RES_NEGOTIATION_REQUIRED_USER_
,DECODE(smartFormsE0.NEGOTIATED_FLAG,'Y','Yes','No') RES_NEGOTIATED
,DECODE(smartFormsE0.NEGOTIATED_EDITABLE_FLAG,'Y','Yes','No') RES_NEGOTIATED_USER_EDITABLE
,smartFormsE0.AGREEMENT_ID RES_AGREEMENT -- No data to convert this column
,DECODE(smartFormsE0.AGREEMENT_EDITABLE_FLAG,'Y','Yes','No') RES_AGREEMENT_USER_EDITABLE
,(SELECT partyE0.PARTY_NAME 
	FROM POZ_SUPPLIERS supE0
	,HZ_PARTIES partyE0
	WHERE supE0.PARTY_ID = partyE0.PARTY_ID
	AND supE0.VENDOR_ID = smartFormsE0.SUPPLIER_ID
	) RES_SUPPLIER
,DECODE(smartFormsE0.SUPPLIER_EDITABLE_FLAG,'Y','Yes','No') RES_SUPPLIER_USER_EDITABLE
,(SELECT supSitesE0.VENDOR_SITE_CODE
	FROM POZ_SUPPLIERS supE0
	,POZ_SUPPLIER_SITES_ALL_M supSitesE0
	WHERE supE0.VENDOR_ID = supSitesE0.VENDOR_ID
	AND supSitesE0.VENDOR_ID = smartFormsE0.SUPPLIER_ID
	AND supSitesE0.VENDOR_SITE_ID = smartFormsE0.SUPPLIER_SITE_ID
	) RES_SUPPLIER_SITE
,DECODE(smartFormsE0.SITE_EDITABLE_FLAG,'Y','Yes','No') RES_SUPPLIER_SITE_USER_EDITABL
,(SELECT partyE0.PERSON_LAST_NAME||', '||partyE0.PERSON_FIRST_NAME 
	FROM POZ_SUPPLIER_CONTACTS supContactE0
	,HZ_PARTIES partyE0
	WHERE supContactE0.PER_PARTY_ID = partyE0.PARTY_ID
	AND supContactE0.VENDOR_CONTACT_ID = smartFormsE0.SUPPLIER_CONTACT_ID
	) RES_CONTACT
,smartFormsE0.SUPPLIER_CONTACT_PHONE RES_PHONE
,DECODE(smartFormsE0.PHONE_EDITABLE_FLAG,'Y','Yes','No') RES_PHONE_USER_EDITABLE
,smartFormsE0.SUPPLIER_ITEM_NUMBER RES_SUPPLIER_ITEM
,DECODE(smartFormsE0.SUPPLIER_ITEM_EDITABLE_FLAG,'Y','Yes','No') RES_SUPPLIER_ITEM_USER_EDITABL
,smartFormsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,smartFormsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,smartFormsE0.CREATED_BY RSC_CREATED_BY
,smartFormsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,smartFormsE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM POR_SMART_FORMS_ALL_VL smartFormsE0
ORDER BY 1,2