/* ****************************************************************************
 * $Revision: 72749 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2019-10-23 15:22:46 +0700 (Wed, 23 Oct 2019) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Availability%20Lookups%20-%20Lookup%20Types.sql $:
 * $Id: Manage Availability Lookups - Lookup Types.sql 72749 2019-10-23 08:22:46Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
--RSC_PREREQUISITE_OBJECTS=CMP_PLANS_VL 
-- REPLACE_HTML_KEYWORD = RES_USER_DEFINED_TEXT
 
SELECT cmpPLANEO.PLAN_NAME RES_PLAN
,DECODE(cmpPLANEO.PLAN_INFO_ENABLED_FLAG,'Y','Yes','No') RES_ENABLE_PLAN_INFORMATION_TA
,cmpPLANEO.PLAN_INFO_TASK_NAME RES_TASK_NAME
,(SELECT DECODE(ENABLED_FLAG,'Y','Yes','No') FROM CMP_LOOKUP_USAGES_VL WHERE ATTRIBUTE_VALUE = 'ORA_MANAGER_DUE_DATE' AND KEY_VALUE = cmpPLANEO.PLAN_ID) RES_MANAGER_DUE_DATE
,(SELECT DECODE(ENABLED_FLAG,'Y','Yes','No') FROM CMP_LOOKUP_USAGES_VL WHERE ATTRIBUTE_VALUE = 'ORA_EVALUATION_PERIOD' AND KEY_VALUE = cmpPLANEO.PLAN_ID) RES_EVALUATION_PERIOD_FROM_CYC
,(SELECT DECODE(ENABLED_FLAG,'Y','Yes','No') FROM CMP_LOOKUP_USAGES_VL WHERE ATTRIBUTE_VALUE = 'ORA_PLAN_ACCESS_PERIOD' AND KEY_VALUE = cmpPLANEO.PLAN_ID) RES_PLAN_ACCESS_PERIOD_FROM_CY
,(SELECT DECODE(ENABLED_FLAG,'Y','Yes','No') FROM CMP_LOOKUP_USAGES_VL WHERE ATTRIBUTE_VALUE = 'ORA_HR_DATA_EXTRACT_DATE' AND KEY_VALUE = cmpPLANEO.PLAN_ID) RES_HR_DATA_EXTRACTION_DATE_FR
,(SELECT DECODE(ENABLED_FLAG,'Y','Yes','No') FROM CMP_LOOKUP_USAGES_VL WHERE ATTRIBUTE_VALUE = 'ORA_CORP_CURRENCY' AND KEY_VALUE = cmpPLANEO.PLAN_ID) RES_CORPORATE_CURRENCY_FROM_PL
,DECODE(userDEFINE1.ENABLED_FLAG,'Y','Yes','No') RES_USER_DEFINED_1_ENABLE
,userDEFINE1.DESCRIPTION RES_USER_DEFINED_1_DESCRIPTION
,userDEFINE1.DISPLAY_NAME RES_USER_DEFINED_1_VALUE
,DECODE(userDEFINE1.ENABLED_FLAG,'Y','Yes','No') RES_USER_DEFINED_2_ENABLE
,userDEFINE1.DESCRIPTION RES_USER_DEFINED_2_DESCRIPTION
,userDEFINE1.DISPLAY_NAME RES_USER_DEFINED_2_VALUE
,REPLACE(REPLACE(REPLACE(cmpINSTRUCE0.INSTRUCTION_TEXT,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#') RES_USER_DEFINED_TEXT
,cmpPLANEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,cmpPLANEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,cmpPLANEO.CREATED_BY RSC_CREATED_BY
,cmpPLANEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
FROM CMP_PLANS_VL cmpPLANEO
,CMP_INSTRUCTIONS_VL cmpINSTRUCE0
,(SELECT * FROM CMP_LOOKUP_USAGES_VL WHERE ATTRIBUTE_VALUE = 'ORA_CUSTOM_DATA1') userDEFINE1
,(SELECT * FROM CMP_LOOKUP_USAGES_VL WHERE ATTRIBUTE_VALUE = 'ORA_CUSTOM_DATA2') userDEFINE2
WHERE cmpPLANEO.COMP_TYPE = 'CWB'
AND cmpPLANEO.PLAN_ID = cmpINSTRUCE0.INSTRUCTION_KEY(+)
AND cmpPLANEO.PLAN_ID = userDEFINE1.KEY_VALUE(+)
AND cmpPLANEO.PLAN_ID = userDEFINE2.KEY_VALUE(+)
AND cmpINSTRUCE0.KEY_TYPE = 'PLANINFO'
ORDER BY cmpPLANEO.PLAN_NAME