/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Depreciation%20Methods%20-%20Depreciation%20Flat%20Rates.sql $:
 * $Id: Manage Depreciation Methods - Depreciation Flat Rates.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT QRSLT.METHOD_CODE RES_NAME
,QRSLT.SET_NAME RES_REFERENCE_DATA_SET
,QRSLT.MEANING RES_METHOD_TYPE
,TRUNC(QRSLT.LIFE_IN_MONTHS/12) RES_LIFE_IN_YEARS
,MOD(QRSLT.LIFE_IN_MONTHS,12) RES_LIFE_IN_MONTHS
,DECODE(USE_LIFE_IN_PERIODS_FLAG,'Y',QRSLT.LIFE_IN_MONTHS,NULL) RES_LIFE_IN_PERIODS
,(QRSLT.BASIC_RATE*100) RES_BASIC_RATE
,(QRSLT.ADJUSTING_RATE*100) RES_ADJUSTING_RATE
,(QRSLT.ADJUSTED_RATE*100)  RES_ADJUSTED_RATE
,QRSLT.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY RSC_CREATED_BY
,QRSLT.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

from 
(select DEPRECIATIONMETHODEO.METHOD_CODE
,DepreciationFlatRateEO.METHOD_ID
,DepreciationFlatRateEO.FLAT_RATE_ID
,DepreciationFlatRateEO.BASIC_RATE
,DepreciationFlatRateEO.ADJUSTING_RATE
,DepreciationFlatRateEO.ADJUSTED_RATE
,DepreciationFlatRateEO.LAST_UPDATE_DATE
,DepreciationFlatRateEO.LAST_UPDATED_BY
,DEPRECIATIONFLATRATEEO.CREATED_BY
,DepreciationFlatRateEO.CREATION_DATE
,SETIDSETSEO.SET_NAME 
,LookupMethodTypePEO.meaning
,DEPRECIATIONMETHODEO.LIFE_IN_MONTHS
,DEPRECIATIONMETHODEO.USE_LIFE_IN_PERIODS_FLAG
from FA_FLAT_RATES DEPRECIATIONFLATRATEEO ,
FA_METHODS DEPRECIATIONMETHODEO ,
FND_SETID_SETS_VL SETIDSETSEO,
FND_LOOKUPS LookupMethodTypePEO
where DEPRECIATIONFLATRATEEO.METHOD_ID = DEPRECIATIONMETHODEO.METHOD_ID
and DEPRECIATIONMETHODEO.SET_ID                    = SETIDSETSEO.SET_ID(+)
and LookupMethodTypePEO.LOOKUP_TYPE (+)          = 'FA_RATE_SOURCE_RULE'
AND DepreciationMethodEO.RATE_SOURCE_RULE          = LookupMethodTypePEO.LOOKUP_CODE (+)
) QRSLT