/* ****************************************************************************
* $Revision: 78557 $:
* $Author: tanawat.wongjan $:
* $Date: 2022-05-24 10:32:18 +0700 (Tue, 24 May 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Project%20Templates%20-%20Project%20Plan%20Resources.sql $:
* $Id: Manage Project Templates - Project Plan Resources.sql 78557 2022-05-24 03:32:18Z tanawat.wongjan $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT projTemplatesE0.NAME RES_TEMPLATE_NAME
,projTemplatesE0.SEGMENT1 RES_TEMPLATE_NUMBER
,(SELECT ELEMENT_NUMBER
	FROM PJF_PROJ_ELEMENTS_VL
	WHERE PROJ_ELEMENT_ID = projElementsE0.DENORM_PARENT_ELEMENT_ID
	) RES_PARENT_TASK_NUMBER
,projElementsE0.ELEMENT_NUMBER RES_TASK_NUMBER
,(CASE
	WHEN elementResourcsE0.RES_TYPE_CODE = 'NAMED_PERSON' THEN
		(SELECT DISPLAY_NAME
			FROM PER_PERSON_NAMES_F
			WHERE NAME_TYPE = 'GLOBAL'
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
			AND PERSON_ID = elementResourcsE0.PERSON_ID)
	WHEN elementResourcsE0.RES_TYPE_CODE = 'JOB' THEN
		(SELECT NAME
			FROM PER_JOBS_F_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND JOB_ID = elementResourcsE0.JOB_ID)
	WHEN elementResourcsE0.RES_TYPE_CODE = 'EXPENDITURE_CATEGORY' THEN
		(SELECT EXPENDITURE_CATEGORY_NAME 
			FROM PJF_EXP_CATEGORIES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND EXPENDITURE_CATEGORY_ID = elementResourcsE0.EXPENDITURE_CATEGORY_ID)
	WHEN elementResourcsE0.RES_TYPE_CODE = 'EXPENDITURE_TYPE' THEN
		(SELECT EXPENDITURE_TYPE_NAME 
			FROM PJF_EXP_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND EXPENDITURE_TYPE_ID = elementResourcsE0.EXPENDITURE_TYPE_ID)
	WHEN elementResourcsE0.RES_TYPE_CODE = 'RESOURCE_CLASS' THEN
		(SELECT NAME
			FROM PJF_RESOURCE_CLASSES_VL
			WHERE RESOURCE_CLASS_CODE = elementResourcsE0.RESOURCE_CLASS_CODE)
	ELSE elementResourcsE0.RES_TYPE_CODE
	END) RES_RESOURCE
,TO_CHAR(elementResourcsE0.PLANNING_START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(elementResourcsE0.PLANNING_END_DATE,'DD-Mon-YYYY') RES_FINISH_DATE
,planLinesE0.TOTAL_QUANTITY RES_QUANTITY_PLANNED
,'' RES_QUANTITY_ITD_ACTUAL
,planLinesE0.TOTAL_TC_RAW_COST RES_RAW_COST_PLANNED
,'' RES_RAW_COST_ITD_ACTUAL
,planLinesE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,planLinesE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,planLinesE0.CREATED_BY  RSC_CREATED_BY
,planLinesE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,projTemplatesE0.ORG_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJF_PROJECTS_ALL_VL projTemplatesE0
,FUN_ALL_BUSINESS_UNITS_V buE0
,PJF_PROJ_ELEMENTS_VL projElementsE0
,(SELECT planE.*
	FROM PJO_PLANNING_ELEMENTS planE
	,PJO_PLAN_VERSIONS_VL planV
	WHERE planE.PLAN_VERSION_ID = planV.PLAN_VERSION_ID
	AND planV.VERSION_NAME = 'Project Plan'
	) elementResourcsE0
,PJO_PLAN_LINES planLinesE0
WHERE projTemplatesE0.TEMPLATE_FLAG = 'Y'
AND projTemplatesE0.ORG_ID = buE0.BU_ID
AND projTemplatesE0.PROJECT_ID = projElementsE0.PROJECT_ID
AND projElementsE0.PROJ_ELEMENT_ID = elementResourcsE0.TASK_ID
AND projElementsE0.PROJECT_ID = elementResourcsE0.PROJECT_ID
AND elementResourcsE0.PLANNING_ELEMENT_ID = planLinesE0.PLANNING_ELEMENT_ID
ORDER BY projTemplatesE0.NAME
,DECODE(projElementsE0.OBJECT_TYPE,'PJF_STRUCTURES',1,2)
,projElementsE0.DENORM_WBS_LEVEL
,projElementsE0.ELEMENT_NUMBER