/* ****************************************************************************
 * $Revision: 61008 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-09 17:41:07 +0700 (Thu, 09 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Receivables%20System%20Options%20-%20System%20Options%20-%20GDF.sql $:
 * $Id: Manage Receivables System Options - System Options - GDF.sql 61008 2017-02-09 10:41:07Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=7003##RES##JG_EGP_SYSTEM_ITEMS
-- DFF_ATTRIBUTES=ATTRIBUTE,GLOBAL_ATTRIBUTE,GLOBAL_ATTRIBUTE_NUMBER,GLOBAL_ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

SELECT 
(SELECT ITEM_CLASS_NAME
	FROM EGP_ITEM_CLASSES_VL
	WHERE ITEM_CLASS_ID = ItemClassPEO.PARENT_ITEM_CLASS_ID
	) RES_PARENT_ITEM_CLASS 
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,ItemVersionEO.TEMPLATE_NAME RES_NAME
,OrgOrganizationDefinitionsPE1.ORGANIZATION_CODE RES_ORGANIZATION
,ItemVersionEO.GLOBAL_ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ItemVersionEO.GLOBAL_ATTRIBUTE1
,ItemVersionEO.GLOBAL_ATTRIBUTE2
,ItemVersionEO.GLOBAL_ATTRIBUTE3
,ItemVersionEO.GLOBAL_ATTRIBUTE4
,ItemVersionEO.GLOBAL_ATTRIBUTE5
,ItemVersionEO.GLOBAL_ATTRIBUTE6
,ItemVersionEO.GLOBAL_ATTRIBUTE7
,ItemVersionEO.GLOBAL_ATTRIBUTE8
,ItemVersionEO.GLOBAL_ATTRIBUTE9
,ItemVersionEO.GLOBAL_ATTRIBUTE10
,ItemVersionEO.GLOBAL_ATTRIBUTE11
,ItemVersionEO.GLOBAL_ATTRIBUTE12
,ItemVersionEO.GLOBAL_ATTRIBUTE13
,ItemVersionEO.GLOBAL_ATTRIBUTE14
,ItemVersionEO.GLOBAL_ATTRIBUTE15
,ItemVersionEO.GLOBAL_ATTRIBUTE16
,ItemVersionEO.GLOBAL_ATTRIBUTE17
,ItemVersionEO.GLOBAL_ATTRIBUTE18
,ItemVersionEO.GLOBAL_ATTRIBUTE19
,ItemVersionEO.GLOBAL_ATTRIBUTE20
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER1
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER2
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER3
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER4
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER5
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE1,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE1
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE2,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE2
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE3,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE3
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE4,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE4
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE5,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE5
,ItemVersionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemVersionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemVersionEO.CREATED_BY RSC_CREATED_BY
,ItemVersionEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(SELECT BUSINESS_UNIT_ID
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemVersionEO.ORGANIZATION_ID
	) RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,(CASE
	WHEN EXISTS
		(SELECT DISTINCT MASTER_ORGANIZATION_ID
			FROM INV_ORG_PARAMETERS
			WHERE MASTER_ORGANIZATION_ID = ItemVersionEO.ORGANIZATION_ID)
	THEN NULL
	ELSE ItemVersionEO.ORGANIZATION_ID
	END) RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,(
   SELECT
 B.ITEM_CATALOG_GROUP_ID, 
  B.ORGANIZATION_ID, 
  T.TEMPLATE_NAME, 
    B.GLOBAL_ATTRIBUTE_CATEGORY, 
    B.GLOBAL_ATTRIBUTE1, 
    B.GLOBAL_ATTRIBUTE2, 
    B.GLOBAL_ATTRIBUTE3, 
    B.GLOBAL_ATTRIBUTE4, 
    B.GLOBAL_ATTRIBUTE5, 
    B.GLOBAL_ATTRIBUTE6, 
    B.GLOBAL_ATTRIBUTE7, 
    B.GLOBAL_ATTRIBUTE8, 
    B.GLOBAL_ATTRIBUTE9, 
    B.GLOBAL_ATTRIBUTE10, 
    B.GLOBAL_ATTRIBUTE11, 
    B.GLOBAL_ATTRIBUTE12, 
    B.GLOBAL_ATTRIBUTE13, 
    B.GLOBAL_ATTRIBUTE14, 
    B.GLOBAL_ATTRIBUTE15, 
    B.GLOBAL_ATTRIBUTE16, 
    B.GLOBAL_ATTRIBUTE17, 
    B.GLOBAL_ATTRIBUTE18, 
    B.GLOBAL_ATTRIBUTE19, 
    B.GLOBAL_ATTRIBUTE20, 
    B.GLOBAL_ATTRIBUTE_NUMBER1, 
    B.GLOBAL_ATTRIBUTE_NUMBER2, 
    B.GLOBAL_ATTRIBUTE_NUMBER3, 
    B.GLOBAL_ATTRIBUTE_NUMBER4, 
    B.GLOBAL_ATTRIBUTE_NUMBER5, 
     B.GLOBAL_ATTRIBUTE_DATE1, 
    B.GLOBAL_ATTRIBUTE_DATE2, 
    B.GLOBAL_ATTRIBUTE_DATE3, 
    B.GLOBAL_ATTRIBUTE_DATE4, 
    B.GLOBAL_ATTRIBUTE_DATE5, 
    B.CREATION_DATE, 
    B.CREATED_BY, 
    B.LAST_UPDATE_DATE, 
    B.LAST_UPDATED_BY
FROM 
    EGP_SYSTEM_ITEMS_TL T, 
    EGP_SYSTEM_ITEMS_B B 
WHERE 
    B.INVENTORY_ITEM_ID = T.INVENTORY_ITEM_ID 
    and T.TEMPLATE_NAME IS NOT NULL
    AND B.ORGANIZATION_ID = T.ORGANIZATION_ID 
    AND T.LANGUAGE = USERENV('LANG')
    AND(B.GLOBAL_ATTRIBUTE_CATEGORY IS NOT NULL
OR B.GLOBAL_ATTRIBUTE1          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE2          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE3          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE4          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE5          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE6          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE7          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE8          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE9          IS NOT NULL
OR B.GLOBAL_ATTRIBUTE10         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE11         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE12         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE13         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE14         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE15         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE16         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE17         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE18         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE19         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE20         IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_NUMBER1   IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_NUMBER2   IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_NUMBER3   IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_NUMBER4   IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_NUMBER5   IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_DATE1     IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_DATE2     IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_DATE3     IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_DATE4     IS NOT NULL
OR B.GLOBAL_ATTRIBUTE_DATE5     IS NOT NULL)
 
 ) ItemVersionEO
,INV_ORGANIZATION_DEFINITIONS_V OrgOrganizationDefinitionsPE1
WHERE /*ItemVersionEO.TEMPLATE_NAME IS NOT NULL
AND*/ ItemClassPEO.ITEM_CLASS_ID             = ItemVersionEO.ITEM_CATALOG_GROUP_ID
AND ItemVersionEO.ORGANIZATION_ID = OrgOrganizationDefinitionsPE1.ORGANIZATION_ID
/*AND(ItemVersionEO.GLOBAL_ATTRIBUTE_CATEGORY IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE1          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE2          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE3          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE4          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE5          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE6          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE7          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE8          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE9          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE10         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE11         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE12         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE13         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE14         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE15         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE16         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE17         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE18         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE19         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE20         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER1   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER2   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER3   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER4   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER5   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE1     IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE2     IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE3     IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE4     IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE5     IS NOT NULL)*/
CONNECT BY ItemClassPEO.PARENT_ITEM_CLASS_ID = ItemClassPEO.ITEM_CLASS_ID
ORDER SIBLINGS BY RES_PARENT_ITEM_CLASS,RES_ITEM_CLASS,RES_NAME