/* ****************************************************************************
 * $Revision: 54943 $:
 * $Author: paul.wakefield $:
 * $Date: 2016-05-04 13:45:23 +0700 (Wed, 04 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Trading%20Community%20Person%20Lookups%20-%20Standard%20Lookup%20Type.sql $:
 * $Id: Manage Trading Community Person Lookups - Standard Lookup Type.sql 54943 2016-05-04 06:45:23Z paul.wakefield $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
--RSC_PREREQUISITE_OBJECTS=PAY_CHECKLISTS_VL 
 
SELECT payFLOWEO.FLOW_NAME RES_FLOW_PATTERN
,payFLOWTASK.FLOW_TASK_NAME RES_FLOW_TASK
,(SELECT TASK_NAME FROM PAY_TASKS_VL WHERE TASK_ID = payFLOWTASK.BASE_TASK_ID) RES_TASK
,(SELECT CHECKLIST_NAME FROM PAY_CHECKLISTS_VL WHERE CHECKLIST_ID = payCHECKLISTEO.PARENT_CHECKLIST_ID) RES_PARENT_CHECKLIST
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payCHECKLISTEO.OWNER_TYPE
		AND LOOKUP_TYPE = 'ORA_PAY_TASK_OWNERSHIP' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_OWNER_TYPE
,(CASE
	WHEN payCHECKLISTEO.OWNER_TYPE = 'USER' THEN
		(SELECT USERNAME
			FROM PER_USERS
			WHERE USER_ID = payCHECKLISTEO.OWNER_ID
			AND SYSDATE BETWEEN START_DATE AND NVL(END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY')))			
	WHEN payCHECKLISTEO.OWNER_TYPE = 'GROUP' THEN
		(SELECT ROLE_NAME
			FROM PER_ROLES_DN_VL
			WHERE ROLE_COMMON_NAME = payCHECKLISTEO.OWNER_ID) 		
	END) RES_OWNER
,payCHECKLISTEO.DESCRIPTION RES_DESCRIPTION
,payCHECKLISTEO.RUN_SEQUENCE RES_SEQUENCE

,DECODE(payFLOWTASK.START_NOTIF_FLAG,'Y','Yes','No') RES_FLOW_TASK_START_NOTIFICATI
,DECODE(payFLOWTASK.END_NOTIF_FLAG,'Y','Yes','No') RES_FLOW_TASK_END_NOTIFICATION
,DECODE(payFLOWTASK.WARNING_NOTIF_FLAG,'Y','Yes','No') RES_WARNING_NOTIFICATION
,DECODE(payFLOWTASK.ERROR_NOTIF_FLAG,'Y','Yes','No') RES_ERROR

,payFLOWTASK.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payFLOWTASK.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payFLOWTASK.CREATED_BY RSC_CREATED_BY
,payFLOWTASK.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PAY_FLOWS_VL payFLOWEO
,PAY_FLOW_TASKS_VL payFLOWTASK
,PAY_CHECKLISTS_VL payCHECKLISTEO
WHERE payFLOWEO.FLOW_ID = payFLOWTASK.BASE_FLOW_ID 
AND payFLOWTASK.BASE_FLOW_TASK_ID = payCHECKLISTEO.BASE_FLOW_TASK_ID
AND payFLOWTASK.CATEGORY_TYPE IS NOT NULL
ORDER BY payFLOWEO.FLOW_NAME,payFLOWTASK.FLOW_TASK_NAME