/* ****************************************************************************
 * $Revision: 72749 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2019-10-23 15:22:46 +0700 (Wed, 23 Oct 2019) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Availability%20Lookups%20-%20Lookup%20Types.sql $:
 * $Id: Manage Availability Lookups - Lookup Types.sql 72749 2019-10-23 08:22:46Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
--RSC_PREREQUISITE_OBJECTS=CMP_PLANS_VL
 
SELECT cmpPLANEO.PLAN_NAME RES_PLAN
,DECODE(cmpPLANEO.EMP_STATEMENT_ENABLED_FLAG,'Y','Yes','No') RES_ENABLE_WORKER_STATEMENT
,(SELECT NAME FROM CMP_STMT_GROUPS_TL WHERE STMT_GROUP_ID = cmpPLANEO.STATEMENT_GROUP_ID AND LANGUAGE = USERENV('LANG')) RES_STATEMENT_GROUP
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpPLANEO.STMT_VIEW_STATUS
			AND LOOKUP_TYPE = 'CMP_STMT_VIEW_STATUS' AND LANGUAGE = USERENV('LANG')
			AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_STATEMENT_GENERATION_TIMIN
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpPLANEO.STMT_OUTPUT_FORMAT
			AND LOOKUP_TYPE = 'CMP_STMT_OUTPUT_FORMAT' AND LANGUAGE = USERENV('LANG')
			AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_OUTPUT_FORMAT
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpPLANEO.STMT_DELIVERY_TYPE
			AND LOOKUP_TYPE = 'ORA_CMP_STMT_DELIVERY' AND LANGUAGE = USERENV('LANG')
			AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_STATEMENT_DELIVERY
,DECODE(cmpPLANEO.MULTIPLE_STMT_ENABLED_FLAG,'Y','Yes','No') RES_ALLOW_MANAGERS_TO_COMBINE_
,DECODE(cmpPLANEO.ALLOW_STAGGERED_STMT_RELEASE,'Y','Yes','No')  RES_ALLOW_STAGGERED_RELEASE_OF
,cmpPLANEO.STMT_DAYS_UNTIL_EXPIRATION RES_DAYS_UNTIL_EXPIRATION

 
,cmpPLANEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,cmpPLANEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,cmpPLANEO.CREATED_BY RSC_CREATED_BY
,cmpPLANEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CMP_PLANS_VL cmpPLANEO
WHERE cmpPLANEO.COMP_TYPE = 'CWB'
ORDER BY cmpPLANEO.PLAN_NAME