/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Default%20Item%20Class%20-%20Item%20Organization%20(Service).sql $:
 * $Id: Manage Default Item Class - Item Organization (Service).sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EGP_SYSTEM_ITEMS_V

SELECT ItemClassPEO.ITEM_CLASS_CODE RES_INTERNAL_NAME
,ItemVersionEO.TEMPLATE_NAME RES_NAME
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemVersionEO.ORGANIZATION_ID
	) RES_ORGANIZATION
,DECODE(ItemVersionEO.ASSET_TRACKED_FLAG,'Y','Yes','N','No') RES_ENABLE_ASSET_TRACKING
,DECODE(ItemVersionEO.ALLOW_MAINTENANCE_ASSET_FLAG,'Y','Yes','N','No') RES_ALLOW_MAINTENANCE_ASSET
,DECODE(ItemVersionEO.ENABLE_GENEALOGY_TRACKING_FLAG,'Y','Yes','N','No') RES_ENABLE_GENEALOGY_TRACKING
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_CSE_ASSET_CLASS'
	AND LOOKUP_CODE = ItemVersionEO.ASSET_CLASS
	) RES_ASSET_CLASS
,DECODE(ItemVersionEO.CSS_ENABLED_FLAG,'Y','Yes','N','No') RES_ENABLE_FOR_CUSTOMER_SELF_S
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_SER_REQ_ENABLED_CODE'
	AND LOOKUP_CODE = ItemVersionEO.SERV_REQ_ENABLED_CODE
	) RES_SERVICE_REQUEST
,DECODE(ItemVersionEO.DEFECT_TRACKING_ON_FLAG,'Y','Yes','N','No') RES_ENABLE_DEFECT_TRACKING
,DECODE(ItemVersionEO.SERVICEABLE_PRODUCT_FLAG,'Y','Yes','N','No') RES_ENABLE_CONTRACT_COVERAGE
,DECODE(ItemVersionEO.COMMS_ACTIVATION_REQD_FLAG,'Y','Yes','N','No') RES_ENABLE_PROVISIONING
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_SERV_DUR_TYPE_CODE'
	AND LOOKUP_CODE = ItemVersionEO.SERVICE_DURATION_TYPE_CODE
	) RES_SERVICE_DURATION_TYPE
,ItemVersionEO.SERVICE_DURATION RES_DURATION
,ItemVersionEO.SERVICE_DURATION_PERIOD_CODE RES_DURATION_PERIOD -- Not found in Internal
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_SERV_START_TYPE_CODE'
	AND LOOKUP_CODE = ItemVersionEO.SERVICE_START_TYPE_CODE
	) RES_SERVICE_START_TYPE
,ItemVersionEO.SERVICE_START_DELAY RES_SERVICE_START_DELAY
,DECODE(ItemVersionEO.ALLOW_SUSPEND_FLAG,'Y','Yes','N','No') RES_ALLOW_SUSPEND
,DECODE(ItemVersionEO.ALLOW_TERMINATE_FLAG,'Y','Yes','N','No') RES_ALLOW_TERMINATE
,DECODE(ItemVersionEO.REQUIRES_FULFILLMENT_LOC_FLAG,'Y','Yes','N','No') RES_REQUIRES_FULFILLMENT_LOCAT
,DECODE(ItemVersionEO.REQUIRES_ITM_ASSOCIATION_FLAG,'Y','Yes','N','No') RES_REQUIRES_ITEM_ASSOCIATION
/*,DECODE(ItemVersionEO.COMMS_NL_TRACKABLE_FLAG,'Y','Yes','N','No') RES_TRACK_IN_INSTALLED_BASE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_COMMON_YES_NO_NUM'
	AND LOOKUP_CODE = ItemVersionEO.ASSET_CREATION_CODE
	) RES_CREATE_FIXED_ASSET
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_IB_INSTANCE_CLASS_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.IB_ITEM_INSTANCE_CLASS
	) RES_INSTANCE_CLASS*/
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_MATERIAL_BILLABLE_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.MATERIAL_BILLABLE_FLAG
	) RES_BILLING_TYPE
,DECODE(ItemVersionEO.SERV_BILLING_ENABLED_FLAG,'Y','Yes','N','No') RES_ENABLE_SERVICE_BILLING
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_RECOVERED_PART_DISP_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.RECOVERED_PART_DISP_CODE
	) RES_RECOVERED_PART_DISPOSITION
,ItemVersionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemVersionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemVersionEO.CREATED_BY RSC_CREATED_BY
,ItemVersionEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,ItemVersionEO.ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,EGP_SYSTEM_ITEMS_V ItemVersionEO
WHERE ItemClassPEO.PARENT_ITEM_CLASS_ID NOT IN (SELECT ITEM_CLASS_ID FROM EGP_ITEM_CLASSES_VL)
AND ItemVersionEO.TEMPLATE_NAME IS NOT NULL
AND ItemClassPEO.ITEM_CLASS_ID = ItemVersionEO.ITEM_CATALOG_GROUP_ID
AND (--ItemVersionEO.EAM_ITEM_TYPE IS NOT NULL
--OR ItemVersionEO.EAM_ACTIVITY_CAUSE_CODE IS NOT NULL
--OR ItemVersionEO.EAM_ACT_SHUTDOWN_STATUS IS NOT NULL
ItemVersionEO.ASSET_TRACKED_FLAG IS NOT NULL
--OR ItemVersionEO.EAM_ACTIVITY_TYPE_CODE IS NOT NULL
--OR ItemVersionEO.EAM_ACTIVITY_SOURCE_CODE IS NOT NULL
--OR ItemVersionEO.EAM_ACT_NOTIFICATION_FLAG IS NOT NULL
OR ItemVersionEO.ASSET_CLASS IS NOT NULL
OR ItemVersionEO.SERV_REQ_ENABLED_CODE IS NOT NULL
OR ItemVersionEO.DEFECT_TRACKING_ON_FLAG IS NOT NULL
OR ItemVersionEO.SERVICEABLE_PRODUCT_FLAG IS NOT NULL
OR ItemVersionEO.COMMS_ACTIVATION_REQD_FLAG IS NOT NULL
OR ItemVersionEO.SERVICE_DURATION_TYPE_CODE IS NOT NULL
OR ItemVersionEO.SERVICE_DURATION IS NOT NULL
OR ItemVersionEO.SERVICE_DURATION_PERIOD_CODE IS NOT NULL
OR ItemVersionEO.SERVICE_START_TYPE_CODE IS NOT NULL
OR ItemVersionEO.SERVICE_START_DELAY IS NOT NULL
OR ItemVersionEO.ALLOW_SUSPEND_FLAG IS NOT NULL
OR ItemVersionEO.ALLOW_TERMINATE_FLAG IS NOT NULL
OR ItemVersionEO.REQUIRES_FULFILLMENT_LOC_FLAG IS NOT NULL
OR ItemVersionEO.REQUIRES_ITM_ASSOCIATION_FLAG IS NOT NULL
OR ItemVersionEO.COMMS_NL_TRACKABLE_FLAG IS NOT NULL
--OR ItemVersionEO.ASSET_CREATION_CODE IS NOT NULL
--OR ItemVersionEO.IB_ITEM_INSTANCE_CLASS IS NOT NULL
OR ItemVersionEO.MATERIAL_BILLABLE_FLAG IS NOT NULL
OR ItemVersionEO.SERV_BILLING_ENABLED_FLAG IS NOT NULL
OR ItemVersionEO.RECOVERED_PART_DISP_CODE IS NOT NULL
OR ItemVersionEO.ALLOW_MAINTENANCE_ASSET_FLAG IS NOT NULL
OR ItemVersionEO.ENABLE_GENEALOGY_TRACKING_FLAG IS NOT NULL
OR ItemVersionEO.CSS_ENABLED_FLAG IS NOT NULL
)
ORDER BY ItemClassPEO.ITEM_CLASS_CODE
,ItemVersionEO.TEMPLATE_NAME
,3