/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Programs%20-%20Plans%20and%20Plan%20Types.sql $:
 * $Id: Manage Benefit Programs - Plans and Plan Types.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT benPGMEO.NAME RES_PROGRAM_NAME
,TO_CHAR(benPGMEO.EFFECTIVE_START_DATE,'DD-MM-YYYY') RES_EFFECTIVE_START_DATE
,NULL RES_PLAN_TYPE
,NULL RES_PLAN
,'Plan Type' RES_DESCRIPTION
,benPT.ORDR_NUM RES_SEQUENCE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benPT.PTIP_STAT_CD
		AND LOOKUP_TYPE = 'BEN_STAT' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_STATUS
--,benPLT.NAME RES_PLANS_AND_PLAN_TYPES
,TO_CHAR(benPT.EFFECTIVE_START_DATE,'DD-MM-YYYY') RES_PLANS_AND_PLAN_TYPES_EFFEC
,TO_CHAR(benPT.EFFECTIVE_END_DATE,'DD-MM-YYYY') RES_PLANS_AND_PLAN_TYPES_EFF_0
,benPT.IVR_IDENT RES_INTERACTIVE_VOICE_RESPONSE
,benPT.URL_REF_NAME RES_WEB_ADDRESS
,benPT.SHORT_NAME RES_SHORT_NAME
,benPT.SHORT_CODE RES_SHORT_CODE


,benPT.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benPT.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benPT.CREATED_BY RSC_CREATED_BY
,benPT.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PGM_F benPGMEO
,BEN_PTIP_F benPT
,BEN_PL_TYP_F benPLT
WHERE benPGMEO.PGM_ID = benPT.PGM_ID
AND benPT.PL_TYP_ID = benPLT.PL_TYP_ID
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPT.EFFECTIVE_START_DATE AND NVL(benPT.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLT.EFFECTIVE_START_DATE AND NVL(benPLT.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))

UNION

SELECT benPGMEO.NAME RES_PROGRAM_NAME
,TO_CHAR(benPGMEO.EFFECTIVE_START_DATE,'DD-MM-YYYY') RES_EFFECTIVE_START_DATE
,(SELECT NAME FROM BEN_PL_TYP_F WHERE PL_TYP_ID = benPL.PL_TYP_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_PLAN_TYPE
,benPL.NAME RES_PLAN
,'Plan' RES_DESCRIPTION
,benPLIP.ORDR_NUM RES_SEQUENCE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benPLIP.PLIP_STAT_CD
		AND LOOKUP_TYPE = 'BEN_STAT' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_STATUS
--,benPL.NAME RES_PLANS_AND_PLAN_TYPES
,TO_CHAR(benPLIP.EFFECTIVE_START_DATE,'DD-MM-YYYY') RES_PLANS_AND_PLAN_TYPES_EFFEC
,TO_CHAR(benPLIP.EFFECTIVE_END_DATE,'DD-MM-YYYY') RES_PLANS_AND_PLAN_TYPES_EFF_0
,benPLIP.IVR_IDENT RES_INTERACTIVE_VOICE_RESPONSE
,benPLIP.URL_REF_NAME RES_WEB_ADDRESS
,benPLIP.SHORT_CODE RES_SHORT_CODE
,benPLIP.SHORT_NAME RES_SHORT_NAME

,benPLIP.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benPLIP.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benPLIP.CREATED_BY RSC_CREATED_BY
,benPLIP.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PGM_F benPGMEO
,BEN_PLIP_F benPLIP
,BEN_PL_F benPL
WHERE benPLIP.PL_ID = benPL.PL_ID
AND benPGMEO.PGM_ID = benPLIP.PGM_ID
 AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLIP.EFFECTIVE_START_DATE AND NVL(benPLIP.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPL.EFFECTIVE_START_DATE AND NVL(benPL.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY')) 

ORDER BY RES_PROGRAM_NAME,RES_DESCRIPTION DESC,RES_PLAN_TYPE