/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Organization%20Payment%20Methods%20-%20Payment%20Method%20Rules.sql $:
 * $Id: Manage Organization Payment Methods - Payment Method Rules.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 -- RSC_PREREQUISITE_OBJECTS=PAY_ORG_PAYER_MAPPINGS_F
 
SELECT  DISTINCT payORGPAYMETEO.ORG_PAYMENT_METHOD_NAME RES_NAME
,DECODE(payORGPAYMAPEO.DEFAULT_FLAG,'Y','Yes','No') RES_DEFAULT
,DECODE(payORGPAYMAPEO.THIRD_PARTY_FLAG,'Y','Yes','No') RES_THIRD_PARTY_PAYMENT
,payORGPAYMAPEO.THIRD_PARTY_PAYEE_ID RES_THIRD_PARTY_NAME
,(SELECT NAME FROM HR_ORGANIZATION_UNITS WHERE ORGANIZATION_ID = payORGPAYMAPEO.TAX_UNIT_ID 
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_TAX_REPORTING_UNIT
,payORGPAYMAPEO.PAYMENT_CRITERIA RES_PAYMENT_CRITERIA
,(SELECT ORG_PAYMENT_METHOD_NAME FROM PAY_ORG_PAY_METHODS_VL WHERE ORG_PAYMENT_METHOD_ID = payORGPAYMAPEO.ORG_PAYMENT_METHOD_ID
	AND SYSDATE BETWEEN payORGPAYMAPEO.EFFECTIVE_START_DATE AND NVL(payORGPAYMAPEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	)RES_PAYMENT_SOURCE
,TO_DATE(payORGPAYMAPEO.EFFECTIVE_START_DATE,'YYYY-MM-DD') RES_EFFECTIVE_START_DATE
,TO_DATE(payORGPAYMAPEO.EFFECTIVE_END_DATE,'YYYY-MM-DD') RES_EFFECTIVE_END_DATE

	
  ,payORGPAYMAPEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
  ,payORGPAYMAPEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
  ,payORGPAYMAPEO.CREATED_BY  RSC_CREATED_BY
  ,payORGPAYMAPEO.CREATION_DATE  RSC_CREATION_DATE
  ,null RSC_LEDGER_ID
  ,null RSC_CHART_OF_ACCOUNTS_ID
  ,null RSC_BUSINESS_UNIT_ID
  ,null RSC_LEGAL_ENTITY_ID
  ,null RSC_ORGANIZATION_ID
  ,null RSC_BUSINESS_GROUP_ID
  ,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID


FROM PAY_ORG_PAY_METHODS_VL payORGPAYMETEO
,PAY_ORG_PAY_METHODS_VL tmppayORGPAYMETEO
,PAY_ORG_PAYER_MAPPINGS_F payORGPAYMAPEO

WHERE payORGPAYMETEO.ORG_PAYMENT_METHOD_ID = tmppayORGPAYMETEO.PARENT_ORG_PAY_METHOD_ID
AND tmppayORGPAYMETEO.ORG_PAYMENT_METHOD_ID = payORGPAYMAPEO.ORG_PAYMENT_METHOD_ID
AND payORGPAYMETEO.PARENT_ORG_PAY_METHOD_ID IS NULL
--AND SYSDATE BETWEEN payORGPAYMETEO.EFFECTIVE_START_DATE AND NVL(payORGPAYMETEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND SYSDATE BETWEEN payORGPAYMAPEO.EFFECTIVE_START_DATE AND NVL(payORGPAYMAPEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))

ORDER BY 1