/* ****************************************************************************
* $Revision:  $:
* $Author: Nasrullah Dusenmahamad $:
* $Date: 2017-03-17  $:
* $HeadURL: $:
* $Id: Manage Category Descriptive Flexfields - Context Segments $:
* ****************************************************************************
* Description:
* ************************************************************************** */

SELECT QRSLT.NAME RES_LEGAL_ENTITY
,(SELECT LEGAL_ENTITY_IDENTIFIER
	FROM XLE_ENTITY_PROFILES
	WHERE LEGAL_ENTITY_ID = QRSLT.LEGAL_ENTITY_ID
	) RES_LEGAL_ENTITY_IDENTIFIER
,QRSLT.GEOGRAPHY_NAME RES_TERRITORY
,QRSLT.REGISTERED_NAME RES_LEGAL_REPORTING_UNIT_NAME
,QRSLT.REGISTRATION_NUMBER RES_LEGAL_REPORTING_UNIT_REGIS
,HzPartySitesE0.PARTY_SITE_NUMBER RES_SITE_NUMBER
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'PARTY_SITE_USE_CODE'
	AND LOOKUP_CODE = PartySiteUseEO.SITE_USE_TYPE
	) RES_PURPOSE
,TO_CHAR(PartySiteUseEO.BEGIN_DATE,'DD-Mon-YYYY') RES_FROM_DATE
,DECODE(TO_CHAR(PartySiteUseEO.END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(PartySiteUseEO.END_DATE,'DD-Mon-YYYY')) RES_TO_DATE
	
,PartySiteUseEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,PartySiteUseEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,PartySiteUseEO.CREATED_BY  RSC_CREATED_BY
,PartySiteUseEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,QRSLT.LEGAL_ENTITY_ID RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,QRSLT.ENTERPRISE_ID RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM
	(SELECT XleEtbProfiles.PARTY_ID
	,XleEtbProfiles.LEGAL_ENTITY_ID
	,XleEtbProfiles.ENTERPRISE_ID
	,(SELECT NAME
		FROM XLE_ENTITY_PROFILES
		WHERE LEGAL_ENTITY_ID = XleEtbProfiles.LEGAL_ENTITY_ID
		) NAME
	,XleEtbProfiles.MAIN_ESTABLISHMENT_FLAG
	,XleEtbProfiles.MAIN_EFFECTIVE_FROM
	,XleEtbProfiles.MAIN_EFFECTIVE_TO
	,XleEtbProfiles.EFFECTIVE_FROM
	,XleEtbProfiles.EFFECTIVE_TO
	,XleEtbProfiles.LAST_UPDATED_BY
	,XleEtbProfiles.CREATION_DATE
	,XleEtbProfiles.LAST_UPDATE_DATE
	,XleEtbProfiles.CREATED_BY
	,XleEtbProfiles.ACTIVITY_CODE
	,XleEtbProfiles.SUB_ACTIVITY_CODE
	,XleEtbProfiles.TYPE_OF_COMPANY
	,RegistrationEO.REGISTERED_NAME
	,RegistrationEO.REGISTRATION_NUMBER
	,hz_format_pub.format_address(p_location_id => RegistrationEO.LOCATION_ID, p_line_break => ',') FORMATTED_ADDRESS
	,GeographyPEO.GEOGRAPHY_NAME
	,GeographyPEO.GEOGRAPHY_TYPE
	,GeographyPEO.GEOGRAPHY_ID
	,Jurisdictions.JURISDICTION_ID
	FROM XLE_ETB_PROFILES XleEtbProfiles
	,XLE_REGISTRATIONS RegistrationEO
	,HZ_GEOGRAPHIES GeographyPEO
	,XLE_JURISDICTIONS_VL Jurisdictions
	WHERE((XleEtbProfiles.ESTABLISHMENT_ID = RegistrationEO.SOURCE_ID(+)
	AND REGISTRATIONEO.IDENTIFYING_FLAG(+) = 'Y'))
	AND(XLEETBPROFILES.GEOGRAPHY_ID = GEOGRAPHYPEO.GEOGRAPHY_ID)
	AND XLEETBPROFILES.GEOGRAPHY_ID = Jurisdictions.GEOGRAPHY_ID
	AND RegistrationEO.JURISDICTION_ID = Jurisdictions.JURISDICTION_ID
	) QRSLT
,HZ_PARTY_SITES HzPartySitesE0
,HZ_PARTY_SITE_USES PartySiteUseEO
WHERE QRSLT.PARTY_ID = HzPartySitesE0.PARTY_ID
AND HzPartySitesE0.STATUS = 'A'
AND HzPartySitesE0.PARTY_SITE_ID = PartySiteUseEO.PARTY_SITE_ID
ORDER BY QRSLT.NAME
