/* ****************************************************************************
 * $Revision: 72749 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2019-10-23 15:22:46 +0700 (Wed, 23 Oct 2019) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Availability%20Lookups%20-%20Lookup%20Types.sql $:
 * $Id: Manage Availability Lookups - Lookup Types.sql 72749 2019-10-23 08:22:46Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
--RSC_PREREQUISITE_OBJECTS=CMP_PLAN_CURRENCIES
 
SELECT cmpPLANEO.PLAN_NAME RES_PLAN
,cmpPLANCUREO.CURRENCY RES_CURRENCY
,(SELECT NAME FROM FND_CURRENCIES_VL WHERE CURRENCY_CODE = cmpPLANCUREO.CURRENCY) RES_NAME
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpPLANCUREO.ROUNDING_CODE 
	AND LOOKUP_TYPE = 'CMP_ROUNDING' AND LANGUAGE = USERENV('LANG') 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('31-12-4712','DD-MM-YYYY')) 
	) RES_ROUNDING_RULE

,cmpPLANCUREO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,cmpPLANCUREO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,cmpPLANCUREO.CREATED_BY RSC_CREATED_BY
,cmpPLANCUREO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CMP_PLANS_VL cmpPLANEO
,CMP_PLAN_CURRENCIES cmpPLANCUREO
WHERE cmpPLANEO.PLAN_ID = cmpPLANCUREO.PLAN_ID
AND cmpPLANEO.COMP_TYPE = 'CWB'
ORDER BY cmpPLANEO.PLAN_NAME,cmpPLANCUREO.CURRENCY