/* ****************************************************************************
 * $Revision: 79070 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-07-27 14:44:19 +0700 (Wed, 27 Jul 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Checklist%20Templates%20-%20Checklist%20Templates.sql $:
 * $Id: Manage Checklist Templates - Checklist Templates.sql 79070 2022-07-27 07:44:19Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PER_CHECKLISTS_VL

SELECT chklistsE0.NAME RES_CHECKLIST_NAME
,chklistsE0.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_CHK_CHECKLIST_STATUS'
    AND LOOKUP_CODE = NVL(chklistsE0.ACTIVE_INACTIVE_FLAG,'ORA_CHK_ACTIVE')
    ) RES_STATUS
,TO_CHAR(chklistsE0.DATE_FROM,'DD-Mon-YYYY') RES_DATE_FROM
,TO_CHAR(chklistsE0.DATE_TO,'DD-Mon-YYYY') RES_DATE_TO
,(CASE
    WHEN chklistsE0.LEGISLATION_CODE IS NULL THEN
        'All Countries'
    ELSE
        (SELECT TERRITORY_SHORT_NAME
            FROM FND_TERRITORIES_VL
            WHERE TERRITORY_CODE = chklistsE0.LEGISLATION_CODE)
    END) RES_COUNTRY
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'CHECKLIST_CATEGORY'
    AND LOOKUP_CODE = chklistsE0.CHECKLIST_CATEGORY
    ) RES_CATEGORY
,(SELECT ACTION_NAME
    FROM PER_ACTIONS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND ACTION_ID = chklistsE0.EVENT_REASON_ID
    ) RES_ACTION_NAME
,(SELECT NAME
    FROM BEN_ELIGY_PRFL
    WHERE ELIGY_PRFL_ID = chklistsE0.ELIGIBILITY_PROFILE_ID
    ) RES_ELIGIBILITY_PROFILE
,chklistsE0.ARCHIVE_OFFSET RES_ARCHIVE_AFTER_MONTHS
,chklistsE0.PURGE_OFFSET RES_PURGE_AFTER_MONTHS
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_CHK_ASSIGNMENT_DT'
    AND LOOKUP_CODE = chklistsE0.ALLOCATED_ON
    ) RES_ALLOCATION_CRITERIA
,(CASE
    WHEN chklistsE0.ALLOCATED_ON = 'ORA_CHK_ACTION_DATE' THEN
        chklistsE0.OFFSET_DAYS
    END) RES_DAYS_FOR_INITIATION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_CHK_COMPLETION_DT'
    AND LOOKUP_CODE = NVL(chklistsE0.COMPLETED_ON,'ORA_CHK_MAND_TASK_COMPLETE')
    ) RES_COMPLETION_CRITERIA
,(CASE
    WHEN chklistsE0.COMPLETED_ON = 'ORA_CHK_MAND_TASK_WITH_OFFSET' THEN
        chklistsE0.COMPLETION_OFFSET_DAYS
    END) RES_DAYS_FOR_COMPLETION

--MESSAGE
,chklistsE0.MESSAGE_TITLE RES_MESSAGE_TITLE

,chklistsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,chklistsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,chklistsE0.CREATED_BY RSC_CREATED_BY
,chklistsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PER_CHECKLISTS_VL chklistsE0
ORDER BY chklistsE0.NAME