/* ****************************************************************************
 * $Revision: 78273 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-04-12 17:31:46 +0700 (Tue, 12 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Programs%20-%20Designation%20Life%20Event.sql $:
 * $Id: Manage Benefit Programs - Designation Life Event.sql 78273 2022-04-12 10:31:46Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT benPGMEO.NAME RES_PROGRAM_NAME	
,TO_CHAR(benPGMEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,benPLT.NAME RES_PLAN_TYPE
,(SELECT NAME FROM BEN_LER_F_VL WHERE LER_ID = benLERCHGDPNTEO.LER_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_LIFE_EVENT
,TO_CHAR(benLERCHGDPNTEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_COVERAGE_EFFECTIVE_START_D
,DECODE(TO_CHAR(benLERCHGDPNTEO.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benLERCHGDPNTEO.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_COVERAGE_EFFECTIVE_END_DAT
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_LER_CHG_DPNT_CVG'
    AND LOOKUP_CODE = benLERCHGDPNTEO.LER_CHG_DPNT_CVG_CD
    ) RES_CHANGE_DEPENDENT_COVERAGE_
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DPNT_CVG_STRT'
    AND LOOKUP_CODE = benLERCHGDPNTEO.CVG_EFF_STRT_CD
    ) RES_DEPENDENT_COVERAGE_START_D
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGDPNTEO.CVG_EFF_STRT_RL
    ) RES_DEPENDENT_COVERAGE_START_F
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGDPNTEO.LER_CHG_DPNT_CVG_RL
    ) RES_CHANGE_DEPENDENT_COVERAG_0
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DPNT_CVG_END'
    AND LOOKUP_CODE = benLERCHGDPNTEO.CVG_EFF_END_CD
    ) RES_PREVIOUS_DEPENDENT_COVERAG
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGDPNTEO.CVG_EFF_END_RL
    ) RES_PREVIOUS_DEPENDENT_COVER_1

/*,(SELECT NAME FROM BEN_ACTN_TYP_VL WHERE ACTN_TYP_ID = benLERPOPLACTNTYPEEO.ACTN_TYP_ID) RES_CERTIFICATION_ACTION_ITEM
,DECODE(benLERPOPLACTNTYPEEO.SSPND_FLAG,'Y','Yes','No') RES_SUSPEND_ENROLLMENT
,DECODE(benLERPOPLACTNTYPEEO.RQD_FLAG,'Y','Yes','No') RES_REQUIRED
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ACTN_TYP_DUE_DT'
    AND LOOKUP_CODE = benLERPOPLACTNTYPEEO.ACTN_TYP_DUE_DT_CD
    ) RES_DUE_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERPOPLACTNTYPEEO.ACTN_TYP_DUE_DT_RL
    ) RES_DUE_DATE_FORMULA
,null RES_ACTION_ITEM
,DECODE(TO_CHAR(benLERCHGDPNTEO.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benLERCHGDPNTEO.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
*/

,benLERCHGDPNTEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benLERCHGDPNTEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benLERCHGDPNTEO.CREATED_BY RSC_CREATED_BY
,benLERCHGDPNTEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PGM_F benPGMEO
,BEN_PTIP_F benPT
,BEN_PL_TYP_F benPLT 
,BEN_LER_CHG_DPNT_CVG_F benLERCHGDPNTEO
,BEN_LER_POPL_ACTN_TYP_F benLERPOPLACTNTYPEEO
WHERE benPGMEO.PGM_ID = benPT.PGM_ID
AND benPT.PL_TYP_ID = benPLT.PL_TYP_ID
AND benPT.PTIP_ID = benLERCHGDPNTEO.PTIP_ID
AND benLERCHGDPNTEO.PTIP_ID = benLERPOPLACTNTYPEEO.PTIP_ID
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPT.EFFECTIVE_START_DATE AND NVL(benPT.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLT.EFFECTIVE_START_DATE AND NVL(benPLT.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benLERCHGDPNTEO.EFFECTIVE_START_DATE AND NVL(benLERCHGDPNTEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benLERPOPLACTNTYPEEO.EFFECTIVE_START_DATE AND NVL(benLERPOPLACTNTYPEEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))

ORDER BY 1,2,3