/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=PAY_ELEMENT_LINKS_F

SELECT elementsE0.ELEMENT_NAME RES_ELEMENT_NAME
,legislativeDataGrpsE0.NAME RES_LEGISLATIVE_DATA_GROUP
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
	WHERE BASE_CLASSIFICATION_ID = elementsE0.CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PRIMARY_CLASSIFICATION
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
    WHERE BASE_CLASSIFICATION_ID = elementsE0.SECONDARY_CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
    ) RES_SECONDARY_CLASSIFICATION
,TO_CHAR(payinputvalE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,payElementlinkE0.ELEMENT_LINK_NAME RES_ELEMENT_ELIGIBILITY_NAME
,payinputvalE0.NAME RES_NAME
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = payinputvalE0.UOM 
	AND LOOKUP_TYPE = 'PAY_UNITS' 
	AND LANGUAGE = USERENV('LANG')
	) RES_UNIT_OF_MEASURE
,NVL((SELECT DISTINCT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = paylinkinputvalE0.DEFAULT_VALUE
	AND LOOKUP_TYPE = payinputvalE0.LOOKUP_TYPE 
	AND LANGUAGE = USERENV('LANG'))
	,paylinkinputvalE0.DEFAULT_VALUE
	) RES_DEFAULT
,paylinkinputvalE0.MIN_VALUE RES_MINIMUM
,paylinkinputvalE0.MAX_VALUE RES_MAXIMUM
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = paylinkinputvalE0.WARNING_OR_ERROR
	AND LOOKUP_TYPE = 'PAY_WARNING_ERROR' 
	AND LANGUAGE = USERENV('LANG')
	) RES_WARNING_OR_ERROR
,DECODE(TO_CHAR(payinputvalE0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(payinputvalE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE

,payinputvalE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payinputvalE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payinputvalE0.CREATED_BY RSC_CREATED_BY
,payinputvalE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legislativeDataGrpsE0.LEGISLATION_CODE RSC_COUNTRY_ID


FROM PAY_ELEMENT_TYPES_VL elementsE0
,PAY_INPUT_VALUES_VL payinputvalE0
,PAY_LINK_INPUT_VALUES_F paylinkinputvalE0
,PAY_ELEMENT_LINKS_F payElementlinkE0
,(SELECT NAME
    ,LEGISLATIVE_DATA_GROUP_ID
	,LEGISLATION_CODE
    FROM PER_LEGISLATIVE_DATA_GROUPS_VL
    ) legislativeDataGrpsE0
	
WHERE elementsE0.LEGISLATIVE_DATA_GROUP_ID = legislativeDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID
AND elementsE0.ELEMENT_TYPE_ID = payElementlinkE0.ELEMENT_TYPE_ID 
AND elementsE0.ELEMENT_TYPE_ID = payinputvalE0.ELEMENT_TYPE_ID
AND payinputvalE0.INPUT_VALUE_ID = paylinkinputvalE0.INPUT_VALUE_ID
AND NVL(payElementlinkE0.COSTING_LINK_FLAG,'N') = 'N'
--AND SYSDATE BETWEEN freqruleE0.START_DATE AND NVL(freqruleE0.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND SYSDATE BETWEEN paylinkinputvalE0.EFFECTIVE_START_DATE AND NVL(paylinkinputvalE0.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
ORDER BY elementsE0.ELEMENT_NAME


