/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT 
(SELECT ITEM_CLASS_NAME
	FROM EGP_ITEM_CLASSES_VL
	WHERE ITEM_CLASS_ID = ItemClassPEO.PARENT_ITEM_CLASS_ID
	) RES_PARENT_ITEM_CLASS 
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_ITEM_NUM_GEN_METHOD'
	AND LOOKUP_CODE = ItemClassPEO.ITEM_NUM_GEN_METHOD
	) RES_ITEM_NUMBER_GENERATION_MET
,EntityAutoGenMetadataEO.AUTO_GEN_RULE_SET_ID RES_ITEM_NUMBER_GENERATION_M_0
,EntityAutoGenMetadataEO.STARTING_NUMBER RES_ITEM_NUMBER_GENERATION_M_1
,EntityAutoGenMetadataEO.PREFIX RES_ITEM_NUMBER_GENERATION_M_2
,EntityAutoGenMetadataEO.INCREMENT_BY RES_ITEM_NUMBER_GENERATION_M_3
,EntityAutoGenMetadataEO.SUFFIX RES_ITEM_NUMBER_GENERATION_M_4
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_EGP_CTO_NUM_GEN_METHOD'
	AND LOOKUP_CODE = ItemClassPEO.CFG_ITEM_NUM_GEN_METHOD
	) RES_CONFIGURED_ITEM_NUMBER_GEN
,(CASE
	WHEN ItemClassPEO.CFG_ITEM_NUM_GEN_METHOD <> 'NONE' THEN
		EntityAutoGenMetadataE1.STARTING_NUMBER
	END) RES_CONFIGURED_ITEM_NUMBER_G_5
,(CASE
	WHEN ItemClassPEO.CFG_ITEM_NUM_GEN_METHOD <> 'NONE' THEN
		(SELECT MEANING
			FROM FND_LOOKUPS
			WHERE LOOKUP_TYPE = 'ORA_EGP_CFG_ITEM_NUM_GEN_AFFIX'
			AND LOOKUP_CODE = EntityAutoGenMetadataE1.PREFIX_TYPE)
	END) RES_CONFIGURED_ITEM_NUMBER_G_6
,(CASE
	WHEN ItemClassPEO.CFG_ITEM_NUM_GEN_METHOD <> 'NONE' THEN
		EntityAutoGenMetadataE1.PREFIX
	END) RES_CONFIGURED_ITEM_NUMBER_G_7
,(CASE
	WHEN ItemClassPEO.CFG_ITEM_NUM_GEN_METHOD <> 'NONE' THEN
		EntityAutoGenMetadataE1.INCREMENT_BY
	END) RES_CONFIGURED_ITEM_NUMBER_G_8
,(CASE
	WHEN ItemClassPEO.CFG_ITEM_NUM_GEN_METHOD <> 'NONE' THEN
		(SELECT MEANING
			FROM FND_LOOKUPS
			WHERE LOOKUP_TYPE = 'ORA_EGP_CFG_ITEM_NUM_GEN_AFFIX'
			AND LOOKUP_CODE = EntityAutoGenMetadataE1.SUFFIX_TYPE)
	END) RES_CONFIGURED_ITEM_NUMBER_G_9
,(CASE
	WHEN ItemClassPEO.CFG_ITEM_NUM_GEN_METHOD <> 'NONE' THEN
		EntityAutoGenMetadataE1.SUFFIX
	END) RES_CONFIGURED_ITEM_NUMBER__10
,(CASE
	WHEN ItemClassPEO.CFG_ITEM_NUM_GEN_METHOD <> 'NONE' THEN
		(SELECT MEANING
			FROM FND_LOOKUPS
			WHERE LOOKUP_TYPE = 'ORA_EGP_CFG_ITEM_NUM_GEN_DEL'
			AND LOOKUP_CODE = EntityAutoGenMetadataE1.DELIMITER)
	END) RES_CONFIGURED_ITEM_NUMBER__11
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_ITEM_NUM_GEN_METHOD'
	AND LOOKUP_CODE = ItemClassPEO.ITEM_DESC_GEN_METHOD
	) RES_ITEM_DESCRIPTION_GENERATIO
,EntityAutoGenMetadataE1.AUTO_GEN_RULE_SET_ID RES_ITEM_DESCRIPTION_GENERA_12
,DECODE(ItemClassPEO.NIR_REQD,'Y','Yes','No') RES_ENABLE_NEW_ITEM_REQUEST
,(SELECT TYPE_NAME
	FROM EGO_CHANGE_TYPES_VL
	WHERE CHANGE_TYPE_ID = CHANGE_ORDER_TYPE_ID
	) RES_DEFAULT_CHANGE_ORDER_TYPE
,NVL(EntityAutoGenMetadataEO.LAST_UPDATED_BY,EntityAutoGenMetadataE1.LAST_UPDATED_BY) RSC_LAST_UPDATED_BY
,NVL(EntityAutoGenMetadataEO.LAST_UPDATE_DATE,EntityAutoGenMetadataE1.LAST_UPDATE_DATE) RSC_LAST_UPDATE_DATE
,NVL(EntityAutoGenMetadataEO.CREATED_BY,EntityAutoGenMetadataE1.CREATED_BY) RSC_CREATED_BY
,NVL(EntityAutoGenMetadataEO.CREATION_DATE,EntityAutoGenMetadataE1.CREATION_DATE) RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,(SELECT *
	FROM EGO_ENTITY_AUTO_GEN_METADATA
	WHERE OBJECT_NAME = 'EGP_IC'
	) EntityAutoGenMetadataEO
,(SELECT *
	FROM EGO_ENTITY_AUTO_GEN_METADATA
	WHERE OBJECT_NAME = 'EGP_CI'
	) EntityAutoGenMetadataE1
WHERE ItemClassPEO.ITEM_CLASS_ID = EntityAutoGenMetadataEO.OBJECT_ID1(+)
AND ItemClassPEO.ITEM_CLASS_ID = EntityAutoGenMetadataE1.OBJECT_ID1(+)
CONNECT BY ItemClassPEO.PARENT_ITEM_CLASS_ID = ItemClassPEO.ITEM_CLASS_ID
ORDER SIBLINGS BY RES_PARENT_ITEM_CLASS,RES_ITEM_CLASS