/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Ledger%20Sets%20-%20Ledger%20Set%20Assignments%20-%20DFF.sql $:
 * $Id: Manage Ledger Sets - Ledger Set Assignments - DFF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=101##RES##GL_LEDGER_SET_NORM_ASSIGN
-- DFF_ATTRIBUTES=ATTRIBUTE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

select LedgerSetEO.name AS RES_NAME
 ,(SELECT name
		FROM gl_ledgers
		WHERE ledger_id = GlLedgerSetNormAssign.LEDGER_ID
		) AS RES_LEDGER_OR_LEDGER_SET
,GLLEDGERSETNORMASSIGN.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,GLLEDGERSETNORMASSIGN.ATTRIBUTE1
,GLLEDGERSETNORMASSIGN.ATTRIBUTE2
,GLLEDGERSETNORMASSIGN.ATTRIBUTE3
,GLLEDGERSETNORMASSIGN.ATTRIBUTE4
,GLLEDGERSETNORMASSIGN.ATTRIBUTE5
,GLLEDGERSETNORMASSIGN.ATTRIBUTE6
,GLLEDGERSETNORMASSIGN.ATTRIBUTE7
,GLLEDGERSETNORMASSIGN.ATTRIBUTE8
,GLLEDGERSETNORMASSIGN.ATTRIBUTE9
,GLLEDGERSETNORMASSIGN.ATTRIBUTE10
,GLLEDGERSETNORMASSIGN.ATTRIBUTE11
,GLLEDGERSETNORMASSIGN.ATTRIBUTE12
,GLLEDGERSETNORMASSIGN.ATTRIBUTE13
,GLLEDGERSETNORMASSIGN.ATTRIBUTE14
,GLLEDGERSETNORMASSIGN.ATTRIBUTE15
,GLLEDGERSETNORMASSIGN.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,GLLEDGERSETNORMASSIGN.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,GLLEDGERSETNORMASSIGN.CREATED_BY  RSC_CREATED_BY
,GLLEDGERSETNORMASSIGN.CREATION_DATE  RSC_CREATION_DATE
,PGL.PRIMARY_LEDGER_ID RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM GL_LEDGERS LedgerSetEO 
, GL_LEDGER_SET_NORM_ASSIGN GLLEDGERSETNORMASSIGN
,(select RSHIP.TARGET_LEDGER_ID, RSHIP.PRIMARY_LEDGER_ID from GL_LEDGER_RELATIONSHIPS RSHIP
	WHERE (RSHIP.RELATIONSHIP_TYPE_CODE <> 'NONE'
	AND RSHIP.TARGET_LEDGER_CATEGORY_CODE = 'SECONDARY')
	OR (RSHIP.RELATIONSHIP_TYPE_CODE = 'NONE'
	AND RSHIP.TARGET_LEDGER_CATEGORY_CODE = 'PRIMARY')) PGL
where (GLLEDGERSETNORMASSIGN.ATTRIBUTE_CATEGORY IS NOT NULL OR
GLLEDGERSETNORMASSIGN.ATTRIBUTE1 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE2 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE3 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE4 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE5 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE6 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE7 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE8 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE9 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE10 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE11 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE12 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE13 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE14 IS NOT NULL OR 
GLLEDGERSETNORMASSIGN.ATTRIBUTE15 IS NOT NULL
)
AND LEDGERSETEO.LEDGER_ID = GLLEDGERSETNORMASSIGN.LEDGER_SET_ID
AND(GLLEDGERSETNORMASSIGN.STATUS_CODE IS NULL OR GLLEDGERSETNORMASSIGN.STATUS_CODE  <> 'D')
AND GLLEDGERSETNORMASSIGN.LEDGER_ID = PGL.TARGET_LEDGER_ID
ORDER BY RES_NAME