/* ****************************************************************************
* $Revision: 79762 $:
* $Author: tanawat.wongjan $:
* $Date: 2022-12-05 17:31:44 +0700 (Mon, 05 Dec 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Project%20Templates%20-%20Team%20Members.sql $:
* $Id: Manage Project Templates - Team Members.sql 79762 2022-12-05 10:31:44Z tanawat.wongjan $:
* ****************************************************************************
* Description:
* ************************************************************************** */

--RSC_PREREQUISITE_OBJECTS=PJF_PROJECT_PARTIES

SELECT projTemplatesE0.NAME RES_TEMPLATE_NAME
,projTemplatesE0.SEGMENT1 RES_TEMPLATE_NUMBER
,(SELECT MEANING FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = teamMembersE0.PROJECT_PARTY_TYPE 
	AND LOOKUP_TYPE = 'PJF_TMDIR_MEMBER_TYPE'
	AND LANGUAGE = USERENV('LANG'))RES_TYPE
,(SELECT NAME
    FROM HR_ORGANIZATION_UNITS_F_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND ORGANIZATION_ID = teamMembersE0.PROJ_RESOURCE_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    ) RES_ORGANIZATION
,personE0.FULL_NAME RES_PERSON
,personE0.FULL_NAME RES_RESOURCE
,(SELECT emailE0.EMAIL_ADDRESS 
	FROM PER_EMAIL_ADDRESSES emailE0
	,PER_ALL_PEOPLE_F workersE0
	WHERE emailE0.EMAIL_ADDRESS_ID = workersE0.PRIMARY_EMAIL_ID 
	AND workersE0.PERSON_ID = personE0.PERSON_ID
	AND SYSDATE BETWEEN emailE0.DATE_FROM AND NVL(emailE0.DATE_TO,TO_DATE('31-12-4712','DD-MM-YYYY')) 
	AND SYSDATE BETWEEN workersE0.EFFECTIVE_START_DATE AND NVL(workersE0.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY')) 
	AND emailE0.MASTERED_IN_LDAP_FLAG = 'Y'
	) RES_EMAIL
,(SELECT PROJECT_ROLE_NAME
	FROM PJF_PROJ_ROLE_TYPES_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND PROJECT_ROLE_ID = teamMembersE0.PROJECT_ROLE_ID
	) RES_PROJECT_ROLE
,TO_CHAR(teamMembersE0.START_DATE_ACTIVE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(teamMembersE0.END_DATE_ACTIVE,'DD-Mon-YYYY') RES_END_DATE
,DECODE(teamMembersE0.PJS_TRACK_TIME,'Y','Yes','No') RES_TRACK_TIME
,(SELECT LABOR_EFFORT FROM PJT_PROJECT_RESOURCE
	WHERE PROJ_RESOURCE_ID = teamMembersE0.PROJ_RESOURCE_ID
		  AND RESOURCE_ID = teamMembersE0.RESOURCE_ID
		  AND PROJECT_ID = teamMembersE0.PROJECT_ID ) RES_EFFORT
,(SELECT ALLOCATION FROM PJT_PROJECT_RESOURCE
	WHERE PROJ_RESOURCE_ID = teamMembersE0.PROJ_RESOURCE_ID
		  AND RESOURCE_ID = teamMembersE0.RESOURCE_ID
		  AND PROJECT_ID = teamMembersE0.PROJECT_ID ) RES_ALLOCATION

,teamMembersE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,teamMembersE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,teamMembersE0.CREATED_BY  RSC_CREATED_BY
,teamMembersE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,projTemplatesE0.ORG_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJF_PROJECTS_ALL_VL projTemplatesE0
,FUN_ALL_BUSINESS_UNITS_V buE0
,PJF_PROJECT_PARTIES teamMembersE0
,(SELECT *
	FROM PER_PERSON_NAMES_F
	WHERE NAME_TYPE = 'GLOBAL'
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) personE0
WHERE projTemplatesE0.TEMPLATE_FLAG = 'Y'
AND projTemplatesE0.ORG_ID = buE0.BU_ID
AND projTemplatesE0.PROJECT_ID = teamMembersE0.PROJECT_ID
AND teamMembersE0.PROJECT_PARTY_TYPE = 'IN'
AND teamMembersE0.RESOURCE_SOURCE_ID = personE0.PERSON_ID
ORDER BY projTemplatesE0.NAME,2