/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-07-04 $:
 * $HeadURL:$:
 * $Id: Manage Bank Branch Addresses - Botswana.sql $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT ruleSetsE0.RULE_SET_DISPLAY_NAME RES_DISPLAY_NAME
,ruleSetsE0.RULE_SET_NAME RES_INTERNAL_NAME
,ruleSetsE0.DESCRIPTION RES_DESCRIPTION
,DECODE(ruleSetsE0.COMPOSITE,'Y','Yes','No') RES_COMPOSITE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGO_RL_RULE_SET_TYPES'
	AND LOOKUP_CODE = ruleSetsE0.RULE_SET_TYPE
	) RES_TYPE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGO_RL_RULE_SET_ASSOCIATIONS'
	AND LOOKUP_CODE = ruleSetsE0.ASSOCIATION_TYPE
	) RES_ASSOCIATION_TYPE
,(CASE
	WHEN ruleSetsE0.ASSOCIATION_TYPE = 'AG' THEN --Attribute Group
		ruleSetsE0.ASSOCIATION_PK2
	WHEN ruleSetsE0.ASSOCIATION_TYPE = 'CT' THEN --Change Order Type
		(SELECT TYPE_NAME
			FROM EGO_CHANGE_TYPES_VL
			WHERE TO_CHAR(CHANGE_TYPE_ID) = ruleSetsE0.ASSOCIATION_PK1)
	WHEN ruleSetsE0.ASSOCIATION_TYPE = 'ICC' THEN --Item Class
		(SELECT ITEM_CLASS_NAME
			FROM EGP_ITEM_CLASSES_VL
			WHERE TO_CHAR(ITEM_CLASS_ID) = ruleSetsE0.ASSOCIATION_PK1)
	WHEN ruleSetsE0.ASSOCIATION_TYPE = 'NIR' THEN --New Item Request
		(SELECT TYPE_NAME
			FROM EGO_CHANGE_TYPES_VL
			WHERE  TO_CHAR(CHANGE_TYPE_ID) = ruleSetsE0.ASSOCIATION_PK1)
	END) RES_ASSOCIATION_NAME
,DECODE(ruleSetsE0.IS_DRAFT,'Y','Yes','No') RES_DRAFT
,ruleSetsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ruleSetsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ruleSetsE0.CREATED_BY RSC_CREATED_BY
,ruleSetsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGO_RL_RULE_SETS_VL ruleSetsE0
ORDER BY ruleSetsE0.RULE_SET_DISPLAY_NAME