/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Derived%20Factors%20-%20Full-Time%20Equivalent.sql $:
 * $Id: Manage Derived Factors - Full-Time Equivalent.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT benPCTFLTMEO.NAME RES_NAME
,(CASE WHEN USE_PRMRY_ASNT_ONLY_FLAG = 'N' AND USE_SUM_OF_ALL_ASNTS_FLAG = 'Y' THEN
	'Sum of All Assignments'
	WHEN USE_PRMRY_ASNT_ONLY_FLAG = 'Y' AND USE_SUM_OF_ALL_ASNTS_FLAG = 'N' THEN
	'Primary Assignment'
	ELSE
	NULL	
END )RES_ASSIGNMENT_TO_USE
,benPCTFLTMEO.MN_PCT_VAL RES_MINIMUM_PERCENTAGE
,benPCTFLTMEO.MX_PCT_VAL RES_MAXIMUM_PERCENTAGE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benPCTFLTMEO.RNDG_CD
	AND LOOKUP_TYPE = 'BEN_RNDG' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_ROUNDING_RULE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benPCTFLTMEO.RNDG_RL 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_ROUNDING_FORMULA


,benPCTFLTMEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benPCTFLTMEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benPCTFLTMEO.CREATED_BY RSC_CREATED_BY
,benPCTFLTMEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,benPCTFLTMEO.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM BEN_PCT_FL_TM_FCTR benPCTFLTMEO
ORDER BY benPCTFLTMEO.NAME




























