/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Derived%20Factors%20-%20Age.sql $:
 * $Id: Manage Derived Factors - Age.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT benAGEFACEO.NAME RES_NAME
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benAGEFACEO.AGE_UOM 
	AND LOOKUP_TYPE = 'BEN_TM_UOM' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_UNITS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benAGEFACEO.AGE_TO_USE_CD 
	AND LOOKUP_TYPE = 'BEN_AGE_TO_USE_CD' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_AGE_TO_USE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benAGEFACEO.AGE_CALC_RL 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_CALCULATION_FORMULA
,benAGEFACEO.MN_AGE_NUM RES_GREATER_THAN_OR_EQUAL_TO_A
,benAGEFACEO.MX_AGE_NUM RES_LESS_THAN_AGE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benAGEFACEO.AGE_DET_CD
	AND LOOKUP_TYPE = 'BEN_AGE_DET' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_DETERMINATION_RULE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benAGEFACEO.AGE_DET_RL 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_DETERMINATION_FORMULA
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benAGEFACEO.RNDG_CD
	AND LOOKUP_TYPE = 'BEN_RNDG' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_ROUNDING_RULE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benAGEFACEO.RNDG_RL 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_ROUNDING_FORMULA

,benAGEFACEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benAGEFACEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benAGEFACEO.CREATED_BY RSC_CREATED_BY
,benAGEFACEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,benAGEFACEO.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM BEN_AGE_FCTR benAGEFACEO
ORDER BY benAGEFACEO.NAME