/* ****************************************************************************
 * $Revision$:
 * $Author$:
 * $Date$:
 * $HeadURL$:
 * $Id$:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT benPGMEO.NAME RES_PROGRAM_NAME
,TO_CHAR(benPT.EFFECTIVE_START_DATE,'DD-MM-YYYY') RES_EFFECTIVE_START_DATE
,benPLT.NAME RES_PLAN_TYPE
,TO_CHAR(benPT.EFFECTIVE_START_DATE,'DD-MM-YYYY') RES_COVERAGE_EFFECTIVE_START_D
,DECODE(TO_CHAR(benPT.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benPT.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_COVERAGE_EFFECTIVE_END_DAT
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DPNT_CVG_STRT'
    AND LOOKUP_CODE = benPT.DPNT_CVG_STRT_DT_CD
    ) RES_DEPENDENT_COVERAGE_START_D
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPT.DPNT_CVG_STRT_DT_RL
    ) RES_DEPENDENT_COVERAGE_START_F
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_CVG_END'
    AND LOOKUP_CODE = benPT.DPNT_CVG_END_DT_CD
    ) RES_PREVIOUS_DEPENDENT_COVERAG
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPT.DPNT_CVG_END_DT_RL
    ) RES_PREVIOUS_DEPENDENT_COVER_0
	
/*,TO_CHAR(benPT.EFFECTIVE_END_DATE,'DD-MM-YYYY') RES_EFFECTIVE_END_DATE
,(SELECT NAME FROM BEN_ACTN_TYP_VL WHERE ACTN_TYP_ID = benPOPLACTNEO.ACTN_TYP_ID) RES_ACTION_ITEM
,DECODE(benPOPLACTNEO.SSPND_FLAG,'Y','Yes','No') RES_SUSPEND_ENROLLMENT
,DECODE(benPOPLACTNEO.RQD_FLAG,'Y','Yes','No') RES_REQUIRED
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ACTN_TYP_DUE_DT'
    AND LOOKUP_CODE = benPOPLACTNEO.ACTN_TYP_DUE_DT_CD
    ) RES_DUE_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPOPLACTNEO.ACTN_TYP_DUE_DT_RL
    ) RES_DUE_DATE_FORMULA*/

,benPT.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benPT.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benPT.CREATED_BY RSC_CREATED_BY
,benPT.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PGM_F benPGMEO
,BEN_PTIP_F benPT
,BEN_PL_TYP_F benPLT 
,BEN_POPL_ACTN_TYP_F benPOPLACTNEO
WHERE benPGMEO.PGM_ID = benPT.PGM_ID
AND benPT.PL_TYP_ID = benPLT.PL_TYP_ID
AND benPT.PTIP_ID = benPOPLACTNEO.PTIP_ID
AND benPOPLACTNEO.ACTN_TYP_LVL_CD NOT IN 'DPNT'
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPT.EFFECTIVE_START_DATE AND NVL(benPT.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLT.EFFECTIVE_START_DATE AND NVL(benPLT.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPOPLACTNEO.EFFECTIVE_START_DATE AND NVL(benPOPLACTNEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))


ORDER BY 1,2,3