/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Segment%20Value%20Security%20Rules%20-%20Database%20Resource%20Condition.sql $:
 * $Id: Manage Segment Value Security Rules - Database Resource Condition.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
select  QRSLT.VALUE_SET_CODE   RES_VALUE_SET_CODE
,QRSLT.INSTANCE_SET_NAME   RES_NAME
,QRSLT.DISPLAY_NAME RES_DISPLAY_NAME
,QRSLT.DESCRIPTION_1  RES_DESCRIPTION
,DECODE(QRSLT.PREDICATE,'FILTER','Filter','SQL predicate') RES_CONDITION_TYPE
,QRSLT.PREDICATE RES_SQL_PREDICATE
,QRSLT.Match RES_MATCH
,QRSLT.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY  RSC_CREATED_BY
,QRSLT.CREATION_DATE  RSC_CREATION_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID

from 
(SELECT ValueSetEO.VALUE_SET_ID
,ValueSetEO.VALUE_SET_CODE
,ValueSetEO.PROTECTED_FLAG
,ValueSetEO.MODULE_ID
,ValueSetEO.VALIDATION_TYPE
,ValueSetEO.VALUE_DATA_TYPE
,VALUESETEO.DESCRIPTION
,VALUESETEO.SECURITY_ENABLED_FLAG
,VALUESETEO.DATA_SECURITY_OBJECT_NAME
,ApplTaxonomyPEO.MODULE_ID AS MODULE_ID1
,ApplTaxonomyPEO.MODULE_TYPE
,ApplTaxonomyPEO.MODULE_KEY
,ApplTaxonomyPEO.USER_MODULE_NAME
,ValidationTypeLookupPEO.LOOKUP_TYPE
,ValidationTypeLookupPEO.LOOKUP_CODE
,ValidationTypeLookupPEO.MEANING
,ValueDataTypeLookupPEO.LOOKUP_TYPE
,ValueDataTypeLookupPEO.LOOKUP_CODE
,ValueDataTypeLookupPEO.MEANING
,FndObjectInstanceSetsEO.INSTANCE_SET_NAME
,FndObjectInstanceSetsEO.DISPLAY_NAME
,FNDOBJECTINSTANCESETSEO.DESCRIPTION DESCRIPTION_1
,(case FNDOBJECTINSTANCESETSEO.PREDICATE 
	when 'FILTER' then
	  (select distinct 
	  (select LOOKUPPEO.MEANING from FND_LOOKUPS LOOKUPPEO where LOOKUPPEO.LOOKUP_TYPE = 'FND_DS_FILTER_MATCH_TYPE' and LOOKUPPEO.LOOKUP_CODE    =
	  EXTRACTVALUE(value(X), '/filterCriteriaItem/conjunction') )
	   from FND_OBJECT_INSTANCE_SETS_VL FNDOBJECTINSTANCESETSEO_
		,table(XMLSEQUENCE(extract(FNDOBJECTINSTANCESETSEO_.filter,'/FndFilter/GenericFilter/filterCriteriaRow/filterCriteriaItem'))) X
		where FNDOBJECTINSTANCESETSEO_.instance_set_id = FNDOBJECTINSTANCESETSEO.instance_set_id
	  )
	else
	null
	end) as MATCH

,FndObjectInstanceSetsEO.predicate 
,FNDOBJECTINSTANCESETSEO.LAST_UPDATE_DATE
,FNDOBJECTINSTANCESETSEO.LAST_UPDATED_BY
,FNDOBJECTINSTANCESETSEO.CREATION_DATE
,FNDOBJECTINSTANCESETSEO.CREATED_BY
FROM FND_VS_VALUE_SETS ValueSetEO
,FND_APPL_TAXONOMY_VL ApplTaxonomyPEO
,FND_LOOKUPS ValidationTypeLookupPEO
,FND_LOOKUPS ValueDataTypeLookupPEO
,FND_OBJECTS_VL 
,FND_OBJECT_INSTANCE_SETS_VL FNDOBJECTINSTANCESETSEO
WHERE ValueSetEO.MODULE_ID     = ApplTaxonomyPEO.MODULE_ID
AND ValueSetEO.VALIDATION_TYPE = ValidationTypeLookupPEO.LOOKUP_CODE
and VALUESETEO.VALUE_DATA_TYPE = VALUEDATATYPELOOKUPPEO.LOOKUP_CODE
and  FND_OBJECTS_VL.DATABASE_OBJECT_NAME = 'FND_VS_VALUES_VL'
and  VALUESETEO.DATA_SECURITY_OBJECT_NAME = FND_OBJECTS_VL.obj_name 
and FndObjectInstanceSetsEO.OBJECT_ID = FND_OBJECTS_VL.OBJECT_ID
AND(ValueSetEO.module_id      IN
	(SELECT rf.child_module_id
	FROM fnd_appl_taxonomy_rf rf
	INNER JOIN fnd_appl_taxonomy t
	on RF.ANCESTOR_MODULE_ID = T.MODULE_ID
	where T.MODULE_TYPE      = 'APPLICATION'
	AND t.module_key         = 'GL'
	))
and (((VALUESETEO.VALUE_SET_CODE not like('%$FLEX$%'))
and(VALIDATIONTYPELOOKUPPEO.LOOKUP_TYPE = 'FND_VS_VALIDATION_TYPES')
and(VALUEDATATYPELOOKUPPEO.LOOKUP_TYPE  = 'FND_VS_VALUE_DATA_TYPES')))
)  QRSLT
ORDER BY QRSLT.VALUE_SET_CODE