/* ****************************************************************************
 * $Revision$:
 * $Author$:
 * $Date$:
 * $HeadURL$:
 * $Id$:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
--RSC_PREREQUISITE_OBJECTS=XCC_BCE_LEDGERS
--RSC_PREREQUISITE_OBJECTS=XCC_BCE_BUSINESS_UNITS
-- FIELD_TO_APPLY_FUNCTION=RES_LEDGER_RESERVE_FOR_ENCUMBR/GET_CODE_COMBINATION

SELECT (SELECT NAME FROM GL_LEDGERS WHERE LEDGER_ID = xccBCELEDE0.LEDGER_ID) RES_LEDGER_NAME
,DECODE(xccBCELEDE0.BC_ENABLED_FLAG,'Y','Yes','No') RES_LEDGER_ENABLE_BUDGETARY_CO
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccBCELEDE0.CONTROL_BUDGET_TYPE_CODE
			AND LOOKUP_TYPE = 'XCC_CONTROL_BUDGET_TYPE_CODE' AND LANGUAGE = USERENV('LANG')) RES_LEDGER_CONTROL_BUDGET_FILT
,DECODE(xccBCELEDE0.BUDGET_DATE_RANGE_FLAG,'Y','Yes','No') RES_LEDGER_TRANSACTION_BUDGET_
,DECODE(xccBCELEDE0.COA_CONTROL_BUDGET_FLAG,'Y','Yes','No') RES_LEDGER_TRANSACTIONS_WITHOU
,DECODE(xccBCELEDE0.EA_ENABLED_FLAG,'Y','Yes','No') RES_LEDGER_ENABLE_ENCUMBRANCE_
,(SELECT RES_ENCUMB_CODE_COMBINATION_ID FROM GL_LEDGERS WHERE LEDGER_ID = xccBCELEDE0.LEDGER_ID) RES_LEDGER_RESERVE_FOR_ENCUMBR
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = xccBCEBUE0.BUSINESS_UNIT_ID 
	) RES_BUSINESS_UNIT_NAME
,DECODE(xccBCEBUE0.BC_ENABLED_FLAG,'Y','Yes','No') RES_BUSINESS_UNIT_BUDGETARY_CO
,DECODE(xccBCEBUE0.EA_ENABLED_FLAG,'Y','Yes','No') RES_BUSINESS_UNIT_ENCUMBRANCE_
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccBCEBUE0.BC_LIQUIDATION_DATE_CODE
			AND LOOKUP_TYPE = 'XCC_BC_LIQUIDATIONDT_RULE' AND LANGUAGE = USERENV('LANG')) RES_BUSINESS_UNIT_DEFAULT_DATE
,(SELECT DECODE(BC_ENABLED_FLAG,'Y','Yes','No') FROM XCC_BCE_BUSINESS_FUNCTIONS WHERE LEDGER_ID = xccBCEBUE0.LEDGER_ID
	AND BUSINESS_UNIT_ID = xccBCEBUE0.BUSINESS_UNIT_ID AND BUSINESS_FUNCTION_CODE = 'PROJECT_ACCOUNTING_BF') RES_BUSINESS_UNIT_ENABLE_BUDGE

,(CASE WHEN xccBCEBUE0.LAST_UPDATED_BY IS NULL
	THEN xccBCELEDE0.LAST_UPDATED_BY
	ELSE xccBCEBUE0.LAST_UPDATED_BY END) RSC_LAST_UPDATED_BY
,(CASE WHEN xccBCEBUE0.LAST_UPDATE_DATE IS NULL
	THEN xccBCELEDE0.LAST_UPDATE_DATE
	ELSE xccBCEBUE0.LAST_UPDATE_DATE END) RSC_LAST_UPDATE_DATE
,(CASE WHEN xccBCEBUE0.CREATED_BY IS NULL
	THEN xccBCELEDE0.CREATED_BY
	ELSE xccBCEBUE0.CREATED_BY END) RSC_CREATED_BY
,(CASE WHEN xccBCEBUE0.CREATION_DATE IS NULL
	THEN xccBCELEDE0.CREATION_DATE
	ELSE xccBCEBUE0.CREATION_DATE END) RSC_CREATION_DATE
,xccBCELEDE0.LEDGER_ID RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,xccBCEBUE0.BUSINESS_UNIT_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
   
FROM XCC_BCE_LEDGERS xccBCELEDE0
,XCC_BCE_BUSINESS_UNITS xccBCEBUE0
WHERE xccBCELEDE0.LEDGER_ID = xccBCEBUE0.LEDGER_ID
ORDER BY 1