/* ****************************************************************************
 * $Revision: 55346 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-05-23 14:11:43 +0700 (Mon, 23 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Chart%20of%20Accounts%20Value%20Set%20Values%20-%20Manage%20Values.sql $:
 * $Id: Manage Chart of Accounts Value Set Values - Manage Values.sql 55346 2016-05-23 07:11:43Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=ANC_ABSENCE_PLANS_F

SELECT (SELECT NAME 
	FROM ANC_ABSENCE_PLANS_F_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND ABSENCE_PLAN_ID = absencePlansE0.ABSENCE_PLAN_ID
	AND EFFECTIVE_START_DATE = absencePlansE0.EFFECTIVE_START_DATE
	) RES_PLAN
,(SELECT TERRITORY_SHORT_NAME
	FROM FND_TERRITORIES_VL
	WHERE TERRITORY_CODE = absencePlansE0.LEGISLATION_CODE 
	) RES_LEGISLATION
,(SELECT NAME
	FROM PER_LEGISLATIVE_DATA_GROUPS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND LEGISLATIVE_DATA_GROUP_ID = absencePlansE0.LEGISLATIVE_DATA_GROUP_ID 
	) RES_LEGISLATIVE_DATA_GROUP
,TO_CHAR(absencePlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(absencePlansE0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(absencePlansE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE

-- Adjustments and Transfers show on Accurual
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		DECODE(absencePlansE0.BALANCE_TRANSFER_FLAG,'Y','Yes','No') 
		END) RES_ENABLE_TRANSFERS
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		DECODE(absencePlansE0.OTHER_ADJUSTMENT_FLAG,'Y','Yes','No') 
	END) RES_ENABLE_ADJUSTMENTS
/*
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(CASE
			WHEN absencePlansE0.OTHER_REASONS LIKE '%CE%' THEN
				'Yes'
			ELSE
				'No'
		END)
	END) RES_ADJUSTMENT_REASONS_CLERICA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(CASE
			WHEN absencePlansE0.OTHER_REASONS LIKE '%CP%' THEN
				'Yes'
			ELSE
				'No'
		END)
	END) RES_ADJUSTMENT_REASONS_COMPENS
*/	
	
-- Balance Updates show on balance updates
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		DECODE(absencePlansE0.CASH_OUT_FLAG,'Y','Yes','No') 
	END) RES_DISCRETIONARY_DISBURSEMENT
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON') THEN 
		DECODE(absencePlansE0.BALANCE_TRANSFER_FLAG,'Y','Yes','No') 
	END) RES_BALANCE_TRANSFER_ACROSS_PL


-- Balance Updates show on Donation
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_DON','N') THEN 
		DECODE(absencePlansE0.OTHER_ADJUSTMENT_FLAG,'Y','Yes','No') 
	END) RES_OTHER_ADJUSTMENTS
/*
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_DON','N') AND absencePlansE0.OTHER_ADJUSTMENT_FLAG = 'Y' THEN 
		(CASE
			WHEN absencePlansE0.OTHER_REASONS LIKE '%CE%' THEN
				'Yes'
			ELSE
				'No'
		END)
	END) RES_OTHER_ADJUSTMENT_REASONS_C -- Other Adjustment Reasons - Clerical Error
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_DON','N') AND absencePlansE0.OTHER_ADJUSTMENT_FLAG = 'Y' THEN 
		(CASE
			WHEN absencePlansE0.OTHER_REASONS LIKE '%CP%' THEN
				'Yes'
			ELSE
				'No'
		END)
	END) RES_OTHER_ADJUSTMENT_REASONS_0 -- Other Adjustment Reasons - Compensatory
*/


-- Elective Disbursements Show on Accurual
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		DECODE(absencePlansE0.BEN_IMPACT_FLAG,'Y','Yes','No') 
	END) RES_ENABLE_BENEFITS_INTEGRATIO
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		DECODE(absencePlansE0.PENDING_DISBURSE_FLAG,'Y','Yes','No') 
	END) RES_MARK_AS_PENDING
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_ANC_ELECT_DT_RULE'
			AND LOOKUP_CODE = absencePlansE0.ELECTION_DATE_RULE)
	END) RES_ELECTION_DATE_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		absencePlansE0.ELECT_DISB_PAY_RATE_FACTOR 
	END) RES_DEFAULT_PAYMENT_PERCENTAGE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.ELECT_DISB_VALID_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_EVALUATION_FORMULA


-- Year End Disbursements Show on Accurual
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		absencePlansE0.YREND_DISB_PAY_RATE_FACTOR 
	END) RES_YEAR_END_DISBURSEMENTS_DEF -- Year End Disbursements - Default Payment Percentage


-- Manual Adjustments show on type Compensatory
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		DECODE(absencePlansE0.ADMIN_MANUAL_ADJUSTMENT,'Y','Yes','No') 
	END) RES_MANUAL_ADJUSTMENTS_ENABLE_ -- Manual Adjustments - Enable for administrator
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		DECODE(absencePlansE0.MGR_MANUAL_ADJUSTMENT,'Y','Yes','No') 
	END) RES_MANUAL_ADJUSTMENTS_ENABL_0 -- Manual Adjustments - Enable for manager
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		(CASE
			WHEN absencePlansE0.COMP_MNUL_ADJRSN = 'ORA_ANC_NOTDETERMINED' THEN
				'Yes'
			ELSE
				'No'
			END)
	END) RES_MANUAL_ADJUSTMENTS_REASONS -- Manual Adjustments Reasons - Not determined


-- Expiration Date Updates show on type Compensatory
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		DECODE(absencePlansE0.ADMIN_EXPIRATION_UPDATE,'Y','Yes','No') 
	END) RES_EXPIRATION_DATE_UPDATES_EN -- Expiration Date Updates - Enable for administrator
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		DECODE(absencePlansE0.MGR_EXPIRATION_UPDATE,'Y','Yes','No') 
	END) RES_EXPIRATION_DATE_UPDATES__1 -- Expiration Date Updates - Enable for manager
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		(CASE
			WHEN absencePlansE0.COMP_EXP_ADJRSN = 'ORA_ANC_NOTDETERMINED' THEN
				'Yes'
			ELSE
				'No'
			END)
	END) RES_EXPIRATION_DATE_UPDATES_RE -- Expiration Date Updates Reasons - Not determined

--Discretionary Disbursements show on Accural,Donation
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_DON') THEN 
		DECODE(absencePlansE0.CASH_OUT_FLAG,'Y','Yes','No')
	END) RES_DISCRETIONARY_DISBURSEME_2 -- Discretionary Disbursements - Enable for administrator
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_DON') THEN 
		DECODE(absencePlansE0.MGR_MANUAL_ADJUSTMENT,'Y','Yes','No') 
	END) RES_DISCRETIONARY_DISBURSEME_3 -- Discretionary Disbursements - Enable for manager
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_DON') THEN 
		DECODE(absencePlansE0.EMP_MANUAL_ADJUSTMENT,'Y','Yes','No') 
	END) RES_DISCRETIONARY_DISBURSEME_4 -- Discretionary Disbursements - Enable for worker
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_DON') THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_ANC_DISB_DON_RULE'
			AND LOOKUP_CODE = absencePlansE0.DISB_RULE)
	END) RES_DISBURSEMENT_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.DISB_RULE = 'ORA_ANC_FORMULA' THEN
				(SELECT BASE_FORMULA_NAME 
					FROM FF_FORMULAS_VL 
					WHERE FORMULA_ID = absencePlansE0.DISB_FORMULA_ID
					AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
		END)
	END) RES_DISCRETIONARY_DISBURSEME_5 -- Discretionary Disbursements - Formula
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.DISB_RULE = 'ORA_ANC_FLAT_AMT' THEN
				absencePlansE0.DISB_MIN_FLAT_AMT 
			END)
	END) RES_DISCRETIONARY_DISBURSEME_6 -- Discretionary Disbursements - Minimum
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.DISB_RULE = 'ORA_ANC_FLAT_AMT' THEN
				absencePlansE0.DISB_MAX_FLAT_AMT
			END)
	END) RES_DISCRETIONARY_DISBURSEME_7 -- Discretionary Disbursements - Maximum
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.DISB_RULE = 'ORA_ANC_FLAT_AMT' THEN
				absencePlansE0.DISB_INCR_FLAT_AMT
			END)
	END) RES_DISCRETIONARY_DISBURSEME_8 -- Discretionary Disbursements - Increment


-- Donation show on Accural
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		DECODE(absencePlansE0.DON_ADMIN_MANUAL_ADJ,'Y','Yes','No')
	END) RES_DONATION_ENABLE_FOR_ADMINI
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		DECODE(absencePlansE0.DON_MGR_MANUAL_ADJ,'Y','Yes','No') 
	END) RES_DONATION_ENABLE_FOR_MANAGE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		DECODE(absencePlansE0.DON_EMP_MANUAL_ADJ,'Y','Yes','No') 
	END) RES_DONATION_ENABLE_FOR_WORKER
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_ANC_DISB_DON_RULE'
			AND LOOKUP_CODE = absencePlansE0.DON_RULE)
	END) RES_DONATION_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(CASE
			WHEN absencePlansE0.DON_RULE = 'ORA_ANC_FORMULA' THEN
				(SELECT BASE_FORMULA_NAME 
					FROM FF_FORMULAS_VL 
					WHERE FORMULA_ID = absencePlansE0.DON_FORMULA_ID
					AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
		END)
	END) RES_DONATION_FORMULA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(CASE
			WHEN absencePlansE0.DON_RULE = 'ORA_ANC_FLAT_AMT' THEN
				absencePlansE0.DON_MIN_FLAT_AMT 
			END)
	END) RES_DONATION_MINIMUM
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(CASE
			WHEN absencePlansE0.DON_RULE = 'ORA_ANC_FLAT_AMT' THEN
				absencePlansE0.DON_MAX_FLAT_AMT
			END)
	END) RES_DONATION_MAXIMUM
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN 
		(CASE
			WHEN absencePlansE0.DON_RULE = 'ORA_ANC_FLAT_AMT' THEN
				absencePlansE0.DON_INCR_FLAT_AMT
			END)
	END) RES_DONATION_INCREMENT
	
	
-- Rates
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_ABS_PLAN_USE_BASE_RATE'
	AND LOOKUP_CODE = absencePlansE0.PLAN_USE_RATE_RULE 
	) RES_ABSENCE_PAYMENT_RATE_RULE
,(CASE
	WHEN absencePlansE0.PLAN_USE_RATE_RULE = 'D' THEN
		(SELECT NAME 
			FROM PAY_RATE_DEFINITIONS_F_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND RATE_DEFINITION_ID = absencePlansE0.PLAN_USE_RATE_ID)
	END) RES_ABSENCE_PAYMENT_RATE_RULE_ -- Absence Payment Rate Rule - Rate Name
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(CASE
			WHEN absencePlansE0.PLAN_USE_RATE_RULE = 'F' THEN
				(SELECT BASE_FORMULA_NAME 
					FROM FF_FORMULAS_VL 
					WHERE FORMULA_ID = absencePlansE0.PLAN_USE_FORMULA_ID
					AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
			END)
	END) RES_ABSENCE_PAYMENT_RATE_RUL_9 -- Absence Payment Rate Rule - Formula
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_ABS_PLAN_USE_BASE_RATE'
			AND LOOKUP_CODE = absencePlansE0.PAYOUT_RATE_RULE)
	END) RES_FINAL_DISBURSEMENT_RATE_RU -- Final Disbursement Rate Rule
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(CASE
			WHEN absencePlansE0.PAYOUT_RATE_RULE = 'D' THEN
				(SELECT NAME 
					FROM PAY_RATE_DEFINITIONS_F_TL
					WHERE LANGUAGE = USERENV('LANG')
					AND RATE_DEFINITION_ID = absencePlansE0.PAYOUT_RATE_ID)
			END)
	END) RES_DEFINED_RATE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(CASE
			WHEN absencePlansE0.PAYOUT_RATE_RULE = 'F' THEN
				(SELECT BASE_FORMULA_NAME 
					FROM FF_FORMULAS_VL 
					WHERE FORMULA_ID = absencePlansE0.PAYOUT_RATE_FORMULA_ID
					AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
			END)
	END) RES_FINAL_DISBURSEMENT_RATE_10 -- Final Disbursement Rate Rule - Formula
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_ABS_PLAN_USE_BASE_RATE'
			AND LOOKUP_CODE = absencePlansE0.CASHOUT_RATE_RULE)
	END) RES_DISCRETIONARY_DISBURSEM_11 -- Discretionary Disbursement Rate Rule
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(CASE
			WHEN absencePlansE0.CASHOUT_RATE_RULE = 'D' THEN
				(SELECT NAME 
					FROM PAY_RATE_DEFINITIONS_F_TL
					WHERE LANGUAGE = USERENV('LANG')
					AND RATE_DEFINITION_ID = absencePlansE0.CASHOUT_RATE_ID)
			END)
	END) RES_DISCRETIONARY_DISBURSEM_12 -- Discretionary Disbursement Rate Rule - Rate Name
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(CASE
			WHEN absencePlansE0.CASHOUT_RATE_RULE = 'F' THEN
				(SELECT BASE_FORMULA_NAME 
					FROM FF_FORMULAS_VL 
					WHERE FORMULA_ID = absencePlansE0.CASHOUT_RATE_FORMULA_ID
					AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
			END)
	END) RES_DISCRETIONARY_DISBURSEM_13 -- Discretionary Disbursement Rate Rule - Formula
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_ABS_PLAN_USE_BASE_RATE'
			AND LOOKUP_CODE = absencePlansE0.LIABILITY_RATE_RULE)
	END) RES_LIABILITY_RATE_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(CASE
			WHEN absencePlansE0.LIABILITY_RATE_RULE = 'D' THEN
				(SELECT NAME 
					FROM PAY_RATE_DEFINITIONS_F_TL
					WHERE LANGUAGE = USERENV('LANG')
					AND RATE_DEFINITION_ID = absencePlansE0.LIABILITY_RATE_ID)
			END)
	END) RES_LIABILITY_RATE_RULE_RATE_N -- Liability Rate Rule - Rate Name
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD NOT IN ('N','Q','ORA_ANC_AGREE') THEN
		(CASE
			WHEN absencePlansE0.LIABILITY_RATE_RULE = 'F' THEN
				(SELECT BASE_FORMULA_NAME 
					FROM FF_FORMULAS_VL 
					WHERE FORMULA_ID = absencePlansE0.LIABILITY_RATE_FORMULA_ID
					AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
			END)
	END) RES_LIABILITY_RATE_RULE_FORMUL
	
	
-- Payroll Integration
,DECODE(absencePlansE0.PAYROLL_IMPACT_FLAG,'Y','Yes','No') RES_TRANSFER_ABSENCE_PAYMENT_I -- Transfer absence payment information for payroll processing
,(SELECT (SELECT COMPONENT_NAME
		FROM PAY_DIR_CARD_COMP_DEFS_TL 
		WHERE LANGUAGE = USERENV('LANG') 
		AND DIR_CARD_COMP_DEF_ID = mappingE0.SECONDARY_ENTITY_ID)
	FROM PAY_GI_MAPPINGS mappingE0
	WHERE mappingE0.MAPPING_ID = absencePlansE0.PAYROLL_MAPPING_ID
	) RES_ELEMENT

,absencePlansE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,absencePlansE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,absencePlansE0.CREATED_BY  RSC_CREATED_BY
,absencePlansE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,absencePlansE0.LEGISLATION_CODE RSC_COUNTRY_ID
 
FROM ANC_ABSENCE_PLANS_F absencePlansE0
ORDER BY 1
,absencePlansE0.EFFECTIVE_START_DATE