/* ****************************************************************************
 * $Revision: 73658 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2020-02-28 13:42:07 +0700 (Fri, 28 Feb 2020) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.20/trunk/core/reverse_sql/FINANCIALS/Manage%20Absence%20Reasons%20-%20Absence%20Reason.sql $:
 * $Id: Manage Absence Reasons - Absence Reason.sql 73658 2020-02-28 06:42:07Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 
SELECT aARTLEO.NAME RES_NAME
,TO_CHAR(aARTLEO.EFFECTIVE_START_DATE,'DD-MM-YYYY') RES_EFFECTIVE_START_DATE
,aARTLEO.DESCRIPTION RES_DESCRIPTION
,DECODE(TO_CHAR(aARTLEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL, TO_CHAR(aARTLEO.EFFECTIVE_END_DATE,'DD-MM-YYYY')) RES_EFFECTIVE_END_DATE
,(SELECT MEANING 
	FROM FND_LOOKUPS 
	WHERE LOOKUP_CODE = aAREO.LEGISLATION_CODE 
	AND LOOKUP_TYPE = 'JEES_EURO_COUNTRY_CODES'
	) RES_LEGISLATION
,(SELECT MEANING 
	FROM FND_COMMON_LOOKUPS 
	WHERE LOOKUP_CODE = aAREO.STATUS 
	AND LOOKUP_TYPE = 'ACTIVE_INACTIVE'
	) RES_STATUS
,(SELECT MEANING 
	FROM FND_COMMON_LOOKUPS 
	WHERE LOOKUP_CODE = aAREO.MANAGEMENT_TYPE_CD 
	AND LOOKUP_TYPE = 'ANC_SETUP_OBJ_MGMT'
	)  RES_MANAGEMENT
,aAREO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,aAREO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,aAREO.CREATED_BY RSC_CREATED_BY
,aAREO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,aAREO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM ANC_ABSENCE_REASONS_F  aAREO
,ANC_ABSENCE_REASONS_VL aARTLEO
WHERE aAREO.ABSENCE_REASON_ID = aARTLEO.ABSENCE_REASON_ID
AND aARTLEO.LANGUAGE = USERENV('LANG')
AND aAREO.EFFECTIVE_START_DATE = aARTLEO.EFFECTIVE_START_DATE
ORDER BY aARTLEO.NAME