/* ****************************************************************************
 * $Revision: 78284 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-13 13:03:20 +0700 (Wed, 13 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Profile%20Item%20Catalog%20-%20Related%20Content%20Items.sql $:
 * $Id: Manage Profile Item Catalog - Related Content Items.sql 78284 2022-04-13 06:03:20Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=HRT_CONTENT_TP_VALUESETS_VL
 
SELECT (SELECT CONTENT_TYPE_NAME 
	FROM HRT_CONTENT_TYPES_VL 
	WHERE CONTENT_TYPE_ID = hrtCONTPVALUESETEO.CONTENT_TYPE_ID
	) RES_TEMPLATE_NAME
,hrtCONTPVALUESETEO.VALUE_SET_NAME RES_ITEM_CATALOG_NAME
,hrtCONTENTITEMEO.CONTENT_ITEM_CODE RES_ITEM_CODE
,hrtCONTENTITEMEO.NAME RES_ITEM_NAME
,(SELECT CONTENT_TYPE_NAME 
	FROM HRT_CONTENT_TYPES_VL 
	WHERE CONTENT_TYPE_ID = hrtCONTENTITEMRLATEO.CONTENT_TYPE_ID
	) RES_CONTENT_TYPE
,(SELECT NAME 
	FROM HRT_CONTENT_ITEMS_VL 
	WHERE CONTENT_ITEM_ID = hrtCONTENTITEMRLATEO.CONTENT_ITEM_ID
	) RES_CONTENT_ITEMS
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_CODE = hrtCONTENTITEMRLATEO.RELATIONSHIP_CODE 
	AND LOOKUP_TYPE = 'HRT_CONTENT_RELN_CODE' 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_REATIONSHIP_TYPE
,(SELECT NAME 
	FROM HRT_CONTENT_ITEMS_VL 
	WHERE CONTENT_ITEM_ID = hrtCONTENTITEMRLATEO.RELATED_CONTENT_ITEM_ID
	) RES_REATIONSHIP_CONTENT_ITEMS
,TO_CHAR(hrtCONTENTITEMRLATEO.DATE_FROM,'DD-Mon-YYYY') RES_FROM_DATE
,TO_CHAR(hrtCONTENTITEMRLATEO.DATE_TO,'DD-Mon-YYYY') RES_TO_DATE
,hrtCONTENTITEMRLATEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hrtCONTENTITEMRLATEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hrtCONTENTITEMRLATEO.CREATED_BY RSC_CREATED_BY
,hrtCONTENTITEMRLATEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
FROM HRT_CONTENT_TP_VALUESETS_VL hrtCONTPVALUESETEO
,HRT_CONTENT_ITEMS_VL hrtCONTENTITEMEO 
,HRT_CONTENT_ITEM_RLATS hrtCONTENTITEMRLATEO
WHERE hrtCONTPVALUESETEO.CONTENT_VALUE_SET_ID = hrtCONTENTITEMEO.CONTENT_VALUE_SET_ID 
AND hrtCONTPVALUESETEO.CONTENT_TYPE_ID = hrtCONTENTITEMEO.CONTENT_TYPE_ID 
AND hrtCONTENTITEMEO.CONTENT_ITEM_ID = hrtCONTENTITEMRLATEO.CONTENT_ITEM_ID