/* ****************************************************************************
 * $Revision: 55346 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-05-23 14:11:43 +0700 (Mon, 23 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Chart%20of%20Accounts%20Value%20Set%20Values%20-%20Manage%20Values.sql $:
 * $Id: Manage Chart of Accounts Value Set Values - Manage Values.sql 55346 2016-05-23 07:11:43Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

--RSC_PREREQUISITE_OBJECTS=HRC_DL_LAYOUTS_VL
--RSC_PREREQUISITE_OBJECTS=HRC_DL_LAYOUT_INSTRS_VL

SELECT hdcDLLAYOUTEO.LAYOUT_CODE RES_CODE
,hrcDLLAYOUTINSTRSEO.INSTRUCTION_HEADING RES_HEADING
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = hrcDLLAYOUTINSTRSEO.STATUS
		AND LOOKUP_TYPE = 'ORA_HRC_DL_TEMPLT_STATUS' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_STATUS
,hrcDLLAYOUTINSTRSEO.INSTRUCTION_CONTENT RES_INSTRUCTION

,hrcDLLAYOUTINSTRSEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hrcDLLAYOUTINSTRSEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hrcDLLAYOUTINSTRSEO.CREATED_BY RSC_CREATED_BY
,hrcDLLAYOUTINSTRSEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,(SELECT LEGISLATION_CODE 
	FROM PER_LEGISLATIVE_DATA_GROUPS
	WHERE LEGISLATIVE_DATA_GROUP_ID = hdcDLLAYOUTEO.LEGISLATIVE_DATA_GROUP_ID
	) RSC_COUNTRY_ID

FROM HRC_DL_LAYOUTS_VL  hdcDLLAYOUTEO
,HRC_DL_LAYOUT_INSTRS_VL hrcDLLAYOUTINSTRSEO
WHERE hdcDLLAYOUTEO.LAYOUT_CODE = hrcDLLAYOUTINSTRSEO.LAYOUT_CODE
ORDER BY hdcDLLAYOUTEO.LAYOUT_CODE