/* ****************************************************************************
 * $Revision: 61261 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-03-03 13:51:16 +0700 (Fri, 03 Mar 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Default%20Catalogs%20-%20Default%20Catalogs.sql $:
 * $Id: Manage Default Catalogs - Default Catalogs.sql 61261 2017-03-03 06:51:16Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EXM_RCPT_NOTIF_RULE_SETS

SELECT RcptNotifRuleSetEO.NAME RES_NAME
,RcptNotifRuleSetEO.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_RECEIPT_REQUIREMENT'
	AND LOOKUP_CODE = RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE) RES_TYPE_OF_RECEIPT_REQUIRED
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE = 'BOTH' OR RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE = 'IMAGED' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_IMG_RCPT_ATTACHMENT_STAGE'
		AND LOOKUP_CODE = RcptNotifRuleSetEO.IMG_RECEIPT_DUE_CODE)
	END) RES_STAGE_WHEN_IMAGED_RECEIPTS
,(CASE
	WHEN RcptNotifRuleSetEO.IMG_RECEIPT_DUE_CODE = 'PRIOR_MANAGER_APPROVAL' THEN
		RcptNotifRuleSetEO.RECEIPT_DUE_DAYS
	END) RES_DAYS_TO_WAIT_FOR_IMAGED_RE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_EXM_DEFAULT_REC_PAC_DT'
	AND LOOKUP_CODE = RcptNotifRuleSetEO.DEFAULT_RCPT_CHECKIN_DATE_CODE
	) RES_DEFAULT_ORIGINAL_RECEIPT_P	
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE <> 'NONE' THEN
		DECODE(RcptNotifRuleSetEO.OVERDUE_PROCESS_FLAG,'Y','Yes','No')
	END) RES_ENABLE_OVERDUE_PROCESS
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE <> 'NONE' THEN
		(CASE
			WHEN RcptNotifRuleSetEO.OVERDUE_PROCESS_FLAG = 'Y' THEN
				RcptNotifRuleSetEO.RECEIPT_OVERDUE_DAYS 
			END)
	END) RES_ENABLE_OVERDUE_PROCESS_DAY
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE <> 'NONE' THEN
		(CASE
			WHEN RcptNotifRuleSetEO.OVERDUE_PROCESS_FLAG = 'Y' THEN
				DECODE(RcptNotifRuleSetEO.NOTIF_FILER_OVERDUE_FLAG,'Y','Yes','N','No')
			END)
	END) RES_ENABLE_OVERDUE_PROCESS_NOT
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE <> 'NONE' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_RECEIPT_NOTIFICATION_STAGE'
		AND LOOKUP_CODE = RcptNotifRuleSetEO.RCPT_RECEIVED_NOTIF_CODE)
	END) RES_NOTIFY_INDIVIDUAL_WHEN_REC
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE <> 'NONE' THEN
		DECODE(RcptNotifRuleSetEO.RECPT_MISSING_DECL_REQ_FLAG,'Y','Yes','No')
	END) RES_SEND_MISSING_RECEIPT_DECLA
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE <> 'NONE' THEN
		DECODE(RcptNotifRuleSetEO.HOLD_PROCESS_FLAG,'Y','Yes','No')
	END) RES_ENABLE_HOLDS_PROCESS
	
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE <> 'NONE' THEN
		(CASE
			WHEN RcptNotifRuleSetEO.HOLD_PROCESS_FLAG = 'Y' THEN
				(CASE 
					WHEN RcptNotifRuleSetEO.OVERDUE_PROCESS_FLAG = 'N' AND RcptNotifRuleSetEO.HOLD_CODE = 'RECEIPT_OVERDUE' THEN
						NULL
					ELSE
						(SELECT MEANING
						FROM FND_LOOKUPS
						WHERE LOOKUP_TYPE = 'EXM_EXPENSE_REPORT_HOLD_RULE'
						AND LOOKUP_CODE = RcptNotifRuleSetEO.HOLD_CODE)
					END)
			END)
	END) RES_ENABLE_HOLDS_PROCESS_APPLY
,(CASE
	WHEN RcptNotifRuleSetEO.RECEIPT_REQUIRED_CODE <> 'NONE' THEN
		(CASE
			WHEN RcptNotifRuleSetEO.HOLD_PROCESS_FLAG = 'Y' THEN
				(SELECT MEANING
				FROM FND_LOOKUPS
				WHERE LOOKUP_TYPE = 'EXM_EXP_REPORT_TYPE_TO_HOLD'
				AND LOOKUP_CODE = RcptNotifRuleSetEO.HOLD_REPORT_CODE)
			END)
	END) RES_ENABLE_HOLDS_PROCESS_APP_0
,DECODE(RcptNotifRuleSetEO.HOLD_PROJECT_ONLY_FLAG,'Y','Yes','No') RES_APPLY_HOLD_RULES_TO_EXPENS
,RcptNotifRuleSetEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,RcptNotifRuleSetEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,RcptNotifRuleSetEO.CREATED_BY  RSC_CREATED_BY
,RcptNotifRuleSetEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EXM_RCPT_NOTIF_RULE_SETS RcptNotifRuleSetEO
ORDER BY RcptNotifRuleSetEO.NAME