/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Questionnaire%20Templates%20-%20Questions.sql $:
 * $Id: Manage Questionnaire Templates - Questions.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 -- RSC_PREREQUISITE_OBJECTS=HRQ_QUESTIONNAIRES_VL
 -- RSC_PREREQUISITE_OBJECTS=HRQ_QUESTIONS_VL
 
SELECT hrqQUESTIONAIREO.QUESTIONNAIRE_CODE RES_QUESTIONNAIRE_TEMPLATE_ID
,hrqQUESTIONAIREO.NAME RES_NAME
,(SELECT NAME 
	FROM HRQ_SUBSCRIBERS_TL	
	WHERE LANGUAGE = USERENV('LANG') 
	AND SUBSCRIBER_ID = hrqQUESTIONSEO.SUBSCRIBER_ID
	) RES_SUBSCRIBER
,hrqQSTNRSECTIONEO.NAME RES_TITLE
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = hrqQUESTIONSEO.PRIVACY_FLAG
	AND LOOKUP_TYPE = 'HRQ_PRIVACY' 
	AND LANGUAGE = USERENV('LANG') 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PRIVACY
,(SELECT NAME 
	FROM HRQ_CATEGORIES_VL 
	WHERE CATEGORY_ID = hrqQUESTIONSEO.CATEGORY_ID
	) RES_FOLDER
,hrqQUESTIONSEO.QUESTION_CODE RES_QUESTION_CODE
,(SELECT DISPLAY_NAME 
	FROM PER_PERSON_NAMES_F 
	WHERE PERSON_ID = hrqQUESTIONSEO.OWNER 
	AND NAME_TYPE = 'GLOBAL'
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4512-12-31','YYYY-MM-DD'))
	) RES_OWNER
,hrqQUESTIONSEO.QUESTION_TEXT RES_QUESTION_TEXT
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = hrqQUESTIONSEO.QUESTION_TYPE
	AND LOOKUP_TYPE = 'HRQ_QUESTION_TYPE' 
	AND LANGUAGE = USERENV('LANG') 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_QUESTION_TYPE 
,DECODE(hrqQUESTIONSEO.CONDITION_DISPLAY,'Y','Yes','No') RES_DISPLAY_THE_QUESTION_CONDI
,(SELECT NAME 
	FROM HRQ_RESPONSE_TYPES_VL 
	WHERE RESPONSE_TYPE_ID = hrqQUESTIONSEO.RESPONSE_TYPE_ID
	) RES_RESPONSE_TYPE
,NULL RES_REQUIRED
,(SELECT QUESTION_CODE 
	FROM HRQ_QUESTIONS_VL 
	WHERE QUESTION_ID = hrqQUESTIONSEO.CONDITION_QUESTION_ID
	) RES_CONTROLLING_QUESTION_CODE
,(SELECT LONG_TEXT 
	FROM HRQ_QSTN_ANSWERS_VL 
	WHERE QSTN_ANSWER_ID = hrqQUESTIONSEO.CONDITION_ANSWER_ID 
	AND QUESTION_ID = hrqQUESTIONSEO.CONDITION_QUESTION_ID
	) RES_CONTROLLING_RESPONSE
,DECODE(hrqQUESTIONSEO.ATTACHMENT_ALLOWED,'Y','Yes','No') RES_ALLOW_ATTACHMENTS
,hrqQUESTIONSEO.MIN_LENGTH RES_MINIMUM_LENGTH
,hrqQUESTIONSEO.MAX_LENGTH RES_MAXIMUM_LENGTH
,hrqQUESTIONSEO.CONDITION_QSTN_VERSION_NUM RES_QUESTION_VERSION_NUMBER
,DECODE(hrqQUESTIONSEO.SCORED_FLAG,'Y','Yes','No') RES_SCORE_QUESTION
,hrqQUESTIONSEO.MIN_THRESHOLD_SCORE RES_MINIMUM_CALCULATED_SCORE
,hrqQUESTIONSEO.MAX_THRESHOLD_SCORE RES_MAXIMUM_CALCULATED_SCORE
,(SELECT RATING_NAME
    FROM HRT_RATING_MODELS_VL
    WHERE RATING_MODEL_ID = hrqQUESTIONSEO.RATING_MODEL_ID
	) RES_RATING_MODEL
,hrqQUESTIONSEO.MIN_SELECTIONS RES_MINIMUM_NUMBER_OF_SELECTIO
,hrqQUESTIONSEO.MAX_SELECTIONS RES_MAXIMUM_NUMBER_OF_SELECTIO
,hrqQUESTIONSEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hrqQUESTIONSEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hrqQUESTIONSEO.CREATED_BY RSC_CREATED_BY
,hrqQUESTIONSEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HRQ_QUESTIONNAIRES_VL hrqQUESTIONAIREO
,HRQ_QSTNR_TEMPLATES_VL hrqQSTNRETEMPEO
,HRQ_QSTNR_SECTIONS_VL hrqQSTNRSECTIONEO
,HRQ_QSTNR_QUESTIONS hrqQSTNRQUESTIONEO
,HRQ_QUESTIONS_VL hrqQUESTIONSEO
WHERE hrqQUESTIONAIREO.QUESTIONNAIRE_ID = hrqQSTNRETEMPEO.QUESTIONNAIRE_ID
AND hrqQUESTIONAIREO.QUESTIONNAIRE_ID = hrqQSTNRSECTIONEO.QUESTIONNAIRE_ID
AND hrqQSTNRSECTIONEO.QSTNR_SECTION_ID = hrqQSTNRQUESTIONEO.QSTNR_SECTION_ID
AND hrqQSTNRQUESTIONEO.QUESTION_ID = hrqQUESTIONSEO.QUESTION_ID
AND hrqQSTNRQUESTIONEO.QSTN_VERSION_NUM = hrqQUESTIONSEO.QSTN_VERSION_NUM
ORDER BY hrqQUESTIONAIREO.QUESTIONNAIRE_CODE
,hrqQUESTIONAIREO.NAME