/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=HWM_WORK_DAY_DEF_VL

SELECT wddE0.NAME RES_NAME
,wddE0.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HWM_DAY_DIVIDE_RULES'
    AND LOOKUP_CODE = wddE0.EARNED_DAY_BREAK_RULE
    ) RES_SPANNING_DAYS_RULE
,(CASE
    WHEN wddE0.EARNED_DAY_BREAK_RULE IN ('ORA_HWM_MOST_HOURS','ORA_HWM_START_DAY','ORA_HWM_STOP_DAY') THEN
        wddE0.EARNED_BREAK_THRESHOLD
    END) RES_GROUPING_THRESHOLD
,(CASE
    WHEN wddE0.EARNED_DAY_BREAK_RULE IN ('ORA_HWM_MOST_HOURS') THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'ORA_HWM_WDD_TIE_BREAK_RULES'
            AND LOOKUP_CODE = wddE0.EARNED_TIE_BREAK_CRITERIA)
    END) RES_TIE_HANDLING
,TO_CHAR(wddE0.DAY_START_TIME,'HH:MI AM') RES_DAY_START_TIME
,DECODE(wddE0.IS_OVERTIME_NEXT_DAY,'N','Current Day','Next Day') RES_DAY_START_TIME_OPTION
,wddE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,wddE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,wddE0.CREATED_BY RSC_CREATED_BY
,wddE0.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,wddE0.ENTERPRISE_ID RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HWM_WORK_DAY_DEF_VL wddE0
ORDER BY wddE0.NAME