/* ****************************************************************************
 * $Revision: 50638 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2015-11-18 14:55:09 +0700 (Wed, 18 Nov 2015) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Cumulative%20Mileage%20Determinants%20-%20Manage%20Cumulative%20Mileage%20Determinants.sql $:
 * $Id: Manage Cumulative Mileage Determinants - Manage Cumulative Mileage Determinants.sql 50638 2015-11-18 07:55:09Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=140##RES##FA_METHODS
-- DFF_ATTRIBUTES=ATTRIBUTE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

select QRSLT.METHOD_CODE  RES_NAME
,QRSLT.SET_NAME RES_REFERENCE_DATA_SET
,QRSLT.MEANING RES_METHOD_TYPE
,TRUNC(QRSLT.LIFE_IN_MONTHS/12) RES_LIFE_IN_YEARS
,MOD(QRSLT.LIFE_IN_MONTHS,12) RES_LIFE_IN_MONTHS
,DECODE(USE_LIFE_IN_PERIODS_FLAG,'Y',QRSLT.LIFE_IN_MONTHS,NULL) RES_LIFE_IN_PERIODS
,QRSLT.ATTRIBUTE_CATEGORY_CODE RES_CONTEXT_CODE
,QRSLT.ATTRIBUTE1 
,QRSLT.ATTRIBUTE2
,QRSLT.ATTRIBUTE3
,QRSLT.ATTRIBUTE4
,QRSLT.ATTRIBUTE5
,QRSLT.ATTRIBUTE6
,QRSLT.ATTRIBUTE7
,QRSLT.ATTRIBUTE8
,QRSLT.ATTRIBUTE9
,QRSLT.ATTRIBUTE10
,QRSLT.ATTRIBUTE11
,QRSLT.ATTRIBUTE12
,QRSLT.ATTRIBUTE13
,QRSLT.ATTRIBUTE14
,QRSLT.ATTRIBUTE15
,QRSLT.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY RSC_CREATED_BY
,QRSLT.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

from ( 
SELECT
DepreciationMethodEO.METHOD_CODE
,DepreciationMethodEO.NAME
,DEPRECIATIONMETHODEO.SET_ID
,DEPRECIATIONMETHODEO.DEPRECIATE_LASTYEAR_FLAG
,DepreciationMethodEO.RATE_SOURCE_RULE
,DepreciationMethodEO.DEPRN_BASIS_RULE
,DepreciationMethodEO.DEPRN_BASIS_RULE_ID
,DepreciationMethodEO.PRORATE_PERIODS_PER_YEAR
,DepreciationMethodEO.STL_METHOD_FLAG
,DEPRECIATIONMETHODEO.METHOD_ID
,DEPRECIATIONMETHODEO.LIFE_IN_MONTHS
,DEPRECIATIONMETHODEO.USE_LIFE_IN_PERIODS_FLAG
,DEPRECIATIONMETHODEO.EXCLUDE_SALVAGE_VALUE_FLAG
,DEPRECIATIONMETHODEO.POLISH_ADJ_CALC_BASIS_FLAG
,DEPRECIATIONMETHODEO.LAST_UPDATED_BY 
,DEPRECIATIONMETHODEO.LAST_UPDATE_DATE
,DEPRECIATIONMETHODEO.CREATION_DATE
,DEPRECIATIONMETHODEO.CREATED_BY
,LookupMethodTypePEO.LOOKUP_TYPE
,LookupMethodTypePEO.LOOKUP_CODE
,LookupMethodTypePEO.MEANING
,LookupCalcbasisPEO.LOOKUP_CODE AS LOOKUP_CODE1
,LookupCalcbasisPEO.LOOKUP_TYPE AS LOOKUP_TYPE1
,LOOKUPCALCBASISPEO.MEANING     as MEANING1
,SETIDSETSEO.SET_NAME 
,DEPRECIATIONRU.Rule_NAME
,DEPRECIATIONMETHODEO.ATTRIBUTE_CATEGORY_CODE
,DEPRECIATIONMETHODEO.ATTRIBUTE1 
,DEPRECIATIONMETHODEO.ATTRIBUTE2
,DEPRECIATIONMETHODEO.ATTRIBUTE3
,DEPRECIATIONMETHODEO.ATTRIBUTE4
,DEPRECIATIONMETHODEO.ATTRIBUTE5
,DEPRECIATIONMETHODEO.ATTRIBUTE6
,DEPRECIATIONMETHODEO.ATTRIBUTE7
,DEPRECIATIONMETHODEO.ATTRIBUTE8
,DEPRECIATIONMETHODEO.ATTRIBUTE9
,DEPRECIATIONMETHODEO.ATTRIBUTE10
,DEPRECIATIONMETHODEO.ATTRIBUTE11
,DEPRECIATIONMETHODEO.ATTRIBUTE12
,DEPRECIATIONMETHODEO.ATTRIBUTE13
,DEPRECIATIONMETHODEO.ATTRIBUTE14
,DEPRECIATIONMETHODEO.ATTRIBUTE15
from FA_METHODS DEPRECIATIONMETHODEO
,FA_DEPRN_BASIS_RULES DEPRECIATIONRU
,FND_LOOKUPS LookupMethodTypePEO
,FND_LOOKUPS LOOKUPCALCBASISPEO
,FND_SETID_SETS_VL SETIDSETSEO
WHERE LookupMethodTypePEO.LOOKUP_TYPE (+)          = 'FA_RATE_SOURCE_RULE'
AND DepreciationMethodEO.RATE_SOURCE_RULE          = LookupMethodTypePEO.LOOKUP_CODE (+)
AND LookupCalcbasisPEO.LOOKUP_TYPE (+)             = 'FA_DEPRN_BASIS_RULE'
and DEPRECIATIONMETHODEO.DEPRN_BASIS_RULE          = LOOKUPCALCBASISPEO.LOOKUP_CODE (+)
and DEPRECIATIONMETHODEO.SET_ID                    = SETIDSETSEO.SET_ID(+)
and DEPRECIATIONMETHODEO.DEPRN_BASIS_RULE_ID       =  DEPRECIATIONRU.DEPRN_BASIS_RULE_ID(+)
AND (DEPRECIATIONMETHODEO.ATTRIBUTE_CATEGORY_CODE IS NOT NULL OR
DEPRECIATIONMETHODEO.ATTRIBUTE1 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE2 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE3 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE4 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE5 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE6 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE7 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE8 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE9 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE10 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE11 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE12 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE13 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE14 IS NOT NULL OR 
DEPRECIATIONMETHODEO.ATTRIBUTE15 IS NOT NULL)
ORDER BY DepreciationMethodEO.METHOD_CODE
,DepreciationMethodEO.RATE_SOURCE_RULE
,DEPRECIATIONMETHODEO.DEPRN_BASIS_RULE
) QRSLT