/* ****************************************************************************
 * $Revision: 55346 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-05-23 14:11:43 +0700 (Mon, 23 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Chart%20of%20Accounts%20Value%20Set%20Values%20-%20Manage%20Values.sql $:
 * $Id: Manage Chart of Accounts Value Set Values - Manage Values.sql 55346 2016-05-23 07:11:43Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=ANC_ABSENCE_PLANS_F

SELECT (SELECT NAME 
	FROM ANC_ABSENCE_PLANS_F_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND ABSENCE_PLAN_ID = absencePlansE0.ABSENCE_PLAN_ID
	AND EFFECTIVE_START_DATE = absencePlansE0.EFFECTIVE_START_DATE
	) RES_PLAN
,(SELECT TERRITORY_SHORT_NAME
	FROM FND_TERRITORIES_VL
	WHERE TERRITORY_CODE = absencePlansE0.LEGISLATION_CODE 
	) RES_LEGISLATION
,(SELECT NAME
	FROM PER_LEGISLATIVE_DATA_GROUPS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND LEGISLATIVE_DATA_GROUP_ID = absencePlansE0.LEGISLATIVE_DATA_GROUP_ID 
	) RES_LEGISLATIVE_DATA_GROUP
,TO_CHAR(absencePlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(absencePlansE0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(absencePlansE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP','N') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_ENRL_START'
			AND LOOKUP_CODE = absencePlansE0.ENROLLMENT_START_RULE)
	END) RES_ENROLLMENT_START_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP','N') THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.ENROLLMENT_START_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_START_DATE_FORMULA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP','N') THEN
		absencePlansE0.WAIT_PERIOD_DUR_UNITS 
	END) RES_WAITING_PERIOD
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP','N') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_DURATION_UOM'
			AND LOOKUP_CODE = absencePlansE0.WAIT_PERIOD_DUR_UOM)
	END) RES_WAITING_PERIOD_TYPE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'Q' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_QUA_ENRL_START'
			AND LOOKUP_CODE = absencePlansE0.ENTITLEMENT_START_DATE)
	END) RES_QUALIFICATION_DATE_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'Q' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.ENTITLEMENT_END_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_FORMULA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'Q' THEN
		DECODE(absencePlansE0.EVAL_ENTITLEMENT_FLAG,'Y','Yes','No')
	END) RES_EVALUATE_REMAINING_ENTITLE
	
	
	
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP','N') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_ENRL_END'
			AND LOOKUP_CODE = absencePlansE0.ENROLLMENT_END_RULE)
	END) RES_ENROLLMENT_END_RULE
	
	
	
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'Q' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_ENTL_END'
			AND LOOKUP_CODE = absencePlansE0.ENTITLEMENT_END_RULE)
	END) RES_ENTITLEMENT_END_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'Q' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.ENTITLEMENT_END_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_ENTITLEMENT_END_FORMULA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP','N') THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.ENROLLMENT_END_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_END_DATE_FORMULA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'A' THEN
		DECODE(absencePlansE0.TRANSFR_POSITIVE_BALANCE_FLAG,'Y','Yes','No')
	END) RES_ON_LOSS_OF_PLAN_ELIGIBILIT
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP') THEN
		DECODE(absencePlansE0.ENROLL_POSITIVE_BALANCE_FLAG,'Y','Yes','No')
	END) RES_ON_LOSS_OF_PLAN_ELIGIBIL_0
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP') THEN
		DECODE(absencePlansE0.ENROLL_NEGATIVE_BALANCE_FLAG,'Y','Yes','No')
	END) RES_ON_LOSS_OF_PLAN_ELIGIBIL_1
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP') THEN
		DECODE(absencePlansE0.EMP_ENRL_POSITIVE_BALANCE_FLAG,'Y','Yes','No')
	END) RES_ON_EMPLOYMENT_TERMINATION_
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP') THEN
		DECODE(absencePlansE0.EMP_ENRL_NEGATIVE_BALANCE_FLAG,'Y','Yes','No')
	END) RES_ON_EMPLOYMENT_TERMINATIO_2
,(CASE
	WHEN absencePlansE0.TRANSFR_POSITIVE_BALANCE_FLAG = 'Y' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_ANC_TRANSFER_LMT_RULE'
			AND LOOKUP_CODE = absencePlansE0.TRANSFR_LMT_RULE)
	END) RES_LIMIT_RULE
,(CASE
	WHEN absencePlansE0.TRANSFR_POSITIVE_BALANCE_FLAG = 'Y' AND absencePlansE0.TRANSFR_LMT_RULE = 'ORA_ANC_LIMITED' THEN
		absencePlansE0.TRANSFR_LMT_FLAT_AMT
	END) RES_LIMIT
,(CASE
	WHEN absencePlansE0.TRANSFR_POSITIVE_BALANCE_FLAG = 'Y' AND absencePlansE0.TRANSFR_LMT_RULE = 'ORA_ANC_FORMULA' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.TRANSFR_LMT_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_LIMIT_FORMULA
,(CASE
	WHEN absencePlansE0.TRANSFR_POSITIVE_BALANCE_FLAG = 'Y' AND absencePlansE0.TRANSFR_LMT_RULE IN ('ORA_ANC_LIMITED','ORA_ANC_FORMULA') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_PRORATION'
			AND LOOKUP_CODE = absencePlansE0.TRANSFR_LMT_PRORATE_RULE)
	END) RES_LIMIT_PRORATION_RULE
,(CASE
	WHEN absencePlansE0.TRANSFR_POSITIVE_BALANCE_FLAG = 'Y' AND absencePlansE0.TRANSFR_LMT_PRORATE_RULE = 'F' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.TRANSFR_LMT_PRORATE_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_LIMIT_PRORATION_FORMULA
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ORA_ANC_PLAN_CATEGORY'
	AND LOOKUP_CODE = absencePlansE0.TRANSFR_PLAN_CATEGORY
	) RES_PLAN_CATEGORY
,(SELECT BASE_FORMULA_NAME 
	FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = absencePlansE0.TRANSFR_TARGET_FORMULA_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_TARGET_PLAN_FORMULA
,(CASE
	WHEN absencePlansE0.ENROLL_NEGATIVE_BALANCE_FLAG = 'N' 
	AND absencePlansE0.EMP_ENRL_NEGATIVE_BALANCE_FLAG = 'N' 
	AND absencePlansE0.ENROLL_POSITIVE_BALANCE_FLAG = 'N'
	AND absencePlansE0.EMP_ENRL_POSITIVE_BALANCE_FLAG = 'N' THEN
		DECODE(absencePlansE0.RE_INSTATEMENT_FLAG,'Y','Yes','No')
	END) RES_ALLOW_PRIOR_BALANCE_REINST
	
,absencePlansE0.RE_ENRL_BAL_LMT RES_BALANCE_REINSTATEMENT_LIMI
,absencePlansE0.TIME_FRAME_LMT RES_TIME_FRAME_LIMIT
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ORA_ANC_TMEFRAME_LIMIT'
	AND LOOKUP_CODE = absencePlansE0.TIME_FRAME_UOM
	) RES_TIME_FRAME_LIMIT_TYPE
	
,absencePlansE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,absencePlansE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,absencePlansE0.CREATED_BY  RSC_CREATED_BY
,absencePlansE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,absencePlansE0.LEGISLATION_CODE RSC_COUNTRY_ID
 
FROM ANC_ABSENCE_PLANS_F absencePlansE0
WHERE absencePlansE0.ENTL_METHOD_CD IN ('A','ORA_ANC_COMP','N','Q')
ORDER BY 1
,absencePlansE0.EFFECTIVE_START_DATE