/* ****************************************************************************
* $Revision: 55345 $:
* $Author: wuttipong.thongvises $:
* $Date: 2016-05-23 12:42:33 +0700 (Mon, 23 May 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/
FINANCIALS/Manage%20Server%20Configurations%20-%20Manage%20Data%20Quality%20Server%20Configurations.sql $:
* $Id: Manage Server Configurations - Manage Data Quality Server Configurations.sql 55345 2016-05-23 05:42:33Z
wuttipong.thongvises $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT benELIGYEO.NAME RES_NAME
,benELIGSCHEDDHRSEO.ORDR_NUM RES_SEQUENCE
,TO_CHAR(benELIGSCHEDDHRSEO.HRS_NUM,'999999') RES_MINIMUM_HOURS
,TO_CHAR(benELIGSCHEDDHRSEO.MAX_HRS_NUM,'999999') RES_MAXIMUM_HOURS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benELIGSCHEDDHRSEO.FREQ_CD
	AND LOOKUP_TYPE = 'FREQUENCY' AND LANGUAGE = USERENV('LANG')) RES_SCHEDULED_ENROLLMENT_PERIO
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benELIGSCHEDDHRSEO.SCHEDD_HRS_RL
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_RANGE_OF_HOURS_FORMULA
,DECODE(benELIGSCHEDDHRSEO.EXCLD_FLAG,'Y','Yes','No') RES_EXCLUDE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benELIGSCHEDDHRSEO.DETERMINATION_CD
	AND LOOKUP_TYPE = 'BEN_AGE_DET' AND LANGUAGE = USERENV('LANG')) RES_DETERMINATION_RULE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benELIGSCHEDDHRSEO.DETERMINATION_RL 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_DETERMINATION_FORMULA
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benELIGSCHEDDHRSEO.ROUNDING_CD
	AND LOOKUP_TYPE = 'BEN_RNDG' AND LANGUAGE = USERENV('LANG')) RES_ROUNDING_RULE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benELIGSCHEDDHRSEO.ROUNDING_RL
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_ROUNDING_FORMULA
,DECODE(benELIGSCHEDDHRSEO.USE_WORK_SCHEDULE_FLAG,'Y','Yes','No') RES_USE_WORK_SCHEDULE
,TO_CHAR(benELIGSCHEDDHRSEO.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(benELIGSCHEDDHRSEO.END_DATE,'DD-Mon-YYYY') RES_END_DATE

,benELIGSCHEDDHRSEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,benELIGSCHEDDHRSEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,benELIGSCHEDDHRSEO.CREATED_BY  RSC_CREATED_BY
,benELIGSCHEDDHRSEO.CREATION_DATE  RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM BEN_ELIGY_PRFL benELIGYEO
,BEN_ELIG_SCHEDD_HRS_PRTE benELIGSCHEDDHRSEO
WHERE benELIGSCHEDDHRSEO.ELIGY_PRFL_ID = benELIGSCHEDDHRSEO.ELIGY_PRFL_ID 
AND benELIGYEO.END_DATE BETWEEN benELIGSCHEDDHRSEO.START_DATE AND NVL(benELIGSCHEDDHRSEO.END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND SYSDATE BETWEEN benELIGYEO.START_DATE AND NVL(benELIGYEO.END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
ORDER BY benELIGYEO.NAME,benELIGSCHEDDHRSEO.ORDR_NUM