/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Reporting%20Entities%20-%20Reporting%20Entity.sql $:
 * $Id: Manage Reporting Entities - Reporting Entity.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

select distinct BUSINESSUNITPEO.BU_NAME 						RES_BUSINESS_UNIT
,REPORTINGENTITYHEADEREO.ENTITY_NAME RES_NAME
,REPORTINGENTITYHEADEREO.TAX_IDENTIFICATION_NUM RES_TAXPAYER_ID
,LOCATIONDPEO.LOCATION_CODE RES_LOCATION
,LOCATIONDPEO.DESCRIPTION RES_LOCATION_DESCRIPTION
,ReportingEntityHeaderEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,ReportingEntityHeaderEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,ReportingEntityHeaderEO.CREATED_BY  RSC_CREATED_BY
,ReportingEntityHeaderEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,BusinessUnitPEO.BU_ID RSC_BUSINESS_UNIT_ID
,BusinessUnitPEO.LEGAL_ENTITY_ID RSC_LEGAL_ENTITY_ID
,APREPORTINGENTITYLINESALL.ORG_ID RSC_ORGANIZATION_ID
,BusinessUnitPEO.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

from  FUSION.FUN_ALL_BUSINESS_UNITS_V BusinessUnitPEO
,AP_REPORTING_ENTITIES_ALL REPORTINGENTITYHEADEREO
,AP_REPORTING_ENTITY_LINES_ALL APREPORTINGENTITYLINESALL
,HR_LOCATIONS_ALL_F_VL LOCATIONDPEO
where  BUSINESSUNITPEO.BU_ID = REPORTINGENTITYHEADEREO.ORG_ID
and REPORTINGENTITYHEADEREO.LOCATION_ID = LOCATIONDPEO.LOCATION_ID
and REPORTINGENTITYHEADEREO.TAX_ENTITY_ID = APREPORTINGENTITYLINESALL.TAX_ENTITY_ID(+)
ORDER BY ReportingEntityHeaderEO.ENTITY_NAME