/* ****************************************************************************
 * $Revision: 53780 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-03-22 17:55:28 +0700 (Tue, 22 Mar 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/customized/Backup%20Trunk/reverse_sql/FINANCIALS/Manage%20Disbursement%20Lookups%20-%20Financials%20Generic%20Lookup%20Type.sql $:
 * $Id: Manage Disbursement Lookups - Financials Generic Lookup Type.sql 53780 2016-03-22 10:55:28Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 


SELECT LOOKUPVALUETRANSLATIONEO.LOOKUP_TYPE RES_LOOKUP_TYPE
,LOOKUPVALUETRANSLATIONEO.LOOKUP_CODE RES_LOOKUP_CODE
,SetIdSetPEO.SET_NAME RES_REFERENCE_DATA_SET
,LOOKUPVALUETRANSLATIONEO.DISPLAY_SEQUENCE RES_DISPLAY_SEQUENCE
,DECODE(LOOKUPVALUETRANSLATIONEO.ENABLED_FLAG,'Y','Yes','No') RES_ENABLED
,TO_CHAR(LOOKUPVALUETRANSLATIONEO.START_DATE_ACTIVE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(LOOKUPVALUETRANSLATIONEO.END_DATE_ACTIVE,'DD-Mon-YYYY') RES_END_DATE
,LOOKUPVALUETRANSLATIONEO.MEANING RES_MEANING
,LOOKUPVALUETRANSLATIONEO.DESCRIPTION RES_DESCRIPTION
,LOOKUPVALUETRANSLATIONEO.TAG RES_TAG
,LookupValueTranslationEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,LookupValueTranslationEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,LookupValueTranslationEO.CREATED_BY RSC_CREATED_BY
,LookupValueTranslationEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FUSION.FND_LOOKUP_VALUES_VL LOOKUPVALUETRANSLATIONEO
,FND_LOOKUP_TYPES_VL LOOKUPTYPEEO
,FND_APPL_TAXONOMY_VL APPLTAXONOMYPEO
,FND_SETID_SETS_VL SetIdSetPEO
WHERE LOOKUPVALUETRANSLATIONEO.LOOKUP_TYPE = LOOKUPTYPEEO.LOOKUP_TYPE
AND LOOKUPTYPEEO.MODULE_ID                 = APPLTAXONOMYPEO.MODULE_ID
AND LOOKUPVALUETRANSLATIONEO.set_id        = SetIdSetPEO.set_id
AND(LookupTypeEO.MODULE_ID                IN
	(SELECT rf.child_module_id
	FROM fnd_appl_taxonomy_rf rf
	,FND_APPL_TAXONOMY AT
	WHERE AT.MODULE_TYPE = 'APPLICATION'
	AND at.module_key    = 'IBY'
	AND AT.MODULE_ID     = RF.ANCESTOR_MODULE_ID
	))
ORDER BY LookupValueTranslationEO.LOOKUP_TYPE
,LookupValueTranslationEO.LOOKUP_CODE