/* ****************************************************************************
 * $Revision: 78915 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-07-04 14:22:26 +0700 (Mon, 04 Jul 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Plans%20-%20Enrollment%20Life%20Event.sql $:
 * $Id: Manage Benefit Plans - Enrollment Life Event.sql 78915 2022-07-04 07:22:26Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=BEN_PL_F
 
SELECT benPlansE0.NAME RES_PLAN_NAME
,TO_CHAR(benPlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,benPlansE0.NAME RES_PLAN_OR_OPTION_NAME
,'Plan' RES_PLAN_OR_OPTION_DESCRIPTION
,(SELECT NAME
    FROM BEN_LER_F_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND LER_ID = lifeEventsE0.LER_ID
    ) RES_LIFE_EVENT
,TO_CHAR(lifeEventsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_LIFE_EVENT_EFFECTIVE_START
,DECODE(TO_CHAR(lifeEventsE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY'),'31-12-4712',NULL,TO_CHAR(lifeEventsE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_LIFE_EVENT_EFFECTIVE_END_D
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_PERD_STRT'
    AND LOOKUP_CODE = lifeEventsE0.ENRT_PERD_STRT_DT_CD
    ) RES_LIFE_EVENT_PERIOD_START_DA
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = lifeEventsE0.ENRT_PERD_STRT_DT_RL
    ) RES_LIFE_EVENT_PERIOD_START__0
,lifeEventsE0.ENRT_PERD_END_DAYS RES_LIFE_EVENT_START_DAYS
,lifeEventsE0.DYS_AFTR_END_TO_DFLT_NUM RES_DAYS_AFTER_ENROLLMENT_CLOS
,lifeEventsE0.DYS_NO_ENRL_NOT_ELIG_NUM RES_DAYS_AFTER_LIFE_EVENT_OCCU
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_PERD_END'
    AND LOOKUP_CODE = lifeEventsE0.ENRT_PERD_END_DT_CD
    ) RES_LIFE_EVENT_PERIOD_END_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = lifeEventsE0.ENRT_PERD_END_DT_RL
    ) RES_LIFE_EVENT_PERIOD_END_DA_1
,lifeEventsE0.ENRT_PERD_STRT_DAYS RES_LIFE_EVENT_END_DAYS
	
,lifeEventsE0.ADDL_PROCG_DYS_NUM RES_ADDITIONAL_DAYS_ALLOWED_FO
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_CLS_ENRT_DT_TO_USE'
    AND LOOKUP_CODE = lifeEventsE0.CLS_ENRT_DT_TO_USE_CD
    ) RES_CLOSE_ENROLLMENT_PERIOD_DA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_CVG_STRT'
    AND LOOKUP_CODE = lifeEventsE0.ENRT_CVG_STRT_DT_CD
    ) RES_COVERAGE_START_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = lifeEventsE0.ENRT_CVG_STRT_DT_RL
    ) RES_COVERAGE_START_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_CVG_END'
    AND LOOKUP_CODE = lifeEventsE0.ENRT_CVG_END_DT_CD
    ) RES_PREVIOUS_COVERAGE_END_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = lifeEventsE0.ENRT_CVG_END_DT_RL
    ) RES_PREVIOUS_COVERAGE_END_FORM
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_RT_STRT'
    AND LOOKUP_CODE = lifeEventsE0.RT_STRT_DT_CD
    ) RES_RATE_START_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = lifeEventsE0.RT_STRT_DT_RL
    ) RES_RATE_START_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_RT_END'
    AND LOOKUP_CODE = lifeEventsE0.RT_END_DT_CD
    ) RES_PREVIOUS_RATE_END_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = lifeEventsE0.RT_END_DT_RL
    ) RES_PREVIOUS_RATE_END_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_REINSTATE'
    AND LOOKUP_CODE = lifeEventsE0.REINSTATE_CD
    ) RES_REINSTATEMENT_RULE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_PERD_DET_CD'
    AND LOOKUP_CODE = lifeEventsE0.ENRT_PERD_DET_OVRLP_BCKDT_CD
    ) RES_REINSTATEMENT_OVERRIDE_RUL
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_REINSTATE_OVRDN'
    AND LOOKUP_CODE = lifeEventsE0.REINSTATE_OVRDN_CD
    ) RES_PERIOD_DETERMINATION_RULE


,lifeEventsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,lifeEventsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,lifeEventsE0.CREATED_BY  RSC_CREATED_BY
,lifeEventsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPlansE0.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PL_F benPlansE0
,(SELECT NAME
	,PL_TYP_ID
    FROM BEN_PL_TYP_F
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND OPT_TYP_CD != 'FLXCR'
	) planTypesE0
,(SELECT *
	FROM BEN_POPL_ENRT_TYP_CYCL 
	WHERE COMP_OBJ_TYPE = 'PLN'
	--AND ENRT_TYP_CYCL_CD = 'L'
	) schedulPeriodsE0
,BEN_LEE_RSN_F lifeEventsE0
WHERE SYSDATE BETWEEN benPlansE0.EFFECTIVE_START_DATE AND benPlansE0.EFFECTIVE_END_DATE
AND benPlansE0.PL_TYP_ID = planTypesE0.PL_TYP_ID
AND benPlansE0.PL_ID = schedulPeriodsE0.PL_ID
AND schedulPeriodsE0.POPL_ENRT_TYP_CYCL_ID = lifeEventsE0.POPL_ENRT_TYP_CYCL_ID
AND benPlansE0.EFFECTIVE_END_DATE BETWEEN lifeEventsE0.EFFECTIVE_START_DATE AND lifeEventsE0.EFFECTIVE_END_DATE
ORDER BY benPlansE0.NAME
,benPlansE0.EFFECTIVE_START_DATE