/* ****************************************************************************
 * $Revision: 78895 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-06-29 15:34:19 +0700 (Wed, 29 Jun 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Plans%20-%20Dependent%20Life%20Event.sql $:
 * $Id: Manage Benefit Plans - Dependent Life Event.sql 78895 2022-06-29 08:34:19Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=BEN_PL_F
 
SELECT benPlansE0.NAME RES_PLAN_NAME
,TO_CHAR(benPlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ACTN_TYP'
    AND LOOKUP_CODE = dpntCertsE0.ACTN_TYP_CD
    ) RES_ACTION_ITEM
,TO_CHAR(dpntLesE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_LIFE_EVENT_EFFECTIVE_START
,DECODE(TO_CHAR(dpntLesE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY'),'31-12-4712',NULL,TO_CHAR(dpntLesE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_LIFE_EVENT_EFFECTIVE_END_D
,(SELECT NAME
    FROM BEN_LER_F
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    AND LER_ID = dpntLesE0.LER_ID
     ) RES_LIFE_EVENT
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_LER_CHG_DPNT_CVG'
    AND LOOKUP_CODE = dpntLesE0.LER_CHG_DPNT_CVG_CD
    ) RES_CHANGE_DEPENDENT_COVERAGE_
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = dpntLesE0.LER_CHG_DPNT_CVG_RL
    ) RES_CHANGE_DEPENDENT_COVERAG_0
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DPNT_CVG_STRT'
    AND LOOKUP_CODE = dpntLesE0.CVG_EFF_STRT_CD
    ) RES_DEPENDENT_COVERAGE_START_D
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DPNT_CVG_END'
    AND LOOKUP_CODE = dpntLesE0.CVG_EFF_END_CD
    ) RES_PREVIOUS_DEPENDENT_COVERAG
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = dpntLesE0.CVG_EFF_STRT_RL
    ) RES_DEPENDENT_COVERAGE_START_F
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = dpntLesE0.CVG_EFF_END_RL
    ) RES_PREVIOUS_DEPENDENT_COVER_1
,TO_CHAR(dpntCertsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_CERTIFICATION_EFFECTIVE_ST
,DECODE(TO_CHAR(dpntCertsE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY'),'31-12-4712',NULL,TO_CHAR(dpntCertsE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_CERTIFICATION_EFFECTIVE_EN
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ACTN_TYP_DUE_DT'
    AND LOOKUP_CODE = dpntCertsE0.ACTN_TYP_DUE_DT_CD
    ) RES_DUE_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = dpntCertsE0.ACTN_TYP_DUE_DT_RL
    ) RES_DUE_DATE_FORMULA
,DECODE(dpntCertsE0.SSPND_FLAG,'Y','Yes','No') RES_SUSPEND_ENROLLMENT
,DECODE(dpntCertsE0.RQD_FLAG,'Y','Yes','No') RES_REQUIRED
,dpntLesE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,dpntLesE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,dpntLesE0.CREATED_BY  RSC_CREATED_BY
,dpntLesE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPlansE0.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PL_F benPlansE0
,(SELECT NAME
	,PL_TYP_ID
    FROM BEN_PL_TYP_F
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND OPT_TYP_CD != 'FLXCR'
	) planTypesE0
,BEN_LER_CHG_DPNT_CVG_F dpntLesE0
,(SELECT *
    FROM BEN_LER_POPL_ACTN_TYP_F
    WHERE ACTN_TYP_LVL_CD = 'DPNTCTFN'
    ) dpntCertsE0
WHERE SYSDATE BETWEEN benPlansE0.EFFECTIVE_START_DATE AND benPlansE0.EFFECTIVE_END_DATE
AND benPlansE0.PL_TYP_ID = planTypesE0.PL_TYP_ID
AND benPlansE0.PL_ID = dpntLesE0.PL_ID
AND dpntLesE0.PL_ID = dpntCertsE0.PL_ID
AND dpntLesE0.LER_ID = dpntCertsE0.LER_ID
ORDER BY benPlansE0.NAME
,benPlansE0.EFFECTIVE_START_DATE