/* ****************************************************************************
 * $Revision: 75757 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2021-04-28 10:01:52 +0700 (Wed, 28 Apr 2021) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Actions%20-%20Action%20-%20DFF.sql $:
 * $Id: Manage Actions - Action - DFF.sql 75757 2021-04-28 03:01:52Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=QP_ROUNDING_RULES_VL
-- RSC_PREREQUISITE_OBJECTS=QP_ROUNDING_RULE_RANGES

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=667##RES##QP_ROUNDING_RULE_RANGES_FLEX
-- DFF_ATTRIBUTES=ATTRIBUTE_CHAR,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP
 
SELECT qpROUNDRULE0.NAME RES_NAME
,qpROUNDRANGE0.RANGE_LINE_NUMBER RES_RANGE_LINE_NUMBER
,qpROUNDRANGE0.RANGE_FROM RES_RANGE_FROM
,qpROUNDRANGE0.RANGE_TO RES_RANGE_TO
,qpROUNDRANGE0.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,qpROUNDRANGE0.ATTRIBUTE_CHAR1 
,qpROUNDRANGE0.ATTRIBUTE_CHAR2
,qpROUNDRANGE0.ATTRIBUTE_CHAR3
,qpROUNDRANGE0.ATTRIBUTE_CHAR4 
,qpROUNDRANGE0.ATTRIBUTE_CHAR5
,qpROUNDRANGE0.ATTRIBUTE_CHAR6 
,qpROUNDRANGE0.ATTRIBUTE_CHAR7 
,qpROUNDRANGE0.ATTRIBUTE_CHAR8 
,qpROUNDRANGE0.ATTRIBUTE_CHAR9 
,qpROUNDRANGE0.ATTRIBUTE_CHAR10 
,qpROUNDRANGE0.ATTRIBUTE_CHAR11
,qpROUNDRANGE0.ATTRIBUTE_CHAR12 
,qpROUNDRANGE0.ATTRIBUTE_CHAR13
,qpROUNDRANGE0.ATTRIBUTE_CHAR14 
,qpROUNDRANGE0.ATTRIBUTE_CHAR15 
,qpROUNDRANGE0.ATTRIBUTE_CHAR16 
,qpROUNDRANGE0.ATTRIBUTE_CHAR17 
,qpROUNDRANGE0.ATTRIBUTE_CHAR18 
,qpROUNDRANGE0.ATTRIBUTE_CHAR19 
,qpROUNDRANGE0.ATTRIBUTE_CHAR20
,qpROUNDRANGE0.ATTRIBUTE_NUMBER1
,qpROUNDRANGE0.ATTRIBUTE_NUMBER2
,qpROUNDRANGE0.ATTRIBUTE_NUMBER3
,qpROUNDRANGE0.ATTRIBUTE_NUMBER4
,qpROUNDRANGE0.ATTRIBUTE_NUMBER5
,qpROUNDRANGE0.ATTRIBUTE_NUMBER6
,qpROUNDRANGE0.ATTRIBUTE_NUMBER7
,qpROUNDRANGE0.ATTRIBUTE_NUMBER8
,qpROUNDRANGE0.ATTRIBUTE_NUMBER9
,qpROUNDRANGE0.ATTRIBUTE_NUMBER10
,TO_CHAR(qpROUNDRANGE0.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(qpROUNDRANGE0.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(qpROUNDRANGE0.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(qpROUNDRANGE0.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(qpROUNDRANGE0.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP1
,qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP2
,qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP3
,qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP4
,qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP5

,qpROUNDRANGE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,qpROUNDRANGE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,qpROUNDRANGE0.CREATED_BY RSC_CREATED_BY
,qpROUNDRANGE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM QP_ROUNDING_RULES_VL qpROUNDRULE0
,QP_ROUNDING_RULE_RANGES qpROUNDRANGE0
WHERE qpROUNDRULE0.ROUNDING_RULE_ID = qpROUNDRANGE0.ROUNDING_RULE_ID 
AND (qpROUNDRANGE0.ATTRIBUTE_CATEGORY IS NOT NULL OR
qpROUNDRANGE0.ATTRIBUTE_CHAR1 IS NOT NULL OR
qpROUNDRANGE0.ATTRIBUTE_CHAR2 IS NOT NULL OR
qpROUNDRANGE0.ATTRIBUTE_CHAR3 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR4 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR5 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR6 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR7 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR8 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR9 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR10 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR11 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR12 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR13 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR14 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR15 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR16 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR17 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR18 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR19 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_CHAR20 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_DATE1 IS NOT NULL OR
qpROUNDRANGE0.ATTRIBUTE_DATE2 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_DATE3 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_DATE4 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_DATE5 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP1 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP2 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP3 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP4 IS NOT NULL OR 
qpROUNDRANGE0.ATTRIBUTE_TIMESTAMP5 IS NOT NULL  
)
ORDER BY qpROUNDRULE0.NAME,qpROUNDRANGE0.RANGE_LINE_NUMBER,qpROUNDRANGE0.RANGE_FROM