/* ****************************************************************************
 * $Revision: 73232 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2020-01-17 14:24:29 +0700 (Fri, 17 Jan 2020) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Values%20Defined%20by%20Criteria%20-%20Criteria%20and%20Values.sql $:
 * $Id: Manage Values Defined by Criteria - Criteria and Values.sql 73232 2020-01-17 07:24:29Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */ 
 
 -- RSC_PREREQUISITE_OBJECTS=PAY_VALUE_DEFINITIONS_F 
 -- RSC_PREREQUISITE_OBJECTS=PAY_RANGE_ITEMS_F
 
 
WITH tmpPAY AS 
 (SELECT payVALUESDEFINIEO.*
,payVALUESDEFINITLEO.NAME
,payVALUESDEFINITLEO.DISPLAY_TAG
,NVL((SELECT DESCRIPTION FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = payVALUESDEFINIEO.DATABASE_ITEM_ID)
	,(SELECT USER_NAME FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = payVALUESDEFINIEO.DATABASE_ITEM_ID)) DB_DESC
,tmpITEMEO.PROMPT
,tmpITEMEO.TYPE
,tmpITEMEO.LEGISLATIVE_DATA_GROUP_ID AS ITEM_LEGIS
,tmpITEMEO.LEGISLATION_CODE AS ITEM_LEGIS_CODE
,tmpITEMEO.EFFECTIVE_START_DATE AS ITEM_START_DATE
,tmpITEMEO.EFFECTIVE_END_DATE AS ITEM_END_DATE
,tmpUSAGEES.EFFECTIVE_START_DATE AS USAGEES_START_DATE
,tmpUSAGEES.EFFECTIVE_END_DATE AS USAGEES_END_DATE
,tmpUSAGEES.VALUE_SET_CODE AS USAGEES_VALUE_SET_CODE
,tmpUSAGEES.DIR_CARD_COMP_DEF_ID
,tmpUSAGEES.DIR_OVERRIDE_USAGE_ID AS USAGEES_ID
,payDIRCARDCOMPEO.DIR_CARD_DEFINITION_ID
,payDIRCARDCOMPEO.COMPONENT_NAME
,tmpUSAGEES.CREATED_BY AS ITEM_CRE_BY
,tmpUSAGEES.CREATION_DATE AS ITEM_CRE_DATE
,tmpUSAGEES.LAST_UPDATE_DATE AS ITEM_LAST_DATE
,tmpUSAGEES.LAST_UPDATED_BY AS ITEM_LAST_BY
								FROM PAY_VALUE_DEFINITIONS_F payVALUESDEFINIEO
								,PAY_VALUE_DEFINITIONS_TL payVALUESDEFINITLEO
								,PAY_ALLOW_OVERRIDES_VL tmpITEMEO
								,PAY_DIR_OVERRIDE_USAGES_F tmpUSAGEES
								,PAY_DIR_CARD_COMP_DEFS_VL payDIRCARDCOMPEO
								WHERE payVALUESDEFINITLEO.LANGUAGE = USERENV('LANG')
								AND payVALUESDEFINIEO.VALUE_DEFN_ID = payVALUESDEFINITLEO.VALUE_DEFN_ID
								AND payVALUESDEFINIEO.VALUE_DEFN_ID = tmpITEMEO.VALUE_DEFN_ID
								AND tmpITEMEO.ALLOW_OVERRIDES_ID = tmpUSAGEES.ALLOW_OVERRIDES_ID
								AND tmpUSAGEES.DIR_CARD_COMP_DEF_ID = payDIRCARDCOMPEO.DIR_CARD_COMP_DEF_ID 
								AND payVALUESDEFINIEO.EFFECTIVE_END_DATE BETWEEN tmpITEMEO.EFFECTIVE_START_DATE AND tmpITEMEO.EFFECTIVE_END_DATE
								AND payVALUESDEFINIEO.EFFECTIVE_END_DATE BETWEEN tmpUSAGEES.EFFECTIVE_START_DATE AND tmpUSAGEES.EFFECTIVE_END_DATE
								AND payVALUESDEFINIEO.DEFAULT_FLAG IS NULL)
,chkITEME0 AS
(SELECT tmpITEMEO.RANGE_ITEM_ID,tmpITEMEO.VALUE_DEFN_ID,tmpITEMEO.CALC_TYPE_ID ,row_number () over (
           partition by VALUE_DEFN_ID
           order by LOW_VALUE 
         ) chkNUM
FROM PAY_RANGE_ITEMS_F tmpITEMEO 
)
,TreeE0 AS 
(SELECT DISTINCT payVALUESDEFINIEO.VALUE_DEFN_ID
,payVALUESDEFINIEO.EFFECTIVE_START_DATE
,payVALUESDEFINIEO.EFFECTIVE_END_DATE
,SUBSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,1)+3,INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,2)-4)  PK1
,SUBSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,2)+3,INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,3) - INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,2)-3) PK2
,SUBSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,3)+3,INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,4) - INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,3)-3) PK3
,SUBSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,4)+3,INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,5) - INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,4)-3) PK4
,SUBSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,5)+3,INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,6) - INSTR(SYS_CONNECT_BY_PATH(payVALUESDEFINIEO.VALUE_DEFN_ID,'###'),'###',1,5)-3) PK5
,LEVEL AS TreeLVL
FROM PAY_VALUE_DEFINITIONS_F payVALUESDEFINIEO
START WITH payVALUESDEFINIEO.CALC_TYPE_ID = (SELECT CALC_TYPE_ID FROM PAY_CALC_TYPES_VL payCAL WHERE payCAL.NAME LIKE 'Value By Criteria' ) 
CONNECT BY PRIOR payVALUESDEFINIEO.VALUE_DEFN_ID = payVALUESDEFINIEO.PARENT_VALUE_DEFN_ID)


SELECT 	RES_NAME
,RES_EFFECTIVE_START_DATE
,RES_PARENT_1
,RES_PARENT_2
,RES_PARENT_3
,RES_PARENT_4
,RES_PARENT_5
,RES_CRITERIA_OR_VALUE_DISPLAYE
,RES_CALCULATION_VALUE_DEFINITI
,RES_CALCULATION_VALUE_DEFINI_0
,RES_VALUE_START_DATE
,RES_ENTERABLE_VALUE_TYPE
,RES_ENTERABLE_DISPLAY_VALUE
,RES_USAGE_RULE_CALCULATION_CAR
,RES_USAGE_RULE_CALCULATION_COM
,RES_USAGE_RULE_VALUE_SET
,RES_USAGE_RULE_START_DATE
,RES_USAGE_RULE_END_DATE

,RSC_LAST_UPDATED_BY
,RSC_LAST_UPDATE_DATE
,RSC_CREATED_BY
,RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM
(SELECT (SELECT NAME FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK1 AND LANGUAGE = USERENV('LANG')) RES_NAME
,(SELECT EFFECTIVE_START_DATE FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK1 
	AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) RES_EFFECTIVE_START_DATE
,(SELECT NAME FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK1 AND LANGUAGE = USERENV('LANG')) RES_PARENT_1
,(CASE
	WHEN TreeE0.PK2_DEF = 'Y'
	THEN 'Default Criteria'
    WHEN TreeE0.PK2_DISPLAY IS NULL AND TreeE0.PK2_LOW IS NOT NULL AND TreeE0.PK2_VSCODE IS NULL AND TreeE0.PK2_EXPRESS <> 'IN'
	THEN TreeE0.PK2_DB_DESC||' '||TreeE0.PK2_EXPRESS||' '||TreeE0.PK2_LOW
	WHEN TreeE0.PK2_DISPLAY IS NOT NULL AND TreeE0.PK2_LOW IS NOT NULL AND TreeE0.PK2_VSCODE IS NULL AND TreeE0.PK2_EXPRESS <> 'IN'
	THEN TreeE0.PK2_DISPLAY||' '||TreeE0.PK2_EXPRESS||' '||TreeE0.PK2_LOW
	WHEN TreeE0.PK2_DISPLAY IS NULL AND TreeE0.PK2_LOW IS NOT NULL AND TreeE0.PK2_VSCODE IS NOT NULL AND TreeE0.PK2_EXPRESS <> 'IN'
	THEN TreeE0.PK2_DB_DESC||' '||TreeE0.PK2_EXPRESS||' '||'###R4C###'||TreeE0.PK2_VSCODE||'###R4CVS###'||TreeE0.PK2_LOW||'###R4C###'
	WHEN TreeE0.PK2_DISPLAY IS NOT NULL AND TreeE0.PK2_LOW IS NOT NULL AND TreeE0.PK2_VSCODE IS NOT NULL AND TreeE0.PK2_EXPRESS <> 'IN'
	THEN TreeE0.PK2_DISPLAY||' '||TreeE0.PK2_EXPRESS||' '||'###R4C###'||TreeE0.PK2_VSCODE||'###R4CVS###'||TreeE0.PK2_LOW||'###R4C###'
	WHEN TreeE0.PK2_DISPLAY IS NULL AND TreeE0.PK2_LOW IS NOT NULL AND TreeE0.PK2_VSCODE IS NOT NULL AND TreeE0.PK2_EXPRESS = 'IN'
	THEN TreeE0.PK2_DB_DESC||' In ('||'###R4C###'||PK2_VSCODE||'###R4CVS###'||(SELECT LISTAGG(TreeE0.PK2_LOW,'###R4CVS###') WITHIN GROUP (ORDER BY VALUE_DEFN_ID) FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK2)||'###R4C###)'
	WHEN TreeE0.PK2_DISPLAY IS NOT NULL AND TreeE0.PK2_LOW IS NOT NULL AND TreeE0.PK2_VSCODE IS NOT NULL AND TreeE0.PK2_EXPRESS = 'IN'
	THEN TreeE0.PK2_DISPLAY||' In ('||'###R4C###'||PK2_VSCODE||'###R4CVS###'||(SELECT LISTAGG(TreeE0.PK2_LOW,'###R4CVS###') WITHIN GROUP (ORDER BY VALUE_DEFN_ID) FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK2)||'###R4C###)'
	END) RES_PARENT_2
,(CASE
	WHEN TreeE0.PK3_DEF = 'Y'
	THEN 'Default Criteria'
    WHEN TreeE0.PK3_DISPLAY IS NULL AND TreeE0.PK3_LOW IS NOT NULL AND TreeE0.PK3_VSCODE IS NULL AND TreeE0.PK3_EXPRESS <> 'IN'
	THEN TreeE0.PK3_DB_DESC||' '||TreeE0.PK3_EXPRESS||' '||TreeE0.PK3_LOW
	WHEN TreeE0.PK3_DISPLAY IS NOT NULL AND TreeE0.PK3_LOW IS NOT NULL AND TreeE0.PK3_VSCODE IS NULL AND TreeE0.PK3_EXPRESS <> 'IN'
	THEN TreeE0.PK3_DISPLAY||' '||TreeE0.PK3_EXPRESS||' '||TreeE0.PK3_LOW
	WHEN TreeE0.PK3_DISPLAY IS NULL AND TreeE0.PK3_LOW IS NOT NULL AND TreeE0.PK3_VSCODE IS NOT NULL AND TreeE0.PK3_EXPRESS <> 'IN'
	THEN TreeE0.PK3_DB_DESC||' '||TreeE0.PK3_EXPRESS||' '||'###R4C###'||TreeE0.PK3_VSCODE||'###R4CVS###'||TreeE0.PK3_LOW||'###R4C###'
	WHEN TreeE0.PK3_DISPLAY IS NOT NULL AND TreeE0.PK3_LOW IS NOT NULL AND TreeE0.PK3_VSCODE IS NOT NULL AND TreeE0.PK3_EXPRESS <> 'IN'
	THEN TreeE0.PK3_DISPLAY||' '||TreeE0.PK3_EXPRESS||' '||'###R4C###'||TreeE0.PK3_VSCODE||'###R4CVS###'||TreeE0.PK3_LOW||'###R4C###'
	WHEN TreeE0.PK3_DISPLAY IS NULL AND TreeE0.PK3_LOW IS NOT NULL AND TreeE0.PK3_VSCODE IS NOT NULL AND TreeE0.PK3_EXPRESS = 'IN'
	THEN TreeE0.PK3_DB_DESC||' In ('||'###R4C###'||PK3_VSCODE||'###R4CVS###'||(SELECT LISTAGG(TreeE0.PK3_LOW,'###R4CVS###') WITHIN GROUP (ORDER BY VALUE_DEFN_ID) FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK3)||'###R4C###)'
	WHEN TreeE0.PK3_DISPLAY IS NOT NULL AND TreeE0.PK3_LOW IS NOT NULL AND TreeE0.PK3_VSCODE IS NOT NULL AND TreeE0.PK3_EXPRESS = 'IN'
	THEN TreeE0.PK3_DISPLAY||' In ('||'###R4C###'||PK3_VSCODE||'###R4CVS###'||(SELECT LISTAGG(TreeE0.PK3_LOW,'###R4CVS###') WITHIN GROUP (ORDER BY VALUE_DEFN_ID) FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK3)||'###R4C###)'
	END) RES_PARENT_3
,(CASE
	WHEN TreeE0.PK4_DEF = 'Y'
	THEN 'Default Criteria'
    WHEN TreeE0.PK4_DISPLAY IS NULL AND TreeE0.PK4_LOW IS NOT NULL AND TreeE0.PK4_VSCODE IS NULL AND TreeE0.PK4_EXPRESS <> 'IN'
	THEN TreeE0.PK4_DB_DESC||' '||TreeE0.PK4_EXPRESS||' '||TreeE0.PK4_LOW
	WHEN TreeE0.PK4_DISPLAY IS NOT NULL AND TreeE0.PK4_LOW IS NOT NULL AND TreeE0.PK4_VSCODE IS NULL AND TreeE0.PK4_EXPRESS <> 'IN'
	THEN TreeE0.PK4_DISPLAY||' '||TreeE0.PK4_EXPRESS||' '||TreeE0.PK4_LOW
	WHEN TreeE0.PK4_DISPLAY IS NULL AND TreeE0.PK4_LOW IS NOT NULL AND TreeE0.PK4_VSCODE IS NOT NULL AND TreeE0.PK4_EXPRESS <> 'IN'
	THEN TreeE0.PK4_DB_DESC||' '||TreeE0.PK4_EXPRESS||' '||'###R4C###'||TreeE0.PK4_VSCODE||'###R4CVS###'||TreeE0.PK4_LOW||'###R4C###'
	WHEN TreeE0.PK4_DISPLAY IS NOT NULL AND TreeE0.PK4_LOW IS NOT NULL AND TreeE0.PK4_VSCODE IS NOT NULL AND TreeE0.PK4_EXPRESS <> 'IN'
	THEN TreeE0.PK4_DISPLAY||' '||TreeE0.PK4_EXPRESS||' '||'###R4C###'||TreeE0.PK4_VSCODE||'###R4CVS###'||TreeE0.PK4_LOW||'###R4C###'
	WHEN TreeE0.PK4_DISPLAY IS NULL AND TreeE0.PK4_LOW IS NOT NULL AND TreeE0.PK4_VSCODE IS NOT NULL AND TreeE0.PK4_EXPRESS = 'IN'
	THEN TreeE0.PK4_DB_DESC||' In ('||'###R4C###'||PK4_VSCODE||'###R4CVS###'||(SELECT LISTAGG(TreeE0.PK4_LOW,'###R4CVS###') WITHIN GROUP (ORDER BY VALUE_DEFN_ID) FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK4)||'###R4C###)'
	WHEN TreeE0.PK4_DISPLAY IS NOT NULL AND TreeE0.PK4_LOW IS NOT NULL AND TreeE0.PK4_VSCODE IS NOT NULL AND TreeE0.PK4_EXPRESS = 'IN'
	THEN TreeE0.PK4_DISPLAY||' In ('||'###R4C###'||PK4_VSCODE||'###R4CVS###'||(SELECT LISTAGG(TreeE0.PK4_LOW,'###R4CVS###') WITHIN GROUP (ORDER BY VALUE_DEFN_ID) FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK4)||'###R4C###)'
	END) RES_PARENT_4
,(CASE
	WHEN TreeE0.PK5_DEF = 'Y'
	THEN 'Default Criteria'
    WHEN TreeE0.PK5_DISPLAY IS NULL AND TreeE0.PK5_LOW IS NOT NULL AND TreeE0.PK5_VSCODE IS NULL AND TreeE0.PK5_EXPRESS <> 'IN'
	THEN TreeE0.PK5_DB_DESC||' '||TreeE0.PK5_EXPRESS||' '||TreeE0.PK5_LOW
	WHEN TreeE0.PK5_DISPLAY IS NOT NULL AND TreeE0.PK5_LOW IS NOT NULL AND TreeE0.PK5_VSCODE IS NULL AND TreeE0.PK5_EXPRESS <> 'IN'
	THEN TreeE0.PK5_DISPLAY||' '||TreeE0.PK5_EXPRESS||' '||TreeE0.PK5_LOW
	WHEN TreeE0.PK5_DISPLAY IS NULL AND TreeE0.PK5_LOW IS NOT NULL AND TreeE0.PK5_VSCODE IS NOT NULL AND TreeE0.PK5_EXPRESS <> 'IN'
	THEN TreeE0.PK5_DB_DESC||' '||TreeE0.PK5_EXPRESS||' '||'###R4C###'||TreeE0.PK5_VSCODE||'###R4CVS###'||TreeE0.PK5_LOW||'###R4C###'
	WHEN TreeE0.PK5_DISPLAY IS NOT NULL AND TreeE0.PK5_LOW IS NOT NULL AND TreeE0.PK5_VSCODE IS NOT NULL AND TreeE0.PK5_EXPRESS <> 'IN'
	THEN TreeE0.PK5_DISPLAY||' '||TreeE0.PK5_EXPRESS||' '||'###R4C###'||TreeE0.PK5_VSCODE||'###R4CVS###'||TreeE0.PK5_LOW||'###R4C###'
	WHEN TreeE0.PK5_DISPLAY IS NULL AND TreeE0.PK5_LOW IS NOT NULL AND TreeE0.PK5_VSCODE IS NOT NULL AND TreeE0.PK5_EXPRESS = 'IN'
	THEN TreeE0.PK5_DB_DESC||' In ('||'###R4C###'||PK5_VSCODE||'###R4CVS###'||(SELECT LISTAGG(TreeE0.PK5_LOW,'###R4CVS###') WITHIN GROUP (ORDER BY VALUE_DEFN_ID) FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK5)||'###R4C###)'
	WHEN TreeE0.PK5_DISPLAY IS NOT NULL AND TreeE0.PK5_LOW IS NOT NULL AND TreeE0.PK5_VSCODE IS NOT NULL AND TreeE0.PK5_EXPRESS = 'IN'
	THEN TreeE0.PK5_DISPLAY||' In ('||'###R4C###'||PK5_VSCODE||'###R4CVS###'||(SELECT LISTAGG(TreeE0.PK5_LOW,'###R4CVS###') WITHIN GROUP (ORDER BY VALUE_DEFN_ID) FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK5)||'###R4C###)'
	END) RES_PARENT_5
,(CASE WHEN tmpPAY.VALUE_IDENTIFIER IS NOT NULL
	THEN tmpPAY.VALUE_IDENTIFIER
	ELSE tmpPAY.NAME END) RES_CRITERIA_OR_VALUE_DISPLAYE
,'Value' RES_CALCULATION_VALUE_DEFINITI
,tmpPAY.NAME RES_CALCULATION_VALUE_DEFINI_0
,TO_CHAR(tmpPAY.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_VALUE_START_DATE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = tmpPAY.TYPE
	AND LOOKUP_TYPE = 'PAY_DED_OVERRIDE_TYPE' AND LANGUAGE = USERENV('LANG')) RES_ENTERABLE_VALUE_TYPE
,tmpPAY.PROMPT RES_ENTERABLE_DISPLAY_VALUE
,(SELECT DISPLAY_NAME FROM PAY_DIR_CARD_DEFINITIONS_VL WHERE DIR_CARD_DEFINITION_ID =tmpPAY.DIR_CARD_DEFINITION_ID) RES_USAGE_RULE_CALCULATION_CAR
,tmpPAY.COMPONENT_NAME RES_USAGE_RULE_CALCULATION_COM
,tmpPAY.USAGEES_VALUE_SET_CODE RES_USAGE_RULE_VALUE_SET
,TO_CHAR(tmpPAY.USAGEES_START_DATE,'DD-Mon-YYYY') RES_USAGE_RULE_START_DATE
,TO_CHAR(tmpPAY.USAGEES_END_DATE,'DD-Mon-YYYY') RES_USAGE_RULE_END_DATE

,tmpPAY.ITEM_LAST_BY RSC_LAST_UPDATED_BY
,tmpPAY.ITEM_LAST_DATE RSC_LAST_UPDATE_DATE
,tmpPAY.ITEM_CRE_BY RSC_CREATED_BY
,tmpPAY.ITEM_CRE_DATE RSC_CREATION_DATE
,TreeE0.TreeLVL RES_LEVEL

FROM  tmpPAY
,(SELECT TreeE0.VALUE_DEFN_ID
,TreeE0.EFFECTIVE_START_DATE
,TreeE0.EFFECTIVE_END_DATE
,TreeE0.TreeLVL
,PK1
,PK2
,PK3
,PK4
,PK5
,(SELECT DEFAULT_FLAG FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK2 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK2_DEF
,(SELECT VALUE_SET_CODE1 FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK2 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK2_VSCODE
,(SELECT EXPRESSION FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK2 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK2_EXPRESS
,(SELECT NAME FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK2 AND LANGUAGE = USERENV('LANG')) PK2_NAME
,(SELECT DISPLAY_TAG FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK2 AND LANGUAGE = USERENV('LANG')) PK2_DISPLAY
,NVL((SELECT DESCRIPTION FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = (SELECT DATABASE_ITEM_ID FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK2 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE))
	,(SELECT USER_NAME FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = (SELECT DATABASE_ITEM_ID FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK2 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE))) PK2_DB_DESC
,(SELECT LOW_VALUE_TEXT FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK2 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND RANGE_ITEM_ID = (SELECT RANGE_ITEM_ID FROM chkITEME0 WHERE VALUE_DEFN_ID = TreeE0.PK2 AND chkNUM = 1)) PK2_LOW
,(SELECT DEFAULT_FLAG FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK3 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK3_DEF
,(SELECT VALUE_SET_CODE1 FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK3 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK3_VSCODE
,(SELECT EXPRESSION FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK3 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK3_EXPRESS
,(SELECT NAME FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK3 AND LANGUAGE = USERENV('LANG')) PK3_NAME
,(SELECT DISPLAY_TAG FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK3 AND LANGUAGE = USERENV('LANG')) PK3_DISPLAY
,NVL((SELECT DESCRIPTION FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = (SELECT DATABASE_ITEM_ID FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK3 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE))
	,(SELECT USER_NAME FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = (SELECT DATABASE_ITEM_ID FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK3 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE))) PK3_DB_DESC
,(SELECT LOW_VALUE_TEXT FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK3 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND RANGE_ITEM_ID = (SELECT RANGE_ITEM_ID FROM chkITEME0 WHERE VALUE_DEFN_ID = TreeE0.PK3 AND chkNUM = 1)) PK3_LOW
,(SELECT DEFAULT_FLAG FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK4 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK4_DEF
,(SELECT VALUE_SET_CODE1 FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK4 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK4_VSCODE
,(SELECT EXPRESSION FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK4 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK4_EXPRESS
,(SELECT NAME FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK4 AND LANGUAGE = USERENV('LANG')) PK4_NAME
,(SELECT DISPLAY_TAG FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK4 AND LANGUAGE = USERENV('LANG')) PK4_DISPLAY
,NVL((SELECT DESCRIPTION FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = (SELECT DATABASE_ITEM_ID FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK4 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE))
	,(SELECT USER_NAME FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = (SELECT DATABASE_ITEM_ID FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK4 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE))) PK4_DB_DESC
,(SELECT LOW_VALUE_TEXT FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK4 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND RANGE_ITEM_ID = (SELECT RANGE_ITEM_ID FROM chkITEME0 WHERE VALUE_DEFN_ID = TreeE0.PK4 AND chkNUM = 1)) PK4_LOW
,(SELECT DEFAULT_FLAG FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK5 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK5_DEF
,(SELECT VALUE_SET_CODE1 FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK5 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK5_VSCODE
,(SELECT EXPRESSION FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK5 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) PK5_EXPRESS
,(SELECT NAME FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK5 AND LANGUAGE = USERENV('LANG')) PK5_NAME
,(SELECT DISPLAY_TAG FROM PAY_VALUE_DEFINITIONS_TL WHERE VALUE_DEFN_ID = TreeE0.PK5 AND LANGUAGE = USERENV('LANG')) PK5_DISPLAY
,NVL((SELECT DESCRIPTION FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = (SELECT DATABASE_ITEM_ID FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK5 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE))
	,(SELECT USER_NAME FROM FF_DATABASE_ITEMS_VL WHERE DATABASE_ITEM_ID = (SELECT DATABASE_ITEM_ID FROM PAY_VALUE_DEFINITIONS_F WHERE VALUE_DEFN_ID = TreeE0.PK5 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE))) PK5_DB_DESC
,(SELECT LOW_VALUE_TEXT FROM PAY_RANGE_ITEMS_F WHERE VALUE_DEFN_ID = TreeE0.PK5 AND TreeE0.EFFECTIVE_START_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND RANGE_ITEM_ID = (SELECT RANGE_ITEM_ID FROM chkITEME0 WHERE VALUE_DEFN_ID = TreeE0.PK5 AND chkNUM = 1)) PK5_LOW
FROM TreeE0
) TreeE0
WHERE tmpPAY.VALUE_DEFN_ID = TreeE0.VALUE_DEFN_ID
AND tmpPAY.EFFECTIVE_START_DATE = TreeE0.EFFECTIVE_START_DATE
--AND (tmpPAY.EXPRESSION IS NULL OR tmpPAY.EXPRESSION <> 'IN')
ORDER BY RES_LEVEL,RES_PARENT_1,RES_CRITERIA_OR_VALUE_DISPLAYE,RES_USAGE_RULE_START_DATE
)

