/* ****************************************************************************
 * $Revision: 56510 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-07-06 09:21:36 +0700 (Wed, 06 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Locations%20(United%20States)%20-%20Manage%20Locations.sql $:
 * $Id: Manage Locations (United States) - Manage Locations.sql 56510 2016-07-06 02:21:36Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 SELECT xleENTITYPROFILES.NAME RES_LEGAL_ENTITY_NAME
,xleENTITYPROFILES.LEGAL_ENTITY_IDENTIFIER RES_LEGAL_ENTITY_IDENTIFIER
,hzPATIESE0.PARTY_NAME RES_CONTACT_NAME
,hzORGCONTACTE0.CONTACT_NUMBER RES_CONTACT_NUMBER
,hzPARTYSITE0.PARTY_SITE_NUMBER RES_SITE_NUMBER
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = hzPARTYSITEUSE0.SITE_USE_TYPE 
	AND LANGUAGE = USERENV('LANG') AND LOOKUP_TYPE = 'PARTY_SITE_USE_CODE' 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_PURPOSE
,TO_CHAR(hzPARTYSITEUSE0.BEGIN_DATE,'DD-Mon-YYYY') RES_FROM_DATE
,TO_CHAR(hzPARTYSITEUSE0.END_DATE,'DD-Mon-YYYY') RES_TO_DATE

,hzPARTYSITEUSE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hzPARTYSITEUSE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hzPARTYSITEUSE0.CREATED_BY RSC_CREATED_BY
,hzPARTYSITEUSE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FUSION.XLE_ENTITY_PROFILES xleENTITYPROFILES 
,HZ_RELATIONSHIPS hzRELATIONE0 
,HZ_ORG_CONTACTS hzORGCONTACTE0
,HZ_PARTIES hzPATIESE0
,HZ_PARTY_SITES hzPARTYSITE0
,HZ_PARTY_SITE_USES hzPARTYSITEUSE0

WHERE xleENTITYPROFILES.PARTY_ID = hzRELATIONE0.OBJECT_ID
AND hzRELATIONE0.RELATIONSHIP_ID = hzORGCONTACTE0.PARTY_RELATIONSHIP_ID
AND hzRELATIONE0.SUBJECT_ID = hzPATIESE0.PARTY_ID
AND hzPATIESE0.PARTY_ID = hzPARTYSITE0.PARTY_ID
AND hzPARTYSITE0.PARTY_SITE_ID = hzPARTYSITEUSE0.PARTY_SITE_ID
ORDER BY xleENTITYPROFILES.NAME,hzPATIESE0.PARTY_NAME
 