/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10011##RES##EGP_ITEM_REVISIONS_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.

SELECT 
(SELECT ITEM_CLASS_NAME
	FROM EGP_ITEM_CLASSES_VL
	WHERE ITEM_CLASS_ID = ItemClassPEO.PARENT_ITEM_CLASS_ID
	) RES_PARENT_ITEM_CLASS 
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,ItemRevisionEO.TEMPLATE_NAME RES_NAME
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemRevisionEO.ORGANIZATION_ID
	) RES_ORGANIZATION
,ItemRevisionEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ItemRevisionEO.ATTRIBUTE1
,ItemRevisionEO.ATTRIBUTE2
,ItemRevisionEO.ATTRIBUTE3
,ItemRevisionEO.ATTRIBUTE4
,ItemRevisionEO.ATTRIBUTE5
,ItemRevisionEO.ATTRIBUTE6
,ItemRevisionEO.ATTRIBUTE7
,ItemRevisionEO.ATTRIBUTE8
,ItemRevisionEO.ATTRIBUTE9
,ItemRevisionEO.ATTRIBUTE10
,ItemRevisionEO.ATTRIBUTE11
,ItemRevisionEO.ATTRIBUTE12
,ItemRevisionEO.ATTRIBUTE13
,ItemRevisionEO.ATTRIBUTE14
,ItemRevisionEO.ATTRIBUTE15
,ItemRevisionEO.ATTRIBUTE_NUMBER1
,ItemRevisionEO.ATTRIBUTE_NUMBER2
,ItemRevisionEO.ATTRIBUTE_NUMBER3
,ItemRevisionEO.ATTRIBUTE_NUMBER4
,ItemRevisionEO.ATTRIBUTE_NUMBER5
,ItemRevisionEO.ATTRIBUTE_NUMBER6
,ItemRevisionEO.ATTRIBUTE_NUMBER7
,ItemRevisionEO.ATTRIBUTE_NUMBER8
,ItemRevisionEO.ATTRIBUTE_NUMBER9
,ItemRevisionEO.ATTRIBUTE_NUMBER10
,TO_CHAR(ItemRevisionEO.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(ItemRevisionEO.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(ItemRevisionEO.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(ItemRevisionEO.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(ItemRevisionEO.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,ItemRevisionEO.ATTRIBUTE_TIMESTAMP1
,ItemRevisionEO.ATTRIBUTE_TIMESTAMP2
,ItemRevisionEO.ATTRIBUTE_TIMESTAMP3
,ItemRevisionEO.ATTRIBUTE_TIMESTAMP4
,ItemRevisionEO.ATTRIBUTE_TIMESTAMP5
,ItemRevisionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemRevisionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemRevisionEO.CREATED_BY RSC_CREATED_BY
,ItemRevisionEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(SELECT BUSINESS_UNIT_ID
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemRevisionEO.ORGANIZATION_ID
	) RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,(CASE
	WHEN EXISTS
		(SELECT DISTINCT MASTER_ORGANIZATION_ID
			FROM INV_ORG_PARAMETERS
			WHERE MASTER_ORGANIZATION_ID = ItemRevisionEO.ORGANIZATION_ID)
	THEN NULL
	ELSE ItemRevisionEO.ORGANIZATION_ID
	END) RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
--,EGP_SYSTEM_ITEMS_V ItemVersionEO
,(SELECT B.INVENTORY_ITEM_ID, 
    B.ORGANIZATION_ID, 
    B.ATTRIBUTE_CATEGORY, 
    B.ATTRIBUTE1, 
    B.ATTRIBUTE2, 
    B.ATTRIBUTE3, 
    B.ATTRIBUTE4, 
    B.ATTRIBUTE5, 
    B.ATTRIBUTE6, 
    B.ATTRIBUTE7, 
    B.ATTRIBUTE8, 
    B.ATTRIBUTE9, 
    B.ATTRIBUTE10, 
    B.ATTRIBUTE11, 
    B.ATTRIBUTE12, 
    B.ATTRIBUTE13, 
    B.ATTRIBUTE14, 
    B.ATTRIBUTE15, 
    B.ATTRIBUTE_NUMBER1,
    B.ATTRIBUTE_NUMBER2,
    B.ATTRIBUTE_NUMBER3,
    B.ATTRIBUTE_NUMBER4,
    B.ATTRIBUTE_NUMBER5,
    B.ATTRIBUTE_NUMBER6,
    B.ATTRIBUTE_NUMBER7,
    B.ATTRIBUTE_NUMBER8,
    B.ATTRIBUTE_NUMBER9,
    B.ATTRIBUTE_NUMBER10,
    B.ATTRIBUTE_DATE1,
    B.ATTRIBUTE_DATE2,
    B.ATTRIBUTE_DATE3,
    B.ATTRIBUTE_DATE4,
    B.ATTRIBUTE_DATE5,
    B.ATTRIBUTE_TIMESTAMP1,
    B.ATTRIBUTE_TIMESTAMP2,
    B.ATTRIBUTE_TIMESTAMP3,
    B.ATTRIBUTE_TIMESTAMP4,
    B.ATTRIBUTE_TIMESTAMP5,
    B.CREATION_DATE, 
    B.CREATED_BY, 
    B.LAST_UPDATE_DATE, 
    B.LAST_UPDATED_BY
	,ItemVersionEO.TEMPLATE_NAME
	,ItemVersionEO.ITEM_CATALOG_GROUP_ID
	FROM EGP_ITEM_REVISIONS_B B 
	,EGP_SYSTEM_ITEMS_V ItemVersionEO
	WHERE ItemVersionEO.INVENTORY_ITEM_ID = B.INVENTORY_ITEM_ID
	AND ItemVersionEO.ORGANIZATION_ID = B.ORGANIZATION_ID
	AND ItemVersionEO.TEMPLATE_ITEM_FLAG = 'Y'
	AND (B.ATTRIBUTE_CATEGORY  IS NOT NULL
		OR B.ATTRIBUTE1           IS NOT NULL
		OR B.ATTRIBUTE2           IS NOT NULL
		OR B.ATTRIBUTE3           IS NOT NULL
		OR B.ATTRIBUTE4           IS NOT NULL
		OR B.ATTRIBUTE5           IS NOT NULL
		OR B.ATTRIBUTE6           IS NOT NULL
		OR B.ATTRIBUTE7           IS NOT NULL
		OR B.ATTRIBUTE8           IS NOT NULL
		OR B.ATTRIBUTE9           IS NOT NULL
		OR B.ATTRIBUTE10          IS NOT NULL
		OR B.ATTRIBUTE11          IS NOT NULL
		OR B.ATTRIBUTE12          IS NOT NULL
		OR B.ATTRIBUTE13          IS NOT NULL
		OR B.ATTRIBUTE14          IS NOT NULL
		OR B.ATTRIBUTE15          IS NOT NULL
		OR B.ATTRIBUTE_NUMBER1    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER2    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER3    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER4    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER5    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER6    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER7    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER8    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER9    IS NOT NULL
		OR B.ATTRIBUTE_NUMBER10   IS NOT NULL
		OR B.ATTRIBUTE_DATE1      IS NOT NULL
		OR B.ATTRIBUTE_DATE2      IS NOT NULL
		OR B.ATTRIBUTE_DATE3      IS NOT NULL
		OR B.ATTRIBUTE_DATE4      IS NOT NULL
		OR B.ATTRIBUTE_DATE5      IS NOT NULL
		OR B.ATTRIBUTE_TIMESTAMP1 IS NOT NULL
		OR B.ATTRIBUTE_TIMESTAMP2 IS NOT NULL
		OR B.ATTRIBUTE_TIMESTAMP3 IS NOT NULL
		OR B.ATTRIBUTE_TIMESTAMP4 IS NOT NULL
		OR B.ATTRIBUTE_TIMESTAMP5 IS NOT NULL)
	) ItemRevisionEO
WHERE /*ItemVersionEO.TEMPLATE_NAME IS NOT NULL
AND*/ ItemClassPEO.ITEM_CLASS_ID = ItemRevisionEO.ITEM_CATALOG_GROUP_ID
/*AND ItemVersionEO.INVENTORY_ITEM_ID = ItemRevisionEO.INVENTORY_ITEM_ID
AND ItemVersionEO.ORGANIZATION_ID = ItemRevisionEO.ORGANIZATION_ID*/
/*AND(ItemRevisionEO.ATTRIBUTE_CATEGORY  IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE1           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE2           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE3           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE4           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE5           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE6           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE7           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE8           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE9           IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE10          IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE11          IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE12          IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE13          IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE14          IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE15          IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER1    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER2    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER3    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER4    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER5    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER6    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER7    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER8    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER9    IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_NUMBER10   IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_DATE1      IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_DATE2      IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_DATE3      IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_DATE4      IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_DATE5      IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_TIMESTAMP1 IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_TIMESTAMP2 IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_TIMESTAMP3 IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_TIMESTAMP4 IS NOT NULL
OR ItemRevisionEO.ATTRIBUTE_TIMESTAMP5 IS NOT NULL)*/
CONNECT BY ItemClassPEO.PARENT_ITEM_CLASS_ID = ItemClassPEO.ITEM_CLASS_ID
ORDER SIBLINGS BY RES_PARENT_ITEM_CLASS,RES_ITEM_CLASS,RES_NAME