/* ****************************************************************************
* $Revision: 59117 $:
* $Author: nasrullah.dusenmahamad $:
* $Date: 2016-10-21 11:10:58 +0700 (Fri, 21 Oct 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Key%20Flexfields%20-%20Segment%20Labels.sql $:
* $Id: Manage Key Flexfields - Segment Labels.sql 59117 2016-10-21 04:10:58Z nasrullah.dusenmahamad $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=FOS_AGREEMENT_DEFINITION_VL
-- RSC_PREREQUISITE_OBJECTS=FOS_AGREEMENT_PTR_F

SELECT FosAgreementDefinitionE0.AGREEMENT_NUMBER RES_NAME
,FosAgreementDefinitionE0.PRIORITY RES_PRIORITY
,FosAgreementPtrFE0.PTR_NUMBER RES_LINE
,(CASE
	WHEN FosAgreementPtrFE0.TO_BU_ID = -1 THEN
		'All Business Units'
	ELSE
		(SELECT BU_NAME
		FROM FUN_ALL_BUSINESS_UNITS_V
		WHERE BU_ID = FosAgreementPtrFE0.TO_BU_ID
		AND SYSDATE BETWEEN DATE_FROM AND DATE_TO)
	END) RES_SELLING_BU
,(SELECT NAME
	FROM XLE_ENTITY_PROFILES
	WHERE LEGAL_ENTITY_ID = FosAgreementPtrFE0.TO_LE_ID
	) RES_SELLING_LEGAL_ENTITY
,(SELECT NAME 
	FROM HR_ORGANIZATION_V
	WHERE CLASSIFICATION_CODE = 'INV'
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND ORGANIZATION_ID = FosAgreementPtrFE0.FROM_TRADE_ORGANIZATION_ID 
	) RES_RECEIVING_TRADE_ORGANIZATI
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = FosAgreementPtrFE0.FROM_BU_ID
	AND SYSDATE BETWEEN DATE_FROM AND DATE_TO
	) RES_RECEIVING_BU
,(SELECT NAME
	FROM XLE_ENTITY_PROFILES
	WHERE LEGAL_ENTITY_ID = FosAgreementPtrFE0.FROM_LE_ID
	) RES_RECEIVING_LEGAL_ENTITY
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = OrganizationParameterEO.PROFIT_CENTER_BU_ID
	) RES_REQUISITION_BU
,TO_CHAR(FosAgreementPtrFE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(FosAgreementPtrFE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY'),'31-12-4712',NULL,TO_CHAR(FosAgreementPtrFE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,FosAgreementPtrFE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,FosAgreementPtrFE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,FosAgreementPtrFE0.CREATED_BY RSC_CREATED_BY
,FosAgreementPtrFE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FOS_AGREEMENT_DEFINITION_VL FosAgreementDefinitionE0
,FOS_AGREEMENT_PTR_F FosAgreementPtrFE0
,INV_ORG_PARAMETERS OrganizationParameterEO
WHERE FosAgreementDefinitionE0.AGREEMENT_TYPE = 'DROP_SHIP'
AND FosAgreementDefinitionE0.AGREEMENT_ID = FosAgreementPtrFE0.AGREEMENT_ID
AND FosAgreementPtrFE0.FROM_TRADE_ORGANIZATION_ID = OrganizationParameterEO.ORGANIZATION_ID
ORDER BY FosAgreementDefinitionE0.AGREEMENT_NUMBER
,FosAgreementPtrFE0.PTR_NUMBER