/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Capitalized%20Interest%20Rate%20Schedules%20-%20Rate%20Multipliers.sql $:
 * $Id: Manage Capitalized Interest Rate Schedules - Rate Multipliers.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT pjnRATESCHEO.RATE_SCH_NAME RES_NAME
,pjcCINTVEREO.RATE_SCH_REVISION RES_SCHEDULE_VERSION_NAME
,HROrgUNITEO.NAME RES_ORGANIZATION
,pjcCINTRNameEO.RATE_NAME RES_RATE_NAME
,'0'||pjcCINTMULEO.MULTIPLIER RES_MULTIPLIER
,pjcCINTMULEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,pjcCINTMULEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,pjcCINTMULEO.CREATED_BY RSC_CREATED_BY
,pjcCINTMULEO.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HR_ORGANIZATION_UNITS HROrgUNITEO
,PJC_CINT_RS_REVISIONS pjcCINTVEREO
,PJC_CINT_RATE_MULTPLRS pjcCINTMULEO
,PJC_CINT_RATE_NAMES pjcCINTRNameEO
,PJC_CINT_RATE_SCH_VL pjnRATESCHEO
WHERE pjnRATESCHEO.CINT_RATE_SCH_ID = pjcCINTVEREO.CINT_RATE_SCH_ID
AND pjcCINTVEREO.CINT_RS_REVISION_ID = pjcCINTMULEO.CINT_RS_REVISION_ID
AND pjcCINTMULEO.ORGANIZATION_ID = HROrgUNITEO.ORGANIZATION_ID
AND pjcCINTMULEO.RATE_NAME_ID = pjcCINTRNameEO.RATE_NAME_ID
ORDER BY pjnRATESCHEO.RATE_SCH_NAME
,pjcCINTVEREO.START_DATE_ACTIVE 
,HROrgUNITEO.NAME