/* ****************************************************************************
* $Revision:  $:
* $Author: Nasrullah Dusenmahamad $:
* $Date: 2017-03-17  $:
* $HeadURL: $:
* $Id: Manage Category Descriptive Flexfields - Context Segments $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT collapsE0.NAME RES_RULE_NAME
,collapsE0.SEQ RES_SEQUENCE_NUMBER
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'BEN_CLPSE_LER_DT'
	AND LOOKUP_CODE = collapsE0.EVAL_LER_DET_CD
	) RES_LIFE_EVENT_OCCURRED_DATE
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'BEN_CLPSE_CD'
	AND LOOKUP_CODE = collapsE0.CLPSE_CD
	) RES_CONFIGURATION_APPROACH
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'BEN_STAT'
	AND LOOKUP_CODE = collapsE0.STATUS_CD 
	) RES_STATUS
,collapsE0.TLRNC_DYS_NUM RES_PROXIMITY_DAYS
,(SELECT FORMULA_NAME
	FROM FF_FORMULAS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND FORMULA_ID = collapsE0.CLPSE_RL
	) RES_LIFE_EVENT_OCCURRED_DATE_F
,collapsE0.DESCRIPTION RES_DESCRIPTION

,(SELECT FORMULA_NAME
	FROM FF_FORMULAS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND FORMULA_ID = collapsE0.EVAL_LER_DET_RL 
	) RES_COLLAPSING_FORMULA
,(SELECT NAME
	FROM BEN_LER_F
	WHERE LER_ID = collapsE0.EVAL_LER_ID
	) RES_RESULTING_EVENT_NAME

,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'BEN_BOOL'
	AND LOOKUP_CODE = collapsE0.BOOL1_CD 
	) RES_OPERATOR
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'BEN_CLPSE_EVAL_CD'
	AND LOOKUP_CODE = collapsE0.EVAL_CD 
	) RES_HANDLING_OF_LOSING_EVENTS
,(SELECT FORMULA_NAME
	FROM FF_FORMULAS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND FORMULA_ID = collapsE0.EVAL_RL
	) RES_HANDLING_OF_LOSING_EVENTS_
,collapsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,collapsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,collapsE0.CREATED_BY RSC_CREATED_BY
,collapsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,collapsE0.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM BEN_CLPSE_LF_EVT collapsE0
ORDER BY collapsE0.SEQ