/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2017-11-16  $:
 * $HeadURL:  $:
 * $Id: Publish Account Hierarchies - Publish Account Hierarchies.sql  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT TO_CHAR(gradeRatesE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,legisDataGroupsE0.NAME RES_LEGISLATIVE_DATA_GROUP 
,gradeRatesE0.NAME RES_NAME
,(CASE
    WHEN rateValuesE0.RATE_OBJECT_TYPE = 'GRADE' THEN
        (SELECT NAME
            FROM PER_GRADES_F_TL
            WHERE LANGUAGE = USERENV('LANG')
            AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
            AND GRADE_ID = rateValuesE0.RATE_OBJECT_ID)
    WHEN rateValuesE0.RATE_OBJECT_TYPE = 'STEP' THEN
        (SELECT NAME
            FROM PER_GRADE_STEPS_F_TL
            WHERE LANGUAGE = USERENV('LANG')
            AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
            AND GRADE_STEP_ID = rateValuesE0.RATE_OBJECT_ID)
    END) RES_GRADE_NAME
,(CASE
    WHEN rateValuesE0.RATE_OBJECT_TYPE = 'GRADE' THEN
        (SELECT GRADE_CODE
            FROM PER_GRADES_F_VL
			WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
            AND GRADE_ID = rateValuesE0.RATE_OBJECT_ID) 
	END) RES_GRADE_CODE
,rateValuesE0.MINIMUM RES_MINIMUM
,rateValuesE0.MAXIMUM RES_MAXIMUM
,rateValuesE0.MID_VALUE RES_MIDPOINT
,rateValuesE0.VALUE RES_VALUE
,rateValuesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,rateValuesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,rateValuesE0.CREATED_BY RSC_CREATED_BY
,rateValuesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legisDataGroupsE0.LEGISLATION_CODE RSC_COUNTRY_ID

FROM PER_RATES_F_VL gradeRatesE0
,(SELECT LEGISLATIVE_DATA_GROUP_ID
    ,NAME
	,LEGISLATION_CODE
    FROM PER_LEGISLATIVE_DATA_GROUPS_VL
    ) legisDataGroupsE0
,PER_RATE_VALUES_F rateValuesE0
WHERE gradeRatesE0.RATE_OBJECT_TYPE= 'GRADE'
AND gradeRatesE0.LEGISLATIVE_DATA_GROUP_ID = legisDataGroupsE0.LEGISLATIVE_DATA_GROUP_ID
AND gradeRatesE0.RATE_ID = rateValuesE0.RATE_ID
AND gradeRatesE0.EFFECTIVE_START_DATE BETWEEN rateValuesE0.EFFECTIVE_START_DATE AND rateValuesE0.EFFECTIVE_END_DATE
ORDER BY legisDataGroupsE0.NAME
,gradeRatesE0.NAME
,gradeRatesE0.EFFECTIVE_START_DATE
,rateValuesE0.SEQUENCE
