/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Units%20of%20Measure%20-%20Manage%20Units%20of%20Measure.sql $:
 * $Id: Manage Units of Measure - Manage Units of Measure.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT UNITOFMEASUREEO.UOM_CODE RES_UOM_CODE
,UNITOFMEASUREEO.UNIT_OF_MEASURE RES_UOM_NAME
,UNITOFMEASUREEO.DESCRIPTION RES_DESCRIPTION
,QRSLT.UOM_CLASS_TL RES_CLASS_NAME
,QRSLT.BASE_UNIT_OF_MEASURE RES_BASE_UOM_NAME
,TO_CHAR(UNITOFMEASUREEO.DISABLE_DATE,'DD-Mon-YYYY') RES_END_DATE
,UNITOFMEASUREEO.UOM_RECIPROCAL_DESC RES_RECIPROCAL_DESCRIPTION
,UNITOFMEASUREEO.UOM_PLURAL_DESC RES_PLURAL_DESCRIPTION
,UNITOFMEASUREEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,UNITOFMEASUREEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
,UNITOFMEASUREEO.CREATED_BY  RSC_CREATED_BY
,UNITOFMEASUREEO.CREATION_DATE  RSC_CREATION_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
    
FROM INV_UNITS_OF_MEASURE_VL UNITOFMEASUREEO
,(SELECT UnitOfMeasureEO.UNIT_OF_MEASURE_ID
	, UnitOfMeasureClassEO.UOM_CLASS
	, UnitOfMeasureClassEO.UOM_CLASS_TL
	, UnitOfMeasureClassEO.DESCRIPTION
	, UnitOfMeasureClassEO.DISABLE_DATE         AS UOM_CLASS_DISABLE_DATE
	, NVL(UnitOfMeasureEO.UNIT_OF_MEASURE,'-1') AS BASE_UNIT_OF_MEASURE
	, UnitOfMeasureEO.UOM_CLASS                 AS UOM_CLASS_FOR_BASE_UOM
	, UnitOfMeasureEO.UOM_CODE                  AS UOM_CODE_FOR_BASE_UOM
	, UnitOfMeasureEO.BASE_UOM_FLAG
	FROM INV_UOM_CLASSES_VL UnitOfMeasureClassEO
	,INV_UNITS_OF_MEASURE_VL UnitOfMeasureEO
	WHERE UnitOfMeasureClassEO.UOM_CLASS = UnitOfMeasureEO.UOM_CLASS(+)
	AND(UnitOfMeasureEO.BASE_UOM_FLAG    = 'Y')
	ORDER BY UNITOFMEASURECLASSEO.UOM_CLASS_TL
	) QRSLT
WHERE UNITOFMEASUREEO.UOM_CLASS = QRSLT.UOM_CLASS(+)

ORDER BY UNITOFMEASUREEO.UNIT_OF_MEASURE