/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Aging%20Periods%20-%20Aging%20Period%20Details.sql $:
 * $Id: Manage Aging Periods - Aging Period Details.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


select APAGINGPERIODS.PERIOD_NAME RES_NAME
,APAGINGPERIODLINES.PERIOD_SEQUENCE_NUM RES_COLUMN_ORDER
,APAGINGPERIODLINES.DAYS_START RES_DAYS_FROM
,APAGINGPERIODLINES.DAYS_TO RES_DAYS_TO
,APAGINGPERIODLINES.REPORT_HEADING1 RES_COLUMN_HEADING_FIRST
,APAGINGPERIODLINES.REPORT_HEADING2 RES_COLUMN_HEADING_SECOND
,APAGINGPERIODLINES.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,APAGINGPERIODLINES.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,APAGINGPERIODLINES.CREATED_BY  RSC_CREATED_BY
,APAGINGPERIODLINES.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM AP_AGING_PERIODS ApAgingPeriods ,
AP_AGING_PERIOD_LINES APAGINGPERIODLINES
where APAGINGPERIODS.AGING_PERIOD_ID =	APAGINGPERIODLINES.AGING_PERIOD_ID 
ORDER BY ApAgingPeriods.PERIOD_NAME,ApAgingPeriodLines.PERIOD_SEQUENCE_NUM