/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Derived%20Factors%20-%20Compensation.sql $:
 * $Id: Manage Derived Factors - Compensation.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT benCOMPLVLEO.NAME RES_NAME
,(SELECT NAME FROM FND_CURRENCIES_VL
	WHERE CURRENCY_CODE = benCOMPLVLEO.COMP_LVL_UOM) RES_UNIT_OF_MEASURE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benCOMPLVLEO.COMP_SRC_CD
	AND LOOKUP_TYPE = 'BEN_COMP_SRC' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_SOURCE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benCOMPLVLEO.STTD_SAL_PRDCTY_CD
	AND LOOKUP_TYPE = 'BEN_ACTY_REF_PERD' AND LANGUAGE = USERENV('LANG')) RES_SOURCE_VALUE
,benCOMPLVLEO.MN_COMP_VAL RES_GREATER_THAN_OR_EQUAL_TO_C
,benCOMPLVLEO.MX_COMP_VAL RES_LESS_THAN_COMPENSATION
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benCOMPLVLEO.COMP_LVL_DET_CD
	AND LOOKUP_TYPE = 'BEN_AGE_DET' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_DETERMINATION_RULE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benCOMPLVLEO.COMP_LVL_DET_RL 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_DETERMINATION_FORMULA
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benCOMPLVLEO.RNDG_CD
	AND LOOKUP_TYPE = 'BEN_RNDG' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_ROUNDING_RULE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = benCOMPLVLEO.RNDG_RL 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_ROUNDING_FORMULA

,benCOMPLVLEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benCOMPLVLEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benCOMPLVLEO.CREATED_BY RSC_CREATED_BY
,benCOMPLVLEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,benCOMPLVLEO.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM BEN_COMP_LVL_FCTR benCOMPLVLEO
ORDER BY benCOMPLVLEO.NAME
