/* ****************************************************************************
* $Revision: 78229 $:
* $Author: pisan.jariyasettachok $:
* $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Position%20Security%20Profiles%20-%20Positions.sql $:
* $Id: Manage Position Security Profiles - Positions.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PER_POSITION_SECURITY_PROFILES
-- RSC_PREREQUISITE_OBJECTS=PER_POS_SEC_PROFILE_POSITIONS

SELECT posProfilesE0.NAME RES_NAME
,posE0.NAME RES_POSITION_NAME
,posE0.POSITION_CODE RES_POSITION_CODE
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = posE0.BUSINESS_UNIT_ID 
	) RES_POSITION_BUSINESS_UNIT
,NVL((SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'INCLUDE_EXCLUDE'
    AND LOOKUP_CODE = positionsE0.INCLUDE_EXCLUDE_FLAG
    ),'Include') RES_INCLUDE_OR_EXCLUDE_POSITIO
,positionsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,positionsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,positionsE0.CREATED_BY RSC_CREATED_BY
,positionsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
	
FROM PER_POSITION_SECURITY_PROFILES posProfilesE0
,PER_POS_SEC_PROFILE_POSITIONS positionsE0
,(SELECT POSITION_ID
	,NAME
	,POSITION_CODE
	,BUSINESS_UNIT_ID
	FROM HR_ALL_POSITIONS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	) posE0
WHERE posProfilesE0.POSITION_SECURITY_PROFILE_ID = positionsE0.POSITION_SECURITY_PROFILE_ID
AND positionsE0.POSITION_ID = posE0.POSITION_ID
ORDER BY posProfilesE0.NAME
,posE0.NAME