/* ****************************************************************************
* $Revision: 78229 $:
* $Author: pisan.jariyasettachok $:
* $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/
FINANCIALS/Manage%20Receivables%20Descriptive%20Flexfields%20-%20Manage%20Descriptive%20Flexfields.sql $:
* $Id: Manage Receivables Descriptive Flexfields - Manage Descriptive Flexfields.sql 53187 2016-03-01 11:52:21Z
dhara.pithadiya $:
* ****************************************************************************
* Description:
* ************************************************************************** */

WITH TMPpjsPERFTHRESEO AS 
	(SELECT THRES_OBJ_ID,FROM_VALUE,CURRENCY_CODE,INDICATOR_CODE,LAST_UPDATED_BY
	,LAST_UPDATE_DATE,CREATED_BY,CREATION_DATE,
	ROW_NUMBER() OVER (PARTITION BY THRES_OBJ_ID,CURRENCY_CODE ORDER BY FROM_VALUE ASC) AS ROW_NUM
	FROM PJS_PERF_THRESHOLDS )

SELECT pjsPERFRULEEO.RULE_NAME RES_KPI_NAME
,TMPpjsPERFTHRESEO.CURRENCY_CODE RES_CURRENCY_CODE
,TMPpjsPERFTHRESEO.FROM_VALUE RES_THRESHOLD
,'Greater than or equal to threshold' RES_KPI_VALUE_COMPARED_TO_THRE
,(SELECT MEANING FROM FND_LOOKUPS WHERE LOOKUP_CODE = TMPpjsPERFTHRESEO.INDICATOR_CODE 
	AND LOOKUP_TYPE = 'PJS_PERF_INDICATORS') RES_STATUS_INDICATOR

,TMPpjsPERFTHRESEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,TMPpjsPERFTHRESEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,TMPpjsPERFTHRESEO.CREATED_BY RSC_CREATED_BY
,TMPpjsPERFTHRESEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJS_PERF_RULES_VL pjsPERFRULEEO
,TMPpjsPERFTHRESEO
WHERE pjsPERFRULEEO.RULE_ID = TMPpjsPERFTHRESEO.THRES_OBJ_ID
AND pjsPERFRULEEO.MEASURE_FORMAT = 'CURRENCY'
AND pjsPERFRULEEO.THRESHOLD_LEVEL = 'S'
AND TMPpjsPERFTHRESEO.ROW_NUM = 2
AND SYSDATE BETWEEN pjsPERFRULEEO.START_DATE_ACTIVE AND NVL(pjsPERFRULEEO.END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))

UNION

SELECT pjsPERFRULEEO.RULE_NAME RES_KPI_NAME
,TMPpjsPERFTHRESEO.CURRENCY_CODE RES_CURRENCY_CODE
,TMP1.FROM_VALUE RES_THRESHOLD
,'Less than threshold' RES_KPI_VALUE_COMPARED_TO_THRE
,(SELECT MEANING FROM FND_LOOKUPS WHERE LOOKUP_CODE = TMPpjsPERFTHRESEO.INDICATOR_CODE 
	AND LOOKUP_TYPE = 'PJS_PERF_INDICATORS') RES_STATUS_INDICATOR

,TMPpjsPERFTHRESEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,TMPpjsPERFTHRESEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,TMPpjsPERFTHRESEO.CREATED_BY RSC_CREATED_BY
,TMPpjsPERFTHRESEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJS_PERF_RULES_VL pjsPERFRULEEO
,TMPpjsPERFTHRESEO
,(SELECT THRES_OBJ_ID,FROM_VALUE,CURRENCY_CODE,INDICATOR_CODE,LAST_UPDATED_BY
	,LAST_UPDATE_DATE,CREATED_BY,CREATION_DATE,
	ROW_NUMBER() OVER (PARTITION BY THRES_OBJ_ID,CURRENCY_CODE ORDER BY FROM_VALUE ASC) AS ROW_NUM
	FROM PJS_PERF_THRESHOLDS ) TMP1
WHERE pjsPERFRULEEO.RULE_ID = TMPpjsPERFTHRESEO.THRES_OBJ_ID
AND TMP1.THRES_OBJ_ID = pjsPERFRULEEO.RULE_ID
AND TMP1.CURRENCY_CODE = TMPpjsPERFTHRESEO.CURRENCY_CODE
AND TMP1.ROW_NUM = 2 
AND pjsPERFRULEEO.MEASURE_FORMAT = 'CURRENCY'
AND pjsPERFRULEEO.THRESHOLD_LEVEL = 'S'
AND TMPpjsPERFTHRESEO.ROW_NUM = 1
AND SYSDATE BETWEEN pjsPERFRULEEO.START_DATE_ACTIVE AND NVL(pjsPERFRULEEO.END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
