/* ****************************************************************************
 * $Revision: 78557 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-05-24 10:32:18 +0700 (Tue, 24 May 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Project%20Templates%20-%20Project%20Plan%20-%20DFF.sql $:
 * $Id: Manage Project Templates - Project Plan - DFF.sql 78557 2022-05-24 03:32:18Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PJF_PROJ_ELEMENTS_VL

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10037##RES##PJF_TASK_STRUCTURE_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

SELECT projTemplatesE0.NAME RES_TEMPLATE_NAME
,projTemplatesE0.SEGMENT1 RES_TEMPLATE_NUMBER
,(SELECT ELEMENT_NUMBER
	FROM PJF_PROJ_ELEMENTS_VL
	WHERE PROJ_ELEMENT_ID = projElementsE0.DENORM_PARENT_ELEMENT_ID
	) RES_PARENT_TASK_NUMBER
,projElementsE0.ELEMENT_NUMBER RES_TASK_NUMBER
,projElementsE0.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE

,projElementsE0.ATTRIBUTE1 
,projElementsE0.ATTRIBUTE2
,projElementsE0.ATTRIBUTE3
,projElementsE0.ATTRIBUTE4
,projElementsE0.ATTRIBUTE5
,projElementsE0.ATTRIBUTE6
,projElementsE0.ATTRIBUTE7
,projElementsE0.ATTRIBUTE8
,projElementsE0.ATTRIBUTE9
,projElementsE0.ATTRIBUTE10
,projElementsE0.ATTRIBUTE11
,projElementsE0.ATTRIBUTE12
,projElementsE0.ATTRIBUTE13
,projElementsE0.ATTRIBUTE14
,projElementsE0.ATTRIBUTE15
,projElementsE0.ATTRIBUTE16
,projElementsE0.ATTRIBUTE17
,projElementsE0.ATTRIBUTE18
,projElementsE0.ATTRIBUTE19 
,projElementsE0.ATTRIBUTE20 
,projElementsE0.ATTRIBUTE21 
,projElementsE0.ATTRIBUTE22 
,projElementsE0.ATTRIBUTE23 
,projElementsE0.ATTRIBUTE24 
,projElementsE0.ATTRIBUTE25 
,projElementsE0.ATTRIBUTE26 
,projElementsE0.ATTRIBUTE27 
,projElementsE0.ATTRIBUTE28 
,projElementsE0.ATTRIBUTE29 
,projElementsE0.ATTRIBUTE30
,projElementsE0.ATTRIBUTE31 
,projElementsE0.ATTRIBUTE32 
,projElementsE0.ATTRIBUTE33 
,projElementsE0.ATTRIBUTE34 
,projElementsE0.ATTRIBUTE35 
,projElementsE0.ATTRIBUTE36 
,projElementsE0.ATTRIBUTE37 
,projElementsE0.ATTRIBUTE38 
,projElementsE0.ATTRIBUTE39 
,projElementsE0.ATTRIBUTE40
,projElementsE0.ATTRIBUTE41 
,projElementsE0.ATTRIBUTE42 
,projElementsE0.ATTRIBUTE43 
,projElementsE0.ATTRIBUTE44 
,projElementsE0.ATTRIBUTE45 
,projElementsE0.ATTRIBUTE46 
,projElementsE0.ATTRIBUTE47 
,projElementsE0.ATTRIBUTE48 
,projElementsE0.ATTRIBUTE49 
,projElementsE0.ATTRIBUTE50
,projElementsE0.ATTRIBUTE1_NUMBER
,projElementsE0.ATTRIBUTE2_NUMBER
,projElementsE0.ATTRIBUTE3_NUMBER
,projElementsE0.ATTRIBUTE4_NUMBER
,projElementsE0.ATTRIBUTE5_NUMBER
,projElementsE0.ATTRIBUTE6_NUMBER
,projElementsE0.ATTRIBUTE7_NUMBER
,projElementsE0.ATTRIBUTE8_NUMBER
,projElementsE0.ATTRIBUTE9_NUMBER
,projElementsE0.ATTRIBUTE10_NUMBER
,projElementsE0.ATTRIBUTE11_NUMBER
,projElementsE0.ATTRIBUTE12_NUMBER
,projElementsE0.ATTRIBUTE13_NUMBER
,projElementsE0.ATTRIBUTE14_NUMBER
,projElementsE0.ATTRIBUTE15_NUMBER
,TO_CHAR(projElementsE0.ATTRIBUTE1_DATE,'DD-Mon-YYYY') ATTRIBUTE1_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE2_DATE,'DD-Mon-YYYY') ATTRIBUTE2_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE3_DATE,'DD-Mon-YYYY') ATTRIBUTE3_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE4_DATE,'DD-Mon-YYYY') ATTRIBUTE4_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE5_DATE,'DD-Mon-YYYY') ATTRIBUTE5_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE6_DATE,'DD-Mon-YYYY') ATTRIBUTE6_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE7_DATE,'DD-Mon-YYYY') ATTRIBUTE7_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE8_DATE,'DD-Mon-YYYY') ATTRIBUTE8_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE9_DATE,'DD-Mon-YYYY') ATTRIBUTE9_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE10_DATE,'DD-Mon-YYYY') ATTRIBUTE10_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE11_DATE,'DD-Mon-YYYY') ATTRIBUTE11_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE12_DATE,'DD-Mon-YYYY') ATTRIBUTE12_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE13_DATE,'DD-Mon-YYYY') ATTRIBUTE13_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE14_DATE,'DD-Mon-YYYY') ATTRIBUTE14_DATE
,TO_CHAR(projElementsE0.ATTRIBUTE15_DATE,'DD-Mon-YYYY') ATTRIBUTE15_DATE

,projElementsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,projElementsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,projElementsE0.CREATED_BY  RSC_CREATED_BY
,projElementsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,projTemplatesE0.ORG_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJF_PROJECTS_ALL_VL projTemplatesE0
,FUN_ALL_BUSINESS_UNITS_V buE0
,PJF_PROJ_ELEMENTS_VL projElementsE0
WHERE projTemplatesE0.TEMPLATE_FLAG = 'Y'
AND projTemplatesE0.ORG_ID = buE0.BU_ID
AND projTemplatesE0.PROJECT_ID = projElementsE0.PROJECT_ID

AND (projElementsE0.ATTRIBUTE_CATEGORY IS NOT NULL OR
projElementsE0.ATTRIBUTE1 IS NOT NULL OR 
projElementsE0.ATTRIBUTE2 IS NOT NULL OR 
projElementsE0.ATTRIBUTE3 IS NOT NULL OR 
projElementsE0.ATTRIBUTE4 IS NOT NULL OR 
projElementsE0.ATTRIBUTE5 IS NOT NULL OR 
projElementsE0.ATTRIBUTE6 IS NOT NULL OR 
projElementsE0.ATTRIBUTE7 IS NOT NULL OR 
projElementsE0.ATTRIBUTE8 IS NOT NULL OR 
projElementsE0.ATTRIBUTE9 IS NOT NULL OR 
projElementsE0.ATTRIBUTE10 IS NOT NULL OR 
projElementsE0.ATTRIBUTE11 IS NOT NULL OR 
projElementsE0.ATTRIBUTE12 IS NOT NULL OR 
projElementsE0.ATTRIBUTE13 IS NOT NULL OR 
projElementsE0.ATTRIBUTE14 IS NOT NULL OR 
projElementsE0.ATTRIBUTE15 IS NOT NULL OR
projElementsE0.ATTRIBUTE16 IS NOT NULL OR
projElementsE0.ATTRIBUTE17 IS NOT NULL OR 
projElementsE0.ATTRIBUTE18 IS NOT NULL OR 
projElementsE0.ATTRIBUTE19 IS NOT NULL OR 
projElementsE0.ATTRIBUTE20 IS NOT NULL OR
projElementsE0.ATTRIBUTE21 IS NOT NULL OR 
projElementsE0.ATTRIBUTE22 IS NOT NULL OR 
projElementsE0.ATTRIBUTE23 IS NOT NULL OR 
projElementsE0.ATTRIBUTE24 IS NOT NULL OR 
projElementsE0.ATTRIBUTE25 IS NOT NULL OR 
projElementsE0.ATTRIBUTE26 IS NOT NULL OR 
projElementsE0.ATTRIBUTE27 IS NOT NULL OR 
projElementsE0.ATTRIBUTE28 IS NOT NULL OR 
projElementsE0.ATTRIBUTE29 IS NOT NULL OR
projElementsE0.ATTRIBUTE30 IS NOT NULL OR
projElementsE0.ATTRIBUTE31 IS NOT NULL OR 
projElementsE0.ATTRIBUTE32 IS NOT NULL OR 
projElementsE0.ATTRIBUTE33 IS NOT NULL OR 
projElementsE0.ATTRIBUTE34 IS NOT NULL OR 
projElementsE0.ATTRIBUTE35 IS NOT NULL OR 
projElementsE0.ATTRIBUTE36 IS NOT NULL OR 
projElementsE0.ATTRIBUTE37 IS NOT NULL OR 
projElementsE0.ATTRIBUTE38 IS NOT NULL OR 
projElementsE0.ATTRIBUTE39 IS NOT NULL OR
projElementsE0.ATTRIBUTE40 IS NOT NULL OR
projElementsE0.ATTRIBUTE41 IS NOT NULL OR 
projElementsE0.ATTRIBUTE42 IS NOT NULL OR 
projElementsE0.ATTRIBUTE43 IS NOT NULL OR 
projElementsE0.ATTRIBUTE44 IS NOT NULL OR 
projElementsE0.ATTRIBUTE45 IS NOT NULL OR 
projElementsE0.ATTRIBUTE46 IS NOT NULL OR 
projElementsE0.ATTRIBUTE47 IS NOT NULL OR 
projElementsE0.ATTRIBUTE48 IS NOT NULL OR 
projElementsE0.ATTRIBUTE49 IS NOT NULL OR
projElementsE0.ATTRIBUTE50 IS NOT NULL OR
projElementsE0.ATTRIBUTE1_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE2_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE3_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE4_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE5_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE6_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE7_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE8_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE9_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE10_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE11_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE12_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE13_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE14_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE15_NUMBER IS NOT NULL OR
projElementsE0.ATTRIBUTE1_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE2_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE3_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE4_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE5_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE6_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE7_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE8_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE9_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE10_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE11_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE12_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE13_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE14_DATE IS NOT NULL OR
projElementsE0.ATTRIBUTE15_DATE IS NOT NULL)

ORDER BY projTemplatesE0.NAME
,DECODE(projElementsE0.OBJECT_TYPE,'PJF_STRUCTURES',1,2)
,projElementsE0.DENORM_WBS_LEVEL
,projElementsE0.ELEMENT_NUMBER