/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Asset%20Price%20Indexes%20-%20Index%20Values.sql $:
 * $Id: Manage Asset Price Indexes - Index Values.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT PRICEINDEXEO.PRICE_INDEX_NAME RES_NAME
,FISCAL.fiscal_year RES_FISCAL_YEAR
,PRICEINDEXVALUEEO.PERIOD_NAME RES_PERIOD_NAME
,TO_CHAR(PRICEINDEXVALUEEO.PERIOD_START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(PRICEINDEXVALUEEO.PERIOD_END_DATE,'DD-Mon-YYYY') RES_END_DATE
,PRICEINDEXVALUEEO.ORIGINAL_PRICE_INDEX_VALUE RES_VALUE
,PRICEINDEXVALUEEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,PRICEINDEXVALUEEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,PRICEINDEXVALUEEO.CREATED_BY RSC_CREATED_BY
,PRICEINDEXVALUEEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FA_PRICE_INDEXES PRICEINDEXEO
,FA_PRICE_INDEX_VALUES PRICEINDEXVALUEEO
,(SELECT fy.fiscal_year
	,CAL.CALENDAR_TYPE
	,fy.START_DATE
	,fy.end_date
	FROM fa_fiscal_year fy
	,fa_calendar_types cal
	WHERE FY.FISCAL_YEAR_NAME = CAL.FISCAL_YEAR_NAME
	) FISCAL
WHERE PRICEINDEXEO.PRICE_INDEX_ID = PRICEINDEXVALUEEO.PRICE_INDEX_ID 
AND PRICEINDEXEO.CALENDAR_TYPE  =  FISCAL.CALENDAR_TYPE
AND (PRICEINDEXVALUEEO.PERIOD_END_DATE BETWEEN FISCAL.START_DATE AND FISCAL.END_DATE)
order by PRICEINDEXEO.PRICE_INDEX_NAME