/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Chart%20of%20Accounts%20Mappings%20-%20Account%20Rules.sql $:
 * $Id: Manage Chart of Accounts Mappings - Account Rules.sql 56764 2016-07-20 09:02:15Z wuttipong.thongvises 
 * *****************************************************************************/
 
 -- FIELD_TO_APPLY_FUNCTION=RES_TARGET_ACCOUNT/GET_CODE_COMBINATION 
 
WITH Acc AS
	(SELECT name
	,ACCOUNT_RULE_ID
	,TO_CODE_COMBINATION_ID
	,MAX(RES_SOURCE_ACCOUNT_FILTER) RES_SOURCE_ACCOUNT_FILTER
	,MAX(
		CASE
			WHEN RES_XX = '1'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD1
	,MAX(
		CASE
			WHEN RES_XX = '1'
			THEN RES_condition
		END) RES_FIELD1_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '1'
			THEN RES_VALUE_1
		END) RES_FIELD1_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '1'
			THEN RES_VALUE_2
		END) RES_FIELD1_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '2'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD2
	,MAX(
		CASE
			WHEN RES_XX = '2'
			THEN RES_CONDITION
		END) RES_FIELD2_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '2'
			THEN RES_VALUE_1
		END) RES_FIELD2_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '2'
			THEN RES_VALUE_2
		END) RES_FIELD2_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '3'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD3
	,MAX(
		CASE
			WHEN RES_XX = '3'
			THEN RES_CONDITION
		END) RES_FIELD3_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '3'
			THEN RES_VALUE_1
		END) RES_FIELD3_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '3'
			THEN RES_VALUE_2
		END) RES_FIELD3_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '4'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD4
	,MAX(
		CASE
			WHEN RES_XX = '4'
			THEN RES_CONDITION
		END) RES_FIELD4_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '4'
			THEN RES_VALUE_1
		END) RES_FIELD4_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '4'
			THEN RES_VALUE_2
		END) RES_FIELD4_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '5'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD5
	,MAX(
		CASE
			WHEN RES_XX = '5'
			THEN RES_CONDITION
		END) RES_FIELD5_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '5'
			THEN RES_VALUE_1
		END) RES_FIELD5_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '5'
			THEN RES_VALUE_2
		END) RES_FIELD5_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '6'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD6
	,MAX(
		CASE
			WHEN RES_XX = '6'
			THEN RES_CONDITION
		END) RES_FIELD6_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '6'
			THEN RES_VALUE_1
		END) RES_FIELD6_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '6'
			THEN RES_VALUE_2
		END) RES_FIELD6_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '7'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD7
	,MAX(
		CASE
			WHEN RES_XX = '7'
			THEN RES_CONDITION
		END) RES_FIELD7_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '7'
			THEN RES_VALUE_1
		END) RES_FIELD7_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '7'
			THEN RES_VALUE_2
		END) RES_FIELD7_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '8'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD8
	,MAX(
		CASE
			WHEN RES_XX = '8'
			THEN RES_CONDITION
		END) RES_FIELD8_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '8'
			THEN RES_VALUE_1
		END) RES_FIELD8_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '8'
			THEN RES_VALUE_2
		END) RES_FIELD8_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '9'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD9
	,MAX(
		CASE
			WHEN RES_XX = '9'
			THEN RES_CONDITION
		END) RES_FIELD9_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '9'
			THEN RES_VALUE_1
		END) RES_FIELD9_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '9'
			THEN RES_VALUE_2
		END) RES_FIELD9_VALUE2
	,MAX(
		CASE
			WHEN RES_XX = '10'
			THEN RES_ADD_FIELDS
		END) RES_ADD_FIELD10
	,MAX(
		CASE
			WHEN RES_XX = '10'
			THEN RES_CONDITION
		END) RES_FIELD10_CONDITION
	,MAX(
		CASE
			WHEN RES_XX = '10'
			THEN RES_VALUE_1
		END) RES_FIELD10_VALUE1
	,MAX(
		CASE
			WHEN RES_XX = '10'
			THEN RES_VALUE_2
		END) RES_FIELD10_VALUE2
	FROM
		(SELECT COAMAPPINGEO.name
		,CoaMapAccountRuleEO.COA_MAPPING_ID
		,CoaMapAccountRuleEO.TO_CODE_COMBINATION_ID
		,CoaMapAccountRuleEO.ACCOUNT_RULE_ID
		,(SELECT COAMAPACCOUNTRULEEO.prompt
			FROM FND_KF_SEGMENTS_VL COAMAPACCOUNTRULEEO
			,FND_KF_STR_INSTANCES_VL COAMAPACCOUNTRULEEOI
			WHERE COAMAPACCOUNTRULEEO.STRUCTURE_ID           = COAMAPACCOUNTRULEEOI.STRUCTURE_ID
			AND COAMAPACCOUNTRULEEOI.STRUCTURE_INSTANCE_CODE =(EXTRACTVALUE(CoaMapAccountRuleEO.FLEX_FILTER,
				'/FndFilter/KeyFlexFilter/structureInstanceCode'))
			AND COAMAPACCOUNTRULEEO.SEGMENT_IDENTIFIER =(EXTRACTVALUE(value(X),'/filterCriteriaItem/attributeName'))
			) RES_ADD_FIELDS
		,(SELECT decode(MEANING,'Equals to','Equals',MEANING)
			FROM GL_LOOKUPS
			WHERE LOOKUP_TYPE = 'FILTER_OPERATORS'
			AND LOOKUP_CODE   = EXTRACTVALUE(value(X),'/filterCriteriaItem/operator')
			) RES_CONDITION
		,row_number() over(partition BY ACCOUNT_RULE_ID, CoaMapAccountRuleEO.COA_MAPPING_ID, TO_CODE_COMBINATION_ID order by null) RES_SOURCE_ACCOUNT_FILTER
		,row_number() over(PARTITION BY ACCOUNT_RULE_ID, CoaMapAccountRuleEO.COA_MAPPING_ID, TO_CODE_COMBINATION_ID order by NULL) RES_XX
		,EXTRACTVALUE(value(X),'/filterCriteriaItem/value[1]') RES_VALUE_1
		,EXTRACTVALUE(value(X),'/filterCriteriaItem/value[2]') RES_VALUE_2
		FROM GL_COA_MAP_ACCOUNT_RULES CoaMapAccountRuleEO
		,GL_COA_MAPPINGS COAMAPPINGEO
		,TABLE(XMLSEQUENCE(extract(CoaMapAccountRuleEO.FLEX_FILTER,
			'/FndFilter/KeyFlexFilter/filterCriteriaRow/filterCriteriaItem'))) X
		WHERE COAMAPPINGEO.COA_MAPPING_ID = CoaMapAccountRuleEO.COA_MAPPING_ID
		)
	GROUP BY NAME
	,ACCOUNT_RULE_ID
	,TO_CODE_COMBINATION_ID
	)
SELECT ACC.name RES_NAME
,ACC.TO_CODE_COMBINATION_ID RES_TARGET_ACCOUNT
,RES_SOURCE_ACCOUNT_FILTER
,RES_ADD_FIELD1
,RES_FIELD1_CONDITION
,RES_FIELD1_VALUE1
,RES_FIELD1_VALUE2
,RES_ADD_FIELD2
,RES_FIELD2_CONDITION
,RES_FIELD2_VALUE1
,RES_FIELD2_VALUE2
,RES_ADD_FIELD3
,RES_FIELD3_CONDITION
,RES_FIELD3_VALUE1
,RES_FIELD3_VALUE2
,RES_ADD_FIELD4
,RES_FIELD4_CONDITION
,RES_FIELD4_VALUE1
,RES_FIELD4_VALUE2
,RES_ADD_FIELD5
,RES_FIELD5_CONDITION
,RES_FIELD5_VALUE1
,RES_FIELD5_VALUE2
,RES_ADD_FIELD6
,RES_FIELD6_CONDITION
,RES_FIELD6_VALUE1
,RES_FIELD6_VALUE2
,RES_ADD_FIELD7
,RES_FIELD7_CONDITION
,RES_FIELD7_VALUE1
,RES_FIELD7_VALUE2
,RES_ADD_FIELD8
,RES_FIELD8_CONDITION
,RES_FIELD8_VALUE1
,RES_FIELD8_VALUE2
,RES_ADD_FIELD9
,RES_FIELD9_CONDITION
,RES_FIELD9_VALUE1
,RES_FIELD9_VALUE2
,RES_ADD_FIELD10
,RES_FIELD10_CONDITION
,RES_FIELD10_VALUE1
,RES_FIELD10_VALUE2
,CoaMapAccountRuleEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,CoaMapAccountRuleEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,CoaMapAccountRuleEO.CREATED_BY RSC_CREATED_BY
,CoaMapAccountRuleEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,(SELECT DISTINCT LedgerE0.CHART_OF_ACCOUNTS_ID 
	FROM GL_LEDGER_RELATIONSHIPS GlRelation
	,GL_LEDGERS LedgerE0
	WHERE GlRelation.SL_COA_MAPPING_ID = CoaMappingEO.COA_MAPPING_ID
	AND GlRelation.PRIMARY_LEDGER_ID = LedgerE0.LEDGER_ID
	) RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM ACC
,GL_COA_MAP_ACCOUNT_RULES CoaMapAccountRuleEO
,GL_COA_MAPPINGS CoaMappingEO
,FND_KF_STR_INSTANCES_VL KeyFlexfieldStructureInstanc1
,FND_KF_STR_INSTANCES_VL KeyFlexfieldStructureInstanc11
WHERE ACC.ACCOUNT_RULE_ID   = CoaMapAccountRuleEO.ACCOUNT_RULE_ID
and CoaMapAccountRuleEO.COA_MAPPING_ID  = CoaMappingEO.COA_MAPPING_ID
and (CoaMappingEO.TO_COA_ID                          = KeyFlexfieldStructureInstanc1.STRUCTURE_INSTANCE_NUMBER)
AND(CoaMappingEO.FROM_COA_ID                          = KeyFlexfieldStructureInstanc11.STRUCTURE_INSTANCE_NUMBER)
AND(KeyFlexfieldStructureInstanc1.APPLICATION_ID      = 101
AND KeyFlexfieldStructureInstanc1.KEY_FLEXFIELD_CODE  = 'GL#'
AND KeyFlexfieldStructureInstanc1.ENABLED_FLAG        = 'Y')
AND(KeyFlexfieldStructureInstanc11.APPLICATION_ID     = 101
AND KeyFlexfieldStructureInstanc11.KEY_FLEXFIELD_CODE = 'GL#'
AND KeyFlexfieldStructureInstanc11.ENABLED_FLAG       = 'Y')
ORDER BY ACC.NAME,RES_SOURCE_ACCOUNT_FILTER