/* ****************************************************************************
 * $Revision: 54943 $:
 * $Author: paul.wakefield $:
 * $Date: 2016-05-04 13:45:23 +0700 (Wed, 04 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Trading%20Community%20Person%20Lookups%20-%20Standard%20Lookup%20Type.sql $:
 * $Id: Manage Trading Community Person Lookups - Standard Lookup Type.sql 54943 2016-05-04 06:45:23Z paul.wakefield $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
--RSC_PREREQUISITE_OBJECTS=PAY_CHECKLISTS_VL 
 
SELECT payFLOWEO.FLOW_NAME RES_FLOW_PATTERN
,payFLOWTASK.FLOW_TASK_NAME RES_FLOW_TASK
--,(SELECT TASK_TYPE FROM PAY_TASKS_VL WHERE TASK_ID = payFLOWTASK.BASE_TASK_ID) RES_TASK_TYPE
,DECODE(payFLOWTASK.SUBMITTING_USER_FLAG,'Y','Yes','No') RES_SECURE_PROCESS_OR_REPORT
,DECODE(payFLOWTASK.IGNORE_PREREQ_FLAG,'Y','Yes','No') RES_PROCESS_AFTER_ERROR
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWTASK.CATEGORY_TYPE
		AND LOOKUP_TYPE = 'PAY_TASK_CATEGORY' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_ACTIVITY
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWTASK.SUB_CATEGORY_TYPE
		AND LOOKUP_TYPE = 'PAY_TASK_SUB_CATEGORY' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_TASK_GROUP
,(SELECT TASK_NAME FROM PAY_TASKS_VL WHERE TASK_ID = payFLOWTASK.BASE_TASK_ID) RES_TASK
,(SELECT DESCRIPTION FROM PAY_TASKS_VL WHERE TASK_ID = payFLOWTASK.BASE_TASK_ID) RES_TASK_DESCRIPTION

,payFLOWTASK.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payFLOWTASK.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payFLOWTASK.CREATED_BY RSC_CREATED_BY
,payFLOWTASK.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PAY_FLOWS_VL payFLOWEO
,PAY_FLOW_TASKS_VL payFLOWTASK
WHERE payFLOWEO.FLOW_ID = payFLOWTASK.BASE_FLOW_ID 
AND payFLOWTASK.CATEGORY_TYPE IS NOT NULL
ORDER BY payFLOWEO.FLOW_NAME,payFLOWTASK.FLOW_TASK_NAME