/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20User-Defined%20Tables%20-%20User-Defined%20Rows.sql $:
 * $Id: Manage User-Defined Tables - User-Defined Rows.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 
SELECT (SELECT NAME 
	FROM PER_LEGISLATIVE_DATA_GROUPS_VL 
	WHERE LEGISLATIVE_DATA_GROUP_ID = ffUSERTABLEO.LEGISLATIVE_DATA_GROUP_ID
	) RES_LEGISLATIVE_DATA_GROUP
,ffUSERTABLEO.USER_TABLE_NAME RES_NAME
,ffUSERROWEO.DISPLAY_SEQUENCE RES_SEQUENCE
,(CASE
	WHEN ffUSERTABLEO.RANGE_OR_MATCH = 'M' THEN
		(CASE 
			WHEN ffUSERTABLEO.USER_KEY_UNITS = 'D' THEN
				SUBSTR(ffUSERROWEO.ROW_LOW_RANGE_OR_NAME,9,2)||'-'||SUBSTR(ffUSERROWEO.ROW_LOW_RANGE_OR_NAME,6,2)||'-'||SUBSTR(ffUSERROWEO.ROW_LOW_RANGE_OR_NAME,1,4)
			ELSE
				ffUSERROWEO.ROW_LOW_RANGE_OR_NAME 
		END) 
	END) RES_EXACT
,TO_CHAR(ffUSERROWEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,TO_CHAR(ffUSERROWEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY')RES_EFFECTIVE_END_DATE
,(CASE
	WHEN ffUSERTABLEO.RANGE_OR_MATCH = 'R' THEN
		ffUSERROWEO.ROW_LOW_RANGE_OR_NAME 
	END) RES_LOW_RANGE
,(CASE
	WHEN ffUSERTABLEO.RANGE_OR_MATCH = 'R' THEN
		ffUSERROWEO.ROW_HIGH_RANGE 
	END) RES_HIGH_RANGE
,ffUSERROWEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ffUSERROWEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ffUSERROWEO.CREATED_BY RSC_CREATED_BY
,ffUSERROWEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,(SELECT LEGISLATION_CODE 
	FROM PER_LEGISLATIVE_DATA_GROUPS
	WHERE LEGISLATIVE_DATA_GROUP_ID = ffUSERTABLEO.LEGISLATIVE_DATA_GROUP_ID
	) RSC_COUNTRY_ID
FROM FF_USER_TABLES_VL ffUSERTABLEO
,FF_USER_ROWS_VL ffUSERROWEO
WHERE ffUSERTABLEO.USER_TABLE_ID = ffUSERROWEO.USER_TABLE_ID
AND SYSDATE BETWEEN ffUSERROWEO.EFFECTIVE_START_DATE AND NVL(ffUSERROWEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
ORDER BY ffUSERTABLEO.USER_TABLE_NAME
,ffUSERROWEO.DISPLAY_SEQUENCE 