/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Payables%20Document%20Sequences%20-%20Document%20Sequences.sql $:
 * $Id: Manage Payables Document Sequences - Document Sequences.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT DISTINCT QRSLT.NAME RES_DOCUMENT_SEQUENCE_NAME
,QRSLT.APPLICATION_NAME RES_APPLICATION
,QRSLT.USER_MODULE_NAME RES_MODULE
,QRSLT.TYPE_MEANING RES_TYPE
,QRSLT.DETERMINANT_TYPE_MEANING RES_DETERMINANT_TYPE
,TO_CHAR(QRSLT.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(QRSLT.END_DATE,'DD-Mon-YYYY') RES_END_DATE
,QRSLT.INITIAL_VALUE RES_INITIAL_VALUE
,DECODE(QRSLT.TRANSIENTAUDIT,'Y','Yes','No') RES_AUDIT
,DECODE(QRSLT.MESSAGE_FLAG,'Y','Yes','No') RES_DISPLAY_MESSAGE
,DECODE(QRSLT.validate_transaction_date,'Y','Yes','No') RES_VALIDATE_TRANSACTION_DATE
,QRSLT.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY  RSC_CREATED_BY
,QRSLT.CREATION_DATE  RSC_CREATION_DATE
,(CASE
	WHEN QRSLT.DETERMINANT_TYPE = 'LEDGER' THEN
		QRSLT.DETERMINANT_VALUE
	ELSE	
		NULL
	END) RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,(CASE
	WHEN QRSLT.DETERMINANT_TYPE = 'BU' THEN
		QRSLT.DETERMINANT_VALUE
	ELSE	
		NULL
	END) RSC_BUSINESS_UNIT_ID
,(CASE
	WHEN QRSLT.DETERMINANT_TYPE = 'LE' THEN
		QRSLT.DETERMINANT_VALUE
	ELSE	
		NULL
	END) RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM
	(SELECT distinct DocumentSequencesEO.DOC_SEQUENCE_ID
	,DocumentSequencesEO.NAME
	,DocumentSequencesEO.APPLICATION_ID
	,DocumentSequencesEO.MODULE_ID
	,DOCUMENTSEQUENCESEO.TYPE
	,(SELECT MEANING
		FROM FND_LOOKUP_VALUES
		WHERE LOOKUP_type = 'FND_DOCUMENT_SEQUENCES_TYPE'
		AND lookup_code   = DOCUMENTSEQUENCESEO.TYPE
		AND ENABLED_FLAG = 'Y'
	    AND LANGUAGE = USERENV('LANG')
		) TYPE_MEANING
	,DOCUMENTSEQUENCESEO.DETERMINANT_TYPE
	,(SELECT MEANING
		FROM FND_LOOKUP_VALUES
		WHERE LOOKUP_type = 'FND_DOC_SEQ_DETERMINANT_TYPE'
		AND lookup_code   = DOCUMENTSEQUENCESEO.DETERMINANT_TYPE
		AND ENABLED_FLAG = 'Y'
	    AND LANGUAGE = USERENV('LANG')
		) DETERMINANT_TYPE_MEANING
	,DocumentSequencesEO.START_DATE
	,DocumentSequencesEO.END_DATE
	,DocumentSequencesEO.TABLE_NAME
	,DocumentSequencesEO.AUDIT_TABLE_NAME
	,DocumentSequencesEO.DB_SEQUENCE_NAME
	,DocumentSequencesEO.INITIAL_VALUE
	,DocumentSequencesEO.MESSAGE_FLAG
	,DocumentSequencesEO.LAST_UPDATE_DATE
	,DocumentSequencesEO.LAST_UPDATED_BY
	,DocumentSequencesEO.CREATED_BY
	,DocumentSequencesEO.CREATION_DATE
	,DocumentSequencesEO.ENTERPRISE_ID	
	,ApplTaxonomyPEO.MODULE_KEY
	,ApplTaxonomyPEO.MODULE_ID AS MODULE_ID1
	,ApplTaxonomyPEO.MODULE_TYPE
	,ApplTaxonomyPEO.USER_MODULE_NAME
	,(DECODE(AUDIT_TABLE_NAME,NULL,'N','Y')) AS TRANSIENTAUDIT
	,DOCUMENTSEQUENCESEO.VALIDATE_TRANSACTION_DATE
	,ApplicationPEO.APPLICATION_NAME
	,DocSequenceAssignmentsEO.DETERMINANT_VALUE
	FROM FND_DOCUMENT_SEQUENCES DocumentSequencesEO
	,FND_APPL_TAXONOMY_VL APPLTAXONOMYPEO
	,FND_DOC_SEQUENCE_ASSIGNMENTS DOCSEQUENCEASSIGNMENTSEO
	,FND_APPLICATION_VL APPLICATIONPEO
	WHERE DOCUMENTSEQUENCESEO.MODULE_ID    = APPLTAXONOMYPEO.MODULE_ID
	AND DocumentSequencesEO.APPLICATION_ID = APPLICATIONPEO.APPLICATION_ID
	AND(DocumentSequencesEO.MODULE_ID     IN
		(SELECT rf.child_module_id
		FROM fnd_appl_taxonomy_rf rf
		,fnd_appl_taxonomy at
		WHERE AT.MODULE_TYPE = 'APPLICATION'
		AND at.module_key    = 'AP'
		AND at.module_id     = rf.ancestor_module_id
		))
	AND DOCUMENTSEQUENCESEO.DOC_SEQUENCE_ID = DOCSEQUENCEASSIGNMENTSEO.DOC_SEQUENCE_ID(+)
	) QRSLT
ORDER BY QRSLT.NAME