/* ****************************************************************************
 * $Revision: 55346 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-05-23 14:11:43 +0700 (Mon, 23 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Chart%20of%20Accounts%20Value%20Set%20Values%20-%20Manage%20Values.sql $:
 * $Id: Manage Chart of Accounts Value Set Values - Manage Values.sql 55346 2016-05-23 07:11:43Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=ANC_ABSENCE_PLANS_F

SELECT (SELECT NAME 
	FROM ANC_ABSENCE_PLANS_F_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND ABSENCE_PLAN_ID = absencePlansE0.ABSENCE_PLAN_ID
	AND EFFECTIVE_START_DATE = absencePlansE0.EFFECTIVE_START_DATE
	) RES_PLAN
,(SELECT TERRITORY_SHORT_NAME
	FROM FND_TERRITORIES_VL
	WHERE TERRITORY_CODE = absencePlansE0.LEGISLATION_CODE 
	) RES_LEGISLATION
,(SELECT NAME
	FROM PER_LEGISLATIVE_DATA_GROUPS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND LEGISLATIVE_DATA_GROUP_ID = absencePlansE0.LEGISLATIVE_DATA_GROUP_ID 
	) RES_LEGISLATIVE_DATA_GROUP
,TO_CHAR(absencePlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(absencePlansE0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(absencePlansE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
	
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_DON' THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_ACC_PER_FREQUENCY'
			AND LOOKUP_CODE = absencePlansE0.ACC_PERIOD_FREQUENCY)
	END) RES_FREQUENCY
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_DON' THEN 
		(CASE
			WHEN absencePlansE0.ACC_PERIOD_FREQUENCY = 'W' THEN
				(SELECT NAME
					FROM HWM_RP_TM_PERIODS_TL
					WHERE LANGUAGE = USERENV('LANG')
					AND REPEATING_TM_PERIOD_ID = absencePlansE0.ACC_PERIOD_WFM_CALEDAR_ID)
			END)
	END)RES_REPEATING_PERIOD


,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_ANC_COMP_VEST'
			AND LOOKUP_CODE = absencePlansE0.ACCRUAL_VESTING_CD )
	END) RES_VESTING_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		(CASE
			WHEN absencePlansE0.ACCRUAL_VESTING_CD = 'ORA_ANC_FORMULA' THEN 
				(SELECT BASE_FORMULA_NAME 
					FROM FF_FORMULAS_VL 
					WHERE FORMULA_ID = absencePlansE0.PARTIAL_ACCRUAL_FORMULA_ID
					AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
			END)
	END) RES_VESTING_PERIOD_FORMULA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		(CASE
			WHEN absencePlansE0.ACCRUAL_VESTING_CD = 'ORA_ANC_ELAPSED' THEN 
				absencePlansE0.VESTING_PERIOD_DURATION 
			END)
	END) RES_DURATION
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		(CASE
			WHEN absencePlansE0.ACCRUAL_VESTING_CD = 'ORA_ANC_ELAPSED' THEN 
				(SELECT MEANING
					FROM FND_LOOKUP_VALUES
					WHERE LANGUAGE = USERENV('LANG')
					AND LOOKUP_TYPE = 'ANC_SETUP_OBJ_UOM_WITHOUT_HRS'
					AND LOOKUP_CODE = absencePlansE0.VESTING_PERIOD_UOM)
			END)
	END) RES_UOM
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		absencePlansE0.PAY_RATE_FACTOR
	END) RES_PAYMENT_PERCENTAGE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_COMP' THEN 
		(CASE
			WHEN absencePlansE0.ACCRUAL_VESTING_CD = 'ORA_ANC_FORMULA' THEN 
				(SELECT MEANING
					FROM FND_LOOKUP_VALUES
					WHERE LANGUAGE = USERENV('LANG')
					AND LOOKUP_TYPE = 'ANC_ACC_PER_FREQUENCY'
					AND LOOKUP_CODE = absencePlansE0.ACC_PERIOD_FREQUENCY)
			END)
	END) RES_BALANCE_FREQUENCY_SOURCE

-- Plan Limits
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON') THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_ANC_COMP_CEILING'
			AND LOOKUP_CODE = absencePlansE0.CEIL_LIMIT_RULE)
	END) RES_CEILING_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.CEIL_LIMIT_RULE = 'ORA_ANC_FLAT_AMT' THEN 
				absencePlansE0.CEIL_LIMIT_FLAT_AMT
			END)
	END) RES_CEILING
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.CEIL_LIMIT_RULE = 'ORA_ANC_FORMULA' THEN 
				(SELECT BASE_FORMULA_NAME 
					FROM FF_FORMULAS_VL 
					WHERE FORMULA_ID = absencePlansE0.CEIL_LIMIT_FORMULA_ID
					AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
			END)
	END) RES_CEILING_FORMULA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.CEIL_LIMIT_RULE <> 'ORA_ANC_NONE' THEN 
				(SELECT MEANING
					FROM FND_LOOKUP_VALUES
					WHERE LANGUAGE = USERENV('LANG')
					AND LOOKUP_TYPE = 'ANC_CEIL_LMT_PRORATION'
					AND LOOKUP_CODE = absencePlansE0.CEIL_LIMIT_PRORATE_RULE)
			END)
	END) RES_CEILING_PRORATION_RULE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.CEIL_LIMIT_RULE <> 'ORA_ANC_NONE' THEN 
				(CASE
					WHEN absencePlansE0.CEIL_LIMIT_PRORATE_RULE = 'F' THEN
						(SELECT BASE_FORMULA_NAME 
							FROM FF_FORMULAS_VL 
							WHERE FORMULA_ID = absencePlansE0.CEIL_LMT_PRORATE_FORMULA_ID
							AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
					END)
			END)
	END) RES_CEILING_PRORATION_FORMULA
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON') THEN 
		DECODE(absencePlansE0.ACC_NEGATIVE_BAL_FLAG,'Y','Yes','No')
	END) RES_ALLOW_NEGATIVE_BALANCE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON') THEN 
		(CASE
			WHEN absencePlansE0.ACC_NEGATIVE_BAL_FLAG = 'Y' THEN 
				absencePlansE0.ACC_NEGATIVE_BAL_LIMIT
			END)
	END) RES_NEGATIVE_BALANCE_LIMIT
	
	
-- Termination Rules
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_DON' THEN 
		DECODE(absencePlansE0.EMP_ENRL_POSITIVE_BALANCE_FLAG,'Y','Yes','No')
	END) RES_DISBURSE_POSITIVE_BALANCE
,(CASE
	WHEN absencePlansE0.ENTL_METHOD_CD = 'ORA_ANC_DON' THEN 
		DECODE(absencePlansE0.EMP_ENRL_NEGATIVE_BALANCE_FLAG,'Y','Yes','No')
	END) RES_RECOVER_NEGATIVE_BALANCE
,absencePlansE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,absencePlansE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,absencePlansE0.CREATED_BY  RSC_CREATED_BY
,absencePlansE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,absencePlansE0.LEGISLATION_CODE RSC_COUNTRY_ID
 
FROM ANC_ABSENCE_PLANS_F absencePlansE0
WHERE absencePlansE0.ENTL_METHOD_CD IN ('ORA_ANC_COMP','ORA_ANC_DON')
ORDER BY 1
,absencePlansE0.EFFECTIVE_START_DATE