/* ****************************************************************************
 * $Revision: 72749 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2019-10-23 15:22:46 +0700 (Wed, 23 Oct 2019) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Availability%20Lookups%20-%20Lookup%20Types.sql $:
 * $Id: Manage Availability Lookups - Lookup Types.sql 72749 2019-10-23 08:22:46Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
--RSC_PREREQUISITE_OBJECTS=HRT_REVIEW_PERIODS_VL
 
SELECT cmpPLANEO.PLAN_NAME RES_PLAN
,(CASE WHEN cmpPLANEO.PERFORMANCE_SYSTEM IS NOT NULL 
	THEN 'Yes'
	ELSE 'No' END) RES_ENABLE_PERFORMANCE_RATINGS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpPLANEO.PERFORMANCE_SYSTEM 
			AND LOOKUP_TYPE = 'CMP_PERF_APPR_MODE' AND LANGUAGE = USERENV('LANG')
			AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_PERFORMANCE_RATINGS_TO_USE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpPLANEO.PERF_LAYOUT_OPTION 
			AND LOOKUP_TYPE = 'CMP_PERF_LAY_OPT' AND LANGUAGE = USERENV('LANG')
			AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_LAYOUT_OPTIONS
,(SELECT RATING_NAME FROM HRT_RATING_MODELS_VL
		WHERE RATING_MODEL_ID = cmpPLANEO.RATING_MODEL_ID) RES_RATING_MODEL
,(SELECT REVIEW_PERIOD_NAME FROM HRT_REVIEW_PERIODS_VL WHERE REVIEW_PERIOD_ID = cmpPLANEO.PERF_REVIEW_PERIOD_ID) RES_REVIEW_PERIOD
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpPLANEO.PERF_RATING_STATUS_CODE 
			AND LOOKUP_TYPE = 'CMP_PERF_MGT_STATUS' AND LANGUAGE = USERENV('LANG')
			AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_EVALUATION_STATUS
,(SELECT NAME FROM HRA_DOC_TYPES_VL WHERE DOC_TYPE_ID = cmpPLANEO.PERF_DOCUMENT_ID) RES_PERFORMANCE_DOCUMENT_TYPE
,(CASE WHEN cmpPLANEO.PERF_TEMPLATE_PERIOD_ID IS NOT NULL 
	THEN 'Period specific'
	ELSE 'Most recent' END) RES_TIMING
,(SELECT NAME FROM HRA_TMPL_DEFNS_VL where TEMPLATE_DEFN_ID = cmpPLANEO.PERF_TEMPLATE_ID) RES_PERFORMANCE_TEMPLATE
--,RES_WORKER_NAME PER_PERSON_NAMES_F 
--,RES_ASSIGNMENT PER_ALL_ASSIGNMENTS_M 



,cmpPLANEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,cmpPLANEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,cmpPLANEO.CREATED_BY RSC_CREATED_BY
,cmpPLANEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CMP_PLANS_VL cmpPLANEO
WHERE cmpPLANEO.COMP_TYPE = 'CWB'
ORDER BY PLAN_NAME