/* ****************************************************************************
 * $Revision: 53609 $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2016-07-13 10:53:25 +0700  $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Accounting%20Calendars%20-%20Additional%20Year.sql $:
 * $Id: Manage Bank Accounts - Account Contact - DFF.sql 53609 2016-07-13 03:53:25Z  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10024##RES##HZ_PERSON_PROFILES
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.


SELECT 
Head.BANK_NAME  								RES_BANK,
Head.COUNTRY_NAME      							RES_COUNTRY,
Head.BANK_BRANCH_NAME        					RES_BANK_BRANCH,
Head.BANK_ACCOUNT_NAME            				RES_ACCOUNT_NAME,
Head.BANK_ACCOUNT_NUM             				RES_ACCOUNT_NUMBER,
Detail.PARTY_NAME                    			RES_CONTACT_NAME,
DECODE(Detail.PRIMARY_FLAG,'Y','Yes','N','No')                    RES_PRIMARY,
Detail.RES_PURPOSE                    			RES_PURPOSE,
Detail.EMAIL_ADDRESS                    		RES_E_MAIL,

 Detail.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,Detail.ATTRIBUTE1 
,Detail.ATTRIBUTE2
,Detail.ATTRIBUTE3
,Detail.ATTRIBUTE4
,Detail.ATTRIBUTE5
,Detail.ATTRIBUTE6
,Detail.ATTRIBUTE7
,Detail.ATTRIBUTE8
,Detail.ATTRIBUTE9
,Detail.ATTRIBUTE10
,Detail.ATTRIBUTE11
,Detail.ATTRIBUTE12
,Detail.ATTRIBUTE13
,Detail.ATTRIBUTE14
,Detail.ATTRIBUTE15
,Detail.ATTRIBUTE16
,Detail.ATTRIBUTE17
,Detail.ATTRIBUTE18
,Detail.ATTRIBUTE19
,Detail.ATTRIBUTE20
,Detail.ATTRIBUTE21
,Detail.ATTRIBUTE22
,Detail.ATTRIBUTE23
,Detail.ATTRIBUTE24
,Detail.ATTRIBUTE25
,Detail.ATTRIBUTE26
,Detail.ATTRIBUTE27
,Detail.ATTRIBUTE28
,Detail.ATTRIBUTE29
,Detail.ATTRIBUTE30
,Detail.ATTRIBUTE_NUMBER1 
,Detail.ATTRIBUTE_NUMBER2
,Detail.ATTRIBUTE_NUMBER3
,Detail.ATTRIBUTE_NUMBER4
,Detail.ATTRIBUTE_NUMBER5
,Detail.ATTRIBUTE_NUMBER6
,Detail.ATTRIBUTE_NUMBER7
,Detail.ATTRIBUTE_NUMBER8
,Detail.ATTRIBUTE_NUMBER9
,Detail.ATTRIBUTE_NUMBER10
,Detail.ATTRIBUTE_NUMBER11
,Detail.ATTRIBUTE_NUMBER12
,to_char(Detail.ATTRIBUTE_DATE1,'DD-Mon-YYYY')  ATTRIBUTE_DATE1
,to_char(Detail.ATTRIBUTE_DATE2,'DD-Mon-YYYY')  ATTRIBUTE_DATE2
,to_char(Detail.ATTRIBUTE_DATE3,'DD-Mon-YYYY')  ATTRIBUTE_DATE3
,to_char(Detail.ATTRIBUTE_DATE4,'DD-Mon-YYYY')  ATTRIBUTE_DATE4
,to_char(Detail.ATTRIBUTE_DATE5,'DD-Mon-YYYY')  ATTRIBUTE_DATE5
,to_char(Detail.ATTRIBUTE_DATE6,'DD-Mon-YYYY')  ATTRIBUTE_DATE6
,to_char(Detail.ATTRIBUTE_DATE7,'DD-Mon-YYYY')  ATTRIBUTE_DATE7
,to_char(Detail.ATTRIBUTE_DATE8,'DD-Mon-YYYY')  ATTRIBUTE_DATE8
,to_char(Detail.ATTRIBUTE_DATE9,'DD-Mon-YYYY')  ATTRIBUTE_DATE9
,to_char(Detail.ATTRIBUTE_DATE10,'DD-Mon-YYYY')  ATTRIBUTE_DATE10
,to_char(Detail.ATTRIBUTE_DATE11,'DD-Mon-YYYY')  ATTRIBUTE_DATE11
,to_char(Detail.ATTRIBUTE_DATE12,'DD-Mon-YYYY')  ATTRIBUTE_DATE12

,Detail.LAST_UPDATED_BY  						RSC_LAST_UPDATED_BY,
Detail.LAST_UPDATE_DATE  						RSC_LAST_UPDATE_DATE,
Detail.CREATED_BY  								RSC_CREATED_BY,
Detail.CREATION_DATE  							RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,Head.ACCOUNT_OWNER_ORG_ID RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID


FROM
(
    Select 
      CeBankAccounts.BANK_ACCOUNT_ID,
      BankBranchSimplePEO.BANK_NAME               		,
      BankBranchSimplePEO.COUNTRY_NAME            		,
      BankBranchSimplePEO.BANK_BRANCH_NAME        		,
      CeBankAccounts.BANK_ACCOUNT_NAME             		,
      CeBankAccounts.BANK_ACCOUNT_NUM                   ,
	  CeBankAccounts.ACCOUNT_OWNER_ORG_ID
    FROM CE_BANK_ACCOUNTS CeBankAccounts,
        XLE_ENTITY_PROFILES XleEntityProfiles,
        CE_BANK_BRANCHES_SIMPLE_V BankBranchSimplePEO,
        CE_RECON_RULESETS BankStatementReconRuleSetPEO
      WHERE ((CeBankAccounts.ACCOUNT_OWNER_ORG_ID = XleEntityProfiles.LEGAL_ENTITY_ID)
      AND (CeBankAccounts.BANK_BRANCH_ID          = BankBranchSimplePEO.BRANCH_PARTY_ID)
      AND (CeBankAccounts.RECON_RULESET_ID        = BankStatementReconRuleSetPEO.RECON_RULESET_ID (+))
      AND NOT EXISTS
        (SELECT xtr.bank_account_id
        FROM ce_bank_accounts xtr
        WHERE NVL(AP_USE_ALLOWED_FLAG, 'N') = 'N'
        AND NVL(AR_USE_ALLOWED_FLAG, 'N')   = 'N'
        AND NVL(PAY_USE_ALLOWED_FLAG, 'N')  = 'N'
        AND NVL(XTR_USE_ALLOWED_FLAG, 'N')  = 'Y'
        AND xtr.bank_account_id             = CeBankAccounts.bank_account_id
        ))
) Head
, 
(
   SELECT  CeContactAssignments.BANK_ACCOUNT_ID,
     SubjectPartyEO.PARTY_NAME,
    (SELECT MEANING
     FROM FND_LOOKUP_VALUES
     WHERE LOOKUP_TYPE = 'CONTACT_POINT_PURPOSE'
     AND LOOKUP_CODE   =  EmailEO.CONTACT_POINT_PURPOSE
    )                    AS RES_PURPOSE,
    EmailEO.PRIMARY_FLAG,
    EmailEO.EMAIL_ADDRESS,
    EmailEO.CONTACT_POINT_ID ,     
    EmailEO.CONTACT_POINT_TYPE,
	
	EmailEO.ATTRIBUTE_CATEGORY 
,EmailEO.ATTRIBUTE1 
,EmailEO.ATTRIBUTE2
,EmailEO.ATTRIBUTE3
,EmailEO.ATTRIBUTE4
,EmailEO.ATTRIBUTE5
,EmailEO.ATTRIBUTE6
,EmailEO.ATTRIBUTE7
,EmailEO.ATTRIBUTE8
,EmailEO.ATTRIBUTE9
,EmailEO.ATTRIBUTE10
,EmailEO.ATTRIBUTE11
,EmailEO.ATTRIBUTE12
,EmailEO.ATTRIBUTE13
,EmailEO.ATTRIBUTE14
,EmailEO.ATTRIBUTE15
,EmailEO.ATTRIBUTE16
,EmailEO.ATTRIBUTE17
,EmailEO.ATTRIBUTE18
,EmailEO.ATTRIBUTE19
,EmailEO.ATTRIBUTE20

,EmailEO.ATTRIBUTE21
,EmailEO.ATTRIBUTE22
,EmailEO.ATTRIBUTE23
,EmailEO.ATTRIBUTE24
,EmailEO.ATTRIBUTE25
,EmailEO.ATTRIBUTE26
,EmailEO.ATTRIBUTE27
,EmailEO.ATTRIBUTE28
,EmailEO.ATTRIBUTE29
,EmailEO.ATTRIBUTE30
,EmailEO.ATTRIBUTE_NUMBER1 
,EmailEO.ATTRIBUTE_NUMBER2
,EmailEO.ATTRIBUTE_NUMBER3
,EmailEO.ATTRIBUTE_NUMBER4
,EmailEO.ATTRIBUTE_NUMBER5
,EmailEO.ATTRIBUTE_NUMBER6
,EmailEO.ATTRIBUTE_NUMBER7
,EmailEO.ATTRIBUTE_NUMBER8
,EmailEO.ATTRIBUTE_NUMBER9
,EmailEO.ATTRIBUTE_NUMBER10
,EmailEO.ATTRIBUTE_NUMBER11
,EmailEO.ATTRIBUTE_NUMBER12
,EmailEO.ATTRIBUTE_DATE1 
,EmailEO.ATTRIBUTE_DATE2
,EmailEO.ATTRIBUTE_DATE3
,EmailEO.ATTRIBUTE_DATE4
,EmailEO.ATTRIBUTE_DATE5
,EmailEO.ATTRIBUTE_DATE6
,EmailEO.ATTRIBUTE_DATE7
,EmailEO.ATTRIBUTE_DATE8
,EmailEO.ATTRIBUTE_DATE9
,EmailEO.ATTRIBUTE_DATE10
,EmailEO.ATTRIBUTE_DATE11
,EmailEO.ATTRIBUTE_DATE12	
    ,EmailEO.LAST_UPDATED_BY  						
    ,EmailEO.LAST_UPDATE_DATE  						
    ,EmailEO.CREATED_BY  								
    ,EmailEO.CREATION_DATE 

  FROM CE_CONTACT_ASSIGNMENTS CeContactAssignments,
	  HZ_RELATIONSHIPS RelationshipEO,
	  HZ_ORG_CONTACTS OrganizationContactEO,
	  HZ_PARTY_SITES ContactPartySiteEO,
	  HZ_PARTIES SubjectPartyEO,
	  HZ_CONTACT_POINTS EmailEO
	WHERE CeContactAssignments.RELATIONSHIP_ID         = RelationshipEO.RELATIONSHIP_ID
	AND  RelationshipEO.RELATIONSHIP_ID               = OrganizationContactEO.PARTY_RELATIONSHIP_ID(+)
	AND  RelationshipEO.RELATIONSHIP_ID               = ContactPartySiteEO.RELATIONSHIP_ID(+)
	AND RelationshipEO.SUBJECT_ID                      = ContactPartySiteEO.PARTY_ID(+)
	AND  CeContactAssignments.ASSIGNMENT_TYPE = 'ACCOUNT' 
	AND  RelationshipEO.RELATIONSHIP_ID = EmailEO.RELATIONSHIP_ID(+)
	AND RelationshipEO.SUBJECT_ID        = EmailEO.OWNER_TABLE_ID(+)
	AND EmailEO.OWNER_TABLE_NAME(+)      = 'HZ_PARTIES'
	AND EmailEO.CONTACT_POINT_TYPE    = 'EMAIL'
	AND RelationshipEO.SUBJECT_ID                = SubjectPartyEO.PARTY_ID
	
	AND (EmailEO.ATTRIBUTE_CATEGORY IS NOT NULL OR
EmailEO.ATTRIBUTE1 IS NOT NULL OR 
EmailEO.ATTRIBUTE2 IS NOT NULL OR 
EmailEO.ATTRIBUTE3 IS NOT NULL OR 
EmailEO.ATTRIBUTE4 IS NOT NULL OR 
EmailEO.ATTRIBUTE5 IS NOT NULL OR 
EmailEO.ATTRIBUTE6 IS NOT NULL OR 
EmailEO.ATTRIBUTE7 IS NOT NULL OR 
EmailEO.ATTRIBUTE8 IS NOT NULL OR 
EmailEO.ATTRIBUTE9 IS NOT NULL OR 
EmailEO.ATTRIBUTE10 IS NOT NULL OR 
EmailEO.ATTRIBUTE11 IS NOT NULL OR 
EmailEO.ATTRIBUTE12 IS NOT NULL OR 
EmailEO.ATTRIBUTE13 IS NOT NULL OR 
EmailEO.ATTRIBUTE14 IS NOT NULL OR 
EmailEO.ATTRIBUTE15 IS NOT NULL OR 
EmailEO.ATTRIBUTE16 IS NOT NULL OR 
EmailEO.ATTRIBUTE17 IS NOT NULL OR 
EmailEO.ATTRIBUTE18 IS NOT NULL OR 
EmailEO.ATTRIBUTE19 IS NOT NULL OR 
EmailEO.ATTRIBUTE20 IS NOT NULL OR
EmailEO.ATTRIBUTE21 IS NOT NULL OR 
EmailEO.ATTRIBUTE22 IS NOT NULL OR 
EmailEO.ATTRIBUTE23 IS NOT NULL OR 
EmailEO.ATTRIBUTE24 IS NOT NULL OR 
EmailEO.ATTRIBUTE25 IS NOT NULL OR 
EmailEO.ATTRIBUTE26 IS NOT NULL OR 
EmailEO.ATTRIBUTE27 IS NOT NULL OR 
EmailEO.ATTRIBUTE28 IS NOT NULL OR 
EmailEO.ATTRIBUTE29 IS NOT NULL OR 
EmailEO.ATTRIBUTE30 IS NOT NULL OR
EmailEO.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER11 IS NOT NULL OR 
EmailEO.ATTRIBUTE_NUMBER12 IS NOT NULL OR
EmailEO.ATTRIBUTE_DATE1 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE2 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE3 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE4 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE5 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE6 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE7 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE8 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE9 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE10 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE11 IS NOT NULL OR 
EmailEO.ATTRIBUTE_DATE12 IS NOT NULL )

) Detail

WHERE Head.BANK_ACCOUNT_ID =   Detail.BANK_ACCOUNT_ID
ORDER BY RES_BANK ,  RES_COUNTRY , RES_ACCOUNT_NAME,  RES_CONTACT_NAME


