/* ****************************************************************************
* $Revision: 55345 $:
* $Author: wuttipong.thongvises $:
* $Date: 2016-05-23 12:42:33 +0700 (Mon, 23 May 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/
FINANCIALS/Manage%20Server%20Configurations%20-%20Manage%20Data%20Quality%20Server%20Configurations.sql $:
* $Id: Manage Server Configurations - Manage Data Quality Server Configurations.sql 55345 2016-05-23 05:42:33Z
wuttipong.thongvises $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- REPLACE_HTML_KEYWORD = RES_FORMULA_TEXT

/*<RSC_PRE_STEPS_LARGE_COLUMN_POSITION>10</RSC_PRE_STEPS_LARGE_COLUMN_POSITION>
	
-- The column position that using special data type.
 <RSC_PRE_STEPS_LARGE_COLUMN_TYPE>LONG</RSC_PRE_STEPS_LARGE_COLUMN_TYPE>

-- Specify what type of the data.
*/

SELECT ffFORMULAEO.FORMULA_NAME RES_FORMULA_NAME
,(SELECT FORMULA_TYPE_NAME FROM FF_FORMULA_TYPES WHERE FORMULA_TYPE_ID = ffFORMULAEO.FORMULA_TYPE_ID) RES_TYPE
,TO_CHAR(ffFORMULAEO.DESCRIPTION) RES_DESCRIPTION
,(SELECT NAME FROM PER_LEGISLATIVE_DATA_GROUPS_TL WHERE LEGISLATIVE_DATA_GROUP_ID = ffFORMULAEO.LEGISLATIVE_DATA_GROUP_ID AND LANGUAGE = USERENV('LANG')) RES_LEGISLATIVE_DATA_GROUP
,TO_CHAR(ffFORMULAEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,TO_CHAR(ffFORMULAEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_END_DATE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = ffFORMULAEO.EDIT_STATUS
	AND LOOKUP_TYPE =  'FF_DATA_TYPE' AND LANGUAGE = USERENV('LANG') 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_TYPE_OF_EDITOR
,DECODE(ffFORMULAEO.COMPILE_FLAG,'N','Not Compiled','Compiled') RES_COMPILE_STATUS
,REPLACE(REPLACE(REPLACE(ffFORMULAEO.FORMULA_TEXT,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#')  RES_FORMULA_TEXT

,ffFORMULAEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,ffFORMULAEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,ffFORMULAEO.CREATED_BY  RSC_CREATED_BY
,ffFORMULAEO.CREATION_DATE  RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,(SELECT LEGISLATION_CODE 
	FROM PER_LEGISLATIVE_DATA_GROUPS 
	WHERE LEGISLATIVE_DATA_GROUP_ID = ffFORMULAEO.LEGISLATIVE_DATA_GROUP_ID 
	) RSC_COUNTRY_ID

FROM FF_FORMULAS_VL ffFORMULAEO
ORDER BY ffFORMULAEO.FORMULA_NAME , RES_TYPE , ffFORMULAEO.EFFECTIVE_START_DATE