/* ****************************************************************************
 * $Revision: 56510 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-07-06 09:21:36 +0700 (Wed, 06 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Locations%20(United%20States)%20-%20Manage%20Locations.sql $:
 * $Id: Manage Locations (United States) - Manage Locations.sql 56510 2016-07-06 02:21:36Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 
SELECT (SELECT CLASSIFICATION_NAME FROM PAY_ELE_CLASSIFICATIONS_VL 
			WHERE CLASSIFICATION_ID = elementsTYPE0.CLASSIFICATION_ID) RES_PRIMARY_CLASSIFICATION
,(SELECT ELEMENT_NAME
    FROM PAY_ELEMENT_TYPES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND ELEMENT_TYPE_ID = elementsE0.ELEMENT_TYPE_ID
    ) RES_ELEMENT_NAME
,accountsE0.PROPORTION *100 RES_PERCENTAGE
,FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'PAY'
    ,KEY_FLEX_CODE => (SELECT KEY_FLEXFIELD_CODE FROM FND_KF_STR_INSTANCES_VL WHERE STRUCTURE_INSTANCE_NUMBER = accountsE0.ID_FLEX_NUM)
    ,STRUCTURE_NUMBER => accountsE0.ID_FLEX_NUM
    ,COMBINATION_ID => accountsE0.COST_ALLOCATION_KEYFLEX_ID
    ) RES_ACCOUNT

,costElesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,costElesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,costElesE0.CREATED_BY RSC_CREATED_BY
,costElesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID


FROM PAY_COST_INFO_F costElesE0
,PAY_ELEMENT_LINKS_F elementsE0
,(SELECT *
    FROM PAY_COST_ALLOCATIONS_F
    WHERE SOURCE_TYPE = 'EL'
    ) costLinksE0
,(SELECT *
    FROM PAY_COST_ALLOC_ACCOUNTS
    WHERE SOURCE_SUB_TYPE = 'OVRRIDE'
    ) accountsE0
,PAY_ELEMENT_TYPES_VL elementsTYPE0

WHERE costElesE0.SOURCE_TYPE = 'EL'
AND costElesE0.SOURCE_ID = elementsE0.ELEMENT_LINK_ID
AND costElesE0.SOURCE_ID = costLinksE0.SOURCE_ID
AND costElesE0.EFFECTIVE_START_DATE = costLinksE0.EFFECTIVE_START_DATE
AND costElesE0.EFFECTIVE_END_DATE= costLinksE0.EFFECTIVE_END_DATE
AND elementsE0.ELEMENT_TYPE_ID = elementsTYPE0.ELEMENT_TYPE_ID(+)
AND costLinksE0.COST_ALLOCATION_RECORD_ID = accountsE0.COST_ALLOCATION_RECORD_ID
ORDER BY RES_PRIMARY_CLASSIFICATION,RES_ELEMENT_NAME