/* ****************************************************************************
* $Revision: 55454 $:
* $Author: dhara.pithadiya $:
* $Date: 2016-05-25 18:58:04 +0700 (Wed, 25 May 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20AutoInvoice%20Line%20Ordering%20Rules%20-%20AutoInvoice%20Line%20Ordering%20Rules%20-%20DFF.sql $:
* $Id: Manage AutoInvoice Line Ordering Rules - AutoInvoice Line Ordering Rules - DFF.sql 55454 2016-05-25 11:58:04Z dhara.pithadiya $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=707##RES##CST_ELEMENT_GROUP_DETAILS
-- DFF_ATTRIBUTES=ATTRIBUTE_CHAR,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT:
--  - the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.

SELECT DECODE(CstElementGrpE0.COST_ORGANIZATION_ID,NULL,'All'
	,(SELECT NAME
		FROM HR_ORGANIZATION_V
		WHERE CLASSIFICATION_CODE = 'CST'
		AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
		AND ORGANIZATION_ID = CstElementGrpE0.COST_ORGANIZATION_ID
		)
	) RES_COST_ORGANIZATION
,CstElementGrpE0.GROUP_CODE RES_GROUP_NAME
,CostElementPEO.COST_ELEMENT_CODE RES_COST_ELEMENT
,CstElementGrpDetailsE0.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR1
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR2
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR3
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR4
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR5
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR6
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR7
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR8
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR9
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR10
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR11
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR12
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR13
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR14
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR15
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR16
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR17
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR18
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR19
,CstElementGrpDetailsE0.ATTRIBUTE_CHAR20
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER1
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER2
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER3
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER4
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER5
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER6
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER7
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER8
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER9
,CstElementGrpDetailsE0.ATTRIBUTE_NUMBER10
,TO_CHAR(CstElementGrpDetailsE0.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(CstElementGrpDetailsE0.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(CstElementGrpDetailsE0.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(CstElementGrpDetailsE0.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(CstElementGrpDetailsE0.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP1
,CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP2
,CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP3
,CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP4
,CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP5
,CstElementGrpDetailsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,CstElementGrpDetailsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,CstElementGrpDetailsE0.CREATED_BY RSC_CREATED_BY
,CstElementGrpDetailsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,CstElementGrpE0.COST_ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CST_COST_ELEMENT_GRPS_VL CstElementGrpE0
,CST_ELEMENT_GROUP_DETAILS CstElementGrpDetailsE0
,CST_COST_ELEMENTS_VL CostElementPEO
WHERE CstElementGrpE0.GROUP_ID = CstElementGrpDetailsE0.GROUP_ID
AND CstElementGrpDetailsE0.COST_ELEMENT_ID = CostElementPEO.COST_ELEMENT_ID
AND (CstElementGrpDetailsE0.ATTRIBUTE_CATEGORY IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR1       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR2       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR3       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR4       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR5       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR6       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR7       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR8       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR9       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR10      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR11      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR12      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR13      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR14      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR15      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR16      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR17      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR18      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR19      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_CHAR20      IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER1     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER2     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER3     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER4     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER5     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER6     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER7     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER8     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER9     IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_NUMBER10    IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_DATE1       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_DATE2       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_DATE3       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_DATE4       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_DATE5       IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP1  IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP2  IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP3  IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP4  IS NOT NULL
OR CstElementGrpDetailsE0.ATTRIBUTE_TIMESTAMP5  IS NOT NULL)
ORDER BY DECODE(CstElementGrpE0.IS_SEED,'Y',1,2),1,2,3