/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2017-11-08 $:
 * $HeadURL:  $:
 * $Id: Manage Standard Operations - Resources - DFF.sql $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10494##RES##WIS_STD_OPERATION_RESOURCES
-- DFF_ATTRIBUTES=ATTRIBUTE_CHAR,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields. 

-- RSC_PREREQUISITE_OBJECTS=WIS_STANDARD_OPERATIONS_VL
-- RSC_PREREQUISITE_OBJECTS=WIS_STD_OPERATION_RESOURCES
-- RSC_PREREQUISITE_OBJECTS=WIS_RESOURCES_VL

SELECT Distinct 
( SELECT ORGANIZATION_CODE 
  FROM INV_ORGANIZATION_DEFINITIONS_V
  WHERE ORGANIZATION_ID = STAN.ORGANIZATION_ID )                                    RES_ORGANIZATION,
STAN.STANDARD_OPERATION_NAME                                                        RES_NAME,
RSC.RESOURCE_SEQ_NUMBER 															RES_SEQUENCE,
RSC.ATTRIBUTE_CATEGORY 															    RES_CONTEXT_CODE
,RSC.ATTRIBUTE_CHAR1
,RSC.ATTRIBUTE_CHAR2
,RSC.ATTRIBUTE_CHAR3
,RSC.ATTRIBUTE_CHAR4
,RSC.ATTRIBUTE_CHAR5
,RSC.ATTRIBUTE_CHAR6
,RSC.ATTRIBUTE_CHAR7
,RSC.ATTRIBUTE_CHAR8
,RSC.ATTRIBUTE_CHAR9
,RSC.ATTRIBUTE_CHAR10
,RSC.ATTRIBUTE_CHAR11
,RSC.ATTRIBUTE_CHAR12
,RSC.ATTRIBUTE_CHAR13
,RSC.ATTRIBUTE_CHAR14
,RSC.ATTRIBUTE_CHAR15
,RSC.ATTRIBUTE_CHAR16
,RSC.ATTRIBUTE_CHAR17
,RSC.ATTRIBUTE_CHAR18
,RSC.ATTRIBUTE_CHAR19
,RSC.ATTRIBUTE_CHAR20
,RSC.ATTRIBUTE_NUMBER1
,RSC.ATTRIBUTE_NUMBER2
,RSC.ATTRIBUTE_NUMBER3
,RSC.ATTRIBUTE_NUMBER4
,RSC.ATTRIBUTE_NUMBER5
,RSC.ATTRIBUTE_NUMBER6
,RSC.ATTRIBUTE_NUMBER7
,RSC.ATTRIBUTE_NUMBER8
,RSC.ATTRIBUTE_NUMBER9
,RSC.ATTRIBUTE_NUMBER10
,TO_CHAR(RSC.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(RSC.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(RSC.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(RSC.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(RSC.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,RSC.ATTRIBUTE_TIMESTAMP1
,RSC.ATTRIBUTE_TIMESTAMP2
,RSC.ATTRIBUTE_TIMESTAMP3
,RSC.ATTRIBUTE_TIMESTAMP4
,RSC.ATTRIBUTE_TIMESTAMP5
,RSC.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,RSC.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,RSC.CREATED_BY RSC_CREATED_BY
,RSC.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,STAN.ORGANIZATION_ID  RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM  WIS_STANDARD_OPERATIONS_VL  STAN
	 , WIS_STD_OPERATION_RESOURCES  RSC
	 , WIS_RESOURCES_VL  AAA
WHERE STAN.STANDARD_OPERATION_ID =  RSC.STANDARD_OPERATION_ID 
and  RSC.RESOURCE_ID  = AAA.RESOURCE_ID

and (RSC.ATTRIBUTE_CATEGORY IS NOT NULL
OR RSC.ATTRIBUTE_CHAR1            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR2            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR3            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR4            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR5            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR6            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR7            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR8            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR9            IS NOT NULL
OR RSC.ATTRIBUTE_CHAR10           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR11           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR12           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR13           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR14           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR15           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR16           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR17           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR18           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR19           IS NOT NULL
OR RSC.ATTRIBUTE_CHAR20           IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER1     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER2     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER3     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER4     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER5     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER6     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER7     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER8     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER9     IS NOT NULL
OR RSC.ATTRIBUTE_NUMBER10    IS NOT NULL
OR RSC.ATTRIBUTE_DATE1       IS NOT NULL
OR RSC.ATTRIBUTE_DATE2       IS NOT NULL
OR RSC.ATTRIBUTE_DATE3       IS NOT NULL
OR RSC.ATTRIBUTE_DATE4       IS NOT NULL
OR RSC.ATTRIBUTE_DATE5       IS NOT NULL
OR RSC.ATTRIBUTE_TIMESTAMP1  IS NOT NULL
OR RSC.ATTRIBUTE_TIMESTAMP2  IS NOT NULL
OR RSC.ATTRIBUTE_TIMESTAMP3  IS NOT NULL
OR RSC.ATTRIBUTE_TIMESTAMP4  IS NOT NULL
OR RSC.ATTRIBUTE_TIMESTAMP5  IS NOT NULL)
ORDER BY STAN.STANDARD_OPERATION_NAME