/* ****************************************************************************
 * $Revision: 72749 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2019-10-23 15:22:46 +0700 (Wed, 23 Oct 2019) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Availability%20Lookups%20-%20Lookup%20Types.sql $:
 * $Id: Manage Availability Lookups - Lookup Types.sql 72749 2019-10-23 08:22:46Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
SELECT cmpPLANEO.PLAN_NAME RES_PLAN
,cmpINTCEPGROUPE0.GROUP_NAME  RES_ALTERNATE_APPROVER_TABLE
,(SELECT LIST_NAME FROM PER_PERSON_NAMES_F WHERE PERSON_ID = perALLME0.PERSON_ID AND NAME_TYPE = 'GLOBAL') RES_WORKSHEET_MANAGER
,cmpINTCEPAPPE0.ORDER_NUM RES_APPROVAL_SEQUENCE
,(SELECT LIST_NAME FROM PER_PERSON_NAMES_F WHERE PERSON_ID = appASSIGNE0.PERSON_ID AND NAME_TYPE = 'GLOBAL') RES_ALTERNATE_APPROVER

,cmpINTCEPAPPE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,cmpINTCEPAPPE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,cmpINTCEPAPPE0.CREATED_BY RSC_CREATED_BY
,cmpINTCEPAPPE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CMP_PLANS_VL cmpPLANEO
,CMP_INTERCEPT_APPROVERS cmpINTCEPAPPE0
,CMP_INTERCEPT_GROUPS cmpINTCEPGROUPE0
,PER_ALL_ASSIGNMENTS_M perALLME0
,(SELECT INTERCEPT_APPROVER_ID,PERSON_ID
	FROM PER_ALL_ASSIGNMENTS_M perALL,CMP_INTERCEPT_APPROVERS cmpIN  
	WHERE perALL.ASSIGNMENT_ID = cmpIN.APPROVER_ASSIGNMENT_ID 
	AND SYSDATE BETWEEN perALL.EFFECTIVE_START_DATE AND perALL.EFFECTIVE_END_DATE) appASSIGNE0
	
WHERE cmpPLANEO.INTERCEPT_GROUP_ID  = cmpINTCEPAPPE0.INTERCEPT_GROUP_ID 
AND cmpINTCEPAPPE0.MANAGER_ASSIGNMENT_ID  = perALLME0.ASSIGNMENT_ID
AND SYSDATE BETWEEN perALLME0.EFFECTIVE_START_DATE AND perALLME0.EFFECTIVE_END_DATE
AND cmpINTCEPAPPE0.INTERCEPT_APPROVER_ID = appASSIGNE0.INTERCEPT_APPROVER_ID
AND cmpPLANEO.INTERCEPT_GROUP_ID  = cmpINTCEPGROUPE0.INTERCEPT_GROUP_ID 
AND cmpPLANEO.COMP_TYPE = 'CWB'
ORDER BY cmpPLANEO.PLAN_NAME