/* ****************************************************************************
 * $Revision: 53782 $:
 * $Author: nasrullah.dusenmahamad $:
 * $Date: 2016-03-31 18:00:16 +0700 (Tue, 22 Mar 2016) $:
 * $HeadURL: $:
 * $Id: Manage Enterprise HCM Information - Attachments.sql 53782 2016-03-22 11:00:16Z nasrullah.dusenmahamad $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EXM_ACCOM_POLICIES

SELECT 'Accommodations' RES_EXPENSE_CATEGORY
,ExmAccomPolicies.POLICY_NAME RES_POLICY_NAME
,ExmAccomPolicies.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_CURRENCY_OPTION'
	AND LOOKUP_CODE = ExmAccomPolicies.CURRENCY_OPTION_CODE
	) RES_RATE_CURRENCY
,(CASE
	WHEN ExmAccomPolicies.CURRENCY_OPTION_CODE = 'MULTIPLE' THEN
		NULL
	ELSE
		ExmAccomPolicies.CURRENCY_CODE||' - '||
		(SELECT NAME 
			FROM FND_CURRENCIES_TL
			WHERE CURRENCY_CODE = ExmAccomPolicies.CURRENCY_CODE
			AND LANGUAGE = USERENV('LANG'))
	END) RES_CURRENCY
,DECODE(ExmAccomPolicies.ENABLED_ROLE_FLAG,'Y','Yes','No') RES_ROLE
,(CASE
	WHEN ExmAccomPolicies.ENABLED_ROLE_FLAG = 'Y' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_POLICY_ROLE'
		AND LOOKUP_CODE = ExmAccomPolicies.POLICY_ROLE_CODE)
	END) RES_ROLE_TYPE
,DECODE(ExmAccomPolicies.ENABLED_LOCATION_FLAG,'Y','Yes','No') RES_LOCATION
,(CASE
	WHEN ExmAccomPolicies.ENABLED_LOCATION_FLAG = 'Y' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_LOCATION_TYPE'
		AND LOOKUP_CODE = ExmAccomPolicies.LOCATION_TYPE_CODE)
	END) RES_LOCATION_TYPE
,(CASE
	WHEN ExmAccomPolicies.ENABLED_LOCATION_FLAG = 'Y' AND ExmAccomPolicies.LOCATION_TYPE_CODE = 'ZONE' THEN
		(SELECT MEANING 
			FROM FND_LOOKUP_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = ExmAccomPolicies.ZONE_TYPE_CODE)
	END) RES_ZONE_TYPE
,DECODE(ExmAccomPolicies.ENABLED_SEASON_RATE_FLAG,'Y','Yes','No') RES_SEASONAL_RATE
,DECODE(ExmAccomPolicies.ENABLED_GENDER_FLAG,'Y','Yes','No') RES_GENDER
,(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_POLICY_ENFORCEMENT'
		AND LOOKUP_CODE = ExmAccomPolicies.POLICY_ENFORCEMENT_CODE
		) RES_POLICY_ENFORCEMENT
,(CASE
	WHEN ExmAccomPolicies.POLICY_ENFORCEMENT_CODE = 'VIOLATION' THEN
		DECODE(ExmAccomPolicies.POLICY_VIOLATION_FLAG,'Y','Yes','No')
	END) RES_POLICY_VIOLATION_WARNING
,ExmAccomPolicies.WARNING_TOLERANCE RES_WARNING_TOLERANCE_PERCENTA
,(CASE
	WHEN ExmAccomPolicies.POLICY_ENFORCEMENT_CODE = 'VIOLATION' AND ExmAccomPolicies.POLICY_VIOLATION_FLAG = 'Y' THEN
		DECODE(ExmAccomPolicies.DISP_WARNING_TO_USER_FLAG,'Y','Yes','No')
	END) RES_DISPLAY_WARNING_TO_USER
,(CASE
	WHEN ExmAccomPolicies.POLICY_ENFORCEMENT_CODE = 'VIOLATION' THEN
		DECODE(ExmAccomPolicies.PREVENT_SUBMISSION_FLAG,'Y','Yes','No')
	END) RES_PREVENT_REPORT_SUBMISSION
,ExmAccomPolicies.ERROR_TOLERANCE RES_ERROR_TOLERANCE_PERCENTAGE
,ExmAccomPolicies.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ExmAccomPolicies.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ExmAccomPolicies.CREATED_BY RSC_CREATED_BY
,ExmAccomPolicies.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EXM_ACCOM_POLICIES ExmAccomPolicies
ORDER BY ExmAccomPolicies.POLICY_NAME