/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Document%20Types%20-%20Document%20Type.sql $:
 * $Id: Manage Document Types - Document Type.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 -- RSC_PREREQUISITE_OBJECTS=HR_DOCUMENT_TYPES_VL
 
SELECT (SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_TYPE = 'ORA_PER_DOCUMENT_TYPE_LEVEL' 
	AND LOOKUP_CODE = hrDOCTYPEEO.DOCUMENT_TYPE_LEVEL
	AND LANGUAGE = USERENV('LANG') 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('31-12-4712','DD-MM-YYYY')) 
	) RES_DOCUMENT_TYPE_LEVEL
,hrDOCTYPEEO.DOCUMENT_TYPE RES_TYPE
,hrDOCTYPEEO.DESCRIPTION RES_DESCRIPTION
,hrDOCTYPEEO.WARNING_PERIOD RES_EXPIRATION_NOTIFICATION_PE
,hrDOCTYPEEO.MIN_ATTACHMENTS_COUNT RES_MINIMUM_ATTACHMENTS
,hrDOCTYPEEO.BI_REPORT_PATH RES_REPORT_PATH
,NVL((SELECT TERRITORY_SHORT_NAME FROM FND_TERRITORIES_VL WHERE TERRITORY_CODE = hrDOCTYPEEO.LEGISLATION_CODE),'All Countries') RES_COUNTRY
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_TYPE = 'DOCUMENT_CATEGORY' 
	AND LOOKUP_CODE = hrDOCTYPEEO.CATEGORY_CODE
	AND LANGUAGE = USERENV('LANG') 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('31-12-4712','DD-MM-YYYY')) 
	) RES_CATEGORY
,(SELECT EXTENDED_LOOKUP_CODE_NAME 
	FROM HCM_EXTENDED_LOOKUP_CODES_VL 
	WHERE LOOKUP_TYPE = 'DOCUMENT_CATEGORY' 
	AND LOOKUP_CODE = hrDOCTYPEEO.CATEGORY_CODE
	AND EXTENDED_LOOKUP_CODE = hrDOCTYPEEO.SUB_CATEGORY_CODE
	) RES_SUBCATEGORY
,DECODE(hrDOCTYPEEO.ACTIVE_INACTIVE_FLAG,'Y','Active','Inactive') RES_STATUS
,DECODE(hrDOCTYPEEO.AUTHORIZATION_REQUIRED,'Y','Yes','No') RES_APPROVAL_REQUIRED
,DECODE(hrDOCTYPEEO.MULTIPLE_OCCURENCES_FLAG,'Y','Yes','No') RES_ALLOW_MULTIPLE_OCCURRENCES
,DECODE(hrDOCTYPEEO.PUBLISH_REQUIRED,'Y','Yes','No')  RES_PUBLISH_REQUIRED
,(CASE WHEN hrDOCTYPEEO.HIERARCHY_CODE IS NOT NULL THEN
	'Yes'
	ELSE
	'No' 
	END) RES_ENABLE_DOCUMENT_DELIVERY_P
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_TYPE = 'DOCUMENT_HIERARCHY' 
	AND LOOKUP_CODE = hrDOCTYPEEO.HIERARCHY_CODE 
	AND LANGUAGE = USERENV('LANG') AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('31-12-4712','DD-MM-YYYY')) 
	) RES_OVERRIDE_HIERARCHY
,DECODE(hrDOCTYPEEO.RESTRICT_CREATE_ATTACH,'Y','Yes','No') RES_RESTRICT_CREATE
,DECODE(hrDOCTYPEEO.RESTRICT_UPDATE_ATTACH,'Y','Yes','No') RES_RESTRICT_UPDATE
,DECODE(hrDOCTYPEEO.RESTRICT_DELETE_ATTACH,'Y','Yes','No') RES_RESTRICT_DELETE

,(CASE 
	WHEN hrDOCTYPEEO.HIERARCHY_CODE IS NOT NULL THEN
		DECODE(heDocRefsE0.ONLINE_ENABLED,'Y','Yes','No')
	END) RES_DELIVERY_METHOD_ONLINE
,(CASE 
	WHEN hrDOCTYPEEO.HIERARCHY_CODE IS NOT NULL THEN
		DECODE(heDocRefsE0.PAPER_ENABLED,'Y','Yes','No')
	END) RES_DELIVERY_METHOD_PAPER
,(CASE 
	WHEN hrDOCTYPEEO.HIERARCHY_CODE IS NOT NULL THEN
		DECODE(heDocRefsE0.ONLINE_CONSENT_REQ,'Y','Yes','No')
	END) RES_ONLINE_DELIVERY_CONSENT_RE
,(CASE 
	WHEN hrDOCTYPEEO.HIERARCHY_CODE IS NOT NULL THEN
		DECODE(heDocRefsE0.ALLOW_WORKER_OVERRIDE,'Y','Yes','No')
	END) RES_ALLOW_PERSON_LEVEL_OVERRID
/*,(CASE 
	WHEN hrDOCTYPEEO.HIERARCHY_CODE IS NOT NULL THEN
		(CASE
			WHEN hrDOCTYPEEO.HIERARCHY_CODE = 'GENERAL' THEN
				(SELECT NAME
					FROM HR_ORGANIZATION_UNITS
					WHERE SYSDATE BETWEEN DATE_FROM AND DATE_TO
					AND ORGANIZATION_ID = heDocRefsE0.LEMP_ID)
			WHEN hrDOCTYPEEO.HIERARCHY_CODE = 'PAYROLL' THEN
				(SELECT NAME
					FROM HR_ORGANIZATION_UNITS
					WHERE SYSDATE BETWEEN DATE_FROM AND DATE_TO
					AND ORGANIZATION_ID = heDocRefsE0.PSU_ID)
		END)
	END) RES_LEGAL_EMPLOYER_PAYROLL_STA*/
,'' RES_LEGAL_EMPLOYER_PAYROLL_STA
,hrDOCTYPEEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hrDOCTYPEEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hrDOCTYPEEO.CREATED_BY RSC_CREATED_BY
,hrDOCTYPEEO.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,hrDOCTYPEEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM HR_DOCUMENT_TYPES_VL hrDOCTYPEEO
,HR_DOCUMENT_DELIVERY_PREFS heDocRefsE0
WHERE hrDOCTYPEEO.DOCUMENT_TYPE_ID = heDocRefsE0.DOCUMENT_TYPE_ID(+)
ORDER BY hrDOCTYPEEO.ACTIVE_INACTIVE_FLAG 
,hrDOCTYPEEO.DOCUMENT_TYPE