/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- REPLACE_HTML_KEYWORD = RES_UNIQUE_REFERENCE

SELECT elementsE0.ELEMENT_NAME RES_ELEMENT_NAME
,legislativeDataGrpsE0.NAME RES_LEGISLATIVE_DATA_GROUP
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
	WHERE BASE_CLASSIFICATION_ID = elementsE0.CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PRIMARY_CLASSIFICATION
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
    WHERE BASE_CLASSIFICATION_ID = elementsE0.SECONDARY_CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
    ) RES_SECONDARY_CLASSIFICATION
,TO_CHAR(paycalunitE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,REPLACE(REPLACE(REPLACE(paycalunitE0.CONTEXT_VALUE1,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#') RES_UNIQUE_REFERENCE
,(SELECT NAME FROM PAY_CALC_METHODS_TL WHERE CALC_METHOD_ID = paycalunitE0.CALC_METHOD_ID AND LANGUAGE = USERENV('LANG')) RES_CALCULATION_METHOD
,(SELECT NAME FROM PAY_CALC_PARTS_TL WHERE CALC_PART_ID = paycalunitE0.CALC_PART_ID AND LANGUAGE = USERENV('LANG')) RES_CALCULATION_STEP
,(SELECT NAME FROM PAY_VALUE_DEFINITIONS_VL WHERE VALUE_DEFN_ID = paycalunitE0.VALUE_DEFN_ID 
		AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_CALCULATION_VALUE_DEFINITI
,(SELECT BASE_NAME FROM PAY_VALUE_DEFINITIONS_VL WHERE VALUE_DEFN_ID = paycalunitE0.VALUE_DEFN_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))RES_CALCULATION_VALUE_DEFINI_0
,NULL RES_RANGE_VALUES
,(SELECT LEGISLATION_CODE FROM PER_LEGISLATIVE_DATA_GROUPS_VL WHERE LEGISLATIVE_DATA_GROUP_ID = paycalunitE0.LEGISLATIVE_DATA_GROUP_ID)RES_COUNTRY
,DECODE(TO_CHAR(paycalunitE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY'),'31-12-4712',NULL,TO_CHAR(paycalunitE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE

,paycalunitE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,paycalunitE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,paycalunitE0.CREATED_BY RSC_CREATED_BY
,paycalunitE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legislativeDataGrpsE0.LEGISLATION_CODE RSC_COUNTRY_ID


FROM PAY_ELEMENT_TYPES_VL elementsE0
,PAY_CALCULATION_UNITS_F paycalunitE0
,(SELECT NAME
    ,LEGISLATIVE_DATA_GROUP_ID
	,LEGISLATION_CODE
    FROM PER_LEGISLATIVE_DATA_GROUPS_VL
    )legislativeDataGrpsE0
	
WHERE elementsE0.LEGISLATIVE_DATA_GROUP_ID = legislativeDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID
AND elementsE0.ELEMENT_TYPE_ID = paycalunitE0.ELEMENT_TYPE_ID
--AND SYSDATE BETWEEN ruleE0.EFFECTIVE_START_DATE AND NVL(ruleE0.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
--AND SYSDATE BETWEEN elementsE0.EFFECTIVE_START_DATE AND NVL(elementsE0.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
ORDER BY elementsE0.ELEMENT_NAME,paycalunitE0.EFFECTIVE_START_DATE


