/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Billing%20Cycles%20-%20Billing%20Cycles.sql $:
 * $Id: Manage Billing Cycles - Billing Cycles.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT pjfBILLCYCLEEO.BILLING_CYCLE_NAME  RES_NAME
,pjfBILLCYCLEEO.BILLING_CYCLE_DESC  RES_DESCRIPTION
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = pjfBILLCYCLEEO.BILLING_CYCLE_TYPE
	AND LOOKUP_TYPE = 'PJF_BILLING_CYCLE_TYPE' AND LANGUAGE = USERENV('LANG')) RES_TYPE
,(CASE WHEN pjfBILLCYCLEEO.BILLING_CYCLE_TYPE IN 'BILLING_CYCLE_DAYS'
	THEN
		pjfBILLCYCLEEO.BILLING_VALUE1
	ELSE
		NULL
	END)RES_CYCLE_DAYS
,(CASE WHEN pjfBILLCYCLEEO.BILLING_CYCLE_TYPE NOT IN 'BILLING_CYCLE_DAYS'
	THEN 
		pjfBILLCYCLEEO.BILLING_VALUE1 
	ELSE
		NULL
	END)RES_FIRST_DATE_OF_MONTH
,BILLING_VALUE2 RES_SECOND_DATE_OF_MONTH
,(CASE WHEN pjfBILLCYCLEEO.BILLING_CYCLE_TYPE NOT IN ('FIRST_WEEKDAY_OF_MONTH','LAST_WEEKDAY_OF_MONTH','USER_DEFINED','WEEKDAY_EACH_WEEK')
	THEN
		pjfBILLCYCLEEO.BILLING_VALUE3 
	ELSE 
		NULL
	END) RES_THIRD_DATE_OF_MONTH
,(CASE WHEN pjfBILLCYCLEEO.BILLING_CYCLE_TYPE IN ('FIRST_WEEKDAY_OF_MONTH','LAST_WEEKDAY_OF_MONTH','USER_DEFINED','WEEKDAY_EACH_WEEK')
	THEN 
		pjfBILLCYCLEEO.BILLING_VALUE3
	ELSE 
		NULL
	END) RES_DAY_OF_WEEK  
,pjfBILLCYCLEEO.BILLING_VALUE4 RES_FOURTH_VALUE
,pjfBILLCYCLEEO.BILLING_VALUE5 RES_FIFTH_VALUE
,TO_CHAR(pjfBILLCYCLEEO.START_DATE_ACTIVE,'DD-Mon-YYYY') RES_FROM_DATE
,TO_CHAR(pjfBILLCYCLEEO.END_DATE_ACTIVE,'DD-Mon-YYYY') RES_TO_DATE

,pjfBILLCYCLEEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,pjfBILLCYCLEEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,pjfBILLCYCLEEO.CREATED_BY RSC_CREATED_BY
,pjfBILLCYCLEEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJF_BILLING_CYCLES_VL pjfBILLCYCLEEO
WHERE pjfBILLCYCLEEO.START_DATE_ACTIVE < SYSDATE AND NVL(pjfBILLCYCLEEO.END_DATE_ACTIVE,TO_DATE('31-12-4712','DD-MM-YYYY')) >= SYSDATE
ORDER BY pjfBILLCYCLEEO.BILLING_CYCLE_NAME
