/* ****************************************************************************
 * $Revision: 71762 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2019-04-03 15:23:08 +0700 (Wed, 03 Apr 2019) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Organization%20Trees%20-%20Tree%20Version%20Specify%20Nodes%20(Specific%20value).sql $:
 * $Id: Manage Organization Trees - Tree Version Specify Nodes (Specific value).sql 71762 2019-04-03 08:23:08Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT cutOff.TREE_NAME			RES_TREE_NAME
,cutOff.TREE_CODE				RES_TREE_CODE
,cutOff.TREE_STRUCTURE_CODE 	RES_TREE_STRUCTURE_CODE
,cutOff.TREE_VERSION_NAME		RES_NAME
,'Specific value' 			RES_TREE_NODE_TYPE
,(SELECT DATA_SOURCE_NAME 
	FROM FND_TS_DATA_SOURCE_VL
	WHERE DATA_SOURCE_ID = cutOff.DATA_SOURCE_ID
	AND TREE_STRUCTURE_CODE = cutOff.TREE_STRUCTURE_CODE
	) RES_DATA_SOURCE
	
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE1 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_1
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE2 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_2
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE3 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_3
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE4 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_4
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE5 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_5
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE6 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_6
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE7 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_7
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE8 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_8
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE9 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_9
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = RES_PARENT_DISPLAY_CODE10 AND ( cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE)) AS RES_PARENT_NODE_NAME_10
,(SELECT NAME||' '||POSITION_CODE||' '||TO_CHAR(EFFECTIVE_START_DATE,'YYYY-MM-DD') FROM HR_ALL_POSITIONS_F_VL a WHERE POSITION_ID  = PK1_START_VALUE AND cutOff.EFFECTIVE_END_DATE BETWEEN a.EFFECTIVE_START_DATE AND a.EFFECTIVE_END_DATE) AS RES_FULL_NODE_NAME_VALUE

,(SELECT NAME 
	FROM HR_ALL_POSITIONS_F_VL 
	WHERE POSITION_ID = PK1_START_VALUE
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))
	) RES_NODE_NAME_VALUE 
,(SELECT POSITION_CODE 
	FROM HR_ALL_POSITIONS_F_VL 
	WHERE POSITION_ID = PK1_START_VALUE
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))
	) RES_NODE_CODE_VALUE
,(SELECT BUS.BU_NAME 
	FROM HR_ALL_POSITIONS_F_VL POS
	,FUN_ALL_BUSINESS_UNITS_V BUS
	WHERE POS.BUSINESS_UNIT_ID = BUS.BU_ID
	AND POS.POSITION_ID = PK1_START_VALUE
	AND SYSDATE BETWEEN POS.EFFECTIVE_START_DATE AND NVL(POS.EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))
	) RES_NODE_BUSINESS_UNIT_VALUE
,NULL RES_CLASSIFICATION_NAME
,cutOff.DESCRIPTION				RES_NODE_DESCRIPTION
,cutOff.LAST_UPDATED_BY   		RSC_LAST_UPDATED_BY
,cutOff.LAST_UPDATE_DATE  		RSC_LAST_UPDATE_DATE
,cutOff.CREATED_BY 				RSC_CREATED_BY
,cutOff.CREATION_DATE 			RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM (SELECT FndTreeVersionEO.EFFECTIVE_START_DATE
,FndTreeVersionEO.EFFECTIVE_END_DATE
,FndTreeVLEO.TREE_NAME
,FndTreeVersionEO.DESCRIPTION
,FndTreeVersionEO.TREE_VERSION_NAME
,NODE.CREATION_DATE
,NODE.CREATED_BY
,NODE.LAST_UPDATE_DATE
,NODE.LAST_UPDATED_BY
,NODE.TREE_STRUCTURE_CODE
,NODE.TREE_CODE TREE_CODE
,NODE.TREE_VERSION_ID
,NODE.TREE_NODE_ID
,NODE.PK1_START_VALUE
,NODE.DATA_SOURCE_ID
--,ClassificationE0.CLASSIFICATION_NAME
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,1)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,2)-4)  RES_PARENT_DISPLAY_CODE1
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,2)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,3) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,2)-3) RES_PARENT_DISPLAY_CODE2
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,3)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,4) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,3)-3) RES_PARENT_DISPLAY_CODE3
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,4)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,5) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,4)-3) RES_PARENT_DISPLAY_CODE4
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,5)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,6) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,5)-3) RES_PARENT_DISPLAY_CODE5
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,6)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,7) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,6)-3) RES_PARENT_DISPLAY_CODE6
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,7)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,8) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,7)-3) RES_PARENT_DISPLAY_CODE7
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,8)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,9) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,8)-3) RES_PARENT_DISPLAY_CODE8
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,9)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,10) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,9)-3) RES_PARENT_DISPLAY_CODE9
,SUBSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,10)+3,INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,11) - INSTR(SYS_CONNECT_BY_PATH(NODE.PK1_START_VALUE,'###'),'###',1,10)-3) RES_PARENT_DISPLAY_CODE10
FROM PER_POS_TREE_NODE NODE
,FND_TREE_VERSION_VL FndTreeVersionEO
,FND_TREE_VL FndTreeVLEO
/*,(SELECT * 
	FROM (SELECT orgClassificationsE0.CLASSIFICATION_NAME
		,orgsE0.ORGANIZATION_ID
		,ROW_NUMBER() OVER(PARTITION BY orgsE0.ORGANIZATION_ID ORDER BY orgsE0.ORGANIZATION_ID) R1
		FROM HR_ALL_ORGANIZATION_UNITS orgsE0
		,HR_ORG_UNIT_CLASSIFICATIONS_F orgInfosE0
		,HR_ORG_CLASSIFICATIONS_VL orgClassificationsE0
		WHERE orgsE0.ORGANIZATION_ID = orgInfosE0.ORGANIZATION_ID
		AND orgInfosE0.CLASSIFICATION_CODE = orgClassificationsE0.CLASSIFICATION_CODE
		AND SYSDATE BETWEEN orgInfosE0.EFFECTIVE_START_DATE AND orgInfosE0.EFFECTIVE_END_DATE
		)
	WHERE R1 = 1
	)ClassificationE0*/
WHERE NODE.TREE_STRUCTURE_CODE = 'PER_POS_TREE_STRUCTURE'
AND NODE.TREE_CODE = FndTreeVLEO.TREE_CODE
AND NODE.TREE_STRUCTURE_CODE = FndTreeVLEO.TREE_STRUCTURE_CODE
AND NODE.TREE_CODE = FndTreeVersionEO.TREE_CODE
AND NODE.TREE_STRUCTURE_CODE = FndTreeVersionEO.TREE_STRUCTURE_CODE
AND NODE.TREE_VERSION_ID = FndTreeVersionEO.TREE_VERSION_ID
--AND NODE.PK1_START_VALUE = ClassificationE0.ORGANIZATION_ID (+)
AND DEPTH <= 10
AND (CHILD_COUNT = 0  OR (CHILD_COUNT > 0 and DEPTH <= 10 )) 
START WITH NVL(NODE.PARENT_TREE_NODE_ID,'1') = '1'
CONNECT BY PRIOR NODE.TREE_NODE_ID = NODE.PARENT_TREE_NODE_ID
AND NODE.DATA_SOURCE_ID = NODE.DATA_SOURCE_ID) cutOff 
ORDER BY TREE_NAME
,RES_PARENT_NODE_NAME_1 NULLS FIRST,RES_PARENT_NODE_NAME_2 NULLS FIRST
,RES_PARENT_NODE_NAME_3 NULLS FIRST,RES_PARENT_NODE_NAME_4 NULLS FIRST
,RES_PARENT_NODE_NAME_5 NULLS FIRST,RES_PARENT_NODE_NAME_6 NULLS FIRST
,RES_PARENT_NODE_NAME_7 NULLS FIRST,RES_PARENT_NODE_NAME_8 NULLS FIRST
,RES_PARENT_NODE_NAME_9 NULLS FIRST,RES_PARENT_NODE_NAME_10 NULLS FIRST