/* ****************************************************************************
 * $Revision:  $:
 * $Author: nasrullah.dusenmahamad $:
 * $Date: 2017-04-26 $:
 * $HeadURL:  $:
 * $Id: Manage Account Aliases - Account Aliases - DFF.sql $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=801##RES##PAY_ALL_PAYROLLS_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE

SELECT payALLPREO.PAYROLL_NAME RES_NAME 
,payALLPREO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,payALLPREO.ATTRIBUTE1 
,payALLPREO.ATTRIBUTE2
,payALLPREO.ATTRIBUTE3
,payALLPREO.ATTRIBUTE4 
,payALLPREO.ATTRIBUTE5
,payALLPREO.ATTRIBUTE6 
,payALLPREO.ATTRIBUTE7 
,payALLPREO.ATTRIBUTE8 
,payALLPREO.ATTRIBUTE9 
,payALLPREO.ATTRIBUTE10 
,payALLPREO.ATTRIBUTE11
,payALLPREO.ATTRIBUTE12 
,payALLPREO.ATTRIBUTE13
,payALLPREO.ATTRIBUTE14 
,payALLPREO.ATTRIBUTE15 
,payALLPREO.ATTRIBUTE16 
,payALLPREO.ATTRIBUTE17 
,payALLPREO.ATTRIBUTE18 
,payALLPREO.ATTRIBUTE19 
,payALLPREO.ATTRIBUTE20

,payALLPREO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payALLPREO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payALLPREO.CREATED_BY RSC_CREATED_BY
,payALLPREO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PAY_ALL_PAYROLLS_F payALLPREO
WHERE SYSDATE BETWEEN payALLPREO.EFFECTIVE_START_DATE AND NVL(payALLPREO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND (payALLPREO.ATTRIBUTE_CATEGORY IS NOT NULL OR
payALLPREO.ATTRIBUTE1 IS NOT NULL OR
payALLPREO.ATTRIBUTE2 IS NOT NULL OR
payALLPREO.ATTRIBUTE3 IS NOT NULL OR 
payALLPREO.ATTRIBUTE4 IS NOT NULL OR 
payALLPREO.ATTRIBUTE5 IS NOT NULL OR 
payALLPREO.ATTRIBUTE6 IS NOT NULL OR 
payALLPREO.ATTRIBUTE7 IS NOT NULL OR 
payALLPREO.ATTRIBUTE8 IS NOT NULL OR 
payALLPREO.ATTRIBUTE9 IS NOT NULL OR 
payALLPREO.ATTRIBUTE10 IS NOT NULL OR 
payALLPREO.ATTRIBUTE11 IS NOT NULL OR 
payALLPREO.ATTRIBUTE12 IS NOT NULL OR 
payALLPREO.ATTRIBUTE13 IS NOT NULL OR 
payALLPREO.ATTRIBUTE14 IS NOT NULL OR 
payALLPREO.ATTRIBUTE15 IS NOT NULL OR 
payALLPREO.ATTRIBUTE16 IS NOT NULL OR 
payALLPREO.ATTRIBUTE17 IS NOT NULL OR 
payALLPREO.ATTRIBUTE18 IS NOT NULL OR 
payALLPREO.ATTRIBUTE19 IS NOT NULL OR 
payALLPREO.ATTRIBUTE20 IS NOT NULL 
)
ORDER BY payALLPREO.PAYROLL_NAME