/* ****************************************************************************
 * $Revision: 56649 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-07-12 11:20:44 +0700 (Tue, 12 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.12/branches/core/v2.2.0.0/reverse_sql/FINANCIALS/Currency%20Rates%20Manager%20-%20Rate%20Types.sql $:
 * $Id: Currency Rates Manager - Rate Types.sql 56649 2016-07-12 04:20:44Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

--RSC_PREREQUISITE_OBJECTS=IRC_SETTING_VALUES
--RSC_PREREQUISITE_OBJECTS=IRC_SETTINGS

SELECT (SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = ircSETVALE0.STRING_VALUE
	AND LOOKUP_TYPE = 'ORA_IRC_REQ_GEN_METHOD' 
	AND LANGUAGE = USERENV('LANG')
	) RES_REQUISITION_NUMBER_GENERAT
,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'REQUISITION_NUMBER_GENERATION_STARTING_NUMBER'
	) RES_REQUISITION_NUMBER_STARTIN
,(SELECT TREE_NAME 
	FROM FND_TREE_VL
    WHERE TREE_CODE = (SELECT A.STRING_VALUE 
		FROM IRC_SETTING_VALUES A
		,IRC_SETTINGS B 
		WHERE A.SETTING_ID = B.SETTING_ID 
		AND B.CODE = 'RECRUITING_ORG_TREE_CODE')
	) RES_RECRUITING_ORGANIZATION_TR
,(SELECT TREE_VERSION_NAME 
	FROM FND_TREE_VERSION_VL
    WHERE TREE_CODE = (SELECT A.STRING_VALUE 
		FROM IRC_SETTING_VALUES A
		,IRC_SETTINGS B 
		WHERE A.SETTING_ID = B.SETTING_ID
		AND B.CODE = 'RECRUITING_ORG_TREE_CODE') 
	AND TREE_VERSION_ID = (SELECT A.STRING_VALUE 
		FROM IRC_SETTING_VALUES A
		,IRC_SETTINGS B 
		WHERE A.SETTING_ID = B.SETTING_ID
		AND B.CODE = 'RECRUITING_ORG_TREE_VERSION')
	) RES_RECRUITING_ORGANIZATION__0
,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_MAX_UNCONFIRMED_SUBS'
	) RES_MAXIMUM_NUMBER_OF_UNVERIFI

/*
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_APPID') RES_CHANNEL_ID
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_CHAT_SERVER_URI')  RES_DIGITAL_ASSISTANT_URL
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_BRAND_COLOR') RES_BRANDING_COLOR
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_COLOR_TEXT') RES_DESCRIPTION_TEXT_COLOR
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_ACTION_COLOR') RES_ACTION_COLOR
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_CHAT_TITLE') RES_CHAT_TITLE_TEXT
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_CHAT_SUBTITLE') RES_CHAT_SUBTITLE_TEXT
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_INPUT_PLACEHOLDER') RES_PLACEHOLDER_TEXT
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_BOT_BUTTON_ICON') RES_CHATBOT_ICON_URL
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_LOGO_ICON') RES_BUSINESS_ICON_URL
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_BOT_ICON') RES_BOT_ICON_URL
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_CX_CHATBOT_PERSON_ICON') RES_PERSON_BOT_URL
*/


-- Campaign Management

,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_CMT_TOKEN_BATCH_LIMIT'
	) RES_EMAIL_BATCH_LIMIT
,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_CMT_MSG_RETRY_LIMIT'
	) RES_EMAIL_MAXIMUM_RETRY_COUNT
,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_CAMP_AUD_REHIRE_ELIG_ENABLED_FLAG'),'Y','Yes','No'
	) RES_DONT_SEND_EMAILS_TO_CANDID
,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_CAMP_AUD_EMAIL_LIMIT_ENABLED_FLAG'),'Y','Yes','No'
	) RES_ENABLE_DO_NOT_SEND_RULE
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = (SELECT A.STRING_VALUE 
		FROM IRC_SETTING_VALUES A
		,IRC_SETTINGS B 
		WHERE A.SETTING_ID = B.SETTING_ID
		AND B.CODE = 'ORA_IRC_CAMP_AUD_EMAIL_LIMIT_UNIT_CODE')
	AND LOOKUP_TYPE = 'ORA_IRC_CAMP_EMAIL_CAP_UNITS' 
	AND LANGUAGE = USERENV('LANG')
	) RES_DONT_SEND_EMAILS_TO_AUDIEN


-- AI Feature Integration

,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_AI_MATCHING_ENABLED'),'Y','Yes','No'
	) RES_AI_FEATURE_INTEGRATION_INT 
	-- AI Feature Integration - Intelligent Matching
,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_AI_TIME_TO_HIRE_ENABLED'),'Y','Yes','No'
	) RES_AI_FEATURE_INTEGRATION_TIM 
	-- AI Feature Integration - Time to Hire


-- Candidate Search Archiving

,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_CANDIDATE_SEARCH_ARCHIVING_ENABLED'),'Y','Yes','No'
	) RES_CANDIDATE_SEARCH_ARCHIVING


-- Offer Letter
	
,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_RESOLVED_OFFER_LETTER_ENABLED'),'Y','Yes','No'
	) RES_DOWNLOAD_OFFER_LETTER_WITH 
	-- Download Offer Letter with Resolved Tokens


-- Talent Community

,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_TC_OPTIN_ENABLED'),'Y','Yes','No'
	) RES_TALENT_COMMUNITY_ACTIVE
,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_TC_GLOBAL_POOL_VISIBLE'),'Y','Yes','No'
	) RES_TALENT_COMMUNITY_GLOBAL_TA
,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_TC_EMAIL_FREQUENCY'
	) RES_TALENT_COMMUNITY_SEND_JOB_


-- Google Job Search

,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_CX_GOOG_JOB_SEARCH_ENABLED'),'Y','Yes','No'
	) RES_GOOGLE_JOB_SEARCH_ACTIVE


-- Contingent Worker Is External Candidate

,NULL RES_CONTINGENT_WORKER_IS_EXTER


-- Candidate Autoconfirmation

,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_AUTO_CONFIRM_CANDIDATE_ENABLED'),'Y','Yes','No'
	) RES_CANDIDATE_AUTOCONFIRMATION


-- Candidate Last Name Verification and Phone Number Request
	
,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_LAST_NAME_CHECK_AND_CLAIM_PHONE_NUMBER_ENABLED'),'Y','Yes','No'
	) RES_CANDIDATE_LAST_NAME_VERIFI

-- Office 365 Calendar Integration

,DECODE((SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_O365_ENABLED'),'Y','Yes','No'
	) RES_OFFICE_365_CALENDAR_INTEGR
	
,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_O365_APPLICATION_ID'
	) RES_APPLICATION_ID
,'' RES_APPLICATION_PASSWORD --> Encrypted - Unsupported
,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_O365_TENANT_ID'
	) RES_TENANT_ID
,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_O365_DEFAULT_ADMIN_USER_IDENTIFIER'
	) RES_DEFAULT_USER_IDENTIFIER
,(SELECT A.STRING_VALUE 
	FROM IRC_SETTING_VALUES A
	,IRC_SETTINGS B 
	WHERE A.SETTING_ID = B.SETTING_ID
	AND B.CODE = 'ORA_IRC_O365_CALENDAR_NAME'
	) RES_CALENDAR_NAME

/*,DECODE((SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_ENABLED'),'Y','Yes','No') RES_ACTIVE
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_REC_URL') RES_RECOMMENDATION_SERVICE_URL
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_REC_ACCES_TOKEN_URL') RES_RECOMMENDATION_ACCESS_TOKE
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_ING_CLIENT_ID') RES_RECOMMENDATION_CLIENT_ID
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_ING_CLIENT_SECRET') RES_RECOMMENDATION_CLIENT_SECR
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_ING_URL') RES_DATA_SYNCHRONIZATION_SERVI
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_ING_ACCES_TOKEN_URL') RES_DATA_SYNCHRONIZATION_ACCES
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_ING_CLIENT_ID') RES_DATA_SYNCHRONIZATION_CLIEN
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_AI_MATCHING_ING_CLIENT_SECRET') RES_DATA_SYNCHRONIZATION_CLI_1
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_O365_APPLICATION_ID') RES_OFFICE_365_CALENDAR_INTE_2
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_O365_APPLICATION_PSWD') RES_OFFICE_365_CALENDAR_INTE_3
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_O365_TENANT_ID') RES_OFFICE_365_CALENDAR_INTE_4
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_O365_DEFAULT_ADMIN_USER_IDENTIFIER') RES_OFFICE_365_CALENDAR_INTE_5
,(SELECT A.STRING_VALUE FROM IRC_SETTING_VALUES A,IRC_SETTINGS B WHERE A.SETTING_ID = B.SETTING_ID
								AND B.CODE = 'ORA_IRC_O365_CALENDAR_NAME') RES_OFFICE_365_CALENDAR_INTE_6*/

,ircSETVALE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ircSETVALE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ircSETVALE0.CREATED_BY RSC_CREATED_BY
,ircSETVALE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM IRC_SETTING_VALUES ircSETVALE0
,IRC_SETTINGS ircSETE0 
WHERE ircSETVALE0.SETTING_ID = ircSETE0.SETTING_ID
AND ircSETE0.CODE = 'REQUISITION_NUMBER_GENERATION_METHOD'