/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- Add multiple lines of data in one save
SELECT 
(SELECT ITEM_CLASS_NAME
	FROM EGP_ITEM_CLASSES_VL
	WHERE ITEM_CLASS_ID = ItemClassPEO.PARENT_ITEM_CLASS_ID
	) RES_PARENT_ITEM_CLASS 
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGO_ITEMPEOPLE_GRANTEE_TYPE'
	AND LOOKUP_CODE = FndGrantsE0.GRANTEE_TYPE
	) RES_PRINCIPAL
,(CASE
	WHEN FndGrantsE0.GRANTEE_TYPE = 'USER' THEN
		(SELECT USERNAME
		FROM PER_USERS
		WHERE USER_GUID = FndGrantsE0.GRANTEE_KEY)
	WHEN FndGrantsE0.GRANTEE_TYPE = 'GROUP' THEN
		NVL((SELECT ROLE_NAME
		FROM PER_ROLES_DN_VL
		WHERE ROLE_COMMON_NAME = FndGrantsE0.ROLE_NAME),FndGrantsE0.ROLE_NAME)
	END) RES_NAME
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = FndGrantsE0.PARAMETER1
	) RES_ORGANIZATION
,TO_CHAR(FndGrantsE0.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,(SELECT USER_FUNCTION_NAME
	FROM FND_FORM_FUNCTIONS_TL
	WHERE LANGUAGE = USERENV('LANG')	
	AND FUNCTION_ID = FndMenuEntriesEO.FUNCTION_ID
	) RES_ACTIONS
,(SELECT DESCRIPTION
	FROM FND_FORM_FUNCTIONS_TL
	WHERE LANGUAGE = USERENV('LANG')	
	AND FUNCTION_ID = FndMenuEntriesEO.FUNCTION_ID
	) RES_DESCRIPTION
,'' RES_DATA_LEVEL -- Not found in Internal Instance
,FndMenuEntriesEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,FndMenuEntriesEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,FndMenuEntriesEO.CREATED_BY  RSC_CREATED_BY
,FndMenuEntriesEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,(SELECT BUSINESS_UNIT_ID
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = FndGrantsE0.PARAMETER1
	) RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,(CASE
	WHEN EXISTS
		(SELECT DISTINCT MASTER_ORGANIZATION_ID
			FROM INV_ORG_PARAMETERS
			WHERE MASTER_ORGANIZATION_ID = FndGrantsE0.PARAMETER1)
	THEN NULL
	ELSE FndGrantsE0.PARAMETER1
	END) RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,FND_GRANTS FndGrantsE0
,FND_MENU_ENTRIES FndMenuEntriesEO
WHERE TO_CHAR(ItemClassPEO.ITEM_CLASS_ID) = FndGrantsE0.PARAMETER2
AND FndGrantsE0.MENU_ID = FndMenuEntriesEO.MENU_ID
AND FndGrantsE0.ENTERPRISE_ID = FndMenuEntriesEO.ENTERPRISE_ID
AND FndGrantsE0.SANDBOX_ID = FndMenuEntriesEO.SANDBOX_ID

UNION

-- Add single line of data in 1 save.
SELECT 
(SELECT ITEM_CLASS_NAME
	FROM EGP_ITEM_CLASSES_VL
	WHERE ITEM_CLASS_ID = ItemClassPEO.PARENT_ITEM_CLASS_ID
	) RES_PARENT_ITEM_CLASS 
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGO_ITEMPEOPLE_GRANTEE_TYPE'
	AND LOOKUP_CODE = FndGrantsE0.GRANTEE_TYPE
	) RES_PRINCIPAL
,(CASE
	WHEN FndGrantsE0.GRANTEE_TYPE = 'USER' THEN
		(SELECT USERNAME
		FROM PER_USERS
		WHERE USER_GUID = FndGrantsE0.GRANTEE_KEY)
	WHEN FndGrantsE0.GRANTEE_TYPE = 'GROUP' THEN
		NVL((SELECT ROLE_NAME
		FROM PER_ROLES_DN_VL
		WHERE ROLE_COMMON_NAME = FndGrantsE0.ROLE_NAME),FndGrantsE0.ROLE_NAME)
	END) RES_NAME
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = FndGrantsE0.PARAMETER1
	) RES_ORGANIZATION
,TO_CHAR(FndGrantsE0.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,(SELECT USER_FUNCTION_NAME
	FROM FND_FORM_FUNCTIONS_TL
	WHERE LANGUAGE = USERENV('LANG')	
	AND FUNCTION_ID = FndMenuEntriesEO.FUNCTION_ID
	) RES_ACTIONS
,(SELECT DESCRIPTION
	FROM FND_FORM_FUNCTIONS_TL
	WHERE LANGUAGE = USERENV('LANG')	
	AND FUNCTION_ID = FndMenuEntriesEO.FUNCTION_ID
	) RES_DESCRIPTION
,'' RES_DATA_LEVEL -- Not found in Internal Instance
,FndMenuEntriesEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,FndMenuEntriesEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,FndMenuEntriesEO.CREATED_BY  RSC_CREATED_BY
,FndMenuEntriesEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,(SELECT BUSINESS_UNIT_ID
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = FndGrantsE0.PARAMETER1
	) RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,(CASE
	WHEN EXISTS
		(SELECT DISTINCT MASTER_ORGANIZATION_ID
			FROM INV_ORG_PARAMETERS
			WHERE MASTER_ORGANIZATION_ID = FndGrantsE0.PARAMETER1)
	THEN NULL
	ELSE FndGrantsE0.PARAMETER1
	END) RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,FND_GRANTS FndGrantsE0
,FND_MENUS_VL menusE0
,FND_MENU_ENTRIES FndMenuEntriesEO
WHERE ItemClassPEO.ITEM_CLASS_CODE = FndGrantsE0.PARAMETER2
AND FndGrantsE0.MENU_ID = FndMenuEntriesEO.MENU_ID
AND FndGrantsE0.ENTERPRISE_ID = FndMenuEntriesEO.ENTERPRISE_ID
AND FndGrantsE0.SANDBOX_ID = FndMenuEntriesEO.SANDBOX_ID
AND FndGrantsE0.MENU_ID = menusE0.MENU_ID
AND menusE0.MENU_NAME != 'EGO_SYSTEM_ITEMS_B_DUMMY'