/* ****************************************************************************
 * $Revision: 78329 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-04-19 15:19:57 +0700 (Tue, 19 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Performance%20Templates%20-%20Performance%20Template.sql $:
 * $Id: Manage Performance Templates - Performance Template.sql 78329 2022-04-19 08:19:57Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS = HRA_TMPL_DEFNS_VL
 
SELECT (SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HRA_TEMPLATE_TYPE'
    AND LOOKUP_CODE = pfTemplatesE0.TEMPLATE_TYPE_CODE
    ) RES_TEMPLATE_TYPE 
,pfTemplatesE0.NAME RES_NAME
,pfTemplatesE0.COMMENTS RES_COMMENTS
,TO_CHAR(pfTemplatesE0.DATE_FROM,'DD-Mon-YYYY') RES_FROM_DATE
,TO_CHAR(pfTemplatesE0.DATE_TO,'DD-Mon-YYYY') RES_TO_DATE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ACTIVE_INACTIVE'
    AND LOOKUP_CODE = pfTemplatesE0.STATUS_CODE
    ) RES_STATUS
,(SELECT NAME
    FROM HRA_DOC_TYPES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND DOC_TYPE_ID = pfTemplatesE0.DOC_TYPE_ID
    ) RES_DOCUMENT_TYPE
,DECODE(pfTemplatesE0.ENABLE_SYNC_FLAG,'Y','Yes','No') RES_USE_SYNCHRONIZED_GOALS_SEC
,DECODE(pfTemplatesE0.SET_ROLE_MINIMUMS_FLAG,'Y','Yes','No') RES_SET_THE_MINIMUM_NUMBER_FOR
,pfTemplatesE0.TOTAL_MIN_PARTICIPANTS RES_TOTAL_MINIMUM_NUMBER_OF_PA
,(SELECT NAME
    FROM HRA_PF_DEFNS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND PROCESS_FLOW_ID = pfTemplatesE0.PROCESS_FLOW_ID
    ) RES_PROCESS_FLOW
    
-- Rating Calculations
,DECODE(pfTemplatesE0.CALCULATE_RATINGS_FLAG,'Y','Yes','No') RES_CALCULATE_RATINGS
,(CASE
    WHEN pfTemplatesE0.CALCULATE_RATINGS_FLAG = 'Y' THEN
        DECODE(pfTemplatesE0.SHOW_WKR_CALC_RATING_FLAG,'Y','Yes','No')
    END) RES_DISPLAY_CALCULATED_RATINGS
,(CASE
    WHEN pfTemplatesE0.CALCULATE_RATINGS_FLAG = 'Y' THEN
        DECODE(pfTemplatesE0.SHOW_MGR_CALC_RATING_FLAG,'Y','Yes','No')
    END) RES_DISPLAY_CALCULATED_RATIN_0
,(CASE
    WHEN pfTemplatesE0.CALCULATE_RATINGS_FLAG = 'Y' THEN
        DECODE(pfTemplatesE0.USE_CALC_RATINGS_FLAG,'Y','Yes','No')
    END) RES_DISPLAY_CALCULATED_RATIN_1
,(CASE
    WHEN pfTemplatesE0.CALCULATE_RATINGS_FLAG = 'Y' THEN
        DECODE(pfTemplatesE0.SHOW_PCPN_CALC_RATING_FLAG,'Y','Yes','No')
    END) RES_DISPLAY_CALCULATED_RATIN_2
,(CASE
    WHEN pfTemplatesE0.CALCULATE_RATINGS_FLAG = 'Y' THEN
        DECODE(pfTemplatesE0.SHOW_MM_CALC_RATING_FLAG,'Y','Yes','No')
    END) RES_USE_CALCULATED_RATINGS_ONL

-- Processing Options
,DECODE(pfTemplatesE0.STAR_RATING_ENABLED_FLAG,'Y','Yes','No') RES_DISPLAY_STAR_RATINGS
,DECODE(pfTemplatesE0.DIGITAL_SIGNATURE_FLAG,'Y','Yes','No') RES_INCLUDE_DIGITAL_SIGNATURE
,DECODE(pfTemplatesE0.KUDOS_REGION_FLAG,'Y','Yes','No') RES_DISPLAY_FEEDBACK_NOTES
,DECODE(pfTemplatesE0.SELECT_MGR_ALLOWED_FLAG,'Y','Yes','No') RES_WORKER_CAN_SELECT_MANAGER_

-- Participant Options
,DECODE(pfTemplatesE0.PCPN_FEEDBACK_REQ_FLAG,'Y','Yes','No') RES_PARTICIPANT_FEEDBACK_IS_RE
,DECODE(pfTemplatesE0.WRK_SEE_MGR_PCPN_FLAG,'Y','Yes','No') RES_WORKER_CAN_VIEW_THE_PARTIC
,DECODE(pfTemplatesE0.AUTO_POPULATE_MM_FLAG,'Y','Yes','No') RES_AUTO_POPULATE_MATRIX_MANAG
,(SELECT NAME
    FROM HRA_ROLE_DEFNS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND ROLE_ID = pfTemplatesE0.DEFAULT_MATRIX_PCPN_ROLE_ID
    ) RES_ALLOW_MATRIX_MANAGERS_TO_A
,DECODE(pfTemplatesE0.SEND_REQUEST_TO_MM_FLAG,'Y','Yes','No') RES_DEFAULT_PARTICIPANT_ROLE
,NULL RES_SECTION_NAME
,DECODE(ALLOW_WKR_SELECT_MM_ROLE_FLAG,'Y','Yes','No') RES_EMPLOYEE_CAN_ASSIGN_PARTIC
,DECODE(ALLOW_MGR_SELECT_MM_ROLE_FLAG,'Y','Yes','No') RES_MANAGER_CAN_ASSIGN_PARTICI
,DECODE(pfTemplatesE0.SHOW_CHECK_IN_REGION_FLAG,'Y','Yes','No')  RES_DISPLAY_CHECK_INS
,DECODE(pfTemplatesE0.SHOW_FEEDBACK_REQ_REGION_FLAG,'Y','Yes','No')  RES_DISPLAY_REQUESTED_FEEDBACK
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HRA_ALL_MANAGER_TYPES'
    AND LOOKUP_CODE = pfTemplatesE0.ALL_MM_MGR_TYPE_FLAG
    )  RES_MANAGER_TYPE

,pfTemplatesE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,pfTemplatesE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,pfTemplatesE0.CREATED_BY  RSC_CREATED_BY
,pfTemplatesE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
  

FROM HRA_TMPL_DEFNS_VL pfTemplatesE0
ORDER BY NAME
