/* ****************************************************************************
 * $Revision: 80355 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2023-03-01 15:04:31 +0700 (Wed, 01 Mar 2023) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Corporate%20Card%20Programs%20-%20Corporate%20Card%20Program.sql $:
 * $Id: Manage Corporate Card Programs - Corporate Card Program.sql 80355 2023-03-01 08:04:31Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EXM_CARD_PROGRAMS
 
SELECT ExmCardProgramsE0.CARD_PROGRAM_NAME RES_NAME
,ExmCardProgramsE0.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_CARD_TYPE'
	AND LOOKUP_CODE = ExmCardProgramsE0.CARD_TYPE_LOOKUP_CODE
	) RES_CARD_TYPE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_CARD_BRAND'
	AND LOOKUP_CODE = ExmCardProgramsE0.CARD_BRAND_LOOKUP_CODE 
	) RES_CARD_BRAND
,TO_CHAR(ExmCardProgramsE0.INACTIVE_DATE,'DD-Mon-YYYY') RES_INACTIVE_DATE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_CC_FILE_FORMAT'
	AND LOOKUP_CODE = ExmCcUploadRulesE0.FILE_FORMAT_CODE 
	) RES_FILE_FORMAT
,DECODE(ExmCardProgramsE0.ENABLE_CC_TOKEN_FLAG,'Y','Token','M','Masked') RES_CARD_NUMBER_FORMAT	
,DECODE(ExmCardProgramsE0.ENABLE_CC_TOKEN_FLAG,'Y','Yes','No') RES_FILE_CONTAINS_TOKENIZED_CA
,ExmCcUploadRulesE0.DETAIL_WAITING_DURATION RES_TRANSACTION_DETAIL_WAIT_DA
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_EMP_MATCH_RULE'
	AND LOOKUP_CODE = ExmCcUploadRulesE0.CARD_EMP_MATCHING_RULE
	) RES_EMPLOYEE_MATCHING_RULE_FOR
,DECODE(ExmCcUploadRulesE0.MATCH_EMPLOYEE_ACROSS_BU,'Y','Yes','No') RES_PERFORM_EMPLOYEE_MATCHING_
,(SELECT MAP_TYPE_CODE
	FROM EXM_MAP_TYPES_B
	WHERE MAP_TYPE_ID = ExmCcUploadRulesE0.CC_EXP_TYP_SUM_MAP_TYPE_ID
	) RES_TRANSACTION_SUMMARY_MAPPIN
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_CC_SUMM_TRXS_SOURCE_COL'
	AND LOOKUP_CODE = ExmCcUploadRulesE0.CC_EXP_TYP_SUM_SOURCE_COL
	) RES_TRANSACTION_SUMMARY_SOURCE
,(SELECT MAP_TYPE_CODE
	FROM EXM_MAP_TYPES_B
	WHERE MAP_TYPE_ID = ExmCcUploadRulesE0.CC_EXP_TYP_DTL_MAP_TYPE_ID
	) RES_TRANSACTION_DETAILS_MAPPIN
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_CC_DET_TRXS_SOURCE_COL'
	AND LOOKUP_CODE = ExmCcUploadRulesE0.CC_EXP_TYP_DTL_SOURCE_COL
	) RES_TRANSACTION_DETAILS_SOURCE
,ExmCcUploadRulesE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,ExmCcUploadRulesE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,ExmCcUploadRulesE0.CREATED_BY  RSC_CREATED_BY
,ExmCcUploadRulesE0.CREATION_DATE  RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EXM_CARD_PROGRAMS ExmCardProgramsE0
,EXM_CC_UPLOAD_RULES ExmCcUploadRulesE0
WHERE ExmCardProgramsE0.CARD_PROGRAM_ID = ExmCcUploadRulesE0.CARD_PROGRAM_ID
ORDER BY ExmCardProgramsE0.CARD_PROGRAM_NAME