/* ****************************************************************************
* $Revision: 55345 $:
* $Author: wuttipong.thongvises $:
* $Date: 2016-05-23 12:42:33 +0700 (Mon, 23 May 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/
FINANCIALS/Manage%20Server%20Configurations%20-%20Manage%20Data%20Quality%20Server%20Configurations.sql $:
* $Id: Manage Server Configurations - Manage Data Quality Server Configurations.sql 55345 2016-05-23 05:42:33Z
wuttipong.thongvises $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT benELIGYEO.NAME RES_NAME
,benELIGFLPLTMEO.ORDR_NUM RES_SEQUENCE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = benELIGFLPLTMEO.FL_TM_PT_TM_CD 
	AND LOOKUP_TYPE = 'EMP_CAT' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_FULL_TIME_OR_PART_TIME
,DECODE(benELIGFLPLTMEO.EXCLD_FLAG,'Y','Yes','No') RES_EXCLUDE
,TO_CHAR(benELIGFLPLTMEO.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(benELIGFLPLTMEO.END_DATE,'DD-Mon-YYYY') RES_END_DATE

,benELIGFLPLTMEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,benELIGFLPLTMEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,benELIGFLPLTMEO.CREATED_BY  RSC_CREATED_BY
,benELIGFLPLTMEO.CREATION_DATE  RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM BEN_ELIGY_PRFL benELIGYEO
,BEN_ELIG_FL_TM_PT_TM_PRTE benELIGFLPLTMEO
WHERE benELIGYEO.ELIGY_PRFL_ID = benELIGFLPLTMEO.ELIGY_PRFL_ID 
AND benELIGYEO.END_DATE BETWEEN benELIGFLPLTMEO.START_DATE AND NVL(benELIGFLPLTMEO.END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND SYSDATE BETWEEN benELIGYEO.START_DATE AND NVL(benELIGYEO.END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
ORDER BY benELIGYEO.NAME,benELIGFLPLTMEO.ORDR_NUM