/* ****************************************************************************
 * $Revision: 68523 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2018-08-30 14:33:44 +0700 (Thu, 30 Aug 2018) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Project%20Priority%20Values%20-%20Lookup%20Codes.sql $:
 * $Id: Manage Project Priority Values - Lookup Codes.sql 68523 2018-08-30 07:33:44Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT orgsE0.NAME RES_NAME
,orgClassificationsE0.CLASSIFICATION_NAME RES_CLASSIFICATION
,DECODE(orgInfosE0.STATUS,'A','Active','I','Inactive') RES_STATUS
,(SELECT LOCATION_NAME
	FROM PER_LOCATION_DETAILS_F_VL
	WHERE LOCATION_ID = orgsE0.LOCATION_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	) RES_LOCATION
,TO_CHAR(orgsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_FROM_DATE
,TO_CHAR(orgsE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_TO_DATE
,(CASE
    WHEN classificationsE0.ORG_INFORMATION1 = 'Y' OR classificationsE0.ORG_INFORMATION12 = 'Y' OR classificationsE0.ORG_INFORMATION13 = 'Y' THEN
        'Yes'
    ELSE
        'No'
    END) RES_CLASSIFY_AS_PROJECT_AND_TA
,(CASE
    WHEN classificationsE0.ORG_INFORMATION1 = 'Y' OR classificationsE0.ORG_INFORMATION12 = 'Y' OR classificationsE0.ORG_INFORMATION13 = 'Y' THEN
        DECODE(classificationsE0.ORG_INFORMATION1,'Y','Yes','No')
	END) RES_ALLOW_INDIRECT_PROJECTS
,(CASE
    WHEN classificationsE0.ORG_INFORMATION1 = 'Y' OR classificationsE0.ORG_INFORMATION12 = 'Y' OR classificationsE0.ORG_INFORMATION13 = 'Y' THEN
        DECODE(classificationsE0.ORG_INFORMATION12,'Y','Yes','No')
	END) RES_ALLOW_PROJECTS_ENABLED_FOR
,(CASE
    WHEN classificationsE0.ORG_INFORMATION1 = 'Y' OR classificationsE0.ORG_INFORMATION12 = 'Y' OR classificationsE0.ORG_INFORMATION13 = 'Y' THEN
        DECODE(classificationsE0.ORG_INFORMATION13,'Y','Yes','No')
	END) RES_ALLOW_PROJECTS_ENABLED_F_0
,DECODE((SELECT STATUS
    FROM HR_ORG_UNIT_CLASSIFICATIONS_F
    WHERE ORGANIZATION_ID = orgsE0.ORGANIZATION_ID
    AND CLASSIFICATION_CODE = 'PA_EXPENDITURE_ORG'
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    ),'A','Yes','No') RES_CLASSIFY_AS_PROJECT_EXPEND
,orgInfosE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,orgInfosE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,orgInfosE0.CREATED_BY RSC_CREATED_BY
,orgInfosE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HR_ALL_ORGANIZATION_UNITS orgsE0
,HR_ORG_UNIT_CLASSIFICATIONS_F orgInfosE0
,HR_ORG_CLASSIFICATIONS_VL orgClassificationsE0
,(SELECT * 
	FROM HR_ORGANIZATION_INFORMATION_F
	WHERE ORG_INFORMATION_CONTEXT IN ('Project Type Class Information')
	) classificationsE0
WHERE orgsE0.ORGANIZATION_ID = orgInfosE0.ORGANIZATION_ID
AND orgInfosE0.CLASSIFICATION_CODE = orgClassificationsE0.CLASSIFICATION_CODE
AND SYSDATE BETWEEN orgInfosE0.EFFECTIVE_START_DATE AND orgInfosE0.EFFECTIVE_END_DATE
AND orgsE0.ORGANIZATION_ID = classificationsE0.ORGANIZATION_ID(+)
ORDER BY orgsE0.NAME
,orgClassificationsE0.CLASSIFICATION_NAME