/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=IRC_DESCRIPTIONS_VL

WITH ORG AS (SELECT PK1_START_VALUE ORG_ID
    ,SUBSTR(REVERSE(SYS_CONNECT_BY_PATH(REVERSE(ORG_DISPLAY),' ,')),1,LENGTH(REVERSE(SYS_CONNECT_BY_PATH(REVERSE(ORG_DISPLAY),', ')))-2) ORG_DISPLAY
    FROM (SELECT PK1_START_VALUE
        ,PARENT_TREE_NODE_ID
        ,TREE_NODE_ID
        ,PARENT_DATA_SOURCE_ID
        ,DATA_SOURCE_ID
        ,(SELECT NAME
            FROM HR_ORGANIZATION_UNITS
            WHERE SYSDATE BETWEEN DATE_FROM AND DATE_TO
            AND ORGANIZATION_ID = PK1_START_VALUE
            ) ORG_DISPLAY
        FROM PER_ORG_TREE_NODE)
    START WITH NVL(PARENT_TREE_NODE_ID,'1') = '1'
    CONNECT BY PRIOR TREE_NODE_ID = PARENT_TREE_NODE_ID
    AND DATA_SOURCE_ID = PARENT_DATA_SOURCE_ID)

SELECT librariesE0.NAME RES_NAME
,librariesE0.DESCRIPTION_CODE RES_CODE
,(SELECT ORG_DISPLAY
    FROM ORG
    WHERE ORG_ID = contextsE0.ORGANIZATION_ID
    ) RES_ORGANIZATION
,contextsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,contextsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,contextsE0.CREATED_BY RSC_CREATED_BY
,contextsE0.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM IRC_DESCRIPTIONS_VL librariesE0
,(SELECT DESCRIPTION_ID
    ,SHORT_DESCRIPTION
    ,DESCRIPTION
    ,ROW_NUMBER() OVER(PARTITION BY DESCRIPTION_ID ORDER BY VERSION_START_DATE) R1
    ,CREATED_BY
    ,CREATION_DATE
    ,LAST_UPDATED_BY
    ,LAST_UPDATE_DATE
    FROM IRC_DESC_VERSIONS_VL
    ) versionsE0
,(SELECT OBJECT_ID
	,ORGANIZATION_ID
	,LAST_UPDATED_BY
	,LAST_UPDATE_DATE
	,CREATED_BY
	,CREATION_DATE
    FROM IRC_AVAILABILITY_CONTEXT
    WHERE OBJECT_TYPE_CODE = 'ORA_AUTORUN_DUPE_NOTIFICATION'
	AND DIMENSION_TYPE_CODE = 'ORA_ORGANIZATION'
    ) contextsE0
WHERE librariesE0.DESCRIPTION_ID = versionsE0.DESCRIPTION_ID
AND versionsE0.R1 = 1
AND versionsE0.DESCRIPTION_ID = contextsE0.OBJECT_ID
ORDER BY librariesE0.NAME