/* ****************************************************************************
 * $Revision: 53905 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-03-25 10:42:36 +0700 (Fri, 25 Mar 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.12/branches/core/v2.2.0.0/reverse_sql/FINANCIALS/Manage%20Transaction%20Types%20-%20Reference%20Accounts.sql $:
 * $Id: Manage Transaction Types - Reference Accounts.sql 53905 2016-03-25 03:42:36Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 
SELECT AccountDefinitionEO.NAME RES_NAME
,AccountTypesEO.NAME RES_TRANSACTION_ACCOUNT_TYPE
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'ALL'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND SegRulesE0.FLEXFIELD_ASSIGN_MODE_CODE = 'A'
	) RES_ACCOUNT_COMBINATION_RULE
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'FA_COST_CTR'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	) RES_SEGMENT_RULES1
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'GL_INTERCOMPANY'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	) RES_SEGMENT_RULES2
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'GL_LOCAL_USE'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	) RES_SEGMENT_RULES3
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'GL_BALANCING_3'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	) RES_SEGMENT_RULES4
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'GL_MANAGEMENT'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	) RES_SEGMENT_RULES5
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'GL_ACCOUNT'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	) RES_SEGMENT_RULES6
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'GL_BALANCING'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	) RES_SEGMENT_RULES7
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'GL_SECONDARY_TRACKING'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	) RES_SEGMENT_RULES8
,NULL RES_SEGMENT_RULES9
,NULL RES_SEGMENT_RULES10
,AccountDefinitionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,AccountDefinitionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,AccountDefinitionEO.CREATED_BY  RSC_CREATED_BY
,AccountDefinitionEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM XLA_TAB_ACCT_DEFS_VL AccountDefinitionEO
,(SELECT DISTINCT ACCOUNT_TYPE_CODE
	,APPLICATION_ID
	,ACCOUNT_DEFINITION_CODE
	,ACCOUNT_DEFINITION_TYPE_CODE
	FROM XLA_TAB_ACCT_DEF_DETAILS
	) AccountDefinitionDetailsEO
,XLA_TAB_ACCT_TYPES_VL AccountTypesEO
WHERE AccountDefinitionEO.APPLICATION_ID = AccountDefinitionDetailsEO.APPLICATION_ID
AND AccountDefinitionEO.ACCOUNT_DEFINITION_CODE = AccountDefinitionDetailsEO.ACCOUNT_DEFINITION_CODE
AND AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_DEFINITION_TYPE_CODE
AND AccountDefinitionEO.APPLICATION_ID = AccountTypesEO.APPLICATION_ID
and AccountDefinitionEO.APPLICATION_ID   = 435
AND AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE = AccountTypesEO.ACCOUNT_TYPE_CODE
AND AccountDefinitionEO.CHART_OF_ACCOUNTS_ID IS NULL

UNION

SELECT AccountDefinitionEO.NAME RES_NAME
,AccountTypesEO.NAME RES_TRANSACTION_ACCOUNT_TYPE
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = 'ALL'
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND SegRulesE0.FLEXFIELD_ASSIGN_MODE_CODE = 'A'
	) RES_ACCOUNT_COMBINATION_RULE
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 1
	) RES_SEGMENT_RULES1
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 2
	) RES_SEGMENT_RULES2
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 3
	) RES_SEGMENT_RULES3
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 4
	) RES_SEGMENT_RULES4
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 5
	) RES_SEGMENT_RULES5
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 6
	) RES_SEGMENT_RULES6
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 7
	) RES_SEGMENT_RULES7
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 8
	) RES_SEGMENT_RULES8
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 9
	) RES_SEGMENT_RULES9
,(SELECT SegRulesE0.NAME
	FROM XLA_TAB_ACCT_DEF_DETAILS AcctDefDetailsE0
	,XLA_SEG_RULES_VL SegRulesE0
	,(SELECT kfInstancesE0.STRUCTURE_INSTANCE_ID 
		,kfSegmentsE0.COLUMN_NAME
		,kfSegmentsE0.SEQUENCE_NUMBER
		FROM FND_KF_STR_INSTANCES_VL kfInstancesE0
		,FND_KF_SEGMENTS_VL kfSegmentsE0
		WHERE kfInstancesE0.STRUCTURE_ID = kfSegmentsE0.STRUCTURE_ID		
		) KfSegmentsE0
	WHERE AcctDefDetailsE0.SEGMENT_RULE_CODE = SegRulesE0.SEGMENT_RULE_CODE
	AND AcctDefDetailsE0.SEGMENT_RULE_APPL_ID = SegRulesE0.APPLICATION_ID
	AND AcctDefDetailsE0.SEGMENT_RULE_TYPE_CODE = SegRulesE0.SEGMENT_RULE_TYPE_CODE
	AND AcctDefDetailsE0.FLEXFIELD_SEGMENT_CODE = KfSegmentsE0.COLUMN_NAME
	AND KfSegmentsE0.STRUCTURE_INSTANCE_ID = AccountDefinitionEO.CHART_OF_ACCOUNTS_ID
	AND AcctDefDetailsE0.APPLICATION_ID = AccountDefinitionEO.APPLICATION_ID
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE
	AND AcctDefDetailsE0.ACCOUNT_DEFINITION_CODE = AccountDefinitionEO.ACCOUNT_DEFINITION_CODE
	AND AcctDefDetailsE0.ACCOUNT_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE
	AND KfSegmentsE0.SEQUENCE_NUMBER = 10
	) RES_SEGMENT_RULES10
,AccountDefinitionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,AccountDefinitionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,AccountDefinitionEO.CREATED_BY  RSC_CREATED_BY
,AccountDefinitionEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,AccountDefinitionEO.CHART_OF_ACCOUNTS_ID RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM XLA_TAB_ACCT_DEFS_VL AccountDefinitionEO
,(SELECT DISTINCT ACCOUNT_TYPE_CODE
	,APPLICATION_ID
	,ACCOUNT_DEFINITION_CODE
	,ACCOUNT_DEFINITION_TYPE_CODE
	FROM XLA_TAB_ACCT_DEF_DETAILS
	) AccountDefinitionDetailsEO
,XLA_TAB_ACCT_TYPES_VL AccountTypesEO
WHERE AccountDefinitionEO.APPLICATION_ID = AccountDefinitionDetailsEO.APPLICATION_ID
AND AccountDefinitionEO.ACCOUNT_DEFINITION_CODE = AccountDefinitionDetailsEO.ACCOUNT_DEFINITION_CODE
AND AccountDefinitionEO.ACCOUNT_DEFINITION_TYPE_CODE = AccountDefinitionDetailsEO.ACCOUNT_DEFINITION_TYPE_CODE
AND AccountDefinitionEO.APPLICATION_ID = AccountTypesEO.APPLICATION_ID
and AccountDefinitionEO.APPLICATION_ID   = 435
AND AccountDefinitionDetailsEO.ACCOUNT_TYPE_CODE = AccountTypesEO.ACCOUNT_TYPE_CODE
AND AccountDefinitionEO.CHART_OF_ACCOUNTS_ID IS NOT NULL
ORDER BY RES_NAME
,RES_TRANSACTION_ACCOUNT_TYPE