/* ****************************************************************************
 * $Revision: 53782 $:
 * $Author: nasrullah.dusenmahamad $:
 * $Date: 2016-03-31 18:00:16 +0700 (Tue, 22 Mar 2016) $:
 * $HeadURL: $:
 * $Id: Manage Applications Core Value Sets - Manage Applications Core Value Sets.sql 53782 2016-03-22 11:00:16Z nasrullah.dusenmahamad $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT TaxTLEO.TAX_REGIME_CODE RES_TAX_REGIME_CODE
,ZFPOMV.PARTY_NAME RES_CONFIGURATION_OWNER
,TaxTLEO.TAX RES_TAX
,TaxTLEO.TAX_FULL_NAME RES_TAX_NAME
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ZX_TAX_POINT_BASIS'
	AND LOOKUP_CODE   = TaxTLEO.tax_point_basis
	) RES_TAX_POINT_BASIS
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ZX_INCLUSIVE_TAX'
	AND LOOKUP_CODE   = TaxTLEO.DEF_INCLUSIVE_TAX_FLAG
	) RES_TAX_INCLUSION_METHOD
,DECODE(TaxTLEO.TAX_INCLUSIVE_OVERRIDE_FLAG,'Y','Yes','No') RES_ALLOW_OVERRIDE_AND_ENTRY_O
,DECODE(TaxTLEO.ALLOW_ROUNDING_OVERRIDE_FLAG,'Y','Yes','No') RES_ALLOW_TAX_ROUNDING_OVERRID
,DECODE(TaxTLEO.ALLOW_TAX_OVERRIDE_FLAG,'Y','Yes','No') RES_ALLOW_OVERRIDE_OF_CALCULAT
,DECODE(TaxTLEO.ALLOW_MANUAL_ENTRY_FLAG,'Y','Yes','No') RES_ALLOW_ENTRY_OF_MANUAL_TAX_
,DECODE(TaxTLEO.REGN_NUM_SAME_AS_LE_FLAG,'Y','Yes','No') RES_USE_LEGAL_REGISTRATION_NUM
,DECODE(TaxTLEO.ALLOW_DUP_REGN_NUM_FLAG,'Y','Yes','No') RES_ALLOW_DUPLICATE_REGISTRATI
,DECODE(TaxTLEO.HAS_OTHER_JURISDICTIONS_FLAG,'Y','Yes','No') RES_ALLOW_MULTIPLE_JURISDICTIO
,DECODE(ALLOW_MASS_CREATE_FLAG,'Y','Yes','No') RES_ALLOW_CREATION_OF_MULTIPLE
,DECODE(TaxTLEO.Process_Wht_Flag,'Y','Yes','No') RES_USE_IN_WITHHOLDING_TAX_CAL
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ZX_ACCOUNT_CREATION_METHOD'
	AND LOOKUP_CODE   = TaxTLEO.TAX_ACCOUNT_CREATE_METHOD_CODE
	) RES_TAX_ACCOUNTS_CREATION_METH
,TaxTLEO.TAX_ACCOUNT_SOURCE_TAX RES_TAX_ACCOUNTS_SOURCE
,DECODE(TaxTLEO.ALLOW_EXCEPTIONS_FLAG,'Y','Yes','No') RES_ALLOW_TAX_EXCEPTIONS
,DECODE(TaxTLEO.ALLOW_EXEMPTIONS_FLAG,'Y','Yes','No') RES_ALLOW_TAX_EXEMPTIONS
,DECODE(TaxTLEO.USE_LEGAL_MSG_FLAG,'Y','Yes','No') RES_USE_TAX_EXEMPTIONS_FROM_AN
,TaxTLEO.TAX_EXMPT_SOURCE_TAX RES_TAX_EXEMPTIONS_SOURCE
,NVL(TaxTLEO.Validation_Type,'""') RES_VALIDATION_TYPE
,NVL((SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ZX_VALIDATION_LEVEL'
	AND LOOKUP_CODE   = TaxTLEO.Validation_Level
	),'""') RES_VALIDATION_LEVEL
,NVL((SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ZX_UNIQUENESS_VALIDATION_LVL'
	AND LOOKUP_CODE   = TaxTLEO.Uniqueness_Validation_Level
	),'""') RES_DUPLICATE_VALIDATION_LEVEL
,DECODE(TaxTLEO.ALLOW_RECOVERABILITY_FLAG,'Y','Yes','No') RES_ALLOW_TAX_RECOVERY
,DECODE(TaxTLEO.RECOVERY_RATE_OVERRIDE_FLAG,'Y','Yes','No') RES_ALLOW_TAX_RECOVERY_RATE_OV
,TaxTLEO.PRIMARY_RECOVERY_TYPE_CODE RES_PRIMARY_RECOVERY_TYPE
,TaxTLEO.SECONDARY_RECOVERY_TYPE_CODE RES_SECONDARY_RECOVERY_TYPE
,TaxTLEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,TaxTLEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,TaxTLEO.CREATED_BY RSC_CREATED_BY
,TaxTLEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(CASE 
	WHEN ZFPOMV.PARTY_TYPE_CODE = 'OU' THEN	
		ZFPOMV.BU_ID
	ELSE
		NULL
	END) RSC_BUSINESS_UNIT_ID
,(CASE 
	WHEN ZFPOMV.PARTY_TYPE_CODE = 'FIRST_PARTY' THEN	
		ZFPOMV.LEGAL_ENTITY_ID
	ELSE
		NULL
	END) RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM ZX_TAXES_VL TaxTLEO
,ZX_FIRST_PARTY_ORGS_MOAC_V ZFPOMV
,ZX_REGIMES_VL RegimeTLEO
WHERE ZFPOMV.PARTY_TAX_PROFILE_ID                = TaxTLEO.CONTENT_OWNER_ID
AND RegimeTLEO.TAX_REGIME_CODE                   = TaxTLEO.TAX_REGIME_CODE
AND NVL(RegimeTLEO.REGIME_TYPE_FLAG,'I') = 'I'