/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Payment%20Process%20Request%20Templates%20-%20Payment%20Process%20Request%20Template.sql $:
 * $Id: Manage Payment Process Request Templates - Payment Process Request Template.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
--RSC_PREREQUISITE_OBJECTS=AP_PAYMENT_TEMPLATES

SELECT apTemplatesE0.TEMPLATE_NAME RES_NAME
,(SELECT MEANING 
	FROM AP_LOOKUP_VALUES
	WHERE LOOKUP_TYPE = 'PAYMENT_TEMPLATE_TYPE'
	AND LOOKUP_CODE = apTemplatesE0.TEMPLATE_TYPE
	) RES_TYPE
,apTemplatesE0.DESCRIPTION RES_DESCRIPTION
,TO_CHAR(apTemplatesE0.INACTIVE_DATE,'DD-Mon-YYYY') RES_INACTIVE_DATE
,apTemplatesE0.ADDL_PAY_THRU_DAYS RES_PAY_THROUGH_DAYS
,apTemplatesE0.HI_PAYMENT_PRIORITY RES_FROM_PAYMENT_PRIORITY
,apTemplatesE0.LOW_PAYMENT_PRIORITY RES_TO_PAYMENT_PRIORITY
,(SELECT MEANING 
	FROM AP_LOOKUP_VALUES
	WHERE LOOKUP_TYPE = 'AP_SELECT_BASED_ON'
	AND LOOKUP_CODE = apTemplatesE0.PAY_ONLY_WHEN_DUE_FLAG
	) RES_DATE_BASIS
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES
	WHERE LOOKUP_TYPE = 'ORA_ACCELERATED_INVOICES'
	AND LANGUAGE = USERENV('LANG')
	AND LOOKUP_CODE = apTemplatesE0.ACCELERATED_INVOICES_CODE
	) RES_SELECT_EARLY_PAYMENT_INVOI
,DECODE(apTemplatesE0.ZERO_INV_ALLOWED_FLAG,'Y','Yes','No') RES_INCLUDE_ZERO_AMOUNT_INVOIC
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'POZ_VENDOR_TYPE'
	AND LOOKUP_CODE = apTemplatesE0.VENDOR_TYPE_LOOKUP_CODE
	) RES_SUPPLIER_TYPE
,(SELECT PAYMENT_METHOD_NAME
	FROM IBY_PAYMENT_METHODS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND PAYMENT_METHOD_CODE = apTemplatesE0.PAYMENT_METHOD_CODE
	) RES_PAYMENT_METHOD
,(SELECT MEANING 
	FROM AP_LOOKUP_VALUES
	WHERE LOOKUP_TYPE = 'INVOICE_EXCHANGE_RATE_TYPE'
	AND LOOKUP_CODE = apTemplatesE0.INV_EXCHANGE_RATE_TYPE
	) RES_INVOICE_CONVERSION_RATE_TY
,suppliersE0.PARTY_NAME RES_SUPPLIER_OR_PARTY
,suppliersE0.SEGMENT1 RES_SUPPLIER_NUMBER
,suppliersE0.NUM_1099 RES_TAXPAYER_ID
,apTemplatesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,apTemplatesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,apTemplatesE0.CREATED_BY RSC_CREATED_BY
,apTemplatesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM AP_PAYMENT_TEMPLATES apTemplatesE0
,(SELECT Pty.PARTY_NAME
	,Sup.SEGMENT1
	,Sup.VENDOR_ID
	,supTax.NUM_1099
	FROM POZ_SUPPLIERS Sup
	,HZ_PARTIES Pty
	,POZ_SUPPLIERS_INT supTax
	WHERE Sup.PARTY_ID = Pty.PARTY_ID
	AND Sup.VENDOR_ID = supTax.VENDOR_ID(+)
  ) suppliersE0
WHERE apTemplatesE0.VENDOR_ID = suppliersE0.VENDOR_ID(+)
ORDER BY apTemplatesE0.TEMPLATE_NAME