/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Actions%20-%20Action.sql $:
 * $Id: Manage Actions - Action.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

--RSC_PREREQUISITE_OBJECTS=PER_ACTIONS_VL

 SELECT perACTIONEO.ACTION_CODE RES_ACTION_CODE
 ,perACTIONEO.ACTION_NAME RES_ACTION_NAME
 ,perACTIONEO.DESCRIPTION RES_DESCRIPTION
 ,(SELECT MEANING FROM PER_ACTION_TYPES_VL  WHERE ACTION_TYPE_CODE = perACTIONEO.ACTION_TYPE_CODE 
	AND ACTION_TYPE_ID = perACTIONEO.ACTION_TYPE_ID) RES_TYPE
 ,(SELECT USER_STATUS FROM PER_ASSIGNMENT_STATUS_TYPES_VL 
	WHERE ASSIGNMENT_STATUS_TYPE_ID = perACTIONEO.DFLT_ASG_STATUS_TYPE_ID) RES_ASSIGNMENT_STATUS 
 ,DECODE(perACTIONEO.USED_IN_CONTRACT,'Y','Yes','No') RES_USED_IN_CONTRACT
 ,TO_CHAR(perACTIONEO.START_DATE,'DD-Mon-YYYY') RES_START_DATE
 ,TO_CHAR(perACTIONEO.END_DATE,'DD-Mon-YYYY')  RES_END_DATE
 ,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perACTIONEO.ACT_INFORMATION2
	AND LOOKUP_TYPE = 'PER_TERMINATION_TYPE' AND LANGUAGE = USERENV('LANG')) RES_TERMINATION_TYPE
 ,DECODE(perACTIONEO.ACT_INFORMATION1,'Y','Yes','No') RES_REORGANIZATION_RELATED
  
 ,perACTIONEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
 ,perACTIONEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
 ,perACTIONEO.CREATED_BY  RSC_CREATED_BY
 ,perACTIONEO.CREATION_DATE  RSC_CREATION_DATE
 ,null RSC_LEDGER_ID
 ,null RSC_CHART_OF_ACCOUNTS_ID
 ,null RSC_BUSINESS_UNIT_ID
 ,null RSC_LEGAL_ENTITY_ID
 ,null RSC_ORGANIZATION_ID
 ,null RSC_BUSINESS_GROUP_ID
 ,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

 
 FROM PER_ACTIONS_VL perACTIONEO
 --WHERE SYSDATE BETWEEN perACTIONEO.START_DATE AND NVL(perACTIONEO.END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
 ORDER BY perACTIONEO.ACTION_CODE