/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah.Dusenmahamad $:
 * $Date: 2017-08-28 $:
 * $HeadURL:  $:
 * $Id: Manage Pricing Bases - Pricing Basis.sql 54097 2016-03-30 09:27:56Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PER_CHECKLIST_ACTIONS
-- REPLACE_HTML_KEYWORD = RES_NOTES

SELECT chklistsE0.NAME RES_CHECKLIST_NAME
,tasksE0.CHECKLIST_TASK_NAME RES_TASK_NAME
,tasksE0.DESCRIPTION RES_DESCRIPTION
,DECODE(tasksE0.MANDATORY_FLAG,'Y','Yes','No') RES_REQUIRED
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_CHK_TASK_STATUS'
    AND LOOKUP_CODE = NVL(tasksE0.ACTIVE_INACTIVE_FLAG,'ORA_CHK_TASK_ACTIVE')
    ) RES_STATUS
,(SELECT CHECKLIST_TASK_NAME
    FROM PER_TASKS_IN_CHECKLIST_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND TASK_IN_CHECKLIST_ID = precedingsE0.DEPENDENT_TASK_IN_CHECKLIST_ID
    ) RES_PRECEDING_TASK
,(SELECT NAME
    FROM BEN_ELIGY_PRFL
    WHERE ELIGY_PRFL_ID = tasksE0.ELIGIBILITY_PROFILE_ID
    ) RES_ELIGIBILITY_PROFILE
,tasksE0.MEETING_OFFSET RES_OFFSET_DAYS
,tasksE0.TARGET_DURATION RES_TARGET_DURATION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'CHECKLIST_QUALIFYING_UNITS'
    AND LOOKUP_CODE = tasksE0.TARGET_DURATION_UOM
    ) RES_TARGET_DURATION_UOM
,tasksE0.TASK_DELAY_DURATION RES_DELAY_DURATION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'CHECKLIST_QUALIFYING_UNITS'
    AND LOOKUP_CODE = tasksE0.TASK_DELAY_DURATION_UOM
    ) RES_DELAY_DURATION_UOM

,(CASE
	WHEN tasksE0.RESPONSIBILITY_TYPE IS NOT NULL THEN
		NVL((SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_PER_CHECKLIST_PERFORMERS'
			AND LOOKUP_CODE = tasksE0.RESPONSIBILITY_TYPE)
			,'Area of Responsibility') 
	ELSE
		'Initiator'
	END) RES_PERFORMER
,(SELECT USER_DISPLAY_NAME
    FROM ASE_USER_VL
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
    AND USER_GUID = tasksE0.ADHOC_USER_GUID
    ) RES_USER
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'PER_RESPONSIBILITY_TYPES'
    AND LOOKUP_CODE = tasksE0.RESPONSIBILITY_TYPE
	 ) RES_RESPONSIBILITY_TYPE
	 
,(CASE
	WHEN (SELECT MEANING
		FROM FND_LOOKUP_VALUES
		WHERE LANGUAGE = USERENV('LANG')
		AND LOOKUP_TYPE = 'PER_RESPONSIBILITY_TYPES'
		AND LOOKUP_CODE = tasksE0.RESPONSIBILITY_TYPE) IS NULL 
		THEN
		NVL((SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_PER_CHK_TASK_OWNER'
			AND LOOKUP_CODE = tasksE0.OWNER_RESP_TYPE)
			,'Area of Responsibility') 
	ELSE
		'Initiator'
	END) RES_OWNER
,(SELECT USER_DISPLAY_NAME
    FROM ASE_USER_VL
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
    AND USER_GUID = tasksE0.OWNER_USER_GUID
    ) RES_TASK_OWNER_USER_NAME
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'PER_RESPONSIBILITY_TYPES'
    AND LOOKUP_CODE = tasksE0.OWNER_RESP_TYPE
	 ) RES_OWNER_RESPONSIBILITY_TYPE
	 
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_CHK_TASK_ACTION_TYPE'
    AND LOOKUP_CODE = tasksE0.ACTION_TYPE
    ) RES_ACTION_TYPE
	 
,(CASE
    WHEN tasksE0.ACTION_TYPE = 'ORA_CHK_APP_TASK' THEN
		--Application Task
		DECODE(tasksE0.TASK_ACTION_CODE,'Me.me_absence_balance','Absence Balance'
			,'Me.me_add_absence','Add Absence'
			,'Me.me_career_development','Career Development'
			,'Me.me_career_planning','Career Planning'
			,'Me.me_contact_information','Contact Info'
			,'Me.me_document_delivery_preferences_1','Document Delivery Preferences'
			,'Me.hcm_ben_doc_records','Document Records'
			,'Me.me_my_emp_card','Employment Info'
			,'Me.me_existing_absences','Existing Absences'
			,'Me.me_familyand_emergency_contacts','Family and Emergency Contacts'
			,'Me.me_my_goals','Goals'
			,'Me.me_my_documents','Identification Info'
			,'Me.me_personal_compensation','My Compensation'
			,'Me.me_my_spotlight','My Public Info'
			,'Me.me_payment_methods','Payment Methods'
			,'Me.hcm_ben_emp_contacts','People to Cover'
			,'Me.me_personal_details','Personal Details'
			,'Me.hcm_ben_pcp','Primary Care Physicians'
			,'Me.hcm_ben_report_event','Report a Life Event'
			,'Me.me_edit_skillsand_qualifications','Skills and Qualifications'
			,'Me.me_view_social_security_account_information','Social Security Accounts'
			,'Me.me_manage_tax_withholding_1','Tax Withholding'
			,'Me.me_benefits_summary','Your Benefits'
			,tasksE0.TASK_ACTION_CODE)
    WHEN tasksE0.ACTION_TYPE = 'ORA_CHK_CONFIGURABLE_FORM' THEN
		--Configurable Form
		tasksE0.FLEX_CONTEXT_CODE
    WHEN tasksE0.ACTION_TYPE = 'ORA_CHK_ESIGN' THEN
		--Signature Type
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_PER_CHK_ESIGN_TYPES'
			AND LOOKUP_CODE = tasksE0.ESIGN_TYPE)
    WHEN tasksE0.ACTION_TYPE IN ('ORA_CHK_EXTERNAL_URL','ORA_CHK_VIDEO') THEN
		--Action URL
		tasksE0.ACTION_URL
    WHEN tasksE0.ACTION_TYPE = 'ORA_CHK_PRE_EMP_SCREENING' THEN
		--I-9 Section
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_PER_CHK_FORM_I9_SECTIONS'
			AND LOOKUP_CODE = tasksE0.ESIGN_TYPE )
    WHEN tasksE0.ACTION_TYPE = 'ORA_CHK_QUESTIONNAIRE' THEN
		--Questionnaire Template
		(SELECT NAME
			FROM HRQ_QUESTIONNAIRES_VL
			WHERE LATEST_VERSION = 'Y'
			AND QUESTIONNAIRE_ID = tasksE0.QUESTIONNAIRE_ID)
    WHEN tasksE0.ACTION_TYPE = 'ORA_CHK_REPORT' THEN
		--Report Path
		tasksE0.REPORT_PATH
    END) RES_ACTION_TYPE_VALUE_1
,(CASE
    WHEN tasksE0.ACTION_TYPE = 'ORA_CHK_PRE_EMP_SCREENING' THEN
		--I-9 Configuration
		tasksE0.SIGN_TEMPLATE
    END) RES_ACTION_TYPE_VALUE_2

,DECODE(SUBSTR(tasksE0.TASK_CONFIGURATION,INSTR(tasksE0.TASK_CONFIGURATION,'ATC',1,1)+4,1),'Y','Yes','N','No') RES_ATTACHMENTS
,DECODE(SUBSTR(tasksE0.TASK_CONFIGURATION,INSTR(tasksE0.TASK_CONFIGURATION,'CMT',1,1)+4,1),'Y','Yes','N','No') RES_COMMENTS


--Reminder
,(CASE
	WHEN tasksE0.REMINDER_DURATION IS NOT NULL AND tasksE0.REMINDER_RECURRENCE IS NOT NULL THEN
		'Yes'
	ELSE
		'No'
	END) RES_ENABLE_REMINDER
,(CASE
    WHEN tasksE0.REMINDER_DURATION IS NOT NULL AND tasksE0.REMINDER_RECURRENCE IS NOT NULL THEN
        tasksE0.REMINDER_DURATION
    END) RES_REMIND_EVERY_DAYS
,(CASE
    WHEN tasksE0.REMINDER_DURATION IS NOT NULL AND tasksE0.REMINDER_RECURRENCE IS NOT NULL THEN
        tasksE0.REMINDER_RECURRENCE
    END) RES_REMIND_REPEAT_TIMES
,(CASE
    WHEN tasksE0.REMINDER_DURATION IS NOT NULL AND tasksE0.REMINDER_RECURRENCE IS NOT NULL THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'ORA_PER_CHK_TASK_REMINDER_TIME'
            AND LOOKUP_CODE = tasksE0.REMINDER_RELATIVE_TO)
    END) RES_REMIND_OPTION

--Noted
,REPLACE(REPLACE(REPLACE(tasksE0.TASK_DETAILS,'&','#AMP#'),'<','#OPENTAG#'),'>','#CLOSETAG#') RES_NOTES
,tasksE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,tasksE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,tasksE0.CREATED_BY RSC_CREATED_BY
,tasksE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PER_CHECKLISTS_VL chklistsE0
,PER_TASKS_IN_CHECKLIST_VL tasksE0
,PER_TASK_DEPENDENCIES precedingsE0
WHERE chklistsE0.CHECKLIST_ID = tasksE0.CHECKLIST_ID
AND tasksE0.TASK_IN_CHECKLIST_ID = precedingsE0.TASK_IN_CHECKLIST_ID(+)
ORDER BY chklistsE0.NAME
,tasksE0.CHECKLIST_TASK_NAME