/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Default%20Item%20Class%20-%20Item%20-%20GDF.sql $:
 * $Id: Manage Default Item Class - Item - GDF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=7003##RES##JG_EGP_SYSTEM_ITEMS
-- DFF_ATTRIBUTES=ATTRIBUTE,GLOBAL_ATTRIBUTE,GLOBAL_ATTRIBUTE_NUMBER,GLOBAL_ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

SELECT ItemClassPEO.ITEM_CLASS_CODE RES_INTERNAL_NAME
,ItemVersionEO.TEMPLATE_NAME RES_NAME
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemVersionEO.ORGANIZATION_ID
	) RES_ORGANIZATION
,ItemVersionEO.GLOBAL_ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ItemVersionEO.GLOBAL_ATTRIBUTE1
,ItemVersionEO.GLOBAL_ATTRIBUTE2
,ItemVersionEO.GLOBAL_ATTRIBUTE3
,ItemVersionEO.GLOBAL_ATTRIBUTE4
,ItemVersionEO.GLOBAL_ATTRIBUTE5
,ItemVersionEO.GLOBAL_ATTRIBUTE6
,ItemVersionEO.GLOBAL_ATTRIBUTE7
,ItemVersionEO.GLOBAL_ATTRIBUTE8
,ItemVersionEO.GLOBAL_ATTRIBUTE9
,ItemVersionEO.GLOBAL_ATTRIBUTE10
,ItemVersionEO.GLOBAL_ATTRIBUTE11
,ItemVersionEO.GLOBAL_ATTRIBUTE12
,ItemVersionEO.GLOBAL_ATTRIBUTE13
,ItemVersionEO.GLOBAL_ATTRIBUTE14
,ItemVersionEO.GLOBAL_ATTRIBUTE15
,ItemVersionEO.GLOBAL_ATTRIBUTE16
,ItemVersionEO.GLOBAL_ATTRIBUTE17
,ItemVersionEO.GLOBAL_ATTRIBUTE18
,ItemVersionEO.GLOBAL_ATTRIBUTE19
,ItemVersionEO.GLOBAL_ATTRIBUTE20
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER1
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER2
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER3
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER4
,ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER5
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE1,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE1
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE2,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE2
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE3,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE3
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE4,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE4
,TO_CHAR(ItemVersionEO.GLOBAL_ATTRIBUTE_DATE5,'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE5
,ItemVersionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemVersionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemVersionEO.CREATED_BY RSC_CREATED_BY
,ItemVersionEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,ItemVersionEO.ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,EGP_SYSTEM_ITEMS_V ItemVersionEO
WHERE ItemClassPEO.PARENT_ITEM_CLASS_ID NOT IN (SELECT ITEM_CLASS_ID FROM EGP_ITEM_CLASSES_VL)
AND ItemVersionEO.TEMPLATE_NAME IS NOT NULL
AND ItemClassPEO.ITEM_CLASS_ID             = ItemVersionEO.ITEM_CATALOG_GROUP_ID
AND(ItemVersionEO.GLOBAL_ATTRIBUTE_CATEGORY IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE1          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE2          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE3          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE4          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE5          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE6          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE7          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE8          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE9          IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE10         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE11         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE12         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE13         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE14         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE15         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE16         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE17         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE18         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE19         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE20         IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER1   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER2   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER3   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER4   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_NUMBER5   IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE1     IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE2     IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE3     IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE4     IS NOT NULL
OR ItemVersionEO.GLOBAL_ATTRIBUTE_DATE5     IS NOT NULL)
ORDER BY ItemClassPEO.ITEM_CLASS_CODE
,ItemVersionEO.TEMPLATE_NAME
,3