/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Time%20Repository%20Rule%20Templates%20-%20Parameters.sql $:
 * $Id: Manage Time Repository Rule Templates - Parameters.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
-- RSC_PREREQUISITE_OBJECTS=HWM_RULE_TMPLT_INPUTS_VL

SELECT  hwnRuleTMPEO.TEMPLATE_NAME  RES_NAME
,hwnRuleTMPLTinEO.DISPLAY_SEQUENCE RES_DISPLAY_SEQUENCE
,hwnRuleTMPLTinEO.INPUT_NAME RES_FORMULA_PARAMETER_NAME
,(SELECT MEANING FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = hwnRuleTMPLTinEO.RULE_PARAMETER_TYPE AND LOOKUP_TYPE = 'HWM_RULE_PARAMETER_TYPE'
	AND LANGUAGE = USERENV('LANG')) RES_PARAMETER_TYPE
,DECODE(hwnRuleTMPLTinEO.PARM_VALUE_REQUIRED,'Y','Yes','No') RES_REQUIRED
,(SELECT VALUE_SET_CODE FROM FND_VS_VALUE_SETS 
	WHERE VALUE_SET_ID = hwnRuleTMPLTinEO.VALUE_SET_ID) RES_VALUE_SET
,hwnRuleTMPLTinEO.USER_DEFINED_IN_NAME RES_DISPLAY_NAME

,hwnRuleTMPLTinEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hwnRuleTMPLTinEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hwnRuleTMPLTinEO.CREATED_BY RSC_CREATED_BY
,hwnRuleTMPLTinEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HWM_RULE_TMPLTS_VL hwnRuleTMPEO
,HWM_RULE_TMPLT_INPUTS_VL hwnRuleTMPLTinEO
WHERE hwnRuleTMPEO.RULE_TMPLTS_ID = hwnRuleTMPLTinEO.RULE_TMPLTS_ID
ORDER BY hwnRuleTMPEO.TEMPLATE_NAME,hwnRuleTMPLTinEO.DISPLAY_SEQUENCE 
