/* ****************************************************************************
 * $Revision: 53782 $:
 * $Author: nasrullah.dusenmahamad $:
 * $Date: 2016-03-31 18:00:16 +0700 (Tue, 22 Mar 2016) $:
 * $HeadURL: $:
 * $Id: Manage Applications Core Value Sets - Manage Applications Core Value Sets.sql 53782 2016-03-22 11:00:16Z nasrullah.dusenmahamad $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT TaxTLEO.TAX_REGIME_CODE RES_TAX_REGIME_CODE
,ZFPOMV.PARTY_NAME RES_CONFIGURATION_OWNER
,TaxTLEO.TAX RES_TAX
,TaxTLEO.TAX_FULL_NAME RES_TAX_NAME
,TO_CHAR(TaxTLEO.EFFECTIVE_FROM,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(TaxTLEO.EFFECTIVE_TO,'DD-Mon-YYYY') RES_END_DATE
,DECODE(TaxTLEO.LIVE_FOR_PROCESSING_FLAG,'Y','Yes','No') RES_ENABLE_TAX_FOR_TRANSACTION
,TaxTLEO.ZONE_GEOGRAPHY_TYPE RES_GEOGRAPHY_TYPE
,TaxTLEO.PARENT_GEOGRAPHY_TYPE RES_PARENT_GEOGRAPHY_TYPE
,HzGeographies.GEOGRAPHY_NAME RES_PARENT_GEOGRAPHY_NAME
,TaxTLEO.OVERRIDE_GEOGRAPHY_TYPE RES_OVERRIDE_GEOGRAPHY_TYPE
,(SELECT CurrencyPEO.CURRENCY_CODE || ' - ' || CurrencyPEO.NAME
	FROM fnd_currencies_vl CurrencyPEO
	,fnd_lookup_values_b LookupsPEO
	WHERE LookupsPEO.view_application_id(+) = 101
	AND LookupsPEO.lookup_type(+)           = 'GL_CURRENCY_PREFERENCES'
	AND LookupsPEO.enabled_flag(+)          = 'Y'
	AND CurrencyPEO.currency_code           = LookupsPEO.lookup_code(+)
	AND CurrencyPEO.currency_code           = TaxTLEO.TAX_CURRENCY_CODE
	) RES_TAX_CURRENCY
/*,TaxTLEO.MINIMUM_ACCOUNTABLE_UNIT RES_TAX_MINIMUM_ACCOUNTABLE_UN*/
,decode(substr(TaxTLEO.MINIMUM_ACCOUNTABLE_UNIT, 1, 1),'.', trim(to_char(TaxTLEO.MINIMUM_ACCOUNTABLE_UNIT,'0.99')) ,  TaxTLEO.MINIMUM_ACCOUNTABLE_UNIT ) RES_TAX_MINIMUM_ACCOUNTABLE_UN
,TaxTLEO.TAX_PRECISION RES_TAX_PRECISION
,(SELECT USER_CONVERSION_TYPE 
	FROM GL_DAILY_CONVERSION_TYPES
	WHERE CONVERSION_TYPE = TaxTLEO.EXCHANGE_RATE_TYPE
	) RES_CONVERSION_RATE_TYPE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ZX_ROUNDING_RULE'
	AND LOOKUP_CODE   = TaxTLEO.ROUNDING_RULE_CODE
	) RES_ROUNDING_RULE
,TAXABLE_AMT_MAU RES_TAXABLE_BASIS_MINIMUM_ACCO
,TaxTLEO.COMPOUNDING_PRECEDENCE RES_COMPOUNDING_PRECEDENCE
,TaxTLEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,TaxTLEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,TaxTLEO.CREATED_BY RSC_CREATED_BY
,TaxTLEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(CASE 
	WHEN ZFPOMV.PARTY_TYPE_CODE = 'OU' THEN	
		ZFPOMV.BU_ID
	ELSE
		NULL
	END) RSC_BUSINESS_UNIT_ID
,(CASE 
	WHEN ZFPOMV.PARTY_TYPE_CODE = 'FIRST_PARTY' THEN	
		ZFPOMV.LEGAL_ENTITY_ID
	ELSE
		NULL
	END) RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM ZX_TAXES_VL TaxTLEO
,ZX_FIRST_PARTY_ORGS_MOAC_V ZFPOMV
,ZX_REGIMES_VL RegimeTLEO
,HZ_GEOGRAPHIES HzGeographies
WHERE ZFPOMV.PARTY_TAX_PROFILE_ID                = TaxTLEO.CONTENT_OWNER_ID
AND RegimeTLEO.TAX_REGIME_CODE                   = TaxTLEO.TAX_REGIME_CODE
AND TaxTLEO.PARENT_GEOGRAPHY_ID                  = HzGeographies.GEOGRAPHY_ID(+)
AND NVL(RegimeTLEO.REGIME_TYPE_FLAG,'I')         <> 'I'
ORDER BY DECODE(TaxTLEO.TAX_TYPE_CODE,'OFFSET',1,2) 
,RES_TAX
,RES_TAX_REGIME_CODE
,RES_START_DATE