 /* ****************************************************************************
 * $Revision: 48884 $:
 * $Author: dhara.pithadiya $:
 * $Date: 2015-08-18 14:24:02 +0700 (Tue, 18 Aug 2015) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Transaction%20Types%20-%20Manage%20Transaction%20Types.sql $:
 * $Id: Manage Transaction Types - Manage Transaction Types.sql 48884 2015-08-18 07:24:02Z dhara.pithadiya $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PJO_PLANNING_OPTIONS

WITH CHECK_SAME_CONV AS(SELECT PLANNING_OPTION_ID 
	,(CASE
	WHEN (PFC_COST_RATE_TYPE = PC_COST_RATE_TYPE AND PFC_COST_RATE_TYPE = RATE_SCH_COST_RATE_TYPE)
		AND (PFC_COST_RATE_DATE_TYPE = PC_COST_RATE_DATE_TYPE AND PFC_COST_RATE_DATE_TYPE = RATE_SCH_COST_RATE_DATE_TYPE)
		AND (PFC_COST_RATE_DATE = PC_COST_RATE_DATE AND PFC_COST_RATE_DATE = RATE_SCH_COST_RATE_DATE) THEN
			'Y'
		ELSE 'N'
		END) USE_SAME_CONV
	FROM PJO_PLANNING_OPTIONS
	WHERE PROJECT_ID = 0
	)

SELECT planTypesE0.NAME RES_NAME
,DECODE(checkSameConvsE0.USE_SAME_CONV,'Y','Yes','No') RES_USE_SAME_CONVERSION_ATTRIB
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'Y' THEN
			(SELECT USER_CONVERSION_TYPE 
				FROM GL_DAILY_CONVERSION_TYPES 
				WHERE CONVERSION_TYPE = planOptionsE0.PC_COST_RATE_TYPE)
	END) RES_RATE_TYPE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'Y' THEN
			(SELECT MEANING
				FROM FND_LOOKUPS
				WHERE LOOKUP_TYPE = 'PJO_PRJ_PLN_RATE_DRV_DATE_TYPE'
				AND LOOKUP_CODE = planOptionsE0.PC_COST_RATE_DATE_TYPE)
	END) RES_DATE_TYPE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'Y' THEN
			TO_CHAR(planOptionsE0.PC_COST_RATE_DATE,'DD-Mon-YYYY')
	END) RES_FIXED_DATE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			(SELECT USER_CONVERSION_TYPE 
				FROM GL_DAILY_CONVERSION_TYPES 
				WHERE CONVERSION_TYPE = planOptionsE0.PC_COST_RATE_TYPE)
	END) RES_RATE_TYPE_FOR_PROJECT_CURR
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			(SELECT MEANING
				FROM FND_LOOKUPS
				WHERE LOOKUP_TYPE = 'PJO_PRJ_PLN_RATE_DRV_DATE_TYPE'
				AND LOOKUP_CODE = planOptionsE0.PC_COST_RATE_DATE_TYPE)
	END) RES_PROJECT_DATE_TYPE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			TO_CHAR(planOptionsE0.PC_COST_RATE_DATE,'DD-Mon-YYYY')
	END) RES_PROJECT_FIXED_DATE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			(SELECT USER_CONVERSION_TYPE 
				FROM GL_DAILY_CONVERSION_TYPES 
				WHERE CONVERSION_TYPE = planOptionsE0.PFC_COST_RATE_TYPE)
	END) RES_RATE_TYPE_FOR_LEDGER_CURRE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			(SELECT MEANING
				FROM FND_LOOKUPS
				WHERE LOOKUP_TYPE = 'PJO_PRJ_PLN_RATE_DRV_DATE_TYPE'
				AND LOOKUP_CODE = planOptionsE0.PFC_COST_RATE_DATE_TYPE)
	END) RES_LEDGER_DATE_TYPE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			TO_CHAR(planOptionsE0.PFC_COST_RATE_DATE,'DD-Mon-YYYY')
	END) RES_LEDGER_FIXED_DATE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			(SELECT USER_CONVERSION_TYPE 
				FROM GL_DAILY_CONVERSION_TYPES 
				WHERE CONVERSION_TYPE = planOptionsE0.RATE_SCH_COST_RATE_TYPE)
	END) RES_RATE_TYPE_FOR_PLANNING_CUR
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			(SELECT MEANING
				FROM FND_LOOKUPS
				WHERE LOOKUP_TYPE = 'PJO_PRJ_PLN_RATE_DRV_DATE_TYPE'
				AND LOOKUP_CODE = planOptionsE0.RATE_SCH_COST_RATE_DATE_TYPE)
	END) RES_PLANNING_DATE_TYPE
,(CASE
		WHEN checkSameConvsE0.USE_SAME_CONV = 'N' THEN
			TO_CHAR(planOptionsE0.RATE_SCH_COST_RATE_DATE,'DD-Mon-YYYY')
	END) RES_PLANNING_FIXED_DATE
,planOptionsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,planOptionsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,planOptionsE0.CREATED_BY  RSC_CREATED_BY
,planOptionsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJO_PLAN_TYPES_VL planTypesE0
,PJO_PLANNING_OPTIONS planOptionsE0
,CHECK_SAME_CONV checkSameConvsE0
WHERE planTypesE0.PLAN_TYPE_CODE = 'PROJECT_PLAN'
AND planTypesE0.PLAN_TYPE_ID = planOptionsE0.PLAN_TYPE_ID
AND planOptionsE0.PROJECT_ID = 0
AND planOptionsE0.PLANNING_OPTION_ID = checkSameConvsE0.PLANNING_OPTION_ID
ORDER BY planTypesE0.NAME