/* ****************************************************************************
 * $Revision: 78786 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-06-20 10:56:13 +0700 (Mon, 20 Jun 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Transaction%20Types%20-%20Transaction%20Types%20-%20DFF.sql $:
 * $Id: Manage Transaction Types - Transaction Types - DFF.sql 78786 2022-06-20 03:56:13Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=7003##RES##JGxRACustTrxTypes
-- DFF_ATTRIBUTES=GLOBAL_ATTRIBUTE,GLOBAL_ATTRIBUTE_NUMBER,GLOBAL_ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

select DISTINCT FND_SETID_SETS_VL.SET_NAME RES_TRANSACTION_TYPE_SET
,RaCustTrxTypesAll.NAME RES_NAME
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE1 
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE2
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE3
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE4
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE5
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE6
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE7
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE8
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE9
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE10
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE11
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE12
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE13
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE14
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE15
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE16
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE17
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE18
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE19
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE20
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER1
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER2
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER3
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER4
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER5
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE1
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE2
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE3
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE4
,RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE5
,RaCustTrxTypesAll.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,RaCustTrxTypesAll.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,RaCustTrxTypesAll.CREATED_BY  RSC_CREATED_BY
,RaCustTrxTypesAll.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,RaCustTrxTypesAll.LEGAL_ENTITY_ID RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM FUSION.RA_CUST_TRX_TYPES_ALL RaCustTrxTypesAll
,FUSION.FND_SETID_SETS_VL 
WHERE (RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_CATEGORY IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE1 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE2 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE3 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE4 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE5 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE6 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE7 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE8 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE9 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE10 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE11 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE12 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE13 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE14 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE15 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE16 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE17 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE18 IS NOT NULL OR 
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE19 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER1 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER2 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER3 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER4 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_NUMBER5 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE1 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE2 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE3 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE4 IS NOT NULL OR
	RaCustTrxTypesAll.GLOBAL_ATTRIBUTE_DATE5 IS NOT NULL )
AND  FND_SETID_SETS_VL.SET_ID = RaCustTrxTypesAll.SET_ID 
order by RES_NAME