/* ****************************************************************************
 * $Revision: 78982 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-07-13 10:28:17 +0700 (Wed, 13 Jul 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Bank%20Accounts%20-%20Accounts.sql $:
 * $Id: Manage Bank Accounts - Accounts.sql 78982 2022-07-13 03:28:17Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- FIELD_TO_APPLY_FUNCTION=RES_CASH/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_CASH_CLEARING/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_RECONCILIATION_DIFFERENCES/GET_CODE_COMBINATION
 
SELECT BankBranchSimplePEO.BANK_NAME RES_BANK
,BankBranchSimplePEO.COUNTRY_NAME RES_COUNTRY
,BankBranchSimplePEO.BANK_BRANCH_NAME RES_BANK_BRANCH
,BankBranchSimplePEO.BRANCH_NUMBER  RES_BRANCH_NUMBER
,CeBankAccounts.BANK_ACCOUNT_NAME RES_ACCOUNT_NAME
,CeBankAccounts.BANK_ACCOUNT_NUM RES_ACCOUNT_NUMBER
,(SELECT curr.CURRENCY_CODE || ' - ' || curr.NAME
	FROM fnd_currencies_vl curr
	WHERE curr.CURRENCY_CODE = CeBankAccounts.CURRENCY_CODE
	) RES_CURRENCY
,XleEntityProfiles.NAME RES_LEGAL_ENTITY_NAME
,XleEntityProfiles.LEGAL_ENTITY_IDENTIFIER RES_LEGAL_ENTITY_IDENTIFIER
,NULL RES_TAX_REGISTRATION_NUMBER
,(SELECT aa.meaning
	FROM FND_LOOKUP_VALUES_VL aa
	WHERE aa.lookup_type = 'BANK_ACCOUNT_TYPE'
	AND aa.lookup_code   = CeBankAccounts.BANK_ACCOUNT_TYPE
	) RES_ACCOUNT_TYPE
,CeBankAccounts.DESCRIPTION RES_DESCRIPTION
,CeBankAccounts.IBAN_NUMBER RES_IBAN
,CeBankAccounts.CHECK_DIGITS RES_CHECK_DIGIT
,(CASE WHEN BankBranchSimplePEO.COUNTRY = 'GB'
	THEN NULL
	ELSE CeBankAccounts.SECONDARY_ACCOUNT_REFERENCE  
	END) RES_SECONDARY_ACCOUNT_REFERENC
,(CASE WHEN BankBranchSimplePEO.COUNTRY = 'GB'
	THEN CeBankAccounts.SECONDARY_ACCOUNT_REFERENCE  
	ELSE NULL
	END) RES_BUILDING_SOCIETY_ROLL_NUMB
,NULL RES_BANK_ACCOUNT_REFERENCE_TYP
,CeBankAccounts.SECONDARY_ACCOUNT_REFERENCE RES_BANK_ACCOUNT_REFERENCE_NUM
,CeBankAccounts.ACCOUNT_SUFFIX RES_ACCOUNT_SUFFIX
,DECODE(CeBankAccounts.AP_USE_ALLOWED_FLAG,'Y','Yes','No') RES_ACCOUNT_USE_PAYABLES
,DECODE(CeBankAccounts.PAY_USE_ALLOWED_FLAG,'Y','Yes','No') RES_ACCOUNT_USE_PAYROLL
,DECODE(CeBankAccounts.AR_USE_ALLOWED_FLAG,'Y','Yes','No') RES_ACCOUNT_USE_RECEIVABLES
,CeBankAccounts.ASSET_CODE_COMBINATION_ID RES_CASH
,CeBankAccounts.CASH_CLEARING_CCID RES_CASH_CLEARING
,CeBankAccounts.BANK_CHARGES_CCID RES_RECONCILIATION_DIFFERENCES
,CeBankAccounts.BANK_ACCOUNT_NAME_ALT RES_ALTERNATE_ACCOUNT_NAME
,CeBankAccounts.ACCOUNT_HOLDER_NAME RES_ACCOUNT_HOLDER
,CeBankAccounts.ACCOUNT_HOLDER_NAME_ALT RES_ALTERNATE_ACCOUNT_HOLDER
,CeBankAccounts.EFT_USER_NUM RES_EFT_NUMBER
,CeBankAccounts.AGENCY_LOCATION_CODE RES_AGENCY_LOCATION_CODE
,DECODE(DECODE(CeBankAccounts.end_date,NULL,'Y','N'),'Y','Yes','No') RES_ACTIVE
,DECODE(CeBankAccounts.MULTI_CURRENCY_ALLOWED_FLAG,'Y','Yes','No') RES_MULTICURRENCY_ACCOUNT
,DECODE(CeBankAccounts.NETTING_ACCT_FLAG,'Y','Yes','No') RES_NETTING_ACCOUNT
,CeBankAccounts.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,CeBankAccounts.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,CeBankAccounts.CREATED_BY RSC_CREATED_BY
,CeBankAccounts.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,CeBankAccounts.ACCOUNT_OWNER_ORG_ID RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CE_BANK_ACCOUNTS CeBankAccounts
,XLE_ENTITY_PROFILES XleEntityProfiles
,CE_BANK_BRANCHES_SIMPLE_V BankBranchSimplePEO
WHERE((CeBankAccounts.ACCOUNT_OWNER_ORG_ID = XleEntityProfiles.LEGAL_ENTITY_ID)
AND(CeBankAccounts.BANK_BRANCH_ID          = BankBranchSimplePEO.BRANCH_PARTY_ID)
AND NOT EXISTS
	(SELECT xtr.bank_account_id
	FROM ce_bank_accounts xtr
	WHERE NVL(AP_USE_ALLOWED_FLAG,'N') = 'N'
	AND NVL(AR_USE_ALLOWED_FLAG,'N')   = 'N'
	AND NVL(PAY_USE_ALLOWED_FLAG,'N')  = 'N'
	AND NVL(XTR_USE_ALLOWED_FLAG,'N')  = 'Y'
	AND xtr.bank_account_id            = CeBankAccounts.bank_account_id
	))
ORDER BY DECODE(cebankaccounts.end_date,NULL,'Y','N') DESC
,CeBankAccounts.BANK_ACCOUNT_NAME