/* ****************************************************************************
* $Revision: 66921 $:
* $Author: pisan.jariyasettachok $:
* $Date: 2018-02-22 16:47:18 +0700 (Thu, 22 Feb 2018) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/
FINANCIALS/Manage%20Asset%20Books%20-%20Reference%20Data%20Groups.sql $:
* $Id: Manage Segment Value Security Rules - Policy.sql 66921 2018-02-22 09:47:18Z pisan.jariyasettachok $:
* ****************************************************************************
* Description:
* ************************************************************************** */

SELECT QRSLT.VALUE_SET_CODE RES_VALUE_SET_CODE
,QRSLT.name RES_NAME
,QRSLT.START_DATE RES_START_DATE
,QRSLT.END_DATE RES_END_DATE
,QRSLT.APPLICATION_NAME RES_MODULE
,QRSLT.DESCRIPTION RES_DESCRIPTION
,(SELECT ROLE_NAME
	FROM PER_ROLES_DN_VL
	WHERE ROLE_COMMON_NAME = QRSLT.ROLE_NAME) RES_DISPLAY_ROLE_NAME
,QRSLT.ROLE_NAME RES_ROLE_NAME
,(
	CASE
		WHEN QRSLT.IS_ENTERPRISE_ROLE = 'N'
		THEN QRSLT.ROLE_NAME_SPACE
		ELSE NULL
	END) RES_APPLICATION
,DECODE(QRSLT.INSTANCE_TYPE,'GLOBAL','All Values','INSTANCE','Single Value','Multiple Values') RES_ROW_SET
,(
	CASE
		WHEN QRSLT.INSTANCE_TYPE = 'INSTANCE'
		THEN 'VALUE_ID'
		ELSE NULL
	END) RES_SINGLE_VALUE_NAME
,(
	CASE
		WHEN QRSLT.INSTANCE_TYPE = 'INSTANCE'
		THEN 'NUMBER'
		ELSE NULL
	END) RES_SINGLE_VALUE_TYPE
,(
	CASE
		WHEN QRSLT.INSTANCE_TYPE = 'INSTANCE'
		THEN QRSLT.INSTANCE_PK1_VALUE
		ELSE NULL
	END) RES_SINGLE_VALUE_VALUE
,(
	CASE
		WHEN QRSLT.INSTANCE_TYPE = 'SET'
		THEN QRSLT.DISPLAY_NAME2
		ELSE NULL
	END) RES_MULTIPLE_VALUES_CONDITION
,(
	CASE
		WHEN QRSLT.INSTANCE_TYPE = 'SET'
		THEN QRSLT.DESCRIPTION2
		ELSE NULL
	END) RES_MULTIPLE_VALUES_DESCRIPTIO
,QRSLT.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY RSC_CREATED_BY
,QRSLT.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM
	(SELECT ValueSetEO.VALUE_SET_ID
	,ValueSetEO.VALUE_SET_CODE
	,ValueSetEO.PROTECTED_FLAG
	,ValueSetEO.MODULE_ID
	,ValueSetEO.VALIDATION_TYPE
	,ValueSetEO.VALUE_DATA_TYPE
	,VALUESETEO.SECURITY_ENABLED_FLAG
	,VALUESETEO.DATA_SECURITY_OBJECT_NAME
	,ApplTaxonomyPEO.MODULE_ID AS MODULE_ID1
	,ApplTaxonomyPEO.MODULE_TYPE
	,ApplTaxonomyPEO.MODULE_KEY
	,ApplTaxonomyPEO.USER_MODULE_NAME
	,ValidationTypeLookupPEO.LOOKUP_TYPE
	,ValidationTypeLookupPEO.LOOKUP_CODE
	,ValidationTypeLookupPEO.MEANING
	,ValueDataTypeLookupPEO.LOOKUP_TYPE
	,ValueDataTypeLookupPEO.LOOKUP_CODE
	,ValueDataTypeLookupPEO.MEANING
	,FNDGRANTSEO.name
	,FNDGRANTSEO.ROLE_NAME
	,FNDGRANTSEO.ROLE_NAME_SPACE
	,TO_CHAR(FNDGRANTSEO.START_DATE,'DD-Mon-YYYY') START_DATE
	,TO_CHAR(FNDGRANTSEO.END_DATE,'DD-Mon-YYYY') END_DATE
	,ApplicationPEO.APPLICATION_NAME
	,FndGrantsEO.DESCRIPTION
	,FndGrantsEO.CREATED_BY
	,FndGrantsEO.CREATION_DATE
	,FNDGRANTSEO.LAST_UPDATED_BY
	,FNDGRANTSEO.LAST_UPDATE_DATE
	,FNDGRANTSEO.IS_ENTERPRISE_ROLE
	,FNDGRANTSEO.INSTANCE_TYPE
	,FNDGRANTSEO.INSTANCE_PK1_VALUE
	,FNDGRANTSEO.OBJECT_ID
	,FNDOBJECTINSTANCESETSEO.DISPLAY_NAME DISPLAY_NAME2
	,FndObjectInstanceSetsEO.DESCRIPTION DESCRIPTION2
	FROM FND_VS_VALUE_SETS ValueSetEO
	,FND_APPL_TAXONOMY_VL ApplTaxonomyPEO
	,FND_LOOKUPS ValidationTypeLookupPEO
	,FND_LOOKUPS ValueDataTypeLookupPEO
	,FND_OBJECTS_VL
	,FND_GRANTS FNDGRANTSEO
	,FND_APPLICATION_VL APPLICATIONPEO
	,FND_OBJECT_INSTANCE_SETS_VL FndObjectInstanceSetsEO
	WHERE ValueSetEO.MODULE_ID               = ApplTaxonomyPEO.MODULE_ID
	AND ValueSetEO.VALIDATION_TYPE           = ValidationTypeLookupPEO.LOOKUP_CODE
	AND VALUESETEO.VALUE_DATA_TYPE           = VALUEDATATYPELOOKUPPEO.LOOKUP_CODE
	AND FND_OBJECTS_VL.DATABASE_OBJECT_NAME  = 'FND_VS_VALUES_VL'
	AND VALUESETEO.DATA_SECURITY_OBJECT_NAME = FND_OBJECTS_VL.obj_name
	AND FNDGRANTSEO.OBJECT_ID                = FND_OBJECTS_VL.OBJECT_ID
	AND FNDGRANTSEO.MODULE_ID                = APPLICATIONPEO.MODULE_ID
	AND FNDGRANTSEO.object_id               IN
		(SELECT object_id
		FROM fnd_objects obj
		WHERE(1 = 1)
		)
	/*AND(ValueSetEO.module_id IN
		(SELECT rf.child_module_id
		FROM fnd_appl_taxonomy_rf rf
		INNER JOIN fnd_appl_taxonomy t
		ON RF.ANCESTOR_MODULE_ID = T.MODULE_ID
		WHERE T.MODULE_TYPE      = 'APPLICATION'
		AND t.module_key         = 'GL'
		))*/
	AND(((VALUESETEO.VALUE_SET_CODE NOT LIKE('%$FLEX$%'))
	AND(VALIDATIONTYPELOOKUPPEO.LOOKUP_TYPE = 'FND_VS_VALIDATION_TYPES')
	AND(VALUEDATATYPELOOKUPPEO.LOOKUP_TYPE  = 'FND_VS_VALUE_DATA_TYPES')))
	AND FNDGRANTSEO.INSTANCE_SET_ID         = FndObjectInstanceSetsEO.INSTANCE_SET_ID(+)
	) QRSLT
ORDER BY QRSLT.VALUE_SET_CODE