/* ****************************************************************************
 * $Revision: 56623 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-07-11 14:33:44 +0700 (Mon, 11 Jul 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Journal%20Sources%20-%20Manage%20Journal%20Sources.sql $:
 * $Id: Manage Journal Sources - Manage Journal Sources.sql 56623 2016-07-11 07:33:44Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT AuditRuleSetEO.NAME RES_NAME
,AuditRuleSetEO.DESCRIPTION RES_DESCRIPTION
,DECODE(AuditRuleSetEO.RANDOM_AUDIT_FLAG,'Y','Yes','No') RES_AUDIT_A_PERCENTAGE_OF_ALL_
,AuditRuleSetEO.RANDOM_AUDIT_PERCENTAGE RES_AUDIT_A_PERCENTAGE_OF_AL_0
,DECODE(AuditRuleSetEO.IGNORE_CREDIT_ONLY_FLAG,'Y','Yes','No') RES_IGNORE_EXPENSE_REPORTS_THA
,DECODE(AuditRuleSetEO.IGNORE_RCPT_NOT_REQ_FLAG,'Y','Yes','No') RES_IGNORE_EXPENSE_REPORTS_T_1
,DECODE(AuditRuleSetEO.TOTAL_AMOUNT_FLAG,'Y','Yes','No') RES_AUDIT_EXPENSE_REPORTS_GREA
,(CASE
	WHEN AuditRuleSetEO.TOTAL_AMOUNT_FLAG = 'Y' THEN
		DECODE(AuditRuleSetEO.TOTAL_AMOUNT_CURRENCY_CODE,NULL,NULL
			,AuditRuleSetEO.TOTAL_AMOUNT_CURRENCY_CODE || ' - ' || (SELECT NAME FROM FND_CURRENCIES_VL WHERE CURRENCY_CODE = AuditRuleSetEO.TOTAL_AMOUNT_CURRENCY_CODE))
	END) RES_AUDIT_EXPENSE_REPORTS_GR_2
,(CASE
	WHEN AuditRuleSetEO.TOTAL_AMOUNT_FLAG = 'Y' THEN
		AuditRuleSetEO.TOTAL_AMOUNT_LIMIT
	END) RES_AUDIT_EXPENSE_REPORTS_GR_3
,DECODE(AuditRuleSetEO.RECEIPTS_REQUIRED_FLAG,'Y','Yes','No') RES_AUDIT_EXPENSE_REPORTS_WITH
,DECODE(AuditRuleSetEO.IMAGE_RECEIPT_MISSING_FLAG,'Y','Yes','No') RES_AUDIT_EXPENSE_REPORTS_WI_4
,DECODE(AuditRuleSetEO.POLICY_VIOLATIONS_FLAG,'Y','Yes','No') RES_AUDIT_EXPENSE_REPORTS_WI_5
,DECODE(AuditRuleSetEO.EMPLOYEE_ON_AUDIT_LIST_FLAG,'Y','Yes','No') RES_AUDIT_EXPENSE_REPORTS_OF_I
,DECODE(AuditRuleSetEO.AGED_EXPENSE_FLAG,'Y','Yes','No') RES_AUDIT_EXPENSE_REPORTS_WI_6
,AuditRuleSetEO.AGED_EXPENSE_DAYS RES_AUDIT_EXPENSE_REPORTS_WI_7
,DECODE(AuditRuleSetEO.EMPLOYMENT_STATUS_FLAG,'Y','Yes','No') RES_AUDIT_EXPENSE_REPORTS_OF_8
,DECODE(AuditRuleSetEO.EMPLOYMENT_STATUS_FLAG,'Y',(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_AUDIT_EMPLOYMENT_STATUS'
	AND LOOKUP_CODE = AuditRuleSetEO.EMPLOYMENT_STATUS_CODE)
	) RES_AUDIT_EXPENSE_REPORTS_OF_9
,AuditRuleSetEO.AUTO_APPROVAL_TAG RES_AUTOMATIC_APPROVAL
,AuditRuleSetEO.RECEIPT_AUDIT_TAG RES_ORIGINAL_RECEIPTS_AUDIT
,AuditRuleSetEO.RECEIPT_IMAGE_AUDIT_TAG RES_IMAGED_RECEIPTS_AUDIT
,AuditRuleSetEO.RECEIPTLESS_AUDIT_TAG RES_NO_RECEIPTS_REQUIRED_AUDIT
,AuditRuleSetEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,AuditRuleSetEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,AuditRuleSetEO.CREATED_BY RSC_CREATED_BY
,AuditRuleSetEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EXM_AUD_RULE_SETS AuditRuleSetEO
ORDER BY AuditRuleSetEO.NAME