/* ****************************************************************************
 * $Revision: 71754 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2019-04-02 17:28:55 +0700 (Tue, 02 Apr 2019) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Time%20Repository%20Rule%20Sets%20-%20Rule%20Set.sql $:
 * $Id: Manage Time Repository Rule Sets - Rule Set.sql 71754 2019-04-02 10:28:55Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT hwmRULESETEO.RULE_SET_NAME RES_NAME
,hwmRULESETEO.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE
	LOOKUP_CODE = hwmRULESETEO.RULE_TYPE AND LOOKUP_TYPE = 'HWM_RULE_TYPE' AND LANGUAGE = USERENV('LANG')) RES_RULE_SET_TYPE
,TO_CHAR(hwmRULESETEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,TO_CHAR(hwmRULESETEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_END_DATE


,hwmRULESETEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hwmRULESETEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hwmRULESETEO.CREATED_BY RSC_CREATED_BY
,hwmRULESETEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HWM_RULE_SETS_F  hwmRULESETEO
WHERE SYSDATE BETWEEN hwmRULESETEO.EFFECTIVE_START_DATE AND hwmRULESETEO.EFFECTIVE_END_DATE
ORDER BY hwmRULESETEO.RULE_SET_NAME