/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

WITH AccountDateE0 AS (SELECT SourcesE0.NAME
	,JersAssignsE0.AMB_CONTEXT_CODE
	,JersAssignsE0.APPLICATION_ID
	,JersAssignsE0.EVENT_CLASS_CODE
	,JersAssignsE0.JERS_CODE
	,JersAssignsE0.JERS_TYPE_CODE
	,JersAssignsE0.EVENT_TYPE_CODE
	,JersAssignsE0.ACCOUNTING_ATTRIBUTE_CODE
	FROM XLA_SOURCES_VL SourcesE0
	,XLA_JERS_ATTRS_ASSGNS JersAssignsE0
	WHERE SourcesE0.SOURCE_CODE = JersAssignsE0.SOURCE_CODE
	AND SourcesE0.SOURCE_TYPE_CODE = JersAssignsE0.SOURCE_TYPE_CODE
	AND SourcesE0.APPLICATION_ID = JersAssignsE0.SOURCE_APPLICATION_ID
	AND SourcesE0.DATATYPE_CODE = 'D'
	) 
 
 
SELECT (SELECT APPLICATION_NAME
	FROM XLA_SUBLEDGERS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND APPLICATION_ID = SubledgerRuleSetsE0.APPLICATION_ID
	) RES_SUBLEDGER_APPLICATION
,SubledgerRuleSetsE0.NAME  RES_NAME
,SubledgerRuleSetsE0.JERS_CODE RES_SHORT_NAME
,SubledgerRuleSetsE0.DESCRIPTION  RES_DESCRIPTION
,(SELECT NAME 
	FROM XLA_EVENT_CLASSES_TL
	WHERE EVENT_CLASS_CODE = SubledgerRuleSetsE0.EVENT_CLASS_CODE
	AND APPLICATION_ID = SubledgerRuleSetsE0.APPLICATION_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_EVENT_CLASS
,(SELECT NAME 
	FROM XLA_EVENT_TYPES_TL
	WHERE EVENT_CLASS_CODE = SubledgerRuleSetsE0.EVENT_CLASS_CODE
	AND EVENT_TYPE_CODE = SubledgerRuleSetsE0.EVENT_TYPE_CODE
	AND APPLICATION_ID = SubledgerRuleSetsE0.APPLICATION_ID
	AND LANGUAGE = USERENV('LANG')	
	) RES_EVENT_TYPE
,(SELECT NAME 
	FROM FND_KF_STR_INSTANCES_VL
	WHERE STRUCTURE_INSTANCE_NUMBER = SubledgerRuleSetsE0.ACCOUNTING_COA_ID 
	) RES_CHART_OF_ACCOUNTS
,DECODE(SubledgerRuleSetsE0.STATUS_CODE,'ACTIVE','Active','Incomplete') RES_STATUS
,(SELECT NAME FROM AccountDateE0 
WHERE SubledgerRuleSetsE0.AMB_CONTEXT_CODE = AccountDateE0.AMB_CONTEXT_CODE(+)
AND SubledgerRuleSetsE0.APPLICATION_ID = AccountDateE0.APPLICATION_ID(+)
AND SubledgerRuleSetsE0.EVENT_CLASS_CODE = AccountDateE0.EVENT_CLASS_CODE(+)
AND SubledgerRuleSetsE0.JERS_CODE = AccountDateE0.JERS_CODE(+)
AND SubledgerRuleSetsE0.JERS_TYPE_CODE = AccountDateE0.JERS_TYPE_CODE(+)
AND SubledgerRuleSetsE0.EVENT_TYPE_CODE = AccountDateE0.EVENT_TYPE_CODE(+)
AND AccountDateE0.ACCOUNTING_ATTRIBUTE_CODE = 'GL_DATE') RES_ACCOUNTING_DATE
,(SELECT NAME FROM AccountDateE0 
WHERE SubledgerRuleSetsE0.AMB_CONTEXT_CODE = AccountDateE0.AMB_CONTEXT_CODE(+)
AND SubledgerRuleSetsE0.APPLICATION_ID = AccountDateE0.APPLICATION_ID(+)
AND SubledgerRuleSetsE0.EVENT_CLASS_CODE = AccountDateE0.EVENT_CLASS_CODE(+)
AND SubledgerRuleSetsE0.JERS_CODE = AccountDateE0.JERS_CODE(+)
AND SubledgerRuleSetsE0.JERS_TYPE_CODE = AccountDateE0.JERS_TYPE_CODE(+)
AND SubledgerRuleSetsE0.EVENT_TYPE_CODE = AccountDateE0.EVENT_TYPE_CODE(+)
AND AccountDateE0.ACCOUNTING_ATTRIBUTE_CODE = 'ACCRUAL_REVERSAL_GL_DATE') RES_ACCRUAL_REVERSAL_ACCOUNTIN
,(SELECT NAME
	FROM XLA_DESCRIPTIONS_TL
	WHERE DESCRIPTION_CODE = SubledgerRuleSetsE0.DESCRIPTION_CODE
	AND APPLICATION_ID = SubledgerRuleSetsE0.APPLICATION_ID
	AND DESCRIPTION_TYPE_CODE = SubledgerRuleSetsE0.DESCRIPTION_TYPE_CODE
	AND LANGUAGE = USERENV('LANG')	
	) RES_DESCRIPTION_RULE
,SubledgerRuleSetsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,SubledgerRuleSetsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,SubledgerRuleSetsE0.CREATED_BY RSC_CREATED_BY
,SubledgerRuleSetsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,SubledgerRuleSetsE0.ACCOUNTING_COA_ID RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM XLA_JE_RULE_SETS_VL SubledgerRuleSetsE0

 