/* ****************************************************************************
 * $Revision: 78418 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-05-04 14:21:52 +0700 (Wed, 04 May 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Policies%20by%20Expense%20Category%20-%20Mileage.sql $:
 * $Id: Manage Policies by Expense Category - Mileage.sql 78418 2022-05-04 07:21:52Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EXM_MILEAGE_POLICIES

SELECT 'Mileage' RES_EXPENSE_CATEGORY
,ExmMileagePolicies.POLICY_NAME RES_NAME
,ExmMileagePolicies.DESCRIPTION RES_DESCRIPTION
,(SELECT TERRITORY_SHORT_NAME 
	FROM FND_TERRITORIES_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND TERRITORY_CODE = ExmMileagePolicies.COUNTRY_CODE
	) RES_COUNTRY
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_CURRENCY_OPTION'
	AND LOOKUP_CODE = ExmMileagePolicies.CURRENCY_OPTION_CODE
	) RES_RATE_CURRENCY
,(CASE
	WHEN ExmMileagePolicies.CURRENCY_OPTION_CODE = 'MULTIPLE' THEN
		NULL
	ELSE
		ExmMileagePolicies.CURRENCY_CODE||' - '||
		(SELECT NAME 
			FROM FND_CURRENCIES_TL
			WHERE CURRENCY_CODE = ExmMileagePolicies.CURRENCY_CODE
			AND LANGUAGE = USERENV('LANG'))
	END) RES_CURRENCY
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_UNIT_OF_MEASURE'
	AND LOOKUP_CODE = ExmMileagePolicies.UNIT_OF_MEASURE_CODE
	) RES_UNIT_OF_MEASURE	
,DECODE(ExmMileagePolicies.ENABLED_STD_DEDUCTION_FLAG,'Y','Yes','No') RES_STANDARD_MILEAGE_DEDUCTION
,ExmMileagePolicies.MILEAGE_DEDUCTION RES_DISTANCE_DEDUCTION
,DECODE(ExmMileagePolicies.ENABLED_ELIGIBILITY_FLAG,'Y','Yes','No') RES_MINIMUM_DISTANCE_FOR_MILEA
,ExmMileagePolicies.ELIGIBILITY_DISTANCE RES_MINIMUM_DISTANCE
,DECODE(ExmMileagePolicies.ENABLED_DEDUCT_COMMUTE_FLAG,'Y','Yes','No') RES_ENABLE_COMMUTE_MILEAGE_DED
,(CASE WHEN ExmMileagePolicies.ENABLED_DEDUCT_COMMUTE_FLAG = 'Y' THEN
	DECODE(ExmMileagePolicies.COMMUTE_DISTANCE_REQUIRED_FLAG,'Y','Required per day','Optional') 
	ELSE NULL END)RES_COMMUTE_MILEAGE_DEDUCTION
,DECODE(ExmMileagePolicies.ENABLED_ROLE_FLAG,'Y','Yes','No') RES_ROLE
,(CASE
	WHEN ExmMileagePolicies.ENABLED_ROLE_FLAG = 'Y' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_POLICY_ROLE'
		AND LOOKUP_CODE = ExmMileagePolicies.POLICY_ROLE_CODE)
	END) RES_ROLE_TYPE
,DECODE(ExmMileagePolicies.ENABLED_LOCATION_FLAG,'Y','Yes','No') RES_LOCATION
,(CASE
	WHEN ExmMileagePolicies.ENABLED_LOCATION_FLAG = 'Y' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_LOCATION_TYPE'
		AND LOOKUP_CODE = ExmMileagePolicies.LOCATION_TYPE_CODE)
	END) RES_LOCATION_TYPE
,(CASE
	WHEN ExmMileagePolicies.ENABLED_LOCATION_FLAG = 'Y' AND ExmMileagePolicies.LOCATION_TYPE_CODE = 'ZONE' THEN
		(SELECT MEANING 
			FROM FND_LOOKUP_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = ExmMileagePolicies.ZONE_TYPE_CODE)
	END) RES_ZONE_TYPE
,DECODE(ExmMileagePolicies.ENABLED_GENDER_FLAG,'Y','Yes','No') RES_GENDER
,DECODE(ExmMileagePolicies.DISTANCE_THRESHOLD_FLAG,'Y','Yes','No') RES_DISTANCE_THRESHOLD
,(CASE
	WHEN ExmMileagePolicies.DISTANCE_THRESHOLD_FLAG = 'Y' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_THRESHOLD_PERIOD'
		AND LOOKUP_CODE = ExmMileagePolicies.APPLY_THRESHOLD_BY_CODE)
	END) RES_THRESHOLD_PERIOD
,DECODE(ExmMileagePolicies.ENABLED_VEH_CATEGORY_FLAG,'Y','Yes','No') RES_VEHICLE_CATEGORY
,(CASE
	WHEN ExmMileagePolicies.ENABLED_VEH_CATEGORY_FLAG = 'Y' THEN
		(SELECT MEANING 
			FROM FND_LOOKUP_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = ExmMileagePolicies.VEHICLE_CATEGORY_LIST_CODE)
	END) RES_VEHICLE_CATEGORY_SOURCE
,DECODE(ExmMileagePolicies.ENABLED_VEH_TYPE_FLAG,'Y','Yes','No') RES_VEHICLE_TYPE
,(CASE
	WHEN ExmMileagePolicies.ENABLED_VEH_TYPE_FLAG = 'Y' THEN
		(SELECT MEANING 
			FROM FND_LOOKUP_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = ExmMileagePolicies.VEHICLE_TYPE_LIST_CODE)
	END) RES_VEHICLE_TYPE_SOURCE
,DECODE(ExmMileagePolicies.ENABLED_FUEL_TYPE_FLAG,'Y','Yes','No') RES_FUEL_TYPE
,(CASE
	WHEN ExmMileagePolicies.ENABLED_FUEL_TYPE_FLAG = 'Y' THEN
		(SELECT MEANING 
			FROM FND_LOOKUP_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = ExmMileagePolicies.FUEL_TYPE_LIST_CODE)
	END) RES_FUEL_TYPE_SOURCE
,DECODE(ExmMileagePolicies.ENABLED_PASSENGER_FLAG,'Y','Yes','No') RES_ENABLE_PASSENGER_RATE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_PASSENGER_RULE'
	AND LOOKUP_CODE = ExmMileagePolicies.PASSENGER_RULE_CODE
	) RES_RATE_TYPE
,DECODE(ExmMileagePolicies.CAPTURE_PASS_NAMES_FLAG,'Y','Yes','No') RES_CAPTURE_PASSENGER_NAME
,DECODE(ExmMileagePolicies.CALC_PASS_RATE_BY_DIST_FLAG,'Y','Yes','No') RES_CALCULATE_PASSENGER_RATE_B
,DECODE(ExmMileagePolicies.ENABLED_MAX_PASS_FLAG,'Y','Yes','No') RES_RESTRICT_NUMBER_OF_PASSENG
,ExmMileagePolicies.MAXIMUM_PASSENGERS RES_MAXIMUM_NUMBER_OF_PASSENGE
,DECODE(ExmMileagePolicies.ENABLED_ADDITNL_RATES_FLAG,'Y','Yes','No') RES_ENABLE_COMPANY_SPECIFIC_RA
,(CASE
	WHEN ExmMileagePolicies.ENABLED_ADDITNL_RATES_FLAG = 'Y' THEN
		(SELECT MEANING 
			FROM FND_LOOKUP_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = ExmMileagePolicies.ADDITIONAL_RATES_LIST_CODE)
	END) RES_ENABLE_COMPANY_SPECIFIC__0
,ExmMileagePolicies.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ExmMileagePolicies.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ExmMileagePolicies.CREATED_BY RSC_CREATED_BY
,ExmMileagePolicies.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EXM_MILEAGE_POLICIES ExmMileagePolicies
ORDER BY ExmMileagePolicies.POLICY_NAME