/* ****************************************************************************
* $Revision:  $:
* $Author: Nasrullah Dusenmahamad $:
* $Date: 2017-03-17  $:
* $HeadURL: $:
* $Id: Manage Category Descriptive Flexfields - Context Segments $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT lifeEventsE0.NAME RES_NAME
,orgsE0.NAME RES_LEGAL_EMPLOYER
,TO_CHAR(orgsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(orgsE0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(orgsE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,legalsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,legalsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,legalsE0.CREATED_BY RSC_CREATED_BY
,legalsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,lifeEventsE0.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM BEN_LER_F lifeEventsE0
,(SELECT *
    FROM BEN_LE_RESOLUTIONS_F
    WHERE MAPPING_TABLE_NAME = 'BEN_LER_F'
    ) legalsE0
,(SELECT NAME
	,ORGANIZATION_ID
	,EFFECTIVE_START_DATE
	,EFFECTIVE_END_DATE
	FROM HR_ORGANIZATION_V
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND CLASSIFICATION_CODE = 'HCM_LEMP'
	) orgsE0
WHERE  lifeEventsE0.LER_ID = legalsE0.MAPPING_TABLE_PK_ID
AND legalsE0.LEGAL_ENTITY_ID = orgsE0.ORGANIZATION_ID
ORDER BY lifeEventsE0.NAME
,lifeEventsE0.EFFECTIVE_START_DATE
,orgsE0.NAME