/* ****************************************************************************
 * $Revision: 53543 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-03-15 15:46:40 +0700 (Tue, 15 Mar 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 53543 2016-03-15 08:46:40Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10011##RES##EGP_ITEM_CLASS_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.

SELECT 
(SELECT ITEM_CLASS_NAME
	FROM EGP_ITEM_CLASSES_VL
	WHERE ITEM_CLASS_ID = ItemClassPEO.PARENT_ITEM_CLASS_ID
	) RES_PARENT_ITEM_CLASS 
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,ItemClassPEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ItemClassPEO.ATTRIBUTE1
,ItemClassPEO.ATTRIBUTE2
,ItemClassPEO.ATTRIBUTE3
,ItemClassPEO.ATTRIBUTE4
,ItemClassPEO.ATTRIBUTE5
,ItemClassPEO.ATTRIBUTE6
,ItemClassPEO.ATTRIBUTE7
,ItemClassPEO.ATTRIBUTE8
,ItemClassPEO.ATTRIBUTE9
,ItemClassPEO.ATTRIBUTE10
,ItemClassPEO.ATTRIBUTE11
,ItemClassPEO.ATTRIBUTE12
,ItemClassPEO.ATTRIBUTE13
,ItemClassPEO.ATTRIBUTE14
,ItemClassPEO.ATTRIBUTE15
,ItemClassPEO.ATTRIBUTE16
,ItemClassPEO.ATTRIBUTE17
,ItemClassPEO.ATTRIBUTE18
,ItemClassPEO.ATTRIBUTE19
,ItemClassPEO.ATTRIBUTE20
,ItemClassPEO.ATTRIBUTE_NUMBER1
,ItemClassPEO.ATTRIBUTE_NUMBER2
,ItemClassPEO.ATTRIBUTE_NUMBER3
,ItemClassPEO.ATTRIBUTE_NUMBER4
,ItemClassPEO.ATTRIBUTE_NUMBER5
,ItemClassPEO.ATTRIBUTE_NUMBER6
,ItemClassPEO.ATTRIBUTE_NUMBER7
,ItemClassPEO.ATTRIBUTE_NUMBER8
,ItemClassPEO.ATTRIBUTE_NUMBER9
,ItemClassPEO.ATTRIBUTE_NUMBER10
,TO_CHAR(ItemClassPEO.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(ItemClassPEO.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(ItemClassPEO.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(ItemClassPEO.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(ItemClassPEO.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,ItemClassPEO.ATTRIBUTE_TIMESTAMP1
,ItemClassPEO.ATTRIBUTE_TIMESTAMP2
,ItemClassPEO.ATTRIBUTE_TIMESTAMP3
,ItemClassPEO.ATTRIBUTE_TIMESTAMP4
,ItemClassPEO.ATTRIBUTE_TIMESTAMP5
,ItemClassPEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemClassPEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemClassPEO.CREATED_BY RSC_CREATED_BY
,ItemClassPEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
WHERE (ItemClassPEO.ATTRIBUTE_CATEGORY       IS NOT NULL
OR ItemClassPEO.ATTRIBUTE1                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE2                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE3                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE4                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE5                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE6                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE7                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE8                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE9                IS NOT NULL
OR ItemClassPEO.ATTRIBUTE10               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE11               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE12               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE13               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE14               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE15               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE16               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE17               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE18               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE19               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE20               IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER1         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER2         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER3         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER4         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER5         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER6         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER7         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER8         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER9         IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_NUMBER10        IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_DATE1           IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_DATE2           IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_DATE3           IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_DATE4           IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_DATE5           IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_TIMESTAMP1      IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_TIMESTAMP2      IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_TIMESTAMP3      IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_TIMESTAMP4      IS NOT NULL
OR ItemClassPEO.ATTRIBUTE_TIMESTAMP5      IS NOT NULL)
CONNECT BY ItemClassPEO.PARENT_ITEM_CLASS_ID = ItemClassPEO.ITEM_CLASS_ID
ORDER SIBLINGS BY RES_PARENT_ITEM_CLASS,RES_ITEM_CLASS