/* ****************************************************************************
 * $Revision: 54943 $:
 * $Author: paul.wakefield $:
 * $Date: 2016-05-04 13:45:23 +0700 (Wed, 04 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Trading%20Community%20Person%20Lookups%20-%20Standard%20Lookup%20Type.sql $:
 * $Id: Manage Trading Community Person Lookups - Standard Lookup Type.sql 54943 2016-05-04 06:45:23Z paul.wakefield $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 /*<RSC_PRE_STEPS_LARGE_COLUMN_POSITION>8</RSC_PRE_STEPS_LARGE_COLUMN_POSITION>
	
-- The column position that using special data type.
 <RSC_PRE_STEPS_LARGE_COLUMN_TYPE>LONG</RSC_PRE_STEPS_LARGE_COLUMN_TYPE>

-- Specify what type of the data.
*/
 
SELECT payFLOWEO.FLOW_NAME  RES_FLOW_PATTERN
,payFLOWTASK.FLOW_TASK_NAME RES_FLOW_TASK
,payFLOWTASKPARAEO.PARAMETER_NAME RES_NAME
,ACTIONAME.ACTION_NAME RES_EXECUTION_MODE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payTASKPARAMETEREO.DATA_TYPE
		AND LOOKUP_TYPE = 'PAY_PARAMETER_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))  RES_DATA_TYPE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWTASKPARAEO.DEFAULT_TYPE
		AND LOOKUP_TYPE = 'PAY_TASK_DEFAULT_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_PARAMETER_BASIS
,(CASE WHEN payFLOWTASKPARAEO.DEFAULT_TYPE = 'BIND_CONTEXT' THEN
	(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWTASKPARAEO.DEFAULT_VAL
		AND LOOKUP_TYPE = 'PAY_PARAM_CONTEXT_BINDINGS' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))
	ELSE payFLOWTASKPARAEO.DEFAULT_VAL 
		END) RES_BASIS_VALUE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWTASKPARAEO.PARAM_USAGE_TYPE
		AND LOOKUP_TYPE = 'PAY_PARAM_USAGE_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_USAGE
,payFLOWTASKPARAEO.PARAM_SEQUENCE RES_SEQUENCE
,DECODE(payFLOWTASK.START_NOTIF_FLAG,'Y','Yes','No') RES_FLOW_TASK_START_NOTIFICATI
,DECODE(payFLOWTASK.END_NOTIF_FLAG,'Y','Yes','No') RES_FLOW_TASK_END_NOTIFICATION
,DECODE(payFLOWTASK.WARNING_NOTIF_FLAG,'Y','Yes','No') RES_WARNING_NOTIFICATION
,DECODE(payFLOWTASK.ERROR_NOTIF_FLAG,'Y','Yes','No') RES_ERROR
	

,payFLOWTASKPARAEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payFLOWTASKPARAEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payFLOWTASKPARAEO.CREATED_BY RSC_CREATED_BY
,payFLOWTASKPARAEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PAY_FLOWS_VL payFLOWEO
,PAY_FLOW_TASKS_VL payFLOWTASK
,PAY_FLOW_TASK_PARAMETERS_VL payFLOWTASKPARAEO
,PAY_TASK_PARAMETERS  payTASKPARAMETEREO
,(SELECT ACTION_NAME,BASE_TASK_ACTION_ID FROM PAY_TASK_ACTIONS_VL 
	WHERE ACTION_NAME = 'Submit') ACTIONAME
WHERE payFLOWEO.FLOW_ID = payFLOWTASK.BASE_FLOW_ID 
AND payFLOWTASK.BASE_FLOW_TASK_ID = payFLOWTASKPARAEO.BASE_FLOW_TASK_ID
AND payFLOWTASKPARAEO.BASE_TASK_PARAMETER_ID = payTASKPARAMETEREO.BASE_TASK_PARAMETER_ID 
AND payTASKPARAMETEREO.BASE_TASK_ACTION_ID = ACTIONAME.BASE_TASK_ACTION_ID 
AND payFLOWTASK.CATEGORY_TYPE IS NOT NULL
ORDER BY payFLOWEO.FLOW_NAME,payFLOWTASK.FLOW_TASK_NAME,payFLOWTASKPARAEO.PARAMETER_NAME