/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 -- RSC_PREREQUISITE_OBJECTS=PAY_ELEMENT_TYPES_F

SELECT  elementsE0.ELEMENT_NAME RES_ELEMENT_NAME
,legislativeDataGrpsE0.NAME RES_LEGISLATIVE_DATA_GROUP
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
	WHERE BASE_CLASSIFICATION_ID = elementsE0.CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PRIMARY_CLASSIFICATION
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
    WHERE BASE_CLASSIFICATION_ID = elementsE0.SECONDARY_CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
    ) RES_SECONDARY_CLASSIFICATION
,TO_CHAR(elementsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,elementsE0.REPORTING_NAME RES_REPORTING_NAME
,elementsE0.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = elementsE0.PROCESSING_TYPE
	AND LOOKUP_TYPE = 'PAY_PROCESSING_TYPE' AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD')))RES_RECURRING_ENTRY
,(CASE
    WHEN elementsE0.USE_AT_REL_LEVEL = 'Y' THEN
        'Payroll relationship level'
    WHEN elementsE0.USE_AT_TERM_LEVEL = 'Y' THEN
        'Term Level'
    WHEN elementsE0.USE_AT_ASG_LEVEL = 'Y' THEN
        'Assignment level'
    END) RES_EMPLOYMENT_LEVEL
,DECODE(elementsE0.ADJUSTMENT_ONLY_FLAG,'Y','Yes','No') RES_BALANCE_ADJUSTMENTS_ONLY
,DECODE(elementsE0.CLOSED_FOR_ENTRY_FLAG,'Y','Yes','No') RES_CLOSED_FOR_ENTRY
,DECODE(elementsE0.INDIRECT_ONLY_FLAG,'Y','Yes','No') RES_ACCEPT_RESULTS_FROM_FORMUL
,DECODE(elementsE0.STANDARD_LINK_FLAG,'Y','Yes','No') RES_AUTOMATIC_ENTRY
,DECODE(elementsE0.MULTIPLE_ENTRIES_ALLOWED_FLAG,'Y','Yes','No') RES_ALLOW_MULTIPLE_ENTRIES_IN_
,DECODE(elementsE0.PROCESS_IN_RUN_FLAG,'Y','Yes','No') RES_PROCESS_IN_PAYROLL_RUN
,DECODE(elementsE0.ONCE_EACH_PERIOD_FLAG,'Y','Yes','No') RES_PROCESS_ONCE_PER_PERIOD
,elementsE0.PROCESSING_PRIORITY RES_PRIORITY
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = elementsE0.FORMULA_ID
    ) RES_SKIP_RULE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PAY_ELEMENT_EXPEDITE_MODE'
    AND LOOKUP_CODE = elementsFE0.EXPEDITED_MODE
    ) RES_EXPEDITED_PROCESSING_RULE
,(SELECT DEFINITION_NAME
    FROM PAY_TIME_DEFINITIONS
    WHERE TIME_DEFINITION_ID = elementsE0.STARTING_TIME_DEF_ID
    ) RES_EARLIEST_ENTRY_DATE
,(SELECT DEFINITION_NAME
    FROM PAY_TIME_DEFINITIONS
    WHERE TIME_DEFINITION_ID = elementsE0.ENDING_TIME_DEF_ID
    ) RES_LATEST_ENTRY_DATE
,DECODE(elementsE0.GROSSUP_FLAG,'Y','Yes','No') RES_GROSS_UP_DURING_CALCULATIO
,(CASE
    WHEN elementsE0.PROCESS_MODE = 'N' THEN
        'No'
    ELSE
        'Yes'
    END) RES_PROCESS_SEPARATELY
,(CASE
    WHEN elementsE0.PROCESS_MODE = 'S' THEN
        'Yes'
    ELSE
        'No'
    END) RES_PAY_SEPARATELY_FROM_OTHER_
,DECODE(elementsE0.ITERATIVE_FLAG,'Y','Yes','No') RES_ENABLE_ITERATIVE_CALCULATI
,elementsE0.ITERATIVE_PRIORITY RES_ITERATIVE_ORDER
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = elementsE0.ITERATIVE_FORMULA_ID
    ) RES_ITERATIVE_FORMULA 
,(SELECT ELEMENT_NAME 
	FROM PAY_ELEMENT_TYPES_VL 
	WHERE BASE_ELEMENT_NAME = elementsE0.PARENT_BASE_ELEMENT_NAME
	AND LEGISLATIVE_DATA_GROUP_ID = legislativeDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PARENT_ELEMENT
,(SELECT EVENT_GROUP_NAME
    FROM PAY_EVENT_GROUPS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND EVENT_GROUP_ID = elementsE0.RECALC_EVENT_GROUP_ID
    ) RES_RETROACTIVE_EVENT_GROUP
,(SELECT EVENT_GROUP_NAME
    FROM PAY_EVENT_GROUPS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND EVENT_GROUP_ID = elementsE0.PRORATION_GROUP_ID
    ) RES_PRORATION_GROUP
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = elementsE0.PRORATION_FORMULA_ID
    ) RES_PRORATION_FORMULA
,(SELECT DEFINITION_NAME FROM PAY_TIME_DEFINITIONS WHERE TIME_DEFINITION_ID = elementsE0.TIME_DEFINITION_ID) RES_FREQUENCY
,(SELECT NAME
    FROM FND_CURRENCIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CURRENCY_CODE = elementsE0.INPUT_CURRENCY_CODE
    ) RES_INPUT_CURRENCY
,(SELECT NAME
    FROM FND_CURRENCIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CURRENCY_CODE = elementsE0.OUTPUT_CURRENCY_CODE
    ) RES_OUTPUT_CURRENCY
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = elementsE0.CALCULATION_FORMULA_ID
    ) RES_CALCULATION_FORMULA
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = elementsE0.DEFAULTING_FORMULA_ID
    ) RES_DEFAULTING_FORMULA
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = elementsE0.VALIDATION_FORMULA_ID
    ) RES_VALIDATION_FORMULA
,(SELECT NAME FROM PAY_DEDUCTION_TYPES_TL WHERE DEDUCTION_TYPE_ID = elementsE0.DEDUCTION_TYPE_ID AND LANGUAGE = USERENV('LANG')) RES_PAYROLL_COMPONENT
,elementsE0.DEDUCTION_OR_EXEMPTION RES_DEDUCTIONOREXEMPTION
,DECODE(TO_CHAR(elementsE0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(elementsE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE

,elementsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,elementsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,elementsE0.CREATED_BY RSC_CREATED_BY
,elementsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legislativeDataGrpsE0.LEGISLATION_CODE RSC_COUNTRY_ID


FROM PAY_ELEMENT_TYPES_VL elementsE0
,PAY_ELEMENT_TYPES_F elementsFE0
,(SELECT NAME
    ,LEGISLATIVE_DATA_GROUP_ID
	,LEGISLATION_CODE
    FROM PER_LEGISLATIVE_DATA_GROUPS_VL
    ) legislativeDataGrpsE0
	
WHERE elementsE0.LEGISLATIVE_DATA_GROUP_ID = legislativeDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID
AND elementsE0.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
AND elementsE0.EFFECTIVE_START_DATE = elementsFE0.EFFECTIVE_START_DATE

ORDER BY RES_ELEMENT_NAME,elementsE0.EFFECTIVE_START_DATE


