/* ****************************************************************************
* $Revision: 59117 $:
* $Author: nasrullah.dusenmahamad $:
* $Date: 2016-10-21 11:10:58 +0700 (Fri, 21 Oct 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Key%20Flexfields%20-%20Segment%20Labels.sql $:
* $Id: Manage Key Flexfields - Segment Labels.sql 59117 2016-10-21 04:10:58Z nasrullah.dusenmahamad $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=WIS_WORK_AREAS_VL
-- RSC_PREREQUISITE_OBJECTS=WIS_WORK_CENTERS_VL
-- RSC_PREREQUISITE_OBJECTS=WIS_WC_SUB_INVENTORIES

SELECT (SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = WisWorkCentersE0.ORGANIZATION_ID
	AND MFG_PLANT_FLAG = 'Y'
	) RES_ORGANIZATION
,WisWorkCentersE0.WORK_CENTER_NAME RES_NAME
,WisWorkCentersE0.WORK_CENTER_CODE RES_CODE
,WisWorkCentersE0.WORK_CENTER_DESCRIPTION RES_DESCRIPTION
,(SELECT WORK_AREA_NAME
	FROM WIS_WORK_AREAS_VL
	WHERE WORK_AREA_ID = WisWorkCentersE0.WORK_AREA_ID
	) RES_WORK_AREA
,WisWcSubInventorisE0.SUBINVENTORY_NAME RES_SUPPLY_SUBINVENTORY
,(SELECT FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'INV',KEY_FLEX_CODE => 'MTLL',STRUCTURE_NUMBER =>
	STRUCTURE_INSTANCE_NUMBER,COMBINATION_ID => INVENTORY_LOCATION_ID,DATA_SET_NUMBER =>SUBINVENTORY_ID)
	FROM INV_ITEM_LOCATIONS
	WHERE INVENTORY_LOCATION_ID = WisWcSubInventorisE0.LOCATOR_ID
	AND ORGANIZATION_ID = WisWcSubInventorisE0.ORGANIZATION_ID
	) RES_SUPPLY_LOCATOR
,TO_CHAR(WisWorkCentersE0.INACTIVE_DATE,'DD-Mon-YYYY') RES_INACTIVE_ON
,WisWorkCentersE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,WisWorkCentersE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,WisWorkCentersE0.CREATED_BY RSC_CREATED_BY
,WisWorkCentersE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,WisWorkCentersE0.ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM WIS_WORK_CENTERS_VL WisWorkCentersE0
,WIS_WC_SUB_INVENTORIES WisWcSubInventorisE0
WHERE WisWorkCentersE0.WORK_CENTER_ID = WisWcSubInventorisE0.WORK_CENTER_ID(+)
AND WisWorkCentersE0.ORGANIZATION_ID = WisWcSubInventorisE0.ORGANIZATION_ID(+)
ORDER BY RES_ORGANIZATION
,WisWorkCentersE0.WORK_CENTER_NAME