/* ****************************************************************************
 * $Revision: 68847 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2018-10-03 15:50:12 +0700 (Wed, 03 Oct 2018) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.20/trunk/core/reverse_sql/FINANCIALS/Manage%20Invoice%20Methods%20-%20Invoice%20Method.sql $:
 * $Id: Manage Invoice Methods - Invoice Method.sql 68847 2018-10-03 08:50:12Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=GMS_BUSINESS_UNITS
 
SELECT buE0.BU_NAME RES_NAME
,(SELECT NAME
    FROM XLE_ENTITY_PROFILES
    WHERE LEGAL_ENTITY_ID = buE0.LEGAL_ENTITY_ID 
    ) RES_LEGAL_ENTITY
,buE0.DEFAULT_CURRENCY_CODE RES_CURRENCY
,(SELECT NAME
    FROM OKC_CONTRACT_TYPES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CONTRACT_TYPE_ID = grantE0.CONTRACT_TYPE_ID 
    ) RES_CONTRACT_TYPE
,(SELECT INSTITUTION_NAME
    FROM GMS_INSTITUTIONS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND INSTITUTION_ID = grantE0.INSTITUTION_ID
    ) RES_INSTITUTION
,(SELECT IND_SCH_NAME
    FROM PJF_IND_RATE_SCH_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND IND_RATE_SCH_ID = grantE0.IND_RATE_SCH_ID 
    ) RES_BURDEN_SCHEDULE
,grantE0.DAY_TO_CLOSE RES_DAYS_TO_CLOSE
,(SELECT BILL_METHOD_NAME
    FROM PJB_BILLING_METHODS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND BILL_METHOD_ID = grantE0.INVOICE_METHOD_ID
    ) RES_INVOICE_METHOD
,(SELECT BILL_METHOD_NAME
    FROM PJB_BILLING_METHODS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND BILL_METHOD_ID = grantE0.REVENUE_METHOD_ID 
    ) RES_REVENUE_METHOD
,(SELECT BILLING_CYCLE_NAME
    FROM PJF_BILLING_CYCLES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND BILLING_CYCLE_ID = grantE0.BILLING_CYCLE_ID 
    ) RES_BILLING_CYCLE
,(SELECT NAME
    FROM PJB_INVOICE_FORMATS
    WHERE INVOICE_FORMAT_ID = grantE0.LABOR_FORMAT_ID 
    ) RES_LABOR_FORMAT
,(SELECT NAME
    FROM PJB_INVOICE_FORMATS
    WHERE INVOICE_FORMAT_ID = grantE0.NON_LABOR_FORMAT_ID 
    ) RES_NONLABOR_FORMAT
,(SELECT NAME
    FROM PJB_INVOICE_FORMATS
    WHERE INVOICE_FORMAT_ID = grantE0.EVENT_FORMAT_ID 
    ) RES_EVENT_FORMAT
	
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'PJB_EXTENSION_EXECUTION_LEVEL'
	AND LOOKUP_CODE = grantE0.INV_HDR_GROUPING_OPTIONS 
	) RES_INVOICE_GROUPING
,(SELECT NAME
	FROM RA_CUST_TRX_TYPES_ALL
	WHERE TYPE = 'INV'
	AND CUST_TRX_TYPE_SEQ_ID = NVL(grantE0.INV_TRX_TYPE_ID,37)
	) RES_TRANSACTION_TYPE

,'-999' RES_UNDERSPENDING_PERCENTAGE_F
,grantE0.UNDER_SPEND_PCT_TO RES_UNDERSPENDING_PERCENTAGE_T
,'51' RES_ON_TRACK_PERCENTAGE_FROM
,grantE0.ON_TRACK_PCT_TO RES_ON_TRACK_PERCENTAGE_TO
,'101' RES_OVERSPENDING_PERCENTAGE_FR
,'999' RES_OVERSPENDING_PERCENTAGE_TO
,grantE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,grantE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,grantE0.CREATED_BY RSC_CREATED_BY
,grantE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,grantE0.BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM GMS_BUSINESS_UNITS grantE0
,FUN_FIN_BUSINESS_UNITS_V buE0
WHERE grantE0.BU_ID = buE0.BU_ID
ORDER BY buE0.BU_NAME