/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Salary%20Basis%20-%20Salary%20Basis.sql $:
 * $Id: Manage Salary Basis - Salary Basis.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=CMP_SALARY_BASES_VL
 

SELECT cMPSBEO.SALARY_BASIS_NAME RES_NAME 
,cMPSBEO.CODE RES_CODE 
,DECODE(cMPSBEO.STATUS,'A','Active','I','Inactive') RES_STATUS
,(SELECT NAME FROM PER_LEGISLATIVE_DATA_GROUPS_TL WHERE LEGISLATIVE_DATA_GROUP_ID = cMPSBEO.LEGISLATIVE_DATA_GROUP_ID AND LANGUAGE = USERENV('LANG')) RES_LEGISLATIVE_DATA_GROUP
,(SELECT MEANING FROM FND_LOOKUP_VALUES  WHERE LOOKUP_CODE = cMPSBEO.SALARY_BASIS_TYPE AND LOOKUP_TYPE = 'ORA_CMP_SAL_BASIS_DET_METHOD' AND LANGUAGE  = USERENV('LANG')) RES_SALARY_BASIS_TYPE
,(SELECT MEANING FROM FND_LOOKUP_VALUES  WHERE LOOKUP_CODE = cMPSBEO.SALARY_BASIS_CODE AND LOOKUP_TYPE = 'CMP_SALARY_BASIS' AND LANGUAGE  = USERENV('LANG')) RES_FREQUENCY
,TO_CHAR(cMPSBEO.SALARY_ANNUALIZATION_FACTOR,'99999999D99') RES_ANNUALIZATION_FACTOR
,cMPSBEO.AMOUNT_DECIMAL_PRECISION RES_DECIMAL_PLACE_TO_DISPLAY
,(SELECT MEANING FROM FND_LOOKUP_VALUES  WHERE LOOKUP_CODE = cMPSBEO.AMOUNT_ROUNDING_CODE AND LOOKUP_TYPE = 'CMP_ROUNDING' AND LANGUAGE  = USERENV('LANG')) RES_SALARY_AMOUNT_ROUNDING_RUL
,(SELECT MEANING FROM FND_LOOKUP_VALUES  WHERE LOOKUP_CODE = cMPSBEO.ANNUAL_ROUNDING_CODE AND LOOKUP_TYPE = 'CMP_ROUNDING' AND LANGUAGE  = USERENV('LANG')) RES_ANNUALIZED_VALUES_ROUNDING
,cMPSBEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,cMPSBEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,cMPSBEO.CREATED_BY RSC_CREATED_BY
,cMPSBEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,cMPSBEO.BUSINESS_GROUP_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CMP_SALARY_BASES_VL  cMPSBEO
WHERE LANGUAGE = USERENV('LANG')
































