/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Catalog%20Category%20Hierarchy%20-%20Catalog%20Category%20Hierarchy.sql $:
 * $Id: Manage Catalog Category Hierarchy - Catalog Category Hierarchy.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

--RSC_PREREQUISITE_OBJECTS=POR_BROWSE_TREES

SELECT (SELECT DECODE(CATEGORY_NAME,'POR_CATEGORY_HIERARCHY_ROOT','Root Category',CATEGORY_NAME) FROM POR_BROWSE_CATEGORIES_VL WHERE CATEGORY_ID = cutOFF.PK1) RES_PARENT_CATEGORY_NAME_1 
,(SELECT DECODE(CATEGORY_NAME,'POR_CATEGORY_HIERARCHY_ROOT','Root Category',CATEGORY_NAME) FROM POR_BROWSE_CATEGORIES_VL WHERE CATEGORY_ID = cutOFF.PK2 ) RES_PARENT_CATEGORY_NAME_2
,(SELECT DECODE(CATEGORY_NAME,'POR_CATEGORY_HIERARCHY_ROOT','Root Category',CATEGORY_NAME) FROM POR_BROWSE_CATEGORIES_VL WHERE CATEGORY_ID = cutOFF.PK3 ) RES_PARENT_CATEGORY_NAME_3
,(SELECT DECODE(CATEGORY_NAME,'POR_CATEGORY_HIERARCHY_ROOT','Root Category',CATEGORY_NAME) FROM POR_BROWSE_CATEGORIES_VL WHERE CATEGORY_ID = cutOFF.PK4 ) RES_PARENT_CATEGORY_NAME_4
,(SELECT DECODE(CATEGORY_NAME,'POR_CATEGORY_HIERARCHY_ROOT','Root Category',CATEGORY_NAME) FROM POR_BROWSE_CATEGORIES_VL WHERE CATEGORY_ID = cutOFF.PK5 ) RES_PARENT_CATEGORY_NAME_5
,DECODE(BrowseCategoryEO.CATEGORY_NAME,'POR_CATEGORY_HIERARCHY_ROOT','Root Category',BrowseCategoryEO.CATEGORY_NAME) RES_CATEGORY_NAME
,BrowseCategoryEO.CATEGORY_DESCRIPTION RES_DESCRIPTION
,(SELECT DECODE(TOP_CATEGORY_FLAG,'Y','Yes','No') FROM POR_BROWSE_TREES WHERE CHILD_CATEGORY_ID = cutOFF.PARENT_CATEGORY_ID)  RES_FEATURED_CATEGORY
,BrowseCategoryEO.IMAGE_URL RES_IMAGE_URL
,BrowseCategoryEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,BrowseCategoryEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,BrowseCategoryEO.CREATED_BY RSC_CREATED_BY
,BrowseCategoryEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID


FROM (SELECT DISTINCT
SUBSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,1)+3,INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,2)-4)  PK1
,SUBSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,2)+3,INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,3) - INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,2)-3) PK2
,SUBSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,3)+3,INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,4) - INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,3)-3) PK3
,SUBSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,4)+3,INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,5) - INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,4)-3) PK4
,SUBSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,5)+3,INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,6) - INSTR(SYS_CONNECT_BY_PATH(BrowseCategoryTreeEO.PARENT_CATEGORY_ID,'###'),'###',1,5)-3) PK5
,LEVEL AS a
,BrowseCategoryTreeEO.PARENT_CATEGORY_ID
--,BrowseCategoryTreeEO.CHILD_CATEGORY_ID CHILD_CATEGORY_ID
FROM POR_BROWSE_TREES BrowseCategoryTreeEO
START WITH BrowseCategoryTreeEO.PARENT_CATEGORY_ID = '0'
CONNECT BY PRIOR BrowseCategoryTreeEO.CHILD_CATEGORY_ID = BrowseCategoryTreeEO.PARENT_CATEGORY_ID) cutOFF
,POR_BROWSE_CATEGORIES_VL BrowseCategoryEO
WHERE PARENT_CATEGORY_ID NOT IN (SELECT CATEGORY_ID FROM POR_BROWSE_CATEGORIES_VL WHERE CATEGORY_NAME ='POR_CATEGORY_HIERARCHY_ROOT')
AND cutoFF.PARENT_CATEGORY_ID = BrowseCategoryEO.CATEGORY_ID(+)
ORDER BY cutOFF.a,RES_CATEGORY_NAME