/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=WLF_PROPERTIES

WITH EVAL AS (SELECT MANDATORY_FLAG
	,TYPE_OF_USAGE
	,SOURCE_ID
	FROM WLF_LI_RELATIONS_F
	WHERE SOURCE_TYPE = 'ORA_HRQ_QSTNR'
	AND LEARNING_ITEM_ID = -1
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	)
,QUESTIONAIRE AS (SELECT QUESTIONNAIRE_ID
	,NAME
	,DESCRIPTION
	,ROW_NUMBER() OVER (PARTITION BY QUESTIONNAIRE_ID ORDER BY QSTNR_VERSION_NUM DESC) R1
	FROM HRQ_QUESTIONNAIRES_TL
	WHERE LANGUAGE = USERENV('LANG')
	)

SELECT NVL((SELECT 'Yes'
	FROM EVAL
	WHERE TYPE_OF_USAGE = 'ORA_BLENDED'
	),'No') RES_BLENDED_ENABLE_EVALUATION
,(SELECT NAME
	FROM QUESTIONAIRE
	WHERE R1 = 1
    AND QUESTIONNAIRE_ID = (SELECT SOURCE_ID
		FROM EVAL
		WHERE TYPE_OF_USAGE = 'ORA_BLENDED')
	) RES_BLENDED_EVALUATION
,(SELECT DESCRIPTION
	FROM QUESTIONAIRE
	WHERE R1 = 1
    AND QUESTIONNAIRE_ID = (SELECT SOURCE_ID
		FROM EVAL
		WHERE TYPE_OF_USAGE = 'ORA_BLENDED')
	) RES_BLENDED_DESCRIPTION
,(SELECT DECODE(MANDATORY_FLAG,'Y','Yes','No')
	FROM EVAL
	WHERE TYPE_OF_USAGE = 'ORA_BLENDED'
	) RES_BLENDED_REQUIRED_FOR_COMPL

,NVL((SELECT 'Yes'
	FROM EVAL
	WHERE TYPE_OF_USAGE = 'ORA_SP'
	),'No') RES_SELF_PACED_ENABLE_EVALUATI
,(SELECT NAME
	FROM QUESTIONAIRE
	WHERE R1 = 1
    AND QUESTIONNAIRE_ID = (SELECT SOURCE_ID
		FROM EVAL
		WHERE TYPE_OF_USAGE = 'ORA_SP')
	) RES_SELF_PACED_EVALUATION
,(SELECT DESCRIPTION
	FROM QUESTIONAIRE
	WHERE R1 = 1
    AND QUESTIONNAIRE_ID = (SELECT SOURCE_ID
		FROM EVAL
		WHERE TYPE_OF_USAGE = 'ORA_SP')
	) RES_SELF_PACED_DESCRIPTION
,(SELECT DECODE(MANDATORY_FLAG,'Y','Yes','No')
	FROM EVAL
	WHERE TYPE_OF_USAGE = 'ORA_SP'
	) RES_SELF_PACED_REQUIRED_FOR_CO

,NVL((SELECT 'Yes'
	FROM EVAL
	WHERE TYPE_OF_USAGE = 'ORA_ILT'
	),'No') RES_INSTRUCTOR_LED_ENABLE_EVAL
,(SELECT NAME
	FROM QUESTIONAIRE
	WHERE R1 = 1
    AND QUESTIONNAIRE_ID = (SELECT SOURCE_ID
		FROM EVAL
		WHERE TYPE_OF_USAGE = 'ORA_ILT')
	) RES_INSTRUCTOR_LED_EVALUATION
,(SELECT DESCRIPTION
	FROM QUESTIONAIRE
	WHERE R1 = 1
    AND QUESTIONNAIRE_ID = (SELECT SOURCE_ID
		FROM EVAL
		WHERE TYPE_OF_USAGE = 'ORA_ILT')
	) RES_INSTRUCTOR_LED_DESCRIPTION
,(SELECT DECODE(MANDATORY_FLAG,'Y','Yes','No')
	FROM EVAL
	WHERE TYPE_OF_USAGE = 'ORA_ILT'
	) RES_INSTRUCTOR_LED_REQUIRED_FO
,setupsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,setupsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,setupsE0.CREATED_BY  RSC_CREATED_BY
,setupsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM (SELECT LAST_UPDATED_BY
	,LAST_UPDATE_DATE
	,CREATED_BY
	,CREATION_DATE 
	,ROW_NUMBER() OVER (ORDER BY LAST_UPDATE_DATE DESC) R1
	FROM WLF_PROPERTIES 
	) setupsE0
WHERE R1 = 1