/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Questionnaires%20-%20Folders.sql $:
 * $Id: Manage Questionnaires - Folders.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT (SELECT NAME
    FROM HRQ_SUBSCRIBERS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND SUBSCRIBER_ID = foldersE0.SUBSCRIBER_ID
	) RES_SUBSCRIBER
,(SELECT NAME
    FROM HRQ_CATEGORIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CATEGORY_ID = foldersE0.PARENT_DISPLAY_CODE1
    ) RES_PARENT_FOLDER_1
,(SELECT NAME
    FROM HRQ_CATEGORIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CATEGORY_ID = foldersE0.PARENT_DISPLAY_CODE2
    ) RES_PARENT_FOLDER_2
,(SELECT NAME
    FROM HRQ_CATEGORIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CATEGORY_ID = foldersE0.PARENT_DISPLAY_CODE3
    ) RES_PARENT_FOLDER_3
,(SELECT NAME
    FROM HRQ_CATEGORIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CATEGORY_ID = foldersE0.PARENT_DISPLAY_CODE4
    ) RES_PARENT_FOLDER_4
,(SELECT NAME
    FROM HRQ_CATEGORIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CATEGORY_ID = foldersE0.PARENT_DISPLAY_CODE5
    ) RES_PARENT_FOLDER_5
,foldersE0.NAME RES_FOLDER
,foldersE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,foldersE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,foldersE0.CREATED_BY RSC_CREATED_BY
,foldersE0.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM 
(SELECT SUBSCRIBER_ID,NAME,LAST_UPDATED_BY,LAST_UPDATE_DATE,CREATED_BY,CREATION_DATE
,SUBSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,1)+3,INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,2)-4) PARENT_DISPLAY_CODE1
,SUBSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,2)+3,INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,3) - INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,2)-3) PARENT_DISPLAY_CODE2
,SUBSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,3)+3,INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,4) - INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,3)-3) PARENT_DISPLAY_CODE3
,SUBSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,4)+3,INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,5) - INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,4)-3) PARENT_DISPLAY_CODE4
,SUBSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,5)+3,INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,6) - INSTR(SYS_CONNECT_BY_PATH(foldersE0.CATEGORY_ID,'###'),'###',1,5)-3) PARENT_DISPLAY_CODE5
FROM HRQ_CATEGORIES_VL foldersE0
WHERE foldersE0.SUBSCRIBER_ID IN (SELECT SUBSCRIBER_ID FROM HRQ_SUBSCRIBERS_VL WHERE SUBSCRIBER_CODE IN ('PER_CHK','WLF_ASSESSMENTS','WLF_ENROLLMENTS','WFL','HRA','HWR','IRC','HWRTMS','HXLTLTC','HNS'))
AND CONTAIN_QUESTIONNAIRES = 'Y'
START WITH foldersE0.PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR foldersE0.CATEGORY_ID = foldersE0.PARENT_CATEGORY_ID) foldersE0


