/* ****************************************************************************
 * $Revision: 79494 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-10-12 15:14:24 +0700 (Wed, 12 Oct 2022) $:
 * $glrevaluationURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Revaluations%20-%20Revaluations.sql $:
 * $Id: Manage Revaluations - Revaluation Accounts.sql 79494 2022-10-12 08:14:24Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

WITH Acc AS
	(SELECT NAME
,REVAL_ACCOUNT_RANGE_ID
,MAX(
	CASE
		WHEN RES_XX = '1'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD1
,MAX(
	CASE
		WHEN RES_XX = '1'
		THEN RES_condition
	END) RES_FIELD1_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '1'
		THEN RES_VALUE_1
	END) RES_FIELD1_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '1'
		THEN RES_VALUE_2
	END) RES_FIELD1_VALUE2	
,MAX(
	CASE
		WHEN RES_XX = '2'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD2
	,MAX(
	CASE
		WHEN RES_XX = '2'
		THEN RES_CONDITION
	END) RES_FIELD2_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '2'
		THEN RES_VALUE_1
	END) RES_FIELD2_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '2'
		THEN RES_VALUE_2
	END) RES_FIELD2_VALUE2	
	,MAX(
	CASE
		WHEN RES_XX = '3'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD3
	,MAX(
	CASE
		WHEN RES_XX = '3'
		THEN RES_CONDITION
	END) RES_FIELD3_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '3'
		THEN RES_VALUE_1
	END) RES_FIELD3_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '3'
		THEN RES_VALUE_2
	END) RES_FIELD3_VALUE2	
	,MAX(
	CASE
		WHEN RES_XX = '4'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD4
	,MAX(
	CASE
		WHEN RES_XX = '4'
		THEN RES_CONDITION
	END) RES_FIELD4_CONDITION
	,MAX(
	CASE
		WHEN RES_XX = '4'
		THEN RES_VALUE_1
	END) RES_FIELD4_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '4'
		THEN RES_VALUE_2
	END) RES_FIELD4_VALUE2	
	,MAX(
	CASE
		WHEN RES_XX = '5'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD5
	,MAX(
	CASE
		WHEN RES_XX = '5'
		THEN RES_CONDITION
	END) RES_FIELD5_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '5'
		THEN RES_VALUE_1
	END) RES_FIELD5_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '5'
		THEN RES_VALUE_2
	END) RES_FIELD5_VALUE2	
,MAX(
	CASE
		WHEN RES_XX = '6'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD6
	,MAX(
	CASE
		WHEN RES_XX = '6'
		THEN RES_CONDITION
	END) RES_FIELD6_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '6'
		THEN RES_VALUE_1
	END) RES_FIELD6_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '6'
		THEN RES_VALUE_2
	END) RES_FIELD6_VALUE2	
	,MAX(
	CASE
		WHEN RES_XX = '7'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD7
	,MAX(
	CASE
		WHEN RES_XX = '7'
		THEN RES_CONDITION
	END) RES_FIELD7_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '7'
		THEN RES_VALUE_1
	END) RES_FIELD7_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '7'
		THEN RES_VALUE_2
	END) RES_FIELD7_VALUE2	
	,MAX(
	CASE
		WHEN RES_XX = '8'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD8
	,MAX(
	CASE
		WHEN RES_XX = '8'
		THEN RES_CONDITION
	END) RES_FIELD8_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '8'
		THEN RES_VALUE_1
	END) RES_FIELD8_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '8'
		THEN RES_VALUE_2
	END) RES_FIELD8_VALUE2	
	,MAX(
	CASE
		WHEN RES_XX = '9'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD9
	,MAX(
	CASE
		WHEN RES_XX = '9'
		THEN RES_CONDITION
	END) RES_FIELD9_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '9'
		THEN RES_VALUE_1
	END) RES_FIELD9_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '9'
		THEN RES_VALUE_2
	END) RES_FIELD9_VALUE2	
	,MAX(
	CASE
		WHEN RES_XX = '10'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD10
	,MAX(
	CASE
		WHEN RES_XX = '10'
		THEN RES_CONDITION
	END) RES_FIELD10_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '10'
		THEN RES_VALUE_1
	END) RES_FIELD10_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '10'
		THEN RES_VALUE_2
	END) RES_FIELD10_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '11'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD11
	,MAX(
	CASE
		WHEN RES_XX = '11'
		THEN RES_CONDITION
	END) RES_FIELD11_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '11'
		THEN RES_VALUE_1
	END) RES_FIELD11_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '11'
		THEN RES_VALUE_2
	END) RES_FIELD11_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '12'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD12
	,MAX(
	CASE
		WHEN RES_XX = '12'
		THEN RES_CONDITION
	END) RES_FIELD12_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '12'
		THEN RES_VALUE_1
	END) RES_FIELD12_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '12'
		THEN RES_VALUE_2
	END) RES_FIELD12_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '13'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD13
	,MAX(
	CASE
		WHEN RES_XX = '13'
		THEN RES_CONDITION
	END) RES_FIELD13_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '13'
		THEN RES_VALUE_1
	END) RES_FIELD13_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '13'
		THEN RES_VALUE_2
	END) RES_FIELD13_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '14'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD14
	,MAX(
	CASE
		WHEN RES_XX = '14'
		THEN RES_CONDITION
	END) RES_FIELD14_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '14'
		THEN RES_VALUE_1
	END) RES_FIELD14_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '14'
		THEN RES_VALUE_2
	END) RES_FIELD14_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '15'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD15
	,MAX(
	CASE
		WHEN RES_XX = '15'
		THEN RES_CONDITION
	END) RES_FIELD15_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '15'
		THEN RES_VALUE_1
	END) RES_FIELD15_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '15'
		THEN RES_VALUE_2
	END) RES_FIELD15_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '16'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD16
	,MAX(
	CASE
		WHEN RES_XX = '16'
		THEN RES_CONDITION
	END) RES_FIELD16_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '16'
		THEN RES_VALUE_1
	END) RES_FIELD16_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '16'
		THEN RES_VALUE_2
	END) RES_FIELD16_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '17'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD17
	,MAX(
	CASE
		WHEN RES_XX = '17'
		THEN RES_CONDITION
	END) RES_FIELD17_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '17'
		THEN RES_VALUE_1
	END) RES_FIELD17_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '17'
		THEN RES_VALUE_2
	END) RES_FIELD17_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '18'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD18
	,MAX(
	CASE
		WHEN RES_XX = '18'
		THEN RES_CONDITION
	END) RES_FIELD18_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '18'
		THEN RES_VALUE_1
	END) RES_FIELD18_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '18'
		THEN RES_VALUE_2
	END) RES_FIELD18_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '19'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD19
	,MAX(
	CASE
		WHEN RES_XX = '19'
		THEN RES_CONDITION
	END) RES_FIELD19_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '19'
		THEN RES_VALUE_1
	END) RES_FIELD19_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '19'
		THEN RES_VALUE_2
	END) RES_FIELD19_VALUE2		
	,MAX(
	CASE
		WHEN RES_XX = '20'
		THEN RES_ADD_FIELDS
	END) RES_ADD_FIELD20
	,MAX(
	CASE
		WHEN RES_XX = '20'
		THEN RES_CONDITION
	END) RES_FIELD20_CONDITION	
	,MAX(
	CASE
		WHEN RES_XX = '20'
		THEN RES_VALUE_1
	END) RES_FIELD20_VALUE1	
		,MAX(
	CASE
		WHEN RES_XX = '20'
		THEN RES_VALUE_2
	END) RES_FIELD20_VALUE2	
FROM
	(SELECT GLREVALUATION.NAME
	,REVAL_ACCOUNT_RANGE_ID
	,(SELECT COAMAPACCOUNTRULEEO.prompt
		FROM FND_KF_SEGMENTS_VL COAMAPACCOUNTRULEEO
		,FND_KF_STR_INSTANCES_VL COAMAPACCOUNTRULEEOI
		WHERE COAMAPACCOUNTRULEEO.STRUCTURE_ID   = COAMAPACCOUNTRULEEOI.STRUCTURE_ID
		AND COAMAPACCOUNTRULEEOI.STRUCTURE_INSTANCE_CODE =(EXTRACTVALUE(REVALRANGESEO.FLEX_FILTER,
			'/FndFilter/KeyFlexFilter/structureInstanceCode'))
		AND COAMAPACCOUNTRULEEO.COLUMN_NAME = (EXTRACTVALUE(value(X),'/filterCriteriaItem/columnName'))
		AND COAMAPACCOUNTRULEEOI.KEY_FLEXFIELD_CODE = EXTRACTVALUE(REVALRANGESEO.FLEX_FILTER,'/FndFilter/KeyFlexFilter/keyFlexfieldCode')
		) RES_ADD_FIELDS
	,DECODE(EXTRACTVALUE(value(X),'/filterCriteriaItem/operator'),'EQUALTO','Equals',(SELECT MEANING
		FROM GL_LOOKUPS
		WHERE LOOKUP_TYPE = 'FILTER_OPERATORS'
		AND LOOKUP_CODE   = EXTRACTVALUE(value(X),'/filterCriteriaItem/operator')
		)) RES_CONDITION
		
	,row_number() over(PARTITION by REVAL_ACCOUNT_RANGE_ID order by NULL) RES_XX
	,EXTRACTVALUE(value(X),'/filterCriteriaItem/value[1]') RES_VALUE_1
	,EXTRACTVALUE(value(X),'/filterCriteriaItem/value[2]') RES_VALUE_2
	,EXTRACTVALUE(value(X),'/filterCriteriaItem/conjunction') CONJUNCTION
	FROM GL_REVALUATIONS GLREVALUATION
	,GL_REVAL_ACCOUNT_RANGES REVALRANGESEO
	,TABLE(XMLSEQUENCE(extract(REVALRANGESEO.FLEX_FILTER,'/FndFilter/KeyFlexFilter/filterCriteriaRow/filterCriteriaItem'))
		) X
	WHERE GLREVALUATION.REVALUATION_ID = REVALRANGESEO.REVALUATION_ID
	)
GROUP BY NAME
,REVAL_ACCOUNT_RANGE_ID
	)
,con AS
	(SELECT REVAL_ACCOUNT_RANGE_ID
	,SUBSTR(MAX(
		CASE
			WHEN RES_XX = '1'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '2'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '3'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '4'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '5'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '6'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '7'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '8'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '9'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '10'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '11'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '12'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '13'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '14'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '15'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '16'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '17'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '18'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '19'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '20'
			THEN CONDITIONS
		END),5) Name
	FROM
		(SELECT GLREVALUATION.NAME
		,REVALRANGESEO.REVAL_ACCOUNT_RANGE_ID
		,ROW_NUMBER() OVER(PARTITION BY REVALRANGESEO.REVAL_ACCOUNT_RANGE_ID ORDER BY NULL) RES_XX
		,EXTRACTVALUE(VALUE(X),'/filterCriteriaItem/conjunction') ||' '||
			(SELECT COAMAPACCOUNTRULEEO.prompt
			FROM FND_KF_SEGMENTS_VL COAMAPACCOUNTRULEEO
			,FND_KF_STR_INSTANCES_VL COAMAPACCOUNTRULEEOI
			WHERE COAMAPACCOUNTRULEEO.STRUCTURE_ID           = COAMAPACCOUNTRULEEOI.STRUCTURE_ID
			AND COAMAPACCOUNTRULEEOI.STRUCTURE_INSTANCE_CODE =(EXTRACTVALUE(REVALRANGESEO.FLEX_FILTER,
				'/FndFilter/KeyFlexFilter/structureInstanceCode'))
			AND COAMAPACCOUNTRULEEO.COLUMN_NAME = (EXTRACTVALUE(value(X),'/filterCriteriaItem/columnName'))
			AND COAMAPACCOUNTRULEEOI.KEY_FLEXFIELD_CODE = EXTRACTVALUE(REVALRANGESEO.FLEX_FILTER,'/FndFilter/KeyFlexFilter/keyFlexfieldCode')
		) ||' '||
			(SELECT MEANING
			FROM GL_LOOKUPS
			WHERE LOOKUP_TYPE = 'FILTER_OPERATORS'
			AND LOOKUP_CODE   = EXTRACTVALUE(value(X),'/filterCriteriaItem/operator')
			) ||' '||EXTRACTVALUE(VALUE(X),'/filterCriteriaItem/value[1]') ||' '||DECODE(EXTRACTVALUE(value(X),
			'/filterCriteriaItem/operator'),'BETWEEN','and ',NULL) ||EXTRACTVALUE(VALUE(X),'/filterCriteriaItem/value[2]')
			CONDITIONS
		FROM GL_REVALUATIONS GLREVALUATION
		,GL_REVAL_ACCOUNT_RANGES REVALRANGESEO
		,TABLE(XMLSEQUENCE(extract(REVALRANGESEO.FLEX_FILTER,'/FndFilter/KeyFlexFilter/filterCriteriaRow/filterCriteriaItem')
			)) X
		WHERE GLREVALUATION.REVALUATION_ID = REVALRANGESEO.REVALUATION_ID
			--AND GLREVALUATION.REVALUATION_ID   = 300000001629390
			--AND REVALRANGESEO.REVAL_ACCOUNT_RANGE_ID = 300000001629395
		)
	GROUP BY REVAL_ACCOUNT_RANGE_ID
	)
SELECT ACC.NAME RES_NAME
, CON.Name RES_FILTER_CONDITIONS
,row_number() over (partition by REVALRANGESEO.REVALUATION_ID order by con.Name) RES_SEQUENCE
,RES_ADD_FIELD1
,RES_FIELD1_CONDITION
,RES_FIELD1_VALUE1
,RES_FIELD1_VALUE2
,RES_ADD_FIELD2
,RES_FIELD2_CONDITION
,RES_FIELD2_VALUE1
,RES_FIELD2_VALUE2
,RES_ADD_FIELD3
,RES_FIELD3_CONDITION
,RES_FIELD3_VALUE1
,RES_FIELD3_VALUE2
,RES_ADD_FIELD4
,RES_FIELD4_CONDITION
,RES_FIELD4_VALUE1
,RES_FIELD4_VALUE2
,RES_ADD_FIELD5
,RES_FIELD5_CONDITION
,RES_FIELD5_VALUE1
,RES_FIELD5_VALUE2
,RES_ADD_FIELD6
,RES_FIELD6_CONDITION
,RES_FIELD6_VALUE1
,RES_FIELD6_VALUE2
,RES_ADD_FIELD7
,RES_FIELD7_CONDITION
,RES_FIELD7_VALUE1
,RES_FIELD7_VALUE2
,RES_ADD_FIELD8
,RES_FIELD8_CONDITION
,RES_FIELD8_VALUE1
,RES_FIELD8_VALUE2
,RES_ADD_FIELD9
,RES_FIELD9_CONDITION
,RES_FIELD9_VALUE1
,RES_FIELD9_VALUE2
,RES_ADD_FIELD10
,RES_FIELD10_CONDITION
,RES_FIELD10_VALUE1
,RES_FIELD10_VALUE2
,RES_ADD_FIELD11
,RES_FIELD11_CONDITION
,RES_FIELD11_VALUE1
,RES_FIELD11_VALUE2
,RES_ADD_FIELD12
,RES_FIELD12_CONDITION
,RES_FIELD12_VALUE1
,RES_FIELD12_VALUE2
,RES_ADD_FIELD13
,RES_FIELD13_CONDITION
,RES_FIELD13_VALUE1
,RES_FIELD13_VALUE2
,RES_ADD_FIELD14
,RES_FIELD14_CONDITION
,RES_FIELD14_VALUE1
,RES_FIELD14_VALUE2
,RES_ADD_FIELD15
,RES_FIELD15_CONDITION
,RES_FIELD15_VALUE1
,RES_FIELD15_VALUE2
,RES_ADD_FIELD16
,RES_FIELD16_CONDITION
,RES_FIELD16_VALUE1
,RES_FIELD16_VALUE2
,RES_ADD_FIELD17
,RES_FIELD17_CONDITION
,RES_FIELD17_VALUE1
,RES_FIELD17_VALUE2
,RES_ADD_FIELD18
,RES_FIELD18_CONDITION
,RES_FIELD18_VALUE1
,RES_FIELD18_VALUE2
,RES_ADD_FIELD19
,RES_FIELD19_CONDITION
,RES_FIELD19_VALUE1
,RES_FIELD19_VALUE2
,RES_ADD_FIELD20
,RES_FIELD20_CONDITION
,RES_FIELD20_VALUE1
,RES_FIELD20_VALUE2
,REVALRANGESEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,REVALRANGESEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,REVALRANGESEO.CREATED_BY RSC_CREATED_BY
,REVALRANGESEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,(SELECT CHART_OF_ACCOUNTS_ID
	FROM GL_REVALUATIONS
	WHERE REVALUATION_ID = REVALRANGESEO.REVALUATION_ID
	) RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM ACC
,CON 
,GL_REVAL_ACCOUNT_RANGES REVALRANGESEO
WHERE ACC.REVAL_ACCOUNT_RANGE_ID = CON.REVAL_ACCOUNT_RANGE_ID
and CON.REVAL_ACCOUNT_RANGE_ID = REVALRANGESEO.REVAL_ACCOUNT_RANGE_ID
order by ACC.Name,con.name,RES_SEQUENCE