/* ****************************************************************************
 * $Revision: 53609 $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2016-07-13 10:53:25 +0700  $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Accounting%20Calendars%20-%20Additional%20Year.sql $:
 * $Id: Manage Bank Accounts - Account Contact - DFF.sql 53609 2016-07-13 03:53:25Z  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=260##RES##CE_BANK_ACCOUNTS
-- DFF_ATTRIBUTES=ATTRIBUTE,GLOBAL_ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,GLOBAL_ATTRIBUTE_NUMBER,GLOBAL_ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.


Select
BankBranchSimplePEO.BANK_NAME               		RES_BANK,
BankBranchSimplePEO.COUNTRY_NAME            		RES_COUNTRY,
BankBranchSimplePEO.BANK_BRANCH_NAME        		RES_BANK_BRANCH,
 CeBankAccounts.BANK_ACCOUNT_NAME             		RES_ACCOUNT_NAME,
CeBankAccounts.BANK_ACCOUNT_NUM                   RES_ACCOUNT_NUMBER,

CeBankAccounts.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,CeBankAccounts.ATTRIBUTE1 
,CeBankAccounts.ATTRIBUTE2
,CeBankAccounts.ATTRIBUTE3
,CeBankAccounts.ATTRIBUTE4
,CeBankAccounts.ATTRIBUTE5
,CeBankAccounts.ATTRIBUTE6
,CeBankAccounts.ATTRIBUTE7
,CeBankAccounts.ATTRIBUTE8
,CeBankAccounts.ATTRIBUTE9
,CeBankAccounts.ATTRIBUTE10
,CeBankAccounts.ATTRIBUTE11
,CeBankAccounts.ATTRIBUTE12
,CeBankAccounts.ATTRIBUTE13
,CeBankAccounts.ATTRIBUTE14
,CeBankAccounts.ATTRIBUTE15
,CeBankAccounts.GLOBAL_ATTRIBUTE1
,CeBankAccounts.GLOBAL_ATTRIBUTE2
,CeBankAccounts.GLOBAL_ATTRIBUTE3
,CeBankAccounts.GLOBAL_ATTRIBUTE4
,CeBankAccounts.GLOBAL_ATTRIBUTE5
,CeBankAccounts.GLOBAL_ATTRIBUTE6
,CeBankAccounts.GLOBAL_ATTRIBUTE7
,CeBankAccounts.GLOBAL_ATTRIBUTE8
,CeBankAccounts.GLOBAL_ATTRIBUTE9
,CeBankAccounts.GLOBAL_ATTRIBUTE10
,CeBankAccounts.GLOBAL_ATTRIBUTE11
,CeBankAccounts.GLOBAL_ATTRIBUTE12
,CeBankAccounts.GLOBAL_ATTRIBUTE13
,CeBankAccounts.GLOBAL_ATTRIBUTE14
,CeBankAccounts.GLOBAL_ATTRIBUTE15
,CeBankAccounts.GLOBAL_ATTRIBUTE16
,CeBankAccounts.GLOBAL_ATTRIBUTE17
,CeBankAccounts.GLOBAL_ATTRIBUTE18
,CeBankAccounts.GLOBAL_ATTRIBUTE19
,CeBankAccounts.GLOBAL_ATTRIBUTE20
,CeBankAccounts.ATTRIBUTE_NUMBER1
,CeBankAccounts.ATTRIBUTE_NUMBER2
,CeBankAccounts.ATTRIBUTE_NUMBER3
,CeBankAccounts.ATTRIBUTE_NUMBER4
,CeBankAccounts.ATTRIBUTE_NUMBER5
,to_char(CeBankAccounts.ATTRIBUTE_DATE1,'DD-Mon-YYYY')  ATTRIBUTE_DATE1
,to_char(CeBankAccounts.ATTRIBUTE_DATE2,'DD-Mon-YYYY')  ATTRIBUTE_DATE2
,to_char(CeBankAccounts.ATTRIBUTE_DATE3,'DD-Mon-YYYY')  ATTRIBUTE_DATE3
,to_char(CeBankAccounts.ATTRIBUTE_DATE4,'DD-Mon-YYYY')  ATTRIBUTE_DATE4
,to_char(CeBankAccounts.ATTRIBUTE_DATE5,'DD-Mon-YYYY')  ATTRIBUTE_DATE5
,CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER1
,CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER2
,CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER3
,CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER4
,CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER5
,to_char(CeBankAccounts.GLOBAL_ATTRIBUTE_DATE1,'DD-Mon-YYYY')  GLOBAL_ATTRIBUTE_DATE1
,to_char(CeBankAccounts.GLOBAL_ATTRIBUTE_DATE2,'DD-Mon-YYYY')  GLOBAL_ATTRIBUTE_DATE2
,to_char(CeBankAccounts.GLOBAL_ATTRIBUTE_DATE3,'DD-Mon-YYYY')  GLOBAL_ATTRIBUTE_DATE3
,to_char(CeBankAccounts.GLOBAL_ATTRIBUTE_DATE4,'DD-Mon-YYYY')  GLOBAL_ATTRIBUTE_DATE4
,to_char(CeBankAccounts.GLOBAL_ATTRIBUTE_DATE5,'DD-Mon-YYYY')  GLOBAL_ATTRIBUTE_DATE5


,CeBankAccounts.LAST_UPDATED_BY  								RSC_LAST_UPDATED_BY
,CeBankAccounts.LAST_UPDATE_DATE  								RSC_LAST_UPDATE_DATE
,CeBankAccounts.CREATED_BY  										RSC_CREATED_BY
,CeBankAccounts.CREATION_DATE  									RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,CeBankAccounts.ACCOUNT_OWNER_ORG_ID RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

 
FROM CE_BANK_ACCOUNTS CeBankAccounts,
  XLE_ENTITY_PROFILES XleEntityProfiles,
  CE_BANK_BRANCHES_SIMPLE_V BankBranchSimplePEO,
  CE_RECON_RULESETS BankStatementReconRuleSetPEO
WHERE ((CeBankAccounts.ACCOUNT_OWNER_ORG_ID = XleEntityProfiles.LEGAL_ENTITY_ID)
AND (CeBankAccounts.BANK_BRANCH_ID          = BankBranchSimplePEO.BRANCH_PARTY_ID)
AND (CeBankAccounts.RECON_RULESET_ID        = BankStatementReconRuleSetPEO.RECON_RULESET_ID (+))
AND NOT EXISTS
  (SELECT xtr.bank_account_id
  FROM ce_bank_accounts xtr
  WHERE NVL(AP_USE_ALLOWED_FLAG, 'N') = 'N'
  AND NVL(AR_USE_ALLOWED_FLAG, 'N')   = 'N'
  AND NVL(PAY_USE_ALLOWED_FLAG, 'N')  = 'N'
  AND NVL(XTR_USE_ALLOWED_FLAG, 'N')  = 'Y'
  AND xtr.bank_account_id             = CeBankAccounts.bank_account_id
  ))

  AND (  CeBankAccounts.ATTRIBUTE_CATEGORY  IS NOT NULL OR 
  CeBankAccounts.ATTRIBUTE1  IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE2 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE3 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE4 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE5 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE6 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE7 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE8 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE9 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE10 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE11 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE12 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE13 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE14 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE15 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE1 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE2 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE3 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE4 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE5 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE6 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE7 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE8 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE9 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE10 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE11 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE12 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE13 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE14 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE15 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE16 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE17 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE18 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE19 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE20 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_DATE1 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_DATE2 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_DATE3 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_DATE4 IS NOT NULL OR 
CeBankAccounts.ATTRIBUTE_DATE5 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER1 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER2 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER3 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER4 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_NUMBER5 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_DATE1 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_DATE2 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_DATE3 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_DATE4 IS NOT NULL OR 
CeBankAccounts.GLOBAL_ATTRIBUTE_DATE5 IS NOT NULL 
)

ORDER BY DECODE(cebankaccounts.end_date, NULL, 'Y', 'N') DESC,
  CeBankAccounts.BANK_ACCOUNT_NAME


  
  
  
  
  