/* ****************************************************************************
 * $Revision: 61060 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-17 09:40:24 +0700 (Fri, 17 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Application%20Tax%20Options%20-%20Application%20Tax%20Options.sql $:
 * $Id: Manage Application Tax Options - Application Tax Options.sql 61060 2017-02-17 02:40:24Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT ZFPOMV.PARTY_NAME RES_CONFIGURATION_OWNER
,ZxRulesVl.TAX_RULE_CODE RES_RULE_CODE
,ZxRulesVl.TAX_RULE_NAME RES_RULE_NAME
,(SELECT REPORTING_TYPE_NAME
  FROM ZX_REPORTING_TYPES_VL
  WHERE REPORTING_TYPE_CODE = ZxRulesVl.REPORTING_TYPE_CODE
  ) RES_TAX_REPORTING_TYPE
,ZxRulesVl.TAX_REGIME_CODE RES_TAX_REGIME_CODE
,(SELECT MEANING 
  FROM FND_LOOKUP_VALUES_VL
  WHERE LOOKUP_TYPE = 'ZX_RULE_PERIODICITY'
  AND LOOKUP_CODE = ZxRulesVl.PERIODICITY_CODE
  ) RES_REPORT_PERIODICITY
,TO_CHAR(ZxRulesVl.EFFECTIVE_FROM,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(ZxRulesVl.EFFECTIVE_TO,'DD-Mon-YYYY') RES_END_DATE
,ZxRulesVl.TAX RES_TAX
,ZxRulesVl.TAX_LAW_REF_CODE RES_TAX_LAW_REFERENCE
,ZxRulesVl.TAX_LAW_REF_DESC RES_DESCRIPTION
,ZxRulesVl.TAX_STATUS_CODE RES_TAX_STATUS_CODE
,(SELECT eventClassE0.NAME
  FROM ZX_EVNT_CLS_MAPPINGS mappingE0
  ,XLA_EVENT_CLASSES_VL eventClassE0
  WHERE mappingE0.EVENT_CLASS_CODE = eventClassE0.EVENT_CLASS_CODE
  AND mappingE0.APPLICATION_ID = eventClassE0.APPLICATION_ID
  AND mappingE0.ENTITY_CODE = eventClassE0.ENTITY_CODE
  AND mappingE0.ENTITY_CODE = eventClassE0.ENTITY_CODE
  AND mappingE0.EVENT_CLASS_MAPPING_ID = ZxRulesVl.EVENT_CLASS_MAPPING_ID
  ) RES_EVENT_CLASS
,(CASE
  WHEN ZxRulesVl.GEOGRAPHY_TYPE IS NOT NULL THEN 'Yes'
  ELSE 'No'
  END) RES_SET_AS_GEOGRAPHY_SPECIFIC_
,(SELECT MEANING 
  FROM FND_LOOKUP_VALUES_VL
  WHERE LOOKUP_TYPE = 'ZX_PLACE_OF_SUPPLY_TYPE'
  AND LOOKUP_CODE = ZxRulesVl.DETERMINING_FACTOR_CQ_CODE
  ) RES_LOCATION_TYPE
,'' RES_PARENT_GEOGRAPHY_TYPE
,'' RES_PARENT_GEOGRAPHY_NAME
,(SELECT GEOGRAPHY_TYPE_NAME 
  FROM HZ_GEOGRAPHY_TYPES_VL
  WHERE GEOGRAPHY_TYPE = ZxRulesVl.GEOGRAPHY_TYPE
  ) RES_GEOGRAPHY_TYPE
,(SELECT GEOGRAPHY_NAME
  FROM HZ_GEOGRAPHIES
  WHERE GEOGRAPHY_ID = ZxRulesVl.GEOGRAPHY_ID 
  ) RES_GEOGRAPHY_NAME
,detFactorsE0.DET_FACTOR_TEMPL_CODE RES_TAX_DETERMINING_FACTOR_SET
,detFactorsE0.DET_FACTOR_TEMPL_NAME RES_NAME
,(SELECT NAME 
  FROM GL_LEDGERS
  WHERE LEDGER_ID= detFactorsE0.LEDGER_ID
  ) RES_LEDGER
,ZxRulesVl.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ZxRulesVl.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ZxRulesVl.CREATED_BY RSC_CREATED_BY
,ZxRulesVl.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(CASE
	WHEN ZFPOMV.PARTY_TYPE_CODE = 'OU' THEN
		ZFPOMV.BU_ID
	END) RSC_BUSINESS_UNIT_ID
,(CASE
	WHEN ZFPOMV.PARTY_TYPE_CODE = 'FIRST_PARTY' THEN
		ZFPOMV.LEGAL_ENTITY_ID
	END) RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,Null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM ZX_RULES_VL ZxRulesVl
,ZX_FIRST_PARTY_ORGS_MOAC_V ZFPOMV
,ZX_REGIMES_VL ZxRegimesVl
,ZX_DET_FACTOR_TEMPL_VL detFactorsE0
WHERE ZxRegimesVl.TAX_REGIME_CODE         = ZxRulesVl.TAX_REGIME_CODE
AND ZxRulesVl.CONTENT_OWNER_ID            = ZFPOMV.PARTY_TAX_PROFILE_ID
AND NVL(ZxRegimesVl.REGIME_TYPE_FLAG,'I') = 'I'
AND ZxRulesVl.SERVICE_TYPE_CODE = 'DET_TAX_BOX'
AND ZxRulesVl.DET_FACTOR_TEMPL_CODE = detFactorsE0.DET_FACTOR_TEMPL_CODE
ORDER BY ZxRulesVl.TAX_RULE_CODE