/* ****************************************************************************
 * $Revision: 78696 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-06-08 10:47:12 +0700 (Wed, 08 Jun 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Calculation%20Value%20Definitions%20-%20Calculation%20Values.sql $:
 * $Id: Manage Calculation Value Definitions - Calculation Values.sql 78696 2022-06-08 03:47:12Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT payVALUEDEFIEO.NAME RES_NAME
,legislativesE0.NAME RES_LEGISLATIVE_DATA_GROUP
,TO_CHAR(payVALUEDEFIEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,calTYPEO.NAME RES_CALCULATION_TYPE
,payRANGEITEMEO.LOW_VALUE RES_FROM_VALUE
,payRANGEITEMEO.HIGH_VALUE RES_TO_VALUE
,(SELECT NAME 
	FROM PAY_CALC_TYPES_VL 
	WHERE CALC_TYPE_ID = payRANGEITEMEO.CALC_TYPE_ID
	) RES_CALCULATION_TYPE_OVERRIDE
,(CASE 
	WHEN calTYPEO.NAME IN ('Flat Amount') THEN 
		payRANGEITEMEO.VALUE1 
	WHEN calTYPEO.NAME IN ('Flat Amount Times Multiplier') AND (SELECT NAME FROM PAY_CALC_TYPES_VL WHERE CALC_TYPE_ID = payRANGEITEMEO.CALC_TYPE_ID) IN ('Flat Amount') THEN 
		payRANGEITEMEO.VALUE1 
	ELSE 
		NULL 
	END) RES_FLAT_AMOUNT
,(CASE 
	WHEN calTYPEO.NAME IN ('Flat Rate','Flat Rate by Derived Base','Incremental Rate') THEN 
		payRANGEITEMEO.VALUE1 
	WHEN calTYPEO.NAME IN ('Flat Amount Times Multiplier') AND  (SELECT NAME FROM PAY_CALC_TYPES_VL WHERE CALC_TYPE_ID = payRANGEITEMEO.CALC_TYPE_ID) IN ('Flat Rate') THEN 
		payRANGEITEMEO.VALUE1 
	ELSE 
		NULL 
	END) RES_RATE
,(CASE 
	WHEN calTYPEO.NAME IN ('Rate Definition') THEN 
		(SELECT NAME 
			FROM PAY_RATE_DEFINITIONS_F_TL 
			WHERE RATE_DEFINITION_ID = payRANGEITEMEO.VALUE1 
			AND LANGUAGE = USERENV('LANG') 
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY')))						
	ELSE 
		NULL 
	END) RES_RATE_DEFINITION
,(CASE 
	WHEN calTYPEO.NAME IN ('Flat Rate by Derived Base','Incremental Rate','Incremental Calculation') THEN 
		(SELECT NAME 
			FROM PAY_VALUE_DEFINITIONS_TL  
			WHERE VALUE_DEFN_ID = payRANGEITEMEO.VALUE1 
			AND LANGUAGE = USERENV('LANG'))
	ELSE 
		NULL 
	END) RES_CALCULATION_VALUE_DEFINITI
,(CASE 
	WHEN calTYPEO.NAME IN ('Text','Identifier') THEN 
		payRANGEITEMEO.VALUE1 
	WHEN calTYPEO.NAME IN ('Date') AND payRANGEITEMEO.VALUE1 NOT IN ('-999999999','01/01/0001','31-12-4712','01-01-0001') THEN 
		TO_CHAR(TO_DATE(payRANGEITEMEO.VALUE1,'YYYY-MM-DD'),'DD-Mon-YYYY')
	ELSE 
		NULL END 
	) RES_VALUE

,(CASE 
	WHEN (SELECT NAME FROM PAY_CALC_TYPES_VL WHERE CALC_TYPE_ID = payRANGEITEMEO.CALC_TYPE_ID) IN ('Standard Formula 1','Standard Formula 2') THEN 
		payRANGEITEMEO.VALUE1
	ELSE 
		NULL 
	END) RES_PARAMETER_A
,(CASE 
	WHEN (SELECT NAME FROM PAY_CALC_TYPES_VL WHERE CALC_TYPE_ID = payRANGEITEMEO.CALC_TYPE_ID) IN ('Standard Formula 1','Standard Formula 2') THEN 
		payRANGEITEMEO.VALUE2
	ELSE 
		NULL 
	END) RES_PARAMETER_B
,(CASE 
	WHEN (SELECT NAME FROM PAY_CALC_TYPES_VL WHERE CALC_TYPE_ID = payRANGEITEMEO.CALC_TYPE_ID) IN ('Standard Formula 2') THEN 
		payRANGEITEMEO.VALUE3
	ELSE 
		NULL 
	END) RES_PARAMETER_C
,(CASE 
	WHEN (SELECT NAME FROM PAY_CALC_TYPES_VL WHERE CALC_TYPE_ID = payRANGEITEMEO.CALC_TYPE_ID) IN ('Date') THEN 
		TO_CHAR(payRANGEITEMEO.VALUE1,'DD-MM-YYYY')
	ELSE NULL END) RES_DATE
,TO_CHAR(payRANGEITEMEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_CALCULATION_VALUES_EFFECTI
,DECODE(TO_CHAR(payVALUEDEFIEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(payVALUEDEFIEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,payRANGEITEMEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payRANGEITEMEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payRANGEITEMEO.CREATED_BY RSC_CREATED_BY
,payRANGEITEMEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legislativesE0.LEGISLATION_CODE RSC_COUNTRY_ID

FROM PAY_VALUE_DEFINITIONS_VL  payVALUEDEFIEO
,PER_LEGISLATIVE_DATA_GROUPS_VL legislativesE0
,PAY_RANGE_ITEMS_F payRANGEITEMEO
,(SELECT CALC_TYPE_ID
	,NAME 
	FROM PAY_CALC_TYPES_VL
	) calTYPEO
WHERE payVALUEDEFIEO.PARENT_VALUE_DEFN_ID IS NULL
AND payVALUEDEFIEO.LEGISLATIVE_DATA_GROUP_ID = legislativesE0.LEGISLATIVE_DATA_GROUP_ID
AND payVALUEDEFIEO.VALUE_DEFN_ID = payRANGEITEMEO.VALUE_DEFN_ID
AND payVALUEDEFIEO.CALC_TYPE_ID = calTYPEO.CALC_TYPE_ID(+)
ORDER BY payVALUEDEFIEO.NAME
,legislativesE0.NAME
,payVALUEDEFIEO.EFFECTIVE_START_DATE
,payRANGEITEMEO.LOW_VALUE