/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Job%20-%20Profiles.sql $:
 * $Id: Manage Job - Profiles.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

select JOBDEO.name RES_NAME
,JOBDEO.JOB_CODE RES_CODE
,TO_CHAR(JOBDEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY')  RES_EFFECTIVE_START_DATE
,TO_CHAR(JOBDEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_END_DATE
,PROFILEEO.PROFILE_CODE RES_PROFILE_CODE
,PROFILEEO.DESCRIPTION RES_PROFILE_NAME
,PROFILEEO.summary RES_PROFILE_DESCRIPTION
,TO_CHAR(PROFILERELATIONORGEO.OBJECT_EFF_START_DATE,'DD-Mon-YYYY') RES_PROFILE_EFFECTIVE_START_DA
,TO_CHAR(PROFILERELATIONORGEO.OBJECT_EFF_END_DATE,'DD-Mon-YYYY') RES_PROFILE_EFFECTIVE_END_DATE
,ProfileRelationOrgEO.LAST_UPDATED_BY as RSC_LAST_UPDATED_BY
,ProfileRelationOrgEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
,ProfileRelationOrgEO.CREATED_BY  RSC_CREATED_BY
,ProfileRelationOrgEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
    
from PER_JOBS_F_VL JOBDEO 
,HRT_PROFILE_RELATIONS ProfileRelationOrgEO
,HRT_RELATION_CONFIG_VL RELATIONCONFIGPEO
,HRT_PROFILES_VL PROFILEEO
where  JOBDEO.JOB_ID  = ProfileRelationOrgEO.OBJECT_ID
and ProfileRelationOrgEO.PROFILE_ID = PROFILEEO.PROFILE_ID
and PROFILERELATIONORGEO.RELATION_ID          = RELATIONCONFIGPEO.RELATION_ID (+)
and UPPER(RelationConfigPEO.RELATION_TYPE_CODE) = UPPER('PIDO')
and UPPER(RELATIONCONFIGPEO.RELATION_CODE) = UPPER('JOB')
order by JOBDEO.name,JOBDEO.JOB_CODE,JOBDEO.EFFECTIVE_START_DATE,PROFILEEO.PROFILE_CODE,PROFILERELATIONORGEO.OBJECT_EFF_START_DATE