/* ****************************************************************************
 * $Revision: 53782 $:
 * $Author: nasrullah.dusenmahamad $:
 * $Date: 2016-03-31 18:00:16 +0700 (Tue, 22 Mar 2016) $:
 * $HeadURL: $:
 * $Id: Manage Enterprise HCM Information - Attachments.sql 53782 2016-03-22 11:00:16Z nasrullah.dusenmahamad $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EXM_MISC_POLICIES

SELECT 'Miscellaneous' RES_EXPENSE_CATEGORY
,ExmMiscPolicies.POLICY_NAME RES_POLICY_NAME
,ExmMiscPolicies.DESCRIPTION RES_DESCRIPTION
,DECODE(ExmMiscPolicies.ENABLED_ELIGIBILITY_FLAG,'Y','Yes','No') RES_MINIMUM_NUMBER_OF_DAYS_FOR
,ExmMiscPolicies.ELIGIBILITY_DAYS RES_DAYS
,(CASE
	WHEN ExmMiscPolicies.ENABLED_ELIGIBILITY_FLAG = 'Y' THEN
		DECODE(ExmMiscPolicies.DAYS_BASED_ITEM_PARENT_FLAG,'Y','Yes','No') 
	END) RES_BASED_ON_NUMBER_OF_DAYS_IN
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_RATE_TYPE'
	AND LOOKUP_CODE = ExmMiscPolicies.RATE_TYPE_CODE
	) RES_RATE_TYPE
,DECODE(ExmMiscPolicies.SINGLE_INSTANCE_LIMIT_FLAG,'Y','Yes','No') RES_SINGLE_INSTANCE_LIMIT
,DECODE(ExmMiscPolicies.DAILY_LIMIT_FLAG,'Y','Yes','No') RES_DAILY_SUM_LIMIT
,DECODE(ExmMiscPolicies.YEARLY_LIMIT_FLAG,'Y','Yes','No') RES_YEARLY_LIMIT
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'MONTH'
	AND LOOKUP_CODE = ExmMiscPolicies.PERIOD_MONTH
	) RES_PERIOD_START_MONTH
,ExmMiscPolicies.PERIOD_DAY RES_PERIOD_START_DAY
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EXM_CURRENCY_OPTION'
	AND LOOKUP_CODE = ExmMiscPolicies.CURRENCY_OPTION_CODE
	) RES_RATE_CURRENCY
,(CASE
	WHEN ExmMiscPolicies.CURRENCY_OPTION_CODE = 'MULTIPLE' THEN
		NULL
	ELSE
		ExmMiscPolicies.CURRENCY_CODE||' - '||
		(SELECT NAME 
			FROM FND_CURRENCIES_TL
			WHERE CURRENCY_CODE = ExmMiscPolicies.CURRENCY_CODE
			AND LANGUAGE = USERENV('LANG'))
	END) RES_CURRENCY
,DECODE(ExmMiscPolicies.ENABLED_ROLE_FLAG,'Y','Yes','No') RES_ROLE
,(CASE
	WHEN ExmMiscPolicies.ENABLED_ROLE_FLAG = 'Y' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_POLICY_ROLE'
		AND LOOKUP_CODE = ExmMiscPolicies.POLICY_ROLE_CODE)
	END) RES_ROLE_TYPE
,DECODE(ExmMiscPolicies.ENABLED_GENDER_FLAG,'Y','Yes','No') RES_GENDER
,DECODE(ExmMiscPolicies.ENABLED_LOCATION_FLAG,'Y','Yes','No') RES_LOCATION
,(CASE
	WHEN ExmMiscPolicies.ENABLED_LOCATION_FLAG = 'Y' THEN
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_LOCATION_TYPE'
		AND LOOKUP_CODE = ExmMiscPolicies.LOCATION_TYPE_CODE)
	END) RES_LOCATION_TYPE
,(CASE
	WHEN ExmMiscPolicies.ENABLED_LOCATION_FLAG = 'Y' AND ExmMiscPolicies.LOCATION_TYPE_CODE = 'ZONE' THEN
		(SELECT MEANING 
			FROM FND_LOOKUP_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = ExmMiscPolicies.ZONE_TYPE_CODE)
	END) RES_ZONE_TYPE
,(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EXM_POLICY_ENFORCEMENT'
		AND LOOKUP_CODE = ExmMiscPolicies.POLICY_ENFORCEMENT_CODE
		) RES_POLICY_ENFORCEMENT
,(CASE
	WHEN ExmMiscPolicies.POLICY_ENFORCEMENT_CODE = 'VIOLATION' THEN
		DECODE(ExmMiscPolicies.POLICY_VIOLATION_FLAG,'Y','Yes','No')
	END) RES_POLICY_VIOLATION_WARNING
,ExmMiscPolicies.WARNING_TOLERANCE RES_WARNING_TOLERANCE_PERCENTA
,(CASE
	WHEN ExmMiscPolicies.POLICY_ENFORCEMENT_CODE = 'VIOLATION' AND ExmMiscPolicies.POLICY_VIOLATION_FLAG = 'Y' THEN
		DECODE(ExmMiscPolicies.DISP_WARNING_TO_USER_FLAG,'Y','Yes','No')
	END) RES_DISPLAY_WARNING_TO_USER
,(CASE
	WHEN ExmMiscPolicies.POLICY_ENFORCEMENT_CODE = 'VIOLATION' THEN
		DECODE(ExmMiscPolicies.PREVENT_SUBMISSION_FLAG,'Y','Yes','No')
	END) RES_PREVENT_REPORT_SUBMISSION
,ExmMiscPolicies.ERROR_TOLERANCE RES_ERROR_TOLERANCE_PERCENTAGE
,ExmMiscPolicies.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ExmMiscPolicies.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ExmMiscPolicies.CREATED_BY RSC_CREATED_BY
,ExmMiscPolicies.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EXM_MISC_POLICIES ExmMiscPolicies
ORDER BY ExmMiscPolicies.POLICY_NAME