/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Balance%20Exceptions%20-%20Balance%20Exception.sql $:
 * $Id: Manage Balance Exceptions - Balance Exception.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 -- RSC_PREREQUISITE_OBJECTS=PAY_BAL_EXCEPTIONS_VL
 
SELECT (SELECT NAME FROM PER_LEGISLATIVE_DATA_GROUPS_VL WHERE LEGISLATIVE_DATA_GROUP_ID = payBALEXEO.LEGISLATIVE_DATA_GROUP_ID) RES_LEGISLATIVE_DATA_GROUP
,payBALEXEO.BAL_EXCEPTION_NAME RES_BALANCE_EXCEPTION_NAME
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payBALEXEO.COMPARISON_TYPE
		AND LOOKUP_TYPE = 'PAY_BAL_EXCP_COMPARISON_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_COMPARISON_TYPE
,payBALEXEO.COMPARISON_VALUE RES_COMPARISON_VALUE
,(SELECT BALANCE_NAME FROM PAY_BALANCE_TYPES_TL WHERE BALANCE_TYPE_ID = payDEFINEBALEO.BALANCE_TYPE_ID  
	AND LANGUAGE = USERENV('LANG')) RES_BALANCE_NAME
,SUBSTR(payBALDIMENEO.BASE_DIMENSION_NAME,5,LENGTH(payBALDIMENEO.BASE_DIMENSION_NAME)-4) RES_DIMENSION
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payBALEXEO.VARIANCE_TYPE
		AND LOOKUP_TYPE = 'PAY_BAL_EXCP_VARIANCE_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_VARIANCE_TYPE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payBALEXEO.VARIANCE_OPERATOR
		AND LOOKUP_TYPE = 'PAY_BAL_EXCP_VAR_OPERATOR_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_VARIANCE_OPERATOR
,(SELECT BASE_FORMULA_NAME
			FROM FF_FORMULAS_VL
			WHERE FORMULA_ID = payBALEXEO.FORMULA_ID) RES_FORMULA_NAME
,payBALEXEO.VARIANCE_VALUE RES_VARIANCE_VALUE
,payBALEXEO.SEVERITY_LEVEL RES_SEVERITY_LEVEL
,(SELECT BALANCE_NAME FROM PAY_BALANCE_TYPES_TL WHERE BALANCE_TYPE_ID = payTARGETEO.BALANCE_TYPE_ID  
	AND LANGUAGE = USERENV('LANG')) RES_TARGET_BALANCE_NAME
,SUBSTR(payTARGETBALDIMENEO.BASE_DIMENSION_NAME,5,LENGTH(payTARGETBALDIMENEO.BASE_DIMENSION_NAME)-4) RES_TARGET_DIMENSION_NAME

,payBALEXEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payBALEXEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payBALEXEO.CREATED_BY RSC_CREATED_BY
,payBALEXEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PAY_BAL_EXCEPTIONS_VL  payBALEXEO
,PAY_DEFINED_BALANCES payDEFINEBALEO
,PAY_DEFINED_BALANCES payTARGETEO
,PAY_BALANCE_DIMENSIONS payBALDIMENEO
,PAY_BALANCE_DIMENSIONS payTARGETBALDIMENEO
WHERE payBALEXEO.DEFINED_BALANCE_ID = payDEFINEBALEO.DEFINED_BALANCE_ID
AND payDEFINEBALEO.BALANCE_DIMENSION_ID = payBALDIMENEO.BALANCE_DIMENSION_ID
AND payBALEXEO.TARGET_DEFINED_BALANCE_ID  = payTARGETEO.DEFINED_BALANCE_ID(+)
AND payTARGETEO.BALANCE_DIMENSION_ID  = payTARGETBALDIMENEO.BALANCE_DIMENSION_ID(+)
ORDER BY RES_LEGISLATIVE_DATA_GROUP,payBALEXEO.LEGISLATION_CODE,RES_BALANCE_EXCEPTION_NAME