/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20New%20Item%20Request%20Type%20Details%20-%20Status%20Details.sql $:
 * $Id: Manage New Item Request Type Details - Status Details.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=EGO_CHANGE_TYPES_VL
 
SELECT changeOrderTypesE0.TYPE_NAME RES_NAME
,changeStatusE0.STATUS_NAME RES_STATUS
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_EGO_STEP_ACTIVITY_CODES'
	AND LOOKUP_CODE = statusDetailsE0.STEP_ACTIVITY_TYPE
	) RES_ACTIVITY_TYPE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_EGO_STEP_STAGE_TYPES'
	AND LOOKUP_CODE = statusDetailsE0.TASK_STAGE_TYPE
	) RES_APPROVAL_STAGE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_EGO_STEP_LIST_BUILDER_TYPE'
	AND LOOKUP_CODE = statusDetailsE0.TASK_ROUTING_SLIP_LIST_BUILDER
	) RES_ASSIGNMENT_METHOD	
,(CASE
	WHEN statusDetailsE0.STEP_ACTIVITY_TYPE = 'OPTIONAL_APPROVAL' THEN 
		NULL
	ELSE
		(SELECT MEANING
		FROM FND_LOOKUPS
		WHERE LOOKUP_TYPE = 'EGO_ROUTE_STEP_RES_REQ'
		AND LOOKUP_CODE = statusDetailsE0.RESPONSE_REQUIRED_FROM)
	END) RES_RESPONSE_REQUIRED_FROM
,DECODE(statusDetailsE0.SKIP_FLAG,'Y','Yes','No') RES_DISABLE
,statusDetailsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,statusDetailsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,statusDetailsE0.CREATED_BY  RSC_CREATED_BY
,statusDetailsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM EGO_CHANGE_TYPES_VL changeOrderTypesE0
,(SELECT ENTITY_ID1
	,CHANGE_LIFECYCLE_STATUS_ID
	,STATUS_CODE
	,SEQUENCE_NUMBER
	FROM EGO_LIFECYCLE_STATUSES
	WHERE ENTITY_NAME = 'EGO_CHANGE_TYPE'
	) workflowsE0
,EGO_CHANGE_STATUSES_VL changeStatusE0
,(SELECT STEP_ACTIVITY_TYPE
	,TASK_STAGE_TYPE
	,TASK_ROUTING_SLIP_LIST_BUILDER
	,RESPONSE_REQUIRED_FROM
	,SKIP_FLAG
	,OBJECT_PK1
	,OBJECT_PK2
	,LAST_UPDATED_BY
	,LAST_UPDATE_DATE
	,CREATED_BY
	,CREATION_DATE
	FROM EGO_ROUTE_STEPS 
	WHERE OBJECT_NAME = 'EGO_CHANGE'
	) statusDetailsE0
WHERE  changeOrderTypesE0.CHANGE_TYPE_ID = workflowsE0.ENTITY_ID1
AND workflowsE0.STATUS_CODE = changeStatusE0.STATUS_CODE
AND changeOrderTypesE0.CHANGE_TYPE_ID = statusDetailsE0.OBJECT_PK1
AND workflowsE0.CHANGE_LIFECYCLE_STATUS_ID = statusDetailsE0.OBJECT_PK2
AND changeOrderTypesE0.TYPE_INTERNAL_NAME = 'NewItemRequest'
AND DECODE(changeOrderTypesE0.TYPE_CLASSIFICATION,'HEADER','EGO_HEADER_STAGE','LINE','EGO_LINE_STAGE') = statusDetailsE0.TASK_STAGE_TYPE
ORDER BY changeOrderTypesE0.TYPE_NAME
,workflowsE0.SEQUENCE_NUMBER
,statusDetailsE0.STEP_ACTIVITY_TYPE