/* ****************************************************************************
 * $Revision: 62668 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-06-19 18:28:29 +0700 (Mon, 19 Jun 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.12/trunk/core/reverse_sql/FINANCIALS/Assign%20Legal%20Entities%20-%20Assign%20Legal%20Entities.sql $:
 * $Id: Assign Legal Entities - Assign Legal Entities.sql 62668 2017-06-19 11:28:29Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=FUN_BAL_INTRA_RULES

SELECT GlLedgersE0.NAME RES_LEDGER
,(SELECT USER_JE_SOURCE_NAME
	FROM GL_JE_SOURCES_VL
	WHERE JE_SOURCE_NAME = FunBalIntraRulesE0.JE_SOURCE_NAME
	AND LANGUAGE = USERENV('LANG')
	) RES_JOURNAL_SOURCE
,(SELECT USER_JE_CATEGORY_NAME
	FROM GL_JE_CATEGORIES_TL
	WHERE JE_CATEGORY_NAME = FunBalIntraRulesE0.JE_CATEGORY_NAME
	AND LANGUAGE = USERENV('LANG')
	) RES_JOURNAL_CATEGORY	
,FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'GL'
	,KEY_FLEX_CODE => 'GL#'
	,STRUCTURE_NUMBER => FunBalIntraRulesE0.STRUCTURE_ID
	,COMBINATION_ID => FunBalIntraRulesE0.INTRA_RECEIVABLE_CCID
	) RES_RECEIVABLES_ACCOUNT
,FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'GL'
	,KEY_FLEX_CODE => 'GL#'
	,STRUCTURE_NUMBER => FunBalIntraRulesE0.STRUCTURE_ID
	,COMBINATION_ID => FunBalIntraRulesE0.INTRA_PAYABLE_CCID
	) RES_PAYABLES_ACCOUNT
,TO_CHAR(FunBalIntraRulesE0.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(FunBalIntraRulesE0.END_DATE,'DD-Mon-YYYY') RES_END_DATE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'FUN_INTRA_ACCT_BAL_OPT'
	AND LOOKUP_CODE = FunBalIntraRulesE0.BALANCE_BY_FLAG
	) RES_SUMMARIZATION
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'FUN_INTRA_ACCT_CLEAR_OPT'
	AND LOOKUP_CODE = FunBalIntraRulesE0.CLEARING_OPTION
	) RES_CONDITION
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'FUN_INTRA_ACCT_M_M_OPT'
	AND LOOKUP_CODE = DECODE(FunBalIntraRulesE0.MANY_TO_MANY_OPTION,'2D',NULL,FunBalIntraRulesE0.MANY_TO_MANY_OPTION)
	) RES_SOURCE
,FunBalIntraRulesE0.CLEARING_BSV RES_VALUE
,FunBalIntraRulesE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,FunBalIntraRulesE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,FunBalIntraRulesE0.CREATED_BY  RSC_CREATED_BY
,FunBalIntraRulesE0.CREATION_DATE  RSC_CREATION_DATE
,FunBalIntraRulesE0.LEDGER_ID RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FUN_BAL_INTRA_RULES FunBalIntraRulesE0
,GL_LEDGERS GlLedgersE0
WHERE FunBalIntraRulesE0.LEDGER_ID = GlLedgersE0.LEDGER_ID
ORDER BY GlLedgersE0.NAME