/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2017-05-02 $:
 * $HeadURL:  $:
 * $Id: Manage Item Organizations - Basic Information.sql  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT DISTINCT (CASE
	WHEN EXISTS (SELECT 1 FROM HR_ORG_UNIT_CLASSIFICATIONS_F WHERE ORGANIZATION_ID = ORG.ORGANIZATION_ID AND CLASSIFICATION_CODE = 'DEPARTMENT') THEN
		'Create from Existing Department'
	ELSE
		'Create New Organization'
	END) RES_CREATION_METHOD
,ORG.NAME RES_ORGANIZATION_NAME
,NULL RES_MANAGER
,NULL RES_ADMINISTRATOR
,NULL RES_LEAD
,NULL RES_RESOURCE_NAME
,(SELECT CLASSIFICATION_NAME 
	FROM HR_ORG_CLASSIFICATIONS_TL
	WHERE CLASSIFICATION_CODE = ORG_USG.CLASSIFICATION_CODE
	AND LANGUAGE = USERENV('LANG')
	) RES_ORGANIZATION_USAGE
,ORG_USG.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ORG_USG.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ORG_USG.CREATED_BY RSC_CREATED_BY
,ORG_USG.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HR_ALL_ORGANIZATION_UNITS ORG
,HR_ORG_UNIT_CLASSIFICATIONS_F ORG_USG
WHERE ORG.ORGANIZATION_ID = ORG_USG.ORGANIZATION_ID
AND TRUNC(sysdate) BETWEEN ORG_USG.EFFECTIVE_START_DATE AND ORG_USG.EFFECTIVE_END_DATE
AND ORG_USG.CLASSIFICATION_CODE IN ('MARKETING_RESOURCE_ORGANIZATION','SALES_RESOURCE_ORG','CONTRACTS_RESOURCE_ORGANIZATION','SERVICE_RESOURCE_ORGANIZATION')
ORDER BY ORG.NAME
,RES_ORGANIZATION_USAGE