/* ****************************************************************************
 * $Revision: 54943 $:
 * $Author: paul.wakefield $:
 * $Date: 2016-05-04 13:45:23 +0700 (Wed, 04 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Trading%20Community%20Person%20Lookups%20-%20Standard%20Lookup%20Type.sql $:
 * $Id: Manage Trading Community Person Lookups - Standard Lookup Type.sql 54943 2016-05-04 06:45:23Z paul.wakefield $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
SELECT DISTINCT benPLEO.NAME RES_PLAN_NAME
,benPGMEO.NAME RES_PROGRAM_NAME
,(SELECT NAME FROM HR_ORGANIZATION_UNITS
				WHERE SYSDATE BETWEEN DATE_FROM AND DATE_TO
				AND ORGANIZATION_ID = benACTYPOOLE0.LEGAL_ENTITY_ID) RES_LEGAL_EMPLOYER
,TO_CHAR(benACTYPOOLE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,TO_CHAR(benACTYPOOLE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_END_DATE
,benACTYPOOLE0.NAME RES_CREDIT_POOL_NAME
,(SELECT NAME FROM BEN_OPT_F
    WHERE OPT_ID = benACTYPOOLE0.OPT_ID) RES_CREDIT_PROVIDER_OPTION
,(SELECT NAME
	FROM BEN_PL_TYP_F
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND PL_TYP_ID = benACTYPOOLE0.PL_TYP_ID) RES_CREDIT_PROVIDER_PLAN
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_STAT'
    AND LOOKUP_CODE = benACTYPOOLE0.ACTY_BASE_RT_STAT_CD
    ) RES_STATUS
,DECODE(ADD_TO_PGM_POOL_FLAG,'Y','Yes','No') RES_ADD_CREDITS_TO_PROGRAM_LEV
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_FLX_CRDT_POOL_MLT'
    AND LOOKUP_CODE = benACTYPOOLE0.RT_MLT_CD
    ) RES_CALCULATION_METHOD
,(CASE WHEN benACTYPOOLE0.RT_MLT_CD IN ('FLFX') 
		THEN benACTYPOOLE0.VAL 
		ELSE NULL END) RES_VALUE 
,(CASE WHEN benACTYPOOLE0.RT_MLT_CD IN ('CL') 
		THEN benACTYPOOLE0.VAL 
		ELSE NULL END) RES_MULTIPLIER
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_RT_TYP'
    AND LOOKUP_CODE = benACTYPOOLE0.RT_TYP_CD
    ) RES_OPERATOR
,(SELECT NAME FROM BEN_COMP_LVL_FCTR
           WHERE COMP_LVL_FCTR_ID = benACTYPOOLE0.COMP_LVL_FCTR_ID) RES_COMPENSATION_FACTOR
,(SELECT MN_COMP_VAL FROM BEN_COMP_LVL_FCTR
           WHERE COMP_LVL_FCTR_ID = benACTYPOOLE0.COMP_LVL_FCTR_ID) RES_GREATER_THAN_OR_EQUAL_TO_C
,(SELECT MX_COMP_VAL FROM BEN_COMP_LVL_FCTR
           WHERE COMP_LVL_FCTR_ID = benACTYPOOLE0.COMP_LVL_FCTR_ID) RES_LESS_THAN_COMPENSATION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_RNDG'
    AND LOOKUP_CODE = benACTYPOOLE0.RNDG_CD
    ) RES_ROUNDING_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benACTYPOOLE0.RNDG_RL
    ) RES_ROUNDING_FORMULA
,benACTYPOOLE0.LWR_LMT_VAL RES_LOW_LIMIT_VALUE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benACTYPOOLE0.LWR_LMT_CALC_RL
    ) RES_LOW_LIMIT_VALUE_FORMULA
,benACTYPOOLE0.UPR_LMT_VAL RES_HIGH_LIMIT_VALUE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benACTYPOOLE0.UPR_LMT_CALC_RL
    ) RES_HIGH_LIMIT_VALUE_FORMULA
,(CASE WHEN benACTYPOOLE0.RT_MLT_CD IN ('ERL')
	THEN (SELECT FORMULA_NAME
			FROM FF_FORMULAS_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND FORMULA_ID = benACTYPOOLE0.VAL_CALC_RL)
    ELSE NULL END) RES_POST_ENROLLMENT_CALCULATIO
,(CASE WHEN benACTYPOOLE0.RT_MLT_CD IN ('RL')
	THEN (SELECT FORMULA_NAME
			FROM FF_FORMULAS_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND FORMULA_ID = benACTYPOOLE0.VAL_CALC_RL)
    ELSE NULL END) RES_VALUE_FORMULA
,DECODE(benACTYPOOLE0.ALWS_NGTV_USG_FLAG,'Y','Yes','No') RES_ALLOW_OVERSPENDING
,benACTYPOOLE0.PCT_NGTV_USG_BY_TOTAL_POOL RES_OVERSPENDING_LIMIT_PERCENT
,DECODE(AUTO_ALCT_EXCS_FLAG,'Y','Yes','No') RES_ALLOCATE_EXCESS_CREDITS_AU
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_CASH_DSTRBN_LMT'
    AND LOOKUP_CODE = benACTYPOOLE0.CASH_DSTRBN_RSTRCN_CD
    ) RES_CASH_DISBURSEMENT_LIMIT
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_EXCS_TRTMT'
    AND LOOKUP_CODE = benACTYPOOLE0.EXCS_TRTMT_CD
    ) RES_EXCESS_TREATMENT_RULE
,(SELECT FORMULA_NAME FROM FF_FORMULAS_TL
	WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benACTYPOOLE0.EXCS_TRTMT_RL) RES_EXCESS_TREATMENT_FORMULA
,(CASE WHEN benACTYPOOLE0.CASH_DSTRBN_RSTRCN_CD IN ('AMT')
	THEN benACTYPOOLE0.MN_CASH_DSTRBL_VAL
	ELSE benACTYPOOLE0.MN_CASH_DSTRBL_PCT END) RES_MINIMUM
,(CASE WHEN benACTYPOOLE0.CASH_DSTRBN_RSTRCN_CD IN ('AMT')
	THEN benACTYPOOLE0.MX_CASH_DSTRBL_VAL
	ELSE benACTYPOOLE0.MX_CASH_DSTRBL_PCT END) RES_MAXIMUM
	
,benACTYPOOLE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benACTYPOOLE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benACTYPOOLE0.CREATED_BY RSC_CREATED_BY
,benACTYPOOLE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPLEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PL_F benPLEO
,BEN_PLIP_F benPLIPEO
,BEN_PGM_F benPGMEO
,BEN_PL_TYP_F benPLTYPEO
,BEN_ACTY_BASE_RT_F benACTYPOOLE0
WHERE benPLEO.PL_TYP_ID = benPLTYPEO.PL_TYP_ID 
AND benPLEO.PL_ID = benPLIPEO.PL_ID
AND benPLIPEO.PGM_ID = benPGMEO.PGM_ID
AND benPLEO.INVK_FLX_CR_PL_FLAG = 'Y'
AND benPGMEO.PGM_ID = benACTYPOOLE0.PGM_ID
AND benACTYPOOLE0.COMP_OBJ_TYPE = 'PGM'
AND SYSDATE BETWEEN benPLEO.EFFECTIVE_START_DATE AND NVL(benPLEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLIPEO.EFFECTIVE_START_DATE AND NVL(benPLIPEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benACTYPOOLE0.EFFECTIVE_START_DATE AND NVL(benACTYPOOLE0.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))

ORDER BY RES_PLAN_NAME,RES_PROGRAM_NAME,RES_LEGAL_EMPLOYER,RES_CREDIT_POOL_NAME