/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Prorate%20Conventions%20-%20Prorate%20Dates.sql $:
 * $Id: Manage Prorate Conventions - Prorate Dates.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

select PRORATECONVENTIONTYPEEO.PRORATE_CONVENTION_CODE RES_NAME
,SETIDSETSEO.SET_NAME RES_REFERENCE_DATA_SET
,TO_CHAR(ProrateConventionEO.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(PRORATECONVENTIONEO.END_DATE,'DD-Mon-YYYY') RES_END_DATE
,TO_CHAR(PRORATECONVENTIONEO.PRORATE_DATE,'DD-Mon-YYYY') RES_PRORATE_DATE
,PRORATECONVENTIONEO.LAST_UPDATED_BY as RSC_LAST_UPDATED_BY
,PRORATECONVENTIONEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
  ,PRORATECONVENTIONEO.CREATED_BY  RSC_CREATED_BY
  ,PRORATECONVENTIONEO.CREATION_DATE  RSC_CREATION_DATE
  ,null RSC_LEDGER_ID
  ,null RSC_CHART_OF_ACCOUNTS_ID
  ,null RSC_BUSINESS_UNIT_ID
  ,null RSC_LEGAL_ENTITY_ID
  ,null RSC_ORGANIZATION_ID
  ,null RSC_BUSINESS_GROUP_ID
  ,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

from FA_CONVENTIONS PRORATECONVENTIONEO 
,FA_CONVENTION_TYPES PRORATECONVENTIONTYPEEO
,FND_SETID_SETS_VL SETIDSETSEO
where PRORATECONVENTIONEO.CONVENTION_TYPE_ID = PRORATECONVENTIONTYPEEO.CONVENTION_TYPE_ID
and PRORATECONVENTIONTYPEEO.SET_ID                    = SETIDSETSEO.SET_ID(+)
ORDER BY PRORATECONVENTIONTYPEEO.PRORATE_CONVENTION_CODE,ProrateConventionEO.START_DATE 