/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Profile%20Types%20-%20Profile%20Types.sql $:
 * $Id: Manage Profile Types - Profile Types.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
--RSC_PREREQUISITE_OBJECTS=HRT_PROFILE_TYPES_VL
 
SELECT profileTypesE0.PROFILE_TYPE_CODE RES_PROFILE_TYPE
,profileTypesE0.DESCRIPTION RES_NAME
,profileTypesE0.SUMMARY RES_DESCRIPTION
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ACTIVE_INACTIVE'
	AND LOOKUP_CODE = profileTypesE0.PROFILE_STATUS_CODE 
	) RES_STATUS
--,TO_CHAR(profileTypesE0.DATE_FROM,'DD-Mon-YYYY') RES_FROM_DATE
--,TO_CHAR(profileTypesE0.DATE_TO,'DD-Mon-YYYY') RES_TO_DATE
,DECODE(profileTypesE0.AUTO_CREATE_FLAG,'Y','Yes','No') RES_AUTOCREATE_PERSON_PROFILES
,(CASE
	WHEN PROFILE_TYPE_CODE = 'JOB' THEN
		DECODE(profileTypesE0.SHOW_DESCRIPTION_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_JOB_DESCRIPTION
,(CASE
	WHEN PROFILE_TYPE_CODE = 'JOB' THEN
		DECODE(profileTypesE0.SHOW_RESPONSIBILITY_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_JOB_RESPONSIBILITI
,(CASE
	WHEN PROFILE_TYPE_CODE = 'JOB' THEN
		DECODE(profileTypesE0.SHOW_QUALIFICATION_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_JOB_QUALIFICATIONS
,(CASE
	WHEN PROFILE_TYPE_CODE IN ('JOB','POSITION','ORGANIZATION') THEN
		DECODE(profileTypesE0.SHOW_CRITICALITY_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_CRITICALITY
,(CASE
	WHEN PROFILE_TYPE_CODE = 'POSITION' THEN
		DECODE(profileTypesE0.SHOW_DESCRIPTION_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_POSITION_DESCRIPTI
,(CASE
	WHEN PROFILE_TYPE_CODE = 'POSITION' THEN
		DECODE(profileTypesE0.SHOW_RESPONSIBILITY_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_POSITION_RESPONSIB
,(CASE
	WHEN PROFILE_TYPE_CODE = 'POSITION' THEN
		DECODE(profileTypesE0.SHOW_QUALIFICATION_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_POSITION_QUALIFICA
,(CASE
	WHEN PROFILE_TYPE_CODE = 'ORGANIZATION' THEN
		DECODE(profileTypesE0.SHOW_DESCRIPTION_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_ORGANIZATION_DESCR
,(CASE
	WHEN PROFILE_TYPE_CODE = 'ORGANIZATION' THEN
		DECODE(profileTypesE0.SHOW_RESPONSIBILITY_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_ORGANIZATION_RESPO
,(CASE
	WHEN PROFILE_TYPE_CODE = 'ORGANIZATION' THEN
		DECODE(profileTypesE0.SHOW_QUALIFICATION_FLAG,'Y','Yes','No') 
	END) RES_INCLUDE_ORGANIZATION_QUALI
/*,DECODE(profileTypesE0.PID_APPROVAL_FLAG,'Y','Yes','No') RES_ENABLE_USER_DEFINED_APPROV
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES_VL
	WHERE LOOKUP_TYPE = 'HRT_PROFILE_USAGE_CODE'
	AND LOOKUP_CODE = profileTypesE0.PROFILE_USAGE_CODE
	) RES_USAGE*/
,profileTypesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,profileTypesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,profileTypesE0.CREATED_BY RSC_CREATED_BY
,profileTypesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,profileTypesE0.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HRT_PROFILE_TYPES_VL profileTypesE0
WHERE profileTypesE0.PROFILE_USAGE_CODE <> 'T'
ORDER BY profileTypesE0.PROFILE_TYPE_CODE