/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT (SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = poHeadersE0.PRC_BU_ID
	) RES_PROCUREMENT_BU
,poHeadersE0.SEGMENT1 RES_AGREEMENT
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = buAccessesE0.REQ_BU_ID
	) RES_REQUISITIONING_BU
,DECODE(buAccessesE0.ORDERED_LOCALLY_FLAG,'Y','Yes','No') RES_ORDER_LOCALLY
,(SELECT VENDOR_SITE_CODE
	FROM POZ_SUPPLIER_SITES_ALL_M
	WHERE VENDOR_SITE_ID = buAccessesE0.VENDOR_SITE_ID
	) RES_PURCHASING_SITE
,(SELECT LOCATION_NAME
	FROM HR_LOCATIONS_ALL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND LOCATION_ID = buAccessesE0.SHIP_TO_LOCATION_ID
	) RES_SHIP_TO_LOCATION
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = buAccessesE0.BILLTO_BU_ID
	)  RES_BILL_TO_BU
,(SELECT LOCATION_NAME
	FROM HR_LOCATIONS_ALL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND LOCATION_ID = buAccessesE0.BILL_TO_LOCATION_ID
	) RES_BILL_TO_LOCATION
,DECODE(buAccessesE0.ENABLED_FLAG,'Y','Yes','No') RES_ENABLED
,buAccessesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,buAccessesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,buAccessesE0.CREATED_BY RSC_CREATED_BY
,buAccessesE0.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,poHeadersE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
   
FROM PO_HEADERS_ALL poHeadersE0
,PO_GA_ORG_ASSIGNMENTS buAccessesE0
WHERE poHeadersE0.TYPE_LOOKUP_CODE IN ('BLANKET','CONTRACT')
AND poHeadersE0.PO_HEADER_ID = buAccessesE0.PO_HEADER_ID
AND poHeadersE0.PRC_BU_ID = buAccessesE0.PRC_BU_ID
ORDER BY 1,poHeadersE0.SEGMENT1