/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20User-Defined%20Criteria%20-%20User%20Defined%20Criteria.sql $:
 * $Id: Manage User-Defined Criteria - User Defined Criteria.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT bECEO.NAME RES_NAME
,bECEO.SHORT_CODE RES_SHORT_CODE
,bECEO.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING FROM HCM_LOOKUPS  
	WHERE LOOKUP_TYPE = 'BEN_ELIG_USERDEF_TABLE' AND LOOKUP_CODE = bECEO.ACCESS_TABLE_NAME1) RES_SET_1_TABLE
,bECEO.ACCESS_COLUMN_NAME1 RES_SET_1_COLUMN
,bECEO.ACCESS_CALC_RULE RES_SET_1_ACCESS_FORMULA
,bECEO.COL1_LOOKUP_TYPE RES_SET_1_LOOKUP
,DECODE(bECEO.ALW_RANGE_VALIDATION_FLAG,'Y','Yes','No') RES_SET_1_ENABLE_RANGE_VALIDAT
,(SELECT MEANING FROM HCM_LOOKUPS  
	WHERE LOOKUP_TYPE = 'BEN_ELIG_USERDEF_TABLE' AND LOOKUP_CODE = bECEO.ACCESS_TABLE_NAME2) RES_SET_2_TABLE
,bECEO.ACCESS_COLUMN_NAME2 RES_SET_2_COLUMN
,bECEO.ACCESS_CALC_RULE2 RES_SET_2_ACCESS_FORMULA
,bECEO.COL2_LOOKUP_TYPE RES_SET_2_LOOKUP
,DECODE(bECEO.ALW_RANGE_VALIDATION_FLAG2,'Y','Yes','No') RES_SET_2_ENABLE_RANGE_VALIDAT
,bECEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,bECEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,bECEO.CREATED_BY RSC_CREATED_BY
,bECEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,bECEO.LEGISLATION_CODE RSC_COUNTRY_ID
FROM BEN_ELIGY_CRITERIA  bECEO