/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=WLF_PROPERTIES

SELECT (CASE
	WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
		WHERE NAME = 'SELF_SERVICE_BROWSE_MODE'
		AND VALUE = 'SELF_SERVICE_DEPRECATED_OLD_BROWSE_CATALOG') THEN
			'Deprecated Old Browse Catalog'
	WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
		WHERE NAME = 'SELF_SERVICE_BROWSE_MODE'
		AND VALUE = 'SELF_SERVICE_ENABLE_NEW_BROWSE_BY') THEN
			'New Browse Catalog By'
	ELSE
	/*WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
		WHERE NAME = 'SELF_SERVICE_BROWSE_MODE'
		AND VALUE = 'SELF_SERVICE_DISABLE_BROWSE_CATALOG') THEN*/
			'Disable Browse'
	END)RES_CONFIGURE_BROWSE_LEARNING_
,(SELECT NAME
	FROM FND_DF_SEGMENTS_VL
	WHERE DESCRIPTIVE_FLEXFIELD_CODE = dff.DESCRIPTIVE_FLEXFIELD_CODE
	AND SEGMENT_CODE = dff.SEGMENT_CODE
	) RES_NAME
,dff.SEGMENT_CODE RES_SEGMENT_CODE
,(SELECT NAME
	FROM FND_DF_FLEXFIELDS_VL
	WHERE DESCRIPTIVE_FLEXFIELD_CODE = dff.DESCRIPTIVE_FLEXFIELD_CODE
	) RES_FLEXFIELD_NAME
,dff.DESCRIPTIVE_FLEXFIELD_CODE RES_FLEXFIELD_CODE
,DECODE(dff.SEARCHABLE_FLAG,'Y','Yes','No') RES_ENABLED
,dff.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,dff.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,dff.CREATED_BY  RSC_CREATED_BY
,dff.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM WLF_FACETED_SEARCH_DFF_SETUP dff
ORDER BY dff.SEGMENT_CODE