/* ****************************************************************************
 * $Revision: 77293 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2021-11-17 09:21:24 +0700 (Wed, 17 Nov 2021) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Programs%20-%20Enrollment.sql $:
 * $Id: Manage Benefit Programs - Enrollment.sql 77293 2021-11-17 02:21:24Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT benPGMEO.NAME RES_PROGRAM_NAME
,benPGMEO.NAME RES_PROGRAM_HIERARCHY
,'Programs' RES_PROGRAM_HIERARCHY_DESCRIPT
,TO_CHAR(benLERCHAGPGME0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(benLERCHAGPGME0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benLERCHAGPGME0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,(SELECT NAME FROM BEN_LER_F_VL WHERE LER_ID = benLERCHAGPGME0.LER_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_SCHEDULE_TYPE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_MTHD'
    AND LOOKUP_CODE = benLERCHAGPGME0.ENRT_MTHD_CD
    ) RES_ENROLLMENT_METHOD
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHAGPGME0.AUTO_ENRT_MTHD_RL
    ) RES_AUTOMATIC_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DFLT_ENRT'
    AND LOOKUP_CODE = benLERCHAGPGME0.DFLT_ENRT_CD) RES_DEFAULT_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHAGPGME0.DFLT_ENRT_RL) RES_DEFAULT_ENROLLMENT_FORMULA
,NULL RES_ENROLLMENT_CHANGE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT'
    AND LOOKUP_CODE = benLERCHAGPGME0.ENRT_CD
    ) RES_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHAGPGME0.ENRT_RL
    ) RES_ENROLLMENT_FORMULA
,NULL RES_INTERIM_RULE
,NULL RES_INTERIM_FORMULA
,NULL RES_UNSUSPEND_ENROLLMENT_RULE
,NULL RES_UNSUSPEND_ENROLLMENT_FORMU
,NULL RES_UNSUSPEND_RATE_RULE
,NULL RES_UNSUSPEND_RATE_FORMULA
,DECODE(benLERCHAGPGME0.STL_ELIG_CANT_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ELIGIBILITY_PREVEN
,DECODE(benLERCHAGPGME0.CRNT_ENRT_PRCLDS_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ENROLLMENT_PREVENT
,NULL RES_ASSIGN_ON_DEFAULT	

,benLERCHAGPGME0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benLERCHAGPGME0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benLERCHAGPGME0.CREATED_BY RSC_CREATED_BY
,benLERCHAGPGME0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID
	
	
FROM BEN_PGM_F benPGMEO
,(SELECT * FROM BEN_LER_CHG_PGM_ENRT_F 
	WHERE LER_ID IN (SELECT LER_ID FROM BEN_LER_F_VL WHERE TYP_CD IN ('SCHEDDA','SCHEDDO')
				AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) 
				AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) benLERCHAGPGME0
WHERE SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND benPGMEO.PGM_ID  = benLERCHAGPGME0.PGM_ID 


ORDER BY RES_PROGRAM_NAME,RES_PROGRAM_HIERARCHY
