/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Time%20Layout%20Sets%20-%20Layout%20Sets.sql $:
 * $Id: Manage Time Layout Sets - Layout Sets.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT hxtTCLAYEO.NAME RES_LAYOUT_NAME
,hxtTCLAYEO.DESCRIPTION RES_DESCRIPTION


,(SELECT DECODE(TMP_HWM.ENABLED_FLAG,'Y','Yes','No') FROM HWM_TL_TASK_RESULTS TMP_HWM
,(SELECT TL_TASK_FEATURES_ID FROM HWM_TL_TASK_FEATURES_VL WHERE TASK_SHORT_NAME = 'RUIL') TMP_FEA
	WHERE  TMP_HWM.TL_TASK_FEATURES_ID = TMP_FEA.TL_TASK_FEATURES_ID AND TMP_HWM.TL_ANSWER_SET_ID = hxtTCLAYPROPEO.ANS_SET_ID) RES_ADDITIONAL_LAYOUTS_TO_INCL 

,DECODE(hxtTCLAYPROPEO.IND_MGR_FLAG,'Y','Yes','No') RES_ADDITIONAL_LAYOUTS_TO_IN_0

,(SELECT DECODE(TMP_HWM.ENABLED_FLAG,'Y','Yes','No') FROM HWM_TL_TASK_RESULTS TMP_HWM
,(SELECT TL_TASK_FEATURES_ID FROM HWM_TL_TASK_FEATURES_VL WHERE TASK_SHORT_NAME = 'SL') TMP_FEA
	WHERE  TMP_HWM.TL_TASK_FEATURES_ID = TMP_FEA.TL_TASK_FEATURES_ID AND TMP_HWM.TL_ANSWER_SET_ID = hxtTCLAYPROPEO.ANS_SET_ID) RES_ADDITIONAL_LAYOUTS_TO_IN_1 
    
,(SELECT DECODE(TMP_HWM.ENABLED_FLAG,'Y','Yes','No') FROM HWM_TL_TASK_RESULTS TMP_HWM
,(SELECT TL_TASK_FEATURES_ID FROM HWM_TL_TASK_FEATURES_VL WHERE TASK_SHORT_NAME = 'WCL') TMP_FEA
	WHERE  TMP_HWM.TL_TASK_FEATURES_ID = TMP_FEA.TL_TASK_FEATURES_ID AND TMP_HWM.TL_ANSWER_SET_ID = hxtTCLAYPROPEO.ANS_SET_ID) RES_ADDITIONAL_LAYOUTS_TO_IN_2

,(SELECT DECODE(TMP_HWM.ENABLED_FLAG,'Y','Yes','No') FROM HWM_TL_TASK_RESULTS TMP_HWM
,(SELECT TL_TASK_FEATURES_ID FROM HWM_TL_TASK_FEATURES_VL WHERE TASK_SHORT_NAME = 'COL') TMP_FEA
	WHERE  TMP_HWM.TL_TASK_FEATURES_ID = TMP_FEA.TL_TASK_FEATURES_ID AND TMP_HWM.TL_ANSWER_SET_ID = hxtTCLAYPROPEO.ANS_SET_ID) RES_ADDITIONAL_LAYOUTS_TO_IN_3
	
,(CASE WHEN hxtTCLAYPROPEO.IND_TCSMRS_CODE LIKE '%PJC;%' THEN
	'Yes'
	ELSE 'No'
	END) RES_TIME_CONSUMER_PROJECT_COST
,DECODE(hxtTCLAYPROPEO.MEMBERSHIP_FLAG,'Y','Yes','No') RES_TIME_CONSUMER_ENABLE_PROJE
,(CASE WHEN hxtTCLAYPROPEO.IND_TCSMRS_CODE LIKE '%PYR%' THEN
	'Yes'
	ELSE 'No'
	END)RES_TIME_CONSUMER_PAYROLL

,hxtTCLAYEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hxtTCLAYEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hxtTCLAYEO.CREATED_BY RSC_CREATED_BY
,hxtTCLAYEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HXT_TCLAYST_VL hxtTCLAYEO   
,HXT_TCLAYST_PROP hxtTCLAYPROPEO

WHERE hxtTCLAYEO.TCLAYST_ID =  hxtTCLAYPROPEO.ANS_SET_ID                      
ORDER BY hxtTCLAYEO.NAME