/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Country%20Default%20Controls%20-%20Country%20Default%20Controls.sql $:
 * $Id: Manage Country Default Controls - Country Default Controls.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=ZX_FC_COUNTRY_DEFAULTS 
 
SELECT
	(SELECT TERRITORY_SHORT_NAME
	FROM FND_TERRITORIES_VL
	WHERE TERRITORY_CODE = COUNTRY_CODE
	) AS RES_COUNTRY
,(SELECT CATEGORY_SET_NAME
	FROM EGP_CATEGORY_SETS_VL
	WHERE CATEGORY_SET_ID = PRIMARY_INVENTORY_CATEGORY_SET
	) AS RES_PRIMARY_INVENTORY_CATEGORY
,INTENDED_USE_DEFAULT AS RES_DEFAULT_TRANSACTION_INTEND
,PRODUCT_CATEG_DEFAULT AS RES_DEFAULT_PRODUCT_CATEGORY_C
,(SELECT MEANING 
	FROM fnd_lookups
	WHERE LOOKUP_TYPE = 'TAX_ROUNDING_RULE'
	AND lookup_code   = ROUNDING_RULE_CODE
	) AS RES_ROUNDING_RULE
,(SELECT MEANING
	FROM fnd_lookups
	WHERE LOOKUP_TYPE = 'ZX_REGISTRATIONS_TYPE'
	AND lookup_code   = REGISTRATION_TYPE_CODE
	) AS RES_TAX_REGISTRATION_TYPE
,(SELECT MEANING
	FROM fnd_lookups
	WHERE LOOKUP_TYPE = 'ZX_REGISTRATIONS_STATUS'
	AND lookup_code   = REGISTRATION_STATUS_CODE
	) AS RES_TAX_REGISTRATION_STATUS
,(SELECT PARTY_NAME
	FROM HZ_PARTIES
	WHERE PARTY_ID =
		(SELECT PARTY_ID
		FROM ZX_PARTY_TAX_PROFILE
		WHERE PARTY_TAX_PROFILE_ID = ZxFcCountryDefaults.COLLECT_TAX_AUTHORITY_ID
		)
	) AS RES_COLLECTING_TAX_AUTHORITY
,(SELECT PARTY_NAME
	FROM HZ_PARTIES
	WHERE PARTY_ID =
		(SELECT PARTY_ID
		FROM ZX_PARTY_TAX_PROFILE
		WHERE PARTY_TAX_PROFILE_ID = REPORT_TAX_AUTHORITY_ID
		)
	) AS RES_REPORTING_TAX_AUTHORITY
,(SELECT PARTY_NAME
	FROM HZ_PARTIES
	WHERE PARTY_ID =
		(SELECT PARTY_ID
		FROM ZX_PARTY_TAX_PROFILE
		WHERE PARTY_TAX_PROFILE_ID = ISSUE_TAX_AUTHORITY_ID
		)
	) AS RES_ISSUING_TAX_AUTHORITY
,TAX_REGIME_CODE AS RES_TAX_REGIME_CODE
,NVL((SELECT MEANING
	FROM fnd_lookups
	WHERE LOOKUP_TYPE = 'YES_NO'
	AND lookup_code   = DEF_REGIME_FOR_INVOICE_FLAG
	),'No') AS RES_TAX_REGIME_CODE_SET_AS_DEF
,NVL((SELECT MEANING
	FROM fnd_lookups
	WHERE LOOKUP_TYPE = 'YES_NO'
	AND lookup_code   = DEF_REGIME_FOR_LE_TR_FLAG
	),'No') AS RES_TAX_REGIME_CODE_SET_AS_D_0
,TAX AS RES_TAX
,NVL((SELECT MEANING
	FROM fnd_lookups
	WHERE LOOKUP_TYPE = 'YES_NO'
	AND lookup_code   = DEF_TAX_FOR_INVOICE_FLAG
	),'No') AS RES_TAX_SET_AS_DEFAULT_FOR_IMP
,NVL((SELECT MEANING
	FROM fnd_lookups
	WHERE LOOKUP_TYPE = 'YES_NO'
	AND lookup_code   = DEF_TAX_FOR_LE_TR_FLAG
	),'No') AS RES_TAX_SET_AS_DEFAULT_TAX_REG
,ZxFcCountryDefaults.VALIDATION_TYPE RES_VALIDATION_TYPE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ZX_VALIDATION_LEVEL'
	AND LOOKUP_CODE = ZxFcCountryDefaults.VALIDATION_LEVEL
	) RES_VALIDATION_LEVEL
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ZX_UNIQUENESS_VALIDATION_LVL'
	AND LOOKUP_CODE = ZxFcCountryDefaults.UNIQUENESS_VALIDATION_LEVEL
	) RES_DUPLICATE_VALIDATION_LEVEL
,ZxFcCountryDefaults.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ZxFcCountryDefaults.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ZxFcCountryDefaults.CREATED_BY RSC_CREATED_BY
,ZxFcCountryDefaults.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
	
FROM ZX_FC_COUNTRY_DEFAULTS ZxFcCountryDefaults
ORDER BY RES_COUNTRY