/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Individual%20Compensation%20Plans%20-%20Element%20Mapping.sql $:
 * $Id: Manage Individual Compensation Plans - Element Mapping.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
SELECT cmpPLANEO.PLAN_NAME RES_PLAN
,cmpCOMPOEO.COMPONENT_NAME RES_OPTION
,payELEMENTEO.BASE_ELEMENT_NAME RES_PAYROLL_ELEMENT

,(CASE WHEN payELEMENTEO.SECONDARY_CLASSIFICATION_ID IS NULL
	THEN (CASE WHEN (SELECT 1 FROM PAY_ELE_CLASSIFICATIONS_VL WHERE BASE_CLASSIFICATION_ID = payELEMENTEO.CLASSIFICATION_ID
								AND LEGISLATION_CODE = perLEGISEO.LEGISLATION_CODE AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))) IS NULL
								THEN (SELECT CLASSIFICATION_NAME FROM PAY_ELE_CLASSIFICATIONS_VL WHERE CLASSIFICATION_ID = payELEMENTEO.CLASSIFICATION_ID
										AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
										AND LEGISLATION_CODE = perLEGISEO.LEGISLATION_CODE )
								ELSE (SELECT CLASSIFICATION_NAME FROM PAY_ELE_CLASSIFICATIONS_VL WHERE BASE_CLASSIFICATION_ID = payELEMENTEO.CLASSIFICATION_ID
										AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
										AND LEGISLATION_CODE = perLEGISEO.LEGISLATION_CODE ) END)
	ELSE 
		(SELECT CLASSIFICATION_NAME FROM PAY_ELE_CLASSIFICATIONS_VL
			WHERE CLASSIFICATION_ID = (SELECT PARENT_CLASSIFICATION_ID FROM PAY_ELE_CLASSIFICATIONS_VL WHERE BASE_CLASSIFICATION_ID = payELEMENTEO.SECONDARY_CLASSIFICATION_ID
										AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
										AND LEGISLATION_CODE = perLEGISEO.LEGISLATION_CODE ) 
										AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))) END)	RES_CLASSIFICATION

,(SELECT TERRITORY_SHORT_NAME FROM FND_TERRITORIES_VL WHERE TERRITORY_CODE = payELEMENTEO.LEGISLATION_CODE) RES_COUNTRY
,perLEGISEO.NAME RES_LEGISLATIVE_DATA_GROUP
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payELEMENTEO.PROCESSING_TYPE
		AND LOOKUP_TYPE = 'PAY_PROCESSING_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_PROCESSING_TYPE

,cmpATTELEEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,cmpATTELEEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,cmpATTELEEO.CREATED_BY RSC_CREATED_BY
,cmpATTELEEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CMP_PLANS_VL cmpPLANEO
,CMP_PLAN_ATTRIBUTES cmpPLANATTEO
,CMP_ATTRIBUTE_ELEMENTS cmpATTELEEO
,CMP_COMPONENTS_VL cmpCOMPOEO 
,PAY_ELEMENT_TYPES_VL payELEMENTEO
,PER_LEGISLATIVE_DATA_GROUPS_VL perLEGISEO
WHERE cmpPLANEO.COMP_TYPE = 'ICD'
AND cmpPLANATTEO.COMP_TYPE = 'ICD'
AND cmpCOMPOEO.COMP_TYPE = 'ICD'
AND cmpPLANEO.PLAN_ID = cmpPLANATTEO.PLAN_ID
AND cmpPLANATTEO.PLAN_ATTRIBUTE_ID = cmpATTELEEO.PLAN_ATTRIBUTE_ID
AND cmpPLANATTEO.COMPONENT_ID = cmpCOMPOEO.COMPONENT_ID
AND cmpATTELEEO.ELEMENT_TYPE_ID = payELEMENTEO.ELEMENT_TYPE_ID
AND payELEMENTEO.LEGISLATIVE_DATA_GROUP_ID = perLEGISEO.LEGISLATIVE_DATA_GROUP_ID(+)
ORDER BY PLAN_NAME