/* ****************************************************************************
* $Revision: 59117 $:
* $Author: nasrullah.dusenmahamad $:
* $Date: 2016-10-21 11:10:58 +0700 (Fri, 21 Oct 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Key%20Flexfields%20-%20Segment%20Labels.sql $:
* $Id: Manage Key Flexfields - Segment Labels.sql 59117 2016-10-21 04:10:58Z nasrullah.dusenmahamad $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT CostOrgPEO.COST_ORG_NAME RES_COST_ORGANIZATION
,CostBookPEO.COST_BOOK_CODE RES_COST_BOOK
,ValUnitEO.VAL_UNIT_CODE RES_VALUATION_UNIT
,ValStructurePEO.VAL_STRUCTURE_CODE RES_VALUATION_STRUCTURE_CODE
,(SELECT REPLACE(LTRIM(SYS_CONNECT_BY_PATH(NAME,'$$$'),'$$$'),'$$$',DELIMITER) CONCAT_SEGMENT_CODE
	FROM
		(SELECT StructureInstancePEO.STRUCTURE_INSTANCE_NUMBER
		,SegmentPEO.SEQUENCE_NUMBER
		,FKSV.DELIMITER
		,SegmentPEO.COLUMN_NAME
		,SegmentInstancePEO.REQUIRED_FLAG
		,StructureInstancePEO.STRUCTURE_INSTANCE_ID
		,SegmentPEO.STRUCTURE_ID
		,SegmentPEO.NAME
		,SegmentPEO.SEGMENT_CODE
		,SegmentInstancePEO.STRUCTURE_INSTANCE_ID                                                                     AS STRUCTURE_INSTANCE_ID1
		,SegmentInstancePEO.SEGMENT_CODE                                                                              AS SEGMENT_CODE1
		,COUNT( *) over(partition BY STRUCTUREINSTANCEPEO.STRUCTURE_INSTANCE_NUMBER)                                  AS CNT
		,RANK() over(partition BY STRUCTUREINSTANCEPEO.STRUCTURE_INSTANCE_NUMBER ORDER BY SegmentPEO.SEQUENCE_NUMBER) AS
			SEG_SEQUENCE
		FROM FND_KF_STRUCTURES_VL FKSV
		,FND_KF_STR_INSTANCES_VL StructureInstancePEO
		,FND_KF_SEGMENT_INSTANCES SegmentInstancePEO
		,FND_KF_SEGMENTS_VL SegmentPEO
		WHERE StructureInstancePEO.STRUCTURE_INSTANCE_ID = SegmentInstancePEO.STRUCTURE_INSTANCE_ID
		AND StructureInstancePEO.STRUCTURE_ID            = SegmentPEO.STRUCTURE_ID
		AND StructureInstancePEO.APPLICATION_ID          = 707
		AND SegmentPEO.SEGMENT_CODE                      = SegmentInstancePEO.SEGMENT_CODE
		AND FKSV.STRUCTURE_ID                            = STRUCTUREINSTANCEPEO.STRUCTURE_ID
		AND SEGMENTPEO.ENABLED_FLAG                      = 'Y'
		AND SegmentInstancePEO.DISPLAY_FLAG              = 'Y'
		) TEMP_VIEW
	WHERE SEG_SEQUENCE             = CNT
		START WITH SEG_SEQUENCE       = 1
	AND STRUCTURE_INSTANCE_NUMBER  = ValUnitDetailEO.STRUCTURE_INSTANCE_NUMBER
		CONNECT BY PRIOR SEG_SEQUENCE = SEG_SEQUENCE - 1
	AND STRUCTURE_INSTANCE_NUMBER  = ValUnitDetailEO.STRUCTURE_INSTANCE_NUMBER
	) RES_ACCOUNT_CODE
,FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'CST',KEY_FLEX_CODE => (SELECT KEY_FLEXFIELD_CODE FROM FND_KF_STR_INSTANCES_VL WHERE STRUCTURE_INSTANCE_NUMBER= ValUnitDetailEO.STRUCTURE_INSTANCE_NUMBER),STRUCTURE_NUMBER =>
	ValUnitDetailEO.STRUCTURE_INSTANCE_NUMBER,COMBINATION_ID => ValUnitDetailEO.VAL_UNIT_COMBINATION_ID) RES_SEGMENT_VALUES
,ValUnitDetailEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ValUnitDetailEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ValUnitDetailEO.CREATED_BY RSC_CREATED_BY
,ValUnitDetailEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,ValUnitEO.COST_ORG_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CST_VAL_UNITS_VL ValUnitEO
,CST_VAL_STRUCTURES_VL ValStructurePEO
,CST_COST_ORGS_V CostOrgPEO
,CST_COST_BOOKS_VL CostBookPEO
,CST_VAL_UNIT_DETAILS ValUnitDetailEO
WHERE ValUnitEO.VAL_STRUCTURE_ID = ValStructurePEO.VAL_STRUCTURE_ID
AND ValUnitEO.COST_ORG_ID        = CostOrgPEO.COST_ORG_ID
AND ValUnitEO.COST_BOOK_ID       = CostBookPEO.COST_BOOK_ID
AND(ValUnitEO.VAL_UNIT_ID        = ValUnitDetailEO.VAL_UNIT_ID
AND ValUnitEO.COST_BOOK_ID       = ValUnitDetailEO.COST_BOOK_ID
AND ValUnitEO.VAL_STRUCTURE_ID   = ValUnitDetailEO.VAL_STRUCTURE_ID)
ORDER BY CostOrgPEO.COST_ORG_NAME
,CostBookPEO.COST_BOOK_CODE
,5