 /* ****************************************************************************
 * $Revision: 48884 $:
 * $Author: dhara.pithadiya $:
 * $Date: 2015-08-18 14:24:02 +0700 (Tue, 18 Aug 2015) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Transaction%20Types%20-%20Manage%20Transaction%20Types.sql $:
 * $Id: Manage Transaction Types - Manage Transaction Types.sql 48884 2015-08-18 07:24:02Z dhara.pithadiya $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=HRG_GOAL_PLAN_GOALS

SELECT goldPlansE0.GOAL_PLAN_NAME RES_GOAL_PLAN
,hrgGOALE0.GOAL_NAME RES_GOAL_NAME
,hrgMEASUREE0.MEASUREMENT_NAME RES_MEASUREMENTS_NAME
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'HRG_GOAL_QUANTITATIVE_UOM'
	AND LOOKUP_CODE = hrgMEASUREE0.UOM_CODE 
	) RES_UNIT_OF_MEASURE
,TO_CHAR(hrgMEASUREE0.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,hrgMEASUREE0.TARGET_VALUE RES_TARGET_VALUE
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'HRG_GOAL_QUANT_MEASURE_TYPE'
	AND LOOKUP_CODE = hrgMEASUREE0.TARGET_TYPE 
	) RES_TARGET_TYPE
,TO_CHAR(hrgMEASUREE0.END_DATE,'DD-Mon-YYYY') RES_END_DATE
,hrgMEASUREE0.ACTUAL_VALUE RES_ACTUAL_VALUE
,hrgMEASUREE0.COMMENTS RES_COMMENTS

,hrgMEASUREE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,hrgMEASUREE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,hrgMEASUREE0.CREATED_BY  RSC_CREATED_BY
,hrgMEASUREE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,goldPlansE0.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID


FROM HRG_GOAL_PLANS_VL goldPlansE0
,HRG_GOAL_PLAN_GOALS goalsE0
,HRG_GOALS hrgGOALE0
,HRG_GOAL_MEASUREMENTS hrgMEASUREE0
WHERE goldPlansE0.GOAL_PLAN_ID = goalsE0.GOAL_PLAN_ID
AND goalsE0.GOAL_ID = hrgGOALE0.GOAL_ID
AND hrgGOALE0.GOAL_ID = hrgMEASUREE0.GOAL_ID
AND goldPlansE0.GOAL_PLAN_TYPE_CODE = 'ORA_HRG_WORKER'
AND goldPlansE0.MASS_REQUEST_ID = hrgGOALE0.MASS_REQUEST_ID
AND SYSDATE BETWEEN NVL(goalsE0.EFFECTIVE_START_DATE,TO_DATE('01-01-1950','DD-MM-YYYY')) AND NVL(goalsE0.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
ORDER BY goldPlansE0.GOAL_PLAN_NAME