/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=WLF_PROPERTIES

SELECT (SELECT FORMULA_NAME 
	FROM FF_FORMULAS_TL 
	WHERE LANGUAGE = USERENV('LANG')
	AND TO_CHAR(FORMULA_ID) = (SELECT VALUE
		FROM WLF_PROPERTIES
		WHERE NAME = 'ORA_WLF_PLAN_WAGE_RATE_FF_ID')
	) RES_LEARNER_WAGE_RATE_FORMULA


-- Plan Profile Default Values

,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_PLAN_RECORD_STATUS'
    AND LOOKUP_CODE = (SELECT VALUE
		FROM WLF_PROPERTIES
		WHERE NAME = 'PLAN_PROF_DEFAULT_PLAN_RECORD_STATUS')
	) RES_PLAN_RECORD_STATUS
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_ASSIGN_ATTR_LOOKUP'
    AND LOOKUP_CODE = (SELECT VALUE
		FROM WLF_PROPERTIES
		WHERE NAME = 'PLAN_PROF_DEFAULT_ASSIGN_AS')
	) RES_ASSIGN_AS
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_ASSIGN_RECORD_STATUS'
    AND LOOKUP_CODE = (SELECT VALUE
		FROM WLF_PROPERTIES
		WHERE NAME = 'PLAN_PROF_DEFAULT_ASSIGNMENT_STATUS')
	) RES_ASSIGNMENT_STATUS
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_WLF_ASSIGN_REC_TYPE'
    AND LOOKUP_CODE = (SELECT VALUE
		FROM WLF_PROPERTIES
		WHERE NAME = 'PLAN_PROF_DEFAULT_ASSIGNMENT_TYPE')
	) RES_ASSIGNMENT_TYPE
,(SELECT TO_CHAR(TO_DATE(VALUE,'YYYY-MM-DD'),'DD-Mon-YYYY')
	FROM WLF_PROPERTIES
	WHERE NAME = 'PLAN_PROF_DEFAULT_COMPLETE_BY'
	) RES_DUE_DATE
,(SELECT VALUE
	FROM WLF_PROPERTIES
	WHERE NAME = 'PLAN_PROF_DEFAULT_NOTE_TO_LEARNER'
	) RES_WITH_THIS_NOTE


-- Plan Profiles for New Assignments

,(SELECT DECODE(VALUE,'true','Yes','No')
	FROM WLF_PROPERTIES
	WHERE NAME = 'NEW_PLAN_PROF_DEFAULT_DYN_UPD_DEL_CHECKED'
	) RES_WHEN_THE_LEARNERS_ARE_NO_L 
	-- When the learners are no longer eligible for this profile, update or delete the assignment records and plan records
,(CASE
	WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
		WHERE NAME = 'NEW_PLAN_PROF_DEFAULT_DYN_UPD_DEL_CHECKED'
		AND VALUE = 'true') THEN
		
		(CASE
			WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
				WHERE NAME = 'NEW_PLAN_PROF_DEFAULT_CHG_PLAN_REC_STATUS'
				AND VALUE = 'true') THEN
					'Keep assignment as planned and change plan record status to'
				ELSE
					'Remove both the assignment and the plan record'
			END)
	END) RES_PLAN_PROFILES_FOR_NEW_ASSI
,(CASE
	WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
		WHERE NAME = 'NEW_PLAN_PROF_DEFAULT_CHG_PLAN_REC_STATUS'
		AND VALUE = 'true') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_WLF_PLAN_RECORD_STATUS'
			AND LOOKUP_CODE = (SELECT VALUE
				FROM WLF_PROPERTIES
				WHERE NAME = 'NEW_PLAN_PROF_DEFAULT_CHG_PLAN_REC_STATUS_TO'))
	END) RES_PLAN_PROFILES_FOR_NEW_AS_0 
	-- Plan Profiles for New Assignment - Change Plan Record Status to


--Plan Profiles for Existing Assignments

,(SELECT DECODE(VALUE,'true','Yes','No')
	FROM WLF_PROPERTIES
	WHERE NAME = 'EXISTING_PLAN_PROF_DEFAULT_DYN_UPD_DEL_CHECKED'
	) RES_WHEN_THE_ASSIGNMENT_NO_LON -- When the assignment no longer meets the selection criteria update or delete the plan records
,(CASE
	WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
		WHERE NAME = 'EXISTING_PLAN_PROF_DEFAULT_DYN_UPD_DEL_CHECKED'
		AND VALUE = 'true') THEN
		
		(CASE
			WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
				WHERE NAME = 'EXISTING_PLAN_PROF_DEFAULT_CHG_PLAN_REC_STATUS'
				AND VALUE = 'true') THEN
					'Change status of plan records'
				ELSE
					'Remove plan records'
			END)
		
	END) RES_PLAN_PROFILES_FOR_EXISTING
,(CASE
	WHEN EXISTS (SELECT 1 FROM WLF_PROPERTIES
		WHERE NAME = 'EXISTING_PLAN_PROF_DEFAULT_CHG_PLAN_REC_STATUS'
		AND VALUE = 'true') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_WLF_PLAN_RECORD_STATUS'
			AND LOOKUP_CODE = (SELECT VALUE
				FROM WLF_PROPERTIES
				WHERE NAME = 'NEW_PLAN_PROF_DEFAULT_CHG_PLAN_REC_STATUS_TO'))
	END) RES_PLAN_PROFILES_FOR_EXISTI_1
	-- Plan Profiles for Existing Assignments - Change status of plan records

,setupsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,setupsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,setupsE0.CREATED_BY  RSC_CREATED_BY
,setupsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM (SELECT LAST_UPDATED_BY
	,LAST_UPDATE_DATE
	,CREATED_BY
	,CREATION_DATE 
	,ROW_NUMBER() OVER (ORDER BY LAST_UPDATE_DATE DESC) R1
	FROM WLF_PROPERTIES 
	) setupsE0
WHERE R1 = 1