/* ****************************************************************************
* $Revision: 78229 $:
* $Author: pisan.jariyasettachok $:
* $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Position%20Security%20Profiles%20-%20Position%20Security%20Profile.sql $:
* $Id: Manage Position Security Profiles - Position Security Profile.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PER_POSITION_SECURITY_PROFILES
-- RSC_PREREQUISITE_OBJECTS=PER_POS_SECPRF_AORSCOPE

SELECT posProfilesE0.NAME RES_NAME
,posProfilesE0.DESCRIPTION RES_DESCRIPTION
,DECODE(posProfilesE0.ENABLED_FLAG,'Y','Yes','No') RES_ENABLED
,DECODE(posProfilesE0.VIEW_ALL,'Y','Yes','No') RES_VIEW_ALL
,DECODE(posProfilesE0.INCLUDE_FUTURE_POSITIONS,'Y','Yes','No') RES_INCLUDE_FUTURE_POSITIONS


--Area of Responsibility
,DECODE(posProfilesE0.SECURE_BY_AOR,'Y','Yes','No') RES_SECURE_BY_AREA_OF_RESPONSI
,(CASE
    WHEN posProfilesE0.SECURE_BY_AOR = 'Y' THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'PER_RESPONSIBILITY_TYPES'
            AND LOOKUP_CODE = aorE0.RESPONSIBILITY_TYPE)
    END) RES_RESPONSIBILITY_TYPE
,(CASE
    WHEN posProfilesE0.SECURE_BY_AOR = 'Y' THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'ORA_PER_PRSN_SEC_AOR_SCOPES'
            AND LOOKUP_CODE = aorE0.SCOPE_OF_RESPONSIBILITY)
    END) RES_SCOPE_OF_RESPONSIBILITY


--Position Hierarchy
,DECODE(posProfilesE0.SECURE_BY_POSITION_HIERARCHY,'Y','Yes','No') RES_SECURE_BY_POSITION_HIERARC
,(CASE
    WHEN posProfilesE0.SECURE_BY_POSITION_HIERARCHY = 'Y' THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'PER_POS_SEC_PROF_TOP_POS_SEL'
            AND LOOKUP_CODE = posProfilesE0.TOP_POS_SELECTION)
    END) RES_TOP_POSITION_SELECTION
,(CASE
    WHEN posProfilesE0.SECURE_BY_POSITION_HIERARCHY = 'Y' THEN
        topPositionsE0.NAME
    END) RES_POSITION_NAME
,(CASE
    WHEN posProfilesE0.SECURE_BY_POSITION_HIERARCHY = 'Y' THEN
        topPositionsE0.POSITION_CODE
    END) RES_POSITION_CODE
,(CASE
    WHEN posProfilesE0.SECURE_BY_POSITION_HIERARCHY = 'Y' THEN
        (SELECT BU_NAME
			FROM FUN_ALL_BUSINESS_UNITS_V
			WHERE BU_ID = topPositionsE0.BUSINESS_UNIT_ID)
    END) RES_POSITION_BUSINESS_UNIT
,(CASE
    WHEN posProfilesE0.SECURE_BY_POSITION_HIERARCHY = 'Y' THEN
        DECODE(posProfilesE0.INCLUDE_TOP_POSITION,'Y','Yes','No')
    END) RES_INCLUDE_TOP_POSITION
,(CASE
    WHEN posProfilesE0.SECURE_BY_POSITION_HIERARCHY = 'Y' AND posProfilesE0.POS_HIERARCHY_TREE_CODE IS NOT NULL 
		THEN 'Position Tree'
		ELSE 'Position Hierarchy'
    END) RES_HIERARCHY_TYPE
,(CASE
    WHEN posProfilesE0.SECURE_BY_POSITION_HIERARCHY = 'Y' AND posProfilesE0.POS_HIERARCHY_TREE_CODE IS NOT NULL THEN
        (SELECT TREE_NAME
            FROM FND_TREE_VL
            WHERE TREE_STRUCTURE_CODE = posProfilesE0.POS_HIERARCHY_TREE_STRUCT_CODE
            AND TREE_CODE = posProfilesE0.POS_HIERARCHY_TREE_CODE)
    END)  RES_POSITION_TREE


--Workforce Structures
,DECODE(posProfilesE0.SECURE_BY_DEPARTMENT,'Y','Yes','No') RES_SECURE_BY_DEPARTMENT
,DECODE(posProfilesE0.SECURE_BY_BUSINESS_UNIT,'Y','Yes','No') RES_SECURE_BY_BUSINESS_UNIT
,(CASE
    WHEN posProfilesE0.SECURE_BY_DEPARTMENT = 'Y' THEN
        (SELECT NAME
            FROM PER_ORG_SECURITY_PROFILES
            WHERE ORG_SECURITY_PROFILE_ID = posProfilesE0.DEPT_ORG_SECURITY_PROFILE_ID)
    END) RES_SECURE_BY_DEPARTMENT_NAME
,(CASE
    WHEN posProfilesE0.SECURE_BY_BUSINESS_UNIT = 'Y' THEN
        (SELECT NAME
            FROM PER_ORG_SECURITY_PROFILES
            WHERE ORG_SECURITY_PROFILE_ID = posProfilesE0.BU_ORG_SECURITY_PROFILE_ID)
    END) RES_SECURE_BY_BUSINESS_UNIT_NA


--Positions
,DECODE(posProfilesE0.SECURE_BY_POSITION_LIST,'Y','Yes','No') RES_SECURE_BY_POSITION_LIST


,posProfilesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,posProfilesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,posProfilesE0.CREATED_BY RSC_CREATED_BY
,posProfilesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
	
FROM PER_POSITION_SECURITY_PROFILES posProfilesE0
,PER_POS_SECPRF_AORSCOPE aorE0
,(SELECT POSITION_ID
	,NAME
	,POSITION_CODE
	,BUSINESS_UNIT_ID
	FROM HR_ALL_POSITIONS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	) topPositionsE0
WHERE posProfilesE0.POSITION_SECURITY_PROFILE_ID = aorE0.POSITION_SECURITY_PROFILE_ID(+)
AND posProfilesE0.TOP_POSITION_ID = topPositionsE0.POSITION_ID(+)
ORDER BY posProfilesE0.NAME