/* ****************************************************************************
 * $Revision$:
 * $Author$:
 * $Date$:
 * $HeadURL$:
 * $Id$:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT (SELECT NAME FROM GL_LEDGERS WHERE LEDGER_ID = xccBCELEDE0.LEDGER_ID) RES_LEDGER_NAME
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = xccBCEBUE0.BUSINESS_UNIT_ID 
	) RES_BUSINESS_UNIT_NAME
,(SELECT USER_JE_SOURCE_NAME FROM GL_JE_SOURCES_VL WHERE JE_SOURCE_NAME = xccBCEJOURNALE0.JE_SOURCE_CODE 
	AND LANGUAGE = USERENV('LANG')) RES_LEDGER_JOURNAL_SOURCE

,xccBCEJOURNALE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,xccBCEJOURNALE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,xccBCEJOURNALE0.CREATED_BY RSC_CREATED_BY
,xccBCEJOURNALE0.CREATION_DATE RSC_CREATION_DATE
,xccBCEJOURNALE0.LEDGER_ID RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,xccBCEBUE0.BUSINESS_UNIT_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
   
FROM XCC_BCE_LEDGERS xccBCELEDE0
,XCC_BCE_BUSINESS_UNITS xccBCEBUE0
,XCC_BCE_JOURNAL_SOURCES xccBCEJOURNALE0
WHERE xccBCELEDE0.LEDGER_ID = xccBCEJOURNALE0.LEDGER_ID
AND xccBCELEDE0.LEDGER_ID = xccBCEBUE0.LEDGER_ID
ORDER BY 1