/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Question%20Library%20-%20Response.sql $:
 * $Id: Manage Question Library - Response.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 /*<RSC_PRE_STEPS_LARGE_COLUMN_POSITION>7</RSC_PRE_STEPS_LARGE_COLUMN_POSITION>
	
-- The column position that using special data type.
 <RSC_PRE_STEPS_LARGE_COLUMN_TYPE>LONG</RSC_PRE_STEPS_LARGE_COLUMN_TYPE>

-- Specify what type of the data.
*/
-- RSC_PREREQUISITE_OBJECTS=HRQ_QUESTIONS_VL
-- RSC_PREREQUISITE_OBJECTS=HRQ_QSTN_ANSWERS_VL

WITH CAT AS (SELECT CATEGORY_ID
	,(SELECT NAME 
		FROM HRQ_CATEGORIES_TL 
		WHERE LANGUAGE = USERENV('LANG')
		AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,1)+3,INSTR(HIER,'###',1,2)-4)
		) PARENT_FOLDER_1
	,(SELECT NAME 
		FROM HRQ_CATEGORIES_TL 
		WHERE LANGUAGE = USERENV('LANG')
		AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,2)+3,INSTR(HIER,'###',1,3) - INSTR(HIER,'###',1,2)-3)
		) PARENT_FOLDER_2
	,(SELECT NAME 
		FROM HRQ_CATEGORIES_TL 
		WHERE LANGUAGE = USERENV('LANG')
		AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,3)+3,INSTR(HIER,'###',1,4) - INSTR(HIER,'###',1,3)-3) 
		) PARENT_FOLDER_3
	,(SELECT NAME 
		FROM HRQ_CATEGORIES_TL 
		WHERE LANGUAGE = USERENV('LANG')
		AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,4)+3,INSTR(HIER,'###',1,5) - INSTR(HIER,'###',1,4)-3) 
		) PARENT_FOLDER_4
	,(SELECT NAME 
		FROM HRQ_CATEGORIES_TL 
		WHERE LANGUAGE = USERENV('LANG')
		AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,5)+3,INSTR(HIER,'###',1,6) - INSTR(HIER,'###',1,5)-3) 
		) PARENT_FOLDER_5
	FROM (SELECT CATEGORY_ID
		,NAME
		,SUBSCRIBER_ID
		,PARENT_CATEGORY_ID
		,LEVEL LV
		,REPLACE(SYS_CONNECT_BY_PATH(NVL(PARENT_CATEGORY_ID,0),'###'),'###0',NULL)||'###' HIER
		,LAST_UPDATED_BY
		,LAST_UPDATE_DATE
		,CREATED_BY
		,CREATION_DATE
		FROM HRQ_CATEGORIES_VL
		WHERE SUBSCRIBER_ID IN (SELECT SUBSCRIBER_ID 
			FROM HRQ_SUBSCRIBERS_VL 
			WHERE SUBSCRIBER_CODE IN ('HRA','PER_CHK','WLF_ASSESSMENTS','WFL','WLF_ENROLLMENTS','HWR','IRC','HWRTMS','HXLTLTC','HNS'))
		AND CONTAIN_QUESTIONS !='N'
		START WITH PARENT_CATEGORY_ID IS NULL
		CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID)
	)


SELECT hrqQUESTIONSEO.QUESTION_CODE RES_QUESTION_CODE
,(SELECT NAME 
	FROM HRQ_SUBSCRIBERS_VL 
	WHERE SUBSCRIBER_ID = hrqQUESTIONSEO.SUBSCRIBER_ID
	) RES_SUBSCRIBER
,NVL((SELECT DISPLAY_NAME 
	FROM PER_PERSON_NAMES_F 
	WHERE PERSON_ID = hrqQUESTIONSEO.OWNER AND NAME_TYPE = 'GLOBAL'
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4512-12-31','YYYY-MM-DD')))
	,hrqQUESTIONSEO.OWNER
	) RES_OWNER
,CAT.PARENT_FOLDER_1 RES_PARENT_FOLDER_1
,CAT.PARENT_FOLDER_2 RES_PARENT_FOLDER_2
,CAT.PARENT_FOLDER_3 RES_PARENT_FOLDER_3
,CAT.PARENT_FOLDER_4 RES_PARENT_FOLDER_4
,CAT.PARENT_FOLDER_5 RES_PARENT_FOLDER_5
,(SELECT NAME 
	FROM HRQ_CATEGORIES_VL 
	WHERE CATEGORY_ID = hrqQUESTIONSEO.CATEGORY_ID
	) RES_FOLDER
,hrqQSTNANSWEREO.QSTN_ANSWER_ID RES_RESPONSE_CODE
,hrqQSTNANSWEREO.SHORT_TEXT RES_SHORT_DECRIPTION
,hrqQSTNANSWEREO.SCORE RES_SCORE
--,hrqQSTNANSWEREO.RESPONSE_FEEDBACK RES_RESPONSE_FEEDBACK
,'' RES_NAME
,DECODE(hrqQSTNANSWEREO.CORRECT_FLAG,'Y','Yes','No') RES_CORRECT_RESPONSE
,hrqQSTNANSWEREO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hrqQSTNANSWEREO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hrqQSTNANSWEREO.CREATED_BY RSC_CREATED_BY
,hrqQSTNANSWEREO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HRQ_QUESTIONS_VL hrqQUESTIONSEO
,HRT_RATING_LEVELS_VL hrqRATINGLVLEO
,HRQ_QSTN_ANSWERS_VL hrqQSTNANSWEREO
,CAT
WHERE hrqQUESTIONSEO.CATEGORY_ID = CAT.CATEGORY_ID
AND hrqQUESTIONSEO.RATING_MODEL_ID = hrqRATINGLVLEO.RATING_MODEL_ID
AND hrqRATINGLVLEO.RATING_LEVEL_ID = hrqQSTNANSWEREO.RATING_LEVEL_ID
AND hrqQUESTIONSEO.CATEGORY_ID = 2
ORDER BY RES_SUBSCRIBER
,DECODE(CAT.PARENT_FOLDER_1,NULL,0,1)
,DECODE(CAT.PARENT_FOLDER_2,NULL,0,1)
,DECODE(CAT.PARENT_FOLDER_3,NULL,0,1)
,DECODE(CAT.PARENT_FOLDER_4,NULL,0,1)
,DECODE(CAT.PARENT_FOLDER_5,NULL,0,1)
,RES_QUESTION_CODE
,RES_RESPONSE_CODE