/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=PAY_ELEMENT_CRITERIA
-- RSC_PREREQUISITE_OBJECTS=PAY_ELEMENT_LINKS_F

SELECT DISTINCT elementsE0.ELEMENT_NAME RES_ELEMENT_NAME
,legislativeDataGrpsE0.NAME RES_LEGISLATIVE_DATA_GROUP
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
	WHERE BASE_CLASSIFICATION_ID = elementsE0.CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PRIMARY_CLASSIFICATION
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
    WHERE BASE_CLASSIFICATION_ID = elementsE0.SECONDARY_CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
    ) RES_SECONDARY_CLASSIFICATION
,TO_CHAR(payElementlinkE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY')  RES_EFFECTIVE_START_DATE
,payElementlinkE0.ELEMENT_LINK_NAME RES_ELEMENT_ELIGIBILITY_NAME
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'PAY_EC_LINK_LEVEL'
    AND LOOKUP_CODE = payElementcriE0.LINK_LEVEL
    ) RES_EMPLOYMENT_LEVEL
,DECODE(payElementlinkE0.STANDARD_LINK_FLAG,'Y','Yes','No') RES_AUTOMATIC_ENTRY
,DECODE(payElementlinkE0.STANDARD_LINK_FLAG,'Y','Complete',NULL) RES_AUTOMATIC_ENTRY_STATUS
,(SELECT REGISTERED_NAME
	FROM fusion.XLE_REGISTRATIONS
	WHERE source_id = payElementcriE0.PAYROLL_STAT_UNIT_ID
	AND identifying_flag = 'Y'
	) RES_PAYROLL_STATUTORY_UNIT
,(SELECT RELATIONSHIP_TYPE_NAME FROM PAY_RELATIONSHIP_TYPES_TL WHERE RELATIONSHIP_TYPE_ID = payElementcriE0.RELATIONSHIP_TYPE_ID
	AND LANGUAGE = USERENV('LANG')) RES_RELATIONSHIP_TYPE
,(SELECT NAME 
	FROM HR_ORGANIZATION_UNITS_F_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND organization_id = payElementcriE0.LEGAL_EMPLOYER_ID 
	) RES_LEGAL_EMPLOYER
,(SELECT NAME 
		FROM PER_DEPARTMENTS
		WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
		AND ORGANIZATION_ID = payElementcriE0.ORGANIZATION_ID
		) RES_DEPARTMENT
,JobDPEO.NAME RES_JOB_NAME
,JobDPEO.JOB_CODE RES_JOB_CODE
,gradesE0.NAME RES_GRADE_NAME
,gradesE0.GRADE_CODE RES_GRADE_CODE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'EMP_CAT'
    AND LOOKUP_CODE = payElementcriE0.EMPLOYMENT_CATEGORY
    ) RES_EMPLOYMENT_CATEGORY
,payElementcriE0.PEOPLE_GROUP_ID RES_PEOPLE_GROUP
,locationE0.LOCATION_NAME RES_LOCATION_NAME
,locationE0.LOCATION_CODE RES_LOCATION_CODE
,posE0.NAME RES_POSITION_NAME
,posE0.POSITION_CODE RES_POSITION_CODE
,(SELECT PAYROLL_NAME FROM PAY_ALL_PAYROLLS_F WHERE PAYROLL_ID = payElementcriE0.PAYROLL_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_PAYROLL
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = payElementcriE0.BARGAINING_UNIT_CODE 
	AND LOOKUP_TYPE = 'BARGAINING_UNIT_CODE' 
	AND LANGUAGE = USERENV('LANG')
	) RES_BARGAINING_UNIT
,(SELECT COLLECTIVE_AGREEMENT_NAME  
	FROM PER_COL_AGREEMENTS_F_VL 
	WHERE COLLECTIVE_AGREEMENT_ID  =  payElementcriE0.COLLECTIVE_AGREEMENT_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE  AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))
	) RES_COLLECTIVE_AGREEMENT
,DECODE(payElementcriE0.LABOUR_UNION_MEMBER_FLAG,'Y','Yes','No') RES_UNION_MEMBER
,DECODE(payElementcriE0.LINK_TO_ALL_PAYROLLS_FLAG,'Y','Yes','No') RES_ALL_PAYROLLS_ELIGIBLE
,(SELECT FORMULA_NAME
	FROM FF_FORMULAS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND FORMULA_ID = payElementlinkE0.CALCULATION_FORMULA_ID) RES_CALCULATION_FORMULA
,(SELECT FORMULA_NAME
	FROM FF_FORMULAS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND FORMULA_ID = payElementlinkE0.DEFAULTING_FORMULA_ID) RES_DEFAULTING_FORMULA
,(SELECT FORMULA_NAME
	FROM FF_FORMULAS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND FORMULA_ID = payElementlinkE0.VALIDATION_FORMULA_ID) RES_VALIDATION_FORMULA
,DECODE(TO_CHAR(payElementlinkE0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(payElementlinkE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE

,payElementcriE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payElementcriE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payElementcriE0.CREATED_BY RSC_CREATED_BY
,payElementcriE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legislativeDataGrpsE0.LEGISLATION_CODE RSC_COUNTRY_ID


FROM PAY_ELEMENT_TYPES_VL elementsE0
,PAY_ELEMENT_LINKS_F payElementlinkE0
,PAY_ELEMENT_CRITERIA payElementcriE0
,(SELECT NAME
    ,LEGISLATIVE_DATA_GROUP_ID
	,LEGISLATION_CODE
    FROM PER_LEGISLATIVE_DATA_GROUPS_VL
    ) legislativeDataGrpsE0
,(SELECT NAME
		,JOB_ID
		,JOB_CODE
		FROM PER_JOBS_F_VL 
		WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
		) JobDPEO
,(SELECT NAME
		,GRADE_ID
		,GRADE_CODE 
		FROM PER_GRADES_F_VL 
		WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
		) gradesE0
,(SELECT LOCATION_ID 
		,LOCATION_NAME
		,LOCATION_CODE
		FROM HR_LOCATIONS_ALL
		WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE) locationE0
,(SELECT POSITION_ID
	,NAME
	,POSITION_CODE
	FROM HR_ALL_POSITIONS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	) posE0
	
WHERE elementsE0.LEGISLATIVE_DATA_GROUP_ID = legislativeDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID
AND elementsE0.ELEMENT_TYPE_ID = payElementlinkE0.ELEMENT_TYPE_ID 
AND payElementlinkE0.ELEMENT_CRITERIA_ID  = payElementcriE0.ELEMENT_CRITERIA_ID 
AND payElementcriE0.JOB_ID = JobDPEO.JOB_ID(+)
AND payElementcriE0.GRADE_ID = gradesE0.GRADE_ID(+)
AND payElementcriE0.LOCATION_ID = locationE0.LOCATION_ID(+)
AND payElementcriE0.POSITION_ID = posE0.POSITION_ID(+)
AND NVL(payElementlinkE0.COSTING_LINK_FLAG,'N') = 'N'
--AND SYSDATE BETWEEN elementsE0.EFFECTIVE_START_DATE AND NVL(elementsE0.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND elementsE0.EFFECTIVE_START_DATE = payElementlinkE0.EFFECTIVE_START_DATE
ORDER BY elementsE0.ELEMENT_NAME


