/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Spreadsheet%20Business%20Object%20Access%20-%20Assigned%20Business%20Objects.sql $:
 * $Id: Manage Spreadsheet Business Object Access - Assigned Business Objects.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=HRC_SDL_BO_ROLE_MAP

 
SELECT perROLEO.ROLE_COMMON_NAME RES_CODE
,hrcSDLROLEMAPEO.ALL_BUS_OBJ_ACCESS RES_ASSIGN
,DECODE(hrcSDLROLEMAPEO.ACTIVE_STATUS,'Y','Yes','No') RES_ENABLED
,hrcDLUIBUSIOBJEO.UI_NAME RES_BUSINESS_OBJECT
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = hrcDLBUSOBJEO.PRODUCT_AREA
		AND LOOKUP_TYPE = 'ORA_HRC_DL_PRODUCT_AREAS' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_PRODUCT_AREA
,hrcDLUIBUSIOBJEO.UI_DESCRIPTION  RES_DESCRIPTION

,hrcSDLROLEMAPEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hrcSDLROLEMAPEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hrcSDLROLEMAPEO.CREATED_BY RSC_CREATED_BY
,hrcSDLROLEMAPEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PER_ROLES_DN_VL perROLEO
,HRC_SDL_BO_ROLE_MAP hrcSDLROLEMAPEO
,HRC_DL_BUSINESS_OBJECTS  hrcDLBUSOBJEO
,HRC_DL_UI_BUS_OBJECTS_VL hrcDLUIBUSIOBJEO
WHERE perROLEO.ROLE_ID = hrcSDLROLEMAPEO.ROLE_ID
AND hrcSDLROLEMAPEO.BUSINESS_OBJECT_ID = hrcDLBUSOBJEO.BUSINESS_OBJECT_ID
AND hrcDLBUSOBJEO.UI_BUSINESS_OBJECT_ID  = hrcDLUIBUSIOBJEO.UI_BUSINESS_OBJECT_ID
