/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2017-10-31 $:
 * $HeadURL:  $:
 * $Id: Manage Shipping Charge Lists - Shipping Charge List - DFF $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=667##RES##QP_SHIPPING_CHARGE_LISTS_FLEX
-- DFF_ATTRIBUTES=ATTRIBUTE_CHAR,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields. 

-- RSC_PREREQUISITE_OBJECTS=QP_SHIPPING_CHARGE_LISTS_VL

SELECT SHIPPING.NAME 				RES_NAME
,SHIPPING.ATTRIBUTE_CATEGORY 		RES_CONTEXT_CODE
,SHIPPING.ATTRIBUTE_CHAR1
,SHIPPING.ATTRIBUTE_CHAR2
,SHIPPING.ATTRIBUTE_CHAR3
,SHIPPING.ATTRIBUTE_CHAR4
,SHIPPING.ATTRIBUTE_CHAR5
,SHIPPING.ATTRIBUTE_CHAR6
,SHIPPING.ATTRIBUTE_CHAR7
,SHIPPING.ATTRIBUTE_CHAR8
,SHIPPING.ATTRIBUTE_CHAR9
,SHIPPING.ATTRIBUTE_CHAR10
,SHIPPING.ATTRIBUTE_CHAR11
,SHIPPING.ATTRIBUTE_CHAR12
,SHIPPING.ATTRIBUTE_CHAR13
,SHIPPING.ATTRIBUTE_CHAR14
,SHIPPING.ATTRIBUTE_CHAR15
,SHIPPING.ATTRIBUTE_CHAR16
,SHIPPING.ATTRIBUTE_CHAR17
,SHIPPING.ATTRIBUTE_CHAR18
,SHIPPING.ATTRIBUTE_CHAR19
,SHIPPING.ATTRIBUTE_CHAR20
,SHIPPING.ATTRIBUTE_NUMBER1
,SHIPPING.ATTRIBUTE_NUMBER2
,SHIPPING.ATTRIBUTE_NUMBER3
,SHIPPING.ATTRIBUTE_NUMBER4
,SHIPPING.ATTRIBUTE_NUMBER5
,SHIPPING.ATTRIBUTE_NUMBER6
,SHIPPING.ATTRIBUTE_NUMBER7
,SHIPPING.ATTRIBUTE_NUMBER8
,SHIPPING.ATTRIBUTE_NUMBER9
,SHIPPING.ATTRIBUTE_NUMBER10
,TO_CHAR(SHIPPING.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(SHIPPING.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(SHIPPING.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(SHIPPING.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(SHIPPING.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,SHIPPING.ATTRIBUTE_TIMESTAMP1
,SHIPPING.ATTRIBUTE_TIMESTAMP2
,SHIPPING.ATTRIBUTE_TIMESTAMP3
,SHIPPING.ATTRIBUTE_TIMESTAMP4
,SHIPPING.ATTRIBUTE_TIMESTAMP5
,SHIPPING.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,SHIPPING.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,SHIPPING.CREATED_BY RSC_CREATED_BY
,SHIPPING.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,SHIPPING.ORG_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM QP_SHIPPING_CHARGE_LISTS_VL  SHIPPING
WHERE SHIPPING.ATTRIBUTE_CATEGORY IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR1            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR2            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR3            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR4            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR5            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR6            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR7            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR8            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR9            IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR10           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR11           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR12           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR13           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR14           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR15           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR16           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR17           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR18           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR19           IS NOT NULL
OR SHIPPING.ATTRIBUTE_CHAR20           IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER1     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER2     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER3     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER4     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER5     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER6     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER7     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER8     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER9     IS NOT NULL
OR SHIPPING.ATTRIBUTE_NUMBER10    IS NOT NULL
OR SHIPPING.ATTRIBUTE_DATE1       IS NOT NULL
OR SHIPPING.ATTRIBUTE_DATE2       IS NOT NULL
OR SHIPPING.ATTRIBUTE_DATE3       IS NOT NULL
OR SHIPPING.ATTRIBUTE_DATE4       IS NOT NULL
OR SHIPPING.ATTRIBUTE_DATE5       IS NOT NULL
OR SHIPPING.ATTRIBUTE_TIMESTAMP1  IS NOT NULL
OR SHIPPING.ATTRIBUTE_TIMESTAMP2  IS NOT NULL
OR SHIPPING.ATTRIBUTE_TIMESTAMP3  IS NOT NULL
OR SHIPPING.ATTRIBUTE_TIMESTAMP4  IS NOT NULL
OR SHIPPING.ATTRIBUTE_TIMESTAMP5  IS NOT NULL
ORDER BY SHIPPING.NAME