/* ****************************************************************************
 * $Revision$:
 * $Author$:
 * $Date$:
 * $HeadURL$:
 * $Id$:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=XCC_CONTROL_BUDGETS

SELECT DISTINCT xccCONTROLBUDE0.NAME  RES_NAME
,DECODE(xccCONTROLBUDE0.ALLOW_OVERRIDES_FLAG,'Y','Yes','No') RES_ALLOW_OVERRIDES
,xccOVERIDE0.NAME RES_OVERRIDE_RULES_NAME
,DECODE(xccOVERIDE0.ENABLED_FLAG,'Y','Yes','No') RES_ENABLED
,xccOVERIDE0.DESCRIPTION RES_DESCRIPTION
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccOVERIDE0.OVERRIDE_TYPE_CODE
	AND LOOKUP_TYPE = 'XCC_CB_OVERRIDE_TYPE_CODE' AND LANGUAGE = USERENV('LANG')) RES_TYPE
,xccOVERIDE0.OVERRIDE_AMOUNT RES_AMOUNT

,xccOVERIDE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,xccOVERIDE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,xccOVERIDE0.CREATED_BY RSC_CREATED_BY
,xccOVERIDE0.CREATION_DATE RSC_CREATION_DATE
,xccCONTROLBUDE0.LEDGER_ID RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM XCC_CONTROL_BUDGETS xccCONTROLBUDE0
,XCC_CB_OVERRIDE_RULES xccOVERIDE0
WHERE xccCONTROLBUDE0.CONTROL_BUDGET_ID = xccOVERIDE0.CONTROL_BUDGET_ID
AND xccCONTROLBUDE0.ALLOW_OVERRIDES_FLAG = 'Y'
ORDER BY 1,3