/* ****************************************************************************
 * $Revision: 78895 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-06-29 15:34:19 +0700 (Wed, 29 Jun 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Plans%20-%20Dependent%20Certification%20Details.sql $:
 * $Id: Manage Benefit Plans - Dependent Certification Details.sql 78895 2022-06-29 08:34:19Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=BEN_PL_F
 
SELECT benPlansE0.NAME RES_PLAN_NAME
,TO_CHAR(benPlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ACTN_TYP'
    AND LOOKUP_CODE = dpnActionItemsE0.ACTN_TYP_CD
    ) RES_ACTION_ITEM
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_BNF_CTFN_TYP'
    AND LOOKUP_CODE = dpnCertTypesE0.DPNT_CVG_CTFN_TYP_CD
    ) RES_CERTIFICATION_TYPE
,dpnCertTypesE0.DPNT_CTFN_DETERMINE_CD RES_DETERMINATION_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = dpnCertTypesE0.CTFN_RQD_WHEN_RL
    ) RES_DETERMINATION_FORMULA
,DECODE(dpnCertTypesE0.RQD_FLAG,'Y','Yes','No') RES_REQUIRED
,TO_CHAR(dpnCertTypesE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_CERTIFICATION_DETAILS_EFFE
,DECODE(TO_CHAR(dpnCertTypesE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY'),'31-12-4712',NULL,TO_CHAR(dpnCertTypesE0.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_CERTIFICATION_DETAILS_EF_0
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'CONTACT'
    AND LOOKUP_CODE = dpnCertTypesE0.RLSHP_TYP_CD
    ) RES_RELATIONSHIP_TYPE
,dpnCertTypesE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,dpnCertTypesE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,dpnCertTypesE0.CREATED_BY  RSC_CREATED_BY
,dpnCertTypesE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPlansE0.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PL_F benPlansE0
,(SELECT NAME
	,PL_TYP_ID
    FROM BEN_PL_TYP_F
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND OPT_TYP_CD != 'FLXCR'
	) planTypesE0
,BEN_POPL_ACTN_TYP_F dpnActionItemsE0
,BEN_PL_DPNT_CVG_CTFN_F dpnCertTypesE0
WHERE SYSDATE BETWEEN benPlansE0.EFFECTIVE_START_DATE AND benPlansE0.EFFECTIVE_END_DATE
AND benPlansE0.PL_TYP_ID = planTypesE0.PL_TYP_ID
AND benPlansE0.PL_ID = dpnActionItemsE0.PL_ID
AND dpnActionItemsE0.ACTN_TYP_LVL_CD = 'DPNTCTFN'
AND dpnActionItemsE0.POPL_ACTN_TYP_ID = dpnCertTypesE0.POPL_ACTN_TYP_ID
AND benPlansE0.EFFECTIVE_END_DATE BETWEEN dpnCertTypesE0.EFFECTIVE_START_DATE AND dpnCertTypesE0.EFFECTIVE_END_DATE
ORDER BY benPlansE0.NAME
,benPlansE0.EFFECTIVE_START_DATE