/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT (SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemSubInvE0.ORGANIZATION_ID
	) RES_ORGANIZATION
,ItemSubInvE0.SECONDARY_INVENTORY RES_SUBINVENTORY
,(SELECT ITEM_NUMBER
	FROM EGP_SYSTEM_ITEMS_B
	WHERE INVENTORY_ITEM_ID = ItemSubInvE0.INVENTORY_ITEM_ID 
	AND ORGANIZATION_ID = ItemSubInvE0.ORGANIZATION_ID 
	) RES_ITEM
,(SELECT DESCRIPTION
	FROM EGP_SYSTEM_ITEMS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND INVENTORY_ITEM_ID = ItemSubInvE0.INVENTORY_ITEM_ID 
	AND ORGANIZATION_ID = ItemSubInvE0.ORGANIZATION_ID 
	) RES_ITEM_DESCRIPTION
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'INV_MATERIAL_PLANNING'
	AND LOOKUP_CODE = ItemSubInvE0.INVENTORY_PLANNING_CODE
	) RES_INVENTORY_PLANNING_METHOD
,NVL((SELECT UNIT_OF_MEASURE
		FROM INV_UNITS_OF_MEASURE_VL
		WHERE UOM_CODE = ItemSubInvE0.MINMAX_QUANTITY_UOM)
	,(SELECT UNIT_OF_MEASURE
		FROM INV_UNITS_OF_MEASURE_VL
		WHERE UOM_CLASS = 5
		AND BASE_UOM_FLAG = 'Y'
		AND ROWNUM = 1)
	) RES_MIN_MAX_QUANTITY_UOM
,ItemSubInvE0.MIN_MINMAX_QUANTITY RES_MINIMUM_QUANTITY
,ItemSubInvE0.MAX_MINMAX_QUANTITY RES_MAXIMUM_QUANTITY
,ItemSubInvE0.FIXED_LOT_MULTIPLE RES_FIXED_LOT_MULTIPLE
,ItemSubInvE0.MINIMUM_ORDER_QUANTITY RES_MINIMUM_ORDER_QUANTITY
,ItemSubInvE0.MAXIMUM_ORDER_QUANTITY RES_MAXIMUM_ORDER_QUANTITY
,ItemSubInvE0.PREPROCESSING_LEAD_TIME RES_PREPROCESSING
,ItemSubInvE0.PROCESSING_LEAD_TIME RES_PROCESSING
,ItemSubInvE0.POSTPROCESSING_LEAD_TIME RES_POSTPROCESSING
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'INV_SOURCE_TYPES'
	AND LOOKUP_CODE = ItemSubInvE0.SOURCE_TYPE
	) RES_TYPE
,(SELECT ORGANIZATION_NAME
	FROM INV_ORGANIZATION_DEFINITIONS_V
	WHERE ORGANIZATION_ID = ItemSubInvE0.SOURCE_ORGANIZATION_ID
	) RES_SOURCING_ORGANIZATION
,ItemSubInvE0.SOURCE_SUBINVENTORY RES_SOURCING_SUBINVENTORY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = ItemSubInvE0.PAR_UOM_CODE
	) RES_ORDERING_UOM
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'INV_DEFAULT_REPLEN_COUNT_TYPE'
	AND LOOKUP_CODE = ItemSubInvE0.DEFAULT_COUNT_TYPE_CODE
	) RES_REPLENISHMENT_COUNT_TYPE
,ItemSubInvE0.PAR_LEVEL RES_PAR_LEVEL
,ItemSubInvE0.PAR_MAX_QTY RES_PAR_MAXIMUM_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = ItemSubInvE0.PAR_UOM_CODE
	) RES_PAR_LEVEL_UOM
,ItemSubInvE0.QTY_COUNT_TOLERANCE RES_COUNT_TOLERANCE_PERCENTAGE
,ItemSubInvE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemSubInvE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemSubInvE0.CREATED_BY RSC_CREATED_BY
,ItemSubInvE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,ItemSubInvE0.ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
FROM INV_ITEM_SUB_INVENTORIES ItemSubInvE0