/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Revenue%20Scheduling%20Rules%20-%20Schedule%20-%20DFF.sql $:
 * $Id: Manage Revenue Scheduling Rules - Schedule - DFF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=222##RES##RA_RULE_SCHEDULES
-- DFF_ATTRIBUTES=ATTRIBUTE
-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.
 
select SETIDSETPEO.SET_NAME RES_SET
,RARULES.name RES_NAME
,RARULESCHEDULES.period_number RES_PERIOD_NUMBER
,RARULESCHEDULES.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,RARULESCHEDULES.ATTRIBUTE1 
,RARULESCHEDULES.ATTRIBUTE2
,RARULESCHEDULES.ATTRIBUTE3
,RARULESCHEDULES.ATTRIBUTE4
,RARULESCHEDULES.ATTRIBUTE5
,RARULESCHEDULES.ATTRIBUTE6
,RARULESCHEDULES.ATTRIBUTE7
,RARULESCHEDULES.ATTRIBUTE8
,RARULESCHEDULES.ATTRIBUTE9
,RARULESCHEDULES.ATTRIBUTE10
,RARULESCHEDULES.ATTRIBUTE11
,RARULESCHEDULES.ATTRIBUTE12
,RARULESCHEDULES.ATTRIBUTE13
,RARULESCHEDULES.ATTRIBUTE14
,RARULESCHEDULES.ATTRIBUTE15
,RARULESCHEDULES.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,RARULESCHEDULES.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,RARULESCHEDULES.CREATED_BY  RSC_CREATED_BY
,RARULESCHEDULES.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
from RA_RULES RARULES
,RA_RULE_SCHEDULES RARULESCHEDULES
,FND_SETID_SETS_VL SetIdSetPEO
WHERE (RARULESCHEDULES.ATTRIBUTE_CATEGORY IS NOT NULL OR
RARULESCHEDULES.ATTRIBUTE1 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE2 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE3 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE4 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE5 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE6 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE7 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE8 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE9 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE10 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE11 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE12 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE13 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE14 IS NOT NULL OR 
RARULESCHEDULES.ATTRIBUTE15 IS NOT NULL)
and RARULES.RULE_ID =  RARULESCHEDULES.RULE_ID
and RARULES.SET_ID = SETIDSETPEO.SET_ID
AND RARULES.TYPE NOT IN('I')
order by RARULES.NAME
,RARULESCHEDULES.period_number