/* ****************************************************************************
* $Revision: 78229 $:
* $Author: pisan.jariyasettachok $:
* $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Asset%20Categories%20-%20Accounts%20Rules.sql $:
* $Id: Manage Asset Categories - Accounts Rules.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=FA_CATEGORY_BOOKS

-- FIELD_TO_APPLY_FUNCTION=RES_ASSET_COST/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_ASSET_CLEARING/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_DEPRECIATION_EXPENSE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_DEPRECIATION_RESERVE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_BONUS_DEPRECIATION_EXPENSE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_BONUS_DEPRECIATION_RESERVE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_CIP_COST/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_CIP_CLEARING/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_UNPLANNED_DEPRECIATION_EXP/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_IMPAIRMENT_EXPENSE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_IMPAIRMENT_RESERVE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_REVALUATION_RESERVE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_REVALUATION_RESERVE_AMORTI/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_REVALUATION_LOSS_EXPENSE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_CAPITAL_ADJUSTMENT_FUND/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_GENERAL_FUND/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_LEASE_LIABILITY/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_LEASE_INTEREST_EXPENSE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_OPERATING_LEASE_EXPENSE/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_GAIN_OR_LOSS_ON_LEASED_ASS/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_LEASE_CLEARING/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_LEASE_CONVERSION_RATE_GAIN/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_COST_WRITE_OFF_ACCOUNT/GET_CODE_COMBINATION

SELECT faCatsE0.SEGMENT1 AS RES_CATEGORY1
,faCatsE0.SEGMENT2 AS RES_CATEGORY2
,faCatsE0.SEGMENT3 AS RES_CATEGORY3
,faCatsE0.SEGMENT4 AS RES_CATEGORY4
,faCatsE0.SEGMENT5 AS RES_CATEGORY5
,faCatsE0.SEGMENT6 AS RES_CATEGORY6
,faCatsE0.SEGMENT7 AS RES_CATEGORY7
,CategoryBookEO.BOOK_TYPE_CODE              AS RES_BOOK
,CategoryBookEO.ASSET_COST_ACCOUNT_CCID     AS RES_ASSET_COST
,CategoryBookEO.ASSET_CLEARING_ACCOUNT_CCID AS RES_ASSET_CLEARING
,CategoryBookEO.DEPRN_EXPENSE_ACCOUNT_CCID  AS RES_DEPRECIATION_EXPENSE
,CategoryBookEO.RESERVE_ACCOUNT_CCID        AS RES_DEPRECIATION_RESERVE
,CategoryBookEO.BONUS_EXPENSE_ACCOUNT_CCID  AS RES_BONUS_DEPRECIATION_EXPENSE
,CategoryBookEO.BONUS_RESERVE_ACCT_CCID     AS RES_BONUS_DEPRECIATION_RESERVE
,CategoryBookEO.WIP_COST_ACCOUNT_CCID       AS RES_CIP_COST
,CategoryBookEO.WIP_CLEARING_ACCOUNT_CCID   AS RES_CIP_CLEARING
,CategoryBookEO.LEASE_LIABILITY_ACCOUNT_CCID RES_LEASE_LIABILITY
,CategoryBookEO.LEASE_INT_EXPENSE_ACCOUNT_CCID RES_LEASE_INTEREST_EXPENSE
,CategoryBookEO.LEASE_EXPENSE_ACCOUNT_CCID RES_OPERATING_LEASE_EXPENSE
,CategoryBookEO.LEASE_GAIN_LOSS_ACCOUNT_CCID RES_GAIN_OR_LOSS_ON_LEASED_ASS
,CategoryBookEO.LEASE_CLEARING_ACCOUNT_CCID RES_LEASE_CLEARING
,CategoryBookEO.LEASE_RATE_GAIN_LOSS_ACCT_CCID RES_LEASE_CONVERSION_RATE_GAIN
,CategoryBookEO.UNPLAN_EXPENSE_ACCOUNT_CCID AS RES_UNPLANNED_DEPRECIATION_EXP
,CategoryBookEO.IMPAIR_EXPENSE_ACCOUNT_CCID AS RES_IMPAIRMENT_EXPENSE
,CategoryBookEO.IMPAIR_RESERVE_ACCOUNT_CCID AS RES_IMPAIRMENT_RESERVE
,CategoryBookEO.REVAL_RESERVE_ACCOUNT_CCID  AS RES_REVALUATION_RESERVE
,CategoryBookEO.REVAL_AMORT_ACCOUNT_CCID    AS RES_REVALUATION_RESERVE_AMORTI
,CategoryBookEO.REVAL_LOSS_ACCOUNT_CCID     AS RES_REVALUATION_LOSS_EXPENSE
,CategoryBookEO.COST_WRITE_OFF_ACCOUNT_CCID RES_COST_WRITE_OFF_ACCOUNT
,(CASE
	WHEN BookControlPEO.ALLOW_FUND_ACCOUNTING_FLAG = 'Y' 
		THEN CategoryBookEO.CAPITAL_ADJ_ACCOUNT_CCID
		ELSE
			NULL
		END) AS RES_CAPITAL_ADJUSTMENT_FUND
,(CASE
	WHEN BookControlPEO.ALLOW_FUND_ACCOUNTING_FLAG = 'Y' 
		THEN CategoryBookEO.GENERAL_FUND_ACCOUNT_CCID   
		ELSE
			NULL
		END) AS RES_GENERAL_FUND
,NVL((SELECT meaning
	FROM fnd_lookups
	WHERE lookup_type = 'YES_NO'
	AND lookup_code   = CategoryBookEO.DEFAULT_EXPENSE_CCID_FLAG
	),'No') AS RES_DEFAULT_DEPRECIATION_EXPEN
,CategoryBookEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,CategoryBookEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
,CategoryBookEO.CREATED_BY RSC_CREATED_BY
,CategoryBookEO.CREATION_DATE RSC_CREATION_DATE
,PGL.PRIMARY_LEDGER_ID RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FA_CATEGORY_BOOKS CategoryBookEO
,FA_BOOK_CONTROLS BookControlPEO
,FA_CATEGORIES_B faCatsE0
,(select RSHIP.TARGET_LEDGER_ID
	, RSHIP.PRIMARY_LEDGER_ID 
	from GL_LEDGER_RELATIONSHIPS RSHIP
	WHERE (RSHIP.RELATIONSHIP_TYPE_CODE <> 'NONE'
	AND RSHIP.TARGET_LEDGER_CATEGORY_CODE = 'SECONDARY')
	OR (RSHIP.RELATIONSHIP_TYPE_CODE = 'NONE'
	AND RSHIP.TARGET_LEDGER_CATEGORY_CODE = 'PRIMARY')) PGL
WHERE CategoryBookEO.BOOK_TYPE_CODE = BookControlPEO.BOOK_TYPE_CODE
AND BookControlPEO.SET_OF_BOOKS_ID = PGL.TARGET_LEDGER_ID
AND CategoryBookEO.CATEGORY_ID = faCatsE0.CATEGORY_ID
ORDER BY RES_CATEGORY1