/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 -- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=801##RES##PAY_ELEMENT_LINKS_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE

-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.
 
-- RSC_PREREQUISITE_OBJECTS=PAY_ELEMENT_LINKS_F

SELECT DISTINCT elementsE0.ELEMENT_NAME RES_ELEMENT_NAME
,legislativeDataGrpsE0.NAME RES_LEGISLATIVE_DATA_GROUP
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
	WHERE BASE_CLASSIFICATION_ID = elementsE0.CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PRIMARY_CLASSIFICATION
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
    WHERE BASE_CLASSIFICATION_ID = elementsE0.SECONDARY_CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD'))
    ) RES_SECONDARY_CLASSIFICATION
,TO_CHAR(payElementlinkE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY')  RES_EFFECTIVE_START_DATE
,payElementlinkE0.ELEMENT_LINK_NAME RES_ELEMENT_ELIGIBILITY_NAME

,payElementlinkE0.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,payElementlinkE0.ATTRIBUTE1
,payElementlinkE0.ATTRIBUTE2
,payElementlinkE0.ATTRIBUTE3
,payElementlinkE0.ATTRIBUTE4
,payElementlinkE0.ATTRIBUTE5
,payElementlinkE0.ATTRIBUTE6
,payElementlinkE0.ATTRIBUTE7
,payElementlinkE0.ATTRIBUTE8
,payElementlinkE0.ATTRIBUTE9
,payElementlinkE0.ATTRIBUTE10
,payElementlinkE0.ATTRIBUTE11
,payElementlinkE0.ATTRIBUTE12
,payElementlinkE0.ATTRIBUTE13
,payElementlinkE0.ATTRIBUTE14
,payElementlinkE0.ATTRIBUTE15
,payElementlinkE0.ATTRIBUTE16
,payElementlinkE0.ATTRIBUTE17
,payElementlinkE0.ATTRIBUTE18
,payElementlinkE0.ATTRIBUTE19
,payElementlinkE0.ATTRIBUTE20
,payElementlinkE0.ATTRIBUTE21
,payElementlinkE0.ATTRIBUTE22
,payElementlinkE0.ATTRIBUTE23
,payElementlinkE0.ATTRIBUTE24
,payElementlinkE0.ATTRIBUTE25
,payElementlinkE0.ATTRIBUTE26
,payElementlinkE0.ATTRIBUTE27
,payElementlinkE0.ATTRIBUTE28
,payElementlinkE0.ATTRIBUTE29
,payElementlinkE0.ATTRIBUTE30
,payElementlinkE0.ATTRIBUTE_NUMBER1
,payElementlinkE0.ATTRIBUTE_NUMBER2
,payElementlinkE0.ATTRIBUTE_NUMBER3
,payElementlinkE0.ATTRIBUTE_NUMBER4
,payElementlinkE0.ATTRIBUTE_NUMBER5
,payElementlinkE0.ATTRIBUTE_NUMBER6
,payElementlinkE0.ATTRIBUTE_NUMBER7
,payElementlinkE0.ATTRIBUTE_NUMBER8
,payElementlinkE0.ATTRIBUTE_NUMBER9
,payElementlinkE0.ATTRIBUTE_NUMBER10
,payElementlinkE0.ATTRIBUTE_NUMBER11
,payElementlinkE0.ATTRIBUTE_NUMBER12
,payElementlinkE0.ATTRIBUTE_NUMBER13
,payElementlinkE0.ATTRIBUTE_NUMBER14
,payElementlinkE0.ATTRIBUTE_NUMBER15
,payElementlinkE0.ATTRIBUTE_NUMBER16
,payElementlinkE0.ATTRIBUTE_NUMBER17
,payElementlinkE0.ATTRIBUTE_NUMBER18
,payElementlinkE0.ATTRIBUTE_NUMBER19
,payElementlinkE0.ATTRIBUTE_NUMBER20
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE6,'DD-Mon-YYYY') ATTRIBUTE_DATE6
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE7,'DD-Mon-YYYY') ATTRIBUTE_DATE7
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE8,'DD-Mon-YYYY') ATTRIBUTE_DATE8
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE9,'DD-Mon-YYYY') ATTRIBUTE_DATE9
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE10,'DD-Mon-YYYY') ATTRIBUTE_DATE10
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE11,'DD-Mon-YYYY') ATTRIBUTE_DATE11
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE12,'DD-Mon-YYYY') ATTRIBUTE_DATE12
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE13,'DD-Mon-YYYY') ATTRIBUTE_DATE13
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE14,'DD-Mon-YYYY') ATTRIBUTE_DATE14
,TO_CHAR(payElementlinkE0.ATTRIBUTE_DATE15,'DD-Mon-YYYY') ATTRIBUTE_DATE15


,payElementcriE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payElementcriE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payElementcriE0.CREATED_BY RSC_CREATED_BY
,payElementcriE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legislativeDataGrpsE0.LEGISLATION_CODE RSC_COUNTRY_ID


FROM PAY_ELEMENT_TYPES_VL elementsE0
,PAY_ELEMENT_LINKS_F payElementlinkE0
,PAY_ELEMENT_CRITERIA payElementcriE0
,(SELECT NAME
    ,LEGISLATIVE_DATA_GROUP_ID
	,LEGISLATION_CODE
    FROM PER_LEGISLATIVE_DATA_GROUPS_VL
    ) legislativeDataGrpsE0
	
WHERE elementsE0.LEGISLATIVE_DATA_GROUP_ID = legislativeDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID
AND elementsE0.ELEMENT_TYPE_ID = payElementlinkE0.ELEMENT_TYPE_ID 
AND payElementlinkE0.ELEMENT_CRITERIA_ID  = payElementcriE0.ELEMENT_CRITERIA_ID 
--AND SYSDATE BETWEEN elementsE0.EFFECTIVE_START_DATE AND NVL(elementsE0.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND elementsE0.EFFECTIVE_START_DATE = payElementlinkE0.EFFECTIVE_START_DATE
AND NVL(payElementlinkE0.COSTING_LINK_FLAG,'N') = 'N'
AND(payElementlinkE0.ATTRIBUTE_CATEGORY  IS NOT NULL
OR payElementlinkE0.ATTRIBUTE1           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE2           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE3           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE4           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE5           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE6           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE7           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE8           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE9           IS NOT NULL
OR payElementlinkE0.ATTRIBUTE10          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE11          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE12          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE13          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE14          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE15          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE16          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE17          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE18          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE19          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE20          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE21          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE22          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE23          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE24          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE25          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE26          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE27          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE28          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE29          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE30          IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER1    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER2    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER3    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER4    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER5    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER6    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER7    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER8    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER9    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER10   IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER11    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER12    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER13    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER14    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER15    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER16    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER17    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER18    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER19    IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_NUMBER20   IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE1      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE2      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE3      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE4      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE5      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE6      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE7      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE8      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE9      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE10      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE11      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE12      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE13      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE14      IS NOT NULL
OR payElementlinkE0.ATTRIBUTE_DATE15      IS NOT NULL
)
ORDER BY elementsE0.ELEMENT_NAME


