/* ****************************************************************************
 * $Revision: 53609 $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2016-07-13 10:53:25 +0700  $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Accounting%20Calendars%20-%20Additional%20Year.sql $:
 * $Id: Manage Bank Accounts - Account Contact - DFF.sql 53609 2016-07-13 03:53:25Z  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10024##RES##HZ_PERSON_PROFILES
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.



SELECT 
Head.BANK_NAME  								RES_BANK,
Head.COUNTRY_NAME      							RES_COUNTRY,
Head.BANK_BRANCH_NAME        					RES_BANK_BRANCH,
Head.BANK_ACCOUNT_NAME            				RES_ACCOUNT_NAME,
Head.BANK_ACCOUNT_NUM             				RES_ACCOUNT_NUMBER,
Detail.PARTY_NAME                         		RES_CONTACT_NAME,
DECODE(Detail.PRIMARY_FLAG,'Y','Yes','N','No')                    RES_PRIMARY,
(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LOOKUP_TYPE = 'CONTACT_POINT_PURPOSE'
	AND LOOKUP_CODE   = Detail.CONTACT_POINT_PURPOSE
)                                       		RES_PURPOSE,
Detail.PHONE_COUNTRY_CODE                 		RES_PHONE_COUNTRY_CODE,
Detail.PHONE_AREA_CODE                    		RES_AREA_CODE,
Detail.PHONE_NUMBER                       		RES_PHONE,
Detail.PHONE_EXTENSION                    		RES_EXTENSION,


 Detail.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,Detail.ATTRIBUTE1 
,Detail.ATTRIBUTE2
,Detail.ATTRIBUTE3
,Detail.ATTRIBUTE4
,Detail.ATTRIBUTE5
,Detail.ATTRIBUTE6
,Detail.ATTRIBUTE7
,Detail.ATTRIBUTE8
,Detail.ATTRIBUTE9
,Detail.ATTRIBUTE10
,Detail.ATTRIBUTE11
,Detail.ATTRIBUTE12
,Detail.ATTRIBUTE13
,Detail.ATTRIBUTE14
,Detail.ATTRIBUTE15
,Detail.ATTRIBUTE16
,Detail.ATTRIBUTE17
,Detail.ATTRIBUTE18
,Detail.ATTRIBUTE19
,Detail.ATTRIBUTE20
,Detail.ATTRIBUTE21
,Detail.ATTRIBUTE22
,Detail.ATTRIBUTE23
,Detail.ATTRIBUTE24
,Detail.ATTRIBUTE25
,Detail.ATTRIBUTE26
,Detail.ATTRIBUTE27
,Detail.ATTRIBUTE28
,Detail.ATTRIBUTE29
,Detail.ATTRIBUTE30
,Detail.ATTRIBUTE_NUMBER1 
,Detail.ATTRIBUTE_NUMBER2
,Detail.ATTRIBUTE_NUMBER3
,Detail.ATTRIBUTE_NUMBER4
,Detail.ATTRIBUTE_NUMBER5
,Detail.ATTRIBUTE_NUMBER6
,Detail.ATTRIBUTE_NUMBER7
,Detail.ATTRIBUTE_NUMBER8
,Detail.ATTRIBUTE_NUMBER9
,Detail.ATTRIBUTE_NUMBER10
,Detail.ATTRIBUTE_NUMBER11
,Detail.ATTRIBUTE_NUMBER12
,to_char(Detail.ATTRIBUTE_DATE1,'DD-Mon-YYYY')  ATTRIBUTE_DATE1
,to_char(Detail.ATTRIBUTE_DATE2,'DD-Mon-YYYY')  ATTRIBUTE_DATE2
,to_char(Detail.ATTRIBUTE_DATE3,'DD-Mon-YYYY')  ATTRIBUTE_DATE3
,to_char(Detail.ATTRIBUTE_DATE4,'DD-Mon-YYYY')  ATTRIBUTE_DATE4
,to_char(Detail.ATTRIBUTE_DATE5,'DD-Mon-YYYY')  ATTRIBUTE_DATE5
,to_char(Detail.ATTRIBUTE_DATE6,'DD-Mon-YYYY')  ATTRIBUTE_DATE6
,to_char(Detail.ATTRIBUTE_DATE7,'DD-Mon-YYYY')  ATTRIBUTE_DATE7
,to_char(Detail.ATTRIBUTE_DATE8,'DD-Mon-YYYY')  ATTRIBUTE_DATE8
,to_char(Detail.ATTRIBUTE_DATE9,'DD-Mon-YYYY')  ATTRIBUTE_DATE9
,to_char(Detail.ATTRIBUTE_DATE10,'DD-Mon-YYYY')  ATTRIBUTE_DATE10
,to_char(Detail.ATTRIBUTE_DATE11,'DD-Mon-YYYY')  ATTRIBUTE_DATE11
,to_char(Detail.ATTRIBUTE_DATE12,'DD-Mon-YYYY')  ATTRIBUTE_DATE12
,Detail.LAST_UPDATED_BY  						RSC_LAST_UPDATED_BY
,Detail.LAST_UPDATE_DATE  						RSC_LAST_UPDATE_DATE
,Detail.CREATED_BY  							RSC_CREATED_BY
,Detail.CREATION_DATE  							RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,Head.ACCOUNT_OWNER_ORG_ID RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID


FROM
(
    Select 
      CeBankAccounts.BANK_ACCOUNT_ID,
      BankBranchSimplePEO.BANK_NAME               		,
      BankBranchSimplePEO.COUNTRY_NAME            		,
      BankBranchSimplePEO.BANK_BRANCH_NAME        		,
      CeBankAccounts.BANK_ACCOUNT_NAME             		,
      CeBankAccounts.BANK_ACCOUNT_NUM                   ,
	  CeBankAccounts.ACCOUNT_OWNER_ORG_ID
    FROM CE_BANK_ACCOUNTS CeBankAccounts,
        XLE_ENTITY_PROFILES XleEntityProfiles,
        CE_BANK_BRANCHES_SIMPLE_V BankBranchSimplePEO,
        CE_RECON_RULESETS BankStatementReconRuleSetPEO
    WHERE ((CeBankAccounts.ACCOUNT_OWNER_ORG_ID = XleEntityProfiles.LEGAL_ENTITY_ID)
      AND (CeBankAccounts.BANK_BRANCH_ID          = BankBranchSimplePEO.BRANCH_PARTY_ID)
      AND (CeBankAccounts.RECON_RULESET_ID        = BankStatementReconRuleSetPEO.RECON_RULESET_ID (+))
      AND NOT EXISTS
        (SELECT xtr.bank_account_id
        FROM ce_bank_accounts xtr
        WHERE NVL(AP_USE_ALLOWED_FLAG, 'N') = 'N'
        AND NVL(AR_USE_ALLOWED_FLAG, 'N')   = 'N'
        AND NVL(PAY_USE_ALLOWED_FLAG, 'N')  = 'N'
        AND NVL(XTR_USE_ALLOWED_FLAG, 'N')  = 'Y'
        AND xtr.bank_account_id             = CeBankAccounts.bank_account_id
        ))

) Head
, (
   SELECT
   CeContactAssignments.BANK_ACCOUNT_ID
  ,SubjectPartyEO.PARTY_NAME
   ,PhoneEO.PRIMARY_FLAG
   ,PhoneEO.CONTACT_POINT_PURPOSE
   ,PhoneEO.PHONE_COUNTRY_CODE 
  ,PhoneEO.PHONE_AREA_CODE 
  ,PhoneEO.PHONE_NUMBER 
  ,PhoneEO.PHONE_EXTENSION 
  
,PhoneEO.ATTRIBUTE_CATEGORY 
,PhoneEO.ATTRIBUTE1 
,PhoneEO.ATTRIBUTE2
,PhoneEO.ATTRIBUTE3
,PhoneEO.ATTRIBUTE4
,PhoneEO.ATTRIBUTE5
,PhoneEO.ATTRIBUTE6
,PhoneEO.ATTRIBUTE7
,PhoneEO.ATTRIBUTE8
,PhoneEO.ATTRIBUTE9
,PhoneEO.ATTRIBUTE10
,PhoneEO.ATTRIBUTE11
,PhoneEO.ATTRIBUTE12
,PhoneEO.ATTRIBUTE13
,PhoneEO.ATTRIBUTE14
,PhoneEO.ATTRIBUTE15
,PhoneEO.ATTRIBUTE16
,PhoneEO.ATTRIBUTE17
,PhoneEO.ATTRIBUTE18
,PhoneEO.ATTRIBUTE19
,PhoneEO.ATTRIBUTE20

,PhoneEO.ATTRIBUTE21
,PhoneEO.ATTRIBUTE22
,PhoneEO.ATTRIBUTE23
,PhoneEO.ATTRIBUTE24
,PhoneEO.ATTRIBUTE25
,PhoneEO.ATTRIBUTE26
,PhoneEO.ATTRIBUTE27
,PhoneEO.ATTRIBUTE28
,PhoneEO.ATTRIBUTE29
,PhoneEO.ATTRIBUTE30
,PhoneEO.ATTRIBUTE_NUMBER1 
,PhoneEO.ATTRIBUTE_NUMBER2
,PhoneEO.ATTRIBUTE_NUMBER3
,PhoneEO.ATTRIBUTE_NUMBER4
,PhoneEO.ATTRIBUTE_NUMBER5
,PhoneEO.ATTRIBUTE_NUMBER6
,PhoneEO.ATTRIBUTE_NUMBER7
,PhoneEO.ATTRIBUTE_NUMBER8
,PhoneEO.ATTRIBUTE_NUMBER9
,PhoneEO.ATTRIBUTE_NUMBER10
,PhoneEO.ATTRIBUTE_NUMBER11
,PhoneEO.ATTRIBUTE_NUMBER12
,PhoneEO.ATTRIBUTE_DATE1 
,PhoneEO.ATTRIBUTE_DATE2
,PhoneEO.ATTRIBUTE_DATE3
,PhoneEO.ATTRIBUTE_DATE4
,PhoneEO.ATTRIBUTE_DATE5
,PhoneEO.ATTRIBUTE_DATE6
,PhoneEO.ATTRIBUTE_DATE7
,PhoneEO.ATTRIBUTE_DATE8
,PhoneEO.ATTRIBUTE_DATE9
,PhoneEO.ATTRIBUTE_DATE10
,PhoneEO.ATTRIBUTE_DATE11
,PhoneEO.ATTRIBUTE_DATE12	

  ,PhoneEO.LAST_UPDATED_BY 
  ,PhoneEO.LAST_UPDATE_DATE 
  ,PhoneEO.CREATED_BY 
  ,PhoneEO.CREATION_DATE 

FROM CE_CONTACT_ASSIGNMENTS CeContactAssignments,
  HZ_RELATIONSHIPS RelationshipEO,
  HZ_ORG_CONTACTS OrganizationContactEO,
  HZ_PARTY_SITES ContactPartySiteEO,
  HZ_PARTIES SubjectPartyEO,
  HZ_CONTACT_POINTS PhoneEO
WHERE CeContactAssignments.RELATIONSHIP_ID         = RelationshipEO.RELATIONSHIP_ID
AND  RelationshipEO.RELATIONSHIP_ID               = OrganizationContactEO.PARTY_RELATIONSHIP_ID(+)
AND  RelationshipEO.RELATIONSHIP_ID               = ContactPartySiteEO.RELATIONSHIP_ID(+)
AND RelationshipEO.SUBJECT_ID                      = ContactPartySiteEO.PARTY_ID(+)
AND  RelationshipEO.RELATIONSHIP_ID = PhoneEO.RELATIONSHIP_ID(+)
AND RelationshipEO.SUBJECT_ID        = PhoneEO.OWNER_TABLE_ID(+)
AND PhoneEO.OWNER_TABLE_NAME(+)      = 'HZ_PARTIES'
AND  CeContactAssignments.ASSIGNMENT_TYPE = 'ACCOUNT' 
AND PhoneEO.CONTACT_POINT_TYPE   = 'PHONE'
AND RelationshipEO.SUBJECT_ID                = SubjectPartyEO.PARTY_ID
AND (PhoneEO.ATTRIBUTE_CATEGORY IS NOT NULL OR
PhoneEO.ATTRIBUTE1 IS NOT NULL OR 
PhoneEO.ATTRIBUTE2 IS NOT NULL OR 
PhoneEO.ATTRIBUTE3 IS NOT NULL OR 
PhoneEO.ATTRIBUTE4 IS NOT NULL OR 
PhoneEO.ATTRIBUTE5 IS NOT NULL OR 
PhoneEO.ATTRIBUTE6 IS NOT NULL OR 
PhoneEO.ATTRIBUTE7 IS NOT NULL OR 
PhoneEO.ATTRIBUTE8 IS NOT NULL OR 
PhoneEO.ATTRIBUTE9 IS NOT NULL OR 
PhoneEO.ATTRIBUTE10 IS NOT NULL OR 
PhoneEO.ATTRIBUTE11 IS NOT NULL OR 
PhoneEO.ATTRIBUTE12 IS NOT NULL OR 
PhoneEO.ATTRIBUTE13 IS NOT NULL OR 
PhoneEO.ATTRIBUTE14 IS NOT NULL OR 
PhoneEO.ATTRIBUTE15 IS NOT NULL OR 
PhoneEO.ATTRIBUTE16 IS NOT NULL OR 
PhoneEO.ATTRIBUTE17 IS NOT NULL OR 
PhoneEO.ATTRIBUTE18 IS NOT NULL OR 
PhoneEO.ATTRIBUTE19 IS NOT NULL OR 
PhoneEO.ATTRIBUTE20 IS NOT NULL OR
PhoneEO.ATTRIBUTE21 IS NOT NULL OR 
PhoneEO.ATTRIBUTE22 IS NOT NULL OR 
PhoneEO.ATTRIBUTE23 IS NOT NULL OR 
PhoneEO.ATTRIBUTE24 IS NOT NULL OR 
PhoneEO.ATTRIBUTE25 IS NOT NULL OR 
PhoneEO.ATTRIBUTE26 IS NOT NULL OR 
PhoneEO.ATTRIBUTE27 IS NOT NULL OR 
PhoneEO.ATTRIBUTE28 IS NOT NULL OR 
PhoneEO.ATTRIBUTE29 IS NOT NULL OR 
PhoneEO.ATTRIBUTE30 IS NOT NULL OR
PhoneEO.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER11 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_NUMBER12 IS NOT NULL OR
PhoneEO.ATTRIBUTE_DATE1 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE2 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE3 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE4 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE5 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE6 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE7 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE8 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE9 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE10 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE11 IS NOT NULL OR 
PhoneEO.ATTRIBUTE_DATE12 IS NOT NULL )

) Detail

WHERE Head.BANK_ACCOUNT_ID =   Detail.BANK_ACCOUNT_ID
ORDER BY RES_BANK ,  RES_COUNTRY , RES_ACCOUNT_NAME,  RES_CONTACT_NAME