/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Reporting%20Groups%20-%20Regulatory%20Purposes.sql $:
 * $Id: Manage Benefit Reporting Groups - Regulatory Purposes.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT benRPTGGRPEO.NAME RES_NAME
,benPLREGYBODYEO.REGY_PL_NAME RES_REGULATORY_NAME
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LOOKUP_CODE = benPLREGYPRPEO.PL_REGY_PRPS_CD 
	AND LOOKUP_TYPE = 'BEN_REGY_PRPS' 
	AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('31-12-4712','DD-MM-YYYY'))
	) RES_PURPOSE
,TO_CHAR(benPLREGYPRPEO.EFFECTIVE_START_DATE,'DD-MM-YYYY') RES_EFFECTIVE_START_DATE
,TO_CHAR(benPLREGYPRPEO.EFFECTIVE_END_DATE,'DD-MM-YYYY') RES_EFFECTIVE_END_DATE
,benPLREGYPRPEO.LAST_UPDATED_BY 			RSC_LAST_UPDATED_BY
,benPLREGYPRPEO.LAST_UPDATE_DATE 			RSC_LAST_UPDATE_DATE
,benPLREGYPRPEO.CREATED_BY 				RSC_CREATED_BY
,benPLREGYPRPEO.CREATION_DATE 			RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benRPTGGRPEO.LEGISLATION_CODE RSC_COUNTRY_ID
FROM BEN_RPTG_GRP_VL benRPTGGRPEO
,BEN_PL_REGY_BOD_F benPLREGYBODYEO
,BEN_PL_REGY_PRP_F benPLREGYPRPEO
WHERE benRPTGGRPEO.RPTG_GRP_ID = benPLREGYBODYEO.RPTG_GRP_ID 
AND benPLREGYBODYEO.PL_REGY_BOD_ID = benPLREGYPRPEO.PL_REGY_BOD_ID 
AND SYSDATE BETWEEN benPLREGYBODYEO.EFFECTIVE_START_DATE AND NVL(benPLREGYBODYEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLREGYPRPEO.EFFECTIVE_START_DATE AND NVL(benPLREGYPRPEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))