/* ****************************************************************************
 * $Revision$:
 * $Author$:
 * $Date$:
 * $HeadURL$:
 * $Id$:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=XCC_CONTROL_BUDGETS


SELECT xccCONTROLBUDE0.NAME RES_NAME
,xccRULE0.RULE_NAME RES_SUPPLEMENTAL_RULES_NAME
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccRULEFILTERE0.FILTER_CONDITION_CODE
	AND LOOKUP_TYPE = 'XCC_TRX_ATTRIBUTE_FILTER_CODES' AND LANGUAGE = USERENV('LANG')) RES_TYPE
,'All' RES_VALUE
,NULL RES_ENABLED

,xccRULEFILTERE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,xccRULEFILTERE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,xccRULEFILTERE0.CREATED_BY RSC_CREATED_BY
,xccRULEFILTERE0.CREATION_DATE RSC_CREATION_DATE
,xccCONTROLBUDE0.LEDGER_ID RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM XCC_CONTROL_BUDGETS xccCONTROLBUDE0
,XCC_CB_RULES xccRULE0
,XCC_CB_RULE_FILTER_CONDITIONS xccRULEFILTERE0
WHERE xccCONTROLBUDE0.CONTROL_BUDGET_ID  = xccRULE0.CONTROL_BUDGET_ID 
AND xccRULE0.RULE_ID = xccRULEFILTERE0.RULE_ID
AND xccRULEFILTERE0.FILTER_CONDITION_TYPE = 'TRANSACTION_ATTRIBUTE'
AND xccRULEFILTERE0.APPLICABLE_TO_ALL_VALUES_FLAG = 'Y'

UNION

SELECT xccCONTROLBUDE0.NAME  RES_NAME
,xccRULE0.RULE_NAME RES_SUPPLEMENTAL_RULES_NAME
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccRULEFILTERE0.FILTER_CONDITION_CODE
	AND LOOKUP_TYPE = 'XCC_TRX_ATTRIBUTE_FILTER_CODES' AND LANGUAGE = USERENV('LANG')) RES_TYPE
,(CASE WHEN xccRULEFILTERE0.FILTER_CONDITION_CODE = 'JE_SOURCE' 
	THEN NVL((SELECT USER_JE_SOURCE_NAME FROM GL_JE_SOURCES_TL WHERE JE_SOURCE_NAME = xccRULEFILTERVALE0.FILTER_CONDITION_VALUE 
				AND LANGUAGE = USERENV('LANG')),'No Value')
	WHEN xccRULEFILTERE0.FILTER_CONDITION_CODE = 'JE_SOURCE_CATEGORY'
	THEN NVL((SELECT USER_JE_CATEGORY_NAME FROM GL_JE_CATEGORIES_VL WHERE JE_CATEGORY_NAME = xccRULEFILTERVALE0.FILTER_CONDITION_VALUE 
				AND LANGUAGE = USERENV('LANG')),'No Value')
	WHEN xccRULEFILTERE0.FILTER_CONDITION_CODE = 'P2P_BUS_FUNCTION' 
	THEN (SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccRULEFILTERVALE0.FILTER_CONDITION_VALUE
				AND LOOKUP_TYPE = 'XCC_CB_SUPP_RULE_BF' AND LANGUAGE = USERENV('LANG'))
	WHEN xccRULEFILTERE0.FILTER_CONDITION_CODE = 'NATURAL_ACCOUNT_TYPE' 
	THEN (SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccRULEFILTERVALE0.FILTER_CONDITION_VALUE
				AND LOOKUP_TYPE = 'ACCOUNT_TYPE' AND LANGUAGE = USERENV('LANG'))
	WHEN xccRULEFILTERE0.FILTER_CONDITION_CODE = 'DESTINATION_TYPE' 
	THEN (SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccRULEFILTERVALE0.FILTER_CONDITION_VALUE
				AND LOOKUP_TYPE = 'XCC_RECVING_DEST_TYPE' AND LANGUAGE = USERENV('LANG'))
	END) RES_VALUE
,'Yes' RES_ENABLED

,xccRULEFILTERVALE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,xccRULEFILTERVALE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,xccRULEFILTERVALE0.CREATED_BY RSC_CREATED_BY
,xccRULEFILTERVALE0.CREATION_DATE RSC_CREATION_DATE
,xccCONTROLBUDE0.LEDGER_ID RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM XCC_CONTROL_BUDGETS xccCONTROLBUDE0
,XCC_CB_RULES xccRULE0
,XCC_CB_RULE_FILTER_CONDITIONS xccRULEFILTERE0
,XCC_CB_RULE_FILTER_COND_VALS xccRULEFILTERVALE0
WHERE xccCONTROLBUDE0.CONTROL_BUDGET_ID  = xccRULE0.CONTROL_BUDGET_ID 
AND xccRULE0.RULE_ID = xccRULEFILTERE0.RULE_ID
AND xccRULEFILTERE0.RULE_FILTER_CONDITION_ID = xccRULEFILTERVALE0.RULE_FILTER_CONDITION_ID
AND xccRULEFILTERE0.FILTER_CONDITION_TYPE = 'TRANSACTION_ATTRIBUTE'
AND xccRULEFILTERE0.APPLICABLE_TO_ALL_VALUES_FLAG = 'N'

ORDER BY 1,2,3,4
