/* ****************************************************************************
 * $Revision: 53782 $:
 * $Author: nasrullah.dusenmahamad $:
 * $Date: 2016-03-31 18:00:16 +0700 (Tue, 22 Mar 2016) $:
 * $HeadURL: $:
 * $Id: Manage Applications Core Value Sets - Manage Applications Core Value Sets.sql 53782 2016-03-22 11:00:16Z nasrullah.dusenmahamad $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT TaxTLEO.TAX_REGIME_CODE RES_TAX_REGIME_CODE
,ZFPOMV.PARTY_NAME RES_CONFIGURATION_OWNER
,TaxTLEO.TAX RES_TAX
,TaxTLEO.TAX_FULL_NAME RES_TAX_NAME
,POSLOOKUP.MEANING RES_PLACE_OF_SUPPLY
,DECODE(TaxTLEO.APPLICABLE_BY_DEFAULT_FLAG,'Y','Applicable','N','Not Applicable','') RES_TAX_APPLICABILITY
,REGLOOKUP.MEANING RES_TAX_REGISTRATION
,TaxTLEO.DEF_TAXABLE_BASIS_FORMULA RES_TAXABLE_BASIS_FORMULA
,TaxTLEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,TaxTLEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,TaxTLEO.CREATED_BY RSC_CREATED_BY
,TaxTLEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(CASE 
	WHEN ZFPOMV.PARTY_TYPE_CODE = 'OU' THEN	
		ZFPOMV.BU_ID
	ELSE
		NULL
	END) RSC_BUSINESS_UNIT_ID
,(CASE 
	WHEN ZFPOMV.PARTY_TYPE_CODE = 'FIRST_PARTY' THEN	
		ZFPOMV.LEGAL_ENTITY_ID
	ELSE
		NULL
	END) RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM ZX_TAXES_VL TaxTLEO
,ZX_FIRST_PARTY_ORGS_MOAC_V ZFPOMV
,ZX_REGIMES_VL RegimeTLEO
,FND_LOOKUPS POSLOOKUP
,FND_LOOKUPS REGLOOKUP
WHERE ZFPOMV.PARTY_TAX_PROFILE_ID = TaxTLEO.CONTENT_OWNER_ID
AND RegimeTLEO.TAX_REGIME_CODE    = TaxTLEO.TAX_REGIME_CODE
AND POSLOOKUP.LOOKUP_TYPE(+) = 'ZX_PLACE_OF_SUPPLY_TYPE'
AND TRUNC(SYSDATE) BETWEEN POSLOOKUP.START_DATE_ACTIVE(+) AND NVL(POSLOOKUP.END_DATE_ACTIVE(+),TRUNC(SYSDATE))
AND NVL(POSLOOKUP.ENABLED_FLAG(+),'N') = 'Y'
AND POSLOOKUP.LOOKUP_CODE(+)           = TaxTLEO.DEF_PLACE_OF_SUPPLY_TYPE_CODE
AND REGLOOKUP.LOOKUP_TYPE(+)           = 'ZX_REGISTRATION_CQ'
AND TRUNC(SYSDATE) BETWEEN REGLOOKUP.START_DATE_ACTIVE(+) AND NVL(REGLOOKUP.END_DATE_ACTIVE(+),TRUNC(SYSDATE))
AND NVL(REGLOOKUP.ENABLED_FLAG(+),'N')   = 'Y'
AND REGLOOKUP.LOOKUP_CODE(+)             = TaxTLEO.DEF_REGISTR_PARTY_TYPE_CODE
AND NVL(RegimeTLEO.REGIME_TYPE_FLAG,'I') <> 'I'