/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Resource%20Pools%20-%20Resource%20Pools.sql $:
 * $Id: Manage Resource Pools - Resource Pools.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT (SELECT NAME FROM PJR_RESOURCE_POOLS_VL
	WHERE POOL_ID = pjrREPOOLSEO.PARENT_POOL_ID ) RES_PARENT_RESOURCE_POOLS
,pjrREPOOLSEO.NAME RES_RESOURCE_POOLS
,(SELECT DISPLAY_NAME FROM PJT_PRJ_ENTERPRISE_RESOURCE_VL WHERE RESOURCE_ID = pjrREPOOLSEO.RESOURCE_ID)
	RES_POOL_OWNER
,pjrREPOOLSEO.DESCRIPTION RES_DESCRIPTION

,pjrREPOOLSEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,pjrREPOOLSEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,pjrREPOOLSEO.CREATED_BY  RSC_CREATED_BY
,pjrREPOOLSEO.CREATION_DATE  RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJR_RESOURCE_POOLS_VL pjrREPOOLSEO
WHERE SYSDATE BETWEEN pjrREPOOLSEO.FROM_DATE AND NVL(pjrREPOOLSEO.TO_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
START WITH pjrREPOOLSEO.PARENT_POOL_ID is null
CONNECT BY PRIOR pjrREPOOLSEO.POOL_ID = pjrREPOOLSEO.PARENT_POOL_ID
ORDER BY LEVEL,2
