/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=QP_CUST_PRICING_PROFILES

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=667##RES##QP_CUST_PRICING_PROFILES_FLEX
-- DFF_ATTRIBUTES=ATTRIBUTE_CHAR,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.

SELECT (SELECT PARTY_NAME
	FROM HZ_PARTIES
	WHERE PARTY_ID = QpCustomerProfilesE0.CUSTOMER_PARTY_ID
	) RES_CUSTOMER_NAME
,TO_CHAR(QpCustomerProfilesE0.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,QpCustomerProfilesE0.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,QpCustomerProfilesE0.ATTRIBUTE_CHAR1
,QpCustomerProfilesE0.ATTRIBUTE_CHAR2
,QpCustomerProfilesE0.ATTRIBUTE_CHAR3
,QpCustomerProfilesE0.ATTRIBUTE_CHAR4
,QpCustomerProfilesE0.ATTRIBUTE_CHAR5
,QpCustomerProfilesE0.ATTRIBUTE_CHAR6
,QpCustomerProfilesE0.ATTRIBUTE_CHAR7
,QpCustomerProfilesE0.ATTRIBUTE_CHAR8
,QpCustomerProfilesE0.ATTRIBUTE_CHAR9
,QpCustomerProfilesE0.ATTRIBUTE_CHAR10
,QpCustomerProfilesE0.ATTRIBUTE_CHAR11
,QpCustomerProfilesE0.ATTRIBUTE_CHAR12
,QpCustomerProfilesE0.ATTRIBUTE_CHAR13
,QpCustomerProfilesE0.ATTRIBUTE_CHAR14
,QpCustomerProfilesE0.ATTRIBUTE_CHAR15
,QpCustomerProfilesE0.ATTRIBUTE_CHAR16
,QpCustomerProfilesE0.ATTRIBUTE_CHAR17
,QpCustomerProfilesE0.ATTRIBUTE_CHAR18
,QpCustomerProfilesE0.ATTRIBUTE_CHAR19
,QpCustomerProfilesE0.ATTRIBUTE_CHAR20
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER1
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER2
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER3
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER4
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER5
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER6
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER7
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER8
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER9
,QpCustomerProfilesE0.ATTRIBUTE_NUMBER10
,TO_CHAR(QpCustomerProfilesE0.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(QpCustomerProfilesE0.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(QpCustomerProfilesE0.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(QpCustomerProfilesE0.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(QpCustomerProfilesE0.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP1
,QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP2
,QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP3
,QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP4
,QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP5
,QpCustomerProfilesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,QpCustomerProfilesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,QpCustomerProfilesE0.CREATED_BY RSC_CREATED_BY
,QpCustomerProfilesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM QP_CUST_PRICING_PROFILES QpCustomerProfilesE0
WHERE (QpCustomerProfilesE0.ATTRIBUTE_CATEGORY IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR1 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR2 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR3 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR4 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR5 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR6 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR7 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR8 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR9 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR10 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR11 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR12 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR13 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR14 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR15 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR16 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR17 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR18 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR19 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_CHAR20 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER1 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER2 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER3 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER4 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER5 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER6 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER7 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER8 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER9 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_NUMBER10 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_DATE1 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_DATE2 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_DATE3 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_DATE4 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_DATE5 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP1 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP2 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP3 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP4 IS NOT NULL
OR QpCustomerProfilesE0.ATTRIBUTE_TIMESTAMP5 IS NOT NULL)
ORDER BY 1