
/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=HWM_TCATS_VL

SELECT jobReqTemplatesE0.NAME RES_NAME
,jobReqTemplatesE0.REQUISITION_NUMBER RES_CODE
,questionsE0.QUESTION_CODE RES_QUESTION_CODE
,(SELECT NAME
    FROM HRQ_SUBSCRIBERS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND SUBSCRIBER_ID = questionsE0.SUBSCRIBER_ID 
	) RES_SUBSCRIBER
,questionsE0.QSTN_VERSION_NUM RES_QUESTION_VERSION_NUMBER
,(SELECT DISPLAY_NAME
    FROM PER_PERSON_NAMES_F
    WHERE NAME_TYPE = 'GLOBAL'
    AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    AND PERSON_ID = questionsE0.OWNER
    ) RES_OWNER
,(SELECT NAME
    FROM HRQ_CATEGORIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CATEGORY_ID = questionsE0.CATEGORY_ID
    ) RES_FOLDER
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRQ_PRIVACY'
    AND LOOKUP_CODE = questionsE0.PRIVACY_FLAG
    ) RES_PRIVACY
,questionsE0.QUESTION_TEXT RES_QUESTION_TEXT
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRQ_QUESTION_TYPE'
    AND LOOKUP_CODE = questionsE0.QUESTION_TYPE 
	) RES_QUESTION_TYPE
,DECODE(questionsE0.CONDITION_DISPLAY,'Y','Yes','No') RES_DISPLAY_THE_QUESTION_CONDI
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HRQ_QSTN_CLASSIFICATION'
    AND LOOKUP_CODE = questionsE0.CLASSIFICATION_CODE 
	) RES_QUESTION_CLASSIFICATION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HRQ_CANDIDATE_TYPE'
    AND LOOKUP_CODE = questionsE0.CANDIDATE_CODE 
	) RES_CANDIDATE_TYPES
,(SELECT NAME
    FROM HRQ_RESPONSE_TYPES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND RESPONSE_TYPE_ID = NVL(qstnrQuestionsE0.RESPONSE_TYPE_ID,questionsE0.RESPONSE_TYPE_ID)
    ) RES_RESPONSE_TYPE
,DECODE(questionsE0.ATTACHMENT_ALLOWED,'Y','Yes','No') RES_ALLOW_ATTACHMENTS
,questionsE0.MIN_LENGTH RES_MINIMUM_LENGTH
,questionsE0.MAX_LENGTH RES_MAXIMUM_LENGTH
,DECODE(qstnrQuestionsE0.MANDATORY,'Y','Yes','No') RES_REQUIRED

,'' RES_RECRUITING_ORGANIZATIONS_N
,'' RES_RECRUITING_LOCATIONS_NAME
,'' RES_JOB_FAMILIES_NAME
,'' RES_JOB_FUNCTIONS_NAME

,jobReqTemplatesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,jobReqTemplatesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,jobReqTemplatesE0.CREATED_BY RSC_CREATED_BY
,jobReqTemplatesE0.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM IRC_REQUISITIONS_VL jobReqTemplatesE0
,(SELECT *
    FROM IRC_IM_REQ_QSTNRS
    WHERE QSTNR_TYPE_CODE = 'ORA_INTERNAL_APPLYFLOW_QSTNR'
    ) QuestionairesE0
,HRQ_QSTNR_SECTIONS_B qstnrSectionsE0
,HRQ_QSTNR_QUESTIONS qstnrQuestionsE0
,HRQ_QUESTIONS_VL questionsE0
WHERE jobReqTemplatesE0.REQ_USAGE_CODE = 'ORA_TEMPLATE'

AND jobReqTemplatesE0.REQUISITION_ID = QuestionairesE0.REQUISITION_ID
AND QuestionairesE0.QUESTIONNAIRE_ID = qstnrSectionsE0.QUESTIONNAIRE_ID
AND qstnrSectionsE0.QSTNR_SECTION_ID = qstnrQuestionsE0.QSTNR_SECTION_ID
AND qstnrQuestionsE0.QUESTION_ID = questionsE0.QUESTION_ID
ORDER BY jobReqTemplatesE0.REQUISITION_NUMBER