/* ****************************************************************************
 * $Revision:  $:
 * $Author: nasrullah.dusenmahamad $:
 * $Date: 2017-04-26 $:
 * $HeadURL:  $:
 * $Id: Manage Account Aliases - Account Aliases - DFF.sql $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=WIS_WORK_AREAS_VL

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10494##RES##WIS_WORK_AREAS
-- DFF_ATTRIBUTES=ATTRIBUTE_CHAR,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

SELECT (SELECT ORGANIZATION_CODE 
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = WisWorkAreasE0.ORGANIZATION_ID
	) RES_ORGANIZATION
,WisWorkAreasE0.WORK_AREA_NAME RES_NAME
,WisWorkAreasE0.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,WisWorkAreasE0.ATTRIBUTE_CHAR1
,WisWorkAreasE0.ATTRIBUTE_CHAR2
,WisWorkAreasE0.ATTRIBUTE_CHAR3
,WisWorkAreasE0.ATTRIBUTE_CHAR4
,WisWorkAreasE0.ATTRIBUTE_CHAR5
,WisWorkAreasE0.ATTRIBUTE_CHAR6
,WisWorkAreasE0.ATTRIBUTE_CHAR7
,WisWorkAreasE0.ATTRIBUTE_CHAR8
,WisWorkAreasE0.ATTRIBUTE_CHAR9
,WisWorkAreasE0.ATTRIBUTE_CHAR10
,WisWorkAreasE0.ATTRIBUTE_CHAR11
,WisWorkAreasE0.ATTRIBUTE_CHAR12
,WisWorkAreasE0.ATTRIBUTE_CHAR13
,WisWorkAreasE0.ATTRIBUTE_CHAR14
,WisWorkAreasE0.ATTRIBUTE_CHAR15
,WisWorkAreasE0.ATTRIBUTE_CHAR16
,WisWorkAreasE0.ATTRIBUTE_CHAR17
,WisWorkAreasE0.ATTRIBUTE_CHAR18
,WisWorkAreasE0.ATTRIBUTE_CHAR19
,WisWorkAreasE0.ATTRIBUTE_CHAR20
,WisWorkAreasE0.ATTRIBUTE_NUMBER1
,WisWorkAreasE0.ATTRIBUTE_NUMBER2
,WisWorkAreasE0.ATTRIBUTE_NUMBER3
,WisWorkAreasE0.ATTRIBUTE_NUMBER4
,WisWorkAreasE0.ATTRIBUTE_NUMBER5
,WisWorkAreasE0.ATTRIBUTE_NUMBER6
,WisWorkAreasE0.ATTRIBUTE_NUMBER7
,WisWorkAreasE0.ATTRIBUTE_NUMBER8
,WisWorkAreasE0.ATTRIBUTE_NUMBER9
,WisWorkAreasE0.ATTRIBUTE_NUMBER10
,TO_CHAR(WisWorkAreasE0.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(WisWorkAreasE0.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(WisWorkAreasE0.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(WisWorkAreasE0.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(WisWorkAreasE0.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,WisWorkAreasE0.ATTRIBUTE_TIMESTAMP1
,WisWorkAreasE0.ATTRIBUTE_TIMESTAMP2
,WisWorkAreasE0.ATTRIBUTE_TIMESTAMP3
,WisWorkAreasE0.ATTRIBUTE_TIMESTAMP4
,WisWorkAreasE0.ATTRIBUTE_TIMESTAMP5
,WisWorkAreasE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,WisWorkAreasE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,WisWorkAreasE0.CREATED_BY RSC_CREATED_BY
,WisWorkAreasE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM WIS_WORK_AREAS_VL WisWorkAreasE0
WHERE (WisWorkAreasE0.ATTRIBUTE_CATEGORY IS NOT NULL OR
WisWorkAreasE0.ATTRIBUTE_CHAR1 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR2 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR3 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR4 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR5 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR6 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR7 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR8 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR9 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR10 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR11 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR12 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR13 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR14 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR15 IS NOT NULL OR
WisWorkAreasE0.ATTRIBUTE_CHAR16 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR17 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR18 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR19 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_CHAR20 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_DATE1 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_DATE2 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_DATE3 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_DATE4 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_DATE5 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_TIMESTAMP1 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_TIMESTAMP2 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_TIMESTAMP3 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_TIMESTAMP4 IS NOT NULL OR 
WisWorkAreasE0.ATTRIBUTE_TIMESTAMP5 IS NOT NULL)
ORDER BY RES_ORGANIZATION
,WisWorkAreasE0.WORK_AREA_NAME