 /* ****************************************************************************
 * $Revision: 48884 $:
 * $Author: dhara.pithadiya $:
 * $Date: 2015-08-18 14:24:02 +0700 (Tue, 18 Aug 2015) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Transaction%20Types%20-%20Manage%20Transaction%20Types.sql $:
 * $Id: Manage Transaction Types - Manage Transaction Types.sql 48884 2015-08-18 07:24:02Z dhara.pithadiya $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=ASE_APP_ROLE_VL
-- NO_REMOVE_COMMENTS

WITH DATASEC AS (SELECT /*+ PARALLEL(8) */ ACTION_ID
	,ROLE_CODE
	,POLICY_NAME
	,DB_RESOURCE
	,POLICY_TYPE
	,DS_VALUE1
	,DS_VALUE2
	,DS_VALUE3
	,DS_VALUE4
	,DS_VALUE5
	,DS_VALUE6
	,DS_VALUE7
	,DS_VALUE_SET
	,START_DATE
	,END_DATE
	,DESCRIPTION
	,ROW_NUMBER() OVER(PARTITION BY ROLE_CODE,POLICY_NAME,DB_RESOURCE ORDER BY ROLE_CODE,POLICY_NAME,ACTION_ID,DB_RESOURCE DESC) R1
	FROM (SELECT /*+ PARALLEL(8) */ ActionsE0.ACTION_ID
	,ActionsE0.ATTRIBUTE_VALUE_TEXT ROLE_CODE
	,POLICY_NAME.ATTR_VALUE POLICY_NAME
	,DB_RESOURCE.ATTR_VALUE DB_RESOURCE
	,POLICY_TYPE.ATTR_VALUE POLICY_TYPE
	,DS_VALUE1.ATTR_VALUE DS_VALUE1
	,DS_VALUE2.ATTR_VALUE DS_VALUE2
	,DS_VALUE3.ATTR_VALUE DS_VALUE3
	,DS_VALUE4.ATTR_VALUE DS_VALUE4
	,DS_VALUE5.ATTR_VALUE DS_VALUE5
	,DS_VALUE6.ATTR_VALUE DS_VALUE6
	,DS_VALUE7.ATTR_VALUE DS_VALUE7
	,DS_VALUE_SET.ATTR_VALUE DS_VALUE_SET
	,START_DATE.ATTR_VALUE START_DATE
	,END_DATE.ATTR_VALUE END_DATE
	,DESCRIPTION.ATTR_VALUE DESCRIPTION
	FROM ASE_STAGED_ACTION_VALUE ActionsE0
	,(SELECT ActionsE1.ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'DISPLAY_NAME'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) POLICY_NAME
	,(SELECT ATTRIBUTE_VALUE_NUMBER ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'OBJECT_ID'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.Long'
		) DB_RESOURCE
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'POLICY_TYPE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) POLICY_TYPE
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'INSTANCE_PK_1_VALUE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) DS_VALUE1
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'INSTANCE_PK_2_VALUE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) DS_VALUE2
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'INSTANCE_PK_3_VALUE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) DS_VALUE3
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'INSTANCE_PK_4_VALUE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) DS_VALUE4
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'INSTANCE_PK_5_VALUE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) DS_VALUE5
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'INSTANCE_PK_6_VALUE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) DS_VALUE6
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'INSTANCE_PK_7_VALUE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) DS_VALUE7
	,(SELECT ATTRIBUTE_VALUE_NUMBER ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'INSTANCE_SET_ID'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.Long'
		) DS_VALUE_SET
	,(SELECT TO_CHAR(ActionsE1.ATTRIBUTE_VALUE_TIMESTAMP,'DD-Mon-YYYY') ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'START_DATE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.sql.Timestamp'
		) START_DATE
	,(SELECT TO_CHAR(ActionsE1.ATTRIBUTE_VALUE_TIMESTAMP,'DD-Mon-YYYY') ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'END_DATE'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.sql.Timestamp'
		) END_DATE
	,(SELECT ATTRIBUTE_VALUE_TEXT ATTR_VALUE
		,ActionsE1.ACTION_ID
		FROM ASE_STAGED_ACTION_VALUE ActionsE1
		WHERE ActionsE1.ATTRIBUTE_NAME = 'DESCRIPTION'
		AND ActionsE1.ATTRIBUTE_TYPE = 'java.lang.String'
		) DESCRIPTION
	WHERE ActionsE0.ACTION_ID NOT IN (SELECT ACTION_ID FROM ASE_STAGED_ACTION WHERE ACTION_TYPE = 'DATA_SECURITY_POLICY' AND ACTION_NAME LIKE 'D%')
	AND ActionsE0.ATTRIBUTE_NAME = 'ROLE_NAME'
	AND ActionsE0.ATTRIBUTE_TYPE = 'java.lang.String'
	AND ActionsE0.ACTION_ID = POLICY_NAME.ACTION_ID
	AND ActionsE0.ACTION_ID = DB_RESOURCE.ACTION_ID
	AND ActionsE0.ACTION_ID = POLICY_TYPE.ACTION_ID
	AND ActionsE0.ACTION_ID = START_DATE.ACTION_ID
	AND ActionsE0.ACTION_ID = END_DATE.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DESCRIPTION.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DS_VALUE1.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DS_VALUE2.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DS_VALUE3.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DS_VALUE4.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DS_VALUE5.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DS_VALUE6.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DS_VALUE7.ACTION_ID(+)
	AND ActionsE0.ACTION_ID = DS_VALUE_SET.ACTION_ID(+))
	WHERE POLICY_NAME IS NOT NULL
	)

SELECT DISTINCT DutyRolesE0.ROLE_NAME RES_ROLE_NAME
,DutyRolesE0.CODE RES_ROLE_CODE
,DATASEC1.POLICY_NAME RES_POLICY_NAME
,(SELECT DISPLAY_NAME 
	FROM FND_OBJECTS_TL
	WHERE OBJECT_ID = DATASEC1.DB_RESOURCE
	AND LANGUAGE = USERENV('LANG')
	) RES_DATABASE_RESOURCE
,DATASEC1.START_DATE RES_START_DATE
,DATASEC1.END_DATE RES_END_DATE
,DATASEC1.DESCRIPTION RES_POLICY_DESCRIPTION
,DECODE(DATASEC1.POLICY_TYPE,'GLOBAL','All values','INSTANCE','Select by key','SET','Select by instance set') RES_DATA_SET
,(CASE
	WHEN DATASEC1.POLICY_TYPE = 'INSTANCE' THEN
		DATASEC1.DS_VALUE1
	WHEN DATASEC1.POLICY_TYPE = 'SET' THEN
		(SELECT DISPLAY_NAME
			FROM FND_OBJECT_INSTANCE_SETS_TL
			WHERE INSTANCE_SET_ID = DATASEC1.DS_VALUE_SET
			AND LANGUAGE = USERENV('LANG'))
	END) RES_PRIMARY_KEY_VALUE1
,DECODE(DATASEC1.DS_VALUE2,'*NULL*',NULL,DATASEC1.DS_VALUE2) RES_PRIMARY_KEY_VALUE2
,DECODE(DATASEC1.DS_VALUE3,'*NULL*',NULL,DATASEC1.DS_VALUE3) RES_PRIMARY_KEY_VALUE3
,DECODE(DATASEC1.DS_VALUE4,'*NULL*',NULL,DATASEC1.DS_VALUE4) RES_PRIMARY_KEY_VALUE4
,DECODE(DATASEC1.DS_VALUE5,'*NULL*',NULL,DATASEC1.DS_VALUE5) RES_PRIMARY_KEY_VALUE5
,DECODE(DATASEC1.DS_VALUE6,'*NULL*',NULL,DATASEC1.DS_VALUE6) RES_PRIMARY_KEY_VALUE6
,DECODE(DATASEC1.DS_VALUE7,'*NULL*',NULL,DATASEC1.DS_VALUE7) RES_PRIMARY_KEY_VALUE7
,DutyRolesE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,DutyRolesE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,DutyRolesE0.CREATED_BY  RSC_CREATED_BY
,DutyRolesE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM ASE_ROLE_VL DutyRolesE0
,(SELECT DATASEC.*
	FROM DATASEC
	--WHERE DATASEC.R1 = 1
	) DATASEC1
WHERE DutyRolesE0.CODE = DATASEC1.ROLE_CODE
AND SYSDATE BETWEEN DutyRolesE0.EFFECTIVE_START_DATE AND NVL(DutyRolesE0.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
ORDER BY DutyRolesE0.ROLE_NAME

/*NOTE!
	The table 'ASE_STAGED_ACTION_VALUE' has stored data as history record which everytime that we create,update or delete record,
	it's increasing the record without anything that I can relate back to the previous record.
	The key that I use to define the data is 'ROLE_CODE' and 'POLICY_NAME' which Policy name can be change and I cannot trace it back.
	Due to situaton above this query cannot be able to get all data corectly in case of user have changed the ploicy name.
	

*/