/* ****************************************************************************
 * $Revision$:
 * $Author$:
 * $Date$:
 * $HeadURL$:
 * $Id$:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

--RSC_PREREQUISITE_OBJECTS=XCC_SYSTEM_OPTIONS

SELECT (SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccSYSTEMOPE0.SYSTEM_OPTION_CODE
			AND LOOKUP_TYPE = 'ORA_XCC_SYSTEM_OPTIONS' AND LANGUAGE = USERENV('LANG')) RES_FEATURE
,(SELECT DESCRIPTION FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = xccSYSTEMOPE0.SYSTEM_OPTION_CODE
			AND LOOKUP_TYPE = 'ORA_XCC_SYSTEM_OPTIONS' AND LANGUAGE = USERENV('LANG')) RES_DESCRIPTION
,DECODE(xccSYSTEMOPE0.SYSTEM_OPTION_VALUE,'Y','Yes','No') RES_ENABLE
,xccSYSTEMOPE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,xccSYSTEMOPE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,xccSYSTEMOPE0.CREATED_BY  RSC_CREATED_BY
,xccSYSTEMOPE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
   
FROM XCC_SYSTEM_OPTIONS xccSYSTEMOPE0
ORDER BY 1