/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
WITH nameFORMAT AS 
(
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,1),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,1)) AS tmpFORMAT,1 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,2),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,2)) AS tmpFORMAT,2 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,3),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,3)) AS tmpFORMAT,3 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,4),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,4)) AS tmpFORMAT,4 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,5),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,5)) AS tmpFORMAT,5 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,6),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,6)) AS tmpFORMAT,6 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,7),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,7)) AS tmpFORMAT,7 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,8),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,8)) AS tmpFORMAT,8 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,9),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,9)) AS tmpFORMAT,9 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,10),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,10)) AS tmpFORMAT,10 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,11),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,11)) AS tmpFORMAT,11 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,12),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,12)) AS tmpFORMAT,12 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,13),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,13)) AS tmpFORMAT,13 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,14),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,14)) AS tmpFORMAT,14 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,15),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,15)) AS tmpFORMAT,15 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,16),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,16)) AS tmpFORMAT,16 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,17),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,17)) AS tmpFORMAT,17 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,18),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,18)) AS tmpFORMAT,18 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,19),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,19)) AS tmpFORMAT,19 AS SEQ
	FROM HR_NAME_FORMATS
	UNION
	SELECT NAME_FORMAT_ID,DECODE(REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,20),'||','|',REGEXP_SUBSTR(FORMAT_MASK,'[^$]+',1,20)) AS tmpFORMAT,20 AS SEQ
	FROM HR_NAME_FORMATS
)
 

SELECT (SELECT TERRITORY_SHORT_NAME
    FROM FND_TERRITORIES_VL
    WHERE TERRITORY_CODE = nameFormatsE0.LEGISLATION_CODE
    ) RES_COUNTRY
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'PER_NAME_FORMATS'
    AND LOOKUP_CODE = nameFormatsE0.FORMAT_NAME
    ) RES_FORMAT_TYPE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'NAME_TYPE'
    AND LOOKUP_CODE = nameFormatsE0.USER_FORMAT_CHOICE
    ) RES_SCOPE	
,nameFORMAT.SEQ RES_SEQUENCE_COMPONENT
,(CASE WHEN nameFORMAT.tmpFORMAT = '|' 
	THEN '----------'
	WHEN nameFORMAT.tmpFORMAT IN (SELECT LOOKUP_CODE FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE = 'PER_NAME_SUB_FORMAT_COMPONENTS' AND LANGUAGE = USERENV('LANG')
							AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	THEN (SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = nameFORMAT.tmpFORMAT 
			AND LOOKUP_TYPE = 'PER_NAME_SUB_FORMAT_COMPONENTS' AND LANGUAGE = USERENV('LANG')
			AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD')))	
	ELSE (SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = nameFORMAT.tmpFORMAT 
			AND LOOKUP_TYPE = 'PER_NAME_FORMAT_COMPONENTS' AND LANGUAGE = USERENV('LANG')
			AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))) END)RES_SELECTED_COMPONENT
,nameFormatsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,nameFormatsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,nameFormatsE0.CREATED_BY RSC_CREATED_BY
,nameFormatsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,nameFormatsE0.LEGISLATION_CODE RSC_COUNTRY_ID

FROM HR_NAME_FORMATS nameFormatsE0
,nameFORMAT
WHERE nameFormatsE0.NAME_FORMAT_ID = nameFORMAT.NAME_FORMAT_ID
AND nameFORMAT.tmpFORMAT IS NOT NULL 



ORDER BY RES_COUNTRY NULLS FIRST,RES_FORMAT_TYPE,RES_SCOPE,nameFORMAT.SEQ