/* ****************************************************************************
 * $Revision:  $:
 * $Author: nasrullah Dusenmahamad $:
 * $Date: 2018-01-16 $:
 * $HeadURL:  $:
 * $Id: Manage Users - Expense Information.sql  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- FIELD_TO_APPLY_FUNCTION=RES_DEFAULT_EXPENSE_ACCOUNT/GET_CODE_COMBINATION

select Distinct PERSONNAMEDEO.LAST_NAME 				RES_LAST_NAME
,PERSONNAMEDEO.FIRST_NAME 								RES_FIRST_NAME
,EMAILADDRESSEO.EMAIL_ADDRESS 							RES_E_MAIL
,USERDETAILEO.MULTITENANCY_USERNAME 					RES_USER_NAME
,EMPLOYEEASSIGNMENTDEO.DEFAULT_CODE_COMB_ID 			RES_DEFAULT_EXPENSE_ACCOUNT
,(select meaning 
 from fnd_lookups 
 where lookup_type = 'IBY_ADDRESS_TYPES'
 and lookup_code = EMPLOYEEASSIGNMENTDEO.EXPENSE_CHECK_ADDRESS  )                	RES_EXPENSE_CHECK_SEND_TO_ADDR
,PERSONNAMEDEO.LAST_UPDATED_BY  	RSC_LAST_UPDATED_BY
,PERSONNAMEDEO.LAST_UPDATE_DATE  	RSC_LAST_UPDATE_DATE
,PERSONNAMEDEO.CREATED_BY  			RSC_CREATED_BY
,PERSONNAMEDEO.CREATION_DATE  		RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,BusinessUnitPEO.BU_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PER_PERSON_NAMES_F PERSONNAMEDEO
,PER_EMAIL_ADDRESSES EMAILADDRESSEO
,PER_USERS USERDETAILEO
,PER_ALL_ASSIGNMENTS_M EMPLOYEEASSIGNMENTDEO
,FUN_ALL_BUSINESS_UNITS_V BusinessUnitPEO
WHERE PERSONNAMEDEO.PERSON_ID  		= EMAILADDRESSEO.PERSON_ID(+)
and PERSONNAMEDEO.PERSON_ID         = USERDETAILEO.PERSON_ID(+)
and PERSONNAMEDEO.PERSON_ID 		= EMPLOYEEASSIGNMENTDEO.PERSON_ID(+)
and EMPLOYEEASSIGNMENTDEO.PRIMARY_FLAG            = 'Y'
and PERSONNAMEDEO.NAME_TYPE         = 'GLOBAL'
AND EMPLOYEEASSIGNMENTDEO.BUSINESS_UNIT_ID   = BusinessUnitPEO.BU_ID(+)
AND(sysdate BETWEEN PERSONNAMEDEO.EFFECTIVE_START_DATE AND PERSONNAMEDEO.EFFECTIVE_END_DATE) 
AND(sysdate BETWEEN EMPLOYEEASSIGNMENTDEO.EFFECTIVE_START_DATE AND EMPLOYEEASSIGNMENTDEO.EFFECTIVE_END_DATE)
and(EMPLOYEEASSIGNMENTDEO.EFFECTIVE_LATEST_CHANGE = 'Y')
AND EMPLOYEEASSIGNMENTDEO.ASSIGNMENT_STATUS_TYPE = 'ACTIVE'
Order by PERSONNAMEDEO.LAST_NAME,PERSONNAMEDEO.FIRST_NAME

