/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=MSC_MEASURES_VL
 
SELECT MeasuresE0.NAME RES_MEASURE
,DECODE(MeasuresE0.STORE_RESULT,'1','Yes','No') RES_REFRESH_WITH_CURRENT_DATA
,DECODE(MeasuresE0.SHARED_FLAG,'1','Yes','No') RES_SHARED_MEASURE
,MeasuresE0.DECIMAL_PLACES RES_DECIMAL_PLACES
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = MeasuresE0.BASE_UOM_CODE
	) RES_BASE_UNIT_OF_MEASURE
,REPLACE(MeasuresE0.GRAPH_COLOR,'#','') RES_GRAPH_COLOR
,(SELECT NAME 
	FROM FND_CURRENCIES_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND CURRENCY_CODE = MeasuresE0.BASE_CURRENCY_CODE
	) RES_BASE_CURRENCY
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'MSC_MEASURE_SOURCE_TYPE'
	AND LOOKUP_CODE = MeasuresE0.SOURCE_TYPE
	) RES_SOURCE
,(SELECT NAME
	FROM MSC_LEVELS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND LEVEL_ID = MeasuresE0.SOURCE_LEVEL_ID
	) RES_LEVEL
,(SELECT ATTRIBUTE_NAME
	FROM MSC_LEVEL_ATTRIBUTES_VL
	WHERE ATTRIBUTE_ID = MeasuresE0.SOURCE_ATTRIBUTE_ID
	) RES_ATTRIBUTE
,MeasuresE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,MeasuresE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,MeasuresE0.CREATED_BY  RSC_CREATED_BY
,MeasuresE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM MSC_MEASURES_VL MeasuresE0
WHERE (MeasuresE0.STORE_RESULT IS NOT NULL
OR MeasuresE0.SHARED_FLAG IS NOT NULL
OR MeasuresE0.DECIMAL_PLACES IS NOT NULL
OR MeasuresE0.BASE_UOM_CODE IS NOT NULL
OR MeasuresE0.BASE_CURRENCY_CODE IS NOT NULL
OR MeasuresE0.SOURCE_TYPE IS NOT NULL
OR MeasuresE0.SOURCE_LEVEL_ID IS NOT NULL
OR MeasuresE0.SOURCE_ATTRIBUTE_ID IS NOT NULL)
ORDER BY 1