/* ****************************************************************************
 * $Revision: 50638 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2015-11-18 14:55:09 +0700 (Wed, 18 Nov 2015) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Cumulative%20Mileage%20Determinants%20-%20Manage%20Cumulative%20Mileage%20Determinants.sql $:
 * $Id: Manage Cumulative Mileage Determinants - Manage Cumulative Mileage Determinants.sql 50638 2015-11-18 07:55:09Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=140##RES##FA_CONVENTION_TYPES
-- DFF_ATTRIBUTES=ATTRIBUTE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

SELECT ProrateConventionTypeEO.PRORATE_CONVENTION_CODE RES_NAME
,SETIDSETSEO.SET_NAME RES_REFERENCE_DATA_SET
,PRORATECONVENTIONTYPEEO.ATTRIBUTE_CATEGORY_CODE RES_CONTEXT_CODE
,PRORATECONVENTIONTYPEEO.ATTRIBUTE1 
,PRORATECONVENTIONTYPEEO.ATTRIBUTE2
,PRORATECONVENTIONTYPEEO.ATTRIBUTE3
,PRORATECONVENTIONTYPEEO.ATTRIBUTE4
,PRORATECONVENTIONTYPEEO.ATTRIBUTE5
,PRORATECONVENTIONTYPEEO.ATTRIBUTE6
,PRORATECONVENTIONTYPEEO.ATTRIBUTE7
,PRORATECONVENTIONTYPEEO.ATTRIBUTE8
,PRORATECONVENTIONTYPEEO.ATTRIBUTE9
,PRORATECONVENTIONTYPEEO.ATTRIBUTE10
,PRORATECONVENTIONTYPEEO.ATTRIBUTE11
,PRORATECONVENTIONTYPEEO.ATTRIBUTE12
,PRORATECONVENTIONTYPEEO.ATTRIBUTE13
,PRORATECONVENTIONTYPEEO.ATTRIBUTE14
,PRORATECONVENTIONTYPEEO.ATTRIBUTE15
,PRORATECONVENTIONTYPEEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,PRORATECONVENTIONTYPEEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
,PRORATECONVENTIONTYPEEO.CREATED_BY RSC_CREATED_BY
,PRORATECONVENTIONTYPEEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FA_CONVENTION_TYPES PRORATECONVENTIONTYPEEO
,FND_SETID_SETS_VL SETIDSETSEO
WHERE PRORATECONVENTIONTYPEEO.SET_ID = SETIDSETSEO.SET_ID(+)
AND (PRORATECONVENTIONTYPEEO.ATTRIBUTE_CATEGORY_CODE IS NOT NULL OR
PRORATECONVENTIONTYPEEO.ATTRIBUTE1 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE2 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE3 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE4 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE5 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE6 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE7 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE8 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE9 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE10 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE11 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE12 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE13 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE14 IS NOT NULL OR 
PRORATECONVENTIONTYPEEO.ATTRIBUTE15 IS NOT NULL)
ORDER BY ProrateConventionTypeEO.PRORATE_CONVENTION_CODE
,ProrateConventionTypeEO.FISCAL_YEAR_NAME