/* ****************************************************************************
* $Revision: 80381 $:
* $Author: tanawat.wongjan $:
* $Date: 2023-03-02 16:23:01 +0700 (Thu, 02 Mar 2023) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Financial%20Plan%20Types%20-%20Plan%20Settings.sql $:
* $Id: Manage Financial Plan Types - Plan Settings.sql 80381 2023-03-02 09:23:01Z tanawat.wongjan $:
* ****************************************************************************
* Description:
* ************************************************************************** */

SELECT 	pjoPlanTypeEO.NAME							RES_NAME
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' AND pjoPlanTypeEO.PLAN_OPTION_CODE != 'COST_AND_REV_TOGETHER'
		THEN	DECODE(pjoFinPlanAMTEO.COST_QTY_FLAG,'Y','Yes','No') 
		END)	RES_COST_QUANTITY
,(CASE
	WHEN pjoPlanTypeEO.PLAN_OPTION_CODE = 'COST_AND_REV_TOGETHER'
		THEN	DECODE(pjoFinPlanAMTEO.ALL_QTY_FLAG,'Y','Yes','No') 
		END)	RES_QUANTITY
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' 
		THEN	DECODE(pjoFinPlanAMTEO.RAW_COST_FLAG,'Y','Yes','No')
		END	) RES_RAW_COST
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' 
		THEN	DECODE(pjoFinPlanAMTEO.BRDND_COST_FLAG,'Y','Yes','No') 
		END)	RES_BURDENED_COST
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' 
		THEN	DECODE(pjoFinPlanAMTEO.COST_RATE_FLAG,'Y','Yes','No') 
		END)	RES_RAW_COST_RATE
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' 
		THEN	DECODE(pjoFinPlanAMTEO.BRDND_RATE_FLAG,'Y','Yes','No')
		END)	RES_BURDENED_COST_RATE
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' 
		THEN	(SELECT MEANING FROM FND_LOOKUPS
					WHERE LOOKUP_CODE = pjoPlanOptionEO.PLAN_LEVEL_CODE
						AND LOOKUP_TYPE = 'PJO_PLAN_LEVEL_CODE') 
						END) RES_PLANNING_LEVEL	
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' 
		THEN	(SELECT MEANING FROM FND_LOOKUPS
					WHERE LOOKUP_CODE = pjoPlanOptionEO.TIME_PHASED_CODE
						AND LOOKUP_TYPE = 'PJO_TIME_PHASED_TYPE') 
						END)	RES_CALENDAR_TYPE
,(CASE
	WHEN pjoPlanTypeEO.PLAN_OPTION_CODE = 'COST_AND_REV_TOGETHER'
		THEN	(SELECT MEANING FROM FND_LOOKUPS
					WHERE LOOKUP_CODE = pjoPlanOptionEO.NTP_RATE_DATE_TYPE
						AND LOOKUP_TYPE = 'PJO_RATE_DRV_DATE_TYPE')	
						END)	RES_RATE_DERIVATION_DATE_TYPE
,(CASE
	WHEN pjoPlanTypeEO.PLAN_OPTION_CODE = 'COST_AND_REV_TOGETHER'
		THEN	TO_CHAR(pjoPlanOptionEO.NTP_RATE_DATE,'DD-Mon-YYYY')	
		END)	RES_RATE_DERIVATION_DATE	
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' AND pjoPlanTypeEO.PLAN_OPTION_CODE != 'COST_AND_REV_TOGETHER'
		THEN	(SELECT MEANING FROM FND_LOOKUPS
					WHERE LOOKUP_CODE = pjoPlanOptionEO.NTP_RATE_DATE_TYPE
						AND LOOKUP_TYPE = 'PJO_RATE_DRV_DATE_TYPE') 
						END)	RES_COST_RATE_DERIVATION_DATE_
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' AND pjoPlanTypeEO.PLAN_OPTION_CODE != 'COST_AND_REV_TOGETHER'
		THEN	TO_CHAR(pjoPlanOptionEO.NTP_RATE_DATE,'DD-Mon-YYYY')	
		END) RES_COST_RATE_DERIVATION_DATE
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'REVENUE' 
		THEN	(SELECT NAME FROM PJO_PERIOD_PROFILES_VL
					WHERE PERIOD_PROFILE_ID = pjoPlanOptionEO.PERIOD_PROFILE_ID ) 
		END) RES_PERIOD_PROFILE
,(CASE WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'COST' OR  pjoPlanOptionEO.PLANNED_FOR_CODE = 'COST_AND_REV_TOGETHER'
		THEN	
			DECODE(pjoPlanOptionEO.MANUAL_SPREAD_FLAG,'Y','Yes','No') 
		END) RES_MAINTAIN_MANUAL_SPREAD_ON_
,(CASE WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'COST'
		THEN	
			DECODE(pjoPlanOptionEO.MAP_ACT_SUMMARY_FLAG,'Y','Yes','No') 
		END) RES_ASSOCIATE_PROJECT_COSTS_TO
,(CASE WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'COST_AND_REV_TOGETHER'
		THEN	
			DECODE(pjoPlanOptionEO.MAP_ACT_SUMMARY_FLAG,'Y','Yes','No') 
		END) RES_ASSOCIATE_PROJECT_COSTS_OR
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE'
		THEN	DECODE(pjoFinPlanAMTEO.REVENUE_QTY_FLAG,'Y','Yes','No') 
		END)	RES_REVENUE_QUANTITY
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE' OR pjoPlanTypeEO.PLAN_OPTION_CODE = 'COST_AND_REV_TOGETHER'
		THEN	DECODE(pjoFinPlanAMTEO.REVENUE_FLAG,'Y','Yes','No') 
		END) 	RES_REVENUE
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE != 'COST' 
		THEN	DECODE(pjoFinPlanAMTEO.BILL_RATE_FLAG,'Y','Yes','No') 
		END) 	RES_BILL_RATE
,(CASE
	WHEN pjoPlanTypeEO.PLAN_OPTION_CODE = 'COST_AND_REV_SEP'
		THEN	DECODE(pjoPlanOptionEO.USE_PLANNING_RATES_FLAG,'Y','Yes','No')	
		END)	RES_USE_COST_PLAN_OPTIONS_FOR_
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE' 
		THEN (SELECT MEANING FROM FND_LOOKUPS
				WHERE LOOKUP_CODE = pjoPlanOptionEO.PLAN_LEVEL_CODE
					AND LOOKUP_TYPE = 'PJO_PLAN_LEVEL_CODE')
		END)	RES_REVENUE_PLANNING_LEVEL
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE'
		THEN (SELECT MEANING FROM FND_LOOKUPS
				WHERE LOOKUP_CODE = pjoPlanOptionEO.TIME_PHASED_CODE
					AND LOOKUP_TYPE = 'PJO_TIME_PHASED_TYPE')
		END)	RES_REVENUE_CALENDAR_TYPE
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE' 
		THEN	(SELECT MEANING FROM FND_LOOKUPS
					WHERE LOOKUP_CODE = pjoPlanOptionEO.NTP_RATE_DATE_TYPE
						AND LOOKUP_TYPE = 'PJO_RATE_DRV_DATE_TYPE') 
						END)	RES_BILL_RATE_DERIVATION_DATE_
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE' 
		THEN	TO_CHAR(pjoPlanOptionEO.NTP_RATE_DATE,'DD-Mon-YYYY')	
		END) RES_BILL_RATE_DERIVATION_DATE
,(CASE
	WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE' 
		THEN	(SELECT NAME FROM PJO_PERIOD_PROFILES_VL
					WHERE PERIOD_PROFILE_ID = pjoPlanOptionEO.PERIOD_PROFILE_ID ) 
		END) 	RES_REVENUE_PERIOD_PROFILE
,(CASE WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE'
		THEN	
			DECODE(pjoPlanOptionEO.MANUAL_SPREAD_FLAG,'Y','Yes','No') 
		END) RES_REVENUE_MAINTAIN_MANUAL_SP
,(CASE WHEN pjoPlanOptionEO.PLANNED_FOR_CODE = 'REVENUE'
		THEN	
			DECODE(pjoPlanOptionEO.MAP_ACT_SUMMARY_FLAG,'Y','Yes','No') 
		END) RES_ASSOCIATE_PROJECT_REVENUE_

,pjoPlanTypeEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,pjoPlanTypeEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,pjoPlanTypeEO.CREATED_BY  RSC_CREATED_BY
,pjoPlanTypeEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJO_PLAN_TYPES_VL pjoPlanTypeEO
,PJO_PLANNING_OPTIONS pjoPlanOptionEO
,PJO_FIN_PLAN_AMT_SETS pjoFinPlanAMTEO
WHERE pjoPlanTypeEO.PLAN_TYPE_CODE = 'FINANCIAL_PLAN'
AND pjoPlanTypeEO.PLAN_TYPE_ID = pjoPlanOptionEO.PLAN_TYPE_ID
AND pjoPlanOptionEO.AMOUNT_SET_ID = pjoFinPlanAMTEO.FIN_PLAN_AMT_SET_ID
AND pjoPlanOptionEO.PLAN_OPTION_LEVEL_CODE = 'PLAN_TYPE'
AND pjoPlanOptionEO.PROJECT_ID = 0
AND pjoPlanTypeEO.PLAN_OPTION_CODE != 'COST_AND_REV_SEP'

UNION

SELECT 	pjoPlanTypeEO.NAME RES_NAME
,DECODE(pjoFinPlanAMTCostEO.COST_QTY_FLAG,'Y','Yes','No') RES_COST_QUANTITY
,(CASE
	WHEN pjoPlanTypeEO.PLAN_OPTION_CODE = 'COST_AND_REV_TOGETHER' THEN	
		DECODE(pjoFinPlanAMTCostEO.ALL_QTY_FLAG,'Y','Yes','No') 
	END) RES_QUANTITY
,DECODE(pjoFinPlanAMTCostEO.RAW_COST_FLAG,'Y','Yes','No') RES_RAW_COST
,DECODE(pjoFinPlanAMTCostEO.BRDND_COST_FLAG,'Y','Yes','No') RES_BURDENED_COST
,DECODE(pjoFinPlanAMTCostEO.COST_RATE_FLAG,'Y','Yes','No') RES_RAW_COST_RATE
,DECODE(pjoFinPlanAMTCostEO.BRDND_RATE_FLAG,'Y','Yes','No') RES_BURDENED_COST_RATE
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjoPlanOptionCostEO.PLAN_LEVEL_CODE
	AND LOOKUP_TYPE = 'PJO_PLAN_LEVEL_CODE'
	)  RES_PLANNING_LEVEL	
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjoPlanOptionCostEO.TIME_PHASED_CODE
	AND LOOKUP_TYPE = 'PJO_TIME_PHASED_TYPE' 
	) RES_CALENDAR_TYPE
,NULL RES_RATE_DERIVATION_DATE_TYPE
,NULL RES_RATE_DERIVATION_DATE	
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjoPlanOptionCostEO.NTP_RATE_DATE_TYPE
	AND LOOKUP_TYPE = 'PJO_RATE_DRV_DATE_TYPE'
	) RES_COST_RATE_DERIVATION_DATE_
,TO_CHAR(pjoPlanOptionCostEO.NTP_RATE_DATE,'DD-Mon-YYYY') RES_COST_RATE_DERIVATION_DATE
,(SELECT NAME 
	FROM PJO_PERIOD_PROFILES_VL
	WHERE PERIOD_PROFILE_ID = pjoPlanOptionCostEO.PERIOD_PROFILE_ID 
	) RES_PERIOD_PROFILE
,DECODE(pjoPlanOptionCostEO.MANUAL_SPREAD_FLAG,'Y','Yes','No')  RES_MAINTAIN_MANUAL_SPREAD_ON_
,DECODE(pjoPlanOptionCostEO.MAP_ACT_SUMMARY_FLAG,'Y','Yes','No') RES_ASSOCIATE_PROJECT_COSTS_TO
,NULL RES_ASSOCIATE_PROJECT_COSTS_OR
,DECODE(pjoFinPlanAMTRevEO.REVENUE_QTY_FLAG,'Y','Yes','No') RES_REVENUE_QUANTITY
,DECODE(pjoFinPlanAMTRevEO.REVENUE_FLAG,'Y','Yes','No') RES_REVENUE
,DECODE(pjoFinPlanAMTRevEO.BILL_RATE_FLAG,'Y','Yes','No') RES_BILL_RATE
,DECODE(pjoPlanOptionRevEO.USE_PLANNING_RATES_FLAG,'Y','Yes','No') RES_USE_COST_PLAN_OPTIONS_FOR_
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjoPlanOptionRevEO.PLAN_LEVEL_CODE
	AND LOOKUP_TYPE = 'PJO_PLAN_LEVEL_CODE'
	) RES_REVENUE_PLANNING_LEVEL
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjoPlanOptionRevEO.TIME_PHASED_CODE
	AND LOOKUP_TYPE = 'PJO_TIME_PHASED_TYPE'
	) RES_REVENUE_CALENDAR_TYPE
,NULL RES_BILL_RATE_DERIVATION_DATE_
,NULL RES_BILL_RATE_DERIVATION_DATE
,(SELECT NAME 
	FROM PJO_PERIOD_PROFILES_VL
	WHERE PERIOD_PROFILE_ID = pjoPlanOptionRevEO.PERIOD_PROFILE_ID
	) RES_REVENUE_PERIOD_PROFILE
,DECODE(pjoPlanOptionRevEO.MANUAL_SPREAD_FLAG,'Y','Yes','No') RES_REVENUE_MAINTAIN_MANUAL_SP
,DECODE(pjoPlanOptionRevEO.MAP_ACT_SUMMARY_FLAG,'Y','Yes','No') RES_ASSOCIATE_PROJECT_REVENUE_
,pjoPlanTypeEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,pjoPlanTypeEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,pjoPlanTypeEO.CREATED_BY  RSC_CREATED_BY
,pjoPlanTypeEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJO_PLAN_TYPES_VL pjoPlanTypeEO
,(SELECT * 
	FROM PJO_PLANNING_OPTIONS 
	WHERE PLANNED_FOR_CODE = 'COST'
	AND PLAN_OPTION_LEVEL_CODE = 'PLAN_TYPE'
	AND PROJECT_ID = 0
	) pjoPlanOptionCostEO
,(SELECT * 
	FROM PJO_PLANNING_OPTIONS 
	WHERE PLANNED_FOR_CODE = 'REVENUE'
	AND PLAN_OPTION_LEVEL_CODE = 'PLAN_TYPE'
	AND PROJECT_ID = 0
	) pjoPlanOptionRevEO
,PJO_FIN_PLAN_AMT_SETS pjoFinPlanAMTCostEO
,PJO_FIN_PLAN_AMT_SETS pjoFinPlanAMTRevEO
WHERE pjoPlanTypeEO.PLAN_TYPE_CODE = 'FINANCIAL_PLAN'
AND pjoPlanTypeEO.PLAN_TYPE_ID = pjoPlanOptionCostEO.PLAN_TYPE_ID
AND pjoPlanTypeEO.PLAN_TYPE_ID = pjoPlanOptionRevEO.PLAN_TYPE_ID
AND pjoPlanOptionCostEO.AMOUNT_SET_ID = pjoFinPlanAMTCostEO.FIN_PLAN_AMT_SET_ID
AND pjoPlanOptionRevEO.AMOUNT_SET_ID = pjoFinPlanAMTRevEO.FIN_PLAN_AMT_SET_ID
AND pjoPlanTypeEO.PLAN_OPTION_CODE = 'COST_AND_REV_SEP'

ORDER BY RES_NAME