/* ****************************************************************************
 * $Revision: 72749 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2019-10-23 15:22:46 +0700 (Wed, 23 Oct 2019) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Availability%20Lookups%20-%20Lookup%20Types.sql $:
 * $Id: Manage Availability Lookups - Lookup Types.sql 72749 2019-10-23 08:22:46Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 --RSC_PREREQUISITE_OBJECTS=CMP_BUDGET_POOLS_VL
 
SELECT actionsE0.PLAN_NAME RES_PLAN
,actionsE0.POOL_NAME RES_POOL_NAME
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES 
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'CMP_CONFIG_BUDGET_ACTIONS' 
	AND LOOKUP_CODE = actionsE0.VAL1 
	) RES_PARENT_ACTION
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES 
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'CMP_CONFIG_BUDGET_ACTIONS' 
	AND LOOKUP_CODE = actionsE0.VAL2 
	) RES_ACTION
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES 
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'CMP_CONFIG_BUDGET_ACTIONS' 
	AND LOOKUP_CODE = actionsE0.VAL3 
	) RES_SUB_ACTION
,DECODE(actionsE0.ENABLED_FLAG,'Y','Yes','N','No') RES_ENABLE
,actionsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,actionsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,actionsE0.CREATED_BY RSC_CREATED_BY
,actionsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM (SELECT DISTINCT PLAN_NAME
	,POOL_NAME
	,SUBSTR(CON_VALUE,INSTR(CON_VALUE,'###',1,1)+3,INSTR(CON_VALUE,'###',1,2)-4) VAL1
	,SUBSTR(CON_VALUE,INSTR(CON_VALUE,'###',1,2)+3,INSTR(CON_VALUE,'###',1,3) - INSTR(CON_VALUE,'###',1,2)-3) VAL2
	,SUBSTR(CON_VALUE,INSTR(CON_VALUE,'###',1,3)+3,INSTR(CON_VALUE,'###',1,4) - INSTR(CON_VALUE,'###',1,3)-3) VAL3
	,ENABLED_FLAG
	,CON_VALUE
	,LVL
	,LAST_UPDATED_BY
	,LAST_UPDATE_DATE
	,CREATED_BY
	,CREATION_DATE
	FROM (SELECT PLAN_NAME 
		,POOL_NAME
		,ENABLED_FLAG
		,SYS_CONNECT_BY_PATH(ATTRIBUTE_VALUE, '###')||'###' CON_VALUE
		,LEVEL LVL
		,LAST_UPDATED_BY
		,LAST_UPDATE_DATE
		,CREATED_BY
		,CREATION_DATE
		FROM (SELECT cmpPLANEO.PLAN_NAME
			,cmpBUDGETPOOLEO.POOL_NAME
			,actionsE0.TEXT_VALUE1
			,actionsE0.ATTRIBUTE_VALUE
			,actionsE0.ENABLED_FLAG
			,actionsE0.LAST_UPDATED_BY
			,actionsE0.LAST_UPDATE_DATE
			,actionsE0.CREATED_BY
			,actionsE0.CREATION_DATE
			FROM (SELECT PLAN_ID
				,PLAN_NAME
				FROM CMP_PLANS_VL 
				WHERE COMP_TYPE = 'CWB'
				) cmpPLANEO
			,CMP_BUDGET_POOLS_VL cmpBUDGETPOOLEO
			,(SELECT * 
				FROM CMP_LOOKUP_USAGES_B
				WHERE KEY_TYPE = 'BUDGET'
				AND ATTRIBUTE_NAME = 'CMP_CONFIG_BUDGET_ACTIONS'
				) actionsE0
			WHERE cmpPLANEO.PLAN_ID = cmpBUDGETPOOLEO.PLAN_ID
			AND cmpBUDGETPOOLEO.POOL_ID = actionsE0.KEY_VALUE)
		START WITH TEXT_VALUE1 = 'PARENT'
		CONNECT BY PRIOR ATTRIBUTE_VALUE = TEXT_VALUE1)) actionsE0
ORDER BY actionsE0.PLAN_NAME
,actionsE0.POOL_NAME
,actionsE0.VAL1
,NVL(actionsE0.VAL2,'1')
,NVL(actionsE0.VAL3,'1')