/* ****************************************************************************
 * $Revision: 60928 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2017-02-06 17:14:01 +0700 (Mon, 06 Feb 2017) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Complete%20Primary%20to%20Secondary%20Ledger%20Mapping%20-%20Journal%20Conversion%20Rules.sql $:
 * $Id: Complete Primary to Secondary Ledger Mapping - Journal Conversion Rules.sql 60928 2017-02-06 10:14:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=XLA_JE_RULE_SETS_VL
 
WITH SEG AS (SELECT KFFSEG.COLUMN_NAME
	,KFF.STRUCTURE_INSTANCE_NUMBER
	,KFFSEG.SEQUENCE_NUMBER
	,JELinesSegsE0.JERS_CODE
	,JELinesSegsE0.AMB_CONTEXT_CODE
	,JELinesSegsE0.JERS_TYPE_CODE
	,JELinesSegsE0.ACCOUNTING_LINE_CODE
	,JELinesSegsE0.ACCOUNTING_LINE_TYPE_CODE
	,JELinesSegsE0.APPLICATION_ID
	,JELinesSegsE0.SEGMENT_RULE_TYPE_CODE
	,JELinesSegsE0.SEGMENT_RULE_CODE
	,JELinesSegsE0.SEGMENT_RULE_APPL_ID
	,JELinesSegsE0.SIDE_CODE
	,JELinesSegsE0.EVENT_CLASS_CODE
	,JELinesSegsE0.EVENT_TYPE_CODE
	,JELinesSegsE0.INHERIT_ADR_FLAG
	FROM FND_KF_STR_INSTANCES_VL KFF
	,FND_KF_SEGMENTS_VL KFFSEG
	,XLA_JERS_ADR_LINES JELinesSegsE0
	WHERE KFF.STRUCTURE_ID = KFFSEG.STRUCTURE_ID
	AND KFFSEG.COLUMN_NAME = JELinesSegsE0.FLEXFIELD_SEGMENT_CODE)

,SEG_DEFAULT AS (SELECT JELinesSegsE0.FLEXFIELD_SEGMENT_CODE
	,JELinesSegsE0.JERS_CODE
	,JELinesSegsE0.AMB_CONTEXT_CODE
	,JELinesSegsE0.JERS_TYPE_CODE
	,JELinesSegsE0.ACCOUNTING_LINE_CODE
	,JELinesSegsE0.ACCOUNTING_LINE_TYPE_CODE
	,JELinesSegsE0.APPLICATION_ID
	,JELinesSegsE0.SEGMENT_RULE_TYPE_CODE
	,JELinesSegsE0.SEGMENT_RULE_CODE
	,JELinesSegsE0.SEGMENT_RULE_APPL_ID
	,JELinesSegsE0.SIDE_CODE
	,JELinesSegsE0.EVENT_CLASS_CODE
	,JELinesSegsE0.EVENT_TYPE_CODE
	,JELinesSegsE0.INHERIT_ADR_FLAG
	FROM XLA_JERS_ADR_LINES JELinesSegsE0)

SELECT (SELECT APPLICATION_NAME
	FROM XLA_SUBLEDGERS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND APPLICATION_ID = SubledgerRuleSetsE0.APPLICATION_ID
	) RES_SUBLEDGER_APPLICATION
,SubledgerRuleSetsE0.NAME  RES_NAME
,(SELECT MEANING 
	FROM XLA_LOOKUPS
	WHERE LOOKUP_TYPE = 'XLA_JLT_SIDE'
	AND LOOKUP_CODE = SubledgerRSLinesE0.SIDE_CODE
	) RES_LINE_TYPE
,JELineRulesE0.NAME RES_JOURNAL_LINE_RULE
,(SELECT MEANING
	FROM XLA_LOOKUPS
	WHERE LOOKUP_TYPE = 'XLA_ACCOUNTING_CLASS'
	AND LOOKUP_CODE = JELineRulesE0.ACCOUNTING_CLASS_CODE
	) RES_ACCOUNTING_CLASS
,(SELECT (CASE
		WHEN INHERIT_ADR_FLAG = 'Y' THEN
			'Copy'
		ELSE
			(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = XX.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = XX.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = XX.AMB_CONTEXT_CODE
			AND APPLICATION_ID = XX.SEGMENT_RULE_APPL_ID)
		END)
	FROM XLA_JERS_ADR_LINES XX
	WHERE SubledgerRuleSetsE0.JERS_CODE = XX.JERS_CODE
	AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = XX.AMB_CONTEXT_CODE
	AND SubledgerRuleSetsE0.JERS_CODE = XX.JERS_CODE
	AND SubledgerRSLinesE0.JERS_TYPE_CODE = XX.JERS_TYPE_CODE
	AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = XX.ACCOUNTING_LINE_CODE
	AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = XX.ACCOUNTING_LINE_TYPE_CODE
	AND SubledgerRSLinesE0.APPLICATION_ID = XX.APPLICATION_ID
	AND SubledgerRSLinesE0.SIDE_CODE = XX.SIDE_CODE
	AND SubledgerRSLinesE0.EVENT_CLASS_CODE = XX.EVENT_CLASS_CODE
	AND SubledgerRSLinesE0.EVENT_TYPE_CODE = XX.EVENT_TYPE_CODE
	AND FLEXFIELD_SEGMENT_CODE = 'ALL'
	) RES_ACCOUNT_COMBINATION_RULE
,(CASE
	WHEN SEG1.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG1.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG1.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG1.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG1.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_1
,(CASE
	WHEN SEG2.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG2.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG2.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG2.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG2.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_2
,(CASE
	WHEN SEG3.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG3.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG3.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG3.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG3.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_3
,(CASE
	WHEN SEG4.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG4.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG4.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG4.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG4.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_4
,(CASE
	WHEN SEG5.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG5.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG5.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG5.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG5.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_5
,(CASE
	WHEN SEG6.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG6.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG6.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG6.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG6.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_6
,(CASE
	WHEN SEG7.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG7.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG7.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG7.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG7.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_7
,(CASE
	WHEN SEG8.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG8.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG8.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG8.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG8.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_8
,(CASE
	WHEN SEG9.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG9.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG9.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG9.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG9.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_9
,(CASE
	WHEN SEG10.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG10.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG10.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG10.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG10.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_10
,(CASE
	WHEN SEG11.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG11.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG11.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG11.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG11.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_11
,(CASE
	WHEN SEG12.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG12.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG12.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG12.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG12.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_12
,(CASE
	WHEN SEG13.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG13.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG13.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG13.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG13.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_13
,(CASE
	WHEN SEG14.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG14.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG14.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG14.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG14.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_14
,(CASE
	WHEN SEG15.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG15.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG15.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG15.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG15.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_15
,(CASE
	WHEN SEG16.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG16.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG16.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG16.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG16.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_16
,(CASE
	WHEN SEG17.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG17.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG17.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG17.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG17.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_17
,(CASE
	WHEN SEG18.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG18.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG18.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG18.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG18.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_18
,(CASE
	WHEN SEG19.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG19.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG19.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG19.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG19.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_19
,(CASE
	WHEN SEG20.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG20.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG20.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG20.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG20.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_20
,(CASE
	WHEN SEG21.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG21.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG21.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG21.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG21.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_21
,(CASE
	WHEN SEG22.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG22.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG22.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG22.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG22.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_22
,(CASE
	WHEN SEG23.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG23.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG23.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG23.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG23.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_23
,(CASE
	WHEN SEG24.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = SEG24.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = SEG24.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = SEG24.AMB_CONTEXT_CODE
			AND APPLICATION_ID = SEG24.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_24
,(SELECT NAME
	FROM XLA_DESCRIPTIONS_TL
	WHERE DESCRIPTION_CODE = SubledgerRSLinesE0.DESCRIPTION_CODE
	AND APPLICATION_ID = SubledgerRSLinesE0.APPLICATION_ID
	AND DESCRIPTION_TYPE_CODE = NVL(SubledgerRSLinesE0.DESCRIPTION_TYPE_CODE,'S')
	AND LANGUAGE = USERENV('LANG')	
	) RES_LINE_DESCRIPTION_RULE
,SubledgerRSLinesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,SubledgerRSLinesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,SubledgerRSLinesE0.CREATED_BY RSC_CREATED_BY
,SubledgerRSLinesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,SubledgerRuleSetsE0.ACCOUNTING_COA_ID RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM XLA_JE_RULE_SETS_VL SubledgerRuleSetsE0
,XLA_JERS_JLT_LINES SubledgerRSLinesE0
,XLA_ACCT_LINE_TYPES_VL JELineRulesE0
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 1) SEG1
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 2) SEG2
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 3) SEG3
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 4) SEG4
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 5) SEG5
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 6) SEG6
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 7) SEG7
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 8) SEG8
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 9) SEG9
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 10) SEG10
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 11) SEG11
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 12) SEG12
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 13) SEG13
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 14) SEG14
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 15) SEG15
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 16) SEG16
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 17) SEG17
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 18) SEG18
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 19) SEG19
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 20) SEG20
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 21) SEG21
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 22) SEG22
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 23) SEG23
,(SELECT * FROM SEG WHERE SEQUENCE_NUMBER = 24) SEG24
WHERE SubledgerRuleSetsE0.JERS_CODE = SubledgerRSLinesE0.JERS_CODE
AND SubledgerRuleSetsE0.JERS_TYPE_CODE = SubledgerRSLinesE0.JERS_TYPE_CODE
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SubledgerRSLinesE0.AMB_CONTEXT_CODE
AND SubledgerRuleSetsE0.APPLICATION_ID = SubledgerRSLinesE0.APPLICATION_ID

AND SubledgerRuleSetsE0.EVENT_CLASS_CODE = JELineRulesE0.EVENT_CLASS_CODE

AND JELineRulesE0.ACCOUNTING_LINE_CODE = SubledgerRSLinesE0.ACCOUNTING_LINE_CODE
AND JELineRulesE0.ACCOUNTING_LINE_TYPE_CODE = SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE
AND JELineRulesE0.APPLICATION_ID = SubledgerRSLinesE0.APPLICATION_ID
AND JELineRulesE0.AMB_CONTEXT_CODE = SubledgerRSLinesE0.AMB_CONTEXT_CODE
AND JELineRulesE0.EVENT_CLASS_CODE = SubledgerRSLinesE0.EVENT_CLASS_CODE

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG1.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG1.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG1.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG1.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG1.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG1.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG1.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG1.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG1.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG1.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG2.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG2.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG2.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG2.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG2.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG2.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG2.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG2.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG2.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG2.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG3.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG3.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG3.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG3.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG3.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG3.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG3.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG3.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG3.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG3.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG4.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG4.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG4.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG4.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG4.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG4.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG4.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG4.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG4.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG4.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG5.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG5.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG5.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG5.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG5.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG5.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG5.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG5.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG5.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG5.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG6.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG6.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG6.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG6.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG6.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG6.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG6.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG6.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG6.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG6.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG7.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG7.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG7.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG7.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG7.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG7.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG7.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG7.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG7.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG7.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG8.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG8.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG8.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG8.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG8.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG8.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG8.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG8.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG8.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG8.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG9.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG9.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG9.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG9.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG9.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG9.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG9.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG9.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG9.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG9.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG10.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG10.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG10.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG10.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG10.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG10.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG10.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG10.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG10.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG10.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG11.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG11.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG11.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG11.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG11.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG11.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG11.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG11.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG11.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG11.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG12.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG12.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG12.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG12.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG12.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG12.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG12.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG12.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG12.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG12.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG13.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG13.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG13.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG13.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG13.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG13.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG13.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG13.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG13.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG13.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG14.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG14.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG14.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG14.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG14.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG14.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG14.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG14.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG14.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG14.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG15.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG15.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG15.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG15.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG15.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG15.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG15.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG15.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG15.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG15.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG16.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG16.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG16.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG16.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG16.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG16.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG16.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG16.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG16.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG16.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG17.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG17.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG17.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG17.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG17.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG17.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG17.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG17.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG17.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG17.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG18.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG18.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG18.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG18.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG18.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG18.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG18.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG18.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG18.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG18.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG19.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG19.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG19.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG19.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG19.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG19.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG19.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG19.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG19.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG19.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG20.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG20.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG20.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG20.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG20.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG20.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG20.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG20.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG20.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG20.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG21.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG21.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG21.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG21.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG21.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG21.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG21.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG21.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG21.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG21.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG22.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG22.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG22.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG22.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG22.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG22.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG22.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG22.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG22.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG22.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG23.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG23.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG23.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG23.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG23.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG23.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG23.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG23.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG23.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG23.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID = SEG24.STRUCTURE_INSTANCE_NUMBER(+)
AND SubledgerRuleSetsE0.JERS_CODE = SEG24.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG24.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG24.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG24.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG24.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG24.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG24.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG24.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG24.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID IS NOT NULL

UNION

SELECT (SELECT APPLICATION_NAME
	FROM XLA_SUBLEDGERS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND APPLICATION_ID = SubledgerRuleSetsE0.APPLICATION_ID
	) RES_SUBLEDGER_APPLICATION
,SubledgerRuleSetsE0.NAME  RES_NAME
,(SELECT MEANING 
	FROM XLA_LOOKUPS
	WHERE LOOKUP_TYPE = 'XLA_JLT_SIDE'
	AND LOOKUP_CODE = SubledgerRSLinesE0.SIDE_CODE
	) RES_LINE_TYPE
,JELineRulesE0.NAME RES_JOURNAL_LINE_RULE
,(SELECT MEANING
	FROM XLA_LOOKUPS
	WHERE LOOKUP_TYPE = 'XLA_ACCOUNTING_CLASS'
	AND LOOKUP_CODE = JELineRulesE0.ACCOUNTING_CLASS_CODE
	) RES_ACCOUNTING_CLASS
,(SELECT (CASE
		WHEN INHERIT_ADR_FLAG = 'Y' THEN
			'Copy'
		ELSE
			(SELECT NAME
			FROM XLA_SEG_RULES_VL
			WHERE SEGMENT_RULE_CODE = XX.SEGMENT_RULE_CODE
			AND SEGMENT_RULE_TYPE_CODE = XX.SEGMENT_RULE_TYPE_CODE
			AND AMB_CONTEXT_CODE = XX.AMB_CONTEXT_CODE
			AND APPLICATION_ID = XX.SEGMENT_RULE_APPL_ID)
		END)
	FROM XLA_JERS_ADR_LINES XX
	WHERE SubledgerRuleSetsE0.JERS_CODE = XX.JERS_CODE
	AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = XX.AMB_CONTEXT_CODE
	AND SubledgerRuleSetsE0.JERS_CODE = XX.JERS_CODE
	AND SubledgerRSLinesE0.JERS_TYPE_CODE = XX.JERS_TYPE_CODE
	AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = XX.ACCOUNTING_LINE_CODE
	AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = XX.ACCOUNTING_LINE_TYPE_CODE
	AND SubledgerRSLinesE0.APPLICATION_ID = XX.APPLICATION_ID
	AND SubledgerRSLinesE0.SIDE_CODE = XX.SIDE_CODE
	AND SubledgerRSLinesE0.EVENT_CLASS_CODE = XX.EVENT_CLASS_CODE
	AND SubledgerRSLinesE0.EVENT_TYPE_CODE = XX.EVENT_TYPE_CODE
	AND FLEXFIELD_SEGMENT_CODE = 'ALL'
	) RES_ACCOUNT_COMBINATION_RULE
,(CASE
	WHEN SEG1.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
		FROM XLA_SEG_RULES_VL
		WHERE SEGMENT_RULE_CODE = SEG1.SEGMENT_RULE_CODE
		AND SEGMENT_RULE_TYPE_CODE = SEG1.SEGMENT_RULE_TYPE_CODE
		AND AMB_CONTEXT_CODE = SEG1.AMB_CONTEXT_CODE
		AND APPLICATION_ID = SEG1.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_1
,(CASE
	WHEN SEG2.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
		FROM XLA_SEG_RULES_VL
		WHERE SEGMENT_RULE_CODE = SEG2.SEGMENT_RULE_CODE
		AND SEGMENT_RULE_TYPE_CODE = SEG2.SEGMENT_RULE_TYPE_CODE
		AND AMB_CONTEXT_CODE = SEG2.AMB_CONTEXT_CODE
		AND APPLICATION_ID = SEG2.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_2
,(CASE
	WHEN SEG3.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
		FROM XLA_SEG_RULES_VL
		WHERE SEGMENT_RULE_CODE = SEG3.SEGMENT_RULE_CODE
		AND SEGMENT_RULE_TYPE_CODE = SEG3.SEGMENT_RULE_TYPE_CODE
		AND AMB_CONTEXT_CODE = SEG3.AMB_CONTEXT_CODE
		AND APPLICATION_ID = SEG3.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_3
,(CASE
	WHEN SEG4.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
		FROM XLA_SEG_RULES_VL
		WHERE SEGMENT_RULE_CODE = SEG4.SEGMENT_RULE_CODE
		AND SEGMENT_RULE_TYPE_CODE = SEG4.SEGMENT_RULE_TYPE_CODE
		AND AMB_CONTEXT_CODE = SEG4.AMB_CONTEXT_CODE
		AND APPLICATION_ID = SEG4.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_4
,(CASE
	WHEN SEG5.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
		FROM XLA_SEG_RULES_VL
		WHERE SEGMENT_RULE_CODE = SEG5.SEGMENT_RULE_CODE
		AND SEGMENT_RULE_TYPE_CODE = SEG5.SEGMENT_RULE_TYPE_CODE
		AND AMB_CONTEXT_CODE = SEG5.AMB_CONTEXT_CODE
		AND APPLICATION_ID = SEG5.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_5
,(CASE
	WHEN SEG6.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
		FROM XLA_SEG_RULES_VL
		WHERE SEGMENT_RULE_CODE = SEG6.SEGMENT_RULE_CODE
		AND SEGMENT_RULE_TYPE_CODE = SEG6.SEGMENT_RULE_TYPE_CODE
		AND AMB_CONTEXT_CODE = SEG6.AMB_CONTEXT_CODE
		AND APPLICATION_ID = SEG6.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_6
,(CASE
	WHEN SEG7.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
		FROM XLA_SEG_RULES_VL
		WHERE SEGMENT_RULE_CODE = SEG7.SEGMENT_RULE_CODE
		AND SEGMENT_RULE_TYPE_CODE = SEG7.SEGMENT_RULE_TYPE_CODE
		AND AMB_CONTEXT_CODE = SEG7.AMB_CONTEXT_CODE
		AND APPLICATION_ID = SEG7.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_7
,(CASE
	WHEN SEG8.INHERIT_ADR_FLAG = 'Y' THEN
		'Copy'
	ELSE
		(SELECT NAME
		FROM XLA_SEG_RULES_VL
		WHERE SEGMENT_RULE_CODE = SEG8.SEGMENT_RULE_CODE
		AND SEGMENT_RULE_TYPE_CODE = SEG8.SEGMENT_RULE_TYPE_CODE
		AND AMB_CONTEXT_CODE = SEG8.AMB_CONTEXT_CODE
		AND APPLICATION_ID = SEG8.SEGMENT_RULE_APPL_ID)
	END) RES_SEGMENT_RULE_8
,NULL RES_SEGMENT_RULE_9
,NULL RES_SEGMENT_RULE_10
,NULL RES_SEGMENT_RULE_11
,NULL RES_SEGMENT_RULE_12
,NULL RES_SEGMENT_RULE_13
,NULL RES_SEGMENT_RULE_14
,NULL RES_SEGMENT_RULE_15
,NULL RES_SEGMENT_RULE_16
,NULL RES_SEGMENT_RULE_17
,NULL RES_SEGMENT_RULE_18
,NULL RES_SEGMENT_RULE_19
,NULL RES_SEGMENT_RULE_20
,NULL RES_SEGMENT_RULE_21
,NULL RES_SEGMENT_RULE_22
,NULL RES_SEGMENT_RULE_23
,NULL RES_SEGMENT_RULE_24
,(SELECT NAME
	FROM XLA_DESCRIPTIONS_TL
	WHERE DESCRIPTION_CODE = SubledgerRSLinesE0.DESCRIPTION_CODE
	AND APPLICATION_ID = SubledgerRSLinesE0.APPLICATION_ID
	AND DESCRIPTION_TYPE_CODE = NVL(SubledgerRSLinesE0.DESCRIPTION_TYPE_CODE,'S')
	AND LANGUAGE = USERENV('LANG')	
	) RES_LINE_DESCRIPTION_RULE
,SubledgerRSLinesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,SubledgerRSLinesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,SubledgerRSLinesE0.CREATED_BY RSC_CREATED_BY
,SubledgerRSLinesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,SubledgerRuleSetsE0.ACCOUNTING_COA_ID RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM XLA_JE_RULE_SETS_VL SubledgerRuleSetsE0
,XLA_JERS_JLT_LINES SubledgerRSLinesE0
,XLA_ACCT_LINE_TYPES_VL JELineRulesE0
,(SELECT * FROM SEG_DEFAULT WHERE FLEXFIELD_SEGMENT_CODE = 'GL_BALANCING') SEG1
,(SELECT * FROM SEG_DEFAULT WHERE FLEXFIELD_SEGMENT_CODE = 'FA_COST_CTR') SEG2
,(SELECT * FROM SEG_DEFAULT WHERE FLEXFIELD_SEGMENT_CODE = 'GL_MANAGEMENT') SEG3
,(SELECT * FROM SEG_DEFAULT WHERE FLEXFIELD_SEGMENT_CODE = 'GL_ACCOUNT') SEG4
,(SELECT * FROM SEG_DEFAULT WHERE FLEXFIELD_SEGMENT_CODE = 'GL_SECONDARY_TRACKING') SEG5
,(SELECT * FROM SEG_DEFAULT WHERE FLEXFIELD_SEGMENT_CODE = 'GL_BALANCING_3') SEG6
,(SELECT * FROM SEG_DEFAULT WHERE FLEXFIELD_SEGMENT_CODE = 'GL_INTERCOMPANY') SEG7
,(SELECT * FROM SEG_DEFAULT WHERE FLEXFIELD_SEGMENT_CODE = 'GL_LOCAL_USE') SEG8
WHERE SubledgerRuleSetsE0.JERS_CODE = SubledgerRSLinesE0.JERS_CODE
AND SubledgerRuleSetsE0.JERS_TYPE_CODE = SubledgerRSLinesE0.JERS_TYPE_CODE
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SubledgerRSLinesE0.AMB_CONTEXT_CODE
AND SubledgerRuleSetsE0.APPLICATION_ID = SubledgerRSLinesE0.APPLICATION_ID

AND SubledgerRuleSetsE0.EVENT_CLASS_CODE = JELineRulesE0.EVENT_CLASS_CODE

AND JELineRulesE0.ACCOUNTING_LINE_CODE = SubledgerRSLinesE0.ACCOUNTING_LINE_CODE
AND JELineRulesE0.ACCOUNTING_LINE_TYPE_CODE = SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE
AND JELineRulesE0.APPLICATION_ID = SubledgerRSLinesE0.APPLICATION_ID
AND JELineRulesE0.AMB_CONTEXT_CODE = SubledgerRSLinesE0.AMB_CONTEXT_CODE
AND JELineRulesE0.EVENT_CLASS_CODE = SubledgerRSLinesE0.EVENT_CLASS_CODE

AND SubledgerRuleSetsE0.JERS_CODE = SEG1.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG1.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG1.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG1.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG1.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG1.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG1.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG1.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG1.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.JERS_CODE = SEG2.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG2.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG2.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG2.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG2.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG2.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG2.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG2.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG2.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.JERS_CODE = SEG3.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG3.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG3.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG3.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG3.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG3.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG3.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG3.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG3.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.JERS_CODE = SEG4.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG4.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG4.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG4.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG4.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG4.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG4.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG4.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG4.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.JERS_CODE = SEG5.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG5.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG5.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG5.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG5.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG5.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG5.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG5.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG5.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.JERS_CODE = SEG6.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG6.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG6.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG6.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG6.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG6.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG6.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG6.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG6.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.JERS_CODE = SEG7.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG7.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG7.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG7.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG7.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG7.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG7.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG7.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG7.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.JERS_CODE = SEG8.JERS_CODE(+)
AND SubledgerRuleSetsE0.AMB_CONTEXT_CODE = SEG8.AMB_CONTEXT_CODE(+)
AND SubledgerRSLinesE0.JERS_TYPE_CODE = SEG8.JERS_TYPE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_CODE = SEG8.ACCOUNTING_LINE_CODE(+)
AND SubledgerRSLinesE0.ACCOUNTING_LINE_TYPE_CODE = SEG8.ACCOUNTING_LINE_TYPE_CODE(+)
AND SubledgerRSLinesE0.APPLICATION_ID = SEG8.APPLICATION_ID(+)
AND SubledgerRSLinesE0.SIDE_CODE = SEG8.SIDE_CODE(+)
AND SubledgerRSLinesE0.EVENT_CLASS_CODE = SEG8.EVENT_CLASS_CODE(+)
AND SubledgerRSLinesE0.EVENT_TYPE_CODE = SEG8.EVENT_TYPE_CODE(+)

AND SubledgerRuleSetsE0.ACCOUNTING_COA_ID IS NULL

ORDER BY 1,2,3,4