/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20User-Defined%20Tables%20-%20User-Defined%20Table.sql $:
 * $Id: Manage User-Defined Tables - User-Defined Table.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 
SELECT (SELECT NAME 
	FROM PER_LEGISLATIVE_DATA_GROUPS_VL 
	WHERE LEGISLATIVE_DATA_GROUP_ID = ffUSERTABLEO.LEGISLATIVE_DATA_GROUP_ID
	) RES_LEGISLATIVE_DATA_GROUP
,TO_CHAR(SYSDATE,'DD-Mon-YYYY') RES_EFFECTIVE_AS_OF_DATE
,ffUSERTABLEO.USER_TABLE_NAME RES_NAME
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE  LOOKUP_CODE = ffUSERTABLEO.RANGE_OR_MATCH
	AND LOOKUP_TYPE = 'FF_USER_TABLE_RANGE_OR_MATCH' 
	AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_RANGE_OR_MATCH
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE  LOOKUP_CODE = ffUSERTABLEO.USER_KEY_UNITS
	AND LOOKUP_TYPE = 'FF_USER_TABLE_USER_KEY_UNITS' 
	AND LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_UNIT_OF_MEASURE
,ffUSERTABLEO.USER_ROW_TITLE RES_ROW_TITLE
,ffUSERTABLEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ffUSERTABLEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ffUSERTABLEO.CREATED_BY RSC_CREATED_BY
,ffUSERTABLEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,(SELECT LEGISLATION_CODE 
	FROM PER_LEGISLATIVE_DATA_GROUPS
	WHERE LEGISLATIVE_DATA_GROUP_ID = ffUSERTABLEO.LEGISLATIVE_DATA_GROUP_ID
	) RSC_COUNTRY_ID
FROM FF_USER_TABLES_VL ffUSERTABLEO
ORDER BY RES_NAME