/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Units%20of%20Measure%20-%20Manage%20UOM%20Classes.sql $:
 * $Id: Manage Units of Measure - Manage UOM Classes.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=INV_UOM_CLASSES_VL
 
SELECT UNITOFMEASURECLASSEO.UOM_CLASS_CODE RES_CLASS_CODE
,UNITOFMEASURECLASSEO.UOM_CLASS_TL RES_CLASS_NAME
,UNITOFMEASURECLASSEO.DESCRIPTION RES_DESCRIPTION
,UNITOFMEASUREEO.UOM_CODE RES_UOM_CODE
,NVL(UNITOFMEASUREEO.UNIT_OF_MEASURE,'-1')  RES_BASE_UOM_NAME
,UNITOFMEASUREEO.DESCRIPTION RES_BASE_UOM_DESCRIPTION
,TO_CHAR(UNITOFMEASURECLASSEO.DISABLE_DATE,'DD-Mon-YYYY') RES_END_DATE
,UNITOFMEASURECLASSEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,UNITOFMEASURECLASSEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
,UNITOFMEASURECLASSEO.CREATED_BY  RSC_CREATED_BY
,UNITOFMEASURECLASSEO.CREATION_DATE  RSC_CREATION_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
    
FROM INV_UOM_CLASSES_VL UNITOFMEASURECLASSEO
,INV_UNITS_OF_MEASURE_VL UnitOfMeasureEO
WHERE UNITOFMEASURECLASSEO.UOM_CLASS = UNITOFMEASUREEO.UOM_CLASS
AND UNITOFMEASUREEO.BASE_UOM_FLAG    = 'Y'
ORDER BY UNITOFMEASURECLASSEO.UOM_CLASS_TL