/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah.Dusenmahamad $:
 * $Date: 2017-08-28 $:
 * $HeadURL:  $:
 * $Id: Manage Pricing Bases - Pricing Basis.sql 54097 2016-03-30 09:27:56Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PER_CHECKLIST_CONTACTS

SELECT chklistsE0.NAME RES_CHECKLIST_NAME
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_ONB_CONTACT_TITLE'
    AND LOOKUP_CODE = chkContactsE0.CONTACT_TITLE_CODE 
	 ) RES_TITLE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_PER_ONB_CONTACT_TYPE'
    AND LOOKUP_CODE = chkContactsE0.CONTACT_TYPE 
	 ) RES_TYPE
,chkContactsE0.CUSTOM_CONTACT RES_OTHER_CONTACT
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'PER_RESPONSIBILITY_TYPES'
    AND LOOKUP_CODE = chkContactsE0.RESPONSIBILITY_TYPE 
	 ) RES_RESPONSIBILITY_TYPE
,(SELECT USER_DISPLAY_NAME
    FROM ASE_USER_VL
    WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
    AND USER_GUID = chkContactsE0.ADHOC_USER_GUID 
	 ) RES_USER
,chkContactsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,chkContactsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,chkContactsE0.CREATED_BY RSC_CREATED_BY
,chkContactsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PER_CHECKLISTS_VL chklistsE0
,PER_CHECKLIST_CONTACTS chkContactsE0
WHERE chklistsE0.CHECKLIST_ID = chkContactsE0.CHECKLIST_ID
ORDER BY chklistsE0.NAME