/* ****************************************************************************
 * $Revision: 79346 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-09-15 11:40:19 +0700 (Thu, 15 Sep 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Absence%20Certifications%20-%20Absence%20Certification%20Details%20-%20DFF.sql $:
 * $Id: Manage Absence Certifications - Absence Certification Details - DFF.sql 79346 2022-09-15 04:40:19Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10110##RES##ANC_ABS_CERTIFICATIONS_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_DATE,ATTRIBUTE_NUMBER

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for attributes fields.

SELECT (SELECT NAME FROM ANC_ABS_CERTIFICATIONS_F_TL WHERE ABSENCE_CERTIFICATION_ID = ancABSENCEREO.ABSENCE_CERTIFICATION_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	AND LANGUAGE = USERENV('LANG')) RES_NAME
,TO_CHAR(ancABSENCEREO.EFFECTIVE_START_DATE,'DD-Mon-YYYY')  RES_EFFECTIVE_START_DATE
,(SELECT TERRITORY_SHORT_NAME FROM FND_TERRITORIES_VL WHERE TERRITORY_CODE = ancABSENCEREO.LEGISLATION_CODE) RES_LEGISLATION
,ancABSENCEREO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ancABSENCEREO.ATTRIBUTE1
,ancABSENCEREO.ATTRIBUTE2
,ancABSENCEREO.ATTRIBUTE3
,ancABSENCEREO.ATTRIBUTE4
,ancABSENCEREO.ATTRIBUTE5
,ancABSENCEREO.ATTRIBUTE6
,ancABSENCEREO.ATTRIBUTE7
,ancABSENCEREO.ATTRIBUTE8
,ancABSENCEREO.ATTRIBUTE9
,ancABSENCEREO.ATTRIBUTE10
,ancABSENCEREO.ATTRIBUTE11
,ancABSENCEREO.ATTRIBUTE12
,ancABSENCEREO.ATTRIBUTE13
,ancABSENCEREO.ATTRIBUTE14
,ancABSENCEREO.ATTRIBUTE15
,ancABSENCEREO.ATTRIBUTE16
,ancABSENCEREO.ATTRIBUTE17
,ancABSENCEREO.ATTRIBUTE18
,ancABSENCEREO.ATTRIBUTE19
,ancABSENCEREO.ATTRIBUTE20
,ancABSENCEREO.ATTRIBUTE21
,ancABSENCEREO.ATTRIBUTE22
,ancABSENCEREO.ATTRIBUTE23
,ancABSENCEREO.ATTRIBUTE24
,ancABSENCEREO.ATTRIBUTE25
,ancABSENCEREO.ATTRIBUTE26
,ancABSENCEREO.ATTRIBUTE27
,ancABSENCEREO.ATTRIBUTE28
,ancABSENCEREO.ATTRIBUTE29
,ancABSENCEREO.ATTRIBUTE30
,ancABSENCEREO.ATTRIBUTE_NUMBER1
,ancABSENCEREO.ATTRIBUTE_NUMBER2
,ancABSENCEREO.ATTRIBUTE_NUMBER3
,ancABSENCEREO.ATTRIBUTE_NUMBER4
,ancABSENCEREO.ATTRIBUTE_NUMBER5
,ancABSENCEREO.ATTRIBUTE_NUMBER6
,ancABSENCEREO.ATTRIBUTE_NUMBER7
,ancABSENCEREO.ATTRIBUTE_NUMBER8
,ancABSENCEREO.ATTRIBUTE_NUMBER9
,ancABSENCEREO.ATTRIBUTE_NUMBER10
,ancABSENCEREO.ATTRIBUTE_NUMBER11
,ancABSENCEREO.ATTRIBUTE_NUMBER12
,ancABSENCEREO.ATTRIBUTE_NUMBER13
,ancABSENCEREO.ATTRIBUTE_NUMBER14
,ancABSENCEREO.ATTRIBUTE_NUMBER15
,ancABSENCEREO.ATTRIBUTE_NUMBER16
,ancABSENCEREO.ATTRIBUTE_NUMBER17
,ancABSENCEREO.ATTRIBUTE_NUMBER18
,ancABSENCEREO.ATTRIBUTE_NUMBER19
,ancABSENCEREO.ATTRIBUTE_NUMBER20
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE1, 'DD-Mon-YYYY') ATTRIBUTE_DATE1
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE2, 'DD-Mon-YYYY') ATTRIBUTE_DATE2
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE3, 'DD-Mon-YYYY') ATTRIBUTE_DATE3
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE4, 'DD-Mon-YYYY') ATTRIBUTE_DATE4
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE5, 'DD-Mon-YYYY') ATTRIBUTE_DATE5
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE6, 'DD-Mon-YYYY') ATTRIBUTE_DATE6
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE7, 'DD-Mon-YYYY') ATTRIBUTE_DATE7
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE8, 'DD-Mon-YYYY') ATTRIBUTE_DATE8
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE9, 'DD-Mon-YYYY') ATTRIBUTE_DATE9
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE10, 'DD-Mon-YYYY') ATTRIBUTE_DATE10
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE11, 'DD-Mon-YYYY') ATTRIBUTE_DATE11
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE12, 'DD-Mon-YYYY') ATTRIBUTE_DATE12
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE13, 'DD-Mon-YYYY') ATTRIBUTE_DATE13
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE14, 'DD-Mon-YYYY') ATTRIBUTE_DATE14
, TO_CHAR(ancABSENCEREO.ATTRIBUTE_DATE15, 'DD-Mon-YYYY') ATTRIBUTE_DATE15

,ancABSENCEREO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ancABSENCEREO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ancABSENCEREO.CREATED_BY RSC_CREATED_BY
,ancABSENCEREO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,ancABSENCEREO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM ANC_ABS_CERTIFICATIONS_F ancABSENCEREO
WHERE (ancABSENCEREO.ATTRIBUTE_CATEGORY IS NOT NULL OR
ancABSENCEREO.ATTRIBUTE1 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE2 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE3 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE4 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE5 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE6 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE7 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE8 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE9 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE10 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE11 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE12 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE13 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE14 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE15 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE16 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE17 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE18 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE19 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE20 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE21 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE22 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE23 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE24 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE25 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE26 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE27 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE28 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE29 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE30 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER11 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER12 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER13 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER14 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER15 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER16 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER17 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER18 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER19 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_NUMBER20 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE1 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE2 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE3 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE4 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE5 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE6 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE7 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE8 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE10 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE11 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE12 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE13 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE14 IS NOT NULL OR 
ancABSENCEREO.ATTRIBUTE_DATE15 IS NOT NULL 
 )
ORDER BY RES_NAME,ancABSENCEREO.EFFECTIVE_START_DATE