/* ****************************************************************************
 * $Revision: 54943 $:
 * $Author: paul.wakefield $:
 * $Date: 2016-05-04 13:45:23 +0700 (Wed, 04 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Trading%20Community%20Person%20Lookups%20-%20Standard%20Lookup%20Type.sql $:
 * $Id: Manage Trading Community Person Lookups - Standard Lookup Type.sql 54943 2016-05-04 06:45:23Z paul.wakefield $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
SELECT payFLOWEO.FLOW_NAME RES_FLOW_PATTERN
,payFLOWPARAMETEREO.PARAMETER_NAME RES_FLOW_PARAMETER
,payFLOWPARAMETEREO.BASE_FLOW_PARAMETER_NAME RES_BASEFLOWPARAMETERNAME
,payFLOWPARAMETEREO.DESCRIPTION RES_DESCRIPTION
,DECODE(payFLOWPARAMETEREO.CONTEXT_PARAM_FLAG,'Y','Yes','No') RES_USE_FOR_SEARCHES
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWPARAMETEREO.DISPLAY_FLAG
		AND LOOKUP_TYPE = 'PAY_PARAM_DISP_FLAG' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))  RES_DISPLAY
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWPARAMETEREO.PARAM_DISP_TYPE
		AND LOOKUP_TYPE = 'PAY_PARAM_DISP_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_DISPLAY_FORMAT
,payFLOWPARAMETEREO.PARAM_LOOKUP RES_LOOKUP
,payFLOWPARAMETEREO.PARAM_SEQUENCE RES_SEQUENCE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWPARAMETEREO.DEFAULT_TYPE
		AND LOOKUP_TYPE = 'PAY_TASK_DEFAULT_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))  RES_PARAMETER_BASIS
,(CASE WHEN DEFAULT_TYPE = 'BIND_CONTEXT' THEN
	(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = payFLOWPARAMETEREO.DEFAULT_VAL
		AND LOOKUP_TYPE = 'PAY_PARAM_CONTEXT_BINDINGS' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))
	ELSE
	payFLOWPARAMETEREO.DEFAULT_VAL END) RES_BASIS_VALUE
,payFLOWPARAMETEREO.PARAMETER_CODE RES_KEY_PARAMETER --TRANSALATION

,payFLOWPARAMETEREO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,payFLOWPARAMETEREO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,payFLOWPARAMETEREO.CREATED_BY RSC_CREATED_BY
,payFLOWPARAMETEREO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PAY_FLOWS_VL payFLOWEO
,PAY_FLOW_PARAMETERS_VL payFLOWPARAMETEREO
WHERE payFLOWEO.FLOW_ID = payFLOWPARAMETEREO.BASE_FLOW_ID 
ORDER BY payFLOWEO.FLOW_NAME,payFLOWPARAMETEREO.PARAMETER_NAME
