/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Performance%20Template%20Sections%20-%20Performance%20Template%20Section.sql $:
 * $Id: Manage Performance Template Sections - Performance Template Section.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 -- RSC_PREREQUISITE_OBJECTS=HRA_SECTION_DEFNS_VL
 

SELECT pfSectionsE0.NAME RES_NAME
,pfSectionsE0.DESCRIPTION RES_DESCRIPTION
,pfSectionsE0.COMMENTS RES_COMMENTS
,TO_CHAR(pfSectionsE0.DATE_FROM,'DD-Mon-YYYY') RES_FROM_DATE
,TO_CHAR(pfSectionsE0.DATE_TO,'DD-Mon-YYYY') RES_TO_DATE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ACTIVE_INACTIVE'
    AND LOOKUP_CODE = pfSectionsE0.STATUS_CODE
    ) RES_STATUS
    
-- Section Processing	
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRA_SECTION_TYPE'
    AND LOOKUP_CODE = pfSectionsE0.SECTION_TYPE_CODE
    ) RES_SECTION_TYPE
    
--Ratings
,(SELECT RATING_NAME
    FROM HRT_RATING_MODELS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND RATING_MODEL_ID = pfSectionsE0.SECTION_RATING_MODEL_ID
    ) RES_SECTION_RATING_MODEL
,DECODE(pfSectionsE0.RATE_SECTION_FLAG,'Y','Yes','No') RES_RATE_SECTION

--Rating Calculations
,(CASE
    WHEN pfSectionsE0.SECTION_RATING_MODEL_ID IS NOT NULL THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'HRA_PERF_CALC_RULE_TYPE'
            AND LOOKUP_CODE = pfSectionsE0.CALCULATION_RULE_CODE)
    END) RES_CALCULATION_RULE_FOR_SECTI
,(CASE
    WHEN pfSectionsE0.SECTION_RATING_MODEL_ID IS NOT NULL THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'ORA_HRA_PERF_DECIMAL_PLACES'
            AND LOOKUP_CODE = pfSectionsE0.DECIMAL_PLACES)
    END) RES_DECIMAL_PLACES
,(CASE
    WHEN pfSectionsE0.SECTION_RATING_MODEL_ID IS NOT NULL THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'ORA_HRA_MAPPING_METRIC'
            AND LOOKUP_CODE = pfSectionsE0.CALC_MAPPING_CODE)
    END) RES_MAPPING_METRIC
,(CASE
    WHEN pfSectionsE0.SECTION_RATING_MODEL_ID IS NOT NULL AND pfSectionsE0.CALCULATION_RULE_CODE = 'ORA_FAST_FORMULA' THEN
        (SELECT FORMULA_NAME
            FROM FF_FORMULAS_TL
            WHERE LANGUAGE = USERENV('LANG')
            AND FORMULA_ID = pfSectionsE0.FAST_FORMULA_ID)
    END) RES_FAST_FORMULA_RULE
,(CASE
    WHEN pfSectionsE0.SECTION_RATING_MODEL_ID IS NOT NULL THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'HRA_PERF_ROUNDING_RULE_CODE'
            AND LOOKUP_CODE = pfSectionsE0.ROUNDING_RULE_CODE)
    END) RES_DECIMAL_ROUNDING_RULE
,(CASE
    WHEN pfSectionsE0.SECTION_RATING_MODEL_ID IS NOT NULL THEN
        (SELECT MEANING
            FROM FND_LOOKUP_VALUES
            WHERE LANGUAGE = USERENV('LANG')
            AND LOOKUP_TYPE = 'HRA_PERF_MAPPING_METHOD'
            AND LOOKUP_CODE = pfSectionsE0.MAPPING_METHOD_CODE)
    END) RES_MAPPING_METHOD

,DECODE(pfSectionsE0.USE_SEC_WEIGHTS_FOR_CALC,'Y','Yes','No') RES_USE_SECTION_WEIGHTS_IN_CAL

--Comments
,DECODE(pfSectionsE0.ENABLE_SECTION_COMMENTS_FLAG,'Y','Yes','No') RES_ENABLE_SECTION_COMMENTS

--Weighting
,(CASE
    WHEN pfSectionsE0.RATE_SECTION_FLAG = 'Y' THEN
        DECODE(pfSectionsE0.WEIGHT_SECTION_FLAG,'Y','Yes','No')
    END) RES_WEIGHT_SECTION
,(CASE
    WHEN pfSectionsE0.RATE_SECTION_FLAG = 'Y' AND pfSectionsE0.WEIGHT_SECTION_FLAG = 'Y' THEN
        pfSectionsE0.SECTION_WEIGHT
    END) RES_SECTION_WEIGHT
,(CASE
    WHEN pfSectionsE0.RATE_SECTION_FLAG = 'Y' AND pfSectionsE0.WEIGHT_SECTION_FLAG = 'Y' THEN
        pfSectionsE0.SECTION_MIN_WEIGHT
    END) RES_SECTION_MINIMUM_WEIGHT

--Item Processing
,(CASE
    WHEN pfSectionsE0.SECTION_TYPE_CODE IN ('REG','GOAL','ORA_DEVGOAL') THEN
        DECODE(pfSectionsE0.ENABLE_ITEMS_FLAG,'Y','Yes','No')
    END) RES_ENABLE_ITEMS

--Ratings and Calculations
,(CASE
    WHEN pfSectionsE0.ENABLE_ITEMS_FLAG = 'Y' THEN
        DECODE(pfSectionsE0.RATE_ITEM_FLAG,'Y','Yes','No')
    END) RES_RATE_ITEMS
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRA_PERF_ITEM_RATING_TYPE'
    AND LOOKUP_CODE = pfSectionsE0.RATING_TYPE_CODE
    ) RES_RATING_TYPE
,(CASE
    WHEN pfSectionsE0.RATE_ITEM_FLAG = 'Y' AND pfSectionsE0.SECTION_RATING_MODEL_ID IS NOT NULL THEN
        DECODE(pfSectionsE0.USE_SECRTG_FOR_PERFRTG_FLAG,'Y','Yes','No')
    END) RES_USE_SECTION_RATING_MODEL_F
,(CASE
    WHEN pfSectionsE0.RATE_ITEM_FLAG = 'Y' AND NVL(pfSectionsE0.USE_SECRTG_FOR_PERFRTG_FLAG,'N') = 'N' THEN
        (SELECT RATING_NAME
            FROM HRT_RATING_MODELS_TL
            WHERE LANGUAGE = USERENV('LANG')
            AND RATING_MODEL_ID = pfSectionsE0.PERF_RATING_MODEL_ID)
    END) RES_PERFORMANCE_RATING_MODEL
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HRA_PERF_ITEM_CALC_TYPE'
    AND LOOKUP_CODE = pfSectionsE0.ITEM_CALCULATION_CODE
    ) RES_ITEM_CALCULATION

,DECODE(pfSectionsE0.ENABLE_ITEM_COMMENTS_FLAG,'Y','Yes','No') RES_ENABLE_ITEM_COMMENTS
     
--Properties
,DECODE(pfSectionsE0.SHOW_TARGET_PROF_LEVEL,'Y','Yes','No') RES_TARGET_PROFICIENCY_LEVEL
,(CASE 
    WHEN pfSectionsE0.RATE_ITEM_FLAG = 'Y' THEN
        DECODE(pfSectionsE0.SHOW_TARGET_PERF_RTG,'Y','Yes','No')
    END) RES_TARGET_PERFORMANCE_RATING
,(CASE 
    WHEN pfSectionsE0.RATE_ITEM_FLAG = 'Y' THEN
        DECODE(pfSectionsE0.SHOW_SECTION_MIN_WEIGHT,'Y','Yes','No')
    END) RES_MINIMUM_WEIGHT
,(CASE 
    WHEN pfSectionsE0.RATE_ITEM_FLAG = 'Y' THEN
        DECODE(pfSectionsE0.SHOW_SECTION_WEIGHT,'Y','Yes','No')
    END) RES_WEIGHT
,(CASE
    WHEN pfSectionsE0.ENABLE_ITEMS_FLAG = 'Y' THEN
        DECODE(pfSectionsE0.SHOW_MANDATORY,'Y','Yes','No')
    END) RES_REQUIRED

--Section Content
,DECODE(pfSectionsE0.USE_PROFILE_FLAG,'Y','Yes','No') RES_USE_PROFILE_RELATED_TO_WOR
,(SELECT DESCRIPTION
    FROM HRT_PROFILE_TYPES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND PROFILE_TYPE_ID = pfSectionsE0.PROFILE_TYPE_ID
    ) RES_PROFILE_TYPE
,DECODE(pfSectionsE0.USE_SPEC_PROFILE_FLAG,'Y','Yes','No') RES_USE_SPECIFIC_PROFILE
,(SELECT DESCRIPTION
    FROM HRT_PROFILES_VL
    WHERE PROFILE_ID = pfSectionsE0.PROFILE_ID
    ) RES_PROFILE
,(CASE
    WHEN pfSectionsE0.ENABLE_ITEMS_FLAG = 'Y' AND SECTION_TYPE_CODE = 'GOAL'THEN
        DECODE(pfSectionsE0.USE_WORKER_GOALS_FLAG,'Y','Yes','No')
    END) RES_POPULATE_WITH_WORKER_PERFO
,(CASE
    WHEN pfSectionsE0.ENABLE_ITEMS_FLAG = 'Y' AND SECTION_TYPE_CODE = 'ORA_DEVGOAL'THEN
        DECODE(pfSectionsE0.USE_WORKER_GOALS_FLAG,'Y','Yes','No')
    END) RES_POPULATE_WITH_WORKERS_DEVE
,(CASE
    WHEN pfSectionsE0.ENABLE_ITEMS_FLAG = 'Y' AND SECTION_TYPE_CODE = 'GOAL' AND pfSectionsE0.SHOW_SECTION_WEIGHT = 'Y' AND pfSectionsE0.USE_WORKER_GOALS_FLAG = 'Y' THEN
        DECODE(pfSectionsE0.UPDATE_GOAL_WEIGHTS_FLAG,'Y','Yes','No')
    END) RES_ALLOW_UPDATE_GOALS_ACTION_
,(CASE
        WHEN pfSectionsE0.SECTION_TYPE_CODE = 'ORA_DEVGOAL' AND pfSectionsE0.ENABLE_ITEMS_FLAG = 'Y' THEN
            DECODE(pfSectionsE0.INCLUDE_FUTURE_ITEMS_FLAG,'Y','Yes','No')
        END) RES_INCLUDE_FUTURE_DEVELOPMENT
,(CASE
        WHEN pfSectionsE0.SECTION_TYPE_CODE = 'ORA_DEVGOAL' AND pfSectionsE0.ENABLE_ITEMS_FLAG = 'Y' THEN
            DECODE(pfSectionsE0.EXCLUDE_INACTIVE_ITEMS_FLAG,'Y','Yes','No')
        END) RES_EXCLUDE_INACTIVE_DEVELOPME
,(CASE
    WHEN pfSectionsE0.ENABLE_ITEMS_FLAG = 'Y' THEN
        DECODE(pfSectionsE0.USE_SPEC_CONTENT_ITEM_FLAG,'Y','Yes','No') 
    END) RES_USE_SPECIFIC_CONTENT_ITEMS
,DECODE(pfSectionsE0.USE_WRITING_ASSISTANT_FLAG,'Y','Yes','No') RES_ENABLE_WRITING_ASSISTANT_F

,(SELECT NAME
	FROM HRT_PROFILE_TYP_SECTIONS_VL
	WHERE ACTIVE_FLAG = 'Y'
	AND SECTION_ID = pfSectionsE0.REFERENCE_SECTION_ID
	AND CONTENT_TYPE_ID = pfSectionsE0.CONTENT_TYPE_ID
	) RES_COMPETENCIES_SECTION_NAME


,pfSectionsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,pfSectionsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,pfSectionsE0.CREATED_BY RSC_CREATED_BY
,pfSectionsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,pfSectionsE0.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID


FROM HRA_SECTION_DEFNS_VL pfSectionsE0
ORDER BY pfSectionsE0.NAME