/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah Dusenmahamad $:
 * $Date: 2018-03-20  $:
 * $HeadURL: $:
 * $Id: Configure Exception Sets - Exception  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT legislativeDataGrpsE0.NAME RES_LEGISLATIVE_DATA_GROUP
,prClassesE0.CLASSIFICATION_NAME RES_PRIMARY_CLASSIFICATION
,elementsE0.ELEMENT_NAME RES_ELEMENT_NAME
,elementsE0.REPORTING_NAME RES_REPORTING_NAME
,TO_CHAR(elementsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_DATE
,elementsE0.DESCRIPTION RES_DESCRIPTION
,(SELECT CLASSIFICATION_NAME
    FROM PAY_ELE_CLASSIFICATIONS_VL
    WHERE CLASSIFICATION_ID = elementsE0.SECONDARY_CLASSIFICATION_ID
	AND LEGISLATION_CODE = legislativeDataGrpsE0.LEGISLATION_CODE
    ) RES_SECONDARY_CLASSIFICATION	
,(CASE
	WHEN EXISTS (SELECT 1 
			FROM PAY_DIR_CARD_COMP_DEFS_F cardComp
			,PAY_DIR_CARD_DEFINITIONS cardDef
			WHERE cardComp.DIR_CARD_DEFINITION_ID = cardDef.DIR_CARD_DEFINITION_ID
			AND cardDef.BASE_DISPLAY_NAME = 'Time Cards'
			AND cardComp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID
			AND elementsFE0.EFFECTIVE_END_DATE BETWEEN cardComp.EFFECTIVE_START_DATE AND cardComp.EFFECTIVE_END_DATE) THEN 
		'Time Card'
	ELSE
		'Standard'
	END) RES_CATEGORY
,(SELECT NAME
    FROM FND_CURRENCIES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND CURRENCY_CODE = elementsE0.INPUT_CURRENCY_CODE
    ) RES_INPUT_CURRENCY

,DECODE(elementsE0.STANDARD_LINK_FLAG ,'Y','Yes','N','No') RES_SHOULD_EVERY_PERSON_ELIGIB 	-- Should every person eligible for the element automatically receive it?
,(SELECT DEFINITION_NAME
	FROM PAY_TIME_DEFINITIONS
	WHERE TIME_DEFINITION_ID = elementsE0.STARTING_TIME_DEF_ID
	) RES_WHAT_IS_THE_EARLIEST_ENTRY 	-- What is the earliest entry date for this element?
,(SELECT DEFINITION_NAME
	FROM PAY_TIME_DEFINITIONS
	WHERE TIME_DEFINITION_ID = elementsE0.ENDING_TIME_DEF_ID
	) RES_WHAT_IS_THE_LATEST_ENTRY_D 	-- What is the latest entry date for this element?
,(CASE
	WHEN elementsE0.USE_AT_REL_LEVEL = 'Y' THEN
		'Payroll relationship level'
	WHEN elementsE0.USE_AT_TERM_LEVEL = 'Y' THEN
		'Term Level'
	WHEN elementsE0.USE_AT_ASG_LEVEL = 'Y' THEN
		'Assignment level'
    END) RES_AT_WHICH_EMPLOYMENT_LEVEL_ 	-- At which employment level should this element be attached?
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'PAY_PROCESSING_TYPE'
	AND LOOKUP_CODE = elementsE0.PROCESSING_TYPE
    ) RES_DOES_THIS_ELEMENT_RECUR_EA 	-- Does this element recur each payroll period, or does it require explicit entry?


,DECODE(elementsE0.ONCE_EACH_PERIOD_FLAG,'Y','Yes','No') RES_PROCESS_THE_ELEMENT_ONLY_O -- Process the element only once in each payroll period?


,DECODE(elementsE0.MULTIPLE_ENTRIES_ALLOWED_FLAG ,'Y','Yes','N','No') RES_CAN_A_PERSON_HAVE_MORE_THA 	-- Can a person have more than one entry of this element in a payroll


,(CASE
	WHEN elementsE0.PROCESS_MODE = 'N' THEN
		'Process and pay with other earnings'
	WHEN elementsE0.PROCESS_MODE = 'P' THEN
		'Process separately, but pay with other earnings'
	WHEN elementsE0.PROCESS_MODE = 'S' THEN
		'Process separately and pay separately'
	END) RES_PROCESS_AND_PAY_ELEMENT_SE -- Process and pay element separately or with other earnings elements?


,(CASE
	WHEN EXISTS (SELECT 1 FROM PAY_INPUT_VALUES_VL WHERE ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID AND NAME = 'Amount') THEN 
		'Flat amount'
	WHEN EXISTS (SELECT 1 FROM PAY_INPUT_VALUES_VL WHERE ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID AND NAME = 'Factor') THEN 
		'Factor'
	ELSE
		'Percentage'
	END) RES_WHAT_IS_THE_CALCULATION_RU 	-- What is the calculation rule?


,(SELECT lk.MEANING
	FROM PAY_INPUT_VALUES_VL inp
	,FND_LOOKUP_VALUES lk
	WHERE lk.LANGUAGE = USERENV('LANG')
	AND lk.LOOKUP_TYPE = 'PAY_TMPLT_ET_TIME_DEFINITION'
	AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
	AND inp.NAME = 'Periodicity' 
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
	) RES_WHAT_IS_THE_DEFAULT_PERIOD -- What is the default periodicity of this element?
,(SELECT ff.FORMULA_NAME
	FROM PAY_INPUT_VALUES_VL inp
	,FF_FORMULAS_VL ff
	WHERE inp.NAME = 'Periodicity Conversion Rule' 
	AND inp.DEFAULT_VALUE = ff.BASE_FORMULA_NAME
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
	) RES_PERIODICITY_CONVERSION_RUL -- Periodicity Conversion Rule
,(CASE
	WHEN EXISTS (SELECT 1 
			FROM PAY_DIR_CARD_COMP_DEFS_F cardComp
			,PAY_DIR_CARD_DEFINITIONS cardDef
			WHERE cardComp.DIR_CARD_DEFINITION_ID = cardDef.DIR_CARD_DEFINITION_ID
			AND cardDef.BASE_DISPLAY_NAME = 'Time Cards'
			AND cardComp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID
			AND elementsFE0.EFFECTIVE_END_DATE BETWEEN cardComp.EFFECTIVE_START_DATE AND cardComp.EFFECTIVE_END_DATE) THEN 
		'Hours' 
	END) RES_WHAT_ARE_THE_CALCULATION_U -- What are the calculation units for reporting?
,'No' RES_DOES_THIS_ELEMENT_HAVE_A_D -- Does this element have a default rate definition?
,'' RES_RATE_NAME
,(CASE
	WHEN NOT EXISTS (SELECT 1 
			FROM PAY_DIR_CARD_COMP_DEFS_F cardComp
			,PAY_DIR_CARD_DEFINITIONS cardDef
			WHERE cardComp.DIR_CARD_DEFINITION_ID = cardDef.DIR_CARD_DEFINITION_ID
			AND cardDef.BASE_DISPLAY_NAME = 'Time Cards'
			AND cardComp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID
			AND elementsFE0.EFFECTIVE_END_DATE BETWEEN cardComp.EFFECTIVE_START_DATE AND cardComp.EFFECTIVE_END_DATE) THEN 
		(CASE
			WHEN EXISTS (SELECT 1 FROM PAY_INPUT_VALUES_VL WHERE ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID AND NAME = 'Days Worked') THEN 
				'Days'
			WHEN EXISTS (SELECT 1 FROM PAY_INPUT_VALUES_VL WHERE ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID AND NAME = 'Hours Worked') THEN 
				'Hours'
			ELSE
				'None'
			END)
	END) RES_HOW_DO_YOU_WANT_THE_WORK_U -- How do you want the work units to be reported?
,'' RES_WORK_UNITS_CONVERSION_RULE
,(CASE
	WHEN NOT EXISTS (SELECT 1 
			FROM PAY_DIR_CARD_COMP_DEFS_F cardComp
			,PAY_DIR_CARD_DEFINITIONS cardDef
			WHERE cardComp.DIR_CARD_DEFINITION_ID = cardDef.DIR_CARD_DEFINITION_ID
			AND cardDef.BASE_DISPLAY_NAME = 'Time Cards'
			AND cardComp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID
			AND elementsFE0.EFFECTIVE_END_DATE BETWEEN cardComp.EFFECTIVE_START_DATE AND cardComp.EFFECTIVE_END_DATE) THEN 
		'No'
	END) RES_IS_THIS_ELEMENT_SUBJECT_TO -- Is this element subject to proration?
,'' RES_PRORATION_GROUP
,'' RES_PRORATION_UNITS
,'' RES_PRORATION_RATE_CONVERSION_ -- Proration Rate Conversion Rule
,(CASE
	WHEN NOT EXISTS (SELECT 1 
			FROM PAY_DIR_CARD_COMP_DEFS_F cardComp
			,PAY_DIR_CARD_DEFINITIONS cardDef
			WHERE cardComp.DIR_CARD_DEFINITION_ID = cardDef.DIR_CARD_DEFINITION_ID
			AND cardDef.BASE_DISPLAY_NAME = 'Time Cards'
			AND cardComp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID
			AND elementsFE0.EFFECTIVE_END_DATE BETWEEN cardComp.EFFECTIVE_START_DATE AND cardComp.EFFECTIVE_END_DATE) THEN 
		'No'
	END) RES_IS_THIS_ELEMENT_SUBJECT__0 -- Is this element subject to retroactive changes?
,'' RES_RETRO_GROUP
,DECODE(elementsE0.GROSSUP_FLAG,'Y','Yes','N','No') RES_USE_THIS_ELEMENT_TO_CALCUL -- Use this element to calculate a gross amount from a specified net amount?
,(SELECT lk.MEANING
	FROM PAY_INPUT_VALUES_VL inp
	,FND_LOOKUP_VALUES lk
	WHERE lk.LANGUAGE = USERENV('LANG')
	AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
	AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
	AND inp.NAME = 'Tax Processing Type' 
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
	) RES_ISR_TAX_CALCULATION_APPLIC -- ISR tax calculation applicable to this element?
,(SELECT lk.MEANING
	FROM PAY_INPUT_VALUES_VL inp
	,FND_LOOKUP_VALUES lk
	WHERE lk.LANGUAGE = USERENV('LANG')
	AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
	AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
	AND inp.NAME = 'ISR Taxability' 
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
	) RES_ISR_TAXABILITY_RULE_APPLIC -- ISR taxability rule applicable to this element?
,(SELECT lk.MEANING
	FROM PAY_INPUT_VALUES_VL inp
	,FND_LOOKUP_VALUES lk
	WHERE lk.LANGUAGE = USERENV('LANG')
	AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
	AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
	AND inp.NAME = 'State Taxability' 
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
	) RES_STATE_TAXABILITY_RULE_APPL -- State taxability rule applicable to this element?
,'' RES_ARE_THE_REST_DAYS_INCLUDED -- Are the rest days included in the calculation of the daily rate for this element?
,(CASE
	WHEN legislativeDataGrpsE0.LEGISLATION_CODE = 'MX' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE LIKE 'ORA_HRX_MX_CFDI_FOR%'
			AND LOOKUP_CODE = extraE0.EEI_INFORMATION1) --'002 - ISR Tax' 
	END) RES_WHAT_IS_THE_CFDI_CODE_WHEN -- What is the CFDI Code when this element result is positive?
,(CASE
	WHEN legislativeDataGrpsE0.LEGISLATION_CODE = 'MX' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE LIKE 'ORA_HRX_MX_CFDI_FOR%'
			AND LOOKUP_CODE = extraE0.EEI_INFORMATION2) --'050 - Travel expenses' 
	END) RES_WHAT_IS_THE_CFDI_CODE_WH_1 -- What is the CFDI Code when this element result is negative?
,(SELECT lk.MEANING
	FROM PAY_INPUT_VALUES_VL inp
	,FND_LOOKUP_VALUES lk
	WHERE lk.LANGUAGE = USERENV('LANG')
	AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
	AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
	AND inp.NAME = 'Supplemental Tax Processing' 
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
	) RES_WHAT_TAX_WITHHOLDING_METHO -- What tax withholding method applies to this Taxable Benefit element?
,(SELECT lk.MEANING
	FROM PAY_INPUT_VALUES_VL inp
	,FND_LOOKUP_VALUES lk
	WHERE lk.LANGUAGE = USERENV('LANG')
	AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
	AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
	AND inp.NAME = 'EI Allocation' 
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
	) RES_IF_THIS_ELEMENT_IS_INSURAB -- If this element is insurable, how are the earnings allocated?
,(SELECT lk.MEANING
	FROM PAY_INPUT_VALUES_VL inp
	,FND_LOOKUP_VALUES lk
	WHERE lk.LANGUAGE = USERENV('LANG')
	AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
	AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
	AND inp.NAME = 'EI Hours' 
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
	) RES_ARE_THERE_INSURABLE_HOURS_ -- Are there insurable hours associated with this element?
,(CASE
	WHEN legislativeDataGrpsE0.LEGISLATION_CODE = 'CA' THEN
		(SELECT lk.MEANING
			FROM PAY_INPUT_VALUES_VL inp
			,FND_LOOKUP_VALUES lk
			WHERE lk.LANGUAGE = USERENV('LANG')
			AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
			AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
			AND inp.NAME = 'GST' 
			AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID)
	END) RES_DOES_GST_APPLY
,(CASE
	WHEN legislativeDataGrpsE0.LEGISLATION_CODE = 'CA' THEN
		(SELECT lk.MEANING
			FROM PAY_INPUT_VALUES_VL inp
			,FND_LOOKUP_VALUES lk
			WHERE lk.LANGUAGE = USERENV('LANG')
			AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
			AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
			AND inp.NAME = 'PST' 
			AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID)
	END) RES_DOES_PST_APPLY
,(CASE
	WHEN legislativeDataGrpsE0.LEGISLATION_CODE = 'CA' THEN
		(SELECT lk.MEANING
			FROM PAY_INPUT_VALUES_VL inp
			,FND_LOOKUP_VALUES lk
			WHERE lk.LANGUAGE = USERENV('LANG')
			AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
			AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
			AND inp.NAME = 'RST' 
			AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID)
	END) RES_DOES_RST_APPLY
,(CASE
	WHEN legislativeDataGrpsE0.LEGISLATION_CODE = 'CA' THEN
		(SELECT lk.MEANING
			FROM PAY_INPUT_VALUES_VL inp
			,FND_LOOKUP_VALUES lk
			WHERE lk.LANGUAGE = USERENV('LANG')
			AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
			AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
			AND inp.NAME = 'HST' 
			AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID)
	END) RES_DOES_HST_APPLY
,(CASE
	WHEN legislativeDataGrpsE0.LEGISLATION_CODE = 'CA' THEN
		(SELECT lk.MEANING
			FROM PAY_INPUT_VALUES_VL inp
			,FND_LOOKUP_VALUES lk
			WHERE lk.LANGUAGE = USERENV('LANG')
			AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
			AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
			AND inp.NAME = 'PTT' 
			AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID)
	END) RES_DOES_PPT_APPLY
,(SELECT lk.MEANING
	FROM PAY_INPUT_VALUES_VL inp
	,FND_LOOKUP_VALUES lk
	WHERE lk.LANGUAGE = USERENV('LANG')
	AND lk.LOOKUP_TYPE = inp.LOOKUP_TYPE
	AND lk.LOOKUP_CODE = inp.DEFAULT_VALUE
	AND inp.NAME = 'Report Sales Tax Separately' 
	AND inp.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID
	) RES_SHOULD_THE_TAX_BE_REPORTED -- Should the tax be reported separately?


,elementsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,elementsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,elementsE0.CREATED_BY RSC_CREATED_BY
,elementsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,legislativeDataGrpsE0.LEGISLATION_CODE RSC_COUNTRY_ID


FROM PAY_ELEMENT_TYPES_VL elementsE0
,PAY_ELEMENT_TYPES_F elementsFE0
,(SELECT NAME
    ,LEGISLATIVE_DATA_GROUP_ID
	,LEGISLATION_CODE
    FROM PER_LEGISLATIVE_DATA_GROUPS_VL
    ) legislativeDataGrpsE0
,PAY_ELE_CLASSIFICATIONS_VL prClassesE0
,(SELECT ELEMENT_TYPE_ID
	,EEI_INFORMATION1
	,EEI_INFORMATION2
	FROM PAY_ELE_TYPE_EXTRA_INFO
	WHERE INFORMATION_TYPE = 'ORA_HRX_MX_CFDI_PAYSLIP_CODE'
	) extraE0
WHERE elementsE0.LEGISLATIVE_DATA_GROUP_ID = legislativeDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID

AND elementsE0.CLASSIFICATION_ID = prClassesE0.BASE_CLASSIFICATION_ID
AND legislativeDataGrpsE0.LEGISLATION_CODE = prClassesE0.LEGISLATION_CODE

AND prClassesE0.BASE_CLASSIFICATION_NAME = 'Taxable Benefits'

AND elementsE0.ELEMENT_TYPE_ID = elementsFE0.ELEMENT_TYPE_ID 
AND elementsE0.EFFECTIVE_START_DATE = elementsFE0.EFFECTIVE_START_DATE
AND elementsE0.ELEMENT_TYPE_ID = extraE0.ELEMENT_TYPE_ID(+)

ORDER BY elementsE0.ELEMENT_NAME