/* ****************************************************************************
 * $Revision: 53899 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-03-24 18:14:40 +0700 (Thu, 24 Mar 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Applications%20Core%20Standard%20Lookups%20-%20Lookup%20Codes.sql $:
 * $Id: Manage Applications Core Standard Lookups - Lookup Codes.sql 53899 2016-03-24 11:14:40Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=0##RES##FND_LOOKUP_VALUES_B
--  DFF_ATTRIBUTES=ATTRIBUTE
-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.

select LOOKUPTYPEEO.LOOKUP_TYPE RES_LOOKUP_TYPE
,LOOKUPEO.LOOKUP_CODE RES_LOOKUP_CODE
,LOOKUPEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,LOOKUPEO.ATTRIBUTE1 
,LOOKUPEO.ATTRIBUTE2
,LOOKUPEO.ATTRIBUTE3
,LOOKUPEO.ATTRIBUTE4
,LOOKUPEO.ATTRIBUTE5
,LOOKUPEO.ATTRIBUTE6
,LOOKUPEO.ATTRIBUTE7
,LOOKUPEO.ATTRIBUTE8
,LOOKUPEO.ATTRIBUTE9
,LOOKUPEO.ATTRIBUTE10
,LOOKUPEO.ATTRIBUTE11
,LOOKUPEO.ATTRIBUTE12
,LOOKUPEO.ATTRIBUTE13
,LOOKUPEO.ATTRIBUTE14
,LOOKUPEO.ATTRIBUTE15
,LookupEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,LookupEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,LookupEO.CREATED_BY  RSC_CREATED_BY
,LookupEO.CREATION_DATE  RSC_CREATION_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
    
from FND_LOOKUP_TYPES_VL LOOKUPTYPEEO
,FND_LOOKUP_VALUES_VL LookupEO
WHERE LOOKUPTYPEEO.LOOKUP_TYPE         = LOOKUPEO.LOOKUP_TYPE
AND(LookupTypeEO.MODULE_ID  IN
	(SELECT rf.child_module_id
	FROM fnd_appl_taxonomy_rf rf
	,FND_APPL_TAXONOMY AT
	WHERE AT.MODULE_TYPE = 'APPLICATION'
	AND at.module_key    = 'FND'
	AND at.module_id     = rf.ancestor_module_id
	))
AND((((LookupTypeEO.VIEW_APPLICATION_ID = 0))))
and  (LOOKUPEO.ATTRIBUTE_CATEGORY IS NOT NULL OR
LOOKUPEO.ATTRIBUTE1 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE2 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE3 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE4 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE5 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE6 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE7 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE8 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE9 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE10 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE11 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE12 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE13 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE14 IS NOT NULL OR 
LOOKUPEO.ATTRIBUTE15 IS NOT NULL  )
ORDER BY LOOKUPTYPEEO.LOOKUP_TYPE
,LOOKUPEO.LOOKUP_CODE
,LookupEO.DISPLAY_SEQUENCE