/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Programs%20-%20Reporting%20Groups.sql $:
 * $Id: Manage Benefit Programs - Reporting Groups.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT benPGMEO.NAME RES_PROGRAM_NAME 
,TO_CHAR(benPGMEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,benPOPLRPTGRPEO.ORDR_NUM RES_SEQUENCE
,(SELECT NAME FROM BEN_RPTG_GRP_VL WHERE RPTG_GRP_ID = benPOPLRPTGRPEO.RPTG_GRP_ID) RES_REPORTING_GROUP_NAME
,TO_CHAR(benPOPLRPTGRPEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_REPORTING_GROUPS_EFFECTIVE
,TO_CHAR(benPOPLRPTGRPEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_REPORTING_GROUPS_EFFECTI_0


,benPOPLRPTGRPEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benPOPLRPTGRPEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benPOPLRPTGRPEO.CREATED_BY RSC_CREATED_BY
,benPOPLRPTGRPEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PGM_F benPGMEO
,BEN_POPL_RPTG_GRP_F benPOPLRPTGRPEO
WHERE benPGMEO.PGM_ID = benPOPLRPTGRPEO.PGM_ID
AND benPOPLRPTGRPEO.COMP_OBJ_TYPE = 'PGM'
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPOPLRPTGRPEO.EFFECTIVE_START_DATE AND NVL(benPOPLRPTGRPEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
ORDER BY RES_PROGRAM_NAME
