/* ****************************************************************************
* $Revision: 55207 $:
* $Author: dhara.pithadiya $:
* $Date: 2016-05-13 15:25:32 +0700 (Fri, 13 May 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.19/trunk/core/reverse_sql/FINANCIALS/Manage%20Applications%20Core%20Messages%20-%20Message%20Tokens.sql $:
* $Id: Manage Applications Core Messages - Message Tokens.sql 55207 2016-05-13 08:25:32Z dhara.pithadiya $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=HWM_TCSMR_CONFIG_SETS_VL

SELECT tConSetsE0.NAME RES_NAME
,tConSetsE0.DESCRIPTION RES_DESCRIPTION

--Time Consumer
,DECODE(pCostsE0.TCSMR_CONFIG_ID,NULL,'No','Yes') RES_TIME_CONSUMER_PROJECT_COST
,DECODE(prjExecutionsE0.TCSMR_CONFIG_ID,NULL,'No','Yes') RES_TIME_CONSUMER_PROJECT_EXEC
,DECODE(payrollsE0.TCSMR_CONFIG_ID,NULL,'No','Yes') RES_TIME_CONSUMER_PAYROLL
,DECODE(tConSetsE0.WRKFLW_NTFN_ENABLED,'Y','Yes','No') RES_ENABLE_INFORMATIONAL_WORKF
,DECODE(tConSetsE0.WRK_APPROVAL_ENABLED,'Y','Yes','No') RES_ENABLE_INFORMATIONAL_APPRO
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HWM_ABS_APPROVAL_USAGE_CD'
    AND LOOKUP_CODE = tConSetsE0.ABS_APPROVAL_USAGE_CD
    ) RES_ABSENCE_APPROVAL_ROUTING

--Time Consumer: Project Costing
,(SELECT TCAT_NAME
    FROM HWM_TCATS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND TCAT_ID = pCostsE0.TCAT_ID
    ) RES_PROJECT_COSTING_TIME_CATEG
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HWM_TCONS_VALIDATE_ON_SAVE'
    AND LOOKUP_CODE = pCostsE0.VALIDATE_ON_SAVE
    ) RES_PROJECT_COSTING_VALIDATE_O
,DECODE(pCostsE0.TIME_REQUIRED,'Y','Yes','No') RES_PROJECT_COSTING_REQUIRED_T
,(SELECT NAME
    FROM HWM_RP_TM_PERIODS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND REPEATING_TM_PERIOD_ID = pCostsE0.APPROVAL_PERIOD_ID
    ) RES_PROJECT_COSTING_APPROVAL
,DECODE(pCostsE0.ENABLE_ENTRY_LEVEL_APRVL,'Y','Yes','No') RES_PROJECT_COSTING_ENTRY_LEVE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HWM_APRVL_RULE_TM_EVAL'
    AND LOOKUP_CODE = pCostsE0.APRVL_REC_GRP_TYP_CD
    ) RES_PROJECT_COSTING_TIME_DATA_

--Transfer Rules: Import and Process Cost Transactions
,(SELECT DECODE(APPROVAL_REQD,'Y','Yes','No')
    FROM HWM_TCSMR_XFR_CONFIGS
    WHERE APPROVAL_REQD_TCSMR_ID = (SELECT TCSMRS_ID FROM HWM_TCSMRS_B WHERE TCSMRS_CODE = 'PJC')
    AND TCSMR_XFR_PROCESS_ID IN (SELECT TCSMR_XFR_PROCESS_ID FROM HWM_TCSMR_XFR_PROCESSES_B)
    AND TCSMR_CONFIG_ID = pCostsE0.TCSMR_CONFIG_ID
    ) RES_PROJECT_COSTING_APPROVAL_R
,(SELECT DECODE(APPROVAL_REQD,'Y','Yes','No')
    FROM HWM_TCSMR_XFR_CONFIGS
    WHERE APPROVAL_REQD_TCSMR_ID = (SELECT TCSMRS_ID FROM HWM_TCSMRS_B WHERE TCSMRS_CODE = 'PYR')
    AND TCSMR_XFR_PROCESS_ID IN (SELECT TCSMR_XFR_PROCESS_ID FROM HWM_TCSMR_XFR_PROCESSES_B)
    AND TCSMR_CONFIG_ID = pCostsE0.TCSMR_CONFIG_ID
    ) RES_PROJECT_COSTING_APPROVAL_0

--Time Consumer: Project Execution Management
,(SELECT TCAT_NAME
    FROM HWM_TCATS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND TCAT_ID = prjExecutionsE0.TCAT_ID
    ) RES_PROJECT_EXECUTION_MANAGEME

--Transfer Rules: Initiate Absence Records Transfer to Oracle Fusion Project Execution

--Time Consumer: Payroll
,(SELECT TCAT_NAME
    FROM HWM_TCATS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND TCAT_ID = payrollsE0.TCAT_ID
    ) RES_PAYROLL_TIME_CATEGORY
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'HWM_TCONS_VALIDATE_ON_SAVE'
    AND LOOKUP_CODE = payrollsE0.VALIDATE_ON_SAVE
    ) RES_PAYROLL_VALIDATE_ON_TIME_C
,DECODE(payrollsE0.TIME_REQUIRED,'Y','Yes','N','No') RES_PAYROLL_REQUIRED_TIME_CARD
,(SELECT NAME
    FROM HWM_RP_TM_PERIODS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND REPEATING_TM_PERIOD_ID = payrollsE0.APPROVAL_PERIOD_ID
    ) RES_PAYROLL_APPROVAL
,DECODE(payrollsE0.ENABLE_ENTRY_LEVEL_APRVL,'Y','Yes','No') RES_PAYROLL_ENTRY_LEVEL_APPROV
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ORA_HWM_APRVL_RULE_TM_EVAL'
    AND LOOKUP_CODE = payrollsE0.APRVL_REC_GRP_TYP_CD
    ) RES_PAYROLL_TIME_DATA_FOR_APPR

--Transfer Rules: Import and Process Cost Transactions
,(SELECT DECODE(APPROVAL_REQD,'Y','Yes','No')
    FROM HWM_TCSMR_XFR_CONFIGS
    WHERE APPROVAL_REQD_TCSMR_ID = (SELECT TCSMRS_ID FROM HWM_TCSMRS_B WHERE TCSMRS_CODE = 'PJC')
    AND TCSMR_XFR_PROCESS_ID IN (SELECT TCSMR_XFR_PROCESS_ID FROM HWM_TCSMR_XFR_PROCESSES_B)
    AND TCSMR_CONFIG_ID = payrollsE0.TCSMR_CONFIG_ID
    ) RES_PAYROLL_APPROVAL_REQUIRED_
,(SELECT DECODE(APPROVAL_REQD,'Y','Yes','No')
    FROM HWM_TCSMR_XFR_CONFIGS
    WHERE APPROVAL_REQD_TCSMR_ID = (SELECT TCSMRS_ID FROM HWM_TCSMRS_B WHERE TCSMRS_CODE = 'PYR')
    AND TCSMR_XFR_PROCESS_ID IN (SELECT TCSMR_XFR_PROCESS_ID FROM HWM_TCSMR_XFR_PROCESSES_B)
    AND TCSMR_CONFIG_ID = payrollsE0.TCSMR_CONFIG_ID
    ) RES_PAYROLL_APPROVAL_REQUIRE_1
,tConSetsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,tConSetsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,tConSetsE0.CREATED_BY RSC_CREATED_BY
,tConSetsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,tConSetsE0.ENTERPRISE_ID RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HWM_TCSMR_CONFIG_SETS_VL tConSetsE0
,(SELECT *
    FROM HWM_TCSMR_CONFIGS
    WHERE TCSMRS_ID = (SELECT TCSMRS_ID FROM HWM_TCSMRS_B WHERE TCSMRS_CODE = 'PJC')
    ) pCostsE0
,(SELECT *
    FROM HWM_TCSMR_CONFIGS
    WHERE TCSMRS_ID = (SELECT TCSMRS_ID FROM HWM_TCSMRS_B WHERE TCSMRS_CODE = 'PJT')
    ) prjExecutionsE0
,(SELECT *
    FROM HWM_TCSMR_CONFIGS
    WHERE TCSMRS_ID = (SELECT TCSMRS_ID FROM HWM_TCSMRS_B WHERE TCSMRS_CODE = 'PYR')
    ) payrollsE0
WHERE tConSetsE0.TCSMR_CONFIG_SET_ID = pCostsE0.TCSMR_CONFIG_SET_ID(+)
AND tConSetsE0.TCSMR_CONFIG_SET_ID = prjExecutionsE0.TCSMR_CONFIG_SET_ID(+)
AND tConSetsE0.TCSMR_CONFIG_SET_ID = payrollsE0.TCSMR_CONFIG_SET_ID(+)
ORDER BY tConSetsE0.NAME