/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Project%20Types%20-%20Capitalization%20Options.sql $:
 * $Id: Manage Project Types - Capitalization Options.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT pjfPROTypeE0.PROJECT_TYPE RES_NAME
 ,(SELECT MEANING FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjfPROTypeE0.CAPITAL_COST_TYPE_CODE
	AND LOOKUP_TYPE = 'PJC_CAPITAL_COST_TYPE') RES_COST_TYPE
 ,(SELECT MEANING FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjfPROTypeE0.CIP_GROUPING_METHOD_CODE
	AND LOOKUP_TYPE = 'PJC_CIP_GROUPING_METHOD') RES_ASSET_LINE_GROUPING_METHOD
 ,(SELECT MEANING FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjfPROTypeE0.ASSET_ALLOCATION_METHOD
	AND LOOKUP_TYPE = 'PJC_ASSET_ALLOCATION_METHOD') RES_ASSET_COST_ALLOCATION_METH
 ,(SELECT MEANING FROM FND_LOOKUPS
	WHERE LOOKUP_CODE = pjfPROTypeE0.CAPITAL_EVENT_PROCESSING
	AND LOOKUP_TYPE = 'PJC_CAPITAL_EVENT_PROCESSING') RES_EVENT_PROCESSING_METHOD
 ,DECODE(pjfPROTypeE0.INTERFACE_COMPLETE_ASSET_FLAG,'Y','Yes','No') RES_REQUIRE_COMPLETE_ASSET_DEF
 ,DECODE(pjfPROTypeE0.OVERRIDE_ASSET_ASSIGNMENT_FLAG,'Y','Yes','No') RES_OVERRIDE_ASSET_ASSIGNMENT
 ,(CASE 
	WHEN pjfPROTypeE0.VENDOR_INVOICE_GROUPING_CODE = 'G' 
		THEN 'Yes'
		ELSE 'No'
		END) RES_USE_GROUPING_METHOD_FOR_SU
,(SELECT MEANING FROM FND_LOOKUPS
			WHERE LOOKUP_CODE = pjfPROTypeE0.VENDOR_INVOICE_GROUPING_CODE
			AND LOOKUP_TYPE = 'PJF_VENDOR_INV_GROUPING_CODE') RES_EXPORT_SUPPLIER_INVOICES_T
 ,(SELECT DESCRIPTION FROM PJC_CINT_RATE_SCH_VL
	WHERE CINT_RATE_SCH_ID = pjfPROTypeE0.CINT_RATE_SCH_ID) RES_DEFAULT_CAPITALIZED_INTERE
 ,DECODE(pjfPROTypeE0.CINT_SCH_OVERRIDE_FLAG,'Y','Yes','No') RES_ALLOW_OVERRIDE
 ,pjfPROTypeE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
 ,pjfPROTypeE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
 ,pjfPROTypeE0.CREATED_BY RSC_CREATED_BY
 ,pjfPROTypeE0.CREATION_DATE RSC_CREATION_DATE
 ,NULL RSC_LEDGER_ID
 ,NULL RSC_CHART_OF_ACCOUNTS_ID
 ,NULL RSC_BUSINESS_UNIT_ID
 ,NULL RSC_LEGAL_ENTITY_ID
 ,NULL RSC_ORGANIZATION_ID
 ,NULL RSC_BUSINESS_GROUP_ID
 ,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJF_PROJECT_TYPES_VL pjfPROTypeE0
ORDER BY 1

	

