/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Time%20Repository%20Rule%20Templates%20-%20Outputs.sql $:
 * $Id: Manage Time Repository Rule Templates - Outputs.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT hwnRuleTMPEO.TEMPLATE_NAME  RES_NAME
,SUBSTR(hwnRuleTMPLTuseEO.DISPLAY_SEQUENCE,-1,1) RES_DISPLAY_SEQUENCE
,hwnRuleTMPLTuseEO.OUTPUT_NAME RES_OUTPUT_NAME
,(SELECT 'Output Group:'||' '||hwnRuleTMPLTuseEO.TBB_GROUP_NUMBER FROM DUAL) RES_OUTPUT_GROUP
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE = 'HWM_RT_MSG_SEVERITY' 
	AND LOOKUP_CODE = hwnRuleTMPLTuseEO.MSG_SEVERITY AND LANGUAGE = USERENV('LANG'))RES_MESSAGE_SEVERITY
,hwnRuleTMPLTuseEO.ATRB_FLD_NAME RES_TIME_ATTRIBUTE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE = 'HWM_RULE_OUTPUT_VALUE_TYPE' 
	AND LOOKUP_CODE = hwnRuleTMPLTuseEO.OUTPUT_VALUE_TYPE  AND LANGUAGE = USERENV('LANG')) RES_VALUE_TYPE
,(SELECT VALUE_SET_CODE FROM FND_VS_VALUE_SETS 
	WHERE VALUE_SET_ID = hwnRuleTMPLTuseEO.VALUE_SET_ID) RES_VALUE_SET 
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE = 'HWM_TMPLT_OUTPUT_SOURCE' 
	AND LOOKUP_CODE = hwnRuleTMPLTuseEO.OUTPUT_SOURCE  AND LANGUAGE = USERENV('LANG')) RES_OUTPUT_SOURCE
,hwnRuleTMPLTuseEO.USER_DEFINED_OUT_NAME RES_DISPLAY_NAME



,hwnRuleTMPLTuseEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hwnRuleTMPLTuseEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hwnRuleTMPLTuseEO.CREATED_BY RSC_CREATED_BY
,hwnRuleTMPLTuseEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HWM_RULE_TMPLTS_VL hwnRuleTMPEO
,HWM_RULE_TMPLT_USAGES_VL hwnRuleTMPLTuseEO
WHERE hwnRuleTMPEO.RULE_TMPLTS_ID = hwnRuleTMPLTuseEO.RULE_TMPLTS_ID
ORDER BY hwnRuleTMPEO.TEMPLATE_NAME , hwnRuleTMPLTuseEO.DISPLAY_SEQUENCE
