/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Absence%20Categories%20-%20Absence%20Category%20-%20DFF.sql $:
 * $Id: Manage Absence Categories - Absence Category - DFF.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10110##RES##ANC_ABSENCE_CATEGORIES_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_DATE,ATTRIBUTE_NUMBER

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

SELECT ancABSENCECATLEO.NAME RES_NAME
,(SELECT TERRITORY_SHORT_NAME 
	FROM FND_TERRITORIES_VL 
	WHERE TERRITORY_CODE = ancABSENCATEO.LEGISLATION_CODE
	) RES_LEGISLATION
,ancABSENCATEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ancABSENCATEO.ATTRIBUTE1
,ancABSENCATEO.ATTRIBUTE2
,ancABSENCATEO.ATTRIBUTE3
,ancABSENCATEO.ATTRIBUTE4
,ancABSENCATEO.ATTRIBUTE5
,ancABSENCATEO.ATTRIBUTE6
,ancABSENCATEO.ATTRIBUTE7
,ancABSENCATEO.ATTRIBUTE8
,ancABSENCATEO.ATTRIBUTE9
,ancABSENCATEO.ATTRIBUTE10
,ancABSENCATEO.ATTRIBUTE11
,ancABSENCATEO.ATTRIBUTE12
,ancABSENCATEO.ATTRIBUTE13
,ancABSENCATEO.ATTRIBUTE14
,ancABSENCATEO.ATTRIBUTE15
,ancABSENCATEO.ATTRIBUTE16
,ancABSENCATEO.ATTRIBUTE17
,ancABSENCATEO.ATTRIBUTE18
,ancABSENCATEO.ATTRIBUTE19
,ancABSENCATEO.ATTRIBUTE20
,ancABSENCATEO.ATTRIBUTE21
,ancABSENCATEO.ATTRIBUTE22
,ancABSENCATEO.ATTRIBUTE23
,ancABSENCATEO.ATTRIBUTE24
,ancABSENCATEO.ATTRIBUTE25
,ancABSENCATEO.ATTRIBUTE26
,ancABSENCATEO.ATTRIBUTE27
,ancABSENCATEO.ATTRIBUTE28
,ancABSENCATEO.ATTRIBUTE29
,ancABSENCATEO.ATTRIBUTE30
,ancABSENCATEO.ATTRIBUTE_NUMBER1
,ancABSENCATEO.ATTRIBUTE_NUMBER2
,ancABSENCATEO.ATTRIBUTE_NUMBER3
,ancABSENCATEO.ATTRIBUTE_NUMBER4
,ancABSENCATEO.ATTRIBUTE_NUMBER5
,ancABSENCATEO.ATTRIBUTE_NUMBER6
,ancABSENCATEO.ATTRIBUTE_NUMBER7
,ancABSENCATEO.ATTRIBUTE_NUMBER8
,ancABSENCATEO.ATTRIBUTE_NUMBER9
,ancABSENCATEO.ATTRIBUTE_NUMBER10
,ancABSENCATEO.ATTRIBUTE_NUMBER11
,ancABSENCATEO.ATTRIBUTE_NUMBER12
,ancABSENCATEO.ATTRIBUTE_NUMBER13
,ancABSENCATEO.ATTRIBUTE_NUMBER14
,ancABSENCATEO.ATTRIBUTE_NUMBER15
,ancABSENCATEO.ATTRIBUTE_NUMBER16
,ancABSENCATEO.ATTRIBUTE_NUMBER17
,ancABSENCATEO.ATTRIBUTE_NUMBER18
,ancABSENCATEO.ATTRIBUTE_NUMBER19
,ancABSENCATEO.ATTRIBUTE_NUMBER20
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE1, 'DD-Mon-YYYY') ATTRIBUTE_DATE1
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE2, 'DD-Mon-YYYY') ATTRIBUTE_DATE2
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE3, 'DD-Mon-YYYY') ATTRIBUTE_DATE3
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE4, 'DD-Mon-YYYY') ATTRIBUTE_DATE4
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE5, 'DD-Mon-YYYY') ATTRIBUTE_DATE5
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE6, 'DD-Mon-YYYY') ATTRIBUTE_DATE6
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE7, 'DD-Mon-YYYY') ATTRIBUTE_DATE7
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE8, 'DD-Mon-YYYY') ATTRIBUTE_DATE8
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE9, 'DD-Mon-YYYY') ATTRIBUTE_DATE9
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE10, 'DD-Mon-YYYY') ATTRIBUTE_DATE10
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE11, 'DD-Mon-YYYY') ATTRIBUTE_DATE11
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE12, 'DD-Mon-YYYY') ATTRIBUTE_DATE12
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE13, 'DD-Mon-YYYY') ATTRIBUTE_DATE13
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE14, 'DD-Mon-YYYY') ATTRIBUTE_DATE14
, TO_CHAR(ancABSENCATEO.ATTRIBUTE_DATE15, 'DD-Mon-YYYY') ATTRIBUTE_DATE15
,ancABSENCATEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ancABSENCATEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ancABSENCATEO.CREATED_BY RSC_CREATED_BY
,ancABSENCATEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,ancABSENCATEO.LEGISLATION_CODE RSC_COUNTRY_ID
FROM ANC_ABSENCE_CATEGORIES_F_TL ancABSENCECATLEO
,ANC_ABSENCE_CATEGORIES_F ancABSENCATEO
WHERE ancABSENCECATLEO.ABSENCE_CATEGORY_ID = ancABSENCATEO.ABSENCE_CATEGORY_ID
AND SYSDATE BETWEEN ancABSENCECATLEO.EFFECTIVE_START_DATE AND NVL(ancABSENCECATLEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND SYSDATE BETWEEN ancABSENCATEO.EFFECTIVE_START_DATE AND NVL(ancABSENCATEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND ancABSENCECATLEO.LANGUAGE = USERENV('LANG')
AND (ancABSENCATEO.ATTRIBUTE_CATEGORY IS NOT NULL OR
ancABSENCATEO.ATTRIBUTE1 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE2 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE3 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE4 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE5 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE6 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE7 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE8 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE9 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE10 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE11 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE12 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE13 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE14 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE15 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE16 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE17 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE18 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE19 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE20 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE21 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE22 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE23 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE24 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE25 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE26 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE27 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE28 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE29 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE30 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER11 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER12 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER13 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER14 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER15 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER16 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER17 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER18 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER19 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_NUMBER20 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE1 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE2 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE3 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE4 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE5 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE6 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE7 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE8 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE10 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE11 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE12 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE13 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE14 IS NOT NULL OR 
ancABSENCATEO.ATTRIBUTE_DATE15 IS NOT NULL 
 )
ORDER BY RES_NAME