/* ****************************************************************************
* $Revision: 78229 $:
* $Author: pisan.jariyasettachok $:
* $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Worker%20Time%20Entry%20Profiles%20-%20Manager%20View.sql $:
* $Id: Manage Worker Time Entry Profiles - Manager View.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
* ****************************************************************************
* Description:
* ************************************************************************** */



SELECT * FROM (
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME 
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Create' RES_PARENT_TIME_CARD_STATUS
,NULL RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE1,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE32 RES_DAYS_BEFORE
,hxtSOVEO.VALUE33 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--VIEW ONLY
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME 
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'View Only' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'ENTERED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE7,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE44 RES_DAYS_BEFORE
,hxtSOVEO.VALUE45 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--VIEW ONLY
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'View Only' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'SAVED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE6,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE42 RES_DAYS_BEFORE
,hxtSOVEO.VALUE43 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--VIEW ONLY
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'View Only' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'SUBMITTED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE4,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE38 RES_DAYS_BEFORE
,hxtSOVEO.VALUE39 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--VIEW ONLY
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'View Only' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'REJECTED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE5,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE40 RES_DAYS_BEFORE
,hxtSOVEO.VALUE41 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--VIEW ONLY
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'View Only' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'APPROVED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE2,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE34 RES_DAYS_BEFORE
,hxtSOVEO.VALUE35 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--EDIT
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Edit' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'ENTERED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE13,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE56 RES_DAYS_BEFORE
,hxtSOVEO.VALUE57 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--EDIT
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Edit' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'SAVED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE12,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE54 RES_DAYS_BEFORE
,hxtSOVEO.VALUE55 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--EDIT
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Edit' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'SUBMITTED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE10,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE50 RES_DAYS_BEFORE
,hxtSOVEO.VALUE51 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--EDIT
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Edit' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'REJECTED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE11,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE52 RES_DAYS_BEFORE
,hxtSOVEO.VALUE53 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--EDIT
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Edit' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'APPROVED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE8,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE46 RES_DAYS_BEFORE
,hxtSOVEO.VALUE47 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--DELETE
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Delete' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'ENTERED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE19,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE68 RES_DAYS_BEFORE
,hxtSOVEO.VALUE69 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--DELETE
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Delete' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'SAVED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE18,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE66 RES_DAYS_BEFORE
,hxtSOVEO.VALUE67 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--DELETE
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Delete' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'SUBMITTED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE16,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE62 RES_DAYS_BEFORE
,hxtSOVEO.VALUE63 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--DELETE
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Delete' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'REJECTED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE17,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE64 RES_DAYS_BEFORE
,hxtSOVEO.VALUE65 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

UNION ALL

--DELETE
(SELECT  hxtSPEO.NAME RES_PROFILE_NAME  
,TO_CHAR(hxtSOVEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(hxtSOVEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,'Delete' RES_PARENT_TIME_CARD_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = 'APPROVED'
	AND LOOKUP_TYPE =  'ORA_HWM_SP_TC_STATUS' AND LANGUAGE = USERENV('LANG')) RES_TIME_CARD_STATUS
,DECODE(hxtSOVEO.VALUE14,'Y','Yes','No') RES_ENABLE
,hxtSOVEO.VALUE58 RES_DAYS_BEFORE
,hxtSOVEO.VALUE59 RES_DAYS_AFTER

,hxtSOVEO.CREATED_BY  AS RSC_CREATED_BY
,hxtSOVEO.CREATION_DATE AS RSC_CREATION_DATE
,hxtSOVEO.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,hxtSOVEO.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
, null RSC_LEDGER_ID
, null RSC_CHART_OF_ACCOUNTS_ID
, null RSC_BUSINESS_UNIT_ID
, null RSC_LEGAL_ENTITY_ID
, null RSC_ORGANIZATION_ID
, null RSC_BUSINESS_GROUP_ID
, NULL RSC_ENTERPRISE_ID
, NULL RSC_COUNTRY_ID
  

FROM HXT_SETUP_PROFILES_VL hxtSPEO 
,HXT_SETUP_OPTION_VALS hxtSOVEO

WHERE hxtSPEO.PRODUCT_AREA = 'WORKER_TIMECARD' 
AND hxtSOVEO.TYPE = 'MANAGER'
AND hxtSPEO.SETUP_PROFILE_ID = hxtSOVEO.SETUP_PROFILE_ID)

)

ORDER BY 1,2,4