/* ****************************************************************************
 * $Revision: 78339 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-04-20 08:58:35 +0700 (Wed, 20 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Plant%20Parameters%20-%20Plant%20Parameters.sql $:
 * $Id: Manage Plant Parameters - Plant Parameters.sql 78339 2022-04-20 01:58:35Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=RCS_MFG_PARAMETERS

SELECT (SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = RcsMfgParametersE0.ORGANIZATION_ID
	)
/*(SELECT ORGANIZATION_CODE  
	FROM HR_ORGANIZATION_V
	WHERE CLASSIFICATION_CODE = 'INV'
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND ORGANIZATION_ID = RcsMfgParametersE0.ORGANIZATION_ID 
	)*/ RES_ORGANIZATION
,(SELECT SCHEDULE_NAME
	FROM ZMM_SR_SCHEDULES_VL
	WHERE SCHEDULE_ID = RcsMfgParametersE0.MFG_CALENDAR
	) RES_MANUFACTURING_CALENDAR
,DECODE(RcsMfgParametersE0.ENABLE_IOT_FLAG,'Y','Yes','No') RES_ENABLE_SYNCHRONIZATION_TO_
,DECODE(RcsMfgParametersE0.ENABLE_PROCESS_FLAG,'Y','Yes','No') RES_ENABLE_PROCESS_MANUFACTURI
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_DEFAULT_WORK_METHODS'
	AND LOOKUP_CODE = RcsMfgParametersE0.DEF_WORK_METHOD
	) RES_DEFAULT_WORK_METHOD
,RcsMfgParametersE0.DEF_SUPPLY_SUBINV RES_DEFAULT_SUPPLY_SUBINVENTOR
,(SELECT FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'INV',KEY_FLEX_CODE => 'MTLL',STRUCTURE_NUMBER =>
	STRUCTURE_INSTANCE_NUMBER,COMBINATION_ID => INVENTORY_LOCATION_ID,DATA_SET_NUMBER =>SUBINVENTORY_ID)
	FROM INV_ITEM_LOCATIONS
	WHERE INVENTORY_LOCATION_ID = RcsMfgParametersE0.DEF_SUPPLY_LOCATOR
	AND ORGANIZATION_ID = RcsMfgParametersE0.ORGANIZATION_ID
	) RES_DEFAULT_SUPPLY_LOCATOR
,RcsMfgParametersE0.DEF_COMPLTN_SUBINV RES_DEFAULT_COMPLETION_SUBINVE
,(SELECT FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'INV',KEY_FLEX_CODE => 'MTLL',STRUCTURE_NUMBER =>
	STRUCTURE_INSTANCE_NUMBER,COMBINATION_ID => INVENTORY_LOCATION_ID,DATA_SET_NUMBER =>SUBINVENTORY_ID)
	FROM INV_ITEM_LOCATIONS
	WHERE INVENTORY_LOCATION_ID = RcsMfgParametersE0.DEF_COMPLTN_LOCATOR
	AND ORGANIZATION_ID = RcsMfgParametersE0.ORGANIZATION_ID
	) RES_DEFAULT_COMPLETION_LOCATOR
,RcsMfgParametersE0.STARTING_OPRN_SEQ RES_STARTING_OPERATION_SEQUENC
,RcsMfgParametersE0.OPRN_SEQ_INCREMENT RES_OPERATION_SEQUENCE_INCREME
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_PHTM_OPR_INHERIT'
	AND LOOKUP_CODE = RcsMfgParametersE0.PHNTM_OPRN_INHERIT
	) RES_PHANTOM_OPERATION_INHERITA
,RcsMfgParametersE0.WORK_ORDER_PREFIX RES_WORK_ORDER_PREFIX
,RcsMfgParametersE0.WO_STARTING_NUMBER RES_WORK_ORDER_STARTING_NUMBER
,RcsMfgParametersE0.DEF_OVERCOMPLTN_TOL RES_DEFAULT_OVERCOMPLETION_TOL
,DECODE(RcsMfgParametersE0.INC_COMP_YIELD_FLAG,'Y','Yes','No') RES_INCLUDE_COMPONENT_YIELD_IN
,DECODE(RcsMfgParametersE0.AUTO_ASSC_SER_NUM_WO,'Y','Yes','No') RES_AUTOMATICALLY_ASSOCIATE_SE
,(SELECT PICK_GROUPING_RULE_NAME
	FROM INV_PICK_GROUPING_RULES_VL
	WHERE PICK_GROUPING_RULE_ID = RcsMfgParametersE0.PICK_SLIP_GROUPING_RULE 
	) RES_DEFAULT_PICK_SLIP_GROUPING
,DECODE(RcsMfgParametersE0.PRINT_PICK_SLIPS_FLAG,'Y','Yes','No')RES_PRINT_PICK_SLIPS
,DECODE(RcsMfgParametersE0.INCLUDE_PULL_COMP_FLAG,'Y','Yes','No') RES_INCLUDE_PULL_COMPONENTS_FO
,DECODE(RcsMfgParametersE0.ISSUE_PUSH_COMP_FLAG,'Y','Yes','No') RES_ISSUE_PUSH_COMPONENTS_ON_P
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_PUR_REQ_CREATE_TIME'
	AND LOOKUP_CODE = RcsMfgParametersE0.PURCHASE_REQ_CREATE_TIME
	) RES_PURCHASE_REQUISITION_TRIGG
,RcsMfgParametersE0.MAX_SCHED_DURATION RES_MAXIMUM_SCHEDULING_DURATIO
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_DEFAULT_LOT_NUM'
	AND LOOKUP_CODE = RcsMfgParametersE0.DEF_WORK_METHOD 
	) RES_DEFAULT_LOT_NUMBER_USED_FO
,DECODE(RcsMfgParametersE0.ALLOW_DIRECT_PURCH_WO,'Y','Yes','No') RES_ALLOW_DIRECT_PURCHASES_FOR
,DECODE(RcsMfgParametersE0.ALLOW_RESRVTNS_WO_FLAG,'Y','Yes','No') RES_ALLOW_RESERVATIONS_FOR_WOR
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_DEF_TRANS_MODE'
	AND LOOKUP_CODE = RcsMfgParametersE0.DEF_TRANS_MODE
	) RES_DEFAULT_TRANSACTION_MODE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_DEF_TRANS_QTY'
	AND LOOKUP_CODE = RcsMfgParametersE0.DEF_TRANS_QTY
	) RES_DEFAULT_TRANSACTION_QUANTI
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_STARTSTOP_CAPTURELVL'
	AND LOOKUP_CODE = RcsMfgParametersE0.STARTSTOP_CAPTURE_LVL
	) RES_CAPTURE_LEVEL_FOR_SERIALIZ
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_MTL_REPORTING_LVL'
	AND LOOKUP_CODE = RcsMfgParametersE0.MTL_REPORTING_LVL
	) RES_MATERIAL_REPORTING_LEVEL_F
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_ALLOW_BF_QTY_CHG'
	AND LOOKUP_CODE = RcsMfgParametersE0.QTY_CHNG_BACKFLUSH
	) RES_ALLOW_QUANTITY_CHANGES_DUR
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_RCS_BF_LOT_SELECTION'
	AND LOOKUP_CODE = RcsMfgParametersE0.BACKFLUSH_LOT_SELECTION
	) RES_LOT_SELECTION_DURING_BACKF
,DECODE(RcsMfgParametersE0.ALLOW_NEG_ISS_WO_SN_FLAG,'Y','Yes','No') RES_ALLOW_NEGATIVE_ISSUE_WITHO
,DECODE(RcsMfgParametersE0.MANUAL_ISSUE_ASSY_WO_FLAG,'Y','Yes','No') RES_MANUALLY_ISSUE_ASSEMBLY_TO
,DECODE(RcsMfgParametersE0.RESTRICT_LOT_FOR_RETURNS,'Y','Yes','No') RES_RESTRICT_LOT_NUMBERS_DURIN
,RcsMfgParametersE0.DEF_WO_TRAVELER_TMPLT RES_DEFAULT_WORK_ORDER_TRAVELE
,RcsMfgParametersE0.DEF_LABEL_TMPLT RES_DEFAULT_LABEL_TEMPLATE
,DECODE(RcsMfgParametersE0.PRINT_LABEL_EXTERNALLY,'Y','Yes','No') RES_PRINT_PRODUCT_LABELS_USING
,RcsMfgParametersE0.FORECAST_HORIZON RES_FORECAST_HORIZON_IN_DAYS
,RcsMfgParametersE0.GEN_WO_HORIZON RES_GENERATE_WORK_ORDERS_HORIZ

,RcsMfgParametersE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,RcsMfgParametersE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,RcsMfgParametersE0.CREATED_BY RSC_CREATED_BY
,RcsMfgParametersE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,RcsMfgParametersE0.ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM RCS_MFG_PARAMETERS RcsMfgParametersE0
ORDER BY RES_ORGANIZATION