/* ****************************************************************************
 * $Revision: 78239 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 22:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Absence%20Categories%20-%20Absence%20Category.sql $:
 * $Id: Manage Absence Categories - Absence Category.sql 78239 2022-04-07 15:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT ancABSENCECATEO.NAME RES_NAME
,(SELECT TERRITORY_SHORT_NAME 
	FROM FND_TERRITORIES_VL 
	WHERE TERRITORY_CODE = ancABSENCEO.LEGISLATION_CODE
	) RES_LEGISLATION
,ancABSENCEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ancABSENCEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ancABSENCEO.CREATED_BY RSC_CREATED_BY
,ancABSENCEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,ancABSENCEO.LEGISLATION_CODE RSC_COUNTRY_ID
FROM ANC_ABSENCE_CATEGORIES_F_TL ancABSENCECATEO
,ANC_ABSENCE_CATEGORIES_F ancABSENCEO
WHERE ancABSENCECATEO.ABSENCE_CATEGORY_ID = ancABSENCEO.ABSENCE_CATEGORY_ID
AND SYSDATE BETWEEN ancABSENCECATEO.EFFECTIVE_START_DATE AND NVL(ancABSENCECATEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND SYSDATE BETWEEN ancABSENCEO.EFFECTIVE_START_DATE AND NVL(ancABSENCEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND ancABSENCECATEO.LANGUAGE = USERENV('LANG')
ORDER BY ancABSENCECATEO.NAME