/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Coverages%20Across%20Plan%20Types%20-%20Associated%20Plan%20Types.sql $:
 * $Id: Manage Coverages Across Plan Types - Associated Plan Types.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT  benACRPTIPCVGEO.NAME RES_COVERAGE_LIMIT_NAME
,(SELECT NAME FROM BEN_PGM_F WHERE PGM_ID = benACRPTIPCVGEO.PGM_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_PROGRAM_NAME
,(SELECT NAME FROM BEN_PL_TYP_F WHERE PL_TYP_ID = benPTIPEO.PL_TYP_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_PLAN_TYPE_NAME

,benPTIPEO.LAST_UPDATED_BY 			RSC_LAST_UPDATED_BY
,benPTIPEO.LAST_UPDATE_DATE 		RSC_LAST_UPDATE_DATE
,benPTIPEO.CREATED_BY 				RSC_CREATED_BY
,benPTIPEO.CREATION_DATE 			RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM BEN_ACRS_PTIP_CVG_F benACRPTIPCVGEO
,BEN_PTIP_F benPTIPEO
WHERE benACRPTIPCVGEO.ACRS_PTIP_CVG_ID = benPTIPEO.ACRS_PTIP_CVG_ID
AND SYSDATE BETWEEN benACRPTIPCVGEO.EFFECTIVE_START_DATE AND NVL(benACRPTIPCVGEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND SYSDATE BETWEEN benPTIPEO.EFFECTIVE_START_DATE AND NVL(benPTIPEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
