/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Extended%20Lookup%20Codes%20-%20Lookup%20Codes.sql $:
 * $Id: Manage Extended Lookup Codes - Lookup Codes.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
SELECT fndLOOKUPTYPEO.MEANING RES_LOOKUP_TYPE
,(SELECT TERRITORY_SHORT_NAME FROM FND_TERRITORIES_VL WHERE TERRITORY_CODE = hcmEXTENDEO.LEGISLATION_CODE) RES_COUNTRY
,fndLOOKUPVALEO.MEANING RES_LOOKUP_CODE
,hcmEXTENDEO.EXTENDED_LOOKUP_CODE RES_EXTENDED_CODE
,hcmEXTENDEO.EXTENDED_LOOKUP_CODE_NAME RES_EXTENDED_NAME
,DECODE(hcmEXTENDEO.ENTERPRISE_ID,0,'Yes',1,'No') RES_ALL_ENTERPRISES
,hcmEXTENDEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hcmEXTENDEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hcmEXTENDEO.CREATED_BY RSC_CREATED_BY
,hcmEXTENDEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HCM_EXTENDED_LOOKUP_CODES_VL hcmEXTENDEO
,FND_LOOKUP_TYPES_VL fndLOOKUPTYPEO
,FND_LOOKUP_VALUES fndLOOKUPVALEO
WHERE hcmEXTENDEO.LOOKUP_TYPE = fndLOOKUPTYPEO.LOOKUP_TYPE
AND fndLOOKUPVALEO.LOOKUP_TYPE = hcmEXTENDEO.LOOKUP_TYPE
AND fndLOOKUPVALEO.LOOKUP_CODE = hcmEXTENDEO.LOOKUP_CODE
AND fndLOOKUPVALEO.LANGUAGE = USERENV('LANG')
AND SYSDATE BETWEEN fndLOOKUPVALEO.START_DATE_ACTIVE AND NVL(fndLOOKUPVALEO.END_DATE_ACTIVE,TO_DATE('4712-12-31','YYYY-MM-DD'))
ORDER BY RES_LOOKUP_TYPE,RES_LOOKUP_CODE,RES_EXTENDED_CODE,RES_EXTENDED_NAME