/* ****************************************************************************
 * $Revision: 55453 $:
 * $Author: dhara.pithadiya $:
 * $Date: 2016-05-25 18:43:01 +0700 (Wed, 25 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20AutoInvoice%20Line%20Ordering%20Rules%20-%20AutoInvoice%20Line%20Ordering%20Rules.sql $:
 * $Id: Manage AutoInvoice Line Ordering Rules - AutoInvoice Line Ordering Rules.sql 55453 2016-05-25 11:43:01Z dhara.pithadiya $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=WSH_PICKING_RULES
-- RSC_PREREQUISITE_OBJECTS=WSH_PICK_SEQUENCE_RULES_VL
-- RSC_PREREQUISITE_OBJECTS=INV_PICK_GROUPING_RULES_VL

SELECT WshPickingRules.PICKING_RULE_NAME RES_NAME
,OrgOrganizationDefinitionsPE1.ORGANIZATION_CODE RES_SHIP_FROM_ORGANIZATION
,WshPickingRules.PICK_FROM_SUBINVENTORY RES_PICK_FROM_SUBINVENTORY
,FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'INV',KEY_FLEX_CODE => 'MTLL',STRUCTURE_NUMBER =>
	MtlSecondaryInventories1.STRUCTURE_INSTANCE_NUMBER,COMBINATION_ID => MtlSecondaryInventories1.INVENTORY_LOCATION_ID,
	DATA_SET_NUMBER => MtlSecondaryInventories1.SUBINVENTORY_ID) RES_PICK_FROM_LOCATOR
,WshPickingRules.DEFAULT_STAGE_SUBINVENTORY RES_STAGING_SUBINVENTORY
,FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'INV',KEY_FLEX_CODE => 'MTLL',STRUCTURE_NUMBER =>
	MtlSecondaryInventories.STRUCTURE_INSTANCE_NUMBER,COMBINATION_ID => MtlSecondaryInventories.INVENTORY_LOCATION_ID,
	DATA_SET_NUMBER => MtlSecondaryInventories.SUBINVENTORY_ID) RES_STAGING_LOCATOR
,PickSequenceRulePEO.PICK_SEQUENCE_RULE_NAME RES_RELEASE_SEQUENCE_RULE
,PickingGroupingRulePEO.PICK_GROUPING_RULE_NAME RES_PICK_SLIP_GROUPING_RULE
,DECODE(WshPickingRules.AUTO_PICK_CONFIRM_FLAG,'Y','Yes','No') RES_AUTOCONFIRM_PICKS
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_WSH_TRD_COMP_SCRN_MTHD'
	AND LOOKUP_CODE = WshPickingRules.TRADE_COMPLIANCE_METHOD
	) RES_TRADE_COMPLIANCE_SCREENING
,ShipConfirmRulePEO.SHIP_CONFIRM_RULE_NAME RES_SHIP_CONFIRM_RULE
,DECODE(WshPickingRules.AUTOCREATE_DELIVERY_FLAG,'Y','Yes','No') RES_CREATE_SHIPMENTS
,DECODE(WshPickingRules.AC_DELIVERY_CRITERIA,'Y','Within an order','N','Across orders') RES_SHIPMENT_CREATION_CRITERIA
,(CASE
		WHEN WshPickingRules.AUTO_PICK_CONFIRM_FLAG = 'Y'
		THEN DECODE(WshPickingRules.AUTOPACK_FLAG,'Y','Yes','No')
	END) RES_AUTOMATICALLY_PACK
,(CASE
		WHEN WshPickingRules.AUTO_PICK_CONFIRM_FLAG = 'N'
		THEN DECODE(WshPickingRules.APPEND_FLAG,'Y','Yes','No')
	END) RES_APPEND_SHIPMENTS
,WshPickingRules.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,WshPickingRules.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,WshPickingRules.CREATED_BY RSC_CREATED_BY
,WshPickingRules.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,WshPickingRules.ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM WSH_PICKING_RULES WshPickingRules
,INV_ORGANIZATION_DEFINITIONS_V OrgOrganizationDefinitionsPE1
,WSH_PICK_SEQUENCE_RULES_VL PickSequenceRulePEO
,INV_PICK_GROUPING_RULES_VL PickingGroupingRulePEO
,WSH_SHIP_CONFIRM_RULES ShipConfirmRulePEO
,INV_ITEM_LOCATIONS MtlSecondaryInventories
,INV_ITEM_LOCATIONS MtlSecondaryInventories1
WHERE WshPickingRules.ORGANIZATION_ID        = OrgOrganizationDefinitionsPE1.ORGANIZATION_ID(+)
AND WshPickingRules.PICK_SEQUENCE_RULE_ID    = PickSequenceRulePEO.PICK_SEQUENCE_RULE_ID(+)
AND WshPickingRules.PICK_GROUPING_RULE_ID    = PickingGroupingRulePEO.PICK_GROUPING_RULE_ID(+)
AND WshPickingRules.SHIP_CONFIRM_RULE_ID     = ShipConfirmRulePEO.SHIP_CONFIRM_RULE_ID(+)
AND WshPickingRules.DEFAULT_STAGE_LOCATOR_ID = MtlSecondaryInventories.INVENTORY_LOCATION_ID(+)
AND WshPickingRules.PICK_FROM_LOCATOR_ID     = MtlSecondaryInventories1.INVENTORY_LOCATION_ID(+)
ORDER BY WshPickingRules.PICKING_RULE_NAME