/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Question%20Library%20-%20Folder.sql $:
 * $Id: Manage Question Library - Folder.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=HRQ_QUESTIONS_VL

SELECT (SELECT NAME 
	FROM HRQ_SUBSCRIBERS_TL	
	WHERE LANGUAGE = USERENV('LANG') 
	AND SUBSCRIBER_ID = hrqCATEO.SUBSCRIBER_ID
	) RES_SUBSCRIBER
,(SELECT NAME 
	FROM HRQ_CATEGORIES_TL 
	WHERE LANGUAGE = USERENV('LANG')
	AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,1)+3,INSTR(HIER,'###',1,2)-4)
	) RES_PARENT_FOLDER_1
,(SELECT NAME 
	FROM HRQ_CATEGORIES_TL 
	WHERE LANGUAGE = USERENV('LANG')
	AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,2)+3,INSTR(HIER,'###',1,3) - INSTR(HIER,'###',1,2)-3)
	)  RES_PARENT_FOLDER_2
,(SELECT NAME 
	FROM HRQ_CATEGORIES_TL 
	WHERE LANGUAGE = USERENV('LANG')
	AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,3)+3,INSTR(HIER,'###',1,4) - INSTR(HIER,'###',1,3)-3) 
	) RES_PARENT_FOLDER_3
,(SELECT NAME 
	FROM HRQ_CATEGORIES_TL 
	WHERE LANGUAGE = USERENV('LANG')
	AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,4)+3,INSTR(HIER,'###',1,5) - INSTR(HIER,'###',1,4)-3) 
	) RES_PARENT_FOLDER_4
,(SELECT NAME 
	FROM HRQ_CATEGORIES_TL 
	WHERE LANGUAGE = USERENV('LANG')
	AND CATEGORY_ID = SUBSTR(HIER,INSTR(HIER,'###',1,5)+3,INSTR(HIER,'###',1,6) - INSTR(HIER,'###',1,5)-3) 
	) RES_PARENT_FOLDER_5
,hrqCATEO.NAME RES_FOLDER
,hrqCATEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hrqCATEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hrqCATEO.CREATED_BY RSC_CREATED_BY
,hrqCATEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM (SELECT NAME
    ,SUBSCRIBER_ID
    ,PARENT_CATEGORY_ID
	,LEVEL LV
	,REPLACE(SYS_CONNECT_BY_PATH(NVL(PARENT_CATEGORY_ID,0),'###'),'###0',NULL)||'###' HIER
    ,LAST_UPDATED_BY
    ,LAST_UPDATE_DATE
    ,CREATED_BY
    ,CREATION_DATE
	FROM HRQ_CATEGORIES_VL
	WHERE SUBSCRIBER_ID IN (SELECT SUBSCRIBER_ID 
		FROM HRQ_SUBSCRIBERS_VL 
		WHERE SUBSCRIBER_CODE IN ('HRA','PER_CHK','WLF_ASSESSMENTS','WFL','WLF_ENROLLMENTS','HWR','IRC','HWRTMS','HXLTLTC','HNS'))
	AND CONTAIN_QUESTIONS !='N'
	START WITH PARENT_CATEGORY_ID IS NULL
	CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID
	) hrqCATEO
ORDER BY 1,LV,3