/* ****************************************************************************
 * $Revision: 80185 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2023-02-16 16:49:42 +0700 (Thu, 16 Feb 2023) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Mapping%20Sets%20-%20Account%20combination%20Mappings.sql $:
 * $Id: Manage Mapping Sets - Account combination Mappings.sql 80185 2023-02-16 09:49:42Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- FIELD_TO_APPLY_FUNCTION=RES_OUTPUT/GET_CODE_COMBINATION
-- VALUE_SET_LOGIC_TO_APPLY_FIELDS=RES_INPUT_SOURCE1,RES_INPUT_SOURCE2,RES_INPUT_SOURCE3,RES_INPUT_SOURCE4,RES_INPUT_SOURCE5,RES_INPUT_SOURCE6,RES_INPUT_SOURCE7,RES_INPUT_SOURCE8,RES_INPUT_SOURCE9,RES_INPUT_SOURCE10

WITH INPUT_SOURCE1 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE InputsourcesE0.INPUT_SEQ = 1
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE2 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE InputsourcesE0.INPUT_SEQ = 2
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE3 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE INPUT_SEQ = 3
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE4 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE INPUT_SEQ = 4
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE5 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE INPUT_SEQ = 5
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE6 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE INPUT_SEQ = 6
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE7 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE INPUT_SEQ = 7
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE8 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE INPUT_SEQ = 8
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE9 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE INPUT_SEQ = 9
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
,INPUT_SOURCE10 AS (SELECT InputsourcesE0.LOOKUP_TYPE
	,InputsourcesE0.VIEW_APPLICATION_ID
	,InputsourcesE0.VALUE_SET_ID
	,InputsourcesE0.FLEX_SEGMENT
	,InputsourcesE0.APPLICATION_ID
	,InputsourcesE0.MAPPING_SET_CODE
	,InputsourcesE0.AMB_CONTEXT_CODE
	,ValueSet.VALIDATION_TYPE
	,ValueSet.VALUE_SET_CODE
	FROM XLA_MAPPING_SET_INPUTS InputsourcesE0
	,FND_VS_VALUE_SETS ValueSet
	WHERE INPUT_SEQ = 10
	AND InputsourcesE0.VALUE_SET_ID = ValueSet.VALUE_SET_ID(+))
	
SELECT APPLICATIONPEO.application_name RES_SUBLEDGER_APPLICATION
,MAPPINGSETEO.NAME RES_NAME
,MAPPINGSETEO.MAPPING_SET_CODE RES_SHORT_NAME
,DECODE(MAPPINGSETEO.FLEXFIELD_ASSIGN_MODE_CODE,'A','Account combination','S','Segment','Value set') RES_OUTPUT_TYPE
,KFSTRUCTINS.NAME RES_CHART_OF_ACCOUNTS
,'No' RES_DEFAULT
,(CASE
	WHEN INPUT_SOURCE1.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE1.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE1.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1
			AND lookups.LANGUAGE = USERENV('LANG'))
	/*WHEN INPUT_SOURCE1.VALUE_SET_CODE = 'CST_XLA_EGP_CATEGORIES_VS' AND MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1 = '*' THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1*/
	WHEN INPUT_SOURCE1.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE1.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE1.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1)
							WHEN INPUT_SOURCE1.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1)
							WHEN INPUT_SOURCE1.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1)
							WHEN INPUT_SOURCE1.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1)
							WHEN INPUT_SOURCE1.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1)
							WHEN INPUT_SOURCE1.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1)
							WHEN INPUT_SOURCE1.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1)
							ELSE
								INPUT_SOURCE1.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1
			END)
	WHEN INPUT_SOURCE1.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT1
	END) RES_INPUT_SOURCE1
,(CASE
	WHEN INPUT_SOURCE2.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE2.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE2.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE2.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE2.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE2.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2)
							WHEN INPUT_SOURCE2.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2)
							WHEN INPUT_SOURCE2.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2)
							WHEN INPUT_SOURCE2.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2)
							WHEN INPUT_SOURCE2.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2)
							WHEN INPUT_SOURCE2.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2)
							WHEN INPUT_SOURCE2.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2)
							ELSE
								INPUT_SOURCE2.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2
			END)
	WHEN INPUT_SOURCE2.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT2
	END) RES_INPUT_SOURCE2
,(CASE
	WHEN INPUT_SOURCE3.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE3.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE3.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE3.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE3.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE3.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3)
							WHEN INPUT_SOURCE3.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3)
							WHEN INPUT_SOURCE3.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3)
							WHEN INPUT_SOURCE3.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3)
							WHEN INPUT_SOURCE3.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3)
							WHEN INPUT_SOURCE3.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3)
							WHEN INPUT_SOURCE3.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3)
							ELSE
								INPUT_SOURCE3.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3
			END)
	WHEN INPUT_SOURCE3.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT3
	END) RES_INPUT_SOURCE3
,(CASE
	WHEN INPUT_SOURCE4.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE4.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE4.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE4.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE4.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE4.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4)
							WHEN INPUT_SOURCE4.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4)
							WHEN INPUT_SOURCE4.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4)
							WHEN INPUT_SOURCE4.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4)
							WHEN INPUT_SOURCE4.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4)
							WHEN INPUT_SOURCE4.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4)
							WHEN INPUT_SOURCE4.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4)
							ELSE
								INPUT_SOURCE4.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4
			END)
	WHEN INPUT_SOURCE4.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT4
	END) RES_INPUT_SOURCE4
,(CASE
	WHEN INPUT_SOURCE5.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE5.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE5.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE5.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE5.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE5.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5)
							WHEN INPUT_SOURCE5.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5)
							WHEN INPUT_SOURCE5.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5)
							WHEN INPUT_SOURCE5.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5)
							WHEN INPUT_SOURCE5.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5)
							WHEN INPUT_SOURCE5.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5)
							WHEN INPUT_SOURCE5.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5)
							ELSE
								INPUT_SOURCE5.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5
			END)
	WHEN INPUT_SOURCE5.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT5
	END) RES_INPUT_SOURCE5
,(CASE
	WHEN INPUT_SOURCE6.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE6.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE6.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE6.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE6.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE6.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6)
							WHEN INPUT_SOURCE6.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6)
							WHEN INPUT_SOURCE6.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6)
							WHEN INPUT_SOURCE6.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6)
							WHEN INPUT_SOURCE6.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6)
							WHEN INPUT_SOURCE6.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6)
							WHEN INPUT_SOURCE6.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6)
							ELSE
								INPUT_SOURCE6.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6
			END)
	WHEN INPUT_SOURCE6.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT6
	END) RES_INPUT_SOURCE6
,(CASE
	WHEN INPUT_SOURCE7.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE7.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE7.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE7.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE7.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE7.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7)
							WHEN INPUT_SOURCE7.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7)
							WHEN INPUT_SOURCE7.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7)
							WHEN INPUT_SOURCE7.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7)
							WHEN INPUT_SOURCE7.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7)
							WHEN INPUT_SOURCE7.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7)
							WHEN INPUT_SOURCE7.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7)
							ELSE
								INPUT_SOURCE7.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7
			END)
	WHEN INPUT_SOURCE7.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT7
	END) RES_INPUT_SOURCE7
,(CASE
	WHEN INPUT_SOURCE8.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE8.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE8.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE8.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE8.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE8.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8)
							WHEN INPUT_SOURCE8.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8)
							WHEN INPUT_SOURCE8.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8)
							WHEN INPUT_SOURCE8.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8)
							WHEN INPUT_SOURCE8.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8)
							WHEN INPUT_SOURCE8.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8)
							WHEN INPUT_SOURCE8.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8)
							ELSE
								INPUT_SOURCE8.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8
			END)
	WHEN INPUT_SOURCE8.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT8
	END) RES_INPUT_SOURCE8
,(CASE
	WHEN INPUT_SOURCE9.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE9.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE9.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE9.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE9.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE9.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9)
							WHEN INPUT_SOURCE9.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9)
							WHEN INPUT_SOURCE9.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9)
							WHEN INPUT_SOURCE9.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9)
							WHEN INPUT_SOURCE9.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9)
							WHEN INPUT_SOURCE9.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9)
							WHEN INPUT_SOURCE9.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9)
							ELSE
								INPUT_SOURCE9.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9
			END)
	WHEN INPUT_SOURCE9.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT9
	END) RES_INPUT_SOURCE9
,(CASE
	WHEN INPUT_SOURCE10.LOOKUP_TYPE IS NOT NULL THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES lookups
			WHERE lookups.LOOKUP_TYPE = INPUT_SOURCE10.LOOKUP_TYPE
			AND lookups.VIEW_APPLICATION_ID = INPUT_SOURCE10.VIEW_APPLICATION_ID
			AND lookups.LOOKUP_CODE = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10
			AND lookups.LANGUAGE = USERENV('LANG'))
	WHEN INPUT_SOURCE10.VALUE_SET_ID IS NOT NULL THEN
		(CASE
			WHEN INPUT_SOURCE10.VALIDATION_TYPE = 'TABLE' THEN
				(CASE
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10 = '*' THEN
						'*'
					WHEN MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10 IS NULL THEN
						NULL
					ELSE
						(CASE 
							WHEN INPUT_SOURCE10.VALUE_SET_CODE = 'ORA_CJM_XLA_BUSINESS_UNITS_VS' THEN
								(SELECT BU_NAME
									FROM FUN_ALL_BUSINESS_UNITS_V
									WHERE TO_CHAR(BU_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10)
							WHEN INPUT_SOURCE10.VALUE_SET_CODE = 'PJC_ORGANIZATION_VS' THEN
								(SELECT NAME
									FROM HR_ORGANIZATION_UNITS_F_TL
									WHERE language = userenv('LANG') 
									and trunc(sysdate) between effective_start_date and effective_end_date
									AND TO_CHAR(ORGANIZATION_ID) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10)
							WHEN INPUT_SOURCE10.VALUE_SET_CODE = 'ORA_PO_TAB_BUYER_VS' THEN
								(SELECT employee.global_name
									FROM per_employees_x employee
									WHERE TO_CHAR(employee.person_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10)
							WHEN INPUT_SOURCE10.VALUE_SET_CODE = 'ORA_PO_TAB_DELIVER_TO_LOCATION_VS' THEN
								(SELECT location.location_name
									FROM hr_locations location
									WHERE location.active_status = 'A' 
									AND TRUNC(sysdate) BETWEEN location.effective_start_date AND location.effective_end_date
									AND TO_CHAR(location.location_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10)
							WHEN INPUT_SOURCE10.VALUE_SET_CODE = 'ORA_PO_TAB_CATEGORY_VS' THEN
								(SELECT category.category_name
									FROM egp_categories_vl category
									WHERE ((( (TRUNC(sysdate) >= TRUNC(NVL(category.start_date_active, sysdate-1))) AND (TRUNC(sysdate) <= TRUNC(NVL(category.end_date_active, sysdate +1))))))
									AND TO_CHAR(category.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10)
							WHEN INPUT_SOURCE10.VALUE_SET_CODE = 'ORA_CST_XLA_CST_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10)
							WHEN INPUT_SOURCE10.VALUE_SET_CODE = 'ORA_CST_XLA_INV_CATEGORIES_VS' THEN
								(SELECT ec.category_name
									FROM egp_categories_vl ec
									WHERE TO_CHAR(ec.category_id) = MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10)
							ELSE
								INPUT_SOURCE10.VALUE_SET_CODE||'###R4C###'||MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10
							END)
					END)
			ELSE
				MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10
			END)
	WHEN INPUT_SOURCE10.FLEX_SEGMENT IS NOT NULL THEN
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10
	ELSE
		MAPPINGSETVALUEEO.INPUT_VALUE_CONSTANT10
	END) RES_INPUT_SOURCE10
,MAPPINGSETVALUEEO.VALUE_CODE_COMBINATION_ID RES_OUTPUT
,DECODE(TO_CHAR(MAPPINGSETVALUEEO.EFFECTIVE_START_DATE,'DD-MM-YYYY'),'01-01-1951',null,TO_CHAR(MAPPINGSETVALUEEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(MAPPINGSETVALUEEO.EFFECTIVE_END_DATE,'DD-MM-YYYY'),'31-12-4712',null,TO_CHAR(MAPPINGSETVALUEEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,MAPPINGSETVALUEEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,MAPPINGSETVALUEEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,MAPPINGSETVALUEEO.CREATED_BY RSC_CREATED_BY
,MAPPINGSETVALUEEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,KfStructIns.STRUCTURE_INSTANCE_NUMBER  RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM XLA_MAPPING_SETS_VL MAPPINGSETEO
,XLA_MAPPING_SET_FLAVORS MAPPINGSETFLAVOREO
,FND_KF_STR_INSTANCES_VL KfStructIns
,XLA_MAPPING_SET_VALUES MappingSetValueEO
,FND_KF_STR_INSTANCES_VL KEYFLEXFIELDSTRUCTUREINSTANC1
,XLA_SUBLEDGERS_TL APPLICATIONPEO
,INPUT_SOURCE1 
,INPUT_SOURCE2 
,INPUT_SOURCE3 
,INPUT_SOURCE4 
,INPUT_SOURCE5 
,INPUT_SOURCE6 
,INPUT_SOURCE7 
,INPUT_SOURCE8 
,INPUT_SOURCE9 
,INPUT_SOURCE10
WHERE MAPPINGSETEO.MAPPING_SET_CODE = MAPPINGSETFLAVOREO.MAPPING_SET_CODE
AND MAPPINGSETEO.APPLICATION_ID = MAPPINGSETFLAVOREO.APPLICATION_ID
AND MAPPINGSETEO.AMB_CONTEXT_CODE = MAPPINGSETFLAVOREO.AMB_CONTEXT_CODE
AND MAPPINGSETFLAVOREO.STRIPE_ID = KFSTRUCTINS.STRUCTURE_INSTANCE_NUMBER(+)
AND MAPPINGSETFLAVOREO.STRIPE_ID = MAPPINGSETVALUEEO.STRIPE_ID
AND MAPPINGSETFLAVOREO.MAPPING_SET_FLAVOR_ID          = MAPPINGSETVALUEEO.MAPPING_SET_FLAVOR_ID
AND(MappingSetValueEO.TRANSACTION_COA_ID              = KeyFlexfieldStructureInstanc1.STRUCTURE_INSTANCE_NUMBER (+)
AND((KeyFlexfieldStructureInstanc1.Application_id     = 101
AND KeyFlexfieldStructureInstanc1.key_flexfield_code  = 'GL#')
OR(KeyFlexfieldStructureInstanc1.APPLICATION_ID      IS NULL
AND KEYFLEXFIELDSTRUCTUREINSTANC1.KEY_FLEXFIELD_CODE IS NULL)))
AND MappingSetValueEO.AMB_CONTEXT_CODE                = 'DEFAULT'
and KFSTRUCTINS.NAME IS NOT NULL
AND MAPPINGSETEO.FLEXFIELD_ASSIGN_MODE_CODE = 'A'
AND MAPPINGSETEO.APPLICATION_ID = APPLICATIONPEO.APPLICATION_ID(+)
AND APPLICATIONPEO.LANGUAGE = USERENV('LANG')
AND MAPPINGSETVALUEEO.ENABLED_FLAG = 'Y'

AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE1.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE1.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE1.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE2.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE2.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE2.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE3.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE3.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE3.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE4.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE4.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE4.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE5.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE5.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE5.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE6.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE6.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE6.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE7.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE7.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE7.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE8.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE8.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE8.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE9.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE9.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE9.AMB_CONTEXT_CODE(+)
AND MAPPINGSETEO.MAPPING_SET_CODE = INPUT_SOURCE10.MAPPING_SET_CODE(+)
AND MAPPINGSETEO.APPLICATION_ID = INPUT_SOURCE10.APPLICATION_ID(+)
AND MAPPINGSETEO.AMB_CONTEXT_CODE = INPUT_SOURCE10.AMB_CONTEXT_CODE(+)

UNION

SELECT APPLICATIONPEO.application_name RES_SUBLEDGER_APPLICATION
,MAPPINGSETEO.NAME RES_NAME
,MAPPINGSETEO.MAPPING_SET_CODE RES_SHORT_NAME
,DECODE(MAPPINGSETEO.FLEXFIELD_ASSIGN_MODE_CODE,'A','Account combination','S','Segment','Value set') RES_OUTPUT_TYPE
,KFSTRUCTINS.NAME RES_CHART_OF_ACCOUNTS
,'Yes' RES_DEFAULT
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE1 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE1
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE2 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE2
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE3 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE3
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE4 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE4
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE5 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE5
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE6 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE6
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE7 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE7
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE8 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE8
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE9 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE9
,(CASE
	WHEN EXISTS (SELECT 1 FROM INPUT_SOURCE10 WHERE MAPPING_SET_CODE = MAPPINGSETEO.MAPPING_SET_CODE AND APPLICATION_ID = MAPPINGSETEO.APPLICATION_ID AND AMB_CONTEXT_CODE = MAPPINGSETEO.AMB_CONTEXT_CODE) THEN
		'*'
	END) RES_INPUT_SOURCE10
,MAPPINGSETFLAVOREO.DEFAULT_CCID RES_OUTPUT
,NULL RES_EFFECTIVE_START_DATE
,NULL RES_EFFECTIVE_END_DATE
,MAPPINGSETFLAVOREO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,MAPPINGSETFLAVOREO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,MAPPINGSETFLAVOREO.CREATED_BY RSC_CREATED_BY
,MAPPINGSETFLAVOREO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,KfStructIns.STRUCTURE_INSTANCE_NUMBER RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM XLA_MAPPING_SETS_VL MAPPINGSETEO
,XLA_MAPPING_SET_FLAVORS MAPPINGSETFLAVOREO
,FND_KF_STR_INSTANCES_VL KfStructIns
,XLA_SUBLEDGERS_TL APPLICATIONPEO
WHERE MAPPINGSETEO.FLEXFIELD_ASSIGN_MODE_CODE = 'A'
AND MAPPINGSETEO.MAPPING_SET_CODE = MAPPINGSETFLAVOREO.MAPPING_SET_CODE
AND MAPPINGSETEO.APPLICATION_ID = MAPPINGSETFLAVOREO.APPLICATION_ID
AND MAPPINGSETEO.AMB_CONTEXT_CODE = MAPPINGSETFLAVOREO.AMB_CONTEXT_CODE
AND MAPPINGSETFLAVOREO.STRIPE_ID = KFSTRUCTINS.STRUCTURE_INSTANCE_NUMBER(+)
AND APPLICATIONPEO.LANGUAGE = USERENV('LANG')
AND MAPPINGSETEO.APPLICATION_ID = APPLICATIONPEO.APPLICATION_ID(+)
and KFSTRUCTINS.NAME IS NOT NULL
AND MAPPINGSETFLAVOREO.DEFAULT_CCID IS NOT NULL


ORDER BY RES_SUBLEDGER_APPLICATION
,RES_NAME
,RES_CHART_OF_ACCOUNTS