/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Tax%20Regimes%20-%20Transaction%20Tax%20Regimes.sql $:
 * $Id: Manage Tax Regimes - Transaction Tax Regimes.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT QRSLT.TAX_REGIME_CODE RES_TAX_REGIME_CODE
,QRSLT.TAX_REGIME_NAME RES_TAX_REGIME_NAME
,QRSLT.CNTY_OR_GRP_CODE_VIEW RES_REGIME_LEVEL
,QRSLT.COUNTRY_CODE_VIEW RES_COUNTRY
,(SELECT GEOGRAPHY_TYPE_NAME
	FROM HZ_GEOGRAPHY_TYPES_VL
	WHERE GEOGRAPHY_TYPE = QRSLT.GEOGRAPHY_TYPE
	) RES_GEOGRAPHY_TYPE
,QRSLT.GEOGRAPHY_CODE RES_GEOGRAPHY_NAME
,QRSLT.PARENT_REGIME_CODE RES_PARENT_REGIME_CODE
,TO_CHAR(QRSLT.EFFECTIVE_FROM,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(QRSLT.EFFECTIVE_TO,'DD-Mon-YYYY') RES_END_DATE
,QRSLT.REGIME_GROUP RES_USED_TO_GROUP_REGIMES
,DECODE(QRSLT.CURRENCY_CODE,NULL,NULL,QRSLT.CURRENCY_CODE||' - '||QRSLT.TAX_CURRENCY_CODE_VIEW) RES_TAX_CURRENCY
--,QRSLT.MINIMUM_ACCOUNTABLE_UNIT RES_MINIMUM_ACCOUNTABLE_UNIT
,decode(substr(QRSLT.MINIMUM_ACCOUNTABLE_UNIT, 1, 1),'.', trim(to_char(QRSLT.MINIMUM_ACCOUNTABLE_UNIT,'0.99')) ,  QRSLT.MINIMUM_ACCOUNTABLE_UNIT) RES_MINIMUM_ACCOUNTABLE_UNIT
,QRSLT.TAX_PRECISION RES_TAX_PRECISION
,QRSLT.DEF_INCLUSIVE_FLAG_VIEW RES_TAX_INCLUSION_METHOD
,QRSLT.UserConversionType RES_CONVERSION_RATE_TYPE
,QRSLT.ROUNDING_RULE_CODE_VIEW RES_ROUNDING_RULE
,DECODE(QRSLT.ALLOW_ROUNDING_OVERRIDE_FLAG,'Y','Yes','No') RES_ALLOW_TAX_ROUNDING_OVERRID
,QRSLT.REP_TAX_AUTH_NAME RES_REPORTING_TAX_AUTHORITY
,QRSLT.COLL_TAX_AUTH_NAME RES_COLLECTING_TAX_AUTHORITY
,DECODE(QRSLT.REGN_NUM_SAME_AS_LE_FLAG,'Y','Yes','No') RES_USE_LEGAL_REGISTRATION_NUM
,DECODE(QRSLT.TAX_INCLUSIVE_OVERRIDE_FLAG,'Y','Yes','No') RES_ALLOW_OVERRIDE_AND_ENTRY_O
,DECODE(QRSLT.USE_TAX_REPORT_CONFIG_FLAG,'Y','Yes','No') RES_USE_TAX_REPORTING_CONFIGUR
,QRSLT.VALIDATION_TYPE RES_VALIDATION_TYPE
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ZX_VALIDATION_LEVEL'
	AND LOOKUP_CODE = QRSLT.VALIDATION_LEVEL
	) RES_VALIDATION_LEVEL
--,DECODE(QRSLT.VALIDATION_LEVEL,'ERROR','Error','WARNING','Warning',QRSLT.VALIDATION_LEVEL) RES_VALIDATION_LEVEL
,QRSLT.UNIQUE_VALIDATION_VIEW RES_DUPLICATE_VALIDATION_LEVEL
,DECODE(QRSLT.CROSS_REGIME_COMPOUNDING_FLAG,'Y','Yes','No') RES_ALLOW_CROSS_REGIME_COMPOUN
,QRSLT.REGIME_PRECEDENCE RES_COMPOUNDING_PRECEDENCE
,DECODE(QRSLT.HAS_OTHER_JURISDICTIONS_FLAG,'Y','Yes','No') RES_ALLOW_MULTIPLE_JURISDICTIO
,DECODE(QRSLT.ALLOW_RECOVERABILITY_FLAG,'Y','Yes','No') RES_ALLOW_TAX_RECOVERY
,DECODE(QRSLT.ALLOW_EXCEPTIONS_FLAG,'Y','Yes','No') RES_ALLOW_TAX_EXCEPTIONS
,DECODE(QRSLT.ALLOW_EXEMPTIONS_FLAG,'Y','Yes','No') RES_ALLOW_TAX_EXEMPTIONS
,QRSLT.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY RSC_CREATED_BY
,QRSLT.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM
	(SELECT ZxRegimesVl.TAX_REGIME_ID
	,ZxRegimesVl.TAX_REGIME_CODE
	,ZxRegimesVl.PARENT_REGIME_CODE
	,ZxRegimesVl.HAS_SUB_REGIME_FLAG
	,ZxRegimesVl.COUNTRY_OR_GROUP_CODE
	,ZxRegimesVl.COUNTRY_CODE
	,ZxRegimesVl.GEOGRAPHY_TYPE
	,ZxRegimesVl.GEOGRAPHY_ID
	,ZxRegimesVl.EFFECTIVE_FROM
	,ZxRegimesVl.EFFECTIVE_TO
	,ZxRegimesVl.EXCHANGE_RATE_TYPE
	,ZxRegimesVl.TAX_CURRENCY_CODE
	,ZxRegimesVl.THRSHLD_GROUPING_LVL_CODE
	,ZxRegimesVl.THRSHLD_CHK_TMPLT_CODE
	,ZxRegimesVl.PERIOD_SET_NAME
	,ZxRegimesVl.REP_TAX_AUTHORITY_ID
	,ZxRegimesVl.COLL_TAX_AUTHORITY_ID
	,ZxRegimesVl.ROUNDING_RULE_CODE
	,ZxRegimesVl.TAX_PRECISION
	,ZxRegimesVl.MINIMUM_ACCOUNTABLE_UNIT
	,ZxRegimesVl.TAX_STATUS_RULE_FLAG
	,ZxRegimesVl.DEF_PLACE_OF_SUPPLY_TYPE_CODE
	,ZxRegimesVl.APPLICABILITY_RULE_FLAG
	,ZxRegimesVl.PLACE_OF_SUPPLY_RULE_FLAG
	,ZxRegimesVl.TAX_CALC_RULE_FLAG
	,ZxRegimesVl.TAXABLE_BASIS_THRSHLD_FLAG
	,ZxRegimesVl.TAX_RATE_THRSHLD_FLAG
	,ZxRegimesVl.TAX_AMT_THRSHLD_FLAG
	,ZxRegimesVl.TAX_RATE_RULE_FLAG
	,ZxRegimesVl.TAXABLE_BASIS_RULE_FLAG
	,ZxRegimesVl.DEF_INCLUSIVE_TAX_FLAG
	,ZxRegimesVl.HAS_OTHER_JURISDICTIONS_FLAG
	,ZxRegimesVl.ALLOW_ROUNDING_OVERRIDE_FLAG
	,ZxRegimesVl.ALLOW_EXEMPTIONS_FLAG
	,ZxRegimesVl.ALLOW_EXCEPTIONS_FLAG
	,ZxRegimesVl.ALLOW_RECOVERABILITY_FLAG
	,ZxRegimesVl.AUTO_PRVN_FLAG
	,ZxRegimesVl.HAS_TAX_DET_DATE_RULE_FLAG
	,ZxRegimesVl.HAS_EXCH_RATE_DATE_RULE_FLAG
	,ZxRegimesVl.HAS_TAX_POINT_DATE_RULE_FLAG
	,ZxRegimesVl.USE_LEGAL_MSG_FLAG
	,ZxRegimesVl.REGN_NUM_SAME_AS_LE_FLAG
	,ZxRegimesVl.DEF_REC_SETTLEMENT_OPTION_CODE
	,ZxRegimesVl.TAX_ACCOUNT_PRECEDENCE_CODE
	,ZxRegimesVl.OBJECT_VERSION_NUMBER
	,ZxRegimesVl.RECORD_TYPE_CODE
	,ZxRegimesVl.CREATED_BY
	,ZxRegimesVl.CREATION_DATE
	,ZxRegimesVl.LAST_UPDATED_BY
	,ZxRegimesVl.LAST_UPDATE_DATE
	,ZxRegimesVl.DEF_REGISTR_PARTY_TYPE_CODE
	,ZxRegimesVl.REGISTRATION_TYPE_RULE_FLAG
	,ZxRegimesVl.TAX_INCLUSIVE_OVERRIDE_FLAG
	,ZxRegimesVl.REGIME_PRECEDENCE
	,ZxRegimesVl.CROSS_REGIME_COMPOUNDING_FLAG
	,ZxRegimesVl.TAX_REGIME_NAME
	,CASE
			WHEN ZxRegimesVl.REP_TAX_AUTHORITY_ID IS NOT NULL
			THEN
				(SELECT PARTY_NAME
				FROM HZ_PARTIES RepTaxAuthLookup
				,ZX_PARTY_TAX_PROFILE RepPTP
				WHERE RepPTP.PARTY_ID                = RepTaxAuthLookup.PARTY_ID
				AND ZxRegimesVl.REP_TAX_AUTHORITY_ID = RepPTP.PARTY_TAX_PROFILE_ID
				)
		END AS REP_TAX_AUTH_NAME
	,CASE
			WHEN ZxRegimesVl.coll_TAX_AUTHORITY_ID IS NOT NULL
			THEN
				(SELECT PARTY_NAME
				FROM HZ_PARTIES CollTaxAuthLookup
				,ZX_PARTY_TAX_PROFILE CollPTP
				WHERE CollPTP.PARTY_ID                = CollTaxAuthLookup.PARTY_ID
				AND ZxRegimesVl.coll_TAX_AUTHORITY_ID = CollPTP.PARTY_TAX_PROFILE_ID
				)
		END                                            AS COLL_TAX_AUTH_NAME
	,HzGeographyEO.GEOGRAPHY_NAME                   AS GEOGRAPHY_CODE
	,FND_TERRITORIES_VL.TERRITORY_SHORT_NAME        AS CountryCodeName
	,GL_DAILY_CONVERSION_TYPES.USER_CONVERSION_TYPE AS UserConversionType
	,ZxRegimesVl.DEF_REGISTR_PARTY_TYPE_CODE TRANS_REGISTR_PARTY_TYPE_CODE
	,ZxRegimesVl.PARENT_REGIME_CODE TRANS_PARENT_REG_CODE
	,ZxRegimesVl.TAX_CURRENCY_CODE TRANS_CURR_CODE
	,ZxRegimesVl.DEF_PLACE_OF_SUPPLY_TYPE_CODE TRANS_POS_TYPE_CODE
	,ZxRegimesVl.GEOGRAPHY_TYPE TRANS_GEO_TYPE
	,ZxRegimesVl.PROGRAM_APP_NAME
	,ZxRegimesVl.PROGRAM_NAME
	,ZxRegimesVl.USE_TAX_REPORT_CONFIG_FLAG
	,ZxRegimesVl.COUNTRY_OR_GROUP_CODE CNTY_OR_GRP_CODE_FOR_SRCH
	,FND_TERRITORIES_VL.TERRITORY_SHORT_NAME COUNTRY_CODE_FOR_SEARCH
	,ZxRegimesVl.GEOGRAPHY_TYPE GEOGRAPHY_TYPE_FOR_SEARCH
	,HzGeographyEO.GEOGRAPHY_NAME AS Geography_Name_srch
	,ZxRegimesVl.TAX_REGIME_CODE TAX_REGIME_CODE_FOR_SEARCH
	,ZxRegimesVl.TAX_REGIME_NAME TAX_REGIME_NAME_FOR_SEARCH
	,ZxRegimesVl.EFFECTIVE_FROM EFFECTIVE_FROM_FOR_SEARCH
	,NVL(ZxRegimesVl.EFFECTIVE_TO,sysdate + 36500) EFFECTIVE_TO_FOR_SEARCH
	,CASE ZxRegimesVl.HAS_SUB_REGIME_FLAG
			WHEN 'Y'
			THEN 'Yes'
			WHEN 'N'
			THEN 'No'
		END                                     AS REGIME_GROUP
	,HzGeographyEO.GEOGRAPHY_NAME            AS Geography_Name
	,roundingLookup.meaning                  AS rounding_rule_code_view
	,recsettlementLookup.meaning             AS DEF_SETTLEMENT_OPTION_view
	,inclusiveLookup.meaning                 AS DEF_INCLUSIVE_FLAG_view
	,countryorgroupLookup.meaning            AS CNTY_OR_GRP_CODE_view
	,FND_TERRITORIES_VL.TERRITORY_SHORT_NAME AS COUNTRY_CODE_view
	,currencyPeo.NAME                        AS TAX_CURRENCY_CODE_view
	,currencyPeo.CURRENCY_CODE
	,GeographyTypePeo.GEOGRAPHY_TYPE_NAME AS GEOGRAPHY_TYPE_view
	,CASE
			WHEN effective_to IS NULL
			THEN 'Y'
			WHEN SYSDATE > effective_to
			THEN 'N'
			ELSE 'Y'
		END AS effective_to_status
	,ZxRegimesVl.Validation_Type
	,ZxRegimesVl.Validation_Level
	,ZxRegimesVl.Uniqueness_Validation_Level
	,ZXREGIMESVL.BUCKET_LEVEL_FLAG
	,uniquevalidationLookup.meaning unique_validation_view
	FROM ZX_REGIMES_VL ZxRegimesVl
	,HZ_GEOGRAPHIES HzGeographyEO
	,FND_TERRITORIES_VL
	,GL_DAILY_CONVERSION_TYPES
	,fnd_lookups roundingLookup
	,fnd_lookups recsettlementLookup
	,fnd_lookups inclusiveLookup
	,FND_LOOKUPS COUNTRYORGROUPLOOKUP
	,fnd_lookups uniquevalidationLookup
	,FND_CURRENCIES_VL currencyPeo
	,HZ_GEOGRAPHY_TYPES_VL GeographyTypePeo
	WHERE HzGeographyEO.GEOGRAPHY_ID (+)              = ZxRegimesVl.GEOGRAPHY_ID
	AND FND_TERRITORIES_VL.TERRITORY_CODE (+)         = ZxRegimesVl.COUNTRY_CODE
	AND GL_DAILY_CONVERSION_TYPES.CONVERSION_TYPE (+) = ZxRegimesVl.EXCHANGE_RATE_TYPE
	AND roundingLookup.lookup_type (+)                = 'ZX_ROUNDING_RULE'
	AND roundingLookup.lookup_code (+)                = ZxRegimesVl.ROUNDING_RULE_CODE
	AND recsettlementLookup.lookup_type (+)           = 'ZX_REC_SETTLEMENT_OPTION'
	AND recsettlementLookup.lookup_code (+)           = ZxRegimesVl.DEF_REC_SETTLEMENT_OPTION_CODE
	AND inclusiveLookup.lookup_type (+)               = 'ZX_INCLUSIVE_TAX'
	AND inclusiveLookup.lookup_code (+)               = ZxRegimesVl.DEF_INCLUSIVE_TAX_FLAG
	AND countryorgroupLookup.lookup_type (+)          = 'ZX_COUNTRY_OR_GROUP'
	AND countryorgroupLookup.lookup_code (+)          = ZxRegimesVl.COUNTRY_OR_GROUP_CODE
	AND currencyPeo.CURRENCY_CODE (+)                 = ZxRegimesVl.TAX_CURRENCY_CODE
	AND GEOGRAPHYTYPEPEO.GEOGRAPHY_TYPE (+)           = ZXREGIMESVL.GEOGRAPHY_TYPE
	AND UNIQUEVALIDATIONLOOKUP.LOOKUP_TYPE (+)        = 'ZX_UNIQUENESS_VALIDATION_LVL'
	AND UNIQUEVALIDATIONLOOKUP.lookup_code(+)         = ZxRegimesVl.Uniqueness_Validation_Level
	AND NVL(ZxRegimesVl.Regime_Type_Flag,'I')         = 'I'
	ORDER BY ZxRegimesVl.TAX_REGIME_CODE
	) QRSLT
ORDER BY QRSLT.TAX_REGIME_CODE
,QRSLT.COUNTRY_CODE_VIEW