/* ****************************************************************************
 * $Revision: 73708 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2020-03-06 14:23:42 +0700 (Fri, 06 Mar 2020) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Absence%20Categories%20-%20Absence%20Category%20-%20DFF.sql $:
 * $Id: Manage Absence Categories - Absence Category - DFF.sql 73708 2020-03-06 07:23:42Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10110##RES##ANC_ABSENCE_CATEGORIES_LEG_DDF
-- DFF_ATTRIBUTES=INFORMATION,INFORMATION_DATE,INFORMATION_NUMBER

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

SELECT (SELECT NAME FROM ANC_ABSENCE_CATEGORIES_VL WHERE ABSENCE_CATEGORY_ID = ancABSENCATEO.ABSENCE_CATEGORY_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))RES_NAME
,(SELECT TERRITORY_SHORT_NAME 
	FROM FND_TERRITORIES_VL 
	WHERE TERRITORY_CODE = ancABSENCATEO.LEGISLATION_CODE
	) RES_LEGISLATION
,ancABSENCATEO.INFORMATION_CATEGORY RES_CONTEXT_CODE
,ancABSENCATEO.INFORMATION1
,ancABSENCATEO.INFORMATION2
,ancABSENCATEO.INFORMATION3
,ancABSENCATEO.INFORMATION4
,ancABSENCATEO.INFORMATION5
,ancABSENCATEO.INFORMATION6
,ancABSENCATEO.INFORMATION7
,ancABSENCATEO.INFORMATION8
,ancABSENCATEO.INFORMATION9
,ancABSENCATEO.INFORMATION10
,ancABSENCATEO.INFORMATION11
,ancABSENCATEO.INFORMATION12
,ancABSENCATEO.INFORMATION13
,ancABSENCATEO.INFORMATION14
,ancABSENCATEO.INFORMATION15
,ancABSENCATEO.INFORMATION16
,ancABSENCATEO.INFORMATION17
,ancABSENCATEO.INFORMATION18
,ancABSENCATEO.INFORMATION19
,ancABSENCATEO.INFORMATION20
,ancABSENCATEO.INFORMATION21
,ancABSENCATEO.INFORMATION22
,ancABSENCATEO.INFORMATION23
,ancABSENCATEO.INFORMATION24
,ancABSENCATEO.INFORMATION25
,ancABSENCATEO.INFORMATION26
,ancABSENCATEO.INFORMATION27
,ancABSENCATEO.INFORMATION28
,ancABSENCATEO.INFORMATION29
,ancABSENCATEO.INFORMATION30
,ancABSENCATEO.INFORMATION_NUMBER1
,ancABSENCATEO.INFORMATION_NUMBER2
,ancABSENCATEO.INFORMATION_NUMBER3
,ancABSENCATEO.INFORMATION_NUMBER4
,ancABSENCATEO.INFORMATION_NUMBER5
,ancABSENCATEO.INFORMATION_NUMBER6
,ancABSENCATEO.INFORMATION_NUMBER7
,ancABSENCATEO.INFORMATION_NUMBER8
,ancABSENCATEO.INFORMATION_NUMBER9
,ancABSENCATEO.INFORMATION_NUMBER10
,ancABSENCATEO.INFORMATION_NUMBER11
,ancABSENCATEO.INFORMATION_NUMBER12
,ancABSENCATEO.INFORMATION_NUMBER13
,ancABSENCATEO.INFORMATION_NUMBER14
,ancABSENCATEO.INFORMATION_NUMBER15
,ancABSENCATEO.INFORMATION_NUMBER16
,ancABSENCATEO.INFORMATION_NUMBER17
,ancABSENCATEO.INFORMATION_NUMBER18
,ancABSENCATEO.INFORMATION_NUMBER19
,ancABSENCATEO.INFORMATION_NUMBER20
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE1, 'DD-Mon-YYYY') INFORMATION_DATE1
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE2, 'DD-Mon-YYYY') INFORMATION_DATE2
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE3, 'DD-Mon-YYYY') INFORMATION_DATE3
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE4, 'DD-Mon-YYYY') INFORMATION_DATE4
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE5, 'DD-Mon-YYYY') INFORMATION_DATE5
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE6, 'DD-Mon-YYYY') INFORMATION_DATE6
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE7, 'DD-Mon-YYYY') INFORMATION_DATE7
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE8, 'DD-Mon-YYYY') INFORMATION_DATE8
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE9, 'DD-Mon-YYYY') INFORMATION_DATE9
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE10, 'DD-Mon-YYYY') INFORMATION_DATE10
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE11, 'DD-Mon-YYYY') INFORMATION_DATE11
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE12, 'DD-Mon-YYYY') INFORMATION_DATE12
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE13, 'DD-Mon-YYYY') INFORMATION_DATE13
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE14, 'DD-Mon-YYYY') INFORMATION_DATE14
, TO_CHAR(ancABSENCATEO.INFORMATION_DATE15, 'DD-Mon-YYYY') INFORMATION_DATE15

,ancABSENCATEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ancABSENCATEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ancABSENCATEO.CREATED_BY RSC_CREATED_BY
,ancABSENCATEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,ancABSENCATEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM ANC_ABSENCE_CATEGORIES_F ancABSENCATEO
WHERE (ancABSENCATEO.INFORMATION_CATEGORY IS NOT NULL OR
ancABSENCATEO.INFORMATION1 IS NOT NULL OR 
ancABSENCATEO.INFORMATION2 IS NOT NULL OR 
ancABSENCATEO.INFORMATION3 IS NOT NULL OR 
ancABSENCATEO.INFORMATION4 IS NOT NULL OR 
ancABSENCATEO.INFORMATION5 IS NOT NULL OR 
ancABSENCATEO.INFORMATION6 IS NOT NULL OR 
ancABSENCATEO.INFORMATION7 IS NOT NULL OR 
ancABSENCATEO.INFORMATION8 IS NOT NULL OR 
ancABSENCATEO.INFORMATION9 IS NOT NULL OR 
ancABSENCATEO.INFORMATION10 IS NOT NULL OR 
ancABSENCATEO.INFORMATION11 IS NOT NULL OR 
ancABSENCATEO.INFORMATION12 IS NOT NULL OR 
ancABSENCATEO.INFORMATION13 IS NOT NULL OR 
ancABSENCATEO.INFORMATION14 IS NOT NULL OR 
ancABSENCATEO.INFORMATION15 IS NOT NULL OR 
ancABSENCATEO.INFORMATION16 IS NOT NULL OR 
ancABSENCATEO.INFORMATION17 IS NOT NULL OR 
ancABSENCATEO.INFORMATION18 IS NOT NULL OR 
ancABSENCATEO.INFORMATION19 IS NOT NULL OR 
ancABSENCATEO.INFORMATION20 IS NOT NULL OR 
ancABSENCATEO.INFORMATION21 IS NOT NULL OR 
ancABSENCATEO.INFORMATION22 IS NOT NULL OR 
ancABSENCATEO.INFORMATION23 IS NOT NULL OR 
ancABSENCATEO.INFORMATION24 IS NOT NULL OR 
ancABSENCATEO.INFORMATION25 IS NOT NULL OR 
ancABSENCATEO.INFORMATION26 IS NOT NULL OR 
ancABSENCATEO.INFORMATION27 IS NOT NULL OR 
ancABSENCATEO.INFORMATION28 IS NOT NULL OR 
ancABSENCATEO.INFORMATION29 IS NOT NULL OR 
ancABSENCATEO.INFORMATION30 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER1 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER2 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER3 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER4 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER5 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER6 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER7 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER8 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER9 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER10 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER11 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER12 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER13 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER14 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER15 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER16 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER17 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER18 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER19 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_NUMBER20 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE1 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE2 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE3 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE4 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE5 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE6 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE7 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE8 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE10 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE11 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE12 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE13 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE14 IS NOT NULL OR 
ancABSENCATEO.INFORMATION_DATE15 IS NOT NULL 
 )
ORDER BY RES_NAME