 /* ****************************************************************************
 * $Revision: 48884 $:
 * $Author: dhara.pithadiya $:
 * $Date: 2015-08-18 14:24:02 +0700 (Tue, 18 Aug 2015) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Transaction%20Types%20-%20Manage%20Transaction%20Types.sql $:
 * $Id: Manage Transaction Types - Manage Transaction Types.sql 48884 2015-08-18 07:24:02Z dhara.pithadiya $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=QP_DISCOUNT_LISTS_TL 
-- RSC_PREREQUISITE_OBJECTS=QP_DISCOUNT_LISTS_ALL_B 
-- RSC_PREREQUISITE_OBJECTS=QP_DISCOUNT_LIST_ITEMS
-- RSC_PREREQUISITE_OBJECTS=QP_PRICING_TERMS_VL
-- RSC_PREREQUISITE_OBJECTS=QP_TIER_HEADERS
-- RSC_PREREQUISITE_OBJECTS=QP_TIER_LINES
-- RSC_PREREQUISITE_OBJECTS=QP_PRICING_BASIS_TL

SELECT QpDiscountListsTl.NAME RES_NAME
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_QP_ITEM_LEVELS'
	AND LOOKUP_CODE = QpDiscountListItems.ITEM_LEVEL_CODE
	) RES_ITEM_LEVEL
,(SELECT ITEM_NUMBER
	FROM EGP_SYSTEM_ITEMS_VL
	WHERE INVENTORY_ITEM_ID = QpDiscountListItems.ITEM_ID
	AND INVENTORY_ORGANIZATION_ID = QpDiscountListsAllB.ORG_ID
	) RES_DISCOUNT_LINES_NAME
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = QpDiscountListItems.PRICING_UOM_CODE
	) RES_PRICING_UOM
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_QP_RETURN_LINE_TYPES'
	AND LOOKUP_CODE = QpDiscountListItems.LINE_TYPE_CODE
	) RES_LINE_TYPE
,QpPricingTermsVl.NAME RES_RULE_NAME
,QpTierLines.MINIMUM_VALUE RES_MINIMUM
,QpTierLines.MAXIMUM_VALUE RES_MAXIMUM
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_QP_APPLICATION_METHODS'
	AND LOOKUP_CODE = QpTierLines.APPLICATION_METHOD_CODE
	) RES_APPLICATION_METHOD
,QpTierLines.INCREMENT_VALUE RES_INCREMENT_VALUE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_QP_LINE_ADJ_TYPES'
	AND LOOKUP_CODE = QpTierLines.ADJUSTMENT_TYPE_CODE
	) RES_ADJUSTMENT_TYPE
,QpTierLines.ADJUSTMENT_AMOUNT RES_ADJUSTMENT_AMOUNT
,(SELECT NAME 
	FROM QP_PRICING_BASIS_TL
	WHERE PRICING_BASIS_ID = QpTierLines.ADJUSTMENT_BASIS_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_ADJUSTMENT_BASIS
,QpTierLines.TIER_LINE_NUMBER RES_TIERLINENUMBER
,QpTierLines.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,QpTierLines.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,QpTierLines.CREATED_BY  RSC_CREATED_BY
,QpTierLines.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,QpDiscountListsAllB.ORG_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM QP_DISCOUNT_LISTS_TL QpDiscountListsTl
,QP_DISCOUNT_LISTS_ALL_B QpDiscountListsAllB
,QP_DISCOUNT_LIST_ITEMS QpDiscountListItems
,QP_PRICING_TERMS_VL QpPricingTermsVl
,QP_TIER_HEADERS QpTierHeaders
,QP_TIER_LINES QpTierLines
WHERE QpDiscountListsTl.DISCOUNT_LIST_ID = QpDiscountListsAllB.DISCOUNT_LIST_ID
AND QpDiscountListsTl.DISCOUNT_LIST_ID = QpDiscountListItems.DISCOUNT_LIST_ID
AND QpDiscountListItems.DISCOUNT_LIST_ITEM_ID = QpPricingTermsVl.PARENT_ENTITY_KEY_COLUMN1
AND QpPricingTermsVl.PRICING_RULE_TYPE_CODE = 'TIERED_PRICING'
AND QpPricingTermsVl.TIERED_PRICING_HEADER_ID = QpTierHeaders.TIERED_PRICING_HEADER_ID
AND QpTierHeaders.TIERED_PRICING_HEADER_ID = QpTierLines.TIERED_PRICING_HEADER_ID
AND QpDiscountListsTl.LANGUAGE = USERENV('LANG')
ORDER BY QpDiscountListsTl.NAME
,RES_ITEM_LEVEL
,RES_DISCOUNT_LINES_NAME
,QpPricingTermsVl.NAME
,QpTierLines.TIER_LINE_NUMBER