/* ****************************************************************************
 * $Revision: 78757 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-06-15 11:30:49 +0700 (Wed, 15 Jun 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Receivables%20System%20Options%20-%20Billing%20and%20Revenue.sql $:
 * $Id: Manage Receivables System Options - Billing and Revenue.sql 78757 2022-06-15 04:30:49Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=AR_SYSTEM_PARAMETERS_ALL
 
-- FIELD_TO_APPLY_FUNCTION=RES_TAX_ACCOUNT/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_UNALLOCATED_REVENUE_ACCOUN/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_CROSS_CURRENCY_ROUNDING_AC/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_REALIZED_GAINS_ACCOUNT/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_REALIZED_LOSSES_ACCOUNT/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_HEADER_ROUNDING_ACCOUNT/GET_CODE_COMBINATION

SELECT QRSLT.NAME1 RES_BUSINESS_UNIT
,QRSLT.CER_SPLIT_AMOUNT RES_SPLIT_AMOUNT
,QRSLT.CER_DSO_DAYS RES_DAYS_IN_DAYS_SALES_OUTSTAN
,QRSLT.SALES_CREDIT_PCT_LIMIT RES_SALES_CREDIT_PERCENT_LIMIT
,DECODE(QRSLT.SALESREP_REQUIRED_FLAG,'Y','Yes','No') RES_REQUIRE_SALESPERSON
,DECODE(QRSLT.PRINT_REMIT_TO,'Y','Yes','No') RES_PRINT_REMIT_TO_ADDRESS
,DECODE(QRSLT.PRINT_HOME_COUNTRY_FLAG,'Y','Yes','No') RES_PRINT_HOME_COUNTRY
,QRSLT.TERRITORY_SHORT_NAME RES_DEFAULT_COUNTRY
,QRSLT.VIEW_ATTR_4 RES_APPLICATION_RULE_SET
,QRSLT.DISCOUNT_BASIS RES_DISCOUNT_BASIS
,DECODE(QRSLT.UNEARNED_DISCOUNT,'Y','Yes','No') RES_ALLOW_UNEARNED_DISCOUNTS
,DECODE(QRSLT.PARTIAL_DISCOUNT_FLAG,'Y','Yes','No') RES_DISCOUNT_ON_PARTIAL_PAYMEN
,DECODE(QRSLT.SERVICED_BY_ANY_BU_FLAG,'Y','Yes','No') RES_ALLOW_ANY_BUSINESS_UNIT_TO
,QRSLT.EXCEPTION_RULE_ADJ_ACTIVITY RES_EXCEPTION_RULE_ADJUSTMENT_
,QRSLT.ADJUST_REASON RES_EXCEPTION_RULE_ADJUSTMEN_0
,QRSLT.VIEW_ATTR_9 RES_CREDIT_CARD_RECEIPT_METHOD
,QRSLT.VIEW_ATTR_9_1 RES_CREDIT_CARD_REMITTANCE_BAN
,nvl2(QRSLT.VIEW_ATTR_9,QRSLT.NAME1,NULL) RES_CREDIT_CARD_RECEIPT_BUSINE
,QRSLT.VIEW_ATTR_8 RES_BANK_ACCOUNT_RECEIPT_METHO
,QRSLT.VIEW_ATTR_8_1 RES_BANK_ACCOUNT_REMITTANCE_BA
,nvl2(QRSLT.VIEW_ATTR_8,QRSLT.NAME1,NULL) RES_BANK_ACCOUNT_RECEIPT_BUSIN
,QRSLT.LOCATION_TAX_ACCOUNT RES_TAX_ACCOUNT
,QRSLT.UNALLOCATED_REVENUE_CCID RES_UNALLOCATED_REVENUE_ACCOUN
,QRSLT.CODE_COMBINATION_ID_ROUND RES_CROSS_CURRENCY_ROUNDING_AC
,QRSLT.CODE_COMBINATION_ID_GAIN RES_REALIZED_GAINS_ACCOUNT
,QRSLT.CODE_COMBINATION_ID_LOSS RES_REALIZED_LOSSES_ACCOUNT
,DECODE(QRSLT.RUN_GL_JOURNAL_IMPORT_FLAG,'Y','Yes','No') RES_AUTOMATIC_JOURNAL_IMPORT
,DECODE(QRSLT.TRX_HEADER_LEVEL_ROUNDING,'Y','Yes','No') RES_USE_HEADER_LEVEL_ROUNDING
,QRSLT.TRX_HEADER_ROUND_CCID RES_HEADER_ROUNDING_ACCOUNT
,QRSLT.POSTING_DAYS_PER_CYCLE RES_DAYS_PER_POSTING_CYCLE
,DECODE(QRSLT.CREATE_DETAILED_DIST,'Y','Yes','No') RES_ENABLE_MULTIFUND_ACCOUNTIN
,QRSLT.TAX_PRINTING_OPTION RES_TAX_INVOICE_PRINTING_OPTIO
,QRSLT.DOC_SEQ_GEN_LEVEL RES_DOCUMENT_NUMBER_GENERATION
,QRSLT.VIEW_ATTR_1 RES_ITEM_VALIDATION_ORGANIZATI
,DECODE(QRSLT.CHANGE_PRINTED_INVOICE_FLAG,'Y','Yes','No') RES_ALLOW_CHANGE_TO_PRINTED_TR
,DECODE(QRSLT.INVOICE_DELETION_FLAG,'Y','Yes','No') RES_ALLOW_TRANSACTION_DELETION
,decode(QRSLT.enable_recurring_billing_flag,'Y','Yes','No') RES_ENABLE_RECURRING_BILLING
,QRSLT.FROM_EMAIL_NAME RES_FROM_NAME
,QRSLT.FROM_EMAIL_ADDRESS RES_FROM_E_MAIL
,QRSLT.REPLY_TO_EMAIL_ADDRESS RES_REPLY_TO_E_MAIL
,QRSLT.EMAIL_SUBJECT RES_E_MAIL_SUBJECT
,QRSLT.AR_EMAIL_ADDTNL_ATTRS RES_INCLUDE_BUSINESS_UNIT_IN_E
,QRSLT.AR_EMAIL_ADDTNL_ATTRS_2 RES_INCLUDE_TRANSACTION_NUMBER
,QRSLT.EMAIL_BODY RES_E_MAIL_BODY	
,QRSLT.STMT_FROM_EMAIL_ADDRESS RES_STATEMENT_DELIVERY_USING_E
,QRSLT.STMT_FROM_EMAIL_NAME RES_STATEMENT_DELIVERY_USING_1
,QRSLT.STMT_REPLY_TO_EMAIL_ADDRESS RES_STATEMENT_DELIVERY_USING_2
,QRSLT.STMT_EMAIL_SUBJECT RES_STATEMENT_DELIVERY_USING_3
,(SELECT MEANING
	FROM AR_LOOKUPS
	WHERE LOOKUP_TYPE = 'AR_EMAIL_ADDTNL_ATTRS'
	AND LOOKUP_CODE = QRSLT.INCLUDE_STMT_BU_SUB_CODE
	) RES_STATEMENT_DELIVERY_USING_4
,(SELECT MEANING
	FROM AR_LOOKUPS
	WHERE LOOKUP_TYPE = 'AR_EMAIL_ADDTNL_ATTRS'
	AND LOOKUP_CODE = QRSLT.INCLUDE_STMT_DATE_SUB_CODE
	) RES_STATEMENT_DELIVERY_USING_5
,QRSLT.STMT_EMAIL_BODY RES_STATEMENT_DELIVERY_USING_6
,DECODE(QRSLT.ALLOW_LATE_CHARGES,'Y','Yes','No') RES_ASSESS_LATE_CHARGES
,QRSLT.AR_POST_BILLING_ITEM_INCLUSION RES_AVERAGE_DAILY_BALANCE_CALC
,QRSLT.AR_CALCULATION_RUNNING_MODE RES_AVERAGE_DAILY_BALANCE_CA_7
,QRSLT.VIEW_ATTR_5 RES_INTEREST_INVOICE_TRANSACTI
,QRSLT.VIEW_ATTR_5_1 RES_INTEREST_INVOICE_TRANSAC_8
,QRSLT.VIEW_ATTR_6 RES_DEBIT_MEMO_CHARGE_TRANSACT
,QRSLT.VIEW_ATTR_6_1 RES_DEBIT_MEMO_CHARGE_TRANSA_9
,NULL RES_INTEREST_CHARGE_ACTIVITY
,NULL RES_PENALTY_CHARGE_ACTIVITY
,QRSLT.VIEW_ATTR_7 RES_LATE_CHARGE_TRANSACTION_SO
,QRSLT.VIEW_ATTR_7_1 RES_LATE_CHARGE_TRANSACTION_10
,(SELECT NAME
	FROM RA_GROUPING_RULES
	WHERE GROUPING_RULE_ID = QRSLT.DEFAULT_GROUPING_RULE_ID
	) RES_GROUPING_RULE
,DECODE(QRSLT.CREATE_RECIPROCAL_FLAG,'Y','Yes','No') RES_CREATE_RECIPROCAL_CUSTOMER
,DECODE(QRSLT.AI_PURGE_INTERFACE_TABLES_FLAG,'Y','Yes','No') RES_PURGE_INTERFACE_TABLES
,QRSLT.ACCT_DATES_OUT_OF_ORDER RES_ACCOUNTING_DATES_OUT_OF_OR
,QRSLT.AI_MAX_MEMORY_IN_BYTES RES_MAXIMUM_MEMORY_IN_BYTES
,QRSLT.AI_LOG_FILE_MESSAGE_LEVEL RES_LOG_FILE_MESSAGE_LEVEL
,QRSLT.AI_ACCT_FLEX_KEY_LEFT_PROMPT RES_ACCOUNTING_FLEXFIELD
,QRSLT.AI_MTL_ITEMS_KEY_LEFT_PROMPT RES_SYSTEM_ITEMS
,QRSLT.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY RSC_CREATED_BY
,QRSLT.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,QRSLT.ORG_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM
	(SELECT ArSystemParametersAll.SET_OF_BOOKS_ID
	,ArSystemParametersAll.ACCOUNTING_METHOD
	,ArSystemParametersAll.ACCRUE_INTEREST
	,ArSystemParametersAll.UNEARNED_DISCOUNT
	,ArSystemParametersAll.PARTIAL_DISCOUNT_FLAG
	,ArSystemParametersAll.PRINT_REMIT_TO
	,ArSystemParametersAll.DEFAULT_CB_DUE_DATE
	,ArSystemParametersAll.AUTO_SITE_NUMBERING
	,ArSystemParametersAll.CASH_BASIS_SET_OF_BOOKS_ID
	,ArSystemParametersAll.CODE_COMBINATION_ID_GAIN
	,ArSystemParametersAll.AUTOCASH_HIERARCHY_ID
	,ArSystemParametersAll.RUN_GL_JOURNAL_IMPORT_FLAG
	,ArSystemParametersAll.CER_SPLIT_AMOUNT
	,ArSystemParametersAll.CER_DSO_DAYS
	,ArSystemParametersAll.POSTING_DAYS_PER_CYCLE
	,ArSystemParametersAll.ADDRESS_VALIDATION
	,ARSYSTEMPARAMETERSALL.CALC_DISCOUNT_ON_LINES_FLAG
	,DECODE(ARSYSTEMPARAMETERSALL.CALC_DISCOUNT_ON_LINES_FLAG,NULL,NULL,(FUSION.arpt_sql_func_util.get_lookup_meaning(
		'DISCOUNT_BASIS',ARSYSTEMPARAMETERSALL.CALC_DISCOUNT_ON_LINES_FLAG))) DISCOUNT_BASIS
	,ArSystemParametersAll.CHANGE_PRINTED_INVOICE_FLAG
	,ArSystemParametersAll.CODE_COMBINATION_ID_LOSS
	,ArSystemParametersAll.CREATE_RECIPROCAL_FLAG
	,ArSystemParametersAll.DEFAULT_COUNTRY
	,ArSystemParametersAll.DEFAULT_TERRITORY
	,ArSystemParametersAll.GENERATE_CUSTOMER_NUMBER
	,ArSystemParametersAll.INVOICE_DELETION_FLAG
	,ArSystemParametersAll.enable_recurring_billing_flag
	,ArSystemParametersAll.LOCATION_STRUCTURE_ID
	,ArSystemParametersAll.SITE_REQUIRED_FLAG
	,ArSystemParametersAll.TAX_ALLOW_COMPOUND_FLAG
	,ARSYSTEMPARAMETERSALL.TAX_INVOICE_PRINT
	,DECODE(ARSYSTEMPARAMETERSALL.TAX_INVOICE_PRINT,NULL,NULL,(FUSION.arpt_sql_func_util.get_lookup_meaning(
		'TAX_PRINTING_OPTION',ARSYSTEMPARAMETERSALL.TAX_INVOICE_PRINT))) TAX_PRINTING_OPTION
	,ArSystemParametersAll.TAX_METHOD
	,ArSystemParametersAll.TAX_USE_CUSTOMER_EXEMPT_FLAG
	,ArSystemParametersAll.TAX_USE_CUST_EXC_RATE_FLAG
	,ArSystemParametersAll.TAX_USE_LOC_EXC_RATE_FLAG
	,ArSystemParametersAll.TAX_USE_PRODUCT_EXEMPT_FLAG
	,ArSystemParametersAll.TAX_USE_PROD_EXC_RATE_FLAG
	,ArSystemParametersAll.TAX_USE_SITE_EXC_RATE_FLAG
	,ArSystemParametersAll.AI_LOG_FILE_MESSAGE_LEVEL
	,ArSystemParametersAll.AI_MAX_MEMORY_IN_BYTES
	,ArSystemParametersAll.AI_ACCT_FLEX_KEY_LEFT_PROMPT
	,ArSystemParametersAll.AI_MTL_ITEMS_KEY_LEFT_PROMPT
	,ArSystemParametersAll.AI_TERRITORY_KEY_LEFT_PROMPT
	,ArSystemParametersAll.AI_PURGE_INTERFACE_TABLES_FLAG
	,ArSystemParametersAll.AI_ACTIVATE_SQL_TRACE_FLAG
	,ArSystemParametersAll.DEFAULT_GROUPING_RULE_ID
	,ArSystemParametersAll.SALESREP_REQUIRED_FLAG
	,ArSystemParametersAll.AUTO_REC_INVOICES_PER_COMMIT
	,ArSystemParametersAll.AUTO_REC_RECEIPTS_PER_COMMIT
	,ArSystemParametersAll.PAY_UNRELATED_INVOICES_FLAG
	,ArSystemParametersAll.TAX_CACHE
	,ArSystemParametersAll.PRINT_HOME_COUNTRY_FLAG
	,ArSystemParametersAll.LOCATION_TAX_ACCOUNT
	,ArSystemParametersAll.FROM_POSTAL_CODE
	,ArSystemParametersAll.TO_POSTAL_CODE
	,ArSystemParametersAll.TAX_REGISTRATION_NUMBER
	,ArSystemParametersAll.POPULATE_GL_SEGMENTS_FLAG
	,ArSystemParametersAll.CREATE_DETAILED_DIST
	,ArSystemParametersAll.UNALLOCATED_REVENUE_CCID
	,ArSystemParametersAll.ORG_ID
	,ArSystemParametersAll.TAX_CURRENCY_CODE
	,ArSystemParametersAll.TAX_PRECISION
	,ArSystemParametersAll.TAX_MINIMUM_ACCOUNTABLE_UNIT
	,ArSystemParametersAll.TAX_HEADER_LEVEL_FLAG
	,ArSystemParametersAll.TAX_ROUNDING_RULE
	,ArSystemParametersAll.TAX_ROUNDING_ALLOW_OVERRIDE
	,ArSystemParametersAll.TAX_CODE
	,ArSystemParametersAll.RULE_SET_ID
	,ArSystemParametersAll.TAX_USE_ACCOUNT_EXC_RATE_FLAG
	,ArSystemParametersAll.TAX_USE_SYSTEM_EXC_RATE_FLAG
	,ArSystemParametersAll.TAX_HIER_SITE_EXC_RATE
	,ArSystemParametersAll.TAX_HIER_CUST_EXC_RATE
	,ArSystemParametersAll.TAX_HIER_PROD_EXC_RATE
	,ArSystemParametersAll.TAX_HIER_ACCOUNT_EXC_RATE
	,ArSystemParametersAll.TAX_HIER_SYSTEM_EXC_RATE
	,ArSystemParametersAll.TAX_ENFORCE_ACCOUNT_FLAG
	,ArSystemParametersAll.TAX_DATABASE_VIEW_SET
	,ArSystemParametersAll.INCLUSIVE_TAX_USED
	,ArSystemParametersAll.CODE_COMBINATION_ID_ROUND
	,ArSystemParametersAll.TRX_HEADER_LEVEL_ROUNDING
	,ArSystemParametersAll.TRX_HEADER_ROUND_CCID
	,ArSystemParametersAll.SALES_TAX_GEOCODE
	,ArSystemParametersAll.BILLS_RECEIVABLE_ENABLED_FLAG
	,ArSystemParametersAll.TA_INSTALLED_FLAG
	,ArSystemParametersAll.REV_TRANSFER_CLEAR_CCID
	,ArSystemParametersAll.SALES_CREDIT_PCT_LIMIT
	,ArSystemParametersAll.MAX_WRTOFF_AMOUNT
	,ArSystemParametersAll.IREC_CC_RECEIPT_METHOD_ID
	,ArSystemParametersAll.SHOW_BILLING_NUMBER_FLAG
	,ArSystemParametersAll.CROSS_CURRENCY_RATE_TYPE
	,ARSYSTEMPARAMETERSALL.DOCUMENT_SEQ_GEN_LEVEL
	,DECODE(ARSYSTEMPARAMETERSALL.DOCUMENT_SEQ_GEN_LEVEL,NULL,'None',(FUSION.arpt_sql_func_util.get_lookup_meaning(
		'DOC_SEQ_GEN_LEVEL',ARSYSTEMPARAMETERSALL.DOCUMENT_SEQ_GEN_LEVEL))) DOC_SEQ_GEN_LEVEL
	,ArSystemParametersAll.CALC_TAX_ON_CREDIT_MEMO_FLAG
	,ArSystemParametersAll.IREC_BA_RECEIPT_METHOD_ID
	,ArSystemParametersAll.PAYMENT_THRESHOLD
	,ArSystemParametersAll.STANDARD_REFUND
	,ArSystemParametersAll.CREDIT_CLASSIFICATION1
	,ArSystemParametersAll.CREDIT_CLASSIFICATION3
	,ArSystemParametersAll.CREDIT_CLASSIFICATION2
	,ArSystemParametersAll.UNMTCH_CLAIM_CREATION_FLAG
	,ArSystemParametersAll.MATCHED_CLAIM_CREATION_FLAG
	,ArSystemParametersAll.MATCHED_CLAIM_EXCL_CM_FLAG
	,ArSystemParametersAll.MIN_WRTOFF_AMOUNT
	,ArSystemParametersAll.MIN_REFUND_AMOUNT
	,ArSystemParametersAll.ALLOW_LATE_CHARGES
	,ARSYSTEMPARAMETERSALL.POST_BILLING_ITEM_INCLUSION
	,DECODE(ARSYSTEMPARAMETERSALL.POST_BILLING_ITEM_INCLUSION,NULL,NULL,(FUSION.arpt_sql_func_util.get_lookup_meaning(
		'AR_POST_BILLING_ITEM_INCLUSION',ARSYSTEMPARAMETERSALL.POST_BILLING_ITEM_INCLUSION))) AR_POST_BILLING_ITEM_INCLUSION
	,ARSYSTEMPARAMETERSALL.LATE_CHARGE_BILLING_CALC_MODE
	,DECODE(ARSYSTEMPARAMETERSALL.LATE_CHARGE_BILLING_CALC_MODE,NULL,NULL,(FUSION.arpt_sql_func_util.get_lookup_meaning(
		'AR_POST_BILLING_ITEM_INCLUSION',ARSYSTEMPARAMETERSALL.LATE_CHARGE_BILLING_CALC_MODE))) AR_CALCULATION_RUNNING_MODE
	,ArSystemParametersAll.OBJECT_VERSION_NUMBER
	,ArSystemParametersAll.LATE_CHARGE_DM_TYPE_SEQ_ID
	,ArSystemParametersAll.LATE_CHARGE_INV_TYPE_SEQ_ID
	,ArSystemParametersAll.LATE_CHARGE_BAT_SOURCE_SEQ_ID
	,ArSystemParametersAll.CONFIRM_THRESHOLD_AMT
	,ArSystemParametersAll.PAYMENT_APPLICATION_RULE
	,ArSystemParametersAll.AUTOAPPLY_FLAG
	,ArSystemParametersAll.AUTOMATCH_RULE_ID
	,ArSystemParametersAll.EXCEPTION_RULE_ID
	,ArSystemParametersAll.LOCKBOX_MATCHING_OPTION1
	,ArSystemParametersAll.LOCKBOX_MATCHING_OPTION2
	,ArSystemParametersAll.LOCKBOX_MATCHING_OPTION3
	,ArSystemParametersAll.LOCKBOX_MATCHING_OPTION4
	,ArSystemParametersAll.FINCHRG_RECEIVABLES_TRX_ID
	,ARSYSTEMPARAMETERSALL.PENALTY_REC_TRX_ID
	,ARSYSTEMPARAMETERSALL.LAST_UPDATE_DATE
	,ARSYSTEMPARAMETERSALL.LAST_UPDATED_BY
	,ARSYSTEMPARAMETERSALL.CREATED_BY
	,ARSYSTEMPARAMETERSALL.CREATION_DATE
	,ARSYSTEMPARAMETERSALL.AUTOMATCH_RERUN_DAYS
	,GlLedgers.CHART_OF_ACCOUNTS_ID
	,GlLedgers.LEDGER_ID
	,(SELECT NAME
		FROM FUSION.AR_AUTOMATCH_RULES
		WHERE AUTOMATCH_RULE_ID = ArSystemParametersAll.AUTOMATCH_RULE_ID
		) AS AUTO_MATCH_RULE_SET
	,GlLedgers.CURRENCY_CODE
	,GlLedgers.NAME
	,BusinessUnitPEO.BU_NAME AS NAME1
	,BusinessUnitPEO.BU_ID
	,ArSystemParametersAll.EXCEPTION_ADJ_REC_TRX_ID
	,ArSystemParametersAll.EXCEPTION_WRTOFF_REC_TRX_ID
	,(SELECT NAME
		FROM FUSION.AR_RECEIVABLES_TRX_ALL
		WHERE RECEIVABLES_TRX_ID = ArSystemParametersAll.EXCEPTION_ADJ_REC_TRX_ID
		AND ORG_ID               = ARSYSTEMPARAMETERSALL.ORG_ID
		) AS EXCEPTION_RULE_ADJ_ACTIVITY
	/*,(SELECT NAME
		FROM FUSION.AR_RECEIVABLES_TRX_ALL
		WHERE RECEIVABLES_TRX_ID = ArSystemParametersAll.EXCEPTION_WRTOFF_REC_TRX_ID
		AND ORG_ID               = ArSystemParametersAll.ORG_ID
		) AS EXCEPTION_RULE_WOFF_ACTIVITY
	,(SELECT NAME
		FROM FUSION.AR_APP_EXCEPTION_RULES
		WHERE EXCEPTION_RULE_ID = ArSystemParametersAll.EXCEPTION_RULE_ID
		) AS APP_EXCEP_RULE_SET*/
	,ArSystemParametersAll.ITEM_VALIDATION_ORG_ID
	,GlLedgers.OBJECT_VERSION_NUMBER AS OBJECT_VERSION_NUMBER1
	,(SELECT organization_name
		FROM FUSION.inv_organization_definitions_v
		WHERE ORGANIZATION_ID = ARSYSTEMPARAMETERSALL.ITEM_VALIDATION_ORG_ID
		) AS VIEW_ATTR_1
	,ArSystemParametersAll.EXCEPTION_ADJ_REASON_CODE
	,DECODE(ARSYSTEMPARAMETERSALL.EXCEPTION_ADJ_REASON_CODE,NULL,NULL,(FUSION.arpt_sql_func_util.get_lookup_meaning(
		'ADJUST_REASON',ARSYSTEMPARAMETERSALL.EXCEPTION_ADJ_REASON_CODE))) ADJUST_REASON
	,ArSystemParametersAll.EXCEPTION_PMT_METHOD_CODE
	/*,(SELECT payment_method_name
		FROM FUSION.IBY_PAYMENT_METHODS_VL
		WHERE PAYMENT_METHOD_CODE = ARSYSTEMPARAMETERSALL.EXCEPTION_PMT_METHOD_CODE
		) AS VIEW_ATTR_2*/
	/*,(SELECT hierarchy_name
		FROM FUSION.ar_autocash_hierarchies
		WHERE AUTOCASH_HIERARCHY_ID = ARSYSTEMPARAMETERSALL.AUTOCASH_HIERARCHY_ID
		) AS VIEW_ATTR_3*/
	,(SELECT rule_set_name
		FROM FUSION.ar_app_rule_sets
		WHERE RULE_SET_ID = ARSYSTEMPARAMETERSALL.RULE_SET_ID
		) AS VIEW_ATTR_4
	,(SELECT name
		FROM FUSION.ra_cust_trx_types_all
		WHERE CUST_TRX_TYPE_SEQ_ID = ARSYSTEMPARAMETERSALL.LATE_CHARGE_INV_TYPE_SEQ_ID
		) AS VIEW_ATTR_5
	,(SELECT SetIdSetPEO.set_name
		FROM FUSION.ra_cust_trx_types_all
		,Fusion.FND_SETID_SETS_VL SetIdSetPEO
		WHERE CUST_TRX_TYPE_SEQ_ID       = ARSYSTEMPARAMETERSALL.LATE_CHARGE_INV_TYPE_SEQ_ID
		AND ra_cust_trx_types_all.SET_ID = SETIDSETPEO.SET_ID
		) AS VIEW_ATTR_5_1
	,(SELECT name
		FROM FUSION.ra_cust_trx_types_all
		WHERE CUST_TRX_TYPE_SEQ_ID = ARSYSTEMPARAMETERSALL.LATE_CHARGE_DM_TYPE_SEQ_ID
		) AS VIEW_ATTR_6
	,(SELECT SetIdSetPEO.set_name
		FROM FUSION.ra_cust_trx_types_all
		,Fusion.FND_SETID_SETS_VL SetIdSetPEO
		WHERE CUST_TRX_TYPE_SEQ_ID       = ARSYSTEMPARAMETERSALL.LATE_CHARGE_DM_TYPE_SEQ_ID
		AND ra_cust_trx_types_all.SET_ID = SETIDSETPEO.SET_ID
		) AS VIEW_ATTR_6_1
	,(SELECT name
		FROM FUSION.ra_batch_sources_all
		WHERE BATCH_SOURCE_SEQ_ID = ARSYSTEMPARAMETERSALL.LATE_CHARGE_BAT_SOURCE_SEQ_ID
		) AS VIEW_ATTR_7
	,(SELECT SetIdSetPEO.set_name
		FROM FUSION.ra_batch_sources_all
		,Fusion.FND_SETID_SETS_VL SetIdSetPEO
		WHERE BATCH_SOURCE_SEQ_ID       = ARSYSTEMPARAMETERSALL.LATE_CHARGE_BAT_SOURCE_SEQ_ID
		AND ra_batch_sources_all.SET_ID = SETIDSETPEO.SET_ID
		) AS VIEW_ATTR_7_1
	,(SELECT name
		FROM FUSION.ar_receipt_methods
		WHERE RECEIPT_METHOD_ID = ARSYSTEMPARAMETERSALL.IREC_BA_RECEIPT_METHOD_ID
		) AS VIEW_ATTR_8
	,(SELECT CB.bank_account_name
		FROM FUSION.AR_RECEIPT_METHODS ARM
		,FUSION.AR_RECEIPT_METHOD_ACCOUNTS_ALL ARMA
		,FUSION.CE_BANK_ACCOUNTS CB
		WHERE ARM.RECEIPT_METHOD_ID = ARSYSTEMPARAMETERSALL.IREC_BA_RECEIPT_METHOD_ID
		AND ARM.RECEIPT_METHOD_ID   = ARMA.RECEIPT_METHOD_ID
		AND ARMA.ORG_ID             = ArSystemParametersAll.ORG_ID
		AND ARMA.BANK_ACCOUNT_ID    = CB.BANK_ACCOUNT_ID
		AND ARMA.REMIT_BANK_ACCT_USE_ID = ArSystemParametersAll.BA_REMIT_BANK_ACCT_USE_ID
		) AS VIEW_ATTR_8_1
	,(SELECT name
		FROM FUSION.ar_receipt_methods
		WHERE RECEIPT_METHOD_ID = ARSYSTEMPARAMETERSALL.IREC_CC_RECEIPT_METHOD_ID
		) AS VIEW_ATTR_9
	,(SELECT CB.bank_account_name
		FROM FUSION.AR_RECEIPT_METHODS ARM
		,FUSION.AR_RECEIPT_METHOD_ACCOUNTS_ALL ARMA
		,FUSION.CE_BANK_ACCOUNTS CB
		WHERE ARM.RECEIPT_METHOD_ID = ARSYSTEMPARAMETERSALL.IREC_CC_RECEIPT_METHOD_ID
		AND ARMA.ORG_ID = ArSystemParametersAll.ORG_ID
		AND ARM.RECEIPT_METHOD_ID   = ARMA.RECEIPT_METHOD_ID
		AND ARMA.BANK_ACCOUNT_ID    = CB.BANK_ACCOUNT_ID
		) AS VIEW_ATTR_9_1
	,ArSystemParametersAll.SERVICED_BY_ANY_BU_FLAG
	,ArSystemParametersAll.BA_REMIT_BANK_ACCT_USE_ID
	,ArSystemParametersAll.CC_REMIT_BANK_ACCT_USE_ID
	,(SELECT DISTINCT bank_account_name
		FROM FUSION.CE_BANK_ACCT_USES_ALL BAU
		,FUSION.ce_internal_bank_accts_v iba
		WHERE bau.bank_acct_use_id = ArSystemParametersAll.ba_remit_bank_acct_use_id
		AND BAU.BANK_ACCOUNT_ID    = IBA.BANK_ACCOUNT_ID
		) AS VIEW_ATTR_10
	,(SELECT DISTINCT bank_account_name
		FROM FUSION.CE_BANK_ACCT_USES_ALL BAU
		,FUSION.ce_internal_bank_accts_v iba
		WHERE bau.bank_acct_use_id = ArSystemParametersAll.cc_remit_bank_acct_use_id
		AND BAU.BANK_ACCOUNT_ID    = IBA.BANK_ACCOUNT_ID
		) AS VIEW_ATTR_11
	,(SELECT bu_name
		FROM FUSION.CE_BANK_ACCT_USES_ALL BAU
		,FUSION.fun_all_business_units_v fbu
		WHERE bau.bank_acct_use_id = ArSystemParametersAll.ba_remit_bank_acct_use_id
		AND BAU.ORG_ID             = FBU.BU_ID
		) AS VIEW_ATTR_12
	,(SELECT bu_name
		FROM FUSION.CE_BANK_ACCT_USES_ALL BAU
		,FUSION.fun_all_business_units_v fbu
		WHERE bau.bank_acct_use_id = ArSystemParametersAll.cc_remit_bank_acct_use_id
		AND BAU.ORG_ID             = FBU.BU_ID
		) AS VIEW_ATTR_13
	,ArSystemParametersAll.BR_DEFAULT_BATCHSOURCE_SEQ_ID
	,ArSystemParametersAll.BR_REMIT_WITHOUT_RECOURSE_FLAG
	,(SELECT name
		FROM FUSION.ra_batch_sources_all
		WHERE BATCH_SOURCE_SEQ_ID = ARSYSTEMPARAMETERSALL.BR_DEFAULT_BATCHSOURCE_SEQ_ID
		) AS VIEW_ATTR_14
	,(SELECT gdc.USER_CONVERSION_TYPE
		FROM FUSION.GL_DAILY_CONVERSION_TYPES gdc
		WHERE gdc.CONVERSION_TYPE = ArSystemParametersAll.CROSS_CURRENCY_RATE_TYPE
		) AS RATE_TYPE
	,ArSystemParametersAll.EMAIL_BODY
	,ArSystemParametersAll.EMAIL_SUBJECT
	,ArSystemParametersAll.FROM_EMAIL_ADDRESS
	,ArSystemParametersAll.FROM_EMAIL_NAME
	,ARSYSTEMPARAMETERSALL.INCLUDE_TRXNUM_SUBJECT_CODE
	,DECODE(ARSYSTEMPARAMETERSALL.INCLUDE_TRXNUM_SUBJECT_CODE,NULL,NULL,(FUSION.arpt_sql_func_util.get_lookup_meaning(
		'AR_EMAIL_ADDTNL_ATTRS',ARSYSTEMPARAMETERSALL.INCLUDE_TRXNUM_SUBJECT_CODE))) AR_EMAIL_ADDTNL_ATTRS_2
	,ARSYSTEMPARAMETERSALL.INCLUDE_BU_SUBJECT_CODE
	,DECODE(ARSYSTEMPARAMETERSALL.INCLUDE_BU_SUBJECT_CODE,NULL,NULL,(FUSION.arpt_sql_func_util.get_lookup_meaning(
		'AR_EMAIL_ADDTNL_ATTRS',ARSYSTEMPARAMETERSALL.INCLUDE_BU_SUBJECT_CODE))) AR_EMAIL_ADDTNL_ATTRS
	,ArSystemParametersAll.REPLY_TO_EMAIL_ADDRESS
	,ARSYSTEMPARAMETERSALL.ALLOW_PAYMENT_DELETION_FLAG
	,ARSYSTEMPARAMETERSALL.ACCT_DATES_OUT_OF_ORDER
	,fnd_territories.territory_short_name
	,ARSYSTEMPARAMETERSALL.STMT_FROM_EMAIL_ADDRESS 
	,ARSYSTEMPARAMETERSALL.STMT_FROM_EMAIL_NAME 
	,ARSYSTEMPARAMETERSALL.STMT_REPLY_TO_EMAIL_ADDRESS 
	,ARSYSTEMPARAMETERSALL.STMT_EMAIL_SUBJECT 
	,ARSYSTEMPARAMETERSALL.INCLUDE_STMT_BU_SUB_CODE 
	,ARSYSTEMPARAMETERSALL.INCLUDE_STMT_DATE_SUB_CODE 
	,ARSYSTEMPARAMETERSALL.STMT_EMAIL_BODY 
	FROM AR_SYSTEM_PARAMETERS_ALL ArSystemParametersAll
	,GL_LEDGERS GlLedgers
	,FUN_ALL_BUSINESS_UNITS_V BUSINESSUNITPEO
	,fnd_territories_vl fnd_territories
	WHERE(ARSYSTEMPARAMETERSALL.SET_OF_BOOKS_ID = GLLEDGERS.LEDGER_ID)
	AND BUSINESSUNITPEO.BU_ID                   = ARSYSTEMPARAMETERSALL.ORG_ID
	AND ArSystemParametersAll.DEFAULT_COUNTRY   = fnd_territories.territory_code(+)
	) QRSLT
ORDER BY RES_BUSINESS_UNIT