/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Progression%20Grade%20Ladders%20-%20Grades.sql $:
 * $Id: Manage Progression Grade Ladders - Grades.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=PER_GRADE_LADDERS_F_VL
  
SELECT perGRADELADEO.NAME RES_NAME
,TO_CHAR(perRATEVALUEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,perGRADEO.NAME RES_GRADE_NAME
,perGRADEO.GRADE_CODE RES_GRADE_CODE
,perGRADEINLADEO.SEQUENCE RES_SEQUENCE
,perRATEVALUEO.MAXIMUM RES_MAXIMUM
,perRATEVALUEO.MID_VALUE RES_MIDPOINT
,perRATEVALUEO.MINIMUM RES_MINIMUM
,perRATEVALUEO.VALUE RES_VALUE

,perGRADELADEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,perGRADELADEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,perGRADELADEO.CREATED_BY RSC_CREATED_BY
,perGRADELADEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PER_GRADE_LADDERS_F_VL perGRADELADEO
,PER_GRADES_IN_LADDERS_F perGRADEINLADEO
,PER_GRADES_F_VL perGRADEO
,PER_RATE_VALUES_F  perRATEVALUEO
WHERE  perGRADELADEO.GRADE_LADDER_ID = perGRADEINLADEO.GRADE_LADDER_ID
AND perGRADEINLADEO.GRADE_ID = perGRADEO.GRADE_ID
AND perGRADEO.GRADE_ID = perRATEVALUEO.RATE_OBJECT_ID
AND (SELECT LEGISLATION_CODE FROM PER_LEGISLATIVE_DATA_GROUPS_VL 
	WHERE LEGISLATIVE_DATA_GROUP_ID = perGRADELADEO.LEGISLATIVE_DATA_GROUP_ID) =  perRATEVALUEO.LEGISLATION_CODE
AND perGRADEINLADEO.ACTION_OCCURRENCE_ID = perRATEVALUEO.ACTION_OCCURRENCE_ID
AND perGRADELADEO.AUTO_PROGRESSION_CODE IS NOT NULL
AND perGRADELADEO.GRADE_TYPE = 'GRADE'
AND SYSDATE BETWEEN perGRADELADEO.EFFECTIVE_START_DATE  AND NVL(perGRADELADEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN perGRADEINLADEO.EFFECTIVE_START_DATE  AND NVL(perGRADEINLADEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN perRATEVALUEO.EFFECTIVE_START_DATE  AND NVL(perRATEVALUEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
ORDER BY perGRADELADEO.NAME,perRATEVALUEO.EFFECTIVE_START_DATE,perGRADEO.GRADE_CODE,perGRADEINLADEO.SEQUENCE 