/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Job%20-%20Job%20Details%20-%20DFF.sql $:
 * $Id: Manage Job - Job Details - DFF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
 -- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=800##RES##PER_JOBS_DFF
--  DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE
-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.
 

select JOBDEO.name RES_NAME
,JOBDEO.JOB_CODE RES_CODE
,TO_CHAR(JOBDEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY')  RES_EFFECTIVE_START_DATE
,TO_CHAR(JOBDEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_END_DATE
,JOBDEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,JOBDEO.ATTRIBUTE1 
,JOBDEO.ATTRIBUTE2
,JOBDEO.ATTRIBUTE3
,JOBDEO.ATTRIBUTE4
,JOBDEO.ATTRIBUTE5
,JOBDEO.ATTRIBUTE6
,JOBDEO.ATTRIBUTE7
,JOBDEO.ATTRIBUTE8
,JOBDEO.ATTRIBUTE9
,JOBDEO.ATTRIBUTE10
,JOBDEO.ATTRIBUTE11
,JOBDEO.ATTRIBUTE12
,JOBDEO.ATTRIBUTE13
,JOBDEO.ATTRIBUTE14
,JOBDEO.ATTRIBUTE15
,JOBDEO.ATTRIBUTE16 
,JOBDEO.ATTRIBUTE17
,JOBDEO.ATTRIBUTE18
,JOBDEO.ATTRIBUTE19
,JOBDEO.ATTRIBUTE20
,JOBDEO.ATTRIBUTE21
,JOBDEO.ATTRIBUTE22
,JOBDEO.ATTRIBUTE23
,JOBDEO.ATTRIBUTE24
,JOBDEO.ATTRIBUTE25
,JOBDEO.ATTRIBUTE26
,JOBDEO.ATTRIBUTE27
,JOBDEO.ATTRIBUTE28
,JOBDEO.ATTRIBUTE29
,JOBDEO.ATTRIBUTE30
,JOBDEO.ATTRIBUTE_NUMBER1 
,JOBDEO.ATTRIBUTE_NUMBER2
,JOBDEO.ATTRIBUTE_NUMBER3
,JOBDEO.ATTRIBUTE_NUMBER4
,JOBDEO.ATTRIBUTE_NUMBER5
,JOBDEO.ATTRIBUTE_NUMBER6
,JOBDEO.ATTRIBUTE_NUMBER7
,JOBDEO.ATTRIBUTE_NUMBER8
,JOBDEO.ATTRIBUTE_NUMBER9
,JOBDEO.ATTRIBUTE_NUMBER10
,JOBDEO.ATTRIBUTE_NUMBER11
,JOBDEO.ATTRIBUTE_NUMBER12
,JOBDEO.ATTRIBUTE_NUMBER13
,JOBDEO.ATTRIBUTE_NUMBER14
,JOBDEO.ATTRIBUTE_NUMBER15
,JOBDEO.ATTRIBUTE_NUMBER16
,JOBDEO.ATTRIBUTE_NUMBER17
,JOBDEO.ATTRIBUTE_NUMBER18
,JOBDEO.ATTRIBUTE_NUMBER19
,JOBDEO.ATTRIBUTE_NUMBER20
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE1, 'DD-Mon-YYYY') ATTRIBUTE_DATE1
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE2, 'DD-Mon-YYYY') ATTRIBUTE_DATE2
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE3, 'DD-Mon-YYYY') ATTRIBUTE_DATE3
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE4, 'DD-Mon-YYYY') ATTRIBUTE_DATE4
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE5, 'DD-Mon-YYYY') ATTRIBUTE_DATE5
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE6, 'DD-Mon-YYYY') ATTRIBUTE_DATE6
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE7, 'DD-Mon-YYYY') ATTRIBUTE_DATE7
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE8, 'DD-Mon-YYYY') ATTRIBUTE_DATE8
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE9, 'DD-Mon-YYYY') ATTRIBUTE_DATE9
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE10, 'DD-Mon-YYYY') ATTRIBUTE_DATE10
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE11, 'DD-Mon-YYYY') ATTRIBUTE_DATE11
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE12, 'DD-Mon-YYYY') ATTRIBUTE_DATE12
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE13, 'DD-Mon-YYYY') ATTRIBUTE_DATE13
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE14, 'DD-Mon-YYYY') ATTRIBUTE_DATE14
, TO_CHAR(JOBDEO.ATTRIBUTE_DATE15, 'DD-Mon-YYYY') ATTRIBUTE_DATE15
,JOBDEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,JOBDEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,JOBDEO.CREATED_BY  RSC_CREATED_BY
,JOBDEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
from PER_JOBS_F_VL JOBDEO 
where  (JOBDEO.ATTRIBUTE_CATEGORY IS NOT NULL OR
JOBDEO.ATTRIBUTE1 IS NOT NULL OR 
JOBDEO.ATTRIBUTE2 IS NOT NULL OR 
JOBDEO.ATTRIBUTE3 IS NOT NULL OR 
JOBDEO.ATTRIBUTE4 IS NOT NULL OR 
JOBDEO.ATTRIBUTE5 IS NOT NULL OR 
JOBDEO.ATTRIBUTE6 IS NOT NULL OR 
JOBDEO.ATTRIBUTE7 IS NOT NULL OR 
JOBDEO.ATTRIBUTE8 IS NOT NULL OR 
JOBDEO.ATTRIBUTE9 IS NOT NULL OR 
JOBDEO.ATTRIBUTE10 IS NOT NULL OR 
JOBDEO.ATTRIBUTE11 IS NOT NULL OR 
JOBDEO.ATTRIBUTE12 IS NOT NULL OR 
JOBDEO.ATTRIBUTE13 IS NOT NULL OR 
JOBDEO.ATTRIBUTE14 IS NOT NULL OR 
JOBDEO.ATTRIBUTE15 IS NOT NULL OR
JOBDEO.ATTRIBUTE16 IS NOT NULL OR 
JOBDEO.ATTRIBUTE17 IS NOT NULL OR 
JOBDEO.ATTRIBUTE18 IS NOT NULL OR 
JOBDEO.ATTRIBUTE19 IS NOT NULL OR 
JOBDEO.ATTRIBUTE20 IS NOT NULL OR 
JOBDEO.ATTRIBUTE21 IS NOT NULL OR 
JOBDEO.ATTRIBUTE22 IS NOT NULL OR 
JOBDEO.ATTRIBUTE23 IS NOT NULL OR 
JOBDEO.ATTRIBUTE24 IS NOT NULL OR 
JOBDEO.ATTRIBUTE25 IS NOT NULL OR 
JOBDEO.ATTRIBUTE26 IS NOT NULL OR 
JOBDEO.ATTRIBUTE27 IS NOT NULL OR 
JOBDEO.ATTRIBUTE28 IS NOT NULL OR 
JOBDEO.ATTRIBUTE29 IS NOT NULL OR 
JOBDEO.ATTRIBUTE30 IS NOT NULL OR
JOBDEO.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER11 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER12 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER13 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER14 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER15 IS NOT NULL OR
JOBDEO.ATTRIBUTE_NUMBER16 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER17 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER18 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER19 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_NUMBER20 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE1 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE2 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE3 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE4 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE5 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE6 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE7 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE8 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE9 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE10 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE11 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE12 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE13 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE14 IS NOT NULL OR 
JOBDEO.ATTRIBUTE_DATE15 IS NOT NULL )
order by JOBDEO.name,JOBDEO.JOB_CODE,JOBDEO.EFFECTIVE_START_DATE