/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $glrevaluationURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Revaluations%20-%20Revaluations.sql $:
 * $Id: Manage Revaluations - Revaluation Accounts - DFF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

  -- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=101##RES##GL_REVAL_ACCOUNT_RANGES
-- DFF_ATTRIBUTES=ATTRIBUTE

-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.
 
 
WITH CON AS
	(SELECT NAME
	,REVAL_ACCOUNT_RANGE_ID
	,SUBSTR(MAX(
		CASE
			WHEN RES_XX = '1'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '2'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '3'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '4'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '5'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '6'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '7'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '8'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '9'
			THEN CONDITIONS
		END) ||' '||MAX(
		CASE
			WHEN RES_XX = '10'
			THEN CONDITIONS
		END),5) Name_2
	FROM
		(SELECT GLREVALUATION.NAME
		,REVALRANGESEO.REVAL_ACCOUNT_RANGE_ID
		,ROW_NUMBER() OVER(PARTITION BY REVALRANGESEO.REVAL_ACCOUNT_RANGE_ID ORDER BY NULL) RES_XX
		,EXTRACTVALUE(VALUE(X),'/filterCriteriaItem/conjunction') ||' '||
			(SELECT COAMAPACCOUNTRULEEO.prompt
			FROM FND_KF_SEGMENTS_VL COAMAPACCOUNTRULEEO
			,FND_KF_STR_INSTANCES_VL COAMAPACCOUNTRULEEOI
			WHERE COAMAPACCOUNTRULEEO.STRUCTURE_ID           = COAMAPACCOUNTRULEEOI.STRUCTURE_INSTANCE_ID
			AND COAMAPACCOUNTRULEEOI.STRUCTURE_INSTANCE_CODE =(EXTRACTVALUE(REVALRANGESEO.FLEX_FILTER,
				'/FndFilter/KeyFlexFilter/structureInstanceCode'))
			AND COAMAPACCOUNTRULEEO.SEGMENT_IDENTIFIER =(EXTRACTVALUE(VALUE(X),'/filterCriteriaItem/attributeName'))
			AND COAMAPACCOUNTRULEEOI.KEY_FLEXFIELD_CODE = EXTRACTVALUE(REVALRANGESEO.FLEX_FILTER,'/FndFilter/KeyFlexFilter/keyFlexfieldCode')
			) ||' '||
			(SELECT MEANING
			FROM GL_LOOKUPS
			WHERE LOOKUP_TYPE = 'FILTER_OPERATORS'
			AND LOOKUP_CODE   = EXTRACTVALUE(value(X),'/filterCriteriaItem/operator')
			) ||' '||EXTRACTVALUE(VALUE(X),'/filterCriteriaItem/value[1]') ||' '||DECODE(EXTRACTVALUE(value(X),
			'/filterCriteriaItem/operator'),'BETWEEN','and ',NULL) ||EXTRACTVALUE(VALUE(X),'/filterCriteriaItem/value[2]')
			CONDITIONS
		FROM GL_REVALUATIONS GLREVALUATION
		,GL_REVAL_ACCOUNT_RANGES REVALRANGESEO
		,TABLE(XMLSEQUENCE(extract(REVALRANGESEO.FLEX_FILTER,'/FndFilter/KeyFlexFilter/filterCriteriaRow/filterCriteriaItem')
			)) X
		WHERE GLREVALUATION.REVALUATION_ID = REVALRANGESEO.REVALUATION_ID	
		)
	GROUP BY NAME,REVAL_ACCOUNT_RANGE_ID
	)
SELECT CON.NAME RES_NAME
,CON.NAME_2 RES_FILTER_CONDITIONS
,row_number() over (partition by REVALRANGESEO.REVALUATION_ID order by con.NAME_2) RES_SEQUENCE
,REVALRANGESEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,REVALRANGESEO.ATTRIBUTE1
,REVALRANGESEO.ATTRIBUTE2
,REVALRANGESEO.ATTRIBUTE3
,REVALRANGESEO.ATTRIBUTE4
,REVALRANGESEO.ATTRIBUTE5
,REVALRANGESEO.ATTRIBUTE6
,REVALRANGESEO.ATTRIBUTE7
,REVALRANGESEO.ATTRIBUTE8
,REVALRANGESEO.ATTRIBUTE9
,REVALRANGESEO.ATTRIBUTE10
,REVALRANGESEO.ATTRIBUTE11
,REVALRANGESEO.ATTRIBUTE12
,REVALRANGESEO.ATTRIBUTE13
,REVALRANGESEO.ATTRIBUTE14
,REVALRANGESEO.ATTRIBUTE15
,REVALRANGESEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,REVALRANGESEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,REVALRANGESEO.CREATED_BY RSC_CREATED_BY
,REVALRANGESEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,(SELECT CHART_OF_ACCOUNTS_ID
	FROM GL_REVALUATIONS
	WHERE REVALUATION_ID = REVALRANGESEO.REVALUATION_ID
	) RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CON 
,GL_REVAL_ACCOUNT_RANGES REVALRANGESEO
WHERE CON.REVAL_ACCOUNT_RANGE_ID = REVALRANGESEO.REVAL_ACCOUNT_RANGE_ID
and (REVALRANGESEO.ATTRIBUTE_CATEGORY IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE1            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE2            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE3            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE4            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE5            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE6            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE7            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE8            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE9            IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE10           IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE11           IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE12           IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE13           IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE14           IS NOT NULL
OR REVALRANGESEO.ATTRIBUTE15           IS NOT NULL)
order by CON.NAME,CON.NAME_2,RES_SEQUENCE