/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Progression%20Grade%20Ladders%20-%20Progression%20Grade%20Ladder.sql $:
 * $Id: Manage Progression Grade Ladders - Progression Grade Ladder.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 -- RSC_PREREQUISITE_OBJECTS=PER_GRADE_LADDERS_F_VL
 
 WITH LAST_UPDATE_DATA AS (
		SELECT RATE_ID,ROW_NUMBER() OVER(PARTITION BY GRADE_LADDER_ID,LEGISLATIVE_DATA_GROUP_ID ORDER BY LAST_UPDATE_DATE DESC) ROW_NUMBER 
		FROM PER_RATES_F
	)
  
SELECT perGRADELADEO.NAME RES_NAME
  
/*SELECT TO_CHAR(perGRADELADEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,TO_CHAR(perGRADELADEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_END_DATE
,(SELECT AA.action_reason
	FROM fusion.PER_ACTION_REASONS_VL AA
	,fusion.PER_ACTION_OCCURRENCES BB
	WHERE BB.ACTION_OCCURRENCE_ID = perGRADELADEO.ACTION_OCCURRENCE_ID
	AND AA.action_reason_id       = BB.action_reason_id
	) RES_ACTION_REASON 
,(SELECT SET_NAME
	FROM FND_SETID_SETS
	WHERE LANGUAGE = USERENV('LANG')
	AND SET_ID = perGRADELADEO.GRADE_SET_ID
	) RES_GRADE_SET
,perGRADELADEO.NAME RES_NAME
,(SELECT NAME FROM PER_LEGISLATIVE_DATA_GROUPS_VL 
	WHERE LEGISLATIVE_DATA_GROUP_ID = perGRADELADEO.LEGISLATIVE_DATA_GROUP_ID) RES_LEGISLATIVE_DATA_GROUP
,perGRADELADEO.GRADE_LADDER_GRP_CODE RES_GRADE_LADDER_GROUP
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.ACTIVE_STATUS
		AND LOOKUP_TYPE = 'ACTIVE_INACTIVE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_STATUS
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.PROGRESSION_STYLE_CODE
		AND LOOKUP_TYPE = 'ORA_CMP_GSP_PROG_STYLE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_PROGRESSION_INCREMENT
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.PROGRESSION_DATE_CODE
		AND LOOKUP_TYPE = 'ORA_CMP_GSP_PROG_DT' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_TRANSACTION_DATE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.AUTO_PROGRESSION_CODE
		AND LOOKUP_TYPE = 'ORA_CMP_GSP_AUTO_APPROVE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_CONFIRMATION_TYPE
,(SELECT ACTION_NAME FROM PER_ACTIONS_VL WHERE ACTION_ID = perGRADELADEO.PROG_ACTION_ID 
	AND SYSDATE BETWEEN START_DATE AND NVL(END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_ASSIGNMENT_ACTION
,(SELECT ACTION_REASON FROM PER_ACTION_REASONS_VL WHERE ACTION_REASON_ID  = perGRADELADEO.PROG_ACTION_REASON_ID
	AND SYSDATE BETWEEN START_DATE AND NVL(END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_ASSIGNMENT_ACTION_REASON
,DECODE(perGRADELADEO.UPDATE_SALARY_FLAG,'Y','Yes','No') RES_SALARY_UPDATE_DETAILS_INCL
,(SELECT NAME FROM FND_CURRENCIES_VL  WHERE CURRENCY_CODE = perRATEO.CURRENCY_CODE) RES_SALARY_UPDATE_DETAILS_CURR
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perRATEO.RATE_FREQUENCY
		AND LOOKUP_TYPE = 'CMP_SALARY_BASIS' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_SALARY_UPDATE_DETAILS_FREQ
,perRATEO.ANNUALIZATION_FACTOR RES_SALARY_UPDATE_DETAILS_ANNU
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.SALARY_ADJUSTMENT_TYPE_CODE
		AND LOOKUP_TYPE = 'ORA_CMP_GSP_SALARY_ADJ_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_SALARY_UPDATE_DETAILS_SALA
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.SALARY_CALC_METHOD_CODE
		AND LOOKUP_TYPE = 'ORA_CMP_GSP_SAL_CALC_METH' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))  RES_SALARY_UPDATE_DETAILS_SA_0
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.SALARY_CHANGE_DATE_CODE
		AND LOOKUP_TYPE = 'ORA_CMP_GSP_SAL_CHG_DT' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))  RES_SALARY_UPDATE_DETAILS_TRAN
,(SELECT FORMULA_NAME
			FROM FF_FORMULAS_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND FORMULA_ID = perGRADELADEO.PROG_ACTION_OCCURRENCE_ID) RES_SALARY_UPDATE_DETAILS_SA_1
,(SELECT FORMULA_NAME
			FROM FF_FORMULAS_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND FORMULA_ID = perGRADELADEO.SALARY_CALC_RULE_ID) RES_SALARY_UPDATE_DETAILS_SA_2
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.RATE_CHANGE_DATE_CODE
		AND LOOKUP_TYPE = 'ORA_CMP_GSP_RATE_SYNC_DT' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))  RES_RATE_SYNCHRONIZATION_DETAI
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = perGRADELADEO.AUTO_SAL_CHANGE_CODE
		AND LOOKUP_TYPE = 'ORA_CMP_GSP_AUTO_APPROVE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY')))  RES_RATE_SYNCHRONIZATION_DET_3
*/
,perGRADELADEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,perGRADELADEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,perGRADELADEO.CREATED_BY RSC_CREATED_BY
,perGRADELADEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PER_GRADE_LADDERS_F_VL perGRADELADEO
,PER_RATES_F_VL perRATEO
,LAST_UPDATE_DATA lastTMPEO
WHERE  perGRADELADEO.GRADE_LADDER_ID = perRATEO.GRADE_LADDER_ID
AND perGRADELADEO.LEGISLATIVE_DATA_GROUP_ID = perRATEO.LEGISLATIVE_DATA_GROUP_ID
AND perRATEO.RATE_ID = lastTMPEO.RATE_ID
AND lastTMPEO.ROW_NUMBER = 1
AND perGRADELADEO.AUTO_PROGRESSION_CODE IS NOT NULL
AND SYSDATE BETWEEN perGRADELADEO.EFFECTIVE_START_DATE  AND NVL(perGRADELADEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))