/* ****************************************************************************
 * $Revision: 53935 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-03-25 16:18:48 +0700 (Fri, 25 Mar 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Bank%20Statement%20Transaction%20Creation%20Rules%20-%20Manage%20Bank%20Statement%20Transaction%20Creation%20Rules.sql $:
 * $Id: Manage Bank Statement Transaction Creation Rules - Manage Bank Statement Transaction Creation Rules.sql 53935 2016-03-25 09:18:48Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


-- FIELD_TO_APPLY_FUNCTION=RES_RECEIVABLES_ACCOUNT/GET_CODE_COMBINATION
-- FIELD_TO_APPLY_FUNCTION=RES_PAYABLES_ACCOUNT/GET_CODE_COMBINATION

SELECT NVL((SELECT USER_JE_SOURCE_NAME 
	FROM GL_JE_SOURCES_TL
	WHERE JE_SOURCE_NAME = FUNBALINTERRULES.JE_SOURCE_NAME
	AND LANGUAGE = USERENV('LANG')
	),'None') RES_SOURCE
,NVL((SELECT USER_JE_CATEGORY_NAME 
	FROM GL_JE_CATEGORIES_TL
	WHERE JE_CATEGORY_NAME = FUNBALINTERRULES.JE_CATEGORY_NAME
	AND LANGUAGE = USERENV('LANG')
	),'None') RES_CATEGORY
,DECODE(FUNBALINTERRULES.TRX_TYPE_ID, - 1,'All Other', - 2,'None',TRANSACTIONTYPEPEO.TRX_TYPE_NAME)
	RES_TRANSACTION_TYPE
,GLLEDGERS.NAME RES_FROM_LEDGER
,GLLEDGERS1.NAME RES_TO_LEDGER
,(
	CASE
		WHEN FUNBALINTERRULES.API_RULE_TYPE     IN('Bsv','LE')
		THEN DECODE(FUNBALINTERRULES.FROM_LE_ID, - 1,'All Other', - 2,'None',XLEENTITYPROFILES.NAME)
		ELSE NULL
	END) RES_FROM_LEGAL_ENTITY
,(
	CASE
		WHEN FUNBALINTERRULES.API_RULE_TYPE   IN('Bsv','LE')
		THEN DECODE(FUNBALINTERRULES.TO_LE_ID, - 1,'All Other', - 2,'None',XLEENTITYPROFILES1.NAME)
		ELSE NULL
	END) RES_TO_LEGAL_ENTITY
,DECODE(FUNBALINTERRULES.API_RULE_TYPE,'Bsv',DECODE(FUNBALINTERRULES.DR_BSV,'OTHER1234567890123456789012345',
	'All Other',FUNBALINTERRULES.DR_BSV),NULL) RES_FROM_PRIMARY_SEGMENT_VALUE
,DECODE(FUNBALINTERRULES.API_RULE_TYPE,'Bsv',DECODE(FUNBALINTERRULES.CR_BSV,'OTHER1234567890123456789012345',
	'All Other',FUNBALINTERRULES.CR_BSV),NULL) RES_TO_PRIMARY_SEGMENT_VALUE
,FUNBALINTERRULES.DR_CCID RES_RECEIVABLES_ACCOUNT
,FUNBALINTERRULES.CR_CCID RES_PAYABLES_ACCOUNT
,TO_CHAR(FUNBALINTERRULES.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(FUNBALINTERRULES.END_DATE,'DD-Mon-YYYY') RES_END_DATE
,FunBalInterRules.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,FunBalInterRules.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,FunBalInterRules.CREATED_BY RSC_CREATED_BY
,FunBalInterRules.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FUN_BAL_INTER_RULES FunBalInterRules
,GL_LEDGERS GlLedgers
,GL_LEDGERS GlLedgers1
,XLE_ENTITY_PROFILES XleEntityProfiles
,FUN_TRX_TYPES_VL TransactionTypePEO
,XLE_ENTITY_PROFILES XLEENTITYPROFILES1
WHERE FUNBALINTERRULES.FROM_LEDGER_ID            = GLLEDGERS.LEDGER_ID(+)
AND FunBalInterRules.TO_LEDGER_ID              = GlLedgers1.LEDGER_ID(+)
AND FunBalInterRules.FROM_LE_ID                = XleEntityProfiles.LEGAL_ENTITY_ID(+)
AND FunBalInterRules.TO_LE_ID                  = XleEntityProfiles1.LEGAL_ENTITY_ID(+)
AND FUNBALINTERRULES.TRX_TYPE_ID               = TRANSACTIONTYPEPEO.TRX_TYPE_ID(+)
AND FUNBALINTERRULES.API_RULE_TYPE = 'Bsv'
ORDER BY FUNBALINTERRULES.API_RULE_TYPE
,FUNBALINTERRULES.JE_SOURCE_NAME