/* ****************************************************************************
 * $Revision: 74208 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2020-06-03 19:08:12 +0700 (Wed, 03 Jun 2020) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.20/branches/core/v2.2.3.0.B/reverse_sql/FINANCIALS/Manage%20AutoPost%20Criteria%20Sets%20-%20AutoPost%20Criteria.sql $:
 * $Id: Manage AutoPost Criteria Sets - AutoPost Criteria.sql 74208 2020-06-03 12:08:12Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=8402##RES##GMS_PERSONS_DFF
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

SELECT personNamesE0.DISPLAY_NAME RES_PERSON_NAME
,personsE0.PERSON_NUMBER RES_PERSON_NUMBER
,personelE0.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,personelE0.ATTRIBUTE1 
,personelE0.ATTRIBUTE2
,personelE0.ATTRIBUTE3 
,personelE0.ATTRIBUTE4 
,personelE0.ATTRIBUTE5 
,personelE0.ATTRIBUTE6 
,personelE0.ATTRIBUTE7 
,personelE0.ATTRIBUTE8 
,personelE0.ATTRIBUTE9 
,personelE0.ATTRIBUTE10 
,personelE0.ATTRIBUTE11
,personelE0.ATTRIBUTE12 
,personelE0.ATTRIBUTE13
,personelE0.ATTRIBUTE14 
,personelE0.ATTRIBUTE15 
,personelE0.ATTRIBUTE16 
,personelE0.ATTRIBUTE17 
,personelE0.ATTRIBUTE18 
,personelE0.ATTRIBUTE19 
,personelE0.ATTRIBUTE20
,personelE0.ATTRIBUTE_NUMBER1
,personelE0.ATTRIBUTE_NUMBER2
,personelE0.ATTRIBUTE_NUMBER3
,personelE0.ATTRIBUTE_NUMBER4
,personelE0.ATTRIBUTE_NUMBER5
,personelE0.ATTRIBUTE_NUMBER6
,personelE0.ATTRIBUTE_NUMBER7
,personelE0.ATTRIBUTE_NUMBER8
,personelE0.ATTRIBUTE_NUMBER9
,personelE0.ATTRIBUTE_NUMBER10
,TO_CHAR(personelE0.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(personelE0.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(personelE0.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(personelE0.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(personelE0.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,TO_CHAR(personelE0.ATTRIBUTE_DATE6,'DD-Mon-YYYY') ATTRIBUTE_DATE6
,TO_CHAR(personelE0.ATTRIBUTE_DATE7,'DD-Mon-YYYY') ATTRIBUTE_DATE7
,TO_CHAR(personelE0.ATTRIBUTE_DATE8,'DD-Mon-YYYY') ATTRIBUTE_DATE8
,TO_CHAR(personelE0.ATTRIBUTE_DATE9,'DD-Mon-YYYY') ATTRIBUTE_DATE9
,TO_CHAR(personelE0.ATTRIBUTE_DATE10,'DD-Mon-YYYY') ATTRIBUTE_DATE10
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP1,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP1
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP2,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP2
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP3,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP3
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP4,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP4
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP5,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP5
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP6,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP6
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP7,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP7
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP8,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP8
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP9,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP9
,TO_CHAR(personelE0.ATTRIBUTE_TIMESTAMP10,'DD-Mon-YYYY HH24:MI:SS') ATTRIBUTE_TIMESTAMP10
,personelE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,personelE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,personelE0.CREATED_BY RSC_CREATED_BY
,personelE0.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM GMS_PERSONS personelE0
,PER_ALL_PEOPLE_F personsE0
,PER_PERSON_NAMES_F personNamesE0
,PER_ALL_ASSIGNMENTS_M assignmentsE0
WHERE personelE0.PERSON_ID = personsE0.PERSON_ID
AND personelE0.PERSON_ID = personNamesE0.PERSON_ID
AND personNamesE0.NAME_TYPE = 'GLOBAL'
AND personelE0.PERSON_ID = assignmentsE0.PERSON_ID
AND assignmentsE0.PRIMARY_FLAG = 'Y'
AND SYSDATE BETWEEN personsE0.EFFECTIVE_START_DATE AND NVL(personsE0.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN personNamesE0.EFFECTIVE_START_DATE AND NVL(personNamesE0.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN assignmentsE0.EFFECTIVE_START_DATE AND NVL(assignmentsE0.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND (personelE0.ATTRIBUTE_CATEGORY IS NOT NULL OR
	personelE0.ATTRIBUTE1 IS NOT NULL OR
	personelE0.ATTRIBUTE2 IS NOT NULL OR
	personelE0.ATTRIBUTE3 IS NOT NULL OR 
	personelE0.ATTRIBUTE4 IS NOT NULL OR 
	personelE0.ATTRIBUTE5 IS NOT NULL OR 
	personelE0.ATTRIBUTE6 IS NOT NULL OR 
	personelE0.ATTRIBUTE7 IS NOT NULL OR 
	personelE0.ATTRIBUTE8 IS NOT NULL OR 
	personelE0.ATTRIBUTE9 IS NOT NULL OR 
	personelE0.ATTRIBUTE10 IS NOT NULL OR 
	personelE0.ATTRIBUTE11 IS NOT NULL OR 
	personelE0.ATTRIBUTE12 IS NOT NULL OR 
	personelE0.ATTRIBUTE13 IS NOT NULL OR 
	personelE0.ATTRIBUTE14 IS NOT NULL OR 
	personelE0.ATTRIBUTE15 IS NOT NULL OR 
	personelE0.ATTRIBUTE16 IS NOT NULL OR 
	personelE0.ATTRIBUTE17 IS NOT NULL OR 
	personelE0.ATTRIBUTE18 IS NOT NULL OR 
	personelE0.ATTRIBUTE19 IS NOT NULL OR 
	personelE0.ATTRIBUTE20 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
	personelE0.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE1 IS NOT NULL OR
	personelE0.ATTRIBUTE_DATE2 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE3 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE4 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE5 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE6 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE7 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE8 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE9 IS NOT NULL OR 
	personelE0.ATTRIBUTE_DATE10 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP1 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP2 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP3 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP4 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP5 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP6 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP7 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP8 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP9 IS NOT NULL OR
	personelE0.ATTRIBUTE_TIMESTAMP10 IS NOT NULL)
ORDER BY personNamesE0.DISPLAY_NAME