/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Subledger%20Accounting%20Options%20-%20Journal%20Categories.sql $:
 * $Id: Manage Subledger Accounting Options - Journal Categories.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
SELECT GlLedgers.NAME                      RES_LEDGER
,SUBLEDGERAPPLICATIONPEO.APPLICATION_NAME  RES_SUBLEDGER_APPLICATION
,JEEVENTCLASSESVL.name                     RES_EVENT_CLASS
,(SELECT USER_JE_CATEGORY_NAME
	FROM GL_JE_CATEGORIES_VL
	WHERE JE_CATEGORY_NAME = EventClassOptionEO.JE_CATEGORY_NAME
	) AS RES_CATEGORY
,EventClassOptionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,EventClassOptionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,EventClassOptionEO.CREATED_BY RSC_CREATED_BY
,EventClassOptionEO.CREATION_DATE RSC_CREATION_DATE
,EventClassOptionEO.LEDGER_ID RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM GL_LEDGERS GLLEDGERS
,XLA_SUBLEDGERS_TL SUBLEDGERAPPLICATIONPEO
,XLA_JE_CATEGORIES EVENTCLASSOPTIONEO
,XLA_EVENT_CLASSES_VL JEEVENTCLASSESVL
WHERE EventClassOptionEO.LEDGER_ID      = GLLEDGERS.LEDGER_ID
AND EVENTCLASSOPTIONEO.APPLICATION_ID   = SUBLEDGERAPPLICATIONPEO.APPLICATION_ID
AND EVENTCLASSOPTIONEO.APPLICATION_ID   = 140
AND SUBLEDGERAPPLICATIONPEO.LANGUAGE    = USERENV('LANG')
AND SUBLEDGERAPPLICATIONPEO.APPLICATION_NAME != 'Subledger Accounting'
AND EVENTCLASSOPTIONEO.APPLICATION_ID   = JEEVENTCLASSESVL.APPLICATION_ID
AND EventClassOptionEO.EVENT_CLASS_CODE = JEEVENTCLASSESVL.EVENT_CLASS_CODE
ORDER BY GLLEDGERS.name
,SUBLEDGERAPPLICATIONPEO.APPLICATION_NAME
,JEEVENTCLASSESVL.name