/* ****************************************************************************
* $Revision: 55345 $:
* $Author: wuttipong.thongvises $:
* $Date: 2016-05-23 12:42:33 +0700 (Mon, 23 May 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/
FINANCIALS/Manage%20Server%20Configurations%20-%20Manage%20Data%20Quality%20Server%20Configurations.sql $:
* $Id: Manage Server Configurations - Manage Data Quality Server Configurations.sql 55345 2016-05-23 05:42:33Z
wuttipong.thongvises $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT payALLPREO.PAYROLL_NAME RES_NAME
,(SELECT ORG_PAYMENT_METHOD_NAME FROM PAY_ORG_PAY_METHODS_VL 
	WHERE ORG_PAYMENT_METHOD_ID = payORGPAYMETEO.ORG_PAYMENT_METHOD_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))) RES_ORGANIZATION_PAYMENT_METHO
,TO_CHAR(payORGPAYMETEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,TO_CHAR(payORGPAYMETEO.EFFECTIVE_END_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_END_DATE

,payORGPAYMETEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,payORGPAYMETEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,payORGPAYMETEO.CREATED_BY  RSC_CREATED_BY
,payORGPAYMETEO.CREATION_DATE  RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PAY_ALL_PAYROLLS_F payALLPREO
,PAY_ORG_PAY_METHOD_USAGES_F payORGPAYMETEO
WHERE payALLPREO.PAYROLL_ID = payORGPAYMETEO.PAYROLL_ID
AND SYSDATE BETWEEN payALLPREO.EFFECTIVE_START_DATE AND NVL(payALLPREO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
AND SYSDATE BETWEEN payORGPAYMETEO.EFFECTIVE_START_DATE AND NVL(payORGPAYMETEO.EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))