/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Distribution%20Sets%20-%20Distribution%20Set%20-%20DFF.sql $:
 * $Id: Manage Distribution Sets - Distribution Set - DFF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=200##RES##AP_DISTRIBUTION_SETS
-- DFF_ATTRIBUTES=ATTRIBUTE

-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.
 
SELECT DISTINCT BUSINESSUNITPEO.BU_NAME RES_BUSINESS_UNIT
,APDISTRIBUTIONSETSALL.DISTRIBUTION_SET_NAME RES_NAME
,APDISTRIBUTIONSETSALL.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,APDISTRIBUTIONSETSALL.ATTRIBUTE1
,APDISTRIBUTIONSETSALL.ATTRIBUTE2
,APDISTRIBUTIONSETSALL.ATTRIBUTE3
,APDISTRIBUTIONSETSALL.ATTRIBUTE4
,APDISTRIBUTIONSETSALL.ATTRIBUTE5
,APDISTRIBUTIONSETSALL.ATTRIBUTE6
,APDISTRIBUTIONSETSALL.ATTRIBUTE7
,APDISTRIBUTIONSETSALL.ATTRIBUTE8
,APDISTRIBUTIONSETSALL.ATTRIBUTE9
,APDISTRIBUTIONSETSALL.ATTRIBUTE10
,APDISTRIBUTIONSETSALL.ATTRIBUTE11
,APDISTRIBUTIONSETSALL.ATTRIBUTE12
,APDISTRIBUTIONSETSALL.ATTRIBUTE13
,APDISTRIBUTIONSETSALL.ATTRIBUTE14
,APDISTRIBUTIONSETSALL.ATTRIBUTE15
,APDISTRIBUTIONSETSALL.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,APDISTRIBUTIONSETSALL.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,APDISTRIBUTIONSETSALL.CREATED_BY RSC_CREATED_BY
,APDISTRIBUTIONSETSALL.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,APDISTRIBUTIONSETSALL.ORG_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FUN_ALL_BUSINESS_UNITS_V BUSINESSUNITPEO
,AP_DISTRIBUTION_SETS_ALL APDISTRIBUTIONSETSALL
WHERE BUSINESSUNITPEO.BU_ID                   = APDISTRIBUTIONSETSALL.ORG_ID
AND(APDISTRIBUTIONSETSALL.ATTRIBUTE_CATEGORY IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE1          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE2          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE3          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE4          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE5          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE6          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE7          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE8          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE9          IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE10         IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE11         IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE12         IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE13         IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE14         IS NOT NULL
OR APDISTRIBUTIONSETSALL.ATTRIBUTE15         IS NOT NULL)
ORDER BY ApDistributionSetsAll.DISTRIBUTION_SET_NAME