/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Transaction%20Sources%20-%20Manage%20Transaction%20Sources%20-%20DFF.sql $:
 * $Id: Manage Transaction Sources - Manage Transaction Sources - DFF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=222##RES##RA_BATCH_SOURCES
-- DFF_ATTRIBUTES=ATTRIBUTE,GLOBAL_ATTRIBUTE,GLOBAL_ATTRIBUTE_NUMBER,GLOBAL_ATTRIBUTE_DATE
-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.
 
select FND_SETID_SETS_VL.SET_NAME RES_TRANSACTION_SOURCE_SET
,RaBatchSourcesAll.NAME RES_NAME
,RaBatchSourcesAll.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,RaBatchSourcesAll.ATTRIBUTE1 
,RaBatchSourcesAll.ATTRIBUTE2
,RaBatchSourcesAll.ATTRIBUTE3
,RaBatchSourcesAll.ATTRIBUTE4
,RaBatchSourcesAll.ATTRIBUTE5
,RaBatchSourcesAll.ATTRIBUTE6
,RaBatchSourcesAll.ATTRIBUTE7
,RaBatchSourcesAll.ATTRIBUTE8
,RaBatchSourcesAll.ATTRIBUTE9
,RaBatchSourcesAll.ATTRIBUTE10
,RaBatchSourcesAll.ATTRIBUTE11
,RaBatchSourcesAll.ATTRIBUTE12
,RaBatchSourcesAll.ATTRIBUTE13
,RaBatchSourcesAll.ATTRIBUTE14
,RaBatchSourcesAll.ATTRIBUTE15
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE1 
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE2
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE3
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE4
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE5
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE6
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE7
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE8
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE9
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE10
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE11
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE12
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE13
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE14
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE15
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE16
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE17
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE18
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE19
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE20
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER1 
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER2
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER3
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER4
,RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER5
, TO_CHAR(RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE1, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE1
, TO_CHAR(RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE2, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE2
, TO_CHAR(RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE3, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE3
, TO_CHAR(RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE4, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE4
, TO_CHAR(RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE5, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE5
,RaBatchSourcesAll.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,RaBatchSourcesAll.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,RaBatchSourcesAll.CREATED_BY  RSC_CREATED_BY
,RaBatchSourcesAll.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,RaBatchSourcesAll.LEGAL_ENTITY_ID RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 

FROM FUSION.RA_BATCH_SOURCES_ALL RaBatchSourcesAll
,FUSION.FND_SETID_SETS_VL 
WHERE 
(RaBatchSourcesAll.ATTRIBUTE_CATEGORY IS NOT NULL OR
RaBatchSourcesAll.ATTRIBUTE1 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE2 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE3 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE4 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE5 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE6 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE7 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE8 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE9 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE10 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE11 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE12 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE13 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE14 IS NOT NULL OR 
RaBatchSourcesAll.ATTRIBUTE15 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE1 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE2 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE3 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE4 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE5 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE6 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE7 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE8 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE9 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE10 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE11 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE12 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE13 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE14 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE15 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE16 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE17 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE18 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE19 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE20 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER1 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER2 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER3 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER4 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_NUMBER5 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE1 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE2 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE3 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE4 IS NOT NULL OR
RaBatchSourcesAll.GLOBAL_ATTRIBUTE_DATE5 IS NOT NULL)
AND  FND_SETID_SETS_VL.SET_ID = RaBatchSourcesAll.SET_ID 
order by RES_NAME