/* ****************************************************************************
* $Revision: 59117 $:
* $Author: nasrullah.dusenmahamad $:
* $Date: 2016-10-21 11:10:58 +0700 (Fri, 21 Oct 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Key%20Flexfields%20-%20Segment%20Labels.sql $:
* $Id: Manage Key Flexfields - Segment Labels.sql 59117 2016-10-21 04:10:58Z nasrullah.dusenmahamad $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT TrxTypesE0.TRANSACTION_TYPE_NAME RES_TRANSACTION_TYPE
,(SELECT ORGANIZATION_CODE 
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ConsumptinRulesE0.FROM_ORGANIZATION_ID
	) RES_FROM_ORGANIZATION
,(SELECT ORGANIZATION_CODE 
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ConsumptinRulesE0.TO_ORGANIZATION_ID
	) RES_TO_ORGANIZATION
,ConsumptinRulesE0.FROM_SUBINVENTORY_CODE RES_FROM_SUBINVENTORY
,(SELECT FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'INV',KEY_FLEX_CODE => 'MTLL',STRUCTURE_NUMBER =>
	STRUCTURE_INSTANCE_NUMBER,COMBINATION_ID => INVENTORY_LOCATION_ID,DATA_SET_NUMBER =>SUBINVENTORY_ID)
	FROM INV_ITEM_LOCATIONS
	WHERE INVENTORY_LOCATION_ID = ConsumptinRulesE0.FROM_LOCATOR_ID
	AND ORGANIZATION_ID = ConsumptinRulesE0.FROM_ORGANIZATION_ID
	) RES_FROM_LOCATOR
,ConsumptinRulesE0.TO_SUBINVENTORY_CODE RES_TO_SUBINVENTORY
,DECODE(TrxTypesE0.STATUS_CONTROL_FLAG,NULL,'No','Yes') RES_OWNERSHIP_CHANGE
,(SELECT FND_FLEX_EXT.GET_SEGS(APPLICATION_SHORT_NAME => 'INV',KEY_FLEX_CODE => 'MTLL',STRUCTURE_NUMBER =>
	STRUCTURE_INSTANCE_NUMBER,COMBINATION_ID => INVENTORY_LOCATION_ID,DATA_SET_NUMBER =>SUBINVENTORY_ID)
	FROM INV_ITEM_LOCATIONS
	WHERE INVENTORY_LOCATION_ID = ConsumptinRulesE0.TO_LOCATOR_ID
	AND ORGANIZATION_ID = ConsumptinRulesE0.TO_ORGANIZATION_ID
	) RES_TO_LOCATOR
,ItemsE0.ITEM_NUMBER RES_ITEM
,ItemsE0.DESCRIPTION RES_ITEM_DESCRIPTION
,OwningE0.VENDOR_SITE_CODE RES_OWNING_PARTY_SITE
,OwningE0.SUP_NAME RES_OWNING_PARTY
,ConsumptinRulesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ConsumptinRulesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ConsumptinRulesE0.CREATED_BY RSC_CREATED_BY
,ConsumptinRulesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,ConsumptinRulesE0.FROM_ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM INV_CONSUMPTION_RULES ConsumptinRulesE0
,INV_TRANSACTION_TYPES TrxTypesE0
,EGP_SYSTEM_ITEMS_V ItemsE0
,(SELECT SupSitesE0.VENDOR_SITE_ID
	,SupSitesE0.VENDOR_SITE_CODE
	,(SELECT PARTY_NAME
		FROM HZ_PARTIES
		WHERE PARTY_ID = SupsE0.PARTY_ID) SUP_NAME
	FROM POZ_SUPPLIER_SITES_ALL_M SupSitesE0
	,POZ_SUPPLIERS SupsE0
	WHERE SupsE0.VENDOR_ID = SupSitesE0.VENDOR_ID) OwningE0
WHERE ConsumptinRulesE0.TRANSACTION_TYPE_ID = TrxTypesE0.TRANSACTION_TYPE_ID
AND ConsumptinRulesE0.INVENTORY_ITEM_ID = ItemsE0.INVENTORY_ITEM_ID(+)
AND ConsumptinRulesE0.FROM_ORGANIZATION_ID = ItemsE0.ORGANIZATION_ID(+)
AND ConsumptinRulesE0.OWNING_ENTITY_ID = OwningE0.VENDOR_SITE_ID(+)