/* ****************************************************************************
 * $Revision: 55346 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-05-23 14:11:43 +0700 (Mon, 23 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Chart%20of%20Accounts%20Value%20Set%20Values%20-%20Manage%20Values.sql $:
 * $Id: Manage Chart of Accounts Value Set Values - Manage Values.sql 55346 2016-05-23 07:11:43Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=ANC_ABSENCE_PLANS_F

SELECT (SELECT NAME 
	FROM ANC_ABSENCE_PLANS_F_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND ABSENCE_PLAN_ID = absencePlansE0.ABSENCE_PLAN_ID
	AND EFFECTIVE_START_DATE = absencePlansE0.EFFECTIVE_START_DATE
	) RES_PLAN
,(SELECT TERRITORY_SHORT_NAME
	FROM FND_TERRITORIES_VL
	WHERE TERRITORY_CODE = absencePlansE0.LEGISLATION_CODE 
	) RES_LEGISLATION
,(SELECT NAME
	FROM PER_LEGISLATIVE_DATA_GROUPS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND LEGISLATIVE_DATA_GROUP_ID = absencePlansE0.LEGISLATIVE_DATA_GROUP_ID 
	) RES_LEGISLATIVE_DATA_GROUP
,TO_CHAR(absencePlansE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(absencePlansE0.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(absencePlansE0.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_DEFN_TYPE'
	AND LOOKUP_CODE = absencePlansE0.ACC_DEFINITION_TYPE 
	) RES_ACCRUAL_DEFINITION
,(SELECT BASE_FORMULA_NAME 
	FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = absencePlansE0.PARTIAL_ACCRUAL_FORMULA_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_PARTIAL_ACCRUAL_PERIOD_FOR
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_ACCRUAL_VESTING'
	AND LOOKUP_CODE = absencePlansE0.ACCRUAL_VESTING_CD
	) RES_VESTING_RULE
,(SELECT BASE_FORMULA_NAME 
	FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = absencePlansE0.VESTING_PERIOD_FORMULA_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_VESTING_PERIOD_FORMULA
,(CASE
	WHEN absencePlansE0.ACCRUAL_VESTING_CD = 'E' THEN
		absencePlansE0.VESTING_PERIOD_DURATION
	END) RES_DURATION
,(CASE
	WHEN absencePlansE0.ACCRUAL_VESTING_CD = 'E' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_SETUP_OBJ_UOM_WITHOUT_HRS'
			AND LOOKUP_CODE = absencePlansE0.VESTING_PERIOD_UOM)
	END) RES_UOM
,absencePlansE0.PAY_RATE_FACTOR RES_PAYMENT_PERCENTAGE
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_ACCRUAL_METHOD'
	AND LOOKUP_CODE = absencePlansE0.ACCRUAL_METHOD_CD 
	) RES_ACCRUAL_METHOD
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_PRORATION'
	AND LOOKUP_CODE = absencePlansE0.PRORATION_RULE 
	) RES_ACCRUAL_PRORATION_RULE
,(SELECT BASE_FORMULA_NAME 
	FROM FF_FORMULAS_VL 
	WHERE FORMULA_ID = absencePlansE0.PRORATION_FORMULA_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD'))
	) RES_ACCRUAL_PRORATION_FORMULA
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_ACC_PER_FREQUENCY'
	AND LOOKUP_CODE = absencePlansE0.ACC_PERIOD_FREQUENCY 
	) RES_BALANCE_FREQUENCY_SOURCE
,(SELECT NAME
	FROM HWM_RP_TM_PERIODS_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND REPEATING_TM_PERIOD_ID = absencePlansE0.ACC_PERIOD_WFM_CALEDAR_ID 
	) RES_REPEATING_PERIOD
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_CARRY_OVER'
	AND LOOKUP_CODE = absencePlansE0.CEIL_LIMIT_RULE 
	) RES_CEILING_RULE
,(CASE
	WHEN absencePlansE0.CEIL_LIMIT_RULE = 'A' THEN
		absencePlansE0.CEIL_LIMIT_FLAT_AMT 
	END) RES_CEILING
,(CASE
	WHEN absencePlansE0.CEIL_LIMIT_RULE = 'F' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.CEIL_LIMIT_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_CEILING_FORMULA
,(CASE
	WHEN absencePlansE0.CEIL_LIMIT_RULE IN ('A','F','M') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_CEIL_LMT_PRORATION'
			AND LOOKUP_CODE = absencePlansE0.CEIL_LIMIT_PRORATE_RULE)
	END) RES_CEILING_PRORATION_RULE
,(CASE
	WHEN absencePlansE0.CEIL_LIMIT_PRORATE_RULE = 'F' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.CEIL_LMT_PRORATE_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_CEILING_PRORATION_FORMULA
,DECODE(absencePlansE0.ACC_NEGATIVE_BAL_FLAG,'Y','Yes','No') RES_ALLOW_NEGATIVE_BALANCE
,(CASE
	WHEN absencePlansE0.ACC_NEGATIVE_BAL_FLAG = 'Y' THEN
		absencePlansE0.ACC_NEGATIVE_BAL_LIMIT 
	END) RES_NEGATIVE_BALANCE_LIMIT
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_CARRY_OVER'
	AND LOOKUP_CODE = absencePlansE0.ACC_LMT_RULE 
	) RES_ANNUAL_ACCRUAL_LIMIT_RULE
,(CASE
	WHEN absencePlansE0.ACC_LMT_RULE = 'A' THEN
		absencePlansE0.ACC_LMT_FLAT_AMT 
	END) RES_ANNUAL_ACCRUAL_LIMIT
,(CASE
	WHEN absencePlansE0.ACC_LMT_RULE = 'F' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.ACC_LIMIT_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_LIMIT_FORMULA
,(CASE
	WHEN absencePlansE0.ACC_LMT_RULE != 'N' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_CEIL_LMT_PRORATION'
			AND LOOKUP_CODE = absencePlansE0.ACC_LIMIT_PRORATE_RULE)
	END) RES_LIMIT_PRORATION_RULE
,(CASE
	WHEN absencePlansE0.ACC_LIMIT_PRORATE_RULE = 'F' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.ACC_LMT_PRORATE_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_LIMIT_PRORATION_FORMULA
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ORA_ANC_ROLLOVER_RULE'
	AND LOOKUP_CODE = absencePlansE0.ROLLOVR_LMT_RULE 
	) RES_ROLLOVER_RULE
,(CASE
	WHEN absencePlansE0.ROLLOVR_LMT_RULE = 'ORA_ANC_LIMIT_BY_VALUE' THEN
		absencePlansE0.ROLLOVR_LMT_FLAT_AMT 
	END) RES_ROLLOVER_LIMIT
,(CASE
	WHEN absencePlansE0.ROLLOVR_LMT_RULE IN ('ORA_ANC_LIMIT_BY_FORMULA','ORA_ANC_LIMIT_BY_VALUE') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_CEIL_LMT_PRORATION'
			AND LOOKUP_CODE = absencePlansE0.ROLLOVR_LMT_PRORATE_RULE)
	END) RES_YEAR_END_PROCESSING_LIMIT_ -- Year End Processing - Limit Proration Rule
,(CASE
	WHEN absencePlansE0.ROLLOVR_LMT_RULE = 'ORA_ANC_LIMIT_BY_FORMULA' THEN
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.ROLLOVR_LMT_PRORATE_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_YEAR_END_PROCESSING_LIMI_0 -- Year End Processing - Limit Proration Formula
,(CASE
	WHEN absencePlansE0.ROLLOVR_LMT_RULE IN ('ORA_ANC_LIMIT_BY_FORMULA','ORA_ANC_LIMIT_BY_VALUE','ORA_ANC_UNLIMITED') THEN
		(SELECT NAME
			FROM ANC_ABSENCE_PLANS_F_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND ABSENCE_PLAN_ID = absencePlansE0.ROLLOVR_TARGET_PLAN)
	END) RES_ROLLOVER_TARGET_PLAN
,(CASE
	WHEN absencePlansE0.ROLLOVR_LMT_RULE IN ('ORA_ANC_LIMIT_BY_FORMULA','ORA_ANC_LIMIT_BY_VALUE','ORA_ANC_UNLIMITED') THEN
		absencePlansE0.ROLLOVR_PLAN_CONVERSION_RATE 
	END) RES_CONVERSION_FACTOR
,(SELECT MEANING
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'ANC_CARRY_OVER'
	AND LOOKUP_CODE = absencePlansE0.CARRY_OVER_RULE 
	) RES_CARRYOVER_LIMIT_RULE
,(CASE
	WHEN absencePlansE0.CARRY_OVER_RULE = 'A' THEN 
		absencePlansE0.CARRY_OVER_FLAT_AMT 
	END) RES_CARRYOVER_LIMIT
,(CASE
	WHEN absencePlansE0.CARRY_OVER_RULE = 'F' THEN 
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.CARRY_OVER_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_CARRYOVER_FORMULA
,(CASE
	WHEN absencePlansE0.CARRY_OVER_RULE IN ('A','F','M') THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ANC_CARRY_OVER_PRORATION'
			AND LOOKUP_CODE = absencePlansE0.CARRY_OVER_PRORATE_RULE)
	END) RES_CARRYOVER_PRORATION_RULE
,(CASE
	WHEN absencePlansE0.CARRY_OVER_RULE = 'F' AND absencePlansE0.CARRY_OVER_PRORATE_RULE = 'F' THEN 
		(SELECT BASE_FORMULA_NAME 
			FROM FF_FORMULAS_VL 
			WHERE FORMULA_ID = absencePlansE0.CARRY_OVER_PRORATE_FORMULA_ID
			AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('4712-12-31','YYYY-MM-DD')))
	END) RES_CARRYOVER_PRORATION_FORMUL
,(CASE
	WHEN absencePlansE0.CARRY_OVER_RULE IN ('A','F','M') THEN
		DECODE(absencePlansE0.CARRY_OVER_EXPIRED_FLAG,'Y','Yes','No')
	END) RES_CARRYOVERS_EXPIRE_AFTER_SP
,(CASE
	WHEN absencePlansE0.CARRY_OVER_RULE IN ('A','F','M') THEN
		(CASE
			WHEN absencePlansE0.CARRY_OVER_EXPIRED_FLAG = 'Y' THEN
				absencePlansE0.CARRY_OVER_EXPIRED_UNITS 
			END)
	END) RES_EXPIRATION_PERIOD
,(CASE
	WHEN absencePlansE0.CARRY_OVER_RULE IN ('A','F','M') THEN
		(CASE
			WHEN absencePlansE0.CARRY_OVER_EXPIRED_FLAG = 'Y' THEN
				(SELECT MEANING
					FROM FND_LOOKUP_VALUES
					WHERE LANGUAGE = USERENV('LANG')
					AND LOOKUP_TYPE = 'ANC_SETUP_OBJ_UOM_WITHOUT_HRS'
					AND LOOKUP_CODE = absencePlansE0.CARRY_OVER_EXPIRED_UOM)
			END)
	END) RES_EXPIRATION_PERIOD_TYPE
,DECODE(absencePlansE0.YEAR_END_BALANCE_DISBURSE_FLAG,'Y','Yes','No') RES_DISBURSE_REMAINING_BALANCE
,absencePlansE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,absencePlansE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,absencePlansE0.CREATED_BY  RSC_CREATED_BY
,absencePlansE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,absencePlansE0.LEGISLATION_CODE RSC_COUNTRY_ID
 
FROM ANC_ABSENCE_PLANS_F absencePlansE0
WHERE absencePlansE0.ENTL_METHOD_CD = 'A'
ORDER BY 1
,absencePlansE0.EFFECTIVE_START_DATE