/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Salary%20Range%20Differentials%20-%20Salary%20Range%20Differential.sql $:
 * $Id: Manage Salary Range Differentials - Salary Range Differential.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=CMP_RANGE_DIFFS_F_VL
  
SELECT cmpRANGEDIFFEO.NAME RES_DIFFERENTIAL_PROFILE
,cmpRANGEDIFFEO.CODE RES_CODE
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpRANGEDIFFEO.STATUS
		AND LOOKUP_TYPE = 'ACTIVE_INACTIVE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_STATUS
,TO_CHAR(cmpRANGEDIFFEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,(SELECT NAME FROM PER_LEGISLATIVE_DATA_GROUPS_VL 
	WHERE LEGISLATIVE_DATA_GROUP_ID = cmpRANGEDIFFEO.LEGISLATIVE_DATA_GROUP_ID) RES_LEGISLATIVE_DATA_GROUP
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpRANGEDIFFEO.CRITERIA
		AND LOOKUP_TYPE = 'ORA_CMP_RANGE_DIFF_CRITERIA' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_CRITERIA
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpRANGEDIFFEO.RANGE_DIFF_TYPE
		AND LOOKUP_TYPE = 'ORA_CMP_RANGE_DIFF_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_TYPE
,(SELECT GEOGRAPHY_TYPE_NAME  FROM HZ_GEOGRAPHY_TYPES_VL  WHERE  GEOGRAPHY_TYPE_ID = cmpRANGEDIFFEO.GEOGRAPHY_TYPE_ID) RES_COMPENSATION_ZONE_TYPE
,DECODE(cmpRANGEDIFFEO.PROCESS_WFH_FLAG,'Y','Yes','No') RES_CHECK_FOR_REMOTE_WORKER_AD
,'1' RES_SEQUENCE_1
,'2' RES_SEQUENCE_2
,'3' RES_SEQUENCE_3
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpRANGEDIFFEO.ADDRESS_TYPE1
		AND LOOKUP_TYPE = 'ADDRESS_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_ADDRESS_TYPE_1
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpRANGEDIFFEO.ADDRESS_TYPE2
		AND LOOKUP_TYPE = 'ADDRESS_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_ADDRESS_TYPE_2
,(SELECT MEANING FROM FND_LOOKUP_VALUES WHERE LOOKUP_CODE = cmpRANGEDIFFEO.ADDRESS_TYPE3
		AND LOOKUP_TYPE = 'ADDRESS_TYPE' AND LANGUAGE = USERENV('LANG')
		AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_ADDRESS_TYPE_3


,cmpRANGEDIFFEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,cmpRANGEDIFFEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,cmpRANGEDIFFEO.CREATED_BY RSC_CREATED_BY
,cmpRANGEDIFFEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CMP_RANGE_DIFFS_F_VL cmpRANGEDIFFEO
WHERE  cmpRANGEDIFFEO.LANGUAGE = USERENV('LANG')
AND SYSDATE BETWEEN cmpRANGEDIFFEO.EFFECTIVE_START_DATE  AND NVL(cmpRANGEDIFFEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))