/* ****************************************************************************
 * $Revision:  $:
 * $Author: nasrullah dusenmahamad $:
 * $Date: 2018-07-11 $:
 * $HeadURL: $:
 * $Id: Manage Bank Branch Addresses - Spain - DFF.sql $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=10020##RES##HRA_DOC_TYPES_B
-- DFF_ATTRIBUTES=ATTRIBUTE,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

SELECT hRADTEO.NAME RES_NAME
,TO_CHAR(hRADTEO.DATE_FROM,'DD-Mon-YYYY') RES_FROM_DATE
,hRADTEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,hRADTEO.ATTRIBUTE1
,hRADTEO.ATTRIBUTE2
,hRADTEO.ATTRIBUTE3
,hRADTEO.ATTRIBUTE4
,hRADTEO.ATTRIBUTE5
,hRADTEO.ATTRIBUTE6
,hRADTEO.ATTRIBUTE7
,hRADTEO.ATTRIBUTE8
,hRADTEO.ATTRIBUTE9
,hRADTEO.ATTRIBUTE10
,hRADTEO.ATTRIBUTE11
,hRADTEO.ATTRIBUTE12
,hRADTEO.ATTRIBUTE13
,hRADTEO.ATTRIBUTE14
,hRADTEO.ATTRIBUTE15
,hRADTEO.ATTRIBUTE16
,hRADTEO.ATTRIBUTE17
,hRADTEO.ATTRIBUTE18
,hRADTEO.ATTRIBUTE19
,hRADTEO.ATTRIBUTE20
,hRADTEO.ATTRIBUTE21
,hRADTEO.ATTRIBUTE22
,hRADTEO.ATTRIBUTE23
,hRADTEO.ATTRIBUTE24
,hRADTEO.ATTRIBUTE25
,hRADTEO.ATTRIBUTE26
,hRADTEO.ATTRIBUTE27
,hRADTEO.ATTRIBUTE28
,hRADTEO.ATTRIBUTE29
,hRADTEO.ATTRIBUTE30
,hRADTEO.ATTRIBUTE_NUMBER1
,hRADTEO.ATTRIBUTE_NUMBER2
,hRADTEO.ATTRIBUTE_NUMBER3
,hRADTEO.ATTRIBUTE_NUMBER4
,hRADTEO.ATTRIBUTE_NUMBER5
,hRADTEO.ATTRIBUTE_NUMBER6
,hRADTEO.ATTRIBUTE_NUMBER7
,hRADTEO.ATTRIBUTE_NUMBER8
,hRADTEO.ATTRIBUTE_NUMBER9
,hRADTEO.ATTRIBUTE_NUMBER10
,hRADTEO.ATTRIBUTE_NUMBER11
,hRADTEO.ATTRIBUTE_NUMBER12
,hRADTEO.ATTRIBUTE_NUMBER13
,hRADTEO.ATTRIBUTE_NUMBER14
,hRADTEO.ATTRIBUTE_NUMBER15
,hRADTEO.ATTRIBUTE_NUMBER16
,hRADTEO.ATTRIBUTE_NUMBER17
,hRADTEO.ATTRIBUTE_NUMBER18
,hRADTEO.ATTRIBUTE_NUMBER19
,hRADTEO.ATTRIBUTE_NUMBER20
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE6,'DD-Mon-YYYY') ATTRIBUTE_DATE6
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE7,'DD-Mon-YYYY') ATTRIBUTE_DATE7
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE8,'DD-Mon-YYYY') ATTRIBUTE_DATE8
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE9,'DD-Mon-YYYY') ATTRIBUTE_DATE9
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE10,'DD-Mon-YYYY') ATTRIBUTE_DATE10
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE11,'DD-Mon-YYYY') ATTRIBUTE_DATE11
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE12,'DD-Mon-YYYY') ATTRIBUTE_DATE12
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE13,'DD-Mon-YYYY') ATTRIBUTE_DATE13
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE14,'DD-Mon-YYYY') ATTRIBUTE_DATE14
,TO_CHAR(hRADTEO.ATTRIBUTE_DATE15,'DD-Mon-YYYY') ATTRIBUTE_DATE15

,hRADTEO.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,hRADTEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,hRADTEO.CREATED_BY  RSC_CREATED_BY
,hRADTEO.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HRA_DOC_TYPES_VL hRADTEO
WHERE (hRADTEO.ATTRIBUTE_CATEGORY IS NOT NULL OR
hRADTEO.ATTRIBUTE1 IS NOT NULL OR 
hRADTEO.ATTRIBUTE2 IS NOT NULL OR 
hRADTEO.ATTRIBUTE3 IS NOT NULL OR 
hRADTEO.ATTRIBUTE4 IS NOT NULL OR 
hRADTEO.ATTRIBUTE5 IS NOT NULL OR 
hRADTEO.ATTRIBUTE6 IS NOT NULL OR 
hRADTEO.ATTRIBUTE7 IS NOT NULL OR 
hRADTEO.ATTRIBUTE8 IS NOT NULL OR 
hRADTEO.ATTRIBUTE9 IS NOT NULL OR 
hRADTEO.ATTRIBUTE10 IS NOT NULL OR 
hRADTEO.ATTRIBUTE11 IS NOT NULL OR 
hRADTEO.ATTRIBUTE12 IS NOT NULL OR 
hRADTEO.ATTRIBUTE13 IS NOT NULL OR 
hRADTEO.ATTRIBUTE14 IS NOT NULL OR 
hRADTEO.ATTRIBUTE15 IS NOT NULL OR
hRADTEO.ATTRIBUTE16 IS NOT NULL OR 
hRADTEO.ATTRIBUTE17 IS NOT NULL OR 
hRADTEO.ATTRIBUTE18 IS NOT NULL OR 
hRADTEO.ATTRIBUTE19 IS NOT NULL OR 
hRADTEO.ATTRIBUTE20 IS NOT NULL OR
hRADTEO.ATTRIBUTE21 IS NOT NULL OR 
hRADTEO.ATTRIBUTE22 IS NOT NULL OR 
hRADTEO.ATTRIBUTE23 IS NOT NULL OR 
hRADTEO.ATTRIBUTE24 IS NOT NULL OR 
hRADTEO.ATTRIBUTE25 IS NOT NULL OR
hRADTEO.ATTRIBUTE26 IS NOT NULL OR 
hRADTEO.ATTRIBUTE27 IS NOT NULL OR 
hRADTEO.ATTRIBUTE28 IS NOT NULL OR 
hRADTEO.ATTRIBUTE29 IS NOT NULL OR 
hRADTEO.ATTRIBUTE30 IS NOT NULL OR
hRADTEO.ATTRIBUTE_NUMBER1 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER2 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER3 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER4 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER5 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER6 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER7 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER8 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER9 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER10 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER11 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER12 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER13 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER14 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER15 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER16 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER17 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER18 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER19 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_NUMBER20 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_DATE1 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_DATE2 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_DATE3 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE4 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE5 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE6 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE7 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE8 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE9 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_DATE10 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_DATE11 IS NOT NULL OR 
hRADTEO.ATTRIBUTE_DATE12 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE13 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE14 IS NOT NULL OR
hRADTEO.ATTRIBUTE_DATE15 IS NOT NULL 
)
ORDER BY hRADTEO.NAME

