/* ****************************************************************************
* $Revision: 55454 $:
* $Author: dhara.pithadiya $:
* $Date: 2016-05-25 18:58:04 +0700 (Wed, 25 May 2016) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20AutoInvoice%20Line%20Ordering%20Rules%20-%20AutoInvoice%20Line%20Ordering%20Rules%20-%20DFF.sql $:
* $Id: Manage AutoInvoice Line Ordering Rules - AutoInvoice Line Ordering Rules - DFF.sql 55454 2016-05-25 11:58:04Z dhara.pithadiya $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=707##RES##CST_COST_INV_ORGS
-- DFF_ATTRIBUTES=ATTRIBUTE_CHAR,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT:
--  - the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.

SELECT CostOrgEO.COST_ORG_NAME RES_COST_ORGANIZATION
,OrganizationDefinitionPEO.ORGANIZATION_NAME RES_ORGANIZATION_NAME
,CostInvOrgEO.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,CostInvOrgEO.ATTRIBUTE_CHAR1
,CostInvOrgEO.ATTRIBUTE_CHAR2
,CostInvOrgEO.ATTRIBUTE_CHAR3
,CostInvOrgEO.ATTRIBUTE_CHAR4
,CostInvOrgEO.ATTRIBUTE_CHAR5
,CostInvOrgEO.ATTRIBUTE_CHAR6
,CostInvOrgEO.ATTRIBUTE_CHAR7
,CostInvOrgEO.ATTRIBUTE_CHAR8
,CostInvOrgEO.ATTRIBUTE_CHAR9
,CostInvOrgEO.ATTRIBUTE_CHAR10
,CostInvOrgEO.ATTRIBUTE_CHAR11
,CostInvOrgEO.ATTRIBUTE_CHAR12
,CostInvOrgEO.ATTRIBUTE_CHAR13
,CostInvOrgEO.ATTRIBUTE_CHAR14
,CostInvOrgEO.ATTRIBUTE_CHAR15
,CostInvOrgEO.ATTRIBUTE_CHAR16
,CostInvOrgEO.ATTRIBUTE_CHAR17
,CostInvOrgEO.ATTRIBUTE_CHAR18
,CostInvOrgEO.ATTRIBUTE_CHAR19
,CostInvOrgEO.ATTRIBUTE_CHAR20
,CostInvOrgEO.ATTRIBUTE_NUMBER1
,CostInvOrgEO.ATTRIBUTE_NUMBER2
,CostInvOrgEO.ATTRIBUTE_NUMBER3
,CostInvOrgEO.ATTRIBUTE_NUMBER4
,CostInvOrgEO.ATTRIBUTE_NUMBER5
,CostInvOrgEO.ATTRIBUTE_NUMBER6
,CostInvOrgEO.ATTRIBUTE_NUMBER7
,CostInvOrgEO.ATTRIBUTE_NUMBER8
,CostInvOrgEO.ATTRIBUTE_NUMBER9
,CostInvOrgEO.ATTRIBUTE_NUMBER10
,TO_CHAR(CostInvOrgEO.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(CostInvOrgEO.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(CostInvOrgEO.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(CostInvOrgEO.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(CostInvOrgEO.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,CostInvOrgEO.ATTRIBUTE_TIMESTAMP1
,CostInvOrgEO.ATTRIBUTE_TIMESTAMP2
,CostInvOrgEO.ATTRIBUTE_TIMESTAMP3
,CostInvOrgEO.ATTRIBUTE_TIMESTAMP4
,CostInvOrgEO.ATTRIBUTE_TIMESTAMP5
,CostInvOrgEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,CostInvOrgEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,CostInvOrgEO.CREATED_BY RSC_CREATED_BY
,CostInvOrgEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,CostInvOrgEO.COST_ORG_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CST_COST_ORG_PARAMETERS CostOrgParametersEO
,CST_COST_ORGS_V CostOrgEO
,CST_COST_INV_ORGS CostInvOrgEO
,CST_ORGANIZATION_DEFINITIONS_V OrganizationDefinitionPEO
WHERE CostOrgParametersEO.COST_ORG_ID       = CostOrgEO.COST_ORG_ID
AND sysdate BETWEEN CostOrgEO.EFFECTIVE_START_DATE AND CostOrgEO.EFFECTIVE_END_DATE
AND CostOrgParametersEO.COST_ORG_ID = CostInvOrgEO.COST_ORG_ID
AND CostInvOrgEO.INV_ORG_ID         = OrganizationDefinitionPEO.ORGANIZATION_ID
AND OrganizationDefinitionPEO.CLASSIFICATION_CODE = 'INV'
AND (CostInvOrgEO.ATTRIBUTE_CATEGORY IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR1       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR2       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR3       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR4       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR5       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR6       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR7       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR8       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR9       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR10      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR11      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR12      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR13      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR14      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR15      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR16      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR17      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR18      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR19      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_CHAR20      IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER1     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER2     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER3     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER4     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER5     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER6     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER7     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER8     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER9     IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_NUMBER10    IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_DATE1       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_DATE2       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_DATE3       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_DATE4       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_DATE5       IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_TIMESTAMP1  IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_TIMESTAMP2  IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_TIMESTAMP3  IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_TIMESTAMP4  IS NOT NULL
OR CostInvOrgEO.ATTRIBUTE_TIMESTAMP5  IS NOT NULL)
ORDER BY CostOrgEO.COST_ORG_NAME
,OrganizationDefinitionPEO.ORGANIZATION_NAME