/* ****************************************************************************
* $Revision: 78735 $:
* $Author: pisan.jariyasettachok $:
* $Date: 2022-06-13 20:34:08 +0700 (Mon, 13 Jun 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Tax%20Rates%20and%20Tax%20Recovery%20Rates%20-%20Transaction%20Recovery%20Rate%20Account%20Details.sql $:
* $Id: Manage Tax Rates and Tax Recovery Rates - Transaction Recovery Rate Account Details.sql 78735 2022-06-13 13:34:08Z pisan.jariyasettachok $:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- FIELD_TO_APPLY_FUNCTION=RES_TAX_RECOVERABLE_ACCOUNT/GET_CODE_COMBINATION

SELECT ZxRatesVl.TAX_REGIME_CODE AS RES_TAX_REGIME_CODE
,party.PARTY_NAME AS RES_CONFIGURATION_OWNER
,ZxRatesVl.TAX AS RES_TAX
,ZxRatesVl.TAX_RATE_CODE AS RES_TAX_RECOVERY_RATE_CODE
,ZxRatesVl.PERCENTAGE_RATE AS RES_RATE_PERCENTAGE
,TO_CHAR(ZxRatesVl.EFFECTIVE_FROM,'DD-Mon-YYYY') AS RES_EFFECTIVE_START_DATE
,(SELECT name
	FROM gl_ledgers
	WHERE ledger_id = ZA.LEDGER_ID
	) AS RES_LEDGER
,(SELECT BU_NAME
	FROM FUN_ALL_BUSINESS_UNITS_V
	WHERE BU_ID = ZA.INTERNAL_ORGANIZATION_ID--Tax.BU_ID
	) AS RES_BUSINESS_UNIT
,ZA.TAX_ACCOUNT_CCID AS RES_TAX_RECOVERABLE_ACCOUNT
,ZxRatesVl.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ZxRatesVl.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ZxRatesVl.CREATED_BY RSC_CREATED_BY
,ZxRatesVl.CREATION_DATE RSC_CREATION_DATE
,ZA.LEDGER_ID RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,(CASE
	WHEN party.PARTY_TYPE_CODE = 'OU' THEN
		party.BU_ID
	END) RSC_BUSINESS_UNIT_ID
,(CASE
	WHEN party.PARTY_TYPE_CODE = 'FIRST_PARTY' THEN
		party.LEGAL_ENTITY_ID
	END) RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM ZX_RATES_VL ZxRatesVl,
ZX_FIRST_PARTY_ORGS_MOAC_V party,
ZX_REGIMES_VL RegimeTLEO, 
ZX_MCO_CHECK_ACCESS_V ZMCAV,
ZX_ACCOUNTS ZA,
ZX_MCO_LV_TAXES_V Tax
WHERE  RegimeTLEO.TAX_REGIME_CODE         = ZxRatesVl.TAX_REGIME_CODE
AND party.party_tax_profile_id            = ZxRatesVl.CONTENT_OWNER_ID
AND ZxRatesVl.ACTIVE_FLAG                 = 'Y'
AND ZxRatesVl.RATE_TYPE_CODE 			  = 'RECOVERY'
AND UPPER(NVL(RegimeTLEO.REGIME_TYPE_FLAG,'I')) = UPPER('I')  
AND ZMCAV.TAX_REGIME_CODE = ZxRatesVl.TAX_REGIME_CODE
AND ZMCAV.PARENT_FIRST_PTY_ORG_ID = ZxRatesVl.CONTENT_OWNER_ID
AND ZA.TAX_ACCOUNT_ENTITY_ID   			= ZxRatesVl.TAX_RATE_ID
AND Tax.TAX_REGIME_CODE     			= ZxRatesVl.TAX_REGIME_CODE
AND Tax.TAX                				= ZxRatesVl.TAX
AND Tax.CONTENT_OWNER_ID    			= ZxRatesVl.CONTENT_OWNER_ID
ORDER BY (SELECT DECODE(TAX_TYPE_CODE,'OFFSET',1,2) 
	FROM ZX_TAXES_VL 
	WHERE TAX = ZxRatesVl.TAX 
	AND CONTENT_OWNER_ID = ZxRatesVl.CONTENT_OWNER_ID
	AND TAX_REGIME_CODE = ZxRatesVl.TAX_REGIME_CODE
	)
,RES_TAX_RECOVERY_RATE_CODE