/* ****************************************************************************
 * $Revision: 77293 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2021-11-17 09:21:24 +0700 (Wed, 17 Nov 2021) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Programs%20-%20Enrollment.sql $:
 * $Id: Manage Benefit Programs - Enrollment.sql 77293 2021-11-17 02:21:24Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

SELECT RES_PROGRAM_NAME
,RES_EFFECTIVE_START_DATE
,RES_PROGRAM_HIERARCHY
,RES_PROGRAM_HIERARCHY_DESCRIPT
,RES_SCHEDULE_TYPE
,RES_ENROLLMENT_METHOD
,RES_AUTOMATIC_FORMULA
,RES_DEFAULT_ENROLLMENT_RULE
,RES_DEFAULT_ENROLLMENT_FORMULA
,RES_ENROLLMENT_CHANGE
,RES_CURRENT_ELIGIBILITY_PREVEN
,RES_CURRENT_ENROLLMENT_PREVENT
,RES_ASSIGN_ON_DEFAULT
,RES_EFFECTIVE_END_DATE
,RES_ENROLLMENT_RULE
,RES_ENROLLMENT_FORMULA
,RES_INTERIM_RULE
,RES_INTERIM_FORMULA
,RES_UNSUSPEND_ENROLLMENT_RULE
,RES_UNSUSPEND_ENROLLMENT_FORMU
,RES_UNSUSPEND_RATE_RULE
,RES_UNSUSPEND_RATE_FORMULA

,RSC_LAST_UPDATED_BY
,RSC_LAST_UPDATE_DATE
,RSC_CREATED_BY
,RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,RSC_COUNTRY_ID
	

FROM 
(SELECT benPGMEO.NAME RES_PROGRAM_NAME
,benPLT.NAME RES_PROGRAM_HIERARCHY
,'Plan Type' RES_PROGRAM_HIERARCHY_DESCRIPT
,TO_CHAR(benLERCHGPTIPEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(benLERCHGPTIPEO.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benLERCHGPTIPEO.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,(SELECT NAME FROM BEN_LER_F_VL WHERE LER_ID = benLERCHGPTIPEO.LER_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_SCHEDULE_TYPE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_MTHD'
    AND LOOKUP_CODE = benLERCHGPTIPEO.ENRT_MTHD_CD
    ) RES_ENROLLMENT_METHOD
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DFLT_ENRT'
    AND LOOKUP_CODE = benLERCHGPTIPEO.DFLT_ENRT_CD) RES_DEFAULT_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGPTIPEO.DFLT_ENRT_RL) RES_DEFAULT_ENROLLMENT_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_TCO_CHG_ENRT'
    AND LOOKUP_CODE = benLERCHGPTIPEO.TCO_CHG_ENRT_CD
    ) RES_ENROLLMENT_CHANGE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT'
    AND LOOKUP_CODE = benLERCHGPTIPEO.ENRT_CD
    ) RES_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGPTIPEO.ENRT_RL
    ) RES_ENROLLMENT_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DFLT_TO_ASN_PNDG_CTFN'
    AND LOOKUP_CODE = benLERCHGPTIPEO.DFLT_TO_ASN_PNDG_CTFN_CD) RES_INTERIM_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGPTIPEO.DFLT_TO_ASN_PNDG_CTFN_RL) RES_INTERIM_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_UNSSPND_ENRT'
    AND LOOKUP_CODE = benLERCHGPTIPEO.UNSSPND_ENRT_CD) RES_UNSUSPEND_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGPTIPEO.UNSSPND_ENRT_RL) RES_UNSUSPEND_ENROLLMENT_FORMU
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_UNSSPND_ENRT'
    AND LOOKUP_CODE = benLERCHGPTIPEO.UNSSPND_RT_CD) RES_UNSUSPEND_RATE_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGPTIPEO.UNSSPND_RT_RL) RES_UNSUSPEND_RATE_FORMULA
,DECODE(benLERCHGPTIPEO.STL_ELIG_CANT_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ELIGIBILITY_PREVEN
,DECODE(benLERCHGPTIPEO.CRNT_ENRT_PRCLDS_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ENROLLMENT_PREVENT
,DECODE(benLERCHGPTIPEO.DFLT_FLAG,'Y','Yes','No') RES_ASSIGN_ON_DEFAULT	
,NULL RES_AUTOMATIC_FORMULA
,'2' RES_SEQUENCE_0

,benLERCHGPTIPEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benLERCHGPTIPEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benLERCHGPTIPEO.CREATED_BY RSC_CREATED_BY
,benLERCHGPTIPEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID
	
	
FROM BEN_PGM_F benPGMEO
,BEN_PTIP_F benPT
,BEN_PL_TYP_F benPLT
,(SELECT * FROM BEN_LER_CHG_PTIP_ENRT_F 
	WHERE LER_ID IN (SELECT LER_ID FROM BEN_LER_F_VL WHERE TYP_CD IN ('SCHEDDA','SCHEDDO')
				AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) 
				AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) benLERCHGPTIPEO
WHERE benPGMEO.PGM_ID = benPT.PGM_ID
AND benPT.PL_TYP_ID = benPLT.PL_TYP_ID
AND benPT.PTIP_ID = benLERCHGPTIPEO.PTIP_ID
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPT.EFFECTIVE_START_DATE AND NVL(benPT.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLT.EFFECTIVE_START_DATE AND NVL(benPLT.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))


UNION

SELECT benPGMEO.NAME RES_PROGRAM_NAME
,benPL.NAME RES_PROGRAM_HIERARCHY
,'Plan' RES_PROGRAM_HIERARCHY_DESCRIPT
,TO_CHAR(benLERCHGPLIPEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,DECODE(TO_CHAR(benLERCHGPLIPEO.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benLERCHGPLIPEO.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_EFFECTIVE_END_DATE
,(SELECT NAME FROM BEN_LER_F_VL WHERE LER_ID = benLERCHGPLIPEO.LER_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE ,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_SCHEDULE_TYPE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT_MTHD'
    AND LOOKUP_CODE = benLERCHGPLIPEO.ENRT_MTHD_CD
    ) RES_ENROLLMENT_METHOD
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_DFLT_ENRT'
    AND LOOKUP_CODE = benLERCHGPLIPEO.DFLT_ENRT_CD) RES_DEFAULT_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGPLIPEO.DFLT_ENRT_RL) RES_DEFAULT_ENROLLMENT_FORMULA
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_TCO_CHG_ENRT'
    AND LOOKUP_CODE = benLERCHGPLIPEO.TCO_CHG_ENRT_CD
    ) RES_ENROLLMENT_CHANGE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_ENRT'
    AND LOOKUP_CODE = benLERCHGPLIPEO.ENRT_CD
    ) RES_ENROLLMENT_RULE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGPLIPEO.ENRT_RL
    ) RES_ENROLLMENT_FORMULA
,NULL RES_INTERIM_RULE
,NULL RES_INTERIM_FORMULA
,NULL RES_UNSUSPEND_ENROLLMENT_RULE
,NULL RES_UNSUSPEND_ENROLLMENT_FORMU
,NULL RES_UNSUSPEND_RATE_RULE
,NULL RES_UNSUSPEND_RATE_FORMULA
,DECODE(benLERCHGPLIPEO.STL_ELIG_CANT_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ELIGIBILITY_PREVEN
,DECODE(benLERCHGPLIPEO.CRNT_ENRT_PRCLDS_CHG_FLAG,'Y','Yes','No') RES_CURRENT_ENROLLMENT_PREVENT
,DECODE(benLERCHGPLIPEO.DFLT_FLAG,'Y','Yes','No') RES_ASSIGN_ON_DEFAULT	
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benLERCHGPLIPEO.AUTO_ENRT_MTHD_RL
    ) RES_AUTOMATIC_FORMULA
,'3' RES_SEQUENCE_0

,benLERCHGPLIPEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benLERCHGPLIPEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benLERCHGPLIPEO.CREATED_BY RSC_CREATED_BY
,benLERCHGPLIPEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID
	
	
FROM BEN_PGM_F benPGMEO
,BEN_PLIP_F benPLIP
,BEN_PL_F benPL
,(SELECT * FROM BEN_LER_CHG_PLIP_ENRT_F 
	WHERE LER_ID IN (SELECT LER_ID FROM BEN_LER_F_VL WHERE TYP_CD IN ('SCHEDDA','SCHEDDO')
				AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) 
				AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) benLERCHGPLIPEO
WHERE benPGMEO.PGM_ID = benPLIP.PGM_ID
AND benPLIP.PL_ID = benPL.PL_ID
AND benPLIP.PLIP_ID = benLERCHGPLIPEO.PLIP_ID
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLIP.EFFECTIVE_START_DATE AND NVL(benPLIP.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPL.EFFECTIVE_START_DATE AND NVL(benPL.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))

ORDER BY RES_PROGRAM_NAME,RES_SEQUENCE_0,RES_PROGRAM_HIERARCHY)
