/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Legal%20Reporting%20Unit%20HCM%20Information%20-%20IRAS%20Information.sql $:
 * $Id: Manage Legal Reporting Unit HCM Information - IRAS Information.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 
SELECT orgsE0.NAME RES_REGISTRATION_NAME
,orgsE0.REGISTRATION_NUMBER RES_REGISTRATION_NUMBER
,TO_CHAR(orgsE0.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,(SELECT MEANING
    FROM FND_LOOKUPS
    WHERE LOOKUP_TYPE = 'CODE_STATUS'
    AND LOOKUP_CODE = orgsE0.STATUS
    ) RES_STATUS
,irasE0.ORG_INFORMATION1 RES_IR21_CONTACT_NAME
,irasE0.ORG_INFORMATION2 RES_IR21_CONTACT_NUMBER
,irasE0.ORG_INFORMATION5 RES_IRAS_PHONE_NUMBER
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'HRX_SG_PAYER_ID_TYPE'
	AND LOOKUP_CODE = irasE0.ORG_INFORMATION6 
	) RES_IRAS_PAYER_ID_TYPE
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'HRX_SG_DESIGNATION_TYPE'
	AND LOOKUP_CODE = irasE0.ORG_INFORMATION7 
	) RES_IRAS_JOB_DESIGNATION_TYPE
,TO_CHAR(irasE0.ORG_INFORMATION_DATE1,'DD-Mon-YYYY') RES_BONUS_DATE
,TO_CHAR(irasE0.ORG_INFORMATION_DATE2,'DD-Mon-YYYY') RES_IRAS_DATE_OF_INCORPORATION
,DECODE(irasE0.ORG_INFORMATION3,'Y','Yes','No') RES_IRAS_OVERSEAS_HEADQUARTER_
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_TYPE = 'HRX_SG_ER_IRAS_CATEGORY'
	AND LOOKUP_CODE = irasE0.ORG_INFORMATION4 
	) RES_EMPLOYER_IRAS_CATEGORY
,irasE0.ORG_INFORMATION8 RES_IRAS_POSITION_SEGMENT_TYPE
,DECODE(irasE0.ORG_INFORMATION9,'Y','Yes','No') RES_ENABLE_A8A_PROCESSING
,irasE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,irasE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,irasE0.CREATED_BY RSC_CREATED_BY
,irasE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM (SELECT orgsE0.ORGANIZATION_ID
	,(SELECT NAME
		FROM XLE_ETB_PROFILES
		WHERE ESTABLISHMENT_ID = orgsE0.ESTABLISHMENT_ID
		) NAME
	,orgsE0.STATUS
	,orgsE0.EFFECTIVE_START_DATE
	,orgsE0.EFFECTIVE_END_DATE
	,REG.REGISTRATION_NUMBER
	FROM HR_ORGANIZATION_V orgsE0
	,XLE_REGISTRATIONS REG
	WHERE orgsE0.CLASSIFICATION_CODE = 'HCM_LRU'
	AND orgsE0.STATUS = 'A'
	AND orgsE0.ESTABLISHMENT_ID = REG.SOURCE_ID
	AND REG.IDENTIFYING_FLAG = 'Y'
	) orgsE0
,(SELECT *
    FROM HR_ORGANIZATION_INFORMATION_F
    WHERE ORG_INFORMATION_CONTEXT = 'HRX_SG_IRAS_INFORMATION'
    ) irasE0
WHERE orgsE0.ORGANIZATION_ID = irasE0.ORGANIZATION_ID
AND orgsE0.EFFECTIVE_START_DATE BETWEEN irasE0.EFFECTIVE_START_DATE AND irasE0.EFFECTIVE_END_DATE
AND (EXISTS (SELECT 1 FROM HR_ORG_DETAILS_BY_CLASS_V WHERE ORGANIZATION_ID = orgsE0.ORGANIZATION_ID AND CLASSIFICATION_CODE = 'HCM_REPORTING_ESTABLISHMENT')
	OR EXISTS (SELECT 1 FROM HR_ORG_DETAILS_BY_CLASS_V WHERE ORGANIZATION_ID = orgsE0.ORGANIZATION_ID AND CLASSIFICATION_CODE = 'HCM_TRU'))
ORDER BY orgsE0.NAME
,orgsE0.EFFECTIVE_START_DATE