/* ****************************************************************************
 * $Revision: 54470 $:
 * $Author: wuttipong.thongvises $:
 * $Date: 2016-04-19 10:52:05 +0700 (Tue, 19 Apr 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Contact%20Point%20Lookups%20-%20Lookup%20Codes.sql $:
 * $Id: Manage Contact Point Lookups - Lookup Codes.sql 54470 2016-04-19 03:52:05Z wuttipong.thongvises $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- RSC_PREREQUISITE_OBJECTS=CST_COST_PROFILES_VL
 
SELECT SetIdSetPEO.SET_NAME RES_COST_PROFILE_SET
,CostProfileEO.COST_PROFILE_CODE RES_COST_PROFILE
,CostProfileEO.COST_PROFILE_DESC RES_DESCRIPTION
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'CST_COST_METHODS'
	AND LOOKUP_CODE = CostProfileEO.COST_METHOD_CODE
	) RES_COST_METHOD
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'CST_NEGATIVE_QUANTITY_CODES'
	AND LOOKUP_CODE = CostProfileEO.NEGATIVE_QTY_CODE
	) RES_PROCESS_NEGATIVE_QUANTITY
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'CST_QUANTITY_FLOW_CODES'
	AND LOOKUP_CODE = CostProfileEO.QUANTITY_FLOW_CODE
	) RES_QUANTITY_DEPLETION_METHOD
,DECODE(CostProfileEO.IGNORE_INTRA_VU_XFER_FLAG,'N','Yes','No') RES_ACCOUNT_INTRAVALUATION_UNI
,ValStructurePEO.VAL_STRUCTURE_CODE RES_VALUATION_STRUCTURE_CODE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'CST_VALUATION_STRUCTURE_TYPES'
	AND LOOKUP_CODE = ValStructurePEO.VAL_STRUCTURE_TYPE_CODE
	) RES_VALUATION_STRUCTURE_TYPE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'CST_COST_BY_UOM_CODES'
	AND LOOKUP_CODE = CostProfileEO.COST_BY_UOM_TYPE
	) RES_COST_BY
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_CST_PARTIAL_COMPLETION'
	AND LOOKUP_CODE = CostProfileEO.PROVISIONAL_COMPLETION_TYPE
	) RES_PROVISIONAL_COMPLETIONS
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_CST_PARTIAL_COMPLETION'
	AND LOOKUP_CODE = CostProfileEO.PROCESS_PROV_COMPLETION_TYPE
	) RES_PROVISIONAL_COMPLETIONS_FO
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_CST_OPERATION_SCRAP'
	AND LOOKUP_CODE = CostProfileEO.OPERATION_SCRAP_COST_TYPE
	) RES_OPERATION_SCRAP_ACCOUNTING
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_CST_OP_SCRAP_VALUATION'
	AND LOOKUP_CODE = CostProfileEO.OPERATION_SCRAP_VALUATION_TYPE
	) RES_OPERATION_SCRAP_VALUATION
,ComponentGroupPEO.COMPONENT_GROUP_CODE RES_COST_COMPONENT_MAPPING_GRO
,AnalysisMappingPEO.ANALYSIS_MAPPING_CODE RES_ANALYSIS_MAPPING
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'CST_RECEIPT_WITHOUT_COST'
	AND LOOKUP_CODE = CostProfileEO.RECEIPT_WITHOUT_COST_CODE
	) RES_RECEIPT_WITHOUT_COST
,DECODE(CostProfileEO.PROPAGATE_COST_ADJ_FLAG,'Y','Yes','No') RES_PROPAGATE_COST_ADJUSTMENT
,(CASE
	WHEN CostProfileEO.PROPAGATE_COST_ADJ_FLAG = 'N' THEN
		DECODE(CostProfileEO.ENFORCE_TXN_DATE_ORDER_FLAG,'Y','Yes','No')
	END) RES_ENFORCE_PROCESSING_OF_COST
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'CST_REFERENCED_RMA_COST'
	AND LOOKUP_CODE = CostProfileEO.REFERENCED_RMA_COST_CODE
	) RES_REFERENCED_RMA_COST
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'ORA_CST_UNREFERENCED_RMA_COST'
	AND LOOKUP_CODE = CostProfileEO.UNREFERENCED_RMA_COST_CODE 
	) RES_UNREFERENCED_RMA_RECEIPT_C
,DECODE(CostProfileEO.SUMMARIZE_LOTS_FLAG,'Y','Yes','No') RES_SUMMARIZE_COST_TRANSACTION
,DECODE(CostProfileEO.SUMMARIZE_SERIALS_FLAG,'Y','Yes','No') RES_SUMMARIZE_COST_TRANSACTI_0
,CostProfileEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,CostProfileEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,CostProfileEO.CREATED_BY RSC_CREATED_BY
,CostProfileEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CST_COST_PROFILES_VL CostProfileEO
,CST_COMPONENT_GROUPS_VL ComponentGroupPEO
,CST_VAL_STRUCTURES_VL ValStructurePEO
,FND_SETID_SETS_VL SetIdSetPEO
,CST_ANALYSIS_MAPPINGS_VL AnalysisMappingPEO
WHERE CostProfileEO.COMPONENT_GROUP_ID = ComponentGroupPEO.COMPONENT_GROUP_ID
AND CostProfileEo.VAL_STRUCTURE_ID     = ValStructurePEO.VAL_STRUCTURE_ID
AND CostProfileEO.SET_ID               = SetIdSetPEO.SET_ID
AND CostProfileEO.ANALYSIS_MAPPING_ID  = AnalysisMappingPEO.ANALYSIS_MAPPING_ID(+)
ORDER BY SetIdSetPEO.SET_NAME
,CostProfileEO.COST_PROFILE_CODE