/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Receivables%20Activities%20-%20Receivables%20Activities%20-%20DFF.sql $:
 * $Id: Manage Receivables Activities - Receivables Activities - DFF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=222##RES##AR_RECEIVABLES_TRX
-- DFF_ATTRIBUTES=ATTRIBUTE,GLOBAL_ATTRIBUTE
-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.
 
SELECT BUSINESSUNITPEO.BU_NAME RES_BUSINESS_UNIT
,ARRECEIVABLESTRXALL.NAME RES_NAME
,ARRECEIVABLESTRXALL.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ARRECEIVABLESTRXALL.ATTRIBUTE1 
,ARRECEIVABLESTRXALL.ATTRIBUTE2
,ARRECEIVABLESTRXALL.ATTRIBUTE3
,ARRECEIVABLESTRXALL.ATTRIBUTE4
,ARRECEIVABLESTRXALL.ATTRIBUTE5
,ARRECEIVABLESTRXALL.ATTRIBUTE6
,ARRECEIVABLESTRXALL.ATTRIBUTE7
,ARRECEIVABLESTRXALL.ATTRIBUTE8
,ARRECEIVABLESTRXALL.ATTRIBUTE9
,ARRECEIVABLESTRXALL.ATTRIBUTE10
,ARRECEIVABLESTRXALL.ATTRIBUTE11
,ARRECEIVABLESTRXALL.ATTRIBUTE12
,ARRECEIVABLESTRXALL.ATTRIBUTE13
,ARRECEIVABLESTRXALL.ATTRIBUTE14
,ARRECEIVABLESTRXALL.ATTRIBUTE15
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE1 
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE2
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE3
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE4
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE5
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE6
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE7
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE8
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE9
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE10 
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE11
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE12
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE13
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE14
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE15
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE16
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE17
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE18
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE19
,ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE20
,ARRECEIVABLESTRXALL.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,ARRECEIVABLESTRXALL.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,ARRECEIVABLESTRXALL.CREATED_BY  RSC_CREATED_BY
,ARRECEIVABLESTRXALL.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,ARRECEIVABLESTRXALL.ORG_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 

FROM (SELECT *
	FROM AR_RECEIVABLES_TRX_ALL 
	WHERE GL_ACCOUNT_SOURCE = 'ACTIVITY_GL_ACCOUNT'
	AND CODE_COMBINATION_ID IS NOT NULL
	
	UNION
	
	SELECT *
	FROM AR_RECEIVABLES_TRX_ALL 
	WHERE GL_ACCOUNT_SOURCE <> 'ACTIVITY_GL_ACCOUNT'
	) ARRECEIVABLESTRXALL
,FUN_ALL_BUSINESS_UNITS_V BUSINESSUNITPEO
WHERE ARRECEIVABLESTRXALL.ORG_ID = BUSINESSUNITPEO.BU_ID
AND (ARRECEIVABLESTRXALL.ATTRIBUTE_CATEGORY IS NOT NULL OR
ARRECEIVABLESTRXALL.ATTRIBUTE1 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE2 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE3 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE4 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE5 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE6 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE7 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE8 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE9 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE10 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE11 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE12 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE13 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE14 IS NOT NULL OR 
ARRECEIVABLESTRXALL.ATTRIBUTE15 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE1 IS NOT NULL OR  
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE2 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE3 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE4 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE5 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE6 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE7 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE8 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE9 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE10 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE11 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE12 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE13 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE14 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE15 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE16 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE17 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE18 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE19 IS NOT NULL OR 
ARRECEIVABLESTRXALL.GLOBAL_ATTRIBUTE20 IS NOT NULL)
ORDER BY BUSINESSUNITPEO.BU_NAME
,ARRECEIVABLESTRXALL.NAME