/* ****************************************************************************
 * $Revision: 55346 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-05-23 14:11:43 +0700 (Mon, 23 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Chart%20of%20Accounts%20Value%20Set%20Values%20-%20Manage%20Values.sql $:
 * $Id: Manage Chart of Accounts Value Set Values - Manage Values.sql 55346 2016-05-23 07:11:43Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
--RSC_PREREQUISITE_OBJECTS=HRC_DL_LAYOUTS_VL
--RSC_PREREQUISITE_OBJECTS=HRC_DL_LAYOUT_ATTRIBUTES_VL

SELECT hdcDLLAYOUTEO.LAYOUT_CODE RES_CODE
,NULL RES_AVAILABLE_ATTRIBUTES
,ATTRIBUTE_LABEL RES_SELECTED_ATTRIBUTES
,NULL RES_SELECT_KEY

,hrcDLLAYOUTATTEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,hrcDLLAYOUTATTEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,hrcDLLAYOUTATTEO.CREATED_BY RSC_CREATED_BY
,hrcDLLAYOUTATTEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,(SELECT LEGISLATION_CODE 
	FROM PER_LEGISLATIVE_DATA_GROUPS
	WHERE LEGISLATIVE_DATA_GROUP_ID = hdcDLLAYOUTEO.LEGISLATIVE_DATA_GROUP_ID
	) RSC_COUNTRY_ID

FROM HRC_DL_LAYOUTS_VL  hdcDLLAYOUTEO
,HRC_DL_LAYOUT_ATTRIBUTES_VL hrcDLLAYOUTATTEO
WHERE hdcDLLAYOUTEO.LAYOUT_ID = hrcDLLAYOUTATTEO.LAYOUT_ID
ORDER BY hdcDLLAYOUTEO.LAYOUT_CODE