/* ****************************************************************************
 * $Revision: 77700 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-01-26 10:26:35 +0700 (Wed, 26 Jan 2022) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Benefit%20Programs%20-%20Eligibility.sql $:
 * $Id: Manage Benefit Programs - Eligibility.sql 77700 2022-01-26 03:26:35Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
SELECT RES_PROGRAM_NAME
,RES_EFFECTIVE_START_DATE
,RES_PROGRAM_HIERARCHY
,RES_PROGRAM_HIERARCHY_DESCRIPT
,RES_PARTICIPATION_ELIGIBILITY_
,RES_PARTICIPATION_ELIGIBILIT_0
,RES_PARTICIPATION_START_DATE
,RES_PARTICIPATION_START_DATE_F
,RES_PARTICIPATION_PREVIOUS_END
,RES_PARTICIPATION_PREVIOUS_E_1
,RES_WAITING_PERIOD_VALUE
,RES_WAITING_PERIOD_UNIT_OF_MEA
,RES_WAITING_PERIOD_WAITING_PER
,RES_WAITING_PERIOD_PERIOD_STAR
,RES_WAITING_PERIOD_START_DATE_

,RSC_LAST_UPDATED_BY
,RSC_LAST_UPDATE_DATE
,RSC_CREATED_BY
,RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,RSC_COUNTRY_ID

FROM
(SELECT benPGMEO.NAME RES_PROGRAM_NAME
,(SELECT NAME FROM BEN_PGM_F WHERE PGM_ID = benPRTNELIGEO.PGM_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_PROGRAM_HIERARCHY
,TO_CHAR(benPGMEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,'Programs' RES_PROGRAM_HIERARCHY_DESCRIPT
,'1' SEQUENCE
,TO_CHAR(benPRTNELIGEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_PARTICIPATION_ELIGIBILITY_
,DECODE(TO_CHAR(benPRTNELIGEO.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benPRTNELIGEO.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_PARTICIPATION_ELIGIBILIT_0
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_PRTN_ELIG_STRT'
    AND LOOKUP_CODE = benPRTNELIGEO.PRTN_EFF_STRT_DT_CD
    ) RES_PARTICIPATION_START_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.PRTN_EFF_STRT_DT_RL
    ) RES_PARTICIPATION_START_DATE_F
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_PRTN_ELIG_END'
    AND LOOKUP_CODE = benPRTNELIGEO.PRTN_EFF_END_DT_CD
    ) RES_PARTICIPATION_PREVIOUS_END
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.PRTN_EFF_END_DT_RL
    ) RES_PARTICIPATION_PREVIOUS_E_1
,benPRTNELIGEO.WAIT_PERD_VAL RES_WAITING_PERIOD_VALUE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_WTG_PERD_UOM'
    AND LOOKUP_CODE = benPRTNELIGEO.WAIT_PERD_UOM
    ) RES_WAITING_PERIOD_UNIT_OF_MEA
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.WAIT_PERD_RL
    ) RES_WAITING_PERIOD_WAITING_PER
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_MX_WTG_DT_TO_USE'
    AND LOOKUP_CODE = benPRTNELIGEO.WAIT_PERD_DT_TO_USE_CD
    ) RES_WAITING_PERIOD_PERIOD_STAR
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.WAIT_PERD_DT_TO_USE_RL
    ) RES_WAITING_PERIOD_START_DATE_

,benPRTNELIGEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benPRTNELIGEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benPRTNELIGEO.CREATED_BY RSC_CREATED_BY
,benPRTNELIGEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID
	
	
FROM BEN_PGM_F benPGMEO
,BEN_PRTN_ELIG_F benPRTNELIGEO
WHERE benPGMEO.PGM_ID = benPRTNELIGEO.PGM_ID
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))

UNION

SELECT benPGMEO.NAME RES_PROGRAM_NAME
,benPLT.NAME RES_PROGRAM_HIERARCHY
,TO_CHAR(benPT.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,'Plan Type' RES_PROGRAM_HIERARCHY_DESCRIPT
,'2' SEQUENCE
,TO_CHAR(benPRTNELIGEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_PARTICIPATION_ELIGIBILITY_
,DECODE(TO_CHAR(benPRTNELIGEO.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benPRTNELIGEO.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_PARTICIPATION_ELIGIBILIT_0
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_PRTN_ELIG_STRT'
    AND LOOKUP_CODE = benPRTNELIGEO.PRTN_EFF_STRT_DT_CD
    ) RES_PARTICIPATION_START_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.PRTN_EFF_STRT_DT_RL
    ) RES_PARTICIPATION_START_DATE_F
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_PRTN_ELIG_END'
    AND LOOKUP_CODE = benPRTNELIGEO.PRTN_EFF_END_DT_CD
    ) RES_PARTICIPATION_PREVIOUS_END
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.PRTN_EFF_END_DT_RL
    ) RES_PARTICIPATION_PREVIOUS_E_1
,benPRTNELIGEO.WAIT_PERD_VAL RES_WAITING_PERIOD_VALUE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_WTG_PERD_UOM'
    AND LOOKUP_CODE = benPRTNELIGEO.WAIT_PERD_UOM
    ) RES_WAITING_PERIOD_UNIT_OF_MEA
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.WAIT_PERD_RL
    ) RES_WAITING_PERIOD_WAITING_PER
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_MX_WTG_DT_TO_USE'
    AND LOOKUP_CODE = benPRTNELIGEO.WAIT_PERD_DT_TO_USE_CD
    ) RES_WAITING_PERIOD_PERIOD_STAR
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.WAIT_PERD_DT_TO_USE_RL
    ) RES_WAITING_PERIOD_START_DATE_

,benPRTNELIGEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benPRTNELIGEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benPRTNELIGEO.CREATED_BY RSC_CREATED_BY
,benPRTNELIGEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID

FROM BEN_PGM_F benPGMEO
,BEN_PRTN_ELIG_F benPRTNELIGEO
,BEN_PTIP_F benPT
,BEN_PL_TYP_F benPLT
WHERE benPGMEO.PGM_ID = benPT.PGM_ID
AND benPT.PL_TYP_ID = benPLT.PL_TYP_ID
AND benPRTNELIGEO.PTIP_ID = benPT.PTIP_ID
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))

UNION

SELECT benPGMEO.NAME RES_PROGRAM_NAME
,benPL.NAME RES_PROGRAM_HIERARCHY
,TO_CHAR(benPLIP.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_EFFECTIVE_START_DATE
,'Plan' RES_PROGRAM_HIERARCHY_DESCRIPT
,'3' SEQUENCE
,TO_CHAR(benPRTNELIGEO.EFFECTIVE_START_DATE,'DD-Mon-YYYY') RES_PARTICIPATION_ELIGIBILITY_
,DECODE(TO_CHAR(benPRTNELIGEO.EFFECTIVE_END_DATE ,'DD-MM-YYYY'),'31-12-4712',NULL,TO_CHAR(benPRTNELIGEO.EFFECTIVE_END_DATE ,'DD-Mon-YYYY')) RES_PARTICIPATION_ELIGIBILIT_0
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_PRTN_ELIG_STRT'
    AND LOOKUP_CODE = benPRTNELIGEO.PRTN_EFF_STRT_DT_CD
    ) RES_PARTICIPATION_START_DATE
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.PRTN_EFF_STRT_DT_RL
    ) RES_PARTICIPATION_START_DATE_F
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_PRTN_ELIG_END'
    AND LOOKUP_CODE = benPRTNELIGEO.PRTN_EFF_END_DT_CD
    ) RES_PARTICIPATION_PREVIOUS_END
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.PRTN_EFF_END_DT_RL
    ) RES_PARTICIPATION_PREVIOUS_E_1
,benPRTNELIGEO.WAIT_PERD_VAL RES_WAITING_PERIOD_VALUE
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_WTG_PERD_UOM'
    AND LOOKUP_CODE = benPRTNELIGEO.WAIT_PERD_UOM
    ) RES_WAITING_PERIOD_UNIT_OF_MEA
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.WAIT_PERD_RL
    ) RES_WAITING_PERIOD_WAITING_PER
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'BEN_MX_WTG_DT_TO_USE'
    AND LOOKUP_CODE = benPRTNELIGEO.WAIT_PERD_DT_TO_USE_CD
    ) RES_WAITING_PERIOD_PERIOD_STAR
,(SELECT FORMULA_NAME
    FROM FF_FORMULAS_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND FORMULA_ID = benPRTNELIGEO.WAIT_PERD_DT_TO_USE_RL
    ) RES_WAITING_PERIOD_START_DATE_

,benPRTNELIGEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,benPRTNELIGEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,benPRTNELIGEO.CREATED_BY RSC_CREATED_BY
,benPRTNELIGEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,benPGMEO.LEGISLATION_CODE RSC_COUNTRY_ID
	
FROM BEN_PGM_F benPGMEO
,BEN_PRTN_ELIG_F benPRTNELIGEO
,BEN_PLIP_F benPLIP
,BEN_PL_F benPL
WHERE benPLIP.PL_ID = benPL.PL_ID
AND benPGMEO.PGM_ID = benPLIP.PGM_ID
AND benPRTNELIGEO.PLIP_ID = benPLIP.PLIP_ID
AND SYSDATE BETWEEN benPGMEO.EFFECTIVE_START_DATE AND NVL(benPGMEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPLIP.EFFECTIVE_START_DATE AND NVL(benPLIP.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
AND SYSDATE BETWEEN benPL.EFFECTIVE_START_DATE AND NVL(benPL.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY')) 
AND SYSDATE BETWEEN benPRTNELIGEO.EFFECTIVE_START_DATE AND NVL(benPRTNELIGEO.EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))

ORDER BY RES_PROGRAM_NAME,SEQUENCE)