/* ****************************************************************************
* $Revision: 72658 $:
* $Author: tanawat.wongjan $:
* $Date: 2019-10-01 15:00:45 +0700 (Tue, 01 Oct 2019) $:
* $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/
FINANCIALS/Manage%20SCM%20Common%20Value%20Sets%20-%20Manage%20SCM%20Common%20Value%20Sets.sql $:
* $Id: Manage SCM Common Value Sets - Manage SCM Common Value Sets.sql 55804 2016-06-09 04:17:45Z wuttipong.thongvises
$:
* ****************************************************************************
* Description:
* ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=CMP_TCS_ITEM_VL

SELECT compItemsE0.NAME RES_ITEM_NAME
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'CMP_TCS_ITEM_SOURCE_TYPE'
    AND LOOKUP_CODE = compItemsE0.SOURCE_CD
    ) RES_SOURCE_TYPE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'BB' THEN
		benBalancesE0.NAME
    END) RES_BENEFIT_BALANCE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'BB' THEN
		benBalancesE0.BNFTS_BAL_DESC
    END) RES_BENEFIT_BALANCE_DESCRIPTIO
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'BB' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'BEN_BNFTS_BAL_USG'
			AND LOOKUP_CODE = benBalancesE0.BNFTS_BAL_USG_CD)
    END) RES_BENEFIT_BALANCE_USAGE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'BB' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_TCS_DATA_TYPE'
			AND LOOKUP_CODE = compItemsE0.DATA_TYPE_CD)
    END) RES_BENEFIT_BALANCE_TYPE_OF_CO
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'BB' THEN
		(CASE
			WHEN compItemsE0.DATA_TYPE_CD = 'MNTRY' THEN
				(SELECT NAME
					FROM FND_CURRENCIES_TL
					WHERE LANGUAGE = USERENV('LANG')
					AND CURRENCY_CODE = compItemsE0.UOM)
			WHEN compItemsE0.DATA_TYPE_CD = 'NNMNTRY' THEN
				(SELECT MEANING
					FROM FND_LOOKUP_VALUES
					WHERE LANGUAGE = USERENV('LANG')
					AND LOOKUP_TYPE = 'CMP_NONMONETARY_UOM'
					AND LOOKUP_CODE = compItemsE0.NNMNTRY_UOM)
			END)
    END) RES_BENEFIT_BALANCE_UNIT
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'BB' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_ROUNDING'
			AND LOOKUP_CODE = compItemsE0.ROUNDING_CD)
    END) RES_BENEFIT_BALANCE_ROUNDING_R


,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EE' THEN
		(SELECT NAME
			FROM PER_LEGISLATIVE_DATA_GROUPS_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND LEGISLATIVE_DATA_GROUP_ID = compItemsE0.LEGISLATIVE_DATA_GROUP_ID)
    END) RES_ELEMENT_ENTRY_LEGISLATIVE_
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EE' THEN 
		(SELECT ELEMENT_NAME
			FROM PAY_ELEMENT_TYPES_VL
			WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
			AND ELEMENT_TYPE_ID = inputValuesE0.ELEMENT_TYPE_ID)
	END) RES_ELEMENT_ENTRY_PAYROLL_ELEM
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EE' THEN 
		inputValuesE0.NAME
	END) RES_ELEMENT_ENTRY_INPUT_VALUE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EE' THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'UNITS'
			AND LOOKUP_CODE = inputValuesE0.UOM)
	END) RES_ELEMENT_ENTRY_UNITS
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EE' THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_ROUNDING'
			AND LOOKUP_CODE = compItemsE0.ROUNDING_CD)
	END) RES_ELEMENT_ENTRY_ROUNDING_RUL
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EE' THEN 
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_TCS_DATA_TYPE'
			AND LOOKUP_CODE = compItemsE0.DATA_TYPE_CD)
	END) RES_ELEMENT_ENTRY_TYPE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EE' THEN 
		(CASE
			WHEN compItemsE0.DATA_TYPE_CD = 'MNTRY' THEN
				(SELECT NAME
					FROM FND_CURRENCIES_TL
					WHERE LANGUAGE = USERENV('LANG')
					AND CURRENCY_CODE = compItemsE0.UOM)
			WHEN compItemsE0.DATA_TYPE_CD = 'NNMNTRY' THEN
				(SELECT MEANING
					FROM FND_LOOKUP_VALUES
					WHERE LANGUAGE = USERENV('LANG')
					AND LOOKUP_TYPE = 'CMP_NONMONETARY_UOM'
					AND LOOKUP_CODE = compItemsE0.NNMNTRY_UOM)
			END) 
	END) RES_ELEMENT_ENTRY_CURRENCY


,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EXTERNAL_DATA' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_EXTERNAL_DATA_RECORD_TYPE'
			AND LOOKUP_CODE = compItemsE0.SOURCE_KEY_CHAR1)
	END) RES_EXTERNAL_DATA_RECORD_TYPE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EXTERNAL_DATA' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_EXTERNAL_DATA_COLUMN'
			AND LOOKUP_CODE = compItemsE0.SOURCE_KEY_CHAR2)
	END) RES_EXTERNAL_DATA_COLUMN
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EXTERNAL_DATA' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_TCS_DATA_TYPE'
			AND LOOKUP_CODE = compItemsE0.DATA_TYPE_CD)
	END) RES_EXTERNAL_DATA_TYPE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EXTERNAL_DATA' AND compItemsE0.DATA_TYPE_CD = 'MNTRY' THEN
		(SELECT NAME
			FROM FND_CURRENCIES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND CURRENCY_CODE = compItemsE0.UOM)
	END)  RES_EXTERNAL_DATA_CURRENCY
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EXTERNAL_DATA' AND compItemsE0.DATA_TYPE_CD = 'NNMNTRY' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_NONMONETARY_UOM'
			AND LOOKUP_CODE = compItemsE0.NNMNTRY_UOM)
	END)RES_EXTERNAL_DATA_UNITS
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'EXTERNAL_DATA' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_ROUNDING'
			AND LOOKUP_CODE = compItemsE0.ROUNDING_CD)
	END) RES_EXTERNAL_DATA_ROUNDING_RUL
	

,(CASE
	WHEN compItemsE0.SOURCE_CD = 'RULE' THEN
		formulasE0.FORMULA_NAME
	END) RES_FORMULA
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'RULE' THEN
		(SELECT FORMULA_TYPE_NAME 
			FROM FF_FORMULA_TYPES 
			WHERE FORMULA_TYPE_ID = formulasE0.FORMULA_TYPE_ID)
	END) RES_FORMULA_TYPE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'RULE' AND compItemsE0.DATA_TYPE_CD = 'NNMNTRY' THEN
		(SELECT NAME
			FROM FND_CURRENCIES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND CURRENCY_CODE = compItemsE0.UOM)
	END) RES_FORMULA_CURRENCY
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'RULE' AND compItemsE0.DATA_TYPE_CD = 'MNTRY' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_NONMONETARY_UOM'
			AND LOOKUP_CODE = compItemsE0.NNMNTRY_UOM)
	END) RES_FORMULA_UNITS
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'RULE' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_ROUNDING'
			AND LOOKUP_CODE = compItemsE0.ROUNDING_CD)
	END) RES_FORMULA_ROUNDING_RULE


,(CASE
	WHEN compItemsE0.SOURCE_CD = 'PAYBALANCE' THEN
		(SELECT BALANCE_NAME
			FROM PAY_BALANCE_TYPES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND BALANCE_TYPE_ID = dimBalsE0.BALANCE_TYPE_ID)
	END) RES_PAYROLL_BALANCE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'PAYBALANCE' THEN
		leDataGrpsE0.NAME
	END) RES_PAYROLL_BALANCE_LEGISLATIV
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'PAYBALANCE' THEN
		(SELECT DIMENSION_NAME
			FROM PAY_DIMENSION_USAGES_VL
			WHERE BALANCE_DIMENSION_ID = dimBalsE0.BALANCE_DIMENSION_ID
			AND LEGISLATION_CODE = leDataGrpsE0.LEGISLATION_CODE)
	END) RES_PAYROLL_BALANCE_DIMENSION
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'PAYBALANCE' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_TCS_DATA_TYPE'
			AND LOOKUP_CODE = compItemsE0.DATA_TYPE_CD)
	END) RES_PAYROLL_BALANCE_TYPE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'PAYBALANCE' AND compItemsE0.DATA_TYPE_CD = 'MNTRY' THEN
		(SELECT NAME
			FROM FND_CURRENCIES_TL
			WHERE LANGUAGE = USERENV('LANG')
			AND CURRENCY_CODE = compItemsE0.UOM)
	END) RES_PAYROLL_BALANCE_CURRENCY
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'PAYBALANCE' AND compItemsE0.DATA_TYPE_CD = 'NNMNTRY' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_NONMONETARY_UOM'
			AND LOOKUP_CODE = compItemsE0.NNMNTRY_UOM)
	END) RES_PAYROLL_BALANCE_UNITS
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'PAYBALANCE' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'CMP_ROUNDING'
			AND LOOKUP_CODE = compItemsE0.ROUNDING_CD)
	END) RES_PAYROLL_BALANCE_ROUNDING_R

,(CASE
	WHEN compItemsE0.SOURCE_CD = 'SALARY' THEN
		(SELECT MEANING
			FROM FND_LOOKUP_VALUES
			WHERE LANGUAGE = USERENV('LANG')
			AND LOOKUP_TYPE = 'ORA_CMP_TCS_SALARY_SELECTION'
			AND LOOKUP_CODE = compItemsE0.SELECTION_CRITERIA)
	END) RES_SALARY_SELECTION_CRITERIA
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'SALARY' AND compItemsE0.SELECTION_CRITERIA = 'SALARY_BASIS' THEN
        salBasisE0.SALARY_BASIS_NAME
	END) RES_SALARY_BASIS
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'SALARY' THEN
		(SELECT MEANING 
			FROM FND_LOOKUP_VALUES  
			WHERE LANGUAGE  = USERENV('LANG') 
			AND LOOKUP_TYPE = 'ORA_CMP_SAL_BASIS_DET_METHOD' 
			AND LOOKUP_CODE = salBasisE0.SALARY_BASIS_TYPE) 
	END) RES_SALARY_BASIS_TYPE
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'SALARY' THEN
        (SELECT NAME 
			FROM PER_LEGISLATIVE_DATA_GROUPS_TL 
			WHERE LANGUAGE = USERENV('LANG')
			AND LEGISLATIVE_DATA_GROUP_ID = salBasisE0.LEGISLATIVE_DATA_GROUP_ID)
	END) RES_SALARY_BASIS_LEGISLATIVE_D
,(CASE
	WHEN compItemsE0.SOURCE_CD = 'SALARY' THEN
		(SELECT MEANING 
		FROM FND_LOOKUP_VALUES  
		WHERE LANGUAGE  = USERENV('LANG')
		AND LOOKUP_TYPE = 'CMP_SALARY_BASIS'
		AND LOOKUP_CODE = salBasisE0.SALARY_BASIS_CODE )
	END) RES_SALARY_BASIS_FREQUENCY

,DECODE(compItemsE0.ESTIMATED_FLAG,'Y','Yes','No') RES_ESTIMATED_AMOUNT

,compItemsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,compItemsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,compItemsE0.CREATED_BY RSC_CREATED_BY
,compItemsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CMP_TCS_ITEM_VL compItemsE0
,BEN_BNFTS_BAL_F benBalancesE0
,PAY_INPUT_VALUES_VL inputValuesE0
,PAY_DEFINED_BALANCES dimBalsE0
,CMP_SALARY_BASES_VL salBasisE0
,FF_FORMULAS_VL formulasE0
,PER_LEGISLATIVE_DATA_GROUPS_VL leDataGrpsE0
WHERE compItemsE0.SOURCE_KEY = benBalancesE0.BNFTS_BAL_ID(+)
AND compItemsE0.SOURCE_KEY = inputValuesE0.INPUT_VALUE_ID(+)
AND compItemsE0.SOURCE_KEY = dimBalsE0.DEFINED_BALANCE_ID(+)
AND compItemsE0.SOURCE_KEY = salBasisE0.SALARY_BASIS_ID(+)
AND compItemsE0.SOURCE_KEY = formulasE0.FORMULA_ID(+)

AND compItemsE0.LEGISLATIVE_DATA_GROUP_ID = leDataGrpsE0.LEGISLATIVE_DATA_GROUP_ID(+)
ORDER BY compItemsE0.NAME