/* ****************************************************************************
 * $Revision$:
 * $Author$:
 * $Date$:
 * $HeadURL$:
 * $Id$:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT (SELECT ORGANIZATION_CODE 
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = CycleCountHE0.ORGANIZATION_ID
	) RES_ORGANIZATION
,CycleCountHE0.CYCLE_COUNT_HEADER_NAME RES_COUNT_NAME
,CategoriesE0.CATEGORY_NAME RES_CATEGORY_NAME
,CategoriesE0.DESCRIPTION RES_DESCRIPTION
,'Yes' RES_INCLUDE_IN_COUNT
,' ' RES_SYNCHRONIZATION_MODE
,' ' RES_SYNCHRONIZE_ITEM_CATEGORY_
,' ' RES_DELETE_ADDITIONAL_ITEMS
,InvCYCLECLASSE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,InvCYCLECLASSE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,InvCYCLECLASSE0.CREATED_BY  RSC_CREATED_BY
,InvCYCLECLASSE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,InvCYCLECLASSE0.ORGANIZATION_ID RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
   
FROM INV_CYCLE_COUNT_HEADERS CycleCountHE0
,INV_CYCLE_COUNT_CLASSES InvCYCLECLASSE0
,EGP_CATEGORIES_VL CategoriesE0
WHERE CycleCountHE0.CYCLE_COUNT_HEADER_ID = InvCYCLECLASSE0.CYCLE_COUNT_HEADER_ID
AND CycleCountHE0.ORGANIZATION_ID = InvCYCLECLASSE0.ORGANIZATION_ID
AND InvCYCLECLASSE0.ABC_CLASS_ID = CategoriesE0.CATEGORY_ID
ORDER BY 1,2,3