/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Capitalized%20Interest%20Rate%20Schedules%20-%20Schedule%20Version.sql $:
 * $Id: Manage Capitalized Interest Rate Schedules - Schedule Version.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

SELECT pjnRATESCHEO.RATE_SCH_NAME RES_NAME
,pjcCINTVEREO.RATE_SCH_REVISION RES_SCHEDULE_VERSION_NAME
,TO_CHAR(pjcCINTVEREO.START_DATE_ACTIVE,'DD-Mon-YYYY') RES_FROM_DATE
,TO_CHAR(pjcCINTVEREO.END_DATE_ACTIVE,'DD-Mon-YYYY') RES_TO_DATE
,FndTREEEO.TREE_NAME RES_ORGANIZATION_HIERARCHY
,FndTREEVerEO.TREE_VERSION_NAME	RES_HIERARCHY_VERSION
,HROrgUNITEO.NAME RES_HIERARCHY_START_ORGANIZATI
,decode(pjcCINTVEREO.READY_TO_COMPILE_FLAG,'N','Yes','No') RES_HOLD_FROM_BUILD
,(SELECT MEANING 
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'PJC_CINT_BUILD_STATUS'
	AND LOOKUP_CODE = pjcCINTVEREO.COMPILED_FLAG
	) RES_STATUS
,pjcCINTVEREO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,pjcCINTVEREO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,pjcCINTVEREO.CREATED_BY RSC_CREATED_BY
,pjcCINTVEREO.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJC_CINT_RATE_SCH_VL pjnRATESCHEO
,FND_TREE_VL FndTREEEO
,FND_TREE_VERSION_VL FndTREEVerEO
,HR_ORGANIZATION_UNITS HROrgUNITEO
,PJC_CINT_RS_REVISIONS pjcCINTVEREO
WHERE pjnRATESCHEO.CINT_RATE_SCH_ID = pjcCINTVEREO.CINT_RATE_SCH_ID
AND pjcCINTVEREO.ORG_TREE_STRUCTURE_CODE = FndTREEEO.TREE_STRUCTURE_CODE
AND pjcCINTVEREO.ORG_TREE_CODE = FndTREEEO.TREE_CODE
AND pjcCINTVEREO.ORG_TREE_STRUCTURE_CODE = FndTREEVerEO.TREE_STRUCTURE_CODE
AND pjcCINTVEREO.ORG_TREE_CODE = FndTREEVerEO.TREE_CODE
AND pjcCINTVEREO.ORG_TREE_VERSION_ID = FndTREEVerEO.TREE_VERSION_ID
AND pjcCINTVEREO.START_ORGANIZATION_ID = HROrgUNITEO.ORGANIZATION_ID
ORDER BY pjnRATESCHEO.RATE_SCH_NAME
,pjcCINTVEREO.START_DATE_ACTIVE