/* ****************************************************************************
 * $Revision: 53540 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-03-15 15:13:43 +0700 (Tue, 15 Mar 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Currency%20Rates%20Manager%20-%20Rate%20Types.sql $:
 * $Id: Currency Rates Manager - Rate Types.sql 53540 2016-03-15 08:13:43Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=707##RES##CST_ANALYSIS_GROUPS_B
-- DFF_ATTRIBUTES=ATTRIBUTE_CHAR,ATTRIBUTE_NUMBER,ATTRIBUTE_DATE,ATTRIBUTE_TIMESTAMP

-- IMPORTANT: 
-- 	- the alias names for the Foreign keys must be the same as in the inventory.
--  - the alias name for context code must be RES_CONTEXT_CODE
--  - NO ALIASES for atributes fields.
 
SELECT AnalysisGroupsE0.ANALYSIS_GROUP_CODE RES_ANALYSIS_GROUP
,AnalysisGroupsE0.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,AnalysisGroupsE0.ATTRIBUTE_CHAR1
,AnalysisGroupsE0.ATTRIBUTE_CHAR2
,AnalysisGroupsE0.ATTRIBUTE_CHAR3
,AnalysisGroupsE0.ATTRIBUTE_CHAR4
,AnalysisGroupsE0.ATTRIBUTE_CHAR5
,AnalysisGroupsE0.ATTRIBUTE_CHAR6
,AnalysisGroupsE0.ATTRIBUTE_CHAR7
,AnalysisGroupsE0.ATTRIBUTE_CHAR8
,AnalysisGroupsE0.ATTRIBUTE_CHAR9
,AnalysisGroupsE0.ATTRIBUTE_CHAR10
,AnalysisGroupsE0.ATTRIBUTE_CHAR11
,AnalysisGroupsE0.ATTRIBUTE_CHAR12
,AnalysisGroupsE0.ATTRIBUTE_CHAR13
,AnalysisGroupsE0.ATTRIBUTE_CHAR14
,AnalysisGroupsE0.ATTRIBUTE_CHAR15
,AnalysisGroupsE0.ATTRIBUTE_CHAR16
,AnalysisGroupsE0.ATTRIBUTE_CHAR17
,AnalysisGroupsE0.ATTRIBUTE_CHAR18
,AnalysisGroupsE0.ATTRIBUTE_CHAR19
,AnalysisGroupsE0.ATTRIBUTE_CHAR20
,AnalysisGroupsE0.ATTRIBUTE_NUMBER1
,AnalysisGroupsE0.ATTRIBUTE_NUMBER2
,AnalysisGroupsE0.ATTRIBUTE_NUMBER3
,AnalysisGroupsE0.ATTRIBUTE_NUMBER4
,AnalysisGroupsE0.ATTRIBUTE_NUMBER5
,AnalysisGroupsE0.ATTRIBUTE_NUMBER6
,AnalysisGroupsE0.ATTRIBUTE_NUMBER7
,AnalysisGroupsE0.ATTRIBUTE_NUMBER8
,AnalysisGroupsE0.ATTRIBUTE_NUMBER9
,AnalysisGroupsE0.ATTRIBUTE_NUMBER10
,TO_CHAR(AnalysisGroupsE0.ATTRIBUTE_DATE1,'DD-Mon-YYYY') ATTRIBUTE_DATE1
,TO_CHAR(AnalysisGroupsE0.ATTRIBUTE_DATE2,'DD-Mon-YYYY') ATTRIBUTE_DATE2
,TO_CHAR(AnalysisGroupsE0.ATTRIBUTE_DATE3,'DD-Mon-YYYY') ATTRIBUTE_DATE3
,TO_CHAR(AnalysisGroupsE0.ATTRIBUTE_DATE4,'DD-Mon-YYYY') ATTRIBUTE_DATE4
,TO_CHAR(AnalysisGroupsE0.ATTRIBUTE_DATE5,'DD-Mon-YYYY') ATTRIBUTE_DATE5
,AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP1
,AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP2
,AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP3
,AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP4
,AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP5
,AnalysisGroupsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,AnalysisGroupsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,AnalysisGroupsE0.CREATED_BY RSC_CREATED_BY
,AnalysisGroupsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM CST_ANALYSIS_GROUPS_VL AnalysisGroupsE0
WHERE (AnalysisGroupsE0.ATTRIBUTE_CATEGORY IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR1 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR2 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR3 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR4 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR5 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR6 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR7 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR8 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR9 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR10 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR11 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR12 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR13 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR14 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR15 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR16 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR17 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR18 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR19 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_CHAR20 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER1 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER2 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER3 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER4 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER5 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER6 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER7 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER8 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER9 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_NUMBER10 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_DATE1 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_DATE2 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_DATE3 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_DATE4 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_DATE5 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP1 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP2 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP3 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP4 IS NOT NULL OR
AnalysisGroupsE0.ATTRIBUTE_TIMESTAMP5 IS NOT NULL)
ORDER BY AnalysisGroupsE0.ANALYSIS_GROUP_CODE