/* ****************************************************************************
* $Revision: 78557 $:
* $Author: tanawat.wongjan $:
* $Date: 2022-05-24 10:32:18 +0700 (Tue, 24 May 2022) $:
* $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Project%20Templates%20-%20Template%20Information.sql $:
* $Id: Manage Project Templates - Template Information.sql 78557 2022-05-24 03:32:18Z tanawat.wongjan $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT projTemplatesE0.NAME RES_TEMPLATE_NAME
,projTemplatesE0.SEGMENT1 RES_TEMPLATE_NUMBER
,buE0.BU_NAME RES_BUSINESS_UNIT
,(SELECT NAME
    FROM HR_ORGANIZATION_UNITS_F_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND ORGANIZATION_ID = projTemplatesE0.PROJECT_UNIT_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    ) RES_PROJECT_UNIT
,(SELECT PROJECT_TYPE
    FROM PJF_PROJECT_TYPES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND PROJECT_TYPE_ID = projTemplatesE0.PROJECT_TYPE_ID
    ) RES_PROJECT_TYPE
,(SELECT NAME
    FROM HR_ORGANIZATION_UNITS_F_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND ORGANIZATION_ID = projTemplatesE0.CARRYING_OUT_ORGANIZATION_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    ) RES_ORGANIZATION
,(SELECT NAME 
    FROM XLE_ENTITY_PROFILES
    WHERE LEGAL_ENTITY_ID = projTemplatesE0.LEGAL_ENTITY_ID
    ) RES_LEGAL_ENTITY
,(SELECT PROJECT_STATUS_NAME
    FROM PJF_PROJECT_STATUSES_TL
    WHERE LANGUAGE = USERENV('LANG')
    AND PROJECT_STATUS_CODE = projTemplatesE0.PROJECT_STATUS_CODE
    ) RES_INITIAL_PROJECT_STATUS
,projTemplatesE0.DESCRIPTION RES_DESCRIPTION
,TO_CHAR(projTemplatesE0.TEMPLATE_START_DATE_ACTIVE,'DD-Mon-YYYY') RES_FROM_DATE
,TO_CHAR(projTemplatesE0.TEMPLATE_END_DATE_ACTIVE,'DD-Mon-YYYY') RES_TO_DATE
,(CASE
    WHEN projTemplatesE0.GROUP_SPACE_TEMPLATE_NAME IS NOT NULL THEN
        'Yes'
	ELSE 'No'
    END) RES_ENABLE_PROJECT_SPACE_FOR_D
,projTemplatesE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,projTemplatesE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,projTemplatesE0.CREATED_BY  RSC_CREATED_BY
,projTemplatesE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,projTemplatesE0.ORG_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PJF_PROJECTS_ALL_VL projTemplatesE0
,FUN_ALL_BUSINESS_UNITS_V buE0
WHERE projTemplatesE0.TEMPLATE_FLAG = 'Y'
AND projTemplatesE0.ORG_ID = buE0.BU_ID
ORDER BY projTemplatesE0.NAME