 /* ****************************************************************************
 * $Revision: 48884 $:
 * $Author: dhara.pithadiya $:
 * $Date: 2015-08-18 14:24:02 +0700 (Tue, 18 Aug 2015) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20Transaction%20Types%20-%20Manage%20Transaction%20Types.sql $:
 * $Id: Manage Transaction Types - Manage Transaction Types.sql 48884 2015-08-18 07:24:02Z dhara.pithadiya $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT goldPlansE0.GOAL_PLAN_NAME RES_GOAL_PLAN
,(SELECT LIST_NAME
	FROM PER_PERSON_NAMES_F
	WHERE NAME_TYPE = 'GLOBAL'
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND PERSON_ID = planWorkersE0.MANAGER_ID
	) RES_WORKER_NAME
,DECODE(planWorkersE0.CASCADING_LEVEL
	,0,'Self'
	,1,'Direct reports'
	,999999,'All reports'
	,2,'Self and direct reports'
	,1000000,'Self and all reports'
	) RES_ASSIGNEES
,(CASE 
	WHEN planWorkersE0.CASCADING_LEVEL IN (0,1,999999) THEN
		'1'
	WHEN planWorkersE0.CASCADING_LEVEL IN (2,1000000) THEN
		'2'
	END) RES_ASSIGNEE_DETAILS
,(SELECT personsE0.LIST_NAME
	FROM PER_ASSIGNMENT_SUPERVISORS_F supersE0
	,PER_PERSON_NAMES_F personsE0
	WHERE PRIMARY_FLAG = 'Y'
	AND supersE0.MANAGER_ID = personsE0.PERSON_ID
	AND SYSDATE BETWEEN supersE0.EFFECTIVE_START_DATE AND supersE0.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN personsE0.EFFECTIVE_START_DATE AND personsE0.EFFECTIVE_END_DATE
	AND personsE0.NAME_TYPE = 'GLOBAL'
	AND supersE0.PERSON_ID = planWorkersE0.MANAGER_ID
	AND supersE0.ASSIGNMENT_ID = planWorkersE0.MANAGER_ASSIGNMENT_ID
	) RES_MANAGER_NAME
,workersE0.PERSON_NUMBER RES_PERSON_NUMBER
,NVL((SELECT NAME
	FROM PER_JOBS_F_TL
	WHERE LANGUAGE = USERENV('LANG')
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND JOB_ID = assignmentsE0.JOB_ID)
	,'-'||assignmentsE0.ASSIGNMENT_NUMBER) RES_JOB
,(SELECT NAME
    FROM HR_ORGANIZATION_UNITS
    WHERE SYSDATE BETWEEN DATE_FROM AND DATE_TO
    AND ORGANIZATION_ID = assignmentsE0.ORGANIZATION_ID
	 ) RES_DEPARTMENT
,(SELECT EMAIL_ADDRESS 
	FROM PER_EMAIL_ADDRESSES 
	WHERE EMAIL_ADDRESS_ID = workersE0.PRIMARY_EMAIL_ID 
	AND PERSON_ID = workersE0.PERSON_ID
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('31-12-4712','DD-MM-YYYY')) 
	AND MASTERED_IN_LDAP_FLAG = 'Y'
	) RES_EMAIL
,(SELECT NAME 
	FROM HR_ALL_POSITIONS_F_VL 
	WHERE POSITION_ID = assignmentsE0.POSITION_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))
	) RES_POSITION	
,(SELECT BU_NAME 
	FROM FUN_ALL_BUSINESS_UNITS_V 
	WHERE BU_ID = assignmentsE0.BUSINESS_UNIT_ID
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('31-12-4712','DD-MM-YYYY'))
	) RES_BUSINESS_UNIT
,(SELECT CITY 
	FROM HZ_LOCATIONS 
	WHERE LOCATION_ID = assignmentsE0.LOCATION_ID
	) RES_LOCATION
,assignmentsE0.ASSIGNMENT_NAME RES_ASSIGNMENT_NAME
,(SELECT MEANING 
	FROM FND_LOOKUP_VALUES 
	WHERE LANGUAGE = USERENV('LANG')
	AND LOOKUP_CODE = assignmentsE0.ASSIGNMENT_STATUS_TYPE
	AND LOOKUP_TYPE = 'HRG_GOAL_PLAN_SET_ASSGN_STATUS' 
	AND SYSDATE BETWEEN START_DATE_ACTIVE AND NVL(END_DATE_ACTIVE,TO_DATE('31-12-4712','DD-MM-YYYY'))
	)RES_ASSIGNMENT_STATUS
,assignmentsE0.ASSIGNMENT_NUMBER RES_ASSIGNMENT_NUMBER 
,planWorkersE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,planWorkersE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,planWorkersE0.CREATED_BY  RSC_CREATED_BY
,planWorkersE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,goldPlansE0.BUSINESS_GROUP_ID RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
FROM HRG_GOAL_PLANS_VL goldPlansE0
,HRG_MASS_REQ_HIERARCHIES planWorkersE0
,PER_ALL_ASSIGNMENTS_M assignmentsE0
,PER_ALL_PEOPLE_F workersE0
WHERE goldPlansE0.MASS_REQUEST_ID = planWorkersE0.MASS_REQUEST_ID
AND goldPlansE0.GOAL_PLAN_TYPE_CODE = 'ORA_HRG_WORKER'
AND planWorkersE0.MANAGER_ASSIGNMENT_ID = assignmentsE0.ASSIGNMENT_ID
AND SYSDATE BETWEEN assignmentsE0.EFFECTIVE_START_DATE AND assignmentsE0.EFFECTIVE_END_DATE
AND assignmentsE0.PERSON_ID = workersE0.PERSON_ID
AND SYSDATE BETWEEN workersE0.EFFECTIVE_START_DATE AND workersE0.EFFECTIVE_END_DATE
ORDER BY goldPlansE0.GOAL_PLAN_NAME