/* ****************************************************************************
 * $Revision: 74208 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2020-06-03 19:08:12 +0700 (Wed, 03 Jun 2020) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13.20/branches/core/v2.2.3.0.B/reverse_sql/FINANCIALS/Manage%20AutoPost%20Criteria%20Sets%20-%20AutoPost%20Criteria.sql $:
 * $Id: Manage AutoPost Criteria Sets - AutoPost Criteria.sql 74208 2020-06-03 12:08:12Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */


SELECT gmsAWARDTEMPE0.TEMPLATE_NAME RES_TEMPLATE_NAME
,gmsAWARDTEMPE0.TEMPLATE_NUMBER RES_TEMPLATE_NUMBER
,DECODE(gmsAWARDPERSONNELE0.INTERNAL_FLAG,'Y','Yes','No') RES_INTERNAL
,(SELECT DISPLAY_NAME
	FROM PER_PERSON_NAMES_F
	WHERE NAME_TYPE = 'GLOBAL'
	AND PERSON_ID = gmsAWARDPERSONNELE0.PERSONNEL_ID
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	) RES_PERSON_NAME
,(SELECT PERSON_NUMBER FROM PER_ALL_PEOPLE_F WHERE PERSON_ID = gmsAWARDPERSONNELE0.PERSONNEL_ID 
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND NVL(EFFECTIVE_END_DATE,TO_DATE('31-12-4712','DD-MM-YYYY'))) RES_PERSON_NUMBER
,(SELECT PROJECT_ROLE_NAME FROM PJF_PROJ_ROLE_TYPES_VL WHERE PROJECT_ROLE_ID = gmsAWARDPERSONNELE0.ROLE_ID) RES_ROLE
,TO_CHAR(gmsAWARDPERSONNELE0.START_DATE,'DD-Mon-YYYY') RES_START_DATE
,TO_CHAR(gmsAWARDPERSONNELE0.END_DATE,'DD-Mon-YYYY') RES_END_DATE
,(SELECT EMAIL_ADDRESS FROM PER_EMAIL_ADDRESSES WHERE PERSON_ID = gmsAWARDPERSONNELE0.PERSONNEL_ID)RES_E_MAIL

,gmsAWARDPERSONNELE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,gmsAWARDPERSONNELE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,gmsAWARDPERSONNELE0.CREATED_BY RSC_CREATED_BY
,gmsAWARDPERSONNELE0.CREATION_DATE RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM GMS_AWARD_TEMPLATES_VL gmsAWARDTEMPE0
,GMS_AWARD_HEADERS_B gmsAWARDHEABE0
,GMS_AWARD_PERSONNEL gmsAWARDPERSONNELE0
WHERE gmsAWARDTEMPE0.AWARD_HEADER_ID = gmsAWARDHEABE0.ID
AND gmsAWARDHEABE0.ID = gmsAWARDPERSONNELE0.AWARD_ID
ORDER BY gmsAWARDTEMPE0.TEMPLATE_NAME