/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Default%20Item%20Class%20-%20Item%20Organization%20(Purchasing).sql $:
 * $Id: Manage Default Item Class - Item Organization (Purchasing).sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT ItemClassPEO.ITEM_CLASS_CODE RES_INTERNAL_NAME
,ItemVersionEO.TEMPLATE_NAME RES_NAME
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemVersionEO.ORGANIZATION_ID
	) RES_ORGANIZATION
,DECODE(ItemVersionEO.PURCHASING_ITEM_FLAG,'Y','Yes','N','No') RES_PURCHASED
,DECODE(ItemVersionEO.MUST_USE_APPROVED_VENDOR_FLAG,'Y','Yes','N','No') RES_USE_APPROVED_SUPPLIER
,DECODE(ItemVersionEO.NEGOTIATION_REQUIRED_FLAG,'Y','Yes','N','No') RES_NEGOTIATION_REQUIRED
,ItemVersionEO.PURCHASING_TAX_CODE RES_INPUT_TAX_CLASSIFICATION_C
,ItemVersionEO.UNIT_OF_ISSUE RES_UNIT_OF_ISSUE
,ItemVersionEO.INVOICE_CLOSE_TOLERANCE RES_INVOICE_CLOSE_TOLERANCE_PE
,(SELECT HAZARD_CLASS
	FROM PO_HAZARD_CLASSES_VL
	WHERE HAZARD_CLASS_ID = ItemVersionEO.HAZARD_CLASS_ID
	) RES_HAZARD_CLASS
,(CASE
	WHEN ItemVersionEO.ASSET_CATEGORY_ID IS NOT NULL THEN
		(SELECT SEGMENT1||'.'||SEGMENT2
		FROM FA_CATEGORIES_B
		WHERE CATEGORY_ID = ItemVersionEO.ASSET_CATEGORY_ID)
	END) RES_ASSET_CATEGORY
,DECODE(ItemVersionEO.PURCHASING_ENABLED_FLAG,'Y','Yes','N','No') RES_PURCHASABLE
,DECODE(ItemVersionEO.ALLOW_ITEM_DESC_UPDATE_FLAG,'Y','Yes','N','No') RES_ALLOW_PURCHASING_DOCUMENT_
,DECODE(ItemVersionEO.TAXABLE_FLAG,'Y','Yes','N','No') RES_TAXABLE
,(SELECT DISTINCT LIST_NAME
	FROM PO_AGENT_ACCESSES BuyerPEO
	,PER_PERSON_NAMES_F_V PersonNameDPEO
	WHERE BuyerPEO.AGENT_ID = PersonNameDPEO.PERSON_ID
	AND BuyerPEO.ASSIGNMENT_ID = ItemVersionEO.BUYER_ID
	) RES_DEFAULT_BUYER
,ItemVersionEO.RECEIVE_CLOSE_TOLERANCE RES_RECEIPT_CLOSE_TOLERANCE_PE
,(SELECT UN_NUMBER
	FROM PO_UN_NUMBERS_VL
	WHERE UN_NUMBER_ID = ItemVersionEO.UN_NUMBER_ID
	) RES_UN_NUMBER
,ItemVersionEO.LIST_PRICE_PER_UNIT RES_PURCHASE_PRICE
,ItemVersionEO.PRICE_TOLERANCE_PERCENT RES_PRICE_TOLERANCE_PERCENTAGE
,ItemVersionEO.MARKET_PRICE RES_MARKET_PRICE
,ItemVersionEO.ROUNDING_FACTOR RES_ROUNDING_FACTOR
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_COMMON_YES_NO_NUM'
	AND LOOKUP_CODE = ItemVersionEO.OUTSOURCED_ASSEMBLY
	) RES_OUTSIDE_PROCESSING_SERVICE
/*,DECODE(ItemVersionEO.OUTSIDE_OPERATION_FLAG,'Y','Yes','N','No') RES_OUTSIDE_PROCESSING
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_UNITTYPEVS_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.OUTSIDE_OPERATION_UOM_TYPE
	) RES_UNIT_TYPE*/
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_MAT_APPR_LEV'
	AND LOOKUP_CODE = ItemVersionEO.MATCH_APPROVAL_LEVEL
	) RES_MATCH_APPROVAL_LEVEL
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_POINV_MAT_OPTION'
	AND LOOKUP_CODE = ItemVersionEO.INVOICE_MATCH_OPTION
	) RES_INVOICE_MATCH_OPTION
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_RECEIPTROUTVS_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.RECEIVING_ROUTING_ID
	) RES_RECEIPT_ROUTING
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_RECEIPTACTIONVS_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.ENFORCE_SHIP_TO_LOCATION_CODE
	) RES_ENFORCE_SHIP_TO_LOCATION
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_RECEIPTACTIONVS_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.RECEIPT_DAYS_EXCEPTION_CODE
	) RES_RECEIPT_DATE_ACTION
,ItemVersionEO.DAYS_EARLY_RECEIPT_ALLOWED RES_DAYS_EARLY
,ItemVersionEO.DAYS_LATE_RECEIPT_ALLOWED RES_DAYS_LATE
,DECODE(ItemVersionEO.ALLOW_SUBSTITUTE_RECEIPTS_FLAG,'Y','Yes','N','No') RES_ALLOW_SUBSTITUTE_RECEIPTS
,DECODE(ItemVersionEO.ALLOW_UNORDERED_RECEIPTS_FLAG,'Y','Yes','N','No') RES_ALLOW_UNORDERED_RECEIPTS
,DECODE(ItemVersionEO.ALLOW_EXPRESS_DELIVERY_FLAG,'Y','Yes','N','No') RES_ALLOW_EXPRESS_TRANSACTIONS
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_RECEIPTACTIONVS_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.QTY_RCV_EXCEPTION_CODE
	) RES_ACTION
,ItemVersionEO.QTY_RCV_TOLERANCE RES_TOLERANCE_PERCENTAGE
,ItemVersionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemVersionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemVersionEO.CREATED_BY RSC_CREATED_BY
,ItemVersionEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,ItemVersionEO.ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,EGP_SYSTEM_ITEMS_V ItemVersionEO
WHERE ItemClassPEO.PARENT_ITEM_CLASS_ID NOT IN (SELECT ITEM_CLASS_ID FROM EGP_ITEM_CLASSES_VL)
AND ItemVersionEO.TEMPLATE_NAME IS NOT NULL
AND ItemClassPEO.ITEM_CLASS_ID = ItemVersionEO.ITEM_CATALOG_GROUP_ID
AND(ItemVersionEO.PURCHASING_ITEM_FLAG IS NOT NULL
OR ItemVersionEO.MUST_USE_APPROVED_VENDOR_FLAG IS NOT NULL
OR ItemVersionEO.NEGOTIATION_REQUIRED_FLAG IS NOT NULL
OR ItemVersionEO.PURCHASING_TAX_CODE IS NOT NULL
OR ItemVersionEO.UNIT_OF_ISSUE IS NOT NULL
OR ItemVersionEO.INVOICE_CLOSE_TOLERANCE IS NOT NULL
OR ItemVersionEO.HAZARD_CLASS_ID IS NOT NULL
OR ItemVersionEO.ASSET_CATEGORY_ID IS NOT NULL
OR ItemVersionEO.PURCHASING_ENABLED_FLAG IS NOT NULL
OR ItemVersionEO.ALLOW_ITEM_DESC_UPDATE_FLAG IS NOT NULL
OR ItemVersionEO.TAXABLE_FLAG IS NOT NULL
OR ItemVersionEO.BUYER_ID IS NOT NULL
OR ItemVersionEO.RECEIVE_CLOSE_TOLERANCE IS NOT NULL
OR ItemVersionEO.UN_NUMBER_ID IS NOT NULL
OR ItemVersionEO.LIST_PRICE_PER_UNIT IS NOT NULL
OR ItemVersionEO.PRICE_TOLERANCE_PERCENT IS NOT NULL
OR ItemVersionEO.MARKET_PRICE IS NOT NULL
OR ItemVersionEO.ROUNDING_FACTOR IS NOT NULL
OR ItemVersionEO.OUTSOURCED_ASSEMBLY IS NOT NULL
/*OR ItemVersionEO.OUTSIDE_OPERATION_FLAG IS NOT NULL
OR ItemVersionEO.OUTSIDE_OPERATION_UOM_TYPE IS NOT NULL*/
OR ItemVersionEO.MATCH_APPROVAL_LEVEL IS NOT NULL
OR ItemVersionEO.INVOICE_MATCH_OPTION IS NOT NULL
OR ItemVersionEO.RECEIVING_ROUTING_ID IS NOT NULL
OR ItemVersionEO.ENFORCE_SHIP_TO_LOCATION_CODE IS NOT NULL
OR ItemVersionEO.RECEIPT_DAYS_EXCEPTION_CODE IS NOT NULL
OR ItemVersionEO.DAYS_EARLY_RECEIPT_ALLOWED IS NOT NULL
OR ItemVersionEO.DAYS_LATE_RECEIPT_ALLOWED IS NOT NULL
OR ItemVersionEO.ALLOW_SUBSTITUTE_RECEIPTS_FLAG IS NOT NULL
OR ItemVersionEO.ALLOW_UNORDERED_RECEIPTS_FLAG IS NOT NULL
OR ItemVersionEO.ALLOW_EXPRESS_DELIVERY_FLAG IS NOT NULL
OR ItemVersionEO.QTY_RCV_EXCEPTION_CODE IS NOT NULL
OR ItemVersionEO.QTY_RCV_TOLERANCE IS NOT NULL
)
ORDER BY ItemClassPEO.ITEM_CLASS_CODE
,ItemVersionEO.TEMPLATE_NAME
,3