/* ****************************************************************************
 * $Revision: 78551 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2022-05-23 13:30:05 +0700 (Mon, 23 May 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Classification%20Categories%20-%20Classification%20Codes.sql $:
 * $Id: Manage Classification Categories - Classification Codes.sql 78551 2022-05-23 06:30:05Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 WITH TREE_PATH AS (SELECT TREE_NODE_ID,SUBSTR(SYS_CONNECT_BY_PATH(PK2_START_VALUE,'###'),1,INSTR(SYS_CONNECT_BY_PATH(PK2_START_VALUE,'###'),'###',-1)-1 ) AS VALUETREE FROM FND_TREE_NODE A
,HZ_CLASS_CATEGORIES B
WHERE B.CLASS_CATEGORY = A.TREE_CODE
START WITH A.PARENT_PK2_VALUE IS NULL
CONNECT BY NOCYCLE PRIOR A.TREE_NODE_ID = A.PARENT_TREE_NODE_ID)

SELECT CLASSCATEGORYEO.CLASS_CATEGORY RES_CLASSIFICATION_CATEGORY
,'Specific value' RES_TREE_NODE_TYPE
,FNDTREESTRUCTUREEO.TREE_STRUCTURE_NAME RES_DATA_SOURCE
,FNDTREEVERSIONEO.TREE_VERSION_NAME RES_TREE_VERSION
,FNDTREEVERSIONEO.TREE_VERSION_NAME RES_TREE
,FNDTREESTRUCTUREEO.TREE_STRUCTURE_NAME RES_TREE_STRUCTURE
,FNDTREEVERSIONEO.TREE_VERSION_NAME RES_REFERENCED_TREE
,NULL RES_REFERENCED_TREE_VERSION
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND 
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,1)+3,INSTR(VALUETREE,'###',1,2)-(INSTR(VALUETREE,'###',1,1)+3))) RES_PARENT_CLASSIFICATION_CODE
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,2)+3,INSTR(VALUETREE,'###',1,3)-(INSTR(VALUETREE,'###',1,2)+3))) RES_PARENT_CLASSIFICATION_CO_0
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,3)+3,INSTR(VALUETREE,'###',1,4)-(INSTR(VALUETREE,'###',1,3)+3))) RES_PARENT_CLASSIFICATION_CO_1
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,4)+3,INSTR(VALUETREE,'###',1,5)-(INSTR(VALUETREE,'###',1,4)+3))) RES_PARENT_CLASSIFICATION_CO_2
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,5)+3,INSTR(VALUETREE,'###',1,6)-(INSTR(VALUETREE,'###',1,5)+3))) RES_PARENT_CLASSIFICATION_CO_3
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,6)+3,INSTR(VALUETREE,'###',1,7)-(INSTR(VALUETREE,'###',1,6)+3))) RES_PARENT_CLASSIFICATION_CO_4
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,7)+3,INSTR(VALUETREE,'###',1,8)-(INSTR(VALUETREE,'###',1,7)+3))) RES_PARENT_CLASSIFICATION_CO_5
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,8)+3,INSTR(VALUETREE,'###',1,9)-(INSTR(VALUETREE,'###',1,8)+3))) RES_PARENT_CLASSIFICATION_CO_6
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,9)+3,INSTR(VALUETREE,'###',1,10)-(INSTR(VALUETREE,'###',1,9)+3))) RES_PARENT_CLASSIFICATION_CO_7
,(SELECT MEANING FROM HZ_CLASS_CATEGORY_CODES_V WHERE CLASS_CATEGORY = FNDTREENODEEO.TREE_CODE AND
	CLASS_CODE = SUBSTR(VALUETREE,INSTR(VALUETREE,'###',1,10)+3,INSTR(VALUETREE,'###',1,11)-(INSTR(VALUETREE,'###',1,10)+3))) RES_PARENT_CLASSIFICATION_CO_8
,CLASSCATEGORYCODEPEO.CLASS_CODE RES_CLASSIFICATION_CODE
,CLASSCATEGORYCODEPEO.MEANING RES_CLASSIFICATION_CODE_MEANIN
,CLASSCATEGORYCODEPEO.DESCRIPTION RES_CLASSIFICATION_CODE_DESCRI
,TO_CHAR(CLASSCATEGORYCODEPEO.START_DATE_ACTIVE,'DD-Mon-YYYY') RES_START_DATE
,DECODE(TO_CHAR(CLASSCATEGORYCODEPEO.END_DATE_ACTIVE,'DD-MM-YYYY'),'31-12-4712',null,TO_CHAR(CLASSCATEGORYCODEPEO.END_DATE_ACTIVE,'DD-Mon-YYYY')) RES_END_DATE
,FndTreeNodeEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,FndTreeNodeEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,FndTreeNodeEO.CREATED_BY RSC_CREATED_BY
,FndTreeNodeEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HZ_CLASS_CATEGORIES ClassCategoryEO
,FND_TREE_VERSION_VL FNDTREEVERSIONEO
,FND_TREE_NODE FNDTREENODEEO
,FND_TREE_STRUCTURE_VL FNDTREESTRUCTUREEO
,HZ_CLASS_CATEGORY_CODES_V CLASSCATEGORYCODEPEO
,TREE_PATH
WHERE CLASSCATEGORYEO.CLASS_CATEGORY           = FNDTREENODEEO.TREE_CODE
AND FNDTREESTRUCTUREEO.TREE_STRUCTURE_CODE     = FNDTREEVERSIONEO.TREE_STRUCTURE_CODE
AND FNDTREEVERSIONEO.TREE_STRUCTURE_CODE       = 'HZ_CLASSIFICATION_HIERARCHY'
AND CLASSCATEGORYCODEPEO.CLASS_CATEGORY        = FNDTREENODEEO.TREE_CODE
AND CLASSCATEGORYCODEPEO.class_code            = FndTreeNodeEO.PK2_START_VALUE
AND FNDTREEVERSIONEO.TREE_VERSION_ID           = FNDTREENODEEO.TREE_VERSION_ID
AND FNDTREENODEEO.TREE_NODE_ID 				   = TREE_PATH.TREE_NODE_ID
--order SIBLINGS by CLASSCATEGORYEO.CLASS_CATEGORY