/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Default%20Item%20Class%20-%20Item%20Template.sql $:
 * $Id: Manage Default Item Class - Item Template.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT ItemClassPEO.ITEM_CLASS_CODE RES_INTERNAL_NAME
,ItemVersionEO.TEMPLATE_NAME RES_NAME
,ItemVersionEO.DESCRIPTION RES_DESCRIPTION
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = ItemVersionEO.ORGANIZATION_ID
	) RES_ORGANIZATION
,ItemClassPEO.ITEM_CLASS_NAME RES_ITEM_CLASS
,DECODE(ItemVersionEO.DEFAULT_TEMPLATE_FLAG,'Y','Yes','No') RES_SET_AS_DEFAULT
,ItemVersionEO.INVENTORY_ITEM_STATUS_CODE RES_ITEM_STATUS
,(SELECT PHASE_NAME
	FROM EGP_PHASES_VL
	WHERE PHASE_CODE = ItemVersionEO.CURRENT_PHASE_CODE
	) RES_LIFECYCLE_PHASE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_ITEM_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.ITEM_TYPE
	) RES_USER_ITEM_TYPE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_PACK_TYPE'
	AND LOOKUP_CODE = ItemVersionEO.TRADE_ITEM_DESCRIPTOR
	) RES_PACK_TYPE
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = ItemVersionEO.PRIMARY_UOM_CODE
	) RES_PRIMARY_UNIT_OF_MEASURE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_ITEM_TRACKING'
	AND LOOKUP_CODE = ItemVersionEO.TRACKING_QUANTITY_IND
	) RES_TRACKING_UNIT_OF_MEASURE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_ITEM_PRICING'
	AND LOOKUP_CODE = ItemVersionEO.ONT_PRICING_QTY_SOURCE
	) RES_PRICING
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_ITEM_CONVERSIONS'
	AND LOOKUP_CODE = ItemVersionEO.ALLOWED_UNITS_LOOKUP_CODE
	) RES_CONVERSIONS
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = ItemVersionEO.SECONDARY_UOM_CODE
	) RES_SECONDARY_UNIT_OF_MEASURE
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'EGP_DEFAULTING'
	AND LOOKUP_CODE = ItemVersionEO.SECONDARY_DEFAULT_IND
	) RES_DEFAULTING_CONTROL
,ItemVersionEO.DUAL_UOM_DEVIATION_HIGH RES_POSITIVE_DEVIATION_FACTOR
,ItemVersionEO.DUAL_UOM_DEVIATION_LOW RES_NEGATIVE_DEVIATION_FACTOR
,ItemVersionEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,ItemVersionEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,ItemVersionEO.CREATED_BY RSC_CREATED_BY
,ItemVersionEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,ItemVersionEO.ORGANIZATION_ID RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM EGP_ITEM_CLASSES_VL ItemClassPEO
,EGP_SYSTEM_ITEMS_V ItemVersionEO
WHERE ItemClassPEO.PARENT_ITEM_CLASS_ID NOT IN (SELECT ITEM_CLASS_ID FROM EGP_ITEM_CLASSES_VL)
AND ItemVersionEO.TEMPLATE_NAME IS NOT NULL
AND ItemClassPEO.ITEM_CLASS_ID = ItemVersionEO.ITEM_CATALOG_GROUP_ID
ORDER BY ItemClassPEO.ITEM_CLASS_CODE
,ItemVersionEO.TEMPLATE_NAME
,4