/* ****************************************************************************
 * $Revision: 68473 $:
 * $Author: tanawat.wongjan $:
 * $Date: 2018-08-27 15:46:49 +0700 (Mon, 27 Aug 2018) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20New%20Item%20Request%20Type%20Details%20-%20Assigned%20To.sql $:
 * $Id: Manage New Item Request Type Details - Assigned To.sql 68473 2018-08-27 08:46:49Z tanawat.wongjan $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
/*<RSC_PRE_STEPS_LARGE_COLUMN_POSITION>5</RSC_PRE_STEPS_LARGE_COLUMN_POSITION>
	
-- The column position that using special data type.
 <RSC_PRE_STEPS_LARGE_COLUMN_TYPE>LONG</RSC_PRE_STEPS_LARGE_COLUMN_TYPE>

-- Specify what type of the data.
*/
 
SELECT hrtContentTypeEO.CONTENT_TYPE_NAME RES_CONTENT_TYPE
 ,hrtContentItemEO.NAME RES_NAME
 ,(SELECT RATING_NAME FROM HRT_RATING_MODELS_VL
		WHERE RATING_MODEL_ID = hrtContentItemEO.RATING_MODEL_ID) RES_RATING_MODEL
 ,hrtContentItemEO.ITEM_DESCRIPTION RES_DESCRIPTION 
 ,hrtContentItemEO.ITEM_DESCRLONG RES_LONG_DESCRIPTION
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Certification Regime  - Job Certification Required?' THEN
	hrtContentItemEO.ITEM_TEXT_11
	ELSE
	NULL END) RES_CERTIFICATION_REQUIRED
 ,hrtContentItemEO.ITEM_TEXT_TL_1 RES_COMPETENCY_ALIAS
 ,(SELECT MEANING FROM FND_LOOKUP_VALUES
	WHERE LOOKUP_CODE = hrtContentItemEO.ITEM_TEXT_3
		AND LOOKUP_TYPE = 'HRT_VALIDITY_PERIOD'
		AND LANGUAGE = USERENV('LANG')) RES_RENEWAL_PERIOD_UNITS
 ,(SELECT MEANING FROM FND_LOOKUP_VALUES
	WHERE LOOKUP_CODE = hrtContentItemEO.ITEM_TEXT_4
		AND LOOKUP_TYPE = 'HRT_SATISFACTION_METHOD'
		AND LANGUAGE = USERENV('LANG')) RES_SATISFACTION_METHOD 
 ,(SELECT MEANING FROM FND_LOOKUP_VALUES
	WHERE LOOKUP_CODE = hrtContentItemEO.ITEM_TEXT_5
		AND LOOKUP_TYPE = 'HRT_COMPETENCY_CATEGORY'
		AND LANGUAGE = USERENV('LANG')) RES_CATEGORY  
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME != 'Licenses and Certifications' THEN
	(SELECT MEANING FROM FND_LOOKUP_VALUES
		WHERE LOOKUP_CODE = hrtContentItemEO.ITEM_TEXT_2
		AND LOOKUP_TYPE = 'HRT_COMPETENCY_EVAL_TYPE'
		AND LANGUAGE = USERENV('LANG'))
		ELSE
    NULL END) RES_EVALUATION_METHOD
 
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Competencies' THEN
	hrtContentItemEO.ITEM_NUMBER_1
	ELSE
	NULL END) RES_RENEWAL_PERIOD_FREQUENCY
 ,hrtContentItemEO.ITEM_TEXT_TL_2 RES_SHORT_DESCRIPTION
 ,hrtContentItemEO.ITEM_TEXT_TL_6 RES_BEHAVIORAL_INDICATOR
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Conduct Regime - Job Rules Acceptance?' THEN
	hrtContentItemEO.ITEM_TEXT_11
	ELSE
	NULL END) RES_CONDUCT_ACCEPTANCE_REQUIRE
 ,(SELECT MEANING FROM FND_LOOKUP_VALUES
	WHERE LOOKUP_CODE = hrtContentItemEO.ITEM_TEXT_3
		AND LOOKUP_TYPE = 'HRT_EDUCATION_LEVEL'
		AND LANGUAGE = USERENV('LANG'))  RES_EDUCATION_LEVEL
 ,NULL RES_FIELD_OF_STUDY
 ,hrtContentItemEO.ITEM_TEXT_8  RES_TYPE_OF_STUDY
 ,hrtContentItemEO.ITEM_NUMBER_2  RES_RANK
 ,hrtContentItemEO.ITEM_NUMBER_3  RES_MONTHS_OF_EDUCATION
 ,hrtContentItemEO.ITEM_NUMBER_5  RES_YEARS_OF_EDUCATION
 ,(SELECT GEOGRAPHY_NAME FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ID = hrtContentItemEO.COUNTRY_ID ) RES_COUNTRY
 
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Establishment' THEN
	ITEM_TEXT_TL_1 
	ELSE
	NULL END) RES_LOCATION
 ,(SELECT GEOGRAPHY_NAME FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ID =  hrtContentItemEO.STATE_PROVINCE_ID) RES_STATE
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Licenses and Certifications' THEN
	DECODE (hrtContentItemEO.ITEM_TEXT_2,'Y','Yes','No')
	ELSE 
	NULL END ) RES_RENEWAL_REQUIRED
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Licenses and Certifications' THEN
  (SELECT MEANING FROM FND_LOOKUP_VALUES
	WHERE LOOKUP_CODE = hrtContentItemEO.ITEM_TEXT_1
		AND LOOKUP_TYPE = 'HRT_VALIDITY_PERIOD'
		AND LANGUAGE = USERENV('LANG'))
	ELSE
	NULL END) RES_RENEWAL_PERIOD
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Licenses and Certifications' THEN
	ITEM_NUMBER_1
	ELSE 
	NULL END ) RES_RENEWAL_LENGTH
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Responsibility Holder Job?' THEN
	ITEM_TEXT_11 
	ELSE
	NULL END) RES_RESPONSIBILITY_HOLDER_JOB
 ,(CASE WHEN hrtContentTypeEO.CONTENT_TYPE_NAME = 'Projects' THEN
  (SELECT MEANING FROM FND_LOOKUP_VALUES
	WHERE LOOKUP_CODE = hrtContentItemEO.ITEM_TEXT_1
		AND LOOKUP_TYPE = 'ORA_HRT_PROJ_TYPES'
		AND LANGUAGE = USERENV('LANG')) 
   ELSE
	NULL END) RES_PROJECT_TYPE
  
 ,hrtContentItemEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
 ,hrtContentItemEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
 ,hrtContentItemEO.CREATED_BY RSC_CREATED_BY
 ,hrtContentItemEO.CREATION_DATE RSC_CREATION_DATE
 ,NULL RSC_LEDGER_ID
 ,NULL RSC_CHART_OF_ACCOUNTS_ID
 ,NULL RSC_BUSINESS_UNIT_ID
 ,NULL RSC_LEGAL_ENTITY_ID
 ,NULL RSC_ORGANIZATION_ID
 ,NULL RSC_BUSINESS_GROUP_ID
 ,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM HRT_CONTENT_TYPES_VL hrtContentTypeEO
,HRT_CONTENT_ITEMS_VL hrtContentItemEO
WHERE hrtContentTypeEO.CONTENT_TYPE_ID = hrtContentItemEO.CONTENT_TYPE_ID
AND hrtContentTypeEO.BUSINESS_GROUP_ID = hrtContentItemEO.BUSINESS_GROUP_ID
ORDER BY hrtContentTypeEO.CONTENT_TYPE_NAME

