/* ****************************************************************************
* $Revision:  $:
* $Author: Nasrullah Dusenmahamad $:
* $Date: 2017-03-17  $:
* $HeadURL: $:
* $Id: Manage Category Descriptive Flexfields - Context Segments $:
* ****************************************************************************
* Description:
* ************************************************************************** */


SELECT shiftsE0.SHIFT_NAME RES_NAME
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ZMM_SR_FLEX_TYPE'
    AND LOOKUP_CODE = shiftDetailsE0.SHIFT_DETAIL_CODE
    ) RES_SHIFT_DETAILS_NAME
,'1' RES_DAY
,TO_CHAR(TIMESTAMP '1970-01-01 00:00:00.000' + NUMTODSINTERVAL(shiftDetailsE0.START_TIME_MS_NUM/ 1000, 'SECOND' ),'HH24:MI:SS') RES_START_TIME
,(CASE
	WHEN shiftDetailsE0.DURATION_UOM_CODE = 'MINUTES' THEN
		shiftDetailsE0.DURATION_MS_NUM/1000/60 
	WHEN shiftDetailsE0.DURATION_UOM_CODE = 'HOURS' THEN
		shiftDetailsE0.DURATION_MS_NUM/1000/60/60 
	WHEN shiftDetailsE0.DURATION_UOM_CODE = 'DAYS' THEN
		shiftDetailsE0.DURATION_MS_NUM/1000/60/60/24
	WHEN shiftDetailsE0.DURATION_UOM_CODE = 'WEEKS' THEN
		shiftDetailsE0.DURATION_MS_NUM/1000/60/60/24/7
	END) RES_DURATION
,(SELECT MEANING
    FROM FND_LOOKUP_VALUES
    WHERE LANGUAGE = USERENV('LANG')
    AND LOOKUP_TYPE = 'ZMM_SR_DURATION_UOM'
    AND LOOKUP_CODE = shiftDetailsE0.DURATION_UOM_CODE
    ) RES_DURATION_UNIT
,shiftDetailsE0.MIN_BREAK_MS_NUM/1000/60 RES_MINIMUM_BREAK_MINUTES
,shiftDetailsE0.MAX_BREAK_MS_NUM/1000/60 RES_MAXIMUM_BREAK_MINUTES
,shiftDetailsE0.CORE_FLAG RES_CORE_WORK
,shiftDetailsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,shiftDetailsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,shiftDetailsE0.CREATED_BY RSC_CREATED_BY
,shiftDetailsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM ZMM_SR_SHIFTS_VL shiftsE0
,ZMM_SR_SHIFT_DTLS shiftDetailsE0
WHERE shiftsE0.SHIFT_ID = shiftDetailsE0.SHIFT_ID
AND shiftsE0.SHIFT_TYPE_CODE = 'TIME'
AND shiftsE0.SHIFT_DTL_TYPE_CODE = 'FLEX'
ORDER BY shiftsE0.SHIFT_NAME