/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Receipt%20Classes%20and%20Methods%20-%20Receipt%20Class%20and%20Methods%20-%20DFF.sql $:
 * $Id: Manage Receipt Classes and Methods - Receipt Class and Methods - DFF.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- syntax: APPLICATION_ID##RES##DFF_CODE (Descriptive Flexfield name)
-- DFF_LOGIC_TO_APPLY=222##RES##AR_RECEIPT_CLASSES
-- DFF_ATTRIBUTES=ATTRIBUTE,GLOBAL_ATTRIBUTE,GLOBAL_ATTRIBUTE_NUMBER,GLOBAL_ATTRIBUTE_DATE

-- IMPORTANT:
-- - the alias names for the Foreign keys must be the same as in the inventory.
-- - the alias name for context code must be RES_CONTEXT_CODE
-- - NO ALIASES for atributes fields.

select ArReceiptClasses.NAME AS RES_NAME
,ArReceiptClasses.ATTRIBUTE_CATEGORY RES_CONTEXT_CODE
,ArReceiptClasses.ATTRIBUTE1
,ArReceiptClasses.ATTRIBUTE2
,ArReceiptClasses.ATTRIBUTE3
,ArReceiptClasses.ATTRIBUTE4
,ArReceiptClasses.ATTRIBUTE5
,ArReceiptClasses.ATTRIBUTE6
,ArReceiptClasses.ATTRIBUTE7
,ArReceiptClasses.ATTRIBUTE8
,ArReceiptClasses.ATTRIBUTE9
,ArReceiptClasses.ATTRIBUTE10
,ArReceiptClasses.ATTRIBUTE11
,ArReceiptClasses.ATTRIBUTE12
,ArReceiptClasses.ATTRIBUTE13
,ArReceiptClasses.ATTRIBUTE14
,ArReceiptClasses.ATTRIBUTE15
,ArReceiptClasses.GLOBAL_ATTRIBUTE1
,ArReceiptClasses.GLOBAL_ATTRIBUTE2
,ArReceiptClasses.GLOBAL_ATTRIBUTE3
,ArReceiptClasses.GLOBAL_ATTRIBUTE4
,ArReceiptClasses.GLOBAL_ATTRIBUTE5
,ArReceiptClasses.GLOBAL_ATTRIBUTE6
,ArReceiptClasses.GLOBAL_ATTRIBUTE7
,ArReceiptClasses.GLOBAL_ATTRIBUTE8
,ArReceiptClasses.GLOBAL_ATTRIBUTE9
,ArReceiptClasses.GLOBAL_ATTRIBUTE10
,ArReceiptClasses.GLOBAL_ATTRIBUTE11
,ArReceiptClasses.GLOBAL_ATTRIBUTE12
,ArReceiptClasses.GLOBAL_ATTRIBUTE13
,ArReceiptClasses.GLOBAL_ATTRIBUTE14
,ArReceiptClasses.GLOBAL_ATTRIBUTE15
,ArReceiptClasses.GLOBAL_ATTRIBUTE16
,ArReceiptClasses.GLOBAL_ATTRIBUTE17
,ArReceiptClasses.GLOBAL_ATTRIBUTE18
,ArReceiptClasses.GLOBAL_ATTRIBUTE19
,ArReceiptClasses.GLOBAL_ATTRIBUTE20
,ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER1
,ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER2
,ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER3
,ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER4
,ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER5
, TO_CHAR(ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE1, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE1
, TO_CHAR(ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE2, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE2
, TO_CHAR(ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE3, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE3
, TO_CHAR(ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE4, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE4
, TO_CHAR(ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE5, 'DD-Mon-YYYY') GLOBAL_ATTRIBUTE_DATE5
,ArReceiptClasses.LAST_UPDATED_BY  as RSC_LAST_UPDATED_BY
,ArReceiptClasses.LAST_UPDATE_DATE  AS RSC_LAST_UPDATE_DATE
,ArReceiptClasses.CREATED_BY  RSC_CREATED_BY
,ArReceiptClasses.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID
 
FROM FUSION.AR_RECEIPT_CLASSES ArReceiptClasses
where (ArReceiptClasses.ATTRIBUTE_CATEGORY IS NOT NULL OR
ArReceiptClasses.ATTRIBUTE1 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE2 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE3 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE4 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE5 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE6 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE7 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE8 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE9 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE10 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE11 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE12 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE13 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE14 IS NOT NULL OR 
ArReceiptClasses.ATTRIBUTE15 IS NOT NULL OR
ArReceiptClasses.GLOBAL_ATTRIBUTE1 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE2 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE3 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE4 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE5 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE6 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE7 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE8 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE9 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE10 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE11 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE12 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE13 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE14 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE15 IS NOT NULL OR
ArReceiptClasses.GLOBAL_ATTRIBUTE16 IS NOT NULL OR
ArReceiptClasses.GLOBAL_ATTRIBUTE17 IS NOT NULL OR
ArReceiptClasses.GLOBAL_ATTRIBUTE18 IS NOT NULL OR
ArReceiptClasses.GLOBAL_ATTRIBUTE19 IS NOT NULL OR
ArReceiptClasses.GLOBAL_ATTRIBUTE20 IS NOT NULL OR
ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER1 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER2 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER3 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER4 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_NUMBER5 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE1 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE2 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE3 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE4 IS NOT NULL OR 
ArReceiptClasses.GLOBAL_ATTRIBUTE_DATE5 IS NOT NULL 
)
ORDER BY RES_NAME

/*SELECT ArReceiptClasses.NAME AS RES_NAME
, DFF.FIELD_NAME AS RES_FIELD_NAME
, DFF.FIELD_VALUE AS RES_FIELD_VALUE
,NULL MAPPER 
,ArReceiptClasses.LAST_UPDATED_BY  AS RSC_LAST_UPDATED_BY
,ArReceiptClasses.LAST_UPDATE_DATE  AS RSC_LAST_UPDATE_DATE
FROM FUSION.AR_RECEIPT_CLASSES ArReceiptClasses
, TABLE(FUSION_READONLY.##RES_PLSQL_PACKAGE_NAME##.GET_DFF(P_APPLICATION_ID => 222
														  ,P_DFF_CODE => 'AR_RECEIPT_CLASSES'
														  ,P_BASE_TABLE => 'AR_RECEIPT_CLASSES'
														  ,P_PK_COLUMN_1 => 'RECEIPT_CLASS_ID'																	  
	)) DFF
WHERE DFF.FIELD_VALUE                     IS NOT NULL
AND  ArReceiptClasses.RECEIPT_CLASS_ID = TO_NUMBER(DFF.COL_1)
and (ArReceiptClasses.last_updated_by ##LAST_UPDATED_BY_OPERATOR## (##USER_NAME_LIST##) AND ArReceiptClasses.last_update_date ##LAST_UPDATE_DATE_OPERATOR##  to_date('##SEEDED_DATE##'))
ORDER BY RES_NAME*/