/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Manage%20Asset%20Books%20-%20Group%20Rules.sql $:
 * $Id: Manage Asset Books - Group Rules.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
 
SELECT QRSLT.BOOK_TYPE_CODE RES_NAME       
,DECODE(QRSLT.ALLOW_GROUP_DEPRN_FLAG,'Y','Yes','No') RES_ALLOW_GROUP_DEPRECIATION		 
,DECODE(QRSLT.ALLOW_CIP_MEMBER_FLAG,'Y','Yes','No') RES_ALLOW_CIP_MEMBERS
,DECODE(QRSLT.ALLOW_CIP_DEP_GROUP_FLAG,'Y','Yes','No') RES_ALLOW_CIP_DEPRECIATION
,DECODE(QRSLT.ALLOW_MEMBER_TRACKING_FLAG,'Y','Yes','No') RES_ALLOW_MEMBER_TRACKING
,DECODE(QRSLT.ALLOW_INTERCO_GROUP_FLAG,'Y','Yes','No') RES_ALLOW_INTERCOMPANY_MEMBER	
,QRSLT.LAST_UPDATED_BY AS RSC_LAST_UPDATED_BY
,QRSLT.LAST_UPDATE_DATE AS RSC_LAST_UPDATE_DATE
,QRSLT.CREATED_BY AS RSC_CREATED_BY
,QRSLT.CREATION_DATE AS RSC_CREATION_DATE
,PGL.PRIMARY_LEDGER_ID AS RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM (SELECT BookControlEO.BOOK_CONTROL_ID
,BookControlEO.BOOK_TYPE_CODE
,BookControlEO.BOOK_TYPE_NAME
,BookControlEO.DISTRIBUTION_SOURCE_BOOK
,BookControlEO.BOOK_CLASS
,BookControlEO.SET_OF_BOOKS_ID
,BookControlEO.DEPRN_CALENDAR
,BookControlEO.FISCAL_YEAR_NAME
,BookControlEO.PRORATE_CALENDAR
,BookControlEO.CURRENT_FISCAL_YEAR
,BookControlEO.DEPR_FIRST_YEAR_RET_FLAG
,BookControlEO.AMORTIZE_FLAG
,BookControlEO.ALLOW_MASS_CHANGES
,BookControlEO.ALLOW_COST_SIGN_CHANGE_FLAG
,BookControlEO.GL_POSTING_ALLOWED_FLAG
,BookControlEO.DEPRN_ALLOCATION_CODE
,BookControlEO.DATE_INEFFECTIVE
,BookControlEO.LAST_DEPRN_RUN_DATE
,BookControlEO.FLEXBUILDER_DEFAULTS_CCID
,BookControlEO.ACCOUNTING_FLEX_STRUCTURE
,BookControlEO.DEFERRED_DEPRN_EXPENSE_ACCT
,BookControlEO.DEFERRED_DEPRN_RESERVE_ACCT
,BookControlEO.PROCEEDS_OF_SALE_GAIN_ACCT
,BookControlEO.COST_OF_REMOVAL_GAIN_ACCT
,BookControlEO.NBV_RETIRED_GAIN_ACCT
,BookControlEO.PROCEEDS_OF_SALE_LOSS_ACCT
,BookControlEO.COST_OF_REMOVAL_LOSS_ACCT
,BookControlEO.NBV_RETIRED_LOSS_ACCT
,BookControlEO.PROCEEDS_OF_SALE_CLEARING_ACCT
,BookControlEO.COST_OF_REMOVAL_CLEARING_ACCT
,BookControlEO.ALLOW_GROUP_DEPRN_FLAG
,BookControlEO.ALLOW_CIP_MEMBER_FLAG
,BookControlEO.ALLOW_CIP_DEP_GROUP_FLAG
,BookControlEO.ALLOW_MEMBER_TRACKING_FLAG
,BookControlEO.ALLOW_INTERCO_GROUP_FLAG
,BookControlEO.ALLOW_CIP_ASSETS_FLAG
,BookControlEO.ALLOW_COST_CEILING
,BookControlEO.ALLOW_DEPRN_EXP_CEILING
,BookControlEO.ALLOW_MASS_COPY
,BookControlEO.COPY_ADDITIONS_FLAG
,BookControlEO.COPY_ADJUSTMENTS_FLAG
,BookControlEO.COPY_RETIREMENTS_FLAG
,BookControlEO.COPY_SALVAGE_VALUE_FLAG
,BookControlEO.INITIAL_DATE
,BookControlEO.MC_SOURCE_FLAG
,BookControlEO.DEPRN_REQUEST_ID
,BookControlEO.ALLOW_PURGE_FLAG
,BookControlEO.ATTRIBUTE_CATEGORY_CODE
,BookControlEO.CAPITAL_GAIN_THRESHOLD
,BookControlEO.DEPRN_STATUS
,BookControlEO.INITIAL_PERIOD_COUNTER
,BookControlEO.LAST_MASS_COPY_PERIOD_COUNTER
,BookControlEO.LAST_PERIOD_COUNTER
,BookControlEO.LAST_PURGE_PERIOD_COUNTER
,BookControlEO.MASS_COPY_SOURCE_BOOK
,BookControlEO.MASS_REQUEST_ID
,BookControlEO.NBV_AMOUNT_THRESHOLD
,BookControlEO.NBV_FRACTION_THRESHOLD
,BookControlEO.IMMEDIATE_COPY_FLAG
,BookControlEO.USE_PERCENT_SALVAGE_VALUE_FLAG
,BookControlEO.REVAL_YTD_DEPRN_FLAG
,BookControlEO.ALLOW_BACKDATED_TRANSFERS_FLAG
,BookControlEO.CREATE_ACCOUNTING_REQUEST_ID
,BookControlEO.AMORTIZE_REVAL_RESERVE_FLAG
,BookControlEO.DEFAULT_LIFE_EXTENSION_CEILING
,BookControlEO.DEFAULT_LIFE_EXTENSION_FACTOR
,BookControlEO.DEFAULT_MAX_FULLY_RSVD_REVALS
,BookControlEO.DEFAULT_REVAL_FULLY_RSVD_FLAG
,BookControlEO.REVAL_DEPRN_RESERVE_FLAG
,BookControlEO.RETIRE_REVAL_RESERVE_FLAG
,BookControlEO.COPY_GROUP_ASSIGNMENT_FLAG
,BookControlEO.COPY_GROUP_ADDITION_FLAG
,BookControlEO.ALLOW_REVAL_FLAG
,BookControlEO.REVAL_RSV_RETIRED_GAIN_ACCT
,BookControlEO.REVAL_RSV_RETIRED_LOSS_ACCT
,BookControlEO.FULLY_RESERVED_FLAG
,BookControlEO.OBJECT_VERSION_NUMBER
,BookControlEO.ROUND_ANNUAL_DEPRECIATION
,BookControlEO.USE_NBV_THRESHOLD_FLAG
,BookControlEO.DEFAULT_DPIS_TO_INV_DATE_FLAG
,BookControlEO.COPY_AMORT_ADAJ_EXP_FLAG
,BookControlEO.COPY_ALL_COST_ADJUSTMENTS_FLAG
,BookControlEO.LAST_CREATE_MASS_ADDITIONS_ID
,BookControlEO.LAST_POST_MASS_ADDITIONS_ID
,BookControlEO.GLOBAL_ATTRIBUTE1
,BookControlEO.GLOBAL_ATTRIBUTE10
,BookControlEO.GLOBAL_ATTRIBUTE11
,BookControlEO.GLOBAL_ATTRIBUTE12
,BookControlEO.GLOBAL_ATTRIBUTE13
,BookControlEO.GLOBAL_ATTRIBUTE14
,BookControlEO.GLOBAL_ATTRIBUTE15
,BookControlEO.GLOBAL_ATTRIBUTE16
,BookControlEO.GLOBAL_ATTRIBUTE17
,BookControlEO.GLOBAL_ATTRIBUTE18
,BookControlEO.GLOBAL_ATTRIBUTE19
,BookControlEO.GLOBAL_ATTRIBUTE2
,BookControlEO.GLOBAL_ATTRIBUTE20
,BookControlEO.GLOBAL_ATTRIBUTE3
,BookControlEO.GLOBAL_ATTRIBUTE4
,BookControlEO.GLOBAL_ATTRIBUTE5
,BookControlEO.GLOBAL_ATTRIBUTE6
,BookControlEO.GLOBAL_ATTRIBUTE7
,BookControlEO.GLOBAL_ATTRIBUTE8
,BookControlEO.GLOBAL_ATTRIBUTE9
,BOOKCONTROLEO.GLOBAL_ATTRIBUTE_CATEGORY
,BOOKCONTROLEO.LAST_UPDATED_BY
,BookControlEO.LAST_UPDATE_DATE
,BOOKCONTROLEO.CREATED_BY
,BookControlEO.CREATION_DATE
,GlLedgers.NAME
,GlLedgers.LEDGER_ID
,GlLedgers.OBJECT_VERSION_NUMBER AS OBJECT_VERSION_NUMBER1
,BookControlEO.ALLOW_IMPAIRMENT_FLAG
,BookControlEO.ALLOW_DEPRN_OVERRIDE_FLAG
,BookControlEO.ALLOW_COST_BASED_REVAL_FLAG
,BookControlEO.ALLOW_FUND_ACCOUNTING_FLAG
,BookControlEO.ALLOW_NBV_BASED_REVAL_FLAG
,BOOKCONTROLEO.DEFAULT_PERIOD_END_REVAL_FLAG
,DepreciationPeriodEO.PERIOD_NAME
FROM FA_BOOK_CONTROLS BookControlEO
,GL_LEDGERS GLLEDGERS 
,FA_DEPRN_PERIODS DEPRECIATIONPERIODEO
WHERE BOOKCONTROLEO.BOOK_TYPE_CODE = DEPRECIATIONPERIODEO.BOOK_TYPE_CODE(+) 
AND BOOKCONTROLEO.INITIAL_PERIOD_COUNTER+1 =   DEPRECIATIONPERIODEO.PERIOD_COUNTER(+)
AND BOOKCONTROLEO.SET_OF_BOOKS_ID = GLLEDGERS.LEDGER_ID(+) ) QRSLT
,(select RSHIP.TARGET_LEDGER_ID
	, RSHIP.PRIMARY_LEDGER_ID 
	from GL_LEDGER_RELATIONSHIPS RSHIP
	WHERE (RSHIP.RELATIONSHIP_TYPE_CODE <> 'NONE'
	AND RSHIP.TARGET_LEDGER_CATEGORY_CODE = 'SECONDARY')
	OR (RSHIP.RELATIONSHIP_TYPE_CODE = 'NONE'
	AND RSHIP.TARGET_LEDGER_CATEGORY_CODE = 'PRIMARY')) PGL
WHERE QRSLT.SET_OF_BOOKS_ID = PGL.TARGET_LEDGER_ID
order by (CASE
	WHEN QRSLT.BOOK_CLASS = 'CORPORATE' THEN
		1
	ELSE
		2
	END)
,QRSLT.BOOK_TYPE_CODE