/* ****************************************************************************
 * $Revision: 78229 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2022-04-07 14:37:05 +0700 (Thu, 07 Apr 2022) $:
 * $HeadURL: https://svn03.rapid4cloud.com/svn/a/dev/rapidesuite/controldata/FUSION_11.1.13/trunk/core/reverse_sql/FINANCIALS/Mass%20Addition%20Distributions.sql $:
 * $Id: Mass Addition Distributions.sql 78229 2022-04-07 07:37:05Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- STRICTLY_BATCH_SEQ = RES_R4C_INTERNAL,RSC_LEDGER_ID

SELECT FaAdditionsBE0.ASSET_ID RES_INTERFACE_LINE_NUMBER
,FaDistributionHistoryE0.UNITS_ASSIGNED RES_UNITS_ASSIGNED
,(SELECT EMAIL_ADDRESS 
	FROM PER_EMAIL_ADDRESSES
	WHERE PERSON_ID = FaDistributionHistoryE0.ASSIGNED_TO
	AND MASTERED_IN_LDAP_FLAG = 'Y'
	AND SYSDATE BETWEEN DATE_FROM AND NVL(DATE_TO,TO_DATE('4712/12/31','YYYY/MM/DD'))
	) RES_EMPLOYEE_EMAIL_ADDRESS
,FaLocationsE0.SEGMENT1 RES_ASSET_LOCATION_SEGMENT1
,FaLocationsE0.SEGMENT2 RES_ASSET_LOCATION_SEGMENT2
,FaLocationsE0.SEGMENT3 RES_ASSET_LOCATION_SEGMENT3
,FaLocationsE0.SEGMENT4 RES_ASSET_LOCATION_SEGMENT4
,FaLocationsE0.SEGMENT5 RES_ASSET_LOCATION_SEGMENT5
,FaLocationsE0.SEGMENT6 RES_ASSET_LOCATION_SEGMENT6
,FaLocationsE0.SEGMENT7 RES_ASSET_LOCATION_SEGMENT7
,AccountsE0.SEGMENT1 RES_DEPRECIATION_EXPENSE_ACCOU
,AccountsE0.SEGMENT2 RES_DEPRECIATION_EXPENSE_ACC_0
,AccountsE0.SEGMENT3 RES_DEPRECIATION_EXPENSE_ACC_1
,AccountsE0.SEGMENT4 RES_DEPRECIATION_EXPENSE_ACC_2
,AccountsE0.SEGMENT5 RES_DEPRECIATION_EXPENSE_ACC_3
,AccountsE0.SEGMENT6 RES_DEPRECIATION_EXPENSE_ACC_4
,AccountsE0.SEGMENT7 RES_DEPRECIATION_EXPENSE_ACC_5
,AccountsE0.SEGMENT8 RES_DEPRECIATION_EXPENSE_ACC_6
,AccountsE0.SEGMENT9 RES_DEPRECIATION_EXPENSE_ACC_7
,AccountsE0.SEGMENT10 RES_DEPRECIATION_EXPENSE_ACC_8
,AccountsE0.SEGMENT11 RES_DEPRECIATION_EXPENSE_ACC_9
,AccountsE0.SEGMENT12 RES_DEPRECIATION_EXPENSE_AC_10
,AccountsE0.SEGMENT13 RES_DEPRECIATION_EXPENSE_AC_11
,AccountsE0.SEGMENT14 RES_DEPRECIATION_EXPENSE_AC_12
,AccountsE0.SEGMENT15 RES_DEPRECIATION_EXPENSE_AC_13
,AccountsE0.SEGMENT16 RES_DEPRECIATION_EXPENSE_AC_14
,AccountsE0.SEGMENT17 RES_DEPRECIATION_EXPENSE_AC_15
,AccountsE0.SEGMENT18 RES_DEPRECIATION_EXPENSE_AC_16
,AccountsE0.SEGMENT19 RES_DEPRECIATION_EXPENSE_AC_17
,AccountsE0.SEGMENT20 RES_DEPRECIATION_EXPENSE_AC_18
,AccountsE0.SEGMENT21 RES_DEPRECIATION_EXPENSE_AC_19
,AccountsE0.SEGMENT22 RES_DEPRECIATION_EXPENSE_AC_20
,AccountsE0.SEGMENT23 RES_DEPRECIATION_EXPENSE_AC_21
,AccountsE0.SEGMENT24 RES_DEPRECIATION_EXPENSE_AC_22
,AccountsE0.SEGMENT25 RES_DEPRECIATION_EXPENSE_AC_23
,AccountsE0.SEGMENT26 RES_DEPRECIATION_EXPENSE_AC_24
,AccountsE0.SEGMENT27 RES_DEPRECIATION_EXPENSE_AC_25
,AccountsE0.SEGMENT28 RES_DEPRECIATION_EXPENSE_AC_26
,AccountsE0.SEGMENT29 RES_DEPRECIATION_EXPENSE_AC_27
,AccountsE0.SEGMENT30 RES_DEPRECIATION_EXPENSE_AC_28
,FaDistributionHistoryE0.DISTRIBUTION_ID||FaDistributionHistoryE0.BOOK_TYPE_CODE RES_R4C_INTERNAL
,FaDistributionHistoryE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,FaDistributionHistoryE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,FaDistributionHistoryE0.CREATED_BY  RSC_CREATED_BY
,FaDistributionHistoryE0.CREATION_DATE  RSC_CREATION_DATE
,FaBookControlsE0.SET_OF_BOOKS_ID RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,null RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FA_ADDITIONS_B FaAdditionsBE0
,FA_BOOKS FaBooksE0
,FA_BOOK_CONTROLS FaBookControlsE0
,FA_ASSET_INVOICES FaAssetInvoicesE0
,FA_DISTRIBUTION_HISTORY FaDistributionHistoryE0
,GL_CODE_COMBINATIONS AccountsE0
,FA_LOCATIONS FaLocationsE0
WHERE FaAdditionsBE0.ASSET_ID = FaBooksE0.ASSET_ID
AND SYSDATE BETWEEN FaBooksE0.DATE_EFFECTIVE AND NVL(FaBooksE0.DATE_INEFFECTIVE,TO_DATE('4712/12/31','YYYY/MM/DD'))
AND FaBooksE0.BOOK_TYPE_CODE = FaBookControlsE0.BOOK_TYPE_CODE
AND SYSDATE < NVL(FaBookControlsE0.DATE_INEFFECTIVE,TO_DATE('4712/12/31','YYYY/MM/DD'))
AND FaAdditionsBE0.ASSET_ID = FaAssetInvoicesE0.ASSET_ID
AND FaAdditionsBE0.ASSET_ID = FaDistributionHistoryE0.ASSET_ID
AND SYSDATE BETWEEN FaDistributionHistoryE0.DATE_EFFECTIVE AND NVL(FaDistributionHistoryE0.DATE_INEFFECTIVE,TO_DATE('4712/12/31','YYYY/MM/DD'))
AND FaDistributionHistoryE0.CODE_COMBINATION_ID = AccountsE0.CODE_COMBINATION_ID(+)
AND FaDistributionHistoryE0.LOCATION_ID = FaLocationsE0.LOCATION_ID(+)
ORDER BY FaAdditionsBE0.ASSET_NUMBER