/* ****************************************************************************
 * $Revision: 58428 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-09-23 18:27:01 +0700 (Fri, 23 Sep 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/customized/In%20Develop/reverse_sql/Manage%20Units%20of%20Measure%20Profiles%20-%20Profile%20Values.sql $:
 * $Id: Manage Units of Measure Profiles - Profile Values.sql 58428 2016-09-23 11:27:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- STRICTLY_BATCH_SEQ = RES_INTERFACE_LINE_LOCATION_KE

SELECT PoLocationsE0.LINE_LOCATION_ID RES_INTERFACE_LINE_LOCATION_KE
,PoLocationsE0.PO_LINE_ID RES_INTERFACE_LINE_KEY
,PoLocationsE0.SHIPMENT_NUM RES_SCHEDULE
,(SELECT LOCATION_NAME
	FROM PER_LOCATION_DETAILS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND LOCATION_ID = PoLocationsE0.SHIP_TO_LOCATION_ID
	) RES_SHIP_TO_LOCATION
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = PoLocationsE0.SHIP_TO_ORGANIZATION_ID
	) RES_SHIP_TO_ORGANIZATION
,PoLocationsE0.AMOUNT RES_AMOUNT
--,PoLocationsE0.QUANTITY RES_QUANTITY
,(PoLocationsE0.QUANTITY - PoLocationsE0.QUANTITY_BILLED) RES_QUANTITY
,TO_CHAR(PoLocationsE0.NEED_BY_DATE,'YYYY/MM/DD') RES_NEED_BY_DATE
,TO_CHAR(PoLocationsE0.PROMISED_DATE,'YYYY/MM/DD') RES_PROMISED_DATE
,PoLocationsE0.SECONDARY_QUANTITY RES_SECONDARY_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLocationsE0.SECONDARY_UOM_CODE
	) RES_SECONDARY_UOM
,PoLocationsE0.DESTINATION_TYPE_CODE RES_DESTINATION_TYPE_CODE
,PoLocationsE0.ACCRUE_ON_RECEIPT_FLAG RES_ACCRUE_AT_RECEIPT
,PoLocationsE0.ALLOW_SUBSTITUTE_RECEIPTS_FLAG RES_ALLOW_SUBSTITUTE_RECEIPTS
,PoLocationsE0.ASSESSABLE_VALUE RES_ASSESSABLE_VALUE
,PoLocationsE0.DAYS_EARLY_RECEIPT_ALLOWED RES_EARLY_RECEIPT_TOLERANCE_IN
,PoLocationsE0.DAYS_LATE_RECEIPT_ALLOWED RES_LATE_RECEIPT_TOLERANCE_IN_
,PoLocationsE0.ENFORCE_SHIP_TO_LOCATION_CODE RES_ENFORCE_SHIP_TO_LOCATION_C
,PoLocationsE0.INSPECTION_REQUIRED_FLAG RES_INSPECTION_REQUIRED
,PoLocationsE0.RECEIPT_REQUIRED_FLAG RES_RECEIPT_REQUIRED
,PoLocationsE0.INVOICE_CLOSE_TOLERANCE RES_INVOICE_CLOSE_TOLERANCE_PE
,PoLocationsE0.RECEIVE_CLOSE_TOLERANCE RES_RECEIPT_CLOSE_TOLERANCE_PE
,PoLocationsE0.QTY_RCV_TOLERANCE RES_QTY_RCV_TOLERANCE
,PoLocationsE0.QTY_RCV_EXCEPTION_CODE RES_QTY_RCV_EXCEPTION_CODE
,PoLocationsE0.RECEIPT_DAYS_EXCEPTION_CODE RES_RECEIPT_DAYS_EXCEPTION_COD
,DECODE(PoLocationsE0.RECEIVING_ROUTING_ID,1,'Standard receipt',2,'Inspection required',3,'Direct delivery') RES_RECEIPT_ROUTING
,PoLocationsE0.NOTE_TO_RECEIVER RES_NOTE_TO_RECEIVER
,PoLocationsE0.INPUT_TAX_CLASSIFICATION_CODE RES_TAX_CLASSIFICATION_CODE
,PoLocationsE0.LINE_INTENDED_USE RES_INTENDED_USE
,PoLocationsE0.PRODUCT_CATEGORY RES_PRODUCT_CATEGORY_CODE
,PoLocationsE0.PRODUCT_FISC_CLASSIFICATION RES_PRODUCT_FISCAL_CLASSIFICAT
,PoLocationsE0.PRODUCT_TYPE RES_PRODUCT_TYPE_CODE
,PoLocationsE0.TRX_BUSINESS_CATEGORY RES_TRANSACTION_BUSINESS_CATEG
,PoLocationsE0.USER_DEFINED_FISC_CLASS RES_USER_DEFINED_FISCAL_CLASSI
,PoLocationsE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,PoLocationsE0.ATTRIBUTE1 RES_ATTRIBUTE1
,PoLocationsE0.ATTRIBUTE2 RES_ATTRIBUTE2
,PoLocationsE0.ATTRIBUTE3 RES_ATTRIBUTE3
,PoLocationsE0.ATTRIBUTE4 RES_ATTRIBUTE4
,PoLocationsE0.ATTRIBUTE5 RES_ATTRIBUTE5
,PoLocationsE0.ATTRIBUTE6 RES_ATTRIBUTE6
,PoLocationsE0.ATTRIBUTE7 RES_ATTRIBUTE7
,PoLocationsE0.ATTRIBUTE8 RES_ATTRIBUTE8
,PoLocationsE0.ATTRIBUTE9 RES_ATTRIBUTE9
,PoLocationsE0.ATTRIBUTE10 RES_ATTRIBUTE10
,PoLocationsE0.ATTRIBUTE11 RES_ATTRIBUTE11
,PoLocationsE0.ATTRIBUTE12 RES_ATTRIBUTE12
,PoLocationsE0.ATTRIBUTE13 RES_ATTRIBUTE13
,PoLocationsE0.ATTRIBUTE14 RES_ATTRIBUTE14
,PoLocationsE0.ATTRIBUTE15 RES_ATTRIBUTE15
,PoLocationsE0.ATTRIBUTE16 RES_ATTRIBUTE16
,PoLocationsE0.ATTRIBUTE17 RES_ATTRIBUTE17
,PoLocationsE0.ATTRIBUTE18 RES_ATTRIBUTE18
,PoLocationsE0.ATTRIBUTE19 RES_ATTRIBUTE19
,PoLocationsE0.ATTRIBUTE20 RES_ATTRIBUTE20
,PoLocationsE0.ATTRIBUTE_DATE1 RES_ATTRIBUTE_DATE1
,PoLocationsE0.ATTRIBUTE_DATE2 RES_ATTRIBUTE_DATE2
,PoLocationsE0.ATTRIBUTE_DATE3 RES_ATTRIBUTE_DATE3
,PoLocationsE0.ATTRIBUTE_DATE4 RES_ATTRIBUTE_DATE4
,PoLocationsE0.ATTRIBUTE_DATE5 RES_ATTRIBUTE_DATE5
,PoLocationsE0.ATTRIBUTE_DATE6 RES_ATTRIBUTE_DATE6
,PoLocationsE0.ATTRIBUTE_DATE7 RES_ATTRIBUTE_DATE7
,PoLocationsE0.ATTRIBUTE_DATE8 RES_ATTRIBUTE_DATE8
,PoLocationsE0.ATTRIBUTE_DATE9 RES_ATTRIBUTE_DATE9
,PoLocationsE0.ATTRIBUTE_DATE10 RES_ATTRIBUTE_DATE10
,PoLocationsE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,PoLocationsE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,PoLocationsE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,PoLocationsE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,PoLocationsE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,PoLocationsE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,PoLocationsE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,PoLocationsE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,PoLocationsE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,PoLocationsE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,PoLocationsE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,PoLocationsE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,PoLocationsE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,PoLocationsE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,PoLocationsE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,PoLocationsE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,PoLocationsE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,PoLocationsE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,PoLocationsE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,PoLocationsE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,(SELECT PARTY_NAME
	FROM HZ_PARTIES
	WHERE PARTY_ID = PoLocationsE0.CARRIER_ID
	) RES_CARRIER
,PoLocationsE0.MODE_OF_TRANSPORT RES_MODE_OF_TRANSPORT
,PoLocationsE0.SERVICE_LEVEL RES_SERVICE_LEVEL
,(SELECT LOCATION_NAME
	FROM PER_LOCATION_DETAILS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND LOCATION_ID = PoLocationsE0.FINAL_DISCHARGE_LOCATION_ID
	) RES_FINAL_DISCHARGE_LOCATION_C
,TO_CHAR(PoLocationsE0.REQUESTED_SHIP_DATE,'YYYY/MM/DD') RES_REQUESTED_SHIP_DATE
,TO_CHAR(PoLocationsE0.PROMISED_SHIP_DATE,'YYYY/MM/DD') RES_PROMISED_SHIP_DATE
,TO_CHAR(PoLocationsE0.NEED_BY_DATE,'YYYY/MM/DD') RES_REQUESTED_DELIVERY_DATE
,TO_CHAR(PoLocationsE0.PROMISED_DATE,'YYYY/MM/DD') RES_PROMISED_DELIVERY_DATE 
,PoLocationsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,PoLocationsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,PoLocationsE0.CREATED_BY RSC_CREATED_BY
,PoLocationsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,PoLocationsE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PO_HEADERS_ALL PoHeadersE0
,PO_LINES_ALL PoLinesE0
,PO_LINE_LOCATIONS_ALL PoLocationsE0
WHERE PoHeadersE0.PO_HEADER_ID = PoLinesE0.PO_HEADER_ID
AND PoLinesE0.PO_HEADER_ID = PoLocationsE0.PO_HEADER_ID
AND PoLinesE0.PO_LINE_ID = PoLocationsE0.PO_LINE_ID
AND PoLinesE0.LINE_STATUS = 'OPEN'
AND NVL(PoHeadersE0.APPROVED_FLAG,'N') = 'Y'
AND PoHeadersE0.TYPE_LOOKUP_CODE = 'STANDARD' --Only PO
AND PoHeadersE0.DOCUMENT_STATUS = 'OPEN' --PO Header status
AND (PoLocationsE0.QUANTITY - PoLocationsE0.QUANTITY_BILLED) > 0

UNION

SELECT PoLocationsE0.LINE_LOCATION_ID RES_INTERFACE_LINE_LOCATION_KE
,PoLocationsE0.PO_LINE_ID RES_INTERFACE_LINE_KEY
,PoLocationsE0.SHIPMENT_NUM RES_SCHEDULE
,(SELECT LOCATION_NAME
	FROM PER_LOCATION_DETAILS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND LOCATION_ID = PoLocationsE0.SHIP_TO_LOCATION_ID
	) RES_SHIP_TO_LOCATION
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = PoLocationsE0.SHIP_TO_ORGANIZATION_ID
	) RES_SHIP_TO_ORGANIZATION
,(SELECT PoLocationsE0.AMOUNT - NVL(SUM(invLines.AMOUNT),0) 
	FROM AP_INVOICES_ALL inv
	,AP_INVOICE_LINES_ALL invLines
	WHERE inv.INVOICE_ID = invLines.INVOICE_ID
	AND invLines.LINE_TYPE_LOOKUP_CODE != 'TAX'
	AND invLines.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND invLines.PO_LINE_ID = PoLinesE0.PO_LINE_ID
	AND invLines.PO_LINE_LOCATION_ID = PoLocationsE0.LINE_LOCATION_ID
	) RES_AMOUNT
,(PoLocationsE0.QUANTITY - PoLocationsE0.QUANTITY_BILLED) RES_QUANTITY
,TO_CHAR(PoLocationsE0.NEED_BY_DATE,'YYYY/MM/DD') RES_NEED_BY_DATE
,TO_CHAR(PoLocationsE0.PROMISED_DATE,'YYYY/MM/DD') RES_PROMISED_DATE
,PoLocationsE0.SECONDARY_QUANTITY RES_SECONDARY_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLocationsE0.SECONDARY_UOM_CODE
	) RES_SECONDARY_UOM
,PoLocationsE0.DESTINATION_TYPE_CODE RES_DESTINATION_TYPE_CODE
,PoLocationsE0.ACCRUE_ON_RECEIPT_FLAG RES_ACCRUE_AT_RECEIPT
,PoLocationsE0.ALLOW_SUBSTITUTE_RECEIPTS_FLAG RES_ALLOW_SUBSTITUTE_RECEIPTS
,PoLocationsE0.ASSESSABLE_VALUE RES_ASSESSABLE_VALUE
,PoLocationsE0.DAYS_EARLY_RECEIPT_ALLOWED RES_EARLY_RECEIPT_TOLERANCE_IN
,PoLocationsE0.DAYS_LATE_RECEIPT_ALLOWED RES_LATE_RECEIPT_TOLERANCE_IN_
,PoLocationsE0.ENFORCE_SHIP_TO_LOCATION_CODE RES_ENFORCE_SHIP_TO_LOCATION_C
,PoLocationsE0.INSPECTION_REQUIRED_FLAG RES_INSPECTION_REQUIRED
,PoLocationsE0.RECEIPT_REQUIRED_FLAG RES_RECEIPT_REQUIRED
,PoLocationsE0.INVOICE_CLOSE_TOLERANCE RES_INVOICE_CLOSE_TOLERANCE_PE
,PoLocationsE0.RECEIVE_CLOSE_TOLERANCE RES_RECEIPT_CLOSE_TOLERANCE_PE
,PoLocationsE0.QTY_RCV_TOLERANCE RES_QTY_RCV_TOLERANCE
,PoLocationsE0.QTY_RCV_EXCEPTION_CODE RES_QTY_RCV_EXCEPTION_CODE
,PoLocationsE0.RECEIPT_DAYS_EXCEPTION_CODE RES_RECEIPT_DAYS_EXCEPTION_COD
,DECODE(PoLocationsE0.RECEIVING_ROUTING_ID,1,'Standard receipt',2,'Inspection required',3,'Direct delivery') RES_RECEIPT_ROUTING
,PoLocationsE0.NOTE_TO_RECEIVER RES_NOTE_TO_RECEIVER
,PoLocationsE0.INPUT_TAX_CLASSIFICATION_CODE RES_TAX_CLASSIFICATION_CODE
,PoLocationsE0.LINE_INTENDED_USE RES_INTENDED_USE
,PoLocationsE0.PRODUCT_CATEGORY RES_PRODUCT_CATEGORY_CODE
,PoLocationsE0.PRODUCT_FISC_CLASSIFICATION RES_PRODUCT_FISCAL_CLASSIFICAT
,PoLocationsE0.PRODUCT_TYPE RES_PRODUCT_TYPE_CODE
,PoLocationsE0.TRX_BUSINESS_CATEGORY RES_TRANSACTION_BUSINESS_CATEG
,PoLocationsE0.USER_DEFINED_FISC_CLASS RES_USER_DEFINED_FISCAL_CLASSI
,PoLocationsE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,PoLocationsE0.ATTRIBUTE1 RES_ATTRIBUTE1
,PoLocationsE0.ATTRIBUTE2 RES_ATTRIBUTE2
,PoLocationsE0.ATTRIBUTE3 RES_ATTRIBUTE3
,PoLocationsE0.ATTRIBUTE4 RES_ATTRIBUTE4
,PoLocationsE0.ATTRIBUTE5 RES_ATTRIBUTE5
,PoLocationsE0.ATTRIBUTE6 RES_ATTRIBUTE6
,PoLocationsE0.ATTRIBUTE7 RES_ATTRIBUTE7
,PoLocationsE0.ATTRIBUTE8 RES_ATTRIBUTE8
,PoLocationsE0.ATTRIBUTE9 RES_ATTRIBUTE9
,PoLocationsE0.ATTRIBUTE10 RES_ATTRIBUTE10
,PoLocationsE0.ATTRIBUTE11 RES_ATTRIBUTE11
,PoLocationsE0.ATTRIBUTE12 RES_ATTRIBUTE12
,PoLocationsE0.ATTRIBUTE13 RES_ATTRIBUTE13
,PoLocationsE0.ATTRIBUTE14 RES_ATTRIBUTE14
,PoLocationsE0.ATTRIBUTE15 RES_ATTRIBUTE15
,PoLocationsE0.ATTRIBUTE16 RES_ATTRIBUTE16
,PoLocationsE0.ATTRIBUTE17 RES_ATTRIBUTE17
,PoLocationsE0.ATTRIBUTE18 RES_ATTRIBUTE18
,PoLocationsE0.ATTRIBUTE19 RES_ATTRIBUTE19
,PoLocationsE0.ATTRIBUTE20 RES_ATTRIBUTE20
,PoLocationsE0.ATTRIBUTE_DATE1 RES_ATTRIBUTE_DATE1
,PoLocationsE0.ATTRIBUTE_DATE2 RES_ATTRIBUTE_DATE2
,PoLocationsE0.ATTRIBUTE_DATE3 RES_ATTRIBUTE_DATE3
,PoLocationsE0.ATTRIBUTE_DATE4 RES_ATTRIBUTE_DATE4
,PoLocationsE0.ATTRIBUTE_DATE5 RES_ATTRIBUTE_DATE5
,PoLocationsE0.ATTRIBUTE_DATE6 RES_ATTRIBUTE_DATE6
,PoLocationsE0.ATTRIBUTE_DATE7 RES_ATTRIBUTE_DATE7
,PoLocationsE0.ATTRIBUTE_DATE8 RES_ATTRIBUTE_DATE8
,PoLocationsE0.ATTRIBUTE_DATE9 RES_ATTRIBUTE_DATE9
,PoLocationsE0.ATTRIBUTE_DATE10 RES_ATTRIBUTE_DATE10
,PoLocationsE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,PoLocationsE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,PoLocationsE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,PoLocationsE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,PoLocationsE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,PoLocationsE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,PoLocationsE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,PoLocationsE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,PoLocationsE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,PoLocationsE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,PoLocationsE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,PoLocationsE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,PoLocationsE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,PoLocationsE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,PoLocationsE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,PoLocationsE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,PoLocationsE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,PoLocationsE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,PoLocationsE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,PoLocationsE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,(SELECT PARTY_NAME
	FROM HZ_PARTIES
	WHERE PARTY_ID = PoLocationsE0.CARRIER_ID
	) RES_CARRIER
,PoLocationsE0.MODE_OF_TRANSPORT RES_MODE_OF_TRANSPORT
,PoLocationsE0.SERVICE_LEVEL RES_SERVICE_LEVEL
,(SELECT LOCATION_NAME
	FROM PER_LOCATION_DETAILS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND LOCATION_ID = PoLocationsE0.FINAL_DISCHARGE_LOCATION_ID
	) RES_FINAL_DISCHARGE_LOCATION_C
,TO_CHAR(PoLocationsE0.REQUESTED_SHIP_DATE,'YYYY/MM/DD') RES_REQUESTED_SHIP_DATE
,TO_CHAR(PoLocationsE0.PROMISED_SHIP_DATE,'YYYY/MM/DD') RES_PROMISED_SHIP_DATE
,TO_CHAR(PoLocationsE0.NEED_BY_DATE,'YYYY/MM/DD') RES_REQUESTED_DELIVERY_DATE
,TO_CHAR(PoLocationsE0.PROMISED_DATE,'YYYY/MM/DD') RES_PROMISED_DELIVERY_DATE 
,PoLocationsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,PoLocationsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,PoLocationsE0.CREATED_BY RSC_CREATED_BY
,PoLocationsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,PoLocationsE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PO_HEADERS_ALL PoHeadersE0
,PO_LINES_ALL PoLinesE0
,PO_LINE_LOCATIONS_ALL PoLocationsE0
WHERE PoHeadersE0.PO_HEADER_ID = PoLinesE0.PO_HEADER_ID
AND PoLinesE0.PO_HEADER_ID = PoLocationsE0.PO_HEADER_ID
AND PoLinesE0.PO_LINE_ID = PoLocationsE0.PO_LINE_ID
AND PoLinesE0.LINE_STATUS = 'OPEN'
AND NVL(PoHeadersE0.APPROVED_FLAG,'N') = 'Y'
AND PoHeadersE0.TYPE_LOOKUP_CODE = 'STANDARD' --Only PO
AND PoHeadersE0.DOCUMENT_STATUS = 'OPEN' --PO Header status
AND PoLocationsE0.DESTINATION_TYPE_CODE = 'EXPENSE'

AND (SELECT PoLinesE0.AMOUNT - NVL(SUM(invLines.AMOUNT),0) 
	FROM AP_INVOICES_ALL inv
	,AP_INVOICE_LINES_ALL invLines
	WHERE inv.INVOICE_ID = invLines.INVOICE_ID
	AND invLines.LINE_TYPE_LOOKUP_CODE != 'TAX'
	AND invLines.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND invLines.PO_LINE_ID = PoLinesE0.PO_LINE_ID
	AND invLines.PO_LINE_LOCATION_ID = PoLocationsE0.LINE_LOCATION_ID
	) > 0
	
UNION

SELECT PoLocationsE0.LINE_LOCATION_ID RES_INTERFACE_LINE_LOCATION_KE
,PoLocationsE0.PO_LINE_ID RES_INTERFACE_LINE_KEY
,PoLocationsE0.SHIPMENT_NUM RES_SCHEDULE
,(SELECT LOCATION_NAME
	FROM PER_LOCATION_DETAILS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND LOCATION_ID = PoLocationsE0.SHIP_TO_LOCATION_ID
	) RES_SHIP_TO_LOCATION
,(SELECT ORGANIZATION_CODE
	FROM INV_ORG_PARAMETERS
	WHERE ORGANIZATION_ID = PoLocationsE0.SHIP_TO_ORGANIZATION_ID
	) RES_SHIP_TO_ORGANIZATION
,(SELECT PoLocationsE0.AMOUNT - NVL(SUM(invLines.AMOUNT),0) 
	FROM AP_INVOICES_ALL inv
	,AP_INVOICE_LINES_ALL invLines
	WHERE inv.INVOICE_ID = invLines.INVOICE_ID
	AND invLines.LINE_TYPE_LOOKUP_CODE != 'TAX'
	AND invLines.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND invLines.PO_LINE_ID = PoLinesE0.PO_LINE_ID
	AND invLines.PO_LINE_LOCATION_ID = PoLocationsE0.LINE_LOCATION_ID
	) RES_AMOUNT
,(PoLocationsE0.QUANTITY - PoLocationsE0.QUANTITY_BILLED) RES_QUANTITY
,TO_CHAR(PoLocationsE0.NEED_BY_DATE,'YYYY/MM/DD') RES_NEED_BY_DATE
,TO_CHAR(PoLocationsE0.PROMISED_DATE,'YYYY/MM/DD') RES_PROMISED_DATE
,PoLocationsE0.SECONDARY_QUANTITY RES_SECONDARY_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLocationsE0.SECONDARY_UOM_CODE
	) RES_SECONDARY_UOM
,PoLocationsE0.DESTINATION_TYPE_CODE RES_DESTINATION_TYPE_CODE
,PoLocationsE0.ACCRUE_ON_RECEIPT_FLAG RES_ACCRUE_AT_RECEIPT
,PoLocationsE0.ALLOW_SUBSTITUTE_RECEIPTS_FLAG RES_ALLOW_SUBSTITUTE_RECEIPTS
,PoLocationsE0.ASSESSABLE_VALUE RES_ASSESSABLE_VALUE
,PoLocationsE0.DAYS_EARLY_RECEIPT_ALLOWED RES_EARLY_RECEIPT_TOLERANCE_IN
,PoLocationsE0.DAYS_LATE_RECEIPT_ALLOWED RES_LATE_RECEIPT_TOLERANCE_IN_
,PoLocationsE0.ENFORCE_SHIP_TO_LOCATION_CODE RES_ENFORCE_SHIP_TO_LOCATION_C
,PoLocationsE0.INSPECTION_REQUIRED_FLAG RES_INSPECTION_REQUIRED
,PoLocationsE0.RECEIPT_REQUIRED_FLAG RES_RECEIPT_REQUIRED
,PoLocationsE0.INVOICE_CLOSE_TOLERANCE RES_INVOICE_CLOSE_TOLERANCE_PE
,PoLocationsE0.RECEIVE_CLOSE_TOLERANCE RES_RECEIPT_CLOSE_TOLERANCE_PE
,PoLocationsE0.QTY_RCV_TOLERANCE RES_QTY_RCV_TOLERANCE
,PoLocationsE0.QTY_RCV_EXCEPTION_CODE RES_QTY_RCV_EXCEPTION_CODE
,PoLocationsE0.RECEIPT_DAYS_EXCEPTION_CODE RES_RECEIPT_DAYS_EXCEPTION_COD
,DECODE(PoLocationsE0.RECEIVING_ROUTING_ID,1,'Standard receipt',2,'Inspection required',3,'Direct delivery') RES_RECEIPT_ROUTING
,PoLocationsE0.NOTE_TO_RECEIVER RES_NOTE_TO_RECEIVER
,PoLocationsE0.INPUT_TAX_CLASSIFICATION_CODE RES_TAX_CLASSIFICATION_CODE
,PoLocationsE0.LINE_INTENDED_USE RES_INTENDED_USE
,PoLocationsE0.PRODUCT_CATEGORY RES_PRODUCT_CATEGORY_CODE
,PoLocationsE0.PRODUCT_FISC_CLASSIFICATION RES_PRODUCT_FISCAL_CLASSIFICAT
,PoLocationsE0.PRODUCT_TYPE RES_PRODUCT_TYPE_CODE
,PoLocationsE0.TRX_BUSINESS_CATEGORY RES_TRANSACTION_BUSINESS_CATEG
,PoLocationsE0.USER_DEFINED_FISC_CLASS RES_USER_DEFINED_FISCAL_CLASSI
,PoLocationsE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,PoLocationsE0.ATTRIBUTE1 RES_ATTRIBUTE1
,PoLocationsE0.ATTRIBUTE2 RES_ATTRIBUTE2
,PoLocationsE0.ATTRIBUTE3 RES_ATTRIBUTE3
,PoLocationsE0.ATTRIBUTE4 RES_ATTRIBUTE4
,PoLocationsE0.ATTRIBUTE5 RES_ATTRIBUTE5
,PoLocationsE0.ATTRIBUTE6 RES_ATTRIBUTE6
,PoLocationsE0.ATTRIBUTE7 RES_ATTRIBUTE7
,PoLocationsE0.ATTRIBUTE8 RES_ATTRIBUTE8
,PoLocationsE0.ATTRIBUTE9 RES_ATTRIBUTE9
,PoLocationsE0.ATTRIBUTE10 RES_ATTRIBUTE10
,PoLocationsE0.ATTRIBUTE11 RES_ATTRIBUTE11
,PoLocationsE0.ATTRIBUTE12 RES_ATTRIBUTE12
,PoLocationsE0.ATTRIBUTE13 RES_ATTRIBUTE13
,PoLocationsE0.ATTRIBUTE14 RES_ATTRIBUTE14
,PoLocationsE0.ATTRIBUTE15 RES_ATTRIBUTE15
,PoLocationsE0.ATTRIBUTE16 RES_ATTRIBUTE16
,PoLocationsE0.ATTRIBUTE17 RES_ATTRIBUTE17
,PoLocationsE0.ATTRIBUTE18 RES_ATTRIBUTE18
,PoLocationsE0.ATTRIBUTE19 RES_ATTRIBUTE19
,PoLocationsE0.ATTRIBUTE20 RES_ATTRIBUTE20
,PoLocationsE0.ATTRIBUTE_DATE1 RES_ATTRIBUTE_DATE1
,PoLocationsE0.ATTRIBUTE_DATE2 RES_ATTRIBUTE_DATE2
,PoLocationsE0.ATTRIBUTE_DATE3 RES_ATTRIBUTE_DATE3
,PoLocationsE0.ATTRIBUTE_DATE4 RES_ATTRIBUTE_DATE4
,PoLocationsE0.ATTRIBUTE_DATE5 RES_ATTRIBUTE_DATE5
,PoLocationsE0.ATTRIBUTE_DATE6 RES_ATTRIBUTE_DATE6
,PoLocationsE0.ATTRIBUTE_DATE7 RES_ATTRIBUTE_DATE7
,PoLocationsE0.ATTRIBUTE_DATE8 RES_ATTRIBUTE_DATE8
,PoLocationsE0.ATTRIBUTE_DATE9 RES_ATTRIBUTE_DATE9
,PoLocationsE0.ATTRIBUTE_DATE10 RES_ATTRIBUTE_DATE10
,PoLocationsE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,PoLocationsE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,PoLocationsE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,PoLocationsE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,PoLocationsE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,PoLocationsE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,PoLocationsE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,PoLocationsE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,PoLocationsE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,PoLocationsE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,PoLocationsE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,PoLocationsE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,PoLocationsE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,PoLocationsE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,PoLocationsE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,PoLocationsE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,PoLocationsE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,PoLocationsE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,PoLocationsE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,PoLocationsE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,(SELECT PARTY_NAME
	FROM HZ_PARTIES
	WHERE PARTY_ID = PoLocationsE0.CARRIER_ID
	) RES_CARRIER
,PoLocationsE0.MODE_OF_TRANSPORT RES_MODE_OF_TRANSPORT
,PoLocationsE0.SERVICE_LEVEL RES_SERVICE_LEVEL
,(SELECT LOCATION_NAME
	FROM PER_LOCATION_DETAILS_F_VL
	WHERE SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND LOCATION_ID = PoLocationsE0.FINAL_DISCHARGE_LOCATION_ID
	) RES_FINAL_DISCHARGE_LOCATION_C
,TO_CHAR(PoLocationsE0.REQUESTED_SHIP_DATE,'YYYY/MM/DD') RES_REQUESTED_SHIP_DATE
,TO_CHAR(PoLocationsE0.PROMISED_SHIP_DATE,'YYYY/MM/DD') RES_PROMISED_SHIP_DATE
,TO_CHAR(PoLocationsE0.NEED_BY_DATE,'YYYY/MM/DD') RES_REQUESTED_DELIVERY_DATE
,TO_CHAR(PoLocationsE0.PROMISED_DATE,'YYYY/MM/DD') RES_PROMISED_DELIVERY_DATE 
,PoLocationsE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,PoLocationsE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,PoLocationsE0.CREATED_BY RSC_CREATED_BY
,PoLocationsE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,PoLocationsE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PO_HEADERS_ALL PoHeadersE0
,PO_LINES_ALL PoLinesE0
,PO_LINE_LOCATIONS_ALL PoLocationsE0
WHERE PoHeadersE0.PO_HEADER_ID = PoLinesE0.PO_HEADER_ID
AND PoLinesE0.PO_HEADER_ID = PoLocationsE0.PO_HEADER_ID
AND PoLinesE0.PO_LINE_ID = PoLocationsE0.PO_LINE_ID
AND PoLinesE0.LINE_STATUS = 'OPEN'
AND NVL(PoHeadersE0.APPROVED_FLAG,'N') = 'Y'
AND PoHeadersE0.TYPE_LOOKUP_CODE = 'STANDARD' --Only PO
AND PoHeadersE0.DOCUMENT_STATUS = 'OPEN' --PO Header status
AND PoLocationsE0.DESTINATION_TYPE_CODE = 'EXPENSE'

AND NOT EXISTS (SELECT 1
	FROM AP_INVOICES_ALL inv
	,AP_INVOICE_LINES_ALL invLines
	WHERE inv.INVOICE_ID = invLines.INVOICE_ID
	AND invLines.LINE_TYPE_LOOKUP_CODE != 'TAX'
	AND invLines.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND invLines.PO_LINE_ID = PoLinesE0.PO_LINE_ID
	AND invLines.PO_LINE_LOCATION_ID = PoLocationsE0.LINE_LOCATION_ID
	)