/* ****************************************************************************
 * $Revision: 58428 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-09-23 18:27:01 +0700 (Fri, 23 Sep 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/customized/In%20Develop/reverse_sql/Manage%20Units%20of%20Measure%20Profiles%20-%20Profile%20Values.sql $:
 * $Id: Manage Units of Measure Profiles - Profile Values.sql 58428 2016-09-23 11:27:01Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 
-- STRICTLY_BATCH_SEQ = RES_INTERFACE_LINE_KEY

SELECT PoLinesE0.PO_LINE_ID RES_INTERFACE_LINE_KEY
,PoHeadersE0.PO_HEADER_ID RES_INTERFACE_HEADER_KEY
,'ADD' RES_ACTION
,PoLinesE0.LINE_NUM RES_LINE
,(SELECT LINE_TYPE
	FROM PO_LINE_TYPES_TL
	WHERE LINE_TYPE_ID = PoLinesE0.LINE_TYPE_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_LINE_TYPE
,ItemsE0.ITEM_NUMBER RES_ITEM
,REPLACE(PoLinesE0.ITEM_DESCRIPTION,chr(10),' ') RES_ITEM_DESCRIPTION
,PoLinesE0.ITEM_REVISION RES_ITEM_REVISION
,(SELECT CATEGORY_NAME
	FROM EGP_CATEGORIES_TL
	WHERE CATEGORY_ID = PoLinesE0.CATEGORY_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_CATEGORY_NAME
,PoLinesE0.AMOUNT RES_AMOUNT
--,PoLinesE0.QUANTITY RES_QUANTITY
,(SELECT SUM(QUANTITY) - SUM(QUANTITY_BILLED)
	FROM PO_LINE_LOCATIONS_ALL
	WHERE PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND PO_LINE_ID = PoLinesE0.PO_LINE_ID
	) RES_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLinesE0.UOM_CODE
	) RES_UOM
,PoLinesE0.UNIT_PRICE RES_PRICE
,PoLinesE0.SECONDARY_QUANTITY RES_SECONDARY_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLinesE0.SECONDARY_UOM_CODE
	) RES_SECONDARY_UOM
,PoLinesE0.VENDOR_PRODUCT_NUM RES_SUPPLIER_ITEM --????
,PoLinesE0.NEGOTIATED_BY_PREPARER_FLAG RES_NEGOTIATED
,(SELECT HAZARD_CLASS
	FROM PO_HAZARD_CLASSES_TL
	WHERE HAZARD_CLASS_ID = PoLinesE0.HAZARD_CLASS_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_HAZARD_CLASS
,(SELECT UN_NUMBER
	FROM PO_UN_NUMBERS_TL
	WHERE UN_NUMBER_ID = PoLinesE0.UN_NUMBER_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_UN_NUMBER
,PoLinesE0.NOTE_TO_VENDOR RES_NOTE_TO_SUPPLIER
,'' RES_NOTE_TO_RECEIVER
,PoLinesE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,PoLinesE0.ATTRIBUTE1 RES_ATTRIBUTE1
,PoLinesE0.ATTRIBUTE2 RES_ATTRIBUTE2
,PoLinesE0.ATTRIBUTE3 RES_ATTRIBUTE3
,PoLinesE0.ATTRIBUTE4 RES_ATTRIBUTE4
,PoLinesE0.ATTRIBUTE5 RES_ATTRIBUTE5
,PoLinesE0.ATTRIBUTE6 RES_ATTRIBUTE6
,PoLinesE0.ATTRIBUTE7 RES_ATTRIBUTE7
,PoLinesE0.ATTRIBUTE8 RES_ATTRIBUTE8
,PoLinesE0.ATTRIBUTE9 RES_ATTRIBUTE9
,PoLinesE0.ATTRIBUTE10 RES_ATTRIBUTE10
,PoLinesE0.ATTRIBUTE11 RES_ATTRIBUTE11
,PoLinesE0.ATTRIBUTE12 RES_ATTRIBUTE12
,PoLinesE0.ATTRIBUTE13 RES_ATTRIBUTE13
,PoLinesE0.ATTRIBUTE14 RES_ATTRIBUTE14
,PoLinesE0.ATTRIBUTE15 RES_ATTRIBUTE15
,PoLinesE0.ATTRIBUTE16 RES_ATTRIBUTE16
,PoLinesE0.ATTRIBUTE17 RES_ATTRIBUTE17
,PoLinesE0.ATTRIBUTE18 RES_ATTRIBUTE18
,PoLinesE0.ATTRIBUTE19 RES_ATTRIBUTE19
,PoLinesE0.ATTRIBUTE20 RES_ATTRIBUTE20
,PoLinesE0.ATTRIBUTE_DATE1 RES_ATTRIBUTE_DATE1
,PoLinesE0.ATTRIBUTE_DATE2 RES_ATTRIBUTE_DATE2
,PoLinesE0.ATTRIBUTE_DATE3 RES_ATTRIBUTE_DATE3
,PoLinesE0.ATTRIBUTE_DATE4 RES_ATTRIBUTE_DATE4
,PoLinesE0.ATTRIBUTE_DATE5 RES_ATTRIBUTE_DATE5
,PoLinesE0.ATTRIBUTE_DATE6 RES_ATTRIBUTE_DATE6
,PoLinesE0.ATTRIBUTE_DATE7 RES_ATTRIBUTE_DATE7
,PoLinesE0.ATTRIBUTE_DATE8 RES_ATTRIBUTE_DATE8
,PoLinesE0.ATTRIBUTE_DATE9 RES_ATTRIBUTE_DATE9
,PoLinesE0.ATTRIBUTE_DATE10 RES_ATTRIBUTE_DATE10
,PoLinesE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,PoLinesE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,PoLinesE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,PoLinesE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,PoLinesE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,PoLinesE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,PoLinesE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,PoLinesE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,PoLinesE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,PoLinesE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,PoLinesE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,PoLinesE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,PoLinesE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,PoLinesE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,PoLinesE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,PoLinesE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,PoLinesE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,PoLinesE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,PoLinesE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,PoLinesE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,ItemsE0.UNIT_WEIGHT RES_UNIT_WEIGHT
,ItemsE0.WEIGHT_UOM_CODE RES_WEIGHT_UOM
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = ItemsE0.WEIGHT_UOM_CODE
	) RES_WEIGHT_UOM_NAME
,ItemsE0.UNIT_VOLUME RES_UNIT_VOLUMN
,ItemsE0.VOLUME_UOM_CODE RES_VOLUME_UOM
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = ItemsE0.VOLUME_UOM_CODE
	) RES_VOLUME_UOM_NAME
,'' RES_TEMPLATE_NAME
,ItemsE0.ATTRIBUTE_CATEGORY RES_ITEM_ATTRIBUTE_CATEGORY
,ItemsE0.ATTRIBUTE1 RES_ITEM_ATTRIBUTE1
,ItemsE0.ATTRIBUTE2 RES_ITEM_ATTRIBUTE2
,ItemsE0.ATTRIBUTE3 RES_ITEM_ATTRIBUTE3
,ItemsE0.ATTRIBUTE4 RES_ITEM_ATTRIBUTE4
,ItemsE0.ATTRIBUTE5 RES_ITEM_ATTRIBUTE5
,ItemsE0.ATTRIBUTE6 RES_ITEM_ATTRIBUTE6
,ItemsE0.ATTRIBUTE7 RES_ITEM_ATTRIBUTE7
,ItemsE0.ATTRIBUTE8 RES_ITEM_ATTRIBUTE8
,ItemsE0.ATTRIBUTE9 RES_ITEM_ATTRIBUTE9
,ItemsE0.ATTRIBUTE10 RES_ITEM_ATTRIBUTE10
,ItemsE0.ATTRIBUTE11 RES_ITEM_ATTRIBUTE11
,ItemsE0.ATTRIBUTE12 RES_ITEM_ATTRIBUTE12
,ItemsE0.ATTRIBUTE13 RES_ITEM_ATTRIBUTE13
,ItemsE0.ATTRIBUTE14 RES_ITEM_ATTRIBUTE14
,ItemsE0.ATTRIBUTE15 RES_ITEM_ATTRIBUTE15
,PoLinesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,PoLinesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,PoLinesE0.CREATED_BY RSC_CREATED_BY
,PoLinesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,PoHeadersE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PO_HEADERS_ALL PoHeadersE0
,PO_LINES_ALL PoLinesE0
,PO_LINE_LOCATIONS_ALL PoLocationsE0
,EGP_SYSTEM_ITEMS_VL ItemsE0
WHERE PoHeadersE0.PO_HEADER_ID = PoLinesE0.PO_HEADER_ID
AND PoLinesE0.ITEM_ID = ItemsE0.INVENTORY_ITEM_ID
AND PoLocationsE0.SHIP_TO_ORGANIZATION_ID = ItemsE0.ORGANIZATION_ID
AND PoLinesE0.LINE_STATUS = 'OPEN'
AND NVL(PoHeadersE0.APPROVED_FLAG,'N') = 'Y'
AND PoHeadersE0.TYPE_LOOKUP_CODE = 'STANDARD' --Only PO
AND PoHeadersE0.DOCUMENT_STATUS = 'OPEN' --PO Header status
AND (SELECT SUM(QUANTITY) - SUM(QUANTITY_BILLED)
	FROM PO_LINE_LOCATIONS_ALL
	WHERE PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND PO_LINE_ID = PoLinesE0.PO_LINE_ID
	) > 0
	
UNION

SELECT PoLinesE0.PO_LINE_ID RES_INTERFACE_LINE_KEY
,PoHeadersE0.PO_HEADER_ID RES_INTERFACE_HEADER_KEY
,'ADD' RES_ACTION
,PoLinesE0.LINE_NUM RES_LINE
,(SELECT LINE_TYPE
	FROM PO_LINE_TYPES_TL
	WHERE LINE_TYPE_ID = PoLinesE0.LINE_TYPE_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_LINE_TYPE
,NULL RES_ITEM
,REPLACE(PoLinesE0.ITEM_DESCRIPTION,chr(10),' ') RES_ITEM_DESCRIPTION
,PoLinesE0.ITEM_REVISION RES_ITEM_REVISION
,(SELECT CATEGORY_NAME
	FROM EGP_CATEGORIES_TL
	WHERE CATEGORY_ID = PoLinesE0.CATEGORY_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_CATEGORY_NAME
,PoLinesE0.AMOUNT RES_AMOUNT
--,PoLinesE0.QUANTITY RES_QUANTITY
,(SELECT SUM(QUANTITY) - SUM(QUANTITY_BILLED)
	FROM PO_LINE_LOCATIONS_ALL
	WHERE PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND PO_LINE_ID = PoLinesE0.PO_LINE_ID
	) RES_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLinesE0.UOM_CODE
	) RES_UOM
,PoLinesE0.UNIT_PRICE RES_PRICE
,PoLinesE0.SECONDARY_QUANTITY RES_SECONDARY_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLinesE0.SECONDARY_UOM_CODE
	) RES_SECONDARY_UOM
,PoLinesE0.VENDOR_PRODUCT_NUM RES_SUPPLIER_ITEM --????
,PoLinesE0.NEGOTIATED_BY_PREPARER_FLAG RES_NEGOTIATED
,(SELECT HAZARD_CLASS
	FROM PO_HAZARD_CLASSES_TL
	WHERE HAZARD_CLASS_ID = PoLinesE0.HAZARD_CLASS_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_HAZARD_CLASS
,(SELECT UN_NUMBER
	FROM PO_UN_NUMBERS_TL
	WHERE UN_NUMBER_ID = PoLinesE0.UN_NUMBER_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_UN_NUMBER
,PoLinesE0.NOTE_TO_VENDOR RES_NOTE_TO_SUPPLIER
,'' RES_NOTE_TO_RECEIVER
,PoLinesE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,PoLinesE0.ATTRIBUTE1 RES_ATTRIBUTE1
,PoLinesE0.ATTRIBUTE2 RES_ATTRIBUTE2
,PoLinesE0.ATTRIBUTE3 RES_ATTRIBUTE3
,PoLinesE0.ATTRIBUTE4 RES_ATTRIBUTE4
,PoLinesE0.ATTRIBUTE5 RES_ATTRIBUTE5
,PoLinesE0.ATTRIBUTE6 RES_ATTRIBUTE6
,PoLinesE0.ATTRIBUTE7 RES_ATTRIBUTE7
,PoLinesE0.ATTRIBUTE8 RES_ATTRIBUTE8
,PoLinesE0.ATTRIBUTE9 RES_ATTRIBUTE9
,PoLinesE0.ATTRIBUTE10 RES_ATTRIBUTE10
,PoLinesE0.ATTRIBUTE11 RES_ATTRIBUTE11
,PoLinesE0.ATTRIBUTE12 RES_ATTRIBUTE12
,PoLinesE0.ATTRIBUTE13 RES_ATTRIBUTE13
,PoLinesE0.ATTRIBUTE14 RES_ATTRIBUTE14
,PoLinesE0.ATTRIBUTE15 RES_ATTRIBUTE15
,PoLinesE0.ATTRIBUTE16 RES_ATTRIBUTE16
,PoLinesE0.ATTRIBUTE17 RES_ATTRIBUTE17
,PoLinesE0.ATTRIBUTE18 RES_ATTRIBUTE18
,PoLinesE0.ATTRIBUTE19 RES_ATTRIBUTE19
,PoLinesE0.ATTRIBUTE20 RES_ATTRIBUTE20
,PoLinesE0.ATTRIBUTE_DATE1 RES_ATTRIBUTE_DATE1
,PoLinesE0.ATTRIBUTE_DATE2 RES_ATTRIBUTE_DATE2
,PoLinesE0.ATTRIBUTE_DATE3 RES_ATTRIBUTE_DATE3
,PoLinesE0.ATTRIBUTE_DATE4 RES_ATTRIBUTE_DATE4
,PoLinesE0.ATTRIBUTE_DATE5 RES_ATTRIBUTE_DATE5
,PoLinesE0.ATTRIBUTE_DATE6 RES_ATTRIBUTE_DATE6
,PoLinesE0.ATTRIBUTE_DATE7 RES_ATTRIBUTE_DATE7
,PoLinesE0.ATTRIBUTE_DATE8 RES_ATTRIBUTE_DATE8
,PoLinesE0.ATTRIBUTE_DATE9 RES_ATTRIBUTE_DATE9
,PoLinesE0.ATTRIBUTE_DATE10 RES_ATTRIBUTE_DATE10
,PoLinesE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,PoLinesE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,PoLinesE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,PoLinesE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,PoLinesE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,PoLinesE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,PoLinesE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,PoLinesE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,PoLinesE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,PoLinesE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,PoLinesE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,PoLinesE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,PoLinesE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,PoLinesE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,PoLinesE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,PoLinesE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,PoLinesE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,PoLinesE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,PoLinesE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,PoLinesE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,NULL RES_UNIT_WEIGHT
,NULL RES_WEIGHT_UOM
,NULL RES_WEIGHT_UOM_NAME
,NULL RES_UNIT_VOLUMN
,NULL RES_VOLUME_UOM
,NULL RES_VOLUME_UOM_NAME
,'' RES_TEMPLATE_NAME
,NULL RES_ITEM_ATTRIBUTE_CATEGORY
,NULL RES_ITEM_ATTRIBUTE1
,NULL RES_ITEM_ATTRIBUTE2
,NULL RES_ITEM_ATTRIBUTE3
,NULL RES_ITEM_ATTRIBUTE4
,NULL RES_ITEM_ATTRIBUTE5
,NULL RES_ITEM_ATTRIBUTE6
,NULL RES_ITEM_ATTRIBUTE7
,NULL RES_ITEM_ATTRIBUTE8
,NULL RES_ITEM_ATTRIBUTE9
,NULL RES_ITEM_ATTRIBUTE10
,NULL RES_ITEM_ATTRIBUTE11
,NULL RES_ITEM_ATTRIBUTE12
,NULL RES_ITEM_ATTRIBUTE13
,NULL RES_ITEM_ATTRIBUTE14
,NULL RES_ITEM_ATTRIBUTE15
,PoLinesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,PoLinesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,PoLinesE0.CREATED_BY RSC_CREATED_BY
,PoLinesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,PoHeadersE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PO_HEADERS_ALL PoHeadersE0
,PO_LINES_ALL PoLinesE0
WHERE PoHeadersE0.PO_HEADER_ID = PoLinesE0.PO_HEADER_ID
AND PoLinesE0.ITEM_ID IS NULL
/*AND PoLinesE0.ITEM_ID = ItemsE0.INVENTORY_ITEM_ID(+)
AND PoLinesE0.PRC_BU_ID = ItemsE0.ORGANIZATION_ID(+)*/
AND PoLinesE0.LINE_STATUS = 'OPEN'
AND NVL(PoHeadersE0.APPROVED_FLAG,'N') = 'Y'
AND PoHeadersE0.TYPE_LOOKUP_CODE = 'STANDARD' --Only PO
AND PoHeadersE0.DOCUMENT_STATUS = 'OPEN' --PO Header status
AND ((SELECT SUM(QUANTITY) - SUM(QUANTITY_BILLED)
		FROM PO_LINE_LOCATIONS_ALL
		WHERE PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
		AND PO_LINE_ID = PoLinesE0.PO_LINE_ID) > 0
	/*OR 
	(SELECT PoLinesE0.AMOUNT - NVL(SUM(invLines.AMOUNT),0)
		FROM PO_LINE_LOCATIONS_ALL poLocs
		,AP_INVOICE_LINES_ALL invLines
		WHERE poLocs.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
		AND poLocs.PO_LINE_ID = PoLinesE0.PO_LINE_ID
		AND poLocs.DESTINATION_TYPE_CODE = 'EXPENSE'
		AND poLocs.PO_HEADER_ID = invLines.PO_HEADER_ID(+)
		AND poLocs.PO_LINE_ID = invLines.PO_LINE_ID(+)
		AND invLines.LINE_TYPE_LOOKUP_CODE(+) = 'TAX') > 0*/
	)

UNION

--PO LINE that have type as 'Expence' defy that line as for 'Service' which associate with AP invoice. (For amount remaining)
SELECT PoLinesE0.PO_LINE_ID RES_INTERFACE_LINE_KEY
,PoHeadersE0.PO_HEADER_ID RES_INTERFACE_HEADER_KEY
,'ADD' RES_ACTION
,PoLinesE0.LINE_NUM RES_LINE
,(SELECT LINE_TYPE
	FROM PO_LINE_TYPES_TL
	WHERE LINE_TYPE_ID = PoLinesE0.LINE_TYPE_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_LINE_TYPE
,NULL RES_ITEM
,REPLACE(PoLinesE0.ITEM_DESCRIPTION,chr(10),' ') RES_ITEM_DESCRIPTION
,PoLinesE0.ITEM_REVISION RES_ITEM_REVISION
,(SELECT CATEGORY_NAME
	FROM EGP_CATEGORIES_TL
	WHERE CATEGORY_ID = PoLinesE0.CATEGORY_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_CATEGORY_NAME
	
,(SELECT PoLinesE0.AMOUNT - NVL(SUM(invLines.AMOUNT),0) 
	FROM AP_INVOICES_ALL inv
	,AP_INVOICE_LINES_ALL invLines
	WHERE inv.INVOICE_ID = invLines.INVOICE_ID
	--AND inv.PAYMENT_STATUS_FLAG IN ('P','Y')
	AND invLines.LINE_TYPE_LOOKUP_CODE != 'TAX'
	AND invLines.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND invLines.PO_LINE_ID = PoLinesE0.PO_LINE_ID
	) RES_AMOUNT


,PoLinesE0.QUANTITY RES_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLinesE0.UOM_CODE
	) RES_UOM
,PoLinesE0.UNIT_PRICE RES_PRICE
,PoLinesE0.SECONDARY_QUANTITY RES_SECONDARY_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLinesE0.SECONDARY_UOM_CODE
	) RES_SECONDARY_UOM
,PoLinesE0.VENDOR_PRODUCT_NUM RES_SUPPLIER_ITEM --????
,PoLinesE0.NEGOTIATED_BY_PREPARER_FLAG RES_NEGOTIATED
,(SELECT HAZARD_CLASS
	FROM PO_HAZARD_CLASSES_TL
	WHERE HAZARD_CLASS_ID = PoLinesE0.HAZARD_CLASS_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_HAZARD_CLASS
,(SELECT UN_NUMBER
	FROM PO_UN_NUMBERS_TL
	WHERE UN_NUMBER_ID = PoLinesE0.UN_NUMBER_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_UN_NUMBER
,PoLinesE0.NOTE_TO_VENDOR RES_NOTE_TO_SUPPLIER
,'' RES_NOTE_TO_RECEIVER
,PoLinesE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,PoLinesE0.ATTRIBUTE1 RES_ATTRIBUTE1
,PoLinesE0.ATTRIBUTE2 RES_ATTRIBUTE2
,PoLinesE0.ATTRIBUTE3 RES_ATTRIBUTE3
,PoLinesE0.ATTRIBUTE4 RES_ATTRIBUTE4
,PoLinesE0.ATTRIBUTE5 RES_ATTRIBUTE5
,PoLinesE0.ATTRIBUTE6 RES_ATTRIBUTE6
,PoLinesE0.ATTRIBUTE7 RES_ATTRIBUTE7
,PoLinesE0.ATTRIBUTE8 RES_ATTRIBUTE8
,PoLinesE0.ATTRIBUTE9 RES_ATTRIBUTE9
,PoLinesE0.ATTRIBUTE10 RES_ATTRIBUTE10
,PoLinesE0.ATTRIBUTE11 RES_ATTRIBUTE11
,PoLinesE0.ATTRIBUTE12 RES_ATTRIBUTE12
,PoLinesE0.ATTRIBUTE13 RES_ATTRIBUTE13
,PoLinesE0.ATTRIBUTE14 RES_ATTRIBUTE14
,PoLinesE0.ATTRIBUTE15 RES_ATTRIBUTE15
,PoLinesE0.ATTRIBUTE16 RES_ATTRIBUTE16
,PoLinesE0.ATTRIBUTE17 RES_ATTRIBUTE17
,PoLinesE0.ATTRIBUTE18 RES_ATTRIBUTE18
,PoLinesE0.ATTRIBUTE19 RES_ATTRIBUTE19
,PoLinesE0.ATTRIBUTE20 RES_ATTRIBUTE20
,PoLinesE0.ATTRIBUTE_DATE1 RES_ATTRIBUTE_DATE1
,PoLinesE0.ATTRIBUTE_DATE2 RES_ATTRIBUTE_DATE2
,PoLinesE0.ATTRIBUTE_DATE3 RES_ATTRIBUTE_DATE3
,PoLinesE0.ATTRIBUTE_DATE4 RES_ATTRIBUTE_DATE4
,PoLinesE0.ATTRIBUTE_DATE5 RES_ATTRIBUTE_DATE5
,PoLinesE0.ATTRIBUTE_DATE6 RES_ATTRIBUTE_DATE6
,PoLinesE0.ATTRIBUTE_DATE7 RES_ATTRIBUTE_DATE7
,PoLinesE0.ATTRIBUTE_DATE8 RES_ATTRIBUTE_DATE8
,PoLinesE0.ATTRIBUTE_DATE9 RES_ATTRIBUTE_DATE9
,PoLinesE0.ATTRIBUTE_DATE10 RES_ATTRIBUTE_DATE10
,PoLinesE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,PoLinesE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,PoLinesE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,PoLinesE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,PoLinesE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,PoLinesE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,PoLinesE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,PoLinesE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,PoLinesE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,PoLinesE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,PoLinesE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,PoLinesE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,PoLinesE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,PoLinesE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,PoLinesE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,PoLinesE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,PoLinesE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,PoLinesE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,PoLinesE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,PoLinesE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,NULL RES_UNIT_WEIGHT
,NULL RES_WEIGHT_UOM
,NULL RES_WEIGHT_UOM_NAME
,NULL RES_UNIT_VOLUMN
,NULL RES_VOLUME_UOM
,NULL RES_VOLUME_UOM_NAME
,'' RES_TEMPLATE_NAME
,NULL RES_ITEM_ATTRIBUTE_CATEGORY
,NULL RES_ITEM_ATTRIBUTE1
,NULL RES_ITEM_ATTRIBUTE2
,NULL RES_ITEM_ATTRIBUTE3
,NULL RES_ITEM_ATTRIBUTE4
,NULL RES_ITEM_ATTRIBUTE5
,NULL RES_ITEM_ATTRIBUTE6
,NULL RES_ITEM_ATTRIBUTE7
,NULL RES_ITEM_ATTRIBUTE8
,NULL RES_ITEM_ATTRIBUTE9
,NULL RES_ITEM_ATTRIBUTE10
,NULL RES_ITEM_ATTRIBUTE11
,NULL RES_ITEM_ATTRIBUTE12
,NULL RES_ITEM_ATTRIBUTE13
,NULL RES_ITEM_ATTRIBUTE14
,NULL RES_ITEM_ATTRIBUTE15
,PoLinesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,PoLinesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,PoLinesE0.CREATED_BY RSC_CREATED_BY
,PoLinesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,PoHeadersE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PO_HEADERS_ALL PoHeadersE0
,PO_LINES_ALL PoLinesE0

WHERE PoHeadersE0.PO_HEADER_ID = PoLinesE0.PO_HEADER_ID
AND PoLinesE0.ITEM_ID IS NULL
/*AND PoLinesE0.ITEM_ID = ItemsE0.INVENTORY_ITEM_ID(+)
AND PoLinesE0.PRC_BU_ID = ItemsE0.ORGANIZATION_ID(+)*/
AND PoLinesE0.LINE_STATUS = 'OPEN'
AND NVL(PoHeadersE0.APPROVED_FLAG,'N') = 'Y'
AND PoHeadersE0.TYPE_LOOKUP_CODE = 'STANDARD' --Only PO
AND PoHeadersE0.DOCUMENT_STATUS = 'OPEN' --PO Header status

AND EXISTS (SELECT 1 FROM PO_LINE_LOCATIONS_ALL 
	WHERE PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID 
	AND PO_LINE_ID = PoLinesE0.PO_LINE_ID 
	AND DESTINATION_TYPE_CODE = 'EXPENSE')
	
AND (SELECT PoLinesE0.AMOUNT - NVL(SUM(invLines.AMOUNT),0) 
	FROM AP_INVOICES_ALL inv
	,AP_INVOICE_LINES_ALL invLines
	WHERE inv.INVOICE_ID = invLines.INVOICE_ID
	--AND inv.PAYMENT_STATUS_FLAG IN ('P','Y')
	AND invLines.LINE_TYPE_LOOKUP_CODE != 'TAX'
	AND invLines.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND invLines.PO_LINE_ID = PoLinesE0.PO_LINE_ID
	) > 0

/*AND ((SELECT SUM(QUANTITY) - SUM(QUANTITY_BILLED)
		FROM PO_LINE_LOCATIONS_ALL
		WHERE PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
		AND PO_LINE_ID = PoLinesE0.PO_LINE_ID) > 0
	OR 
	(SELECT PoLinesE0.AMOUNT - NVL(SUM(invLines.AMOUNT),0)
		FROM PO_LINE_LOCATIONS_ALL poLocs
		,AP_INVOICE_LINES_ALL invLines
		WHERE poLocs.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
		AND poLocs.PO_LINE_ID = PoLinesE0.PO_LINE_ID
		AND poLocs.DESTINATION_TYPE_CODE = 'EXPENSE'
		AND poLocs.PO_HEADER_ID = invLines.PO_HEADER_ID(+)
		AND poLocs.PO_LINE_ID = invLines.PO_LINE_ID(+)
		AND invLines.LINE_TYPE_LOOKUP_CODE(+) = 'TAX') > 0
	)*/
	
	
UNION

--PO LINE that have type as 'Expence' defy that line as for 'Service' which associate with AP invoice. (For amount remaining)
SELECT PoLinesE0.PO_LINE_ID RES_INTERFACE_LINE_KEY
,PoHeadersE0.PO_HEADER_ID RES_INTERFACE_HEADER_KEY
,'ADD' RES_ACTION
,PoLinesE0.LINE_NUM RES_LINE
,(SELECT LINE_TYPE
	FROM PO_LINE_TYPES_TL
	WHERE LINE_TYPE_ID = PoLinesE0.LINE_TYPE_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_LINE_TYPE
,NULL RES_ITEM
,REPLACE(PoLinesE0.ITEM_DESCRIPTION,chr(10),' ') RES_ITEM_DESCRIPTION
,PoLinesE0.ITEM_REVISION RES_ITEM_REVISION
,(SELECT CATEGORY_NAME
	FROM EGP_CATEGORIES_TL
	WHERE CATEGORY_ID = PoLinesE0.CATEGORY_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_CATEGORY_NAME
	
,PoLinesE0.AMOUNT RES_AMOUNT

,PoLinesE0.QUANTITY RES_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLinesE0.UOM_CODE
	) RES_UOM
,PoLinesE0.UNIT_PRICE RES_PRICE
,PoLinesE0.SECONDARY_QUANTITY RES_SECONDARY_QUANTITY
,(SELECT UNIT_OF_MEASURE
	FROM INV_UNITS_OF_MEASURE_VL
	WHERE UOM_CODE = PoLinesE0.SECONDARY_UOM_CODE
	) RES_SECONDARY_UOM
,PoLinesE0.VENDOR_PRODUCT_NUM RES_SUPPLIER_ITEM --????
,PoLinesE0.NEGOTIATED_BY_PREPARER_FLAG RES_NEGOTIATED
,(SELECT HAZARD_CLASS
	FROM PO_HAZARD_CLASSES_TL
	WHERE HAZARD_CLASS_ID = PoLinesE0.HAZARD_CLASS_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_HAZARD_CLASS
,(SELECT UN_NUMBER
	FROM PO_UN_NUMBERS_TL
	WHERE UN_NUMBER_ID = PoLinesE0.UN_NUMBER_ID
	AND LANGUAGE = USERENV('LANG')
	) RES_UN_NUMBER
,PoLinesE0.NOTE_TO_VENDOR RES_NOTE_TO_SUPPLIER
,'' RES_NOTE_TO_RECEIVER
,PoLinesE0.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,PoLinesE0.ATTRIBUTE1 RES_ATTRIBUTE1
,PoLinesE0.ATTRIBUTE2 RES_ATTRIBUTE2
,PoLinesE0.ATTRIBUTE3 RES_ATTRIBUTE3
,PoLinesE0.ATTRIBUTE4 RES_ATTRIBUTE4
,PoLinesE0.ATTRIBUTE5 RES_ATTRIBUTE5
,PoLinesE0.ATTRIBUTE6 RES_ATTRIBUTE6
,PoLinesE0.ATTRIBUTE7 RES_ATTRIBUTE7
,PoLinesE0.ATTRIBUTE8 RES_ATTRIBUTE8
,PoLinesE0.ATTRIBUTE9 RES_ATTRIBUTE9
,PoLinesE0.ATTRIBUTE10 RES_ATTRIBUTE10
,PoLinesE0.ATTRIBUTE11 RES_ATTRIBUTE11
,PoLinesE0.ATTRIBUTE12 RES_ATTRIBUTE12
,PoLinesE0.ATTRIBUTE13 RES_ATTRIBUTE13
,PoLinesE0.ATTRIBUTE14 RES_ATTRIBUTE14
,PoLinesE0.ATTRIBUTE15 RES_ATTRIBUTE15
,PoLinesE0.ATTRIBUTE16 RES_ATTRIBUTE16
,PoLinesE0.ATTRIBUTE17 RES_ATTRIBUTE17
,PoLinesE0.ATTRIBUTE18 RES_ATTRIBUTE18
,PoLinesE0.ATTRIBUTE19 RES_ATTRIBUTE19
,PoLinesE0.ATTRIBUTE20 RES_ATTRIBUTE20
,PoLinesE0.ATTRIBUTE_DATE1 RES_ATTRIBUTE_DATE1
,PoLinesE0.ATTRIBUTE_DATE2 RES_ATTRIBUTE_DATE2
,PoLinesE0.ATTRIBUTE_DATE3 RES_ATTRIBUTE_DATE3
,PoLinesE0.ATTRIBUTE_DATE4 RES_ATTRIBUTE_DATE4
,PoLinesE0.ATTRIBUTE_DATE5 RES_ATTRIBUTE_DATE5
,PoLinesE0.ATTRIBUTE_DATE6 RES_ATTRIBUTE_DATE6
,PoLinesE0.ATTRIBUTE_DATE7 RES_ATTRIBUTE_DATE7
,PoLinesE0.ATTRIBUTE_DATE8 RES_ATTRIBUTE_DATE8
,PoLinesE0.ATTRIBUTE_DATE9 RES_ATTRIBUTE_DATE9
,PoLinesE0.ATTRIBUTE_DATE10 RES_ATTRIBUTE_DATE10
,PoLinesE0.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,PoLinesE0.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,PoLinesE0.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,PoLinesE0.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,PoLinesE0.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,PoLinesE0.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,PoLinesE0.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,PoLinesE0.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,PoLinesE0.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,PoLinesE0.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,PoLinesE0.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,PoLinesE0.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,PoLinesE0.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,PoLinesE0.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,PoLinesE0.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,PoLinesE0.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,PoLinesE0.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,PoLinesE0.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,PoLinesE0.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,PoLinesE0.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,NULL RES_UNIT_WEIGHT
,NULL RES_WEIGHT_UOM
,NULL RES_WEIGHT_UOM_NAME
,NULL RES_UNIT_VOLUMN
,NULL RES_VOLUME_UOM
,NULL RES_VOLUME_UOM_NAME
,'' RES_TEMPLATE_NAME
,NULL RES_ITEM_ATTRIBUTE_CATEGORY
,NULL RES_ITEM_ATTRIBUTE1
,NULL RES_ITEM_ATTRIBUTE2
,NULL RES_ITEM_ATTRIBUTE3
,NULL RES_ITEM_ATTRIBUTE4
,NULL RES_ITEM_ATTRIBUTE5
,NULL RES_ITEM_ATTRIBUTE6
,NULL RES_ITEM_ATTRIBUTE7
,NULL RES_ITEM_ATTRIBUTE8
,NULL RES_ITEM_ATTRIBUTE9
,NULL RES_ITEM_ATTRIBUTE10
,NULL RES_ITEM_ATTRIBUTE11
,NULL RES_ITEM_ATTRIBUTE12
,NULL RES_ITEM_ATTRIBUTE13
,NULL RES_ITEM_ATTRIBUTE14
,NULL RES_ITEM_ATTRIBUTE15
,PoLinesE0.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,PoLinesE0.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,PoLinesE0.CREATED_BY RSC_CREATED_BY
,PoLinesE0.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,PoHeadersE0.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM PO_HEADERS_ALL PoHeadersE0
,PO_LINES_ALL PoLinesE0

/*,AP_INVOICES_ALL inv
,AP_INVOICE_LINES_ALL invLines*/

WHERE PoHeadersE0.PO_HEADER_ID = PoLinesE0.PO_HEADER_ID
AND PoLinesE0.ITEM_ID IS NULL
/*AND PoLinesE0.ITEM_ID = ItemsE0.INVENTORY_ITEM_ID(+)
AND PoLinesE0.PRC_BU_ID = ItemsE0.ORGANIZATION_ID(+)*/
AND PoLinesE0.LINE_STATUS = 'OPEN'
AND NVL(PoHeadersE0.APPROVED_FLAG,'N') = 'Y'
AND PoHeadersE0.TYPE_LOOKUP_CODE = 'STANDARD' --Only PO
AND PoHeadersE0.DOCUMENT_STATUS = 'OPEN' --PO Header status

/*AND inv.INVOICE_ID = invLines.INVOICE_ID
AND inv.PAYMENT_STATUS_FLAG IN ('P','Y')
AND invLines.LINE_TYPE_LOOKUP_CODE != 'TAX'
AND invLines.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
AND invLines.PO_LINE_ID = PoLinesE0.PO_LINE_ID
AND PoLinesE0.AMOUNT - NVL(SUM(invLines.AMOUNT),0) > 0*/

AND EXISTS (SELECT 1 FROM PO_LINE_LOCATIONS_ALL 
	WHERE PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID 
	AND PO_LINE_ID = PoLinesE0.PO_LINE_ID 
	AND DESTINATION_TYPE_CODE = 'EXPENSE')

	
AND NOT EXISTS (SELECT 1
	FROM AP_INVOICES_ALL inv
	,AP_INVOICE_LINES_ALL invLines
	WHERE inv.INVOICE_ID = invLines.INVOICE_ID
	--AND inv.PAYMENT_STATUS_FLAG IN ('P','Y')
	AND invLines.LINE_TYPE_LOOKUP_CODE != 'TAX'
	AND invLines.PO_HEADER_ID = PoHeadersE0.PO_HEADER_ID
	AND invLines.PO_LINE_ID = PoLinesE0.PO_LINE_ID
	)