/* ****************************************************************************
 * $Revision: 53543 $:
 * $Author: pisan.jariyasettachok $:
 * $Date: 2016-03-15 15:46:40 +0700 (Tue, 15 Mar 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.12/trunk/core/reverse_sql/FINANCIALS/Specify%20Supplier%20Numbering%20-%20Specify%20Supplier%20Numbering.sql $:
 * $Id: Specify Supplier Numbering - Specify Supplier Numbering.sql 53543 2016-03-15 08:46:40Z pisan.jariyasettachok $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */
 

WITH MAX_ROOT AS (SELECT TREE_CODE
	,TREE_VERSION_ID
    ,MAX(DEPTH) MAX_DEPTH
	FROM FND_TREE_NODE
	GROUP BY TREE_CODE
	,TREE_VERSION_ID)
,SET_TOTAL_PARENT AS (SELECT 30 MAX_PARENT FROM DUAL)

SELECT FndTreeNodeEO.PK2_START_VALUE RES_VALUE_SET_CODE
,FndTreeEO.TREE_CODE RES_TREE_CODE
,FndTreeVersionEO.TREE_VERSION_NAME RES_TREE_VERSION_NAME
,TO_CHAR(FndTreeVersionEO.EFFECTIVE_START_DATE,'YYYY/MM/DD') RES_TREE_VERSION_START_DATE
,DECODE(TO_CHAR(FndTreeVersionEO.EFFECTIVE_END_DATE,'YYYY/MM/DD'),'4712/12/31',NULL,TO_CHAR(FndTreeVersionEO.EFFECTIVE_END_DATE,'YYYY/MM/DD')) RES_TREE_VERSION_END_DATE
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 30) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT30
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 29) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT29
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 28) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT28
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 27) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT27
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 26) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT26
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 25) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT25
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 24) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT24
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 23) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT23
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 22) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT22
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 21) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT21
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 20) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT20
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 19) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT19
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 18) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT18
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 17) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT17
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 16) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT16
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 15) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT15
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 14) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT14
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 13) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT13
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 12) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT12
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 11) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT11
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 10) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT10
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 9) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT9
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 8) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT8
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 7) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT7
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 6) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT6
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 5) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT5
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 4) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT4
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 3) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT3
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 2) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT2
,(CASE 
    WHEN ((MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 1) ) THEN
        FndTreeNodeEO.PK1_START_VALUE
    END) RES_PARENT1
,(CASE
    WHEN CONNECT_BY_ISLEAF = 1 AND FndTreeNodeEO.CHILD_COUNT = 0 THEN 
		(CASE
			WHEN (MAX_ROOT.MAX_DEPTH - (LEVEL - 1) = 0) THEN
				FndTreeNodeEO.PK1_START_VALUE 
			END)
    END) RES_VALUE
,(SELECT FndLableVlE0.LABEL_NAME
	FROM FND_TREE_LABEL FndTreeLabelE0
	,FND_LABEL_VL FndLableVlE0
	WHERE FndTreeLabelE0.TREE_STRUCTURE_CODE = FndLableVlE0.TREE_STRUCTURE_CODE
	AND FndTreeLabelE0.DATA_SOURCE_ID = FndLableVlE0.DATA_SOURCE_ID
	AND FndTreeLabelE0.LABEL_PK3_VALUE = FndLableVlE0.LABEL_ID
	AND FndTreeNodeEO.TREE_STRUCTURE_CODE = FndLableVlE0.TREE_STRUCTURE_CODE
	AND FndTreeNodeEO.TREE_CODE = FndTreeLabelE0.TREE_CODE
	AND FndTreeNodeEO.TREE_LABEL_ID = FndTreeLabelE0.TREE_LABEL_ID
	) RES_LABEL_SHORT_NAME
,FndTreeNodeEO.LAST_UPDATED_BY   RSC_LAST_UPDATED_BY
,FndTreeNodeEO.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,FndTreeNodeEO.CREATED_BY RSC_CREATED_BY
,FndTreeNodeEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,NULL RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM FND_TREE_VL FndTreeEO
,FND_TREE_VERSION_VL FndTreeVersionEO
,FND_TREE_NODE FndTreeNodeEO
,MAX_ROOT
,SET_TOTAL_PARENT
WHERE FndTreeEO.Tree_code = FndTreeVersionEO.tree_code
AND FndTreeVersionEO.TREE_STRUCTURE_CODE = 'GL_ACCT_FLEX'
AND FndTreeVersionEO.TREE_STRUCTURE_CODE = FndTreeNodeEO.TREE_STRUCTURE_CODE
AND FndTreeVersionEO.TREE_VERSION_ID = FndTreeNodeEO.TREE_VERSION_ID

and (CHILD_COUNT = 0  OR (CHILD_COUNT > 0 and LEVEL <= MAX_PARENT )   )

AND FndTreeNodeEO.TREE_CODE = MAX_ROOT.TREE_CODE
AND FndTreeNodeEO.TREE_VERSION_ID = MAX_ROOT.TREE_VERSION_ID

AND FndTreeNodeEO.PK1_END_VALUE IS NULL
AND FndTreeNodeEO.REFERENCE_TREE_CODE IS NULL

START WITH NVL(FndTreeNodeEO.PARENT_TREE_NODE_ID,'1') = '1'
CONNECT BY PRIOR FndTreeNodeEO.TREE_NODE_ID = FndTreeNodeEO.PARENT_TREE_NODE_ID
AND PRIOR FndTreeNodeEO.DATA_SOURCE_ID = FndTreeNodeEO.PARENT_DATA_SOURCE_ID
ORDER SIBLINGS BY FNDTREEEO.TREE_NAME
,FndTreeVersionEO.TREE_VERSION_NAME