/* ****************************************************************************
 * $Revision:  $:
 * $Author: Nasrullah.Dusenmahamad $:
 * $Date: 2017-09-12  $:
 * $HeadURL: $:
 * $Id: Manage Suppliers - Supplier Sites.sql  $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

-- RSC_PREREQUISITE_OBJECTS=POZ_SUPPLIER_SITES_ALL_M
-- STRICTLY_BATCH_SEQ = RES_SUPPLIER_NAME,RES_PROCUREMENT_BU,RES_SUPPLIER_SITE

SELECT 'CREATE' RES_IMPORT_ACTION
,(SELECT PersonParty.PARTY_NAME 
	FROM HZ_PARTIES PersonParty 
	,HZ_PARTY_SITES PartySitePEO
	WHERE PersonParty.PARTY_ID = PartySitePEO.PARTY_ID
	AND PartySitePEO.PARTY_SITE_ID = SupplierSiteDEO.PARTY_SITE_ID  
	) RES_SUPPLIER_NAME
,(SELECT BU_NAME 
	FROM FUN_ALL_BUSINESS_UNITS_V 
	WHERE BU_ID = SupplierSiteDEO.PRC_BU_ID  
	) RES_PROCUREMENT_BU
,PartySitePEO.PARTY_SITE_NAME RES_ADDRESS_NAME
,SupplierSiteDEO.VENDOR_SITE_CODE RES_SUPPLIER_SITE
,NULL RES_SUPPLIER_SITE_NEW
,TO_CHAR(SupplierSiteDEO.INACTIVE_DATE,'YYYY/MM/DD') RES_INACTIVE_DATE
,SupplierSiteDEO.RFQ_ONLY_SITE_FLAG RES_SOURCING_ONLY
,SupplierSiteDEO.PURCHASING_SITE_FLAG RES_PURCHASING
,SupplierSiteDEO.Pcard_site_flag RES_PROCUREMENT_CARD
,SupplierSiteDEO.PAY_SITE_FLAG RES_PAY
,SupplierSiteDEO.PRIMARY_PAY_SITE_FLAG RES_PRIMARY_PAY
,SupplierSiteDEO.TAX_REPORTING_SITE_FLAG RES_INCOME_TAX_REPORTING_SITE
,SupplierSiteDEO.VENDOR_SITE_CODE_ALT RES_ALTERNATE_SITE_NAME
,SupplierSiteDEO.CUSTOMER_NUM RES_CUSTOMER_NUMBER
,SupplierSiteDEO.B2B_COMM_METHOD_CODE RES_B2B_COMMUNICATION_METHOD
,SupplierSiteDEO.B2B_SITE_CODE RES_B2B_SUPPLIER_SITE_CODE
,SupplierSiteDEO.SUPPLIER_NOTIF_METHOD RES_COMMUNICATION_METHOD
,SupplierSiteDEO.EMAIL_ADDRESS RES_E_MAIL
,SupplierSiteDEO.FAX_COUNTRY_CODE RES_FAX_COUNTRY_CODE
,SupplierSiteDEO.FAX_AREA_CODE RES_FAX_AREA_CODE
,SupplierSiteDEO.FAX RES_FAX
,SupplierSiteDEO.PAY_ON_CODE RES_HOLD_ALL_NEW_PURCHASING_DO
,SupplierSiteDEO.PURCHASING_HOLD_REASON RES_HOLD_REASON
,PartyPEO.PARTY_NAME RES_CARRIER
,SupplierSiteDEO.MODE_OF_TRANSPORT RES_MODE_OF_TRANSPORT
,SupplierSiteDEO.SERVICE_LEVEL RES_SERVICE_LEVEL
,SupplierSiteDEO.FREIGHT_TERMS_LOOKUP_CODE RES_FREIGHT_TERMS
,SupplierSiteDEO.PAY_ON_CODE RES_PAY_ON_RECEIPT
,SupplierSiteDEO.FOB_LOOKUP_CODE RES_FOB
,SupplierSiteDEO.COUNTRY_OF_ORIGIN_CODE RES_COUNTRY_OF_ORIGIN
,(PARTYPEO.PARTY_NAME
	||DECODE(TRANSPORTLOOKUPPEO.MEANING,NULL,'','-'
	||TRANSPORTLOOKUPPEO.MEANING)
	||DECODE(ServiceLevelLookupPEO.MEANING,NULL,'','-'
	||ServiceLevelLookupPEO.MEANING)) RES_BUYER_MANAGED_TRANSPORTATI
,SupplierSiteDEO.PAY_ON_USE_FLAG RES_PAY_ON_USE
,SupplierSiteDEO.AGING_ONSET_POINT RES_AGING_ONSET_POINT
,SupplierSiteDEO.AGING_PERIOD_DAYS RES_AGING_PERIOD_DAYS
,SupplierSiteDEO.CONSUMPTION_ADVICE_FREQUENCY RES_CONSUMPTION_ADVICE_FREQUEN
,SupplierSiteDEO.CONSUMPTION_ADVICE_SUMMARY RES_CONSUMPTION_ADVICE_SUMMARY
,SupplierSiteDEO.DEFAULT_PAY_SITE_ID RES_DEFAULT_PAY_SITE
,SupplierSiteDEO.PAY_ON_RECEIPT_SUMMARY_CODE RES_INVOICE_SUMMARY_LEVEL
,SupplierSiteDEO.GAPLESS_INV_NUM_FLAG RES_GAPLESS_INVOICE_NUMBERING
,SupplierSiteDEO.SELLING_COMPANY_IDENTIFIER RES_SELLING_COMPANY_IDENTIFIER
,SupplierSiteDEO.CREATE_DEBIT_MEMO_FLAG RES_CREATE_DEBIT_MEMO_FROM_RET
,SupplierSiteDEO.ENFORCE_SHIP_TO_LOCATION_CODE RES_SHIP_TO_EXCEPTION_ACTION
,SupplierSiteDEO.RECEIVING_ROUTING_ID RES_RECEIPT_ROUTING
,SupplierSiteDEO.QTY_RCV_TOLERANCE RES_OVER_RECEIPT_TOLERANCE
,SupplierSiteDEO.Qty_rcv_exception_code RES_OVER_RECEIPT_ACTION
,SupplierSiteDEO.Days_early_receipt_allowed RES_EARLY_RECEIPT_TOLERANCE_IN
,SupplierSiteDEO.Days_late_receipt_allowed RES_LATE_RECEIPT_TOLERANCE_IN_
,SupplierSiteDEO.ALLOW_SUBSTITUTE_RECEIPTS_FLAG RES_ALLOW_SUBSTITUTE_RECEIPTS
,SupplierSiteDEO.ALLOW_UNORDERED_RECEIPTS_FLAG RES_ALLOW_UNORDERED_RECEIPTS
,SupplierSiteDEO.RECEIPT_DAYS_EXCEPTION_CODE RES_RECEIPT_DATE_EXCEPTION
,SupplierSiteDEO.INVOICE_CURRENCY_CODE RES_INVOICE_CURRENCY
,SupplierSiteDEO.INVOICE_AMOUNT_LIMIT RES_INVOICE_AMOUNT_LIMIT
,SupplierSiteDEO.MATCH_OPTION RES_INVOICE_MATCH_OPTION
,NULL RES_MATCH_APPROVAL_LEVEL 
,SupplierSiteDEO.PAYMENT_CURRENCY_CODE RES_PAYMENT_CURRENCY
,SupplierSiteDEO.PAYMENT_PRIORITY RES_PAYMENT_PRIORITY
,SupplierSiteDEO.PAY_GROUP_LOOKUP_CODE RES_PAY_GROUP
,ApInvoiceToleranceTemplates.TOLERANCE_NAME RES_QUANTITY_TOLERANCES
,ApServicesToleranceTemplates.TOLERANCE_NAME RES_AMOUNT_TOLERANCE
,SupplierSiteDEO.HOLD_ALL_PAYMENTS_FLAG RES_HOLD_ALL_INVOICES
,SupplierSiteDEO.HOLD_UNMATCHED_INVOICES_FLAG RES_HOLD_UNMATCHED_INVOICES
,SupplierSiteDEO.HOLD_FUTURE_PAYMENTS_FLAG RES_HOLD_UNVALIDATED_INVOICES
,(SELECT USERNAME
	FROM PER_USERS
	WHERE PERSON_ID = SupplierSiteDEO.hold_by 
	) RES_PAYMENT_HOLD_BY 
,TO_CHAR(SupplierSiteDEO.PAYMENT_HOLD_DATE,'YYYY/MM/DD') RES_PAYMENT_HOLD_DATE
,SupplierSiteDEO.HOLD_REASON RES_PAYMENT_HOLD_REASON
,ApTermsVl.NAME RES_PAYMENT_TERMS
,SupplierSiteDEO.TERMS_DATE_BASIS RES_TERMS_DATE_BASIS
,SupplierSiteDEO.PAY_DATE_BASIS_LOOKUP_CODE RES_PAY_DATE_BASIS
,SupplierSiteDEO.BANK_CHARGE_DEDUCTION_TYPE RES_BANK_CHARGE_DEDUCTION_TYPE
,SupplierSiteDEO.ALWAYS_TAKE_DISC_FLAG RES_ALWAYS_TAKE_DISCOUNT
,SupplierSiteDEO.EXCLUDE_FREIGHT_FROM_DISCOUNT RES_EXCLUDE_FREIGHT_FROM_DISCO
,SupplierSiteDEO.EXCLUDE_TAX_FROM_DISCOUNT RES_EXCLUDE_TAX_FROM_DISCOUNT
,SupplierSiteDEO.AUTO_CALCULATE_INTEREST_FLAG RES_CREATE_INTEREST_INVOICES     
,(SELECT ThirdPartyTaxProfileEO.TAX_CLASSIFICATION_CODE 
	FROM HZ_PARTIES PersonParty 
	,HZ_PARTY_SITES PartySitePEO
	,ZX_PARTY_TAX_PROFILE ThirdPartyTaxProfileEO  
	WHERE PersonParty.PARTY_ID = PartySitePEO.PARTY_ID
	AND PartySitePEO.PARTY_SITE_ID = SupplierSiteDEO.PARTY_SITE_ID
	AND ThirdPartyTaxProfileEO.party_id = PersonParty.PARTY_id
    ) RES_VAT_CODE
,(SELECT ZxPartyTaxProfile.REP_REGISTRATION_NUMBER
	FROM ZX_PARTY_TAX_PROFILE ZxPartyTaxProfile 
	,HZ_PARTY_SITES PartySitePEO
    WHERE ZxPartyTaxProfile.party_id = PartySitePEO.PARTY_ID
	AND PartySitePEO.PARTY_SITE_ID = SupplierSiteDEO.PARTY_SITE_ID
   ) RES_TAX_REGISTRATION_NUMBER
,(SELECT pmthds.payment_method_code
	FROM IBY_PAYMENT_METHODS_VL pmthds
	WHERE pmthds.payment_method_code = (SELECT payment_method_code
                                    FROM iby_ext_party_pmt_mthds m
                                    WHERE m.ext_pmt_party_id = IbyExternalPayeesAll.EXT_PAYEE_ID
                                    AND m.primary_flag       = 'Y'
                                    AND m.payment_function   = IbyExternalPayeesAll.payment_function) 
	) RES_PAYMENT_METHOD
,IbyExternalPayeesAll.DELIVERY_CHANNEL_CODE RES_DELIVERY_CHANNEL
,IbyExternalPayeesAll.BANK_INSTRUCTION1_CODE RES_BANK_INSTRUCTION_1
,IbyExternalPayeesAll.BANK_INSTRUCTION2_CODE RES_BANK_INSTRUCTION_2
,IbyExternalPayeesAll.BANK_INSTRUCTION_DETAILS RES_BANK_INSTRUCTION
,IbyExternalPayeesAll.SETTLEMENT_PRIORITY RES_SETTLEMENT_PRIORITY
,IbyExternalPayeesAll.PAYMENT_TEXT_MESSAGE1 RES_PAYMENT_TEXT_MESSAGE_1
,IbyExternalPayeesAll.PAYMENT_TEXT_MESSAGE2 RES_PAYMENT_TEXT_MESSAGE_2
,IbyExternalPayeesAll.PAYMENT_TEXT_MESSAGE3 RES_PAYMENT_TEXT_MESSAGE_3
,IbyExternalPayeesAll.BANK_CHARGE_BEARER RES_BANK_CHARGE_BEARER
,IbyExternalPayeesAll.PAYMENT_REASON_CODE RES_PAYMENT_REASON
,IbyExternalPayeesAll.PAYMENT_REASON_COMMENTS RES_PAYMENT_REASON_COMMENTS
,IbyExternalPayeesAll.REMIT_ADVICE_DELIVERY_METHOD RES_DELIVERY_METHOD
,IbyExternalPayeesAll.REMIT_ADVICE_EMAIL RES_REMITTANCE_E_MAIL
,IbyExternalPayeesAll.REMIT_ADVICE_FAX RES_REMITTANCE_FAX
  
,SupplierSiteDEO.ATTRIBUTE_CATEGORY RES_ATTRIBUTE_CATEGORY
,SupplierSiteDEO.ATTRIBUTE1 RES_ATTRIBUTE1
,SupplierSiteDEO.ATTRIBUTE2 RES_ATTRIBUTE2
,SupplierSiteDEO.ATTRIBUTE3 RES_ATTRIBUTE3
,SupplierSiteDEO.ATTRIBUTE4 RES_ATTRIBUTE4
,SupplierSiteDEO.ATTRIBUTE5 RES_ATTRIBUTE5
,SupplierSiteDEO.ATTRIBUTE6 RES_ATTRIBUTE6
,SupplierSiteDEO.ATTRIBUTE7 RES_ATTRIBUTE7
,SupplierSiteDEO.ATTRIBUTE8 RES_ATTRIBUTE8
,SupplierSiteDEO.ATTRIBUTE9 RES_ATTRIBUTE9
,SupplierSiteDEO.ATTRIBUTE10 RES_ATTRIBUTE10
,SupplierSiteDEO.ATTRIBUTE11 RES_ATTRIBUTE11
,SupplierSiteDEO.ATTRIBUTE12 RES_ATTRIBUTE12
,SupplierSiteDEO.ATTRIBUTE13 RES_ATTRIBUTE13
,SupplierSiteDEO.ATTRIBUTE14 RES_ATTRIBUTE14
,SupplierSiteDEO.ATTRIBUTE15 RES_ATTRIBUTE15
,SupplierSiteDEO.ATTRIBUTE16 RES_ATTRIBUTE16
,SupplierSiteDEO.ATTRIBUTE17 RES_ATTRIBUTE17
,SupplierSiteDEO.ATTRIBUTE18 RES_ATTRIBUTE18
,SupplierSiteDEO.ATTRIBUTE19 RES_ATTRIBUTE19
,SupplierSiteDEO.ATTRIBUTE20 RES_ATTRIBUTE20
,SupplierSiteDEO.ATTRIBUTE_DATE1 RES_ATTRIBUTE_DATE1
,SupplierSiteDEO.ATTRIBUTE_DATE2 RES_ATTRIBUTE_DATE2
,SupplierSiteDEO.ATTRIBUTE_DATE3 RES_ATTRIBUTE_DATE3
,SupplierSiteDEO.ATTRIBUTE_DATE4 RES_ATTRIBUTE_DATE4
,SupplierSiteDEO.ATTRIBUTE_DATE5 RES_ATTRIBUTE_DATE5
,SupplierSiteDEO.ATTRIBUTE_DATE6 RES_ATTRIBUTE_DATE6
,SupplierSiteDEO.ATTRIBUTE_DATE7 RES_ATTRIBUTE_DATE7
,SupplierSiteDEO.ATTRIBUTE_DATE8 RES_ATTRIBUTE_DATE8
,SupplierSiteDEO.ATTRIBUTE_DATE9 RES_ATTRIBUTE_DATE9
,SupplierSiteDEO.ATTRIBUTE_DATE10 RES_ATTRIBUTE_DATE10
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP1 RES_ATTRIBUTE_TIMESTAMP1
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP2 RES_ATTRIBUTE_TIMESTAMP2
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP3 RES_ATTRIBUTE_TIMESTAMP3
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP4 RES_ATTRIBUTE_TIMESTAMP4
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP5 RES_ATTRIBUTE_TIMESTAMP5
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP6 RES_ATTRIBUTE_TIMESTAMP6
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP7 RES_ATTRIBUTE_TIMESTAMP7
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP8 RES_ATTRIBUTE_TIMESTAMP8
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP9 RES_ATTRIBUTE_TIMESTAMP9
,SupplierSiteDEO.ATTRIBUTE_TIMESTAMP10 RES_ATTRIBUTE_TIMESTAMP10
,SupplierSiteDEO.ATTRIBUTE_NUMBER1 RES_ATTRIBUTE_NUMBER1
,SupplierSiteDEO.ATTRIBUTE_NUMBER2 RES_ATTRIBUTE_NUMBER2
,SupplierSiteDEO.ATTRIBUTE_NUMBER3 RES_ATTRIBUTE_NUMBER3
,SupplierSiteDEO.ATTRIBUTE_NUMBER4 RES_ATTRIBUTE_NUMBER4
,SupplierSiteDEO.ATTRIBUTE_NUMBER5 RES_ATTRIBUTE_NUMBER5
,SupplierSiteDEO.ATTRIBUTE_NUMBER6 RES_ATTRIBUTE_NUMBER6
,SupplierSiteDEO.ATTRIBUTE_NUMBER7 RES_ATTRIBUTE_NUMBER7
,SupplierSiteDEO.ATTRIBUTE_NUMBER8 RES_ATTRIBUTE_NUMBER8
,SupplierSiteDEO.ATTRIBUTE_NUMBER9 RES_ATTRIBUTE_NUMBER9
,SupplierSiteDEO.ATTRIBUTE_NUMBER10 RES_ATTRIBUTE_NUMBER10
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_CATEGORY RES_GLOBAL_ATTRIBUTE_CATEGORY
,SupplierSiteDEO.GLOBAL_ATTRIBUTE1 RES_GLOBAL_ATTRIBUTE1
,SupplierSiteDEO.GLOBAL_ATTRIBUTE2 RES_GLOBAL_ATTRIBUTE2
,SupplierSiteDEO.GLOBAL_ATTRIBUTE3 RES_GLOBAL_ATTRIBUTE3
,SupplierSiteDEO.GLOBAL_ATTRIBUTE4 RES_GLOBAL_ATTRIBUTE4
,SupplierSiteDEO.GLOBAL_ATTRIBUTE5 RES_GLOBAL_ATTRIBUTE5
,SupplierSiteDEO.GLOBAL_ATTRIBUTE6 RES_GLOBAL_ATTRIBUTE6
,SupplierSiteDEO.GLOBAL_ATTRIBUTE7 RES_GLOBAL_ATTRIBUTE7
,SupplierSiteDEO.GLOBAL_ATTRIBUTE8 RES_GLOBAL_ATTRIBUTE8
,SupplierSiteDEO.GLOBAL_ATTRIBUTE9 RES_GLOBAL_ATTRIBUTE9
,SupplierSiteDEO.GLOBAL_ATTRIBUTE10 RES_GLOBAL_ATTRIBUTE10
,SupplierSiteDEO.GLOBAL_ATTRIBUTE11 RES_GLOBAL_ATTRIBUTE11
,SupplierSiteDEO.GLOBAL_ATTRIBUTE12 RES_GLOBAL_ATTRIBUTE12
,SupplierSiteDEO.GLOBAL_ATTRIBUTE13 RES_GLOBAL_ATTRIBUTE13
,SupplierSiteDEO.GLOBAL_ATTRIBUTE14 RES_GLOBAL_ATTRIBUTE14
,SupplierSiteDEO.GLOBAL_ATTRIBUTE15 RES_GLOBAL_ATTRIBUTE15
,SupplierSiteDEO.GLOBAL_ATTRIBUTE16 RES_GLOBAL_ATTRIBUTE16
,SupplierSiteDEO.GLOBAL_ATTRIBUTE17 RES_GLOBAL_ATTRIBUTE17
,SupplierSiteDEO.GLOBAL_ATTRIBUTE18 RES_GLOBAL_ATTRIBUTE18
,SupplierSiteDEO.GLOBAL_ATTRIBUTE19 RES_GLOBAL_ATTRIBUTE19
,SupplierSiteDEO.GLOBAL_ATTRIBUTE20 RES_GLOBAL_ATTRIBUTE20
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE1 RES_GLOBAL_ATTRIBUTE_DATE1
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE2 RES_GLOBAL_ATTRIBUTE_DATE2
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE3 RES_GLOBAL_ATTRIBUTE_DATE3
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE4 RES_GLOBAL_ATTRIBUTE_DATE4
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE5 RES_GLOBAL_ATTRIBUTE_DATE5
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE6 RES_GLOBAL_ATTRIBUTE_DATE6
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE7 RES_GLOBAL_ATTRIBUTE_DATE7
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE8 RES_GLOBAL_ATTRIBUTE_DATE8
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE9 RES_GLOBAL_ATTRIBUTE_DATE9
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_DATE10 RES_GLOBAL_ATTRIBUTE_DATE10
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP1 RES_GLOBAL_ATTRIBUTE_TIMESTAMP
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP2 RES_GLOBAL_ATTRIBUTE_TIMESTA_0
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP3 RES_GLOBAL_ATTRIBUTE_TIMESTA_1
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP4 RES_GLOBAL_ATTRIBUTE_TIMESTA_2
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP5 RES_GLOBAL_ATTRIBUTE_TIMESTA_3
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP6 RES_GLOBAL_ATTRIBUTE_TIMESTA_4
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP7 RES_GLOBAL_ATTRIBUTE_TIMESTA_5
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP8 RES_GLOBAL_ATTRIBUTE_TIMESTA_6
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP9 RES_GLOBAL_ATTRIBUTE_TIMESTA_7
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_TIMESTAMP10 RES_GLOBAL_ATTRIBUTE_TIMESTA_8
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER1 RES_GLOBAL_ATTRIBUTE_NUMBER1
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER2 RES_GLOBAL_ATTRIBUTE_NUMBER2
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER3 RES_GLOBAL_ATTRIBUTE_NUMBER3
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER4 RES_GLOBAL_ATTRIBUTE_NUMBER4
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER5 RES_GLOBAL_ATTRIBUTE_NUMBER5
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER6 RES_GLOBAL_ATTRIBUTE_NUMBER6
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER7 RES_GLOBAL_ATTRIBUTE_NUMBER7
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER8 RES_GLOBAL_ATTRIBUTE_NUMBER8
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER9 RES_GLOBAL_ATTRIBUTE_NUMBER9
,SupplierSiteDEO.GLOBAL_ATTRIBUTE_NUMBER10 RES_GLOBAL_ATTRIBUTE_NUMBER10
,SupplierSiteDEO.PO_ACK_REQD_CODE RES_REQUIRED_ACKNOWLEDGEMENT
,SupplierSiteDEO.PO_ACK_REQD_DAYS RES_ACKNOWLEDGE_WITHIN_DAYS
,NULL RES_BATCH_ID
,'END' RES_END
,SupplierSiteDEO.LAST_UPDATED_BY RSC_LAST_UPDATED_BY
,SupplierSiteDEO.LAST_UPDATE_DATE RSC_LAST_UPDATE_DATE
,SupplierSiteDEO.CREATED_BY RSC_CREATED_BY
,SupplierSiteDEO.CREATION_DATE RSC_CREATION_DATE
,NULL RSC_LEDGER_ID
,NULL RSC_CHART_OF_ACCOUNTS_ID
,SupplierSiteDEO.PRC_BU_ID RSC_BUSINESS_UNIT_ID
,NULL RSC_LEGAL_ENTITY_ID
,NULL RSC_ORGANIZATION_ID
,NULL RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID



FROM POZ_SUPPLIER_SITES_ALL_M SupplierSiteDEO
,AP_TOLERANCE_TEMPLATES ApInvoiceToleranceTemplates
,AP_TOLERANCE_TEMPLATES ApServicesToleranceTemplates
,AP_TERMS_VL ApTermsVl
,WSH_CARRIERS WshCarriers
,HZ_PARTIES PartyPEO
,HZ_PARTY_SITES PartySitePEO
,WSH_LOOKUPS TransportLookupPEO
,WSH_LOOKUPS ServiceLevelLookupPEO
,IBY_EXTERNAL_PAYEES_ALL IbyExternalPayeesAll
WHERE SupplierSiteDEO.PARTY_SITE_ID = PartySitePEO.PARTY_SITE_ID(+)
AND SupplierSiteDEO.PARTY_SITE_ID  = IbyExternalPayeesAll.PARTY_SITE_ID(+)
AND SupplierSiteDEO.VENDOR_SITE_ID = IbyExternalPayeesAll.SUPPLIER_SITE_ID(+)
AND SupplierSiteDEO.TOLERANCE_ID           = ApInvoiceToleranceTemplates.TOLERANCE_ID(+)
AND SupplierSiteDEO.SERVICES_TOLERANCE_ID  = ApServicesToleranceTemplates.TOLERANCE_ID(+)
AND SupplierSiteDEO.TERMS_ID               = ApTermsVl.TERM_ID(+)
AND SupplierSiteDEO.CARRIER_ID             = WshCarriers.CARRIER_ID(+)
AND WshCarriers.CARRIER_ID                 = PartyPEO.PARTY_ID (+)
AND SupplierSiteDEO.MODE_OF_TRANSPORT      = TransportLookupPEO.LOOKUP_CODE(+)
AND TransportLookupPEO.LOOKUP_TYPE(+)      = 'WSH_MODE_OF_TRANSPORT'
AND SupplierSiteDEO.SERVICE_LEVEL          = ServiceLevelLookupPEO.LOOKUP_CODE(+)
AND ServiceLevelLookupPEO.LOOKUP_TYPE(+)   = 'WSH_SERVICE_LEVELS'
AND EXISTS (SELECT 1
	FROM PO_AGENT_ACCESSES PoAgents
	WHERE PoAgents.PRC_BU_ID = SupplierSiteDEO.PRC_BU_ID
	AND PoAgents.access_action_code = 'MANAGE_SUPPLIERS'
	AND PoAgents.active_flag = 'Y'
	AND PoAgents.allowed_flag = 'Y')

AND (IbyExternalPayeesAll.SUPPLIER_SITE_ID IS NOT NULL )
ORDER BY SupplierSiteDEO.VENDOR_SITE_CODE