/* ****************************************************************************
 * $Revision: 55453 $:
 * $Author: dhara.pithadiya $:
 * $Date: 2016-05-25 18:43:01 +0700 (Wed, 25 May 2016) $:
 * $HeadURL: http://svn01.rapidesuite.com:999/svn/a/dev/rapidesuite/controldata/FUSION_11.1.9/trunk/core/reverse_sql/FINANCIALS/Manage%20AutoInvoice%20Line%20Ordering%20Rules%20-%20AutoInvoice%20Line%20Ordering%20Rules.sql $:
 * $Id: Manage AutoInvoice Line Ordering Rules - AutoInvoice Line Ordering Rules.sql 55453 2016-05-25 11:43:01Z dhara.pithadiya $:
 * ****************************************************************************
 * Description:
 * ************************************************************************** */

 
SELECT buE0.BU_NAME RES_BUSINESS_UNIT
,okcBuImplOptionsE0.DEFAULT_CURRENCY_CODE||' - '||(SELECT NAME FROM FND_CURRENCIES_VL WHERE CURRENCY_CODE = okcBuImplOptionsE0.DEFAULT_CURRENCY_CODE) RES_DEFAULT_CURRENCY
,DECODE(okcBuImplOptionsE0.MULTICURRENCY_YN,'Y','Yes','No') RES_ENABLE_MULTICURRENCY
,DECODE(okcBuImplOptionsE0.RELATED_CUST_ALLWD_YN,'Y','Yes','No') RES_ALLOW_RELATED_CUSTOMER_ACC
,(SELECT USER_CONVERSION_TYPE
	FROM GL_DAILY_CONVERSION_TYPES
	WHERE CONVERSION_TYPE = okcBuImplOptionsE0.CON_INV_RATE_TYPE
	) RES_CURRENCY_CONVERSION_CONVER
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_BU_CON_INV_RATE_DATE_TYPE'
	AND LOOKUP_CODE = okcBuImplOptionsE0.CON_INV_RATE_DATE_TYPE
	) RES_CURRENCY_CONVERSION_CONV_0
,TO_CHAR(okcBuImplOptionsE0.CON_INV_RATE_DATE,'DD-Mon-YYYY') RES_CURRENCY_CONVERSION_CONV_1
,(SELECT USER_CONVERSION_TYPE
	FROM GL_DAILY_CONVERSION_TYPES
	WHERE CONVERSION_TYPE = okcBuImplOptionsE0.LGR_INV_RATE_TYPE
	) RES_INVOICE_TRANSACTION_CONVER
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_BU_LGR_INV_RATE_DATE_TYPE'
	AND LOOKUP_CODE = okcBuImplOptionsE0.LGR_INV_RATE_DATE_TYPE
	) RES_INVOICE_TRANSACTION_CONV_2
,(SELECT USER_CONVERSION_TYPE
	FROM GL_DAILY_CONVERSION_TYPES
	WHERE CONVERSION_TYPE = okcBuImplOptionsE0.LGR_REV_RATE_TYPE
	) RES_REVENUE_TRANSACTION_CONVER
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_BU_LGR_REV_RATE_DATE_TYPE'
	AND LOOKUP_CODE = okcBuImplOptionsE0.LGR_REV_RATE_DATE_TYPE
	) RES_REVENUE_TRANSACTION_CONV_3
,DECODE(okcBuImplOptionsE0.INTERFACE_REV_TO_GL_YN,'Y','Yes','No') RES_TRANSFER_REVENUE_TO_GENERA
,DECODE(okcBuImplOptionsE0.CREDIT_MEMO_REASON_YN,'Y','Yes','No') RES_REQUIRE_CREDIT_MEMO_REASON
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_BU_INV_NUMB_METHOD'
	AND LOOKUP_CODE = okcBuImplOptionsE0.CUST_INV_NUMB_METHOD
	) RES_CUSTOMER_BILLING_INVOICE_N
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_BU_INV_NUMB_TYPE'
	AND LOOKUP_CODE = okcBuImplOptionsE0.CUST_INV_NUMB_TYPE
	) RES_CUSTOMER_BILLING_INVOICE_4
,okcBuImplOptionsE0.CUST_INV_NEXT_NUMBER RES_CUSTOMER_BILLING_NEXT_INVO
,(SELECT NAME
	FROM RA_BATCH_SOURCES_ALL
	WHERE BATCH_SOURCE_SEQ_ID = okcBuImplOptionsE0.CUST_INV_BATCH_SRC_ID
	) RES_CUSTOMER_BILLING_INVOICE_B
,DECODE(okcBuImplOptionsE0.TXN_TYPE_REQ_YN,'Y','Yes','No') RES_REQUIRE_MANUAL_ENTRY_OF_TR
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_BU_INV_NUMB_METHOD'
	AND LOOKUP_CODE = okcBuImplOptionsE0.INT_INV_NUMB_METHOD
	) RES_INTERNAL_BILLING_INVOICE_N
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_BU_INV_NUMB_TYPE'
	AND LOOKUP_CODE = okcBuImplOptionsE0.INT_INV_NUMB_TYPE
	) RES_INTERNAL_BILLING_INVOICE_5
,okcBuImplOptionsE0.INT_INV_NEXT_NUMBER RES_INTERNAL_BILLING_NEXT_INVO
,(SELECT NAME
	FROM RA_BATCH_SOURCES_ALL
	WHERE BATCH_SOURCE_SEQ_ID = okcBuImplOptionsE0.INT_INV_BATCH_SRC_ID
	) RES_INTERNAL_BILLING_INVOICE_B
,DECODE(okcBuImplOptionsE0.GLOBAL_BUS_UNIT_YN,'Y','Yes','No') RES_GLOBAL_BUSINESS_UNIT
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_BU_INV_NUMB_METHOD'
	AND LOOKUP_CODE = okcBuImplOptionsE0.CLAUSE_NUMB_METHOD
	) RES_CLAUSE_NUMBERING_METHOD
,(SELECT MEANING
	FROM FND_LOOKUPS
	WHERE LOOKUP_TYPE = 'OKC_NUMBERING_LEVEL'
	AND LOOKUP_CODE = okcBuImplOptionsE0.CLAUSE_NUMB_LEVEL_CODE
	) RES_CLAUSE_NUMBERING_LEVEL
,(SELECT NAME
	FROM FND_DOC_SEQUENCE_CATEGORIES
	WHERE CODE = okcBuImplOptionsE0.CLAUSE_NUMB_SEQ_CAT 
	) RES_CLAUSE_SEQUENCE_CATEGORY
,DECODE(okcBuImplOptionsE0.CC_USE_CONTRACT_EXPERT_YN,'Y','Yes','No') RES_ENABLE_CONTRACT_EXPERT
,DECODE(okcBuImplOptionsE0.CC_AUTO_ADOPT_GL_CLAUS_YN,'Y','Yes','No') RES_AUTOMATICALLY_ADOPT_GLOBAL
,DECODE(okcBuImplOptionsE0.CC_INCL_CLAUSE_NUMB_YN,'Y','Yes','No') RES_DISPLAY_CLAUSE_NUMBER_IN_C
,okcBuImplOptionsE0.CC_CLAUS_LAYOUT_TMPL_ID RES_CLAUSE_LAYOUT_TEMPLATE
,okcBuImplOptionsE0.CC_DEVIAT_LAYOUT_TMPL_ID RES_DEVIATIONS_LAYOUT_TEMPLATE
,(SELECT FULL_NAME 
	FROM PER_PERSON_NAMES_F
	WHERE NAME_TYPE = 'GLOBAL'
	AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
	AND PERSON_ID = okcBuImplOptionsE0.CC_TERMS_LIB_ADMIN_ID
	) RES_TERMS_LIBRARY_ADMINISTRATO
,okcBuImplOptionsE0.LAST_UPDATED_BY  RSC_LAST_UPDATED_BY
,okcBuImplOptionsE0.LAST_UPDATE_DATE  RSC_LAST_UPDATE_DATE
,okcBuImplOptionsE0.CREATED_BY  RSC_CREATED_BY
,okcBuImplOptionsE0.CREATION_DATE  RSC_CREATION_DATE
,null RSC_LEDGER_ID
,null RSC_CHART_OF_ACCOUNTS_ID
,okcBuImplOptionsE0.ORG_ID RSC_BUSINESS_UNIT_ID
,null RSC_LEGAL_ENTITY_ID
,null RSC_ORGANIZATION_ID
,null RSC_BUSINESS_GROUP_ID
,NULL RSC_ENTERPRISE_ID
,NULL RSC_COUNTRY_ID

FROM OKC_BU_IMPL_OPTIONS_ALL okcBuImplOptionsE0
,FUN_ALL_BUSINESS_UNITS_V buE0
WHERE okcBuImplOptionsE0.ORG_ID = buE0.BU_ID
ORDER BY buE0.BU_NAME